enh(release): Add Centreon Web 20.04.19 RN
centreon/centreon-documentation pull request #1029
Opened 2021-09-28 14:23 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-09-28 14:50 UTC, thiuyendang approved these changes

2021-09-30 07:38 UTC, mdebauchez requested changes

2021-09-30 07:38 UTC, mdebauchez commented on fr/releases/centreon-core.md
> +
There is one line break too much

2021-09-30 13:29 UTC, mdebauchez reviewed
There is one line break too much at lign 31 in french

2021-09-30 14:21 UTC, mdebauchez approved these changes

2021-09-30 15:43 UTC, tuntoja requested changes

2021-09-30 15:43 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`September 30, 2021`

```

2021-09-30 15:43 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`September 30, 2021`

```

2021-09-30 15:43 UTC, tuntoja approved these changes

2021-09-30 15:51 UTC, merged