enh(release): Add Centreon Anomaly Detection 21.04.1 RN
centreon/centreon-documentation pull request #1032
Opened 2021-09-29 08:47 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-09-29 09:02 UTC, thiuyendang approved these changes

2021-09-29 09:39 UTC, Nohzoh approved these changes

2021-09-30 15:18 UTC, tuntoja requested changes

2021-09-30 15:18 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

`September 30, 2021`

```

2021-09-30 15:18 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

`September 30, 2021`

```

2021-09-30 15:24 UTC, tuntoja approved these changes

2021-09-30 15:25 UTC, merged