enh(release): Add Centreon Gorgone 21.04.3 RN
centreon/centreon-documentation pull request #1033
Opened 2021-09-29 08:50 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-09-29 09:40 UTC, Nohzoh approved these changes

2021-09-29 09:53 UTC, thiuyendang approved these changes

2021-09-30 14:35 UTC, tuntoja requested changes

2021-09-30 14:35 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`September 30, 2021`

```

2021-09-30 14:35 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`September 30, 2021`

```

2021-09-30 14:42 UTC, merged