enh(release): Add Centreon Web 20.10.12 RN
centreon/centreon-documentation pull request #1035
Opened 2021-09-29 15:45 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-09-29 15:49 UTC, mdebauchez approved these changes

2021-09-30 07:39 UTC, mdebauchez requested changes

2021-09-30 07:39 UTC, mdebauchez commented on fr/releases/centreon-core.md
> +
There is one line break too much

2021-09-30 13:30 UTC, mdebauchez reviewed
There is one line break too much at lign 28 in french

2021-09-30 14:21 UTC, mdebauchez approved these changes

2021-10-05 09:50 UTC, tuntoja requested changes

2021-10-05 09:50 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`October 5, 2021`

```

2021-10-05 09:50 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`October 5, 2021`

```

2021-10-05 09:51 UTC, tuntoja approved these changes

2021-10-05 09:56 UTC, merged