enh(release): Add Centreon Web 21.04.6 RN
centreon/centreon-documentation pull request #1036
Opened 2021-09-29 15:48 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-09-30 07:36 UTC, mdebauchez approved these changes

2021-10-05 09:17 UTC, tuntoja requested changes

2021-10-05 09:17 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`October 5, 2021`

```

2021-10-05 09:17 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`October 5, 2021`

```

2021-10-05 09:22 UTC, tuntoja approved these changes

2021-10-05 09:26 UTC, merged