Prepare web 21.04.8
centreon/centreon-documentation pull request #1063
Opened 2021-10-14 08:49 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-11-09 16:38 UTC, mdebauchez requested changes

2021-11-09 16:38 UTC, mdebauchez commented on en/releases/centreon-core.md
> +- [Resources Status] Fixed wierd behaviord of the ressources status page when applying filters and ordering by a specific column.
'weird behaviors' instead of 'wierd behaviord' I think

2021-11-09 16:38 UTC, mdebauchez commented on fr/releases/centreon-core.md
> +- [Resources Status] Fixed wierd behaviord of the ressources status page when applying filters and ordering by a specific column.
Same comment as in english version

2021-11-09 16:38 UTC, mdebauchez commented on en/releases/centreon-core.md
> +
We don't mention this ticket ? 
https://centreon.atlassian.net/browse/MON-11382

2021-11-15 14:09 UTC, tuntoja requested changes

2021-11-15 14:09 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`Release date: November 15, 2021`

```

2021-11-15 14:09 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`Release date: 15 novembre 2021`

```

2021-11-15 14:09 UTC, tuntoja approved these changes

2021-11-15 14:13 UTC, tuntoja approved these changes

2021-11-15 14:47 UTC, tuntoja approved these changes

2021-11-15 14:47 UTC, tuntoja commented on en/releases/centreon-core.md
> +`Release date: November 15, 2021`
```suggestion
```

2021-11-15 14:47 UTC, tuntoja commented on fr/releases/centreon-core.md
> +`Release date: 15 novembre 2021`
```suggestion
```

2021-11-15 14:51 UTC, cg-tw approved these changes

2021-11-15 14:54 UTC, merged