enh(release): Add Centreon Web 20.10.13
centreon/centreon-documentation pull request #1064
Opened 2021-10-14 08:51 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-11-09 16:41 UTC, mdebauchez approved these changes

2021-11-10 08:59 UTC, tuntoja requested changes

2021-11-10 08:59 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

Release date: 'November 10, 2021'

```

2021-11-10 08:59 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

Release date: '10 novembre 2021'

```

2021-11-10 09:04 UTC, tuntoja commented on en/releases/centreon-core.md
> +
added release date

2021-11-10 09:04 UTC, tuntoja requested changes

2021-11-10 09:04 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
added release date

2021-11-10 09:09 UTC, tuntoja approved these changes

2021-11-10 09:19 UTC, cg-tw requested changes

2021-11-10 09:19 UTC, cg-tw commented on en/releases/centreon-core.md
> +Release date: 'November 10, 2021'
```suggestion
Release date: `November 10, 2021`
```

2021-11-10 09:19 UTC, cg-tw commented on fr/releases/centreon-core.md
> +Release date: '10 novembre 2021'
```suggestion
Release date: `10 novembre 2021`
```

2021-11-10 09:51 UTC, cg-tw requested changes

2021-11-10 09:51 UTC, cg-tw commented on en/releases/centreon-core.md
> +- [CLAPI] Fixed recurrent downtimes exported with CLAPI cannot be imported with CLAPI
```suggestion
- [CLAPI] Fixed recurrent downtimes exported with CLAPI that could not be imported with CLAPI
```

2021-11-10 09:51 UTC, cg-tw commented on en/releases/centreon-core.md
> +- [Configuration] Avoid blocking configuration generation when user don't have notifications enabled
```suggestion
- [Configuration] Avoid blocking configuration generation when users don't have notifications enabled
```

2021-11-10 09:51 UTC, cg-tw commented on en/releases/centreon-core.md
> +- [Configuration] Unwanted empty string parameter for LUA output in Broker configuration
```suggestion
- [Configuration] Fixed unwanted empty string parameter for LUA output in Broker configuration
```

2021-11-10 09:51 UTC, cg-tw commented on en/releases/centreon-core.md
> +- [Custom Views] Can't share views with LDAP groups
```suggestion
- [Custom Views] Couldn't share views with LDAP groups
```

2021-11-15 14:13 UTC, tuntoja approved these changes

2021-11-15 14:22 UTC, tuntoja requested changes

2021-11-15 14:22 UTC, tuntoja commented on en/releases/centreon-core.md
> +- [Discovery] Error message when filling credentials in job as side-effect of a change regarding downtimes
```suggestion
- [Discovery] Fixed an issue causing error messages when filling credentials in a Host Discovery job
```

2021-11-15 14:22 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- [Discovery] Error message when filling credentials in job as side-effect of a change regarding downtimes
```suggestion
- [Discovery] Fixed an issue causing error messages when filling credentials in a Host Discovery job
```

2021-11-15 14:38 UTC, tuntoja approved these changes

2021-11-15 14:38 UTC, tuntoja commented on en/releases/centreon-core.md
> +Release date: `November 10, 2021`
```suggestion
```

2021-11-15 14:48 UTC, tuntoja approved these changes

2021-11-15 14:51 UTC, cg-tw approved these changes

2021-11-15 14:54 UTC, merged