Remove unnecessary parameter
centreon/centreon-documentation pull request #1133
Opened 2021-11-03 10:26 UTC by cg-tw

## Description

Remove unnecessary parameter

## Target serie

- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (master)

2021-11-03 10:33 UTC, zaouchelo submitted a review, later dismissed

2021-11-04 16:19 UTC, lpinsivy approved these changes

2021-11-12 17:02 UTC, chgautier requested changes

2021-11-12 17:02 UTC, chgautier commented on en/graph-views/secure-your-map-platform.md
>  To create self-signed certificate, you can create one using the following commands:
```suggestion
To create a self-signed certificate, you can use the following commands: 
```

2021-11-15 09:43 UTC, chgautier approved these changes

2021-11-15 09:46 UTC, merged