doc(release): add release note for Centreon Autodiscovery 21.04.2
centreon/centreon-documentation pull request #1135
Opened 2021-11-03 13:00 UTC by omercier

## Description

Release notes

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2021-11-03 14:57 UTC, cg-tw requested changes

2021-11-03 14:57 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Improve the way host discovery providers will be identified as compatible
```suggestion
- Improve the way host discovery providers are identified as compatible with the current version of autodiscovery
```
```suggestion
- Improve the way host discovery providers will be identified as compatible
```

2021-11-03 14:57 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Improve the way host discovery providers will be identified as compatible
```suggestion
- Improve the way host discovery providers are identified as compatible with the current version of autodiscovery
```
```suggestion
- Improve the way host discovery providers will be identified as compatible
```

2021-11-03 17:02 UTC, cg-tw approved these changes

2021-11-08 17:12 UTC, thiuyendang approved these changes

2021-11-09 14:28 UTC, tuntoja requested changes

2021-11-09 14:28 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +Release date: `null`
```suggestion
Release date: `September 9, 2021`
```

2021-11-09 14:28 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +Release date: `null`
```suggestion
Release date: `9 septembre 2021`
```

2021-11-09 14:30 UTC, tuntoja requested changes

2021-11-09 14:30 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +Release date: `September 9, 2021`
```suggestion
Release date: `November 9, 2021`
```

2021-11-09 14:30 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +Release date: `9 septembre 2021`
```suggestion
Release date: `9 novembre 2021`
```

2021-11-09 14:32 UTC, tuntoja approved these changes

2021-11-09 14:33 UTC, cg-tw approved these changes

2021-11-09 14:37 UTC, merged