Enh(doc) add doc pp application netbackup ssh
centreon/centreon-documentation pull request #1146
Opened 2021-11-09 21:16 UTC by psamecentreon

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x
- [X] 22.04.x (master)

2021-11-12 15:27 UTC, pkriko requested changes

2021-11-12 15:27 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +The Centreon Plugin Pack includes monitoring of job status, tape usage, drive cleaning, and drvie status using system commands.
```suggestion
The Centreon Plugin Pack includes monitoring of job status, tape usage, drive cleaning, and drive status using system commands.
```

2021-11-12 15:27 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +<!--Dedupstatus -->
```suggestion
<!--Dedup-status -->
```

2021-11-12 15:27 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +<!--Drivecleaning-->
```suggestion
<!--Drive-cleaning-->
```

2021-11-12 15:27 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +<!--Drivestatus-->
```suggestion
<!--Drive-status-->
```

2021-11-12 15:27 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +<!--Jobstatus-->
```suggestion
<!--Job-status-->
```

2021-11-12 15:27 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +| frozen                                    | Jobs in frozen state                   |       |
It's a count too no ?

2021-11-12 15:27 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +<!--Tapeusage-->
```suggestion
<!--Tape-usage-->
```

2021-11-12 15:27 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +uses a SSH backend _sshcli_ (```--ssh-backend='sshcli'```) and it connects to the host _10.30.2.81_ (```--hostname=10.30.2.81```).
Explain the threshold here no ?

2021-11-12 15:27 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +Le Plugin Pack inclue la supervision du statut tâches, l'utilisation des cassets, le nettoyage des devices, et le status des devices
```suggestion
Le Plugin Pack inclut la supervision du statut des tâches, l'utilisation des cassettes, le nettoyage des équipements, et le status des équipements
```

2021-11-12 15:27 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +| usage                                     | Total of tape usage                                     | count |
Same as english review

2021-11-12 15:27 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
> +son mot de passe (```--ssh-password='centreon-password'```) et il se connecte à l'hôte _10.30.2.81_ (```--hostname='10.30.2.81'```).
Explain the threshold

2021-12-13 11:38 UTC, Sims24 approved these changes

2021-12-15 07:52 UTC, Sims24 commented
Replaced by https://github.com/centreon/centreon-documentation/pull/1195

2021-12-15 07:52 UTC, closed without merging