enh(release): add Centreon Web 21.10.1 RN
centreon/centreon-documentation pull request #1169
Opened 2021-11-26 10:16 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x
- [ ] 22.04.x (master)

2021-11-26 11:07 UTC, mdebauchez requested changes

2021-11-26 13:59 UTC, lpinsivy commented on en/releases/centreon-core.md
> +
no this is technical

2021-11-26 14:03 UTC, mdebauchez approved these changes

2021-11-29 14:22 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

Release date: `November 29, 2021`

```

2021-11-29 14:22 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

Release date: `November 29, 2021`

```

2021-11-29 14:24 UTC, chgautier approved these changes

2021-11-29 14:33 UTC, merged