Replace http by https
centreon/centreon-documentation pull request #1172
Opened 2021-11-26 13:57 UTC by cg-tw

## Description

Replace http by https

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2021-11-27 11:05 UTC, thiuyendang requested changes

2021-11-27 11:05 UTC, thiuyendang commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
> +> **NB :** Pour éviter l'ajout du dépôt Centreon sur tous vos serveurs, il est possible instller directement les paquets `https://yum.centreon.com/standard/20.10/el7/stable/noarch/RPMS/centreon-plugi
```suggestion
> **NB :** Pour éviter l'ajout du dépôt Centreon sur tous vos serveurs, il est possible installer directement les paquets `https://yum.centreon.com/standard/20.10/el7/stable/noarch/RPMS/centreon-plugin-Operatingsystems-Linux-Local-20201006-142255.el7.centos.noarch.rpm` et `https://yum.centreon.com/standard/20.10/el7/stable/x86_64/RPMS/centreon-nrpe3-daemon-3.2.1-8.el7.centos.x86_64.rpm` (versions courantes au moment de la rédaction de cette documentation) **mais dans ce cas il ne sera pas possible de les mettre à jour par un `yum update`**.
```

2021-11-29 16:53 UTC, mdebauchez approved these changes

2021-12-02 13:51 UTC, thiuyendang commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
> +> **NB :** Pour éviter l'ajout du dépôt Centreon sur tous vos serveurs, il est possible installer directement les paquets `https://yum.centreon.com/standard/20.10/el7/stable/noarch/RPMS/centreon-plug
```suggestion
> **NB :** Pour éviter l'ajout du dépôt Centreon sur tous vos serveurs, il est possible d'installer directement les paquets `https://yum.centreon.com/standard/20.10/el7/stable/noarch/RPMS/centreon-plugin-Operatingsystems-Linux-Local-20201006-142255.el7.centos.noarch.rpm` et `https://yum.centreon.com/standard/20.10/el7/stable/x86_64/RPMS/centreon-nrpe3-daemon-3.2.1-8.el7.centos.x86_64.rpm` (versions courantes au moment de la rédaction de cette documentation) **mais dans ce cas il ne sera pas possible de les mettre à jour par un `yum update`**.
```

2021-12-02 14:01 UTC, thiuyendang approved these changes

2021-12-03 15:39 UTC, merged