enh(release): Add Centreon Bam 21.10.1
centreon/centreon-documentation pull request #1184
Opened 2021-12-06 17:36 UTC by nmagniezCentreon

## Description

Please include a short resume of the changes and what is the purpose of the PR.

release note BAM 21.10.1

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x
- [ ] 22.04.x (master)

2021-12-06 17:39 UTC, cg-tw approved these changes

2021-12-07 08:10 UTC, mdebauchez approved these changes

2021-12-07 10:29 UTC, tuntoja requested changes

2021-12-07 10:29 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 7, 2021`

```

2021-12-07 10:29 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 7, 2021`

```

2021-12-07 10:29 UTC, tuntoja approved these changes

2021-12-07 10:39 UTC, merged