enh(release): Add Centreon Gorogne 21.10.1
centreon/centreon-documentation pull request #1191
Opened 2021-12-13 15:05 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x
- [ ] 22.04.x (master)

2021-12-13 15:31 UTC, mdebauchez requested changes

2021-12-13 15:31 UTC, mdebauchez commented on en/releases/centreon-core.md
> +- Fixed restart was too long and occasionally reaches the max systemctl timeout
The description used in Release Note field is better I think : 
Gorgone was too long to restart, which could cause the service to reach the systemctl timeout.

2021-12-13 15:31 UTC, mdebauchez commented on fr/releases/centreon-core.md
> +- Fixed restart was too long and occasionally reaches the max systemctl timeout
Same comment as in english version

2021-12-14 13:06 UTC, tuntoja requested changes

2021-12-14 13:06 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

Release date: `December 14, 2021`

```

2021-12-14 13:06 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

Release date: `December 14, 2021`

```

2021-12-14 13:06 UTC, tuntoja approved these changes

2021-12-14 13:08 UTC, merged