enh(release): Add Centreon Web 20.10.15 RN
centreon/centreon-documentation pull request #1207
Opened 2021-12-17 14:55 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2021-12-20 10:45 UTC, mdebauchez approved these changes

2021-12-20 15:38 UTC, cg-tw requested changes

2021-12-20 15:38 UTC, cg-tw commented on en/releases/centreon-core.md
> +- [Configuration] Fixed an issue that prevented from removing the SNMP community (and other fields) from the host form
```suggestion
- [Configuration] Fixed an issue that prevented users from removing the SNMP community (and other fields) from the host form
```

2021-12-20 15:38 UTC, cg-tw commented on fr/releases/centreon-core.md
> +- [Configuration] Fixed an issue that prevented from removing the SNMP community (and other fields) from the host form
```suggestion
- [Configuration] Fixed an issue that prevented users from removing the SNMP community (and other fields) from the host form
```

2021-12-23 16:19 UTC, tuntoja requested changes

2021-12-23 16:19 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

Release date: `December 23, 2021`

```

2021-12-23 16:19 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

Release date: `December 23, 2021`

```

2021-12-23 16:19 UTC, tuntoja approved these changes

2021-12-23 16:20 UTC, cg-tw approved these changes

2021-12-23 16:22 UTC, merged