enh(release): Anomaly 20.04.5 RN
centreon/centreon-documentation pull request #1208
Opened 2021-12-17 15:11 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2021-12-17 16:12 UTC, Nohzoh approved these changes

2021-12-20 10:28 UTC, mdebauchez requested changes
Release note is only in french version, you forgot to add the english version

2021-12-22 13:46 UTC, mdebauchez approved these changes

2022-01-18 09:14 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

`January 18, 2022`

```

2022-01-18 09:14 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

`18 janvier 2022`

```

2022-01-18 09:19 UTC, merged