enh(release): Anomaly 21.04.2 RN
centreon/centreon-documentation pull request #1209
Opened 2021-12-17 15:19 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2021-12-20 10:24 UTC, mdebauchez approved these changes

2021-12-21 15:52 UTC, tuntoja requested changes

2021-12-21 15:52 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 21, 2021`

```

2021-12-21 15:52 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 21, 2021`

```

2021-12-21 15:52 UTC, tuntoja approved these changes

2021-12-22 13:42 UTC, tuntoja requested changes

2021-12-22 13:42 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +Release date: `December 21, 2021`
```suggestion
Release date: `December 22, 2021`
```

2021-12-22 13:42 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +Release date: `December 21, 2021`
```suggestion
Release date: `December 22, 2021`
```

2021-12-22 13:42 UTC, tuntoja approved these changes

2021-12-22 13:51 UTC, merged