enh(release): Anomaly 21.10.1 RN
centreon/centreon-documentation pull request #1210
Opened 2021-12-17 15:21 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x
- [ ] 22.04.x (master)

2021-12-20 10:23 UTC, mdebauchez approved these changes

2021-12-24 12:32 UTC, tuntoja requested changes

2021-12-24 12:32 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 24, 2021`

```

2021-12-24 12:32 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 24, 2021`

```

2021-12-24 12:33 UTC, tuntoja approved these changes

2021-12-24 13:04 UTC, merged