enh(release): add Centreon License Manager 20.10.4 RN
centreon/centreon-documentation pull request #1212
Opened 2021-12-17 15:27 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2021-12-20 10:21 UTC, mdebauchez approved these changes

2021-12-21 18:04 UTC, thiuyendang approved these changes

2022-01-05 08:45 UTC, chgautier requested changes

2022-01-05 08:45 UTC, chgautier commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `January 5, 2022`

```

2022-01-05 08:45 UTC, chgautier commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `January 5, 2022`

```

2022-01-05 08:45 UTC, chgautier approved these changes

2022-01-05 08:46 UTC, merged