enh(release): add Centreon License Manager 21.04.1 RN
centreon/centreon-documentation pull request #1213
Opened 2021-12-17 15:29 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2021-12-20 10:18 UTC, mdebauchez approved these changes

2021-12-21 18:05 UTC, thiuyendang approved these changes

2021-12-30 10:31 UTC, chgautier requested changes

2021-12-30 10:31 UTC, chgautier commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 30, 2021`

```

2021-12-30 10:31 UTC, chgautier commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 30, 2021`

```

2021-12-30 10:31 UTC, chgautier approved these changes

2021-12-30 10:39 UTC, merged