Add a broker known issue broker 21.10
centreon/centreon-documentation pull request #1216
Opened 2021-12-17 16:46 UTC by omercier

## Description

broker known issue

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x
- [ ] 22.04.x (master)

2021-12-17 16:57 UTC, cg-tw requested changes

2021-12-17 16:57 UTC, cg-tw commented on en/resources/known-issues.md
> +| On platforms using BAM module and monitoring tens of thousands of services, after a restart of `cbd` service, an long time can elapse before the data from the monitoring begins to refresh in the We
```suggestion
| On platforms using the BAM module and monitoring tens of thousands of services, after a restart of the `cbd` service, a long time can elapse before the data from the monitoring begins to refresh in the Web interface. From our observations, it takes about 20 minutes for a 50k services platform. **No data is lost, and the latency disappears and won't happen again until the next restart.** | There is no workaround apart from disabling the BAM broker outputs, which would disable the BAM module. This bug is present on all major versions currently supported and should be fixed during January 2022. |
```

2021-12-17 16:57 UTC, cg-tw commented on fr/resources/known-issues.md
> +| Sur des plateformes ayant le module BAM et supervisant plusieurs dizaines de milliers de services, après un redémarrage du service `cbd`, il est possible que les données en provenance de la supervi
```suggestion
| Sur des plateformes ayant le module BAM et supervisant plusieurs dizaines de milliers de services, après un redémarrage du service `cbd`, il est possible que les données en provenance de la supervision mettent plusieurs dizaines de minutes avant de se rafraîchir dans l'interface. D'après nos observations, cela peut prendre 20 minutes pour une plateforme supervisant 50k services. **Aucune donnée n'est perdue, et la latence se résorbe définitivement jusqu'au redémarrage suivant.** | Il n'existe pas de contournement, si ce n'est de désactiver les outputs BAM dans la configuration de broker, ce qui de fait désactive BAM. Ce problème est rencontré sur toutes les versions majeurs actuellement supportées et devrait être corrigé courant janvier 2022. |
```

2021-12-21 08:56 UTC, omercier commented on fr/resources/known-issues.md
> +| Sur des plateformes ayant le module BAM et supervisant plusieurs dizaines de milliers de services, après un redémarrage du service `cbd`, il est possible que les données en provenance de la supervi
```suggestion
| Sur des plateformes ayant le module BAM et supervisant plusieurs dizaines de milliers de services, après un redémarrage du service `cbd`, il est possible que les données en provenance de la supervision mettent plusieurs dizaines de minutes avant de se rafraîchir dans l'interface. D'après nos observations, cela peut prendre 20 minutes pour une plateforme supervisant 50k services. **Aucune donnée n'est perdue, et la latence se résorbe durablement jusqu'au redémarrage suivant.** | Il n'existe pas de contournement, si ce n'est de désactiver les outputs BAM dans la configuration de broker, ce qui revient à désactiver BAM. Ce problème est rencontré sur toutes les versions majeures actuellement supportées et devrait être corrigé courant janvier 2022. |
```

2021-12-21 12:22 UTC, cg-tw approved these changes

2021-12-21 12:22 UTC, merged