fix(ppm): complete 21.04.1 RN
centreon/centreon-documentation pull request #1217
Opened 2021-12-20 08:35 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2021-12-20 13:22 UTC, thiuyendang approved these changes

2021-12-20 15:33 UTC, cg-tw requested changes

2021-12-20 15:33 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Fixed installation of a Plugin Packs behind the legend
```suggestion
- Fixed problem where a Plugin Pack couldn't be installed when it was displayed behind the legend
```

2021-12-20 15:33 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Fixed installation of a Plugin Packs behind the legend
```suggestion
- Fixed problem where a Plugin Pack couldn't be installed when it was displayed behind the legend
```

2022-03-07 14:15 UTC, cg-tw commented
LPI: close PR

2022-03-07 14:15 UTC, closed without merging