enh(doc) add discovery rule for windows NRPE
centreon/centreon-documentation pull request #1220
Opened 2021-12-20 13:31 UTC by cedricmeschin

## Description

Adding NRPE discovery rule for disks on windows

## Target serie

- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (master)

2021-12-20 15:45 UTC, cg-tw requested changes

2021-12-20 15:45 UTC, cg-tw commented on en/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
> +<!--Services-->
```suggestion
**Services**
```

2021-12-20 15:45 UTC, cg-tw commented on en/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
> +<!--DOCUSAURUS_CODE_TABS-->
```suggestion
```

2021-12-20 15:45 UTC, cg-tw commented on en/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
> +<!--END_DOCUSAURUS_CODE_TABS-->
```suggestion
```

2021-12-20 15:45 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
> +<!--DOCUSAURUS_CODE_TABS-->
```suggestion
```

2021-12-20 15:45 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
> +<!--Services-->
```suggestion
**Services**
```

2021-12-20 15:45 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
> +<!--END_DOCUSAURUS_CODE_TABS-->
```suggestion
```

2022-09-06 13:49 UTC, cedricmeschin commented
Refactoring with the new format https://github.com/centreon/centreon-documentation/pull/1796

2022-09-06 13:49 UTC, closed without merging