Update ticketing.md
centreon/centreon-documentation pull request #1235
Opened 2021-12-24 15:01 UTC by Julien-Rozet

## Description

Translations of menus, french words and typo.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x
- [ ] 22.04.x (master)

2022-01-03 17:19 UTC, cg-tw requested changes

2022-01-03 17:19 UTC, cg-tw commented on fr/alerts-notifications/ticketing.md
> +Définissez un titre pour votre widget (par exemple : _Open-Tickets_) et
```suggestion
Définissez un titre pour votre widget (par exemple : **Open-Tickets**) et
```

2022-01-03 17:19 UTC, cg-tw commented on fr/alerts-notifications/ticketing.md
> +-   **Id** : valeur alphanumerique (doit être unique) ;
```suggestion
-   **Id** : valeur alphanumérique (doit être unique) ;
```

2022-05-30 08:52 UTC, Julien-Rozet commented
How to merge this changes to main repo?

2022-05-30 08:59 UTC, cg-tw commented
Hello,
This PR is based on our old file structure and is not compatible with the new one. You will need to create a new PR based on branch "staging".

2022-10-04 13:34 UTC, closed without merging