add(epp): microsens g6 snmp proc
centreon/centreon-documentation pull request #1238
Opened 2021-12-29 10:03 UTC by garnier-quentin

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x
- [X] 22.04.x (master)

2022-01-03 16:16 UTC, cg-tw requested changes

2022-01-03 16:16 UTC, cg-tw commented on en/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +* Fill the **Name**, **Alias** & **IP Address / DNS** fields according to your *Microsens G6 SNMP* server settings
```suggestion
* Fill the **Name**, **Alias** & **IP Address / DNS** fields according to your **Microsens G6 SNMP** server settings
```

2022-01-03 16:16 UTC, cg-tw commented on en/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +* Select the *network-microsens-g6-snmp-custom* template to apply to the Host
```suggestion
* Select the **network-microsens-g6-snmp-custom** template to apply to the Host
```

2022-01-03 16:16 UTC, cg-tw commented on en/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +## How to check in the CLI that the configuration is OK and what are the main options for ?
```suggestion
## How to check in the CLI that the configuration is OK and what are the main options for? 
```

2022-01-03 16:16 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +Centreon vers le serveur Linux supervisé
```suggestion
Centreon vers le serveur Linux supervisé.
```

2022-01-03 16:16 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +1. Installer le Plugin Centreon sur tous les collecteurs Centreon devant superviser des resources **Microsens G6 SNMP**:
```suggestion
1. Installer le Plugin Centreon sur tous les collecteurs Centreon devant superviser des resources **Microsens G6 SNMP** :
```

2022-01-03 16:16 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +1. Installer le Plugin Centreon sur tous les collecteurs Centreon devant superviser des resources **Microsens G6 SNMP**:
```suggestion
1. Installer le Plugin Centreon sur tous les collecteurs Centreon devant superviser des resources **Microsens G6 SNMP** :
```

2022-01-03 16:16 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +2. Sur le serveur Central Centreon, installer le RPM du Pack **Microsens G6 SNMP**:
```suggestion
2. Sur le serveur Central Centreon, installer le RPM du Pack **Microsens G6 SNMP** :
```

2022-01-03 16:16 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +* Complétez les champs **Nom**,**Alias** & **IP Address / DNS** correspondant à votre serveur **Microsens G6 SNMP**.
```suggestion
* Complétez les champs **Nom**, **Alias** & **IP Address / DNS** correspondant à votre serveur **Microsens G6 SNMP**.
```

2022-01-03 16:16 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
> +pour le diagnostique des erreurs commununes des Plugins Centreon.
```suggestion
pour le diagnostic des erreurs communes des Plugins Centreon.
```

2022-01-03 20:29 UTC, Sims24 approved these changes

2022-01-04 08:51 UTC, cg-tw approved these changes

2022-01-04 08:56 UTC, merged