add(epp): dell omem snmp proc
centreon/centreon-documentation pull request #1247
Opened 2022-01-05 14:00 UTC by garnier-quentin

## Description

-

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x
- [X] 22.04.x (master)

2022-01-05 14:08 UTC, lchrdn approved these changes

2022-01-10 20:52 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/hardware-servers-dell-omem-snmp.md
> +    --snmp-community='my-snmp-community' \
some threshold could be great, even reproducing the default it might help to understand the threshold-overload syntax

2022-01-10 20:53 UTC, Sims24 requested changes
inline ⬆️

2022-01-13 12:59 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/hardware-servers-dell-omem-snmp.md
> +    --snmp-community='my-snmp-community' \
we'lle manage the threshold-overload options differently.

2022-01-13 12:59 UTC, Sims24 approved these changes

2022-01-13 13:14 UTC, merged