add(epp): barracuda bma snmp proc
centreon/centreon-documentation pull request #1249
Opened 2022-01-06 09:26 UTC by garnier-quentin

## Description

-

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x
- [X] 22.04.x (master)

2022-01-06 09:35 UTC, lchrdn approved these changes

2022-01-10 20:50 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md
> +    --critical-cpu-load='' \
A value could help.

2022-01-10 20:50 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md
> +
A quick explanation of the threshold value.

2022-01-10 20:51 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md
> +    --warning-cpu-load='' \
See EN review about command line example possible enhancments

2022-01-10 20:51 UTC, Sims24 reviewed
inline

2022-01-13 08:59 UTC, Sims24 requested changes
See comments inline. Thanks!

2022-01-13 13:15 UTC, Sims24 approved these changes

2022-01-13 13:15 UTC, merged