update(epp): office365 management proc
centreon/centreon-documentation pull request #1252
Opened 2022-01-06 15:08 UTC by garnier-quentin

## Description

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x
- [X] 22.04.x (master)

2022-01-06 15:20 UTC, lchrdn submitted a review, later dismissed

2022-01-10 20:47 UTC, Sims24 requested changes

2022-01-10 20:47 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
> +## Prequisites
Still not OK. Missing re ;)

2022-01-13 10:45 UTC, Sims24 approved these changes

2022-01-13 13:11 UTC, merged