Prepare bam 21.04.1
centreon/centreon-documentation pull request #1257
Opened 2022-01-07 17:35 UTC by nmagniezCentreon

## Description

Release Note 21.04.1

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2022-01-10 08:48 UTC, cg-tw requested changes

2022-01-10 08:48 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- ACL: Authorize visualisation on daughter Business Activities even if not part of the same Business View
```suggestion
- ACL: Authorize visualisation on child Business Activities even if not part of the same Business View
```

2022-01-10 08:48 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Fixed the message in popup when deleting "Activités Métiers" (Fr language)
not totally clear

2022-01-10 08:48 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Fixed the relations between BA and escalations are exported in RS engine conf regardless the BA is linked to the RS or not
there are 2 verbs in the sentence

2022-01-10 08:48 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Fixed MBI menu entry is not visible after upgrade from 19.10 to 21.10.0-beta.2 due to BAM module
2 verbs

2022-01-10 08:48 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Fixed the alignment of "required" input text on panel in Add Business Activity panel
in panel + in panel?

2022-01-21 08:52 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +`January 7, 2022`
```suggestion
`January 21, 2022`
```

2022-01-21 08:52 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +`January 7, 2022`
```suggestion
`January 21, 2022`
```

2022-01-21 08:53 UTC, cg-tw requested changes

2022-01-21 08:53 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Fixed the wrong message in popup when deleting "Activités Métiers" (Fr language)
```suggestion
- Fixed the message that appeared in a popup when deleting "Activités Métiers" (Fr language)
```

2022-01-21 08:53 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Fixed the relations between BA and escalations exported in RS engine conf regardless if the BA is linked to the RS or not
```suggestion
- Fixed the relations between BA and escalations exported in RS engine conf regardless of whether the BA is linked to the RS or not
```

2022-01-21 08:53 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Fixed MBI menu entry not visible after upgrade from 19.10 to 21.10.0-beta.2 due to BAM module
```suggestion
- Fixed MBI menu entry that was not visible after upgrade from 19.10 to 21.10.0-beta.2 due to BAM module
```

2022-01-21 08:53 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- ACL: Authorize visualisation on daughter Business Activities even if not part of the same Business View
```suggestion
- ACL: Authorize visualisation on child Business Activities even if not part of the same Business View
```

2022-01-21 08:53 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Fixed the wrong message in popup when deleting "Activités Métiers" (Fr language)
```suggestion
- Fixed the message that appeared in a popup when deleting "Activités Métiers" (Fr language)
```

2022-01-21 08:53 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Fixed the relations between BA and escalations exported in RS engine conf regardless the BA is linked to the RS or not
```suggestion
- Fixed the relations between BA and escalations exported in RS engine conf regardless of whether the BA is linked to the RS or not
```

2022-01-21 08:53 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Fixed MBI menu entry not visible after upgrade from 19.10 to 21.10.0-beta.2 due to BAM module
```suggestion
- Fixed MBI menu entry that was not visible after upgrade from 19.10 to 21.10.0-beta.2 due to BAM module
```

2022-01-21 10:06 UTC, cg-tw approved these changes

2022-01-21 17:53 UTC, merged