enh(release): Add Centreon PPM 20.04.3 RN
centreon/centreon-documentation pull request #1290
Opened 2022-02-02 16:32 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2022-02-03 08:47 UTC, thiuyendang approved these changes

2022-02-04 14:24 UTC, chgautier requested changes

2022-02-04 14:24 UTC, chgautier commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `February 4, 2022`

```

2022-02-04 14:24 UTC, chgautier commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `February 4, 2022`

```

2022-02-04 14:24 UTC, chgautier approved these changes

2022-02-04 14:25 UTC, merged