enh(getting started) - fr monitor first linux host with snmp
centreon/centreon-documentation pull request #1291
Opened 2022-02-04 08:19 UTC by cedricmeschin

## Description

Like new monitoring linux page in english, the same in french

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [X] 21.10.x
- [X] 22.04.x (master)

2022-02-04 11:18 UTC, cg-tw requested changes

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +Dans ce tutoriel, nous partons du principe que votre plate-forme Centreon est installée et fonctionne correctement, et que vous disposez au moins d'une [Centreon IT 100 Edition](IT100.html) qui fourn
```suggestion
Dans ce tutoriel, nous partons du principe que votre plate-forme Centreon est installée et fonctionne correctement, et que vous disposez au moins d'une édition [Centreon IT 100](IT100.html) qui fournit les Plugin Packs Centreon (votre [licence](../administration/licenses.html) est déjà en place).

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +Votre serveur sera supervisé à l'aide de [Linux SNMP Plugin Pack](../integrations/plugin-packs/procedures/operatingsystems-linux-snmp.html). (Plus d'informations sur les Plugin Packs [here](../monito
```suggestion
Votre serveur sera supervisé à l'aide du Plugin Pack [Linux SNMP](../integrations/plugin-packs/procedures/operatingsystems-linux-snmp.html). (Plus d'informations sur les Plugin Packs [ici](../monitoring/pluginpacks.html)). 

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +## Pré-requis
```suggestion
## Prérequis

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +### sur le serveur Linux que vous souhaiter superviser
```suggestion
### Sur le serveur Linux que vous souhaiter superviser

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +La première étape consiste à activer et à configurer l'agent SNMP sur votre hôte à superviser.
```suggestion
La première étape consiste à activer et à configurer l'agent SNMP sur l'hôte à superviser.

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +Trouvez ci-dessous un fichier de configuration minimaliste de snmpd.conf/net-snmp :
```suggestion
Trouvez ci-dessous un fichier de configuration **snmpd.conf/net-snmp** minimaliste :

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +  - remplacez **my-snmp-community** par la valeur correcte pour votre environnement.
```suggestion
  - Remplacez **my-snmp-community** par la valeur correspondant à votre environnement.

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +  - Ajouter la ligne **view centreon included .1.3.6.1** pour avoir accès à toutes les informations de la MIB requises par le plugin
```suggestion
  - Ajoutez la ligne **view centreon included .1.3.6.1** pour avoir accès à toutes les informations de la MIB requises par le plugin

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +1. Connectez-vous à votre collecteur en SSH et installez le plugin SNMP Linux (voir la [procédure de surveillance pour le **Linux SNMP** Plugin Pack](../integrations/plugin-packs/procédures/operating
```suggestion
1. Connectez-vous à votre collecteur en SSH et installez le plugin SNMP Linux (voir la [procédure de surveillance pour le Plugin Pack **Linux SNMP**](../integrations/plugin-packs/procédures/operatingsystems-linux-snmp.html) pour plus d'informations) :

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +2. Dans l'interface web, allez dans **Configuration > Plugin Packs** et installez le Plugin Pack **Linux SNMP** :
```suggestion
2. Dans l'interface web, allez à la page **Configuration > Plugin Packs** et installez le Plugin Pack **Linux SNMP** :

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +1. Allez dans **Configuration > Hôtes > Hôtes** et cliquez sur **Ajouter** :
```suggestion
1. Allez à la page **Configuration > Hôtes > Hôtes** et cliquez sur **Ajouter** :

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +   * Sélectionner le collecteur approprié (laissez "Central" si vous n'avez pas d'autre collecteur) (5)
```suggestion
   * Sélectionnez le collecteur désiré (laissez **Central** si vous n'avez pas d'autre collecteur) (5)

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +   * L'adresse IP (3)
```suggestion
   * L'adresse IP du serveur (3)

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +4. Cliquez sur **Sauvegarderve** (8). Votre équipement a été ajouté à la liste des hôtes :
```suggestion
4. Cliquez sur **Sauvegarder** (8). Votre équipement a été ajouté à la liste des hôtes :

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +5. Allez dans **Configuration > Services > Services par hôte**. Un ensemble d'indicateurs a été créé automatiquement.
```suggestion
5. Allez à la page **Configuration > Services > Services par hôte**. Un ensemble d'indicateurs a été créé automatiquement.

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +   Vous pouvez également utiliser le raccourci situé à côté du nom de l'hôte pour accéder directement à **Configuration > Services > Services par hôte**. La liste sera filtrée par le nom de l'hôte :
```suggestion
   Vous pouvez également utiliser le raccourci situé à côté du nom de l'hôte pour accéder directement à la page **Configuration > Services > Services par hôte**. La liste sera filtrée par le nom de l'hôte :

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +6. [Déployer la configuration](first-supervision#deploying-a-configuration).
```suggestion
6. [Déployez la configuration](first-supervision#deploying-a-configuration).

```

2022-02-04 11:18 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +7. Allez dans **Surveillance > Statut des ressources** et sélectionnez **Toutes** dans le filtre **Statut des ressources**. Dans un premier temps, les ressources apparaissent avec le statut **En atte
```suggestion
7. Allez à la page **Surveillance > Statut des ressources** et sélectionnez **Toutes** dans le filtre **Statut des ressources**. Dans un premier temps, les ressources apparaissent avec le statut **En attente**, ce qui signifie qu'aucun contrôle n'a encore été exécuté :

```

2022-02-07 07:23 UTC, pkriko submitted a review, later dismissed

2022-02-07 08:57 UTC, cg-tw requested changes

2022-02-07 08:57 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +title: Supervise ton premier serveur Linux
```suggestion
title: Superviser un serveur Linux

```

2022-02-07 09:21 UTC, cg-tw requested changes

2022-02-07 09:21 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +Trouvez ci-dessous un fichier de configuration snmpd.conf/net-snmp minimaliste :
```suggestion
Voici ci-dessous un fichier de configuration snmpd.conf/net-snmp minimaliste :

```

2022-02-07 09:23 UTC, cg-tw requested changes

2022-02-07 09:23 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +1. Connectez-vous à votre collecteur en SSH et installez le plugin SNMP Linux (voir la [procédure de surveillance pour le Plugin Pack **Linux SNMP**](../integrations/plugin-packs/procédures/operating
```suggestion
1. Connectez-vous à votre collecteur en SSH et installez le plugin SNMP Linux (voir la [procédure de surveillance pour le Plugin Pack **Linux SNMP**](../integrations/plugin-packs/procedures/operatingsystems-linux-snmp.html) pour plus d'informations) :

```

2022-02-07 11:14 UTC, cg-tw approved these changes

2022-02-08 11:44 UTC, cg-tw requested changes

2022-02-08 11:44 UTC, cg-tw commented on fr/getting-started/monitor-linux-server-with-snmp.md
> +6. [Déployez la configuration](first-supervision#deploying-a-configuration).
```suggestion
6. [Déployez la configuration](first-supervision#deployer-une-configuration).

```

2022-02-16 10:39 UTC, cg-tw approved these changes

2022-02-17 06:18 UTC, pkriko approved these changes

2022-02-24 12:36 UTC, cg-tw commented
closed by https://github.com/centreon/centreon-documentation/pull/1323

2022-02-24 12:36 UTC, closed without merging