enh(release): Add Centreon Web 21.04.11 RN
centreon/centreon-documentation pull request #1292
Opened 2022-02-04 10:18 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

2022-02-09 18:12 UTC, thiuyendang commented on en/releases/centreon-core.md
> +- [UX] Add TheWatch url to Centreon footer
```suggestion
- [UX] Add The Watch url to Centreon footer
```

2022-02-09 18:12 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +- [UX] Add TheWatch url to Centreon footer
```suggestion
- [UX] Add The Watch url to Centreon footer
```

2022-02-09 18:15 UTC, thiuyendang approved these changes

2022-02-10 08:44 UTC, chgautier requested changes

2022-02-10 08:44 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

Release date: `February 10, 2022`

```

2022-02-10 08:44 UTC, chgautier commented on en/releases/centreon-core.md
> +- [Configuration] Wizard doesn't insert anymore old logger configuration
```suggestion
- [Configuration] Wizard doesn't insert old logger configuration anymore
```

2022-02-10 08:44 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

Release date: `February 10, 2022`

```

2022-02-10 08:44 UTC, chgautier commented on fr/releases/centreon-core.md
> +- [Configuration] Wizard doesn't insert anymore old logger configuration
```suggestion
- [Configuration] Wizard doesn't insert old logger configuration anymore
```

2022-02-10 08:45 UTC, chgautier approved these changes

2022-02-10 08:45 UTC, merged