add(epp): prerequisites documenation for Azure monitoring
centreon/centreon-documentation pull request #1293
Opened 2022-02-07 17:04 UTC by lchrdn

## Description

Adding a new documentation describing how to get tokens for setting up Azure monitoring. 

This procedure aims to be part of each "Prerequisites" part of any Azure Plugin Pack documentation to ease update management. 

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x
- [X] 22.04.x (master)

2022-02-11 16:53 UTC, itoussies requested changes

2022-02-11 16:53 UTC, itoussies commented on en/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +These 4 tokens will be mandatory when using host autodiscovery and Centreon Azure based plugins.
```suggestion
These 4 tokens will be mandatory when using host autodiscovery and Centreon Azure based Plugins. 
```

2022-02-11 16:53 UTC, itoussies commented on en/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +	- Next to the name of your subscription you have the **Subscription ID**.
```suggestion
* Get the **subscription ID**:
	- Go to **Subscriptions** in Azure portal. 
	- Copy the *Subscription ID* next to the name of your subscription.
```

2022-02-11 16:53 UTC, itoussies commented on en/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +	- In **Overview**, under the name of the directory you will see the **Tenant ID**.
```suggestion
* Get the **Tenant ID**:
	- Go to **Azure Active Directory**.
	- Go to **Overview** and copy the *Tenant ID*.
```

2022-02-11 16:53 UTC, itoussies commented on en/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +	- In the **Overview** panel you will have **Application (client) ID**.
```suggestion
* Get the **Client ID**:
	- Go to **Azure Active Directory**.
	- Go to **App registrations** in the sidebars on the left and click on your application.
	- Go to **Overview** and copy the *Application (client) ID*.
```

2022-02-11 16:53 UTC, itoussies commented on en/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +*These steps are not required if you can use Azure API.*
Maybe we can put this sentence in a warning format
```suggestion
> These steps are not required if you can use Azure Monitor API.
```

2022-02-11 16:53 UTC, itoussies commented on en/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +	*and enter the code CWT4WQZAD to authenticate.*
```suggestion
```text
To sign in, use a web browser to open the page https://microsoft.com/devicelogin
and enter the code CWT4WQZAD to authenticate.*
```
```

2022-02-15 07:37 UTC, Sims24 commented on en/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +For Centreon to be able to request information about Azure resources through **Azure API**, 4 tokens are needed:
double "are"

2022-02-15 07:57 UTC, itoussies commented on en/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +For Centreon to be able to request information about Azure resources through **Azure API**, 4 tokens are needed:
Fixed

2022-02-25 16:49 UTC, itoussies approved these changes

2022-03-07 14:48 UTC, cg-tw commented
Closed by https://github.com/centreon/centreon-documentation/pull/1342

2022-03-07 14:48 UTC, closed without merging