enh(release): Add Centreon Gorogne v21.10.2 & 21.04.5 RN
centreon/centreon-documentation pull request #1304
Opened 2022-02-15 15:32 UTC by lpinsivy

## Description

- Add Gorgone 21.10.2 RN
- Fix Gorgone 21.10.0 RN
- Add Gorgone 21.04.5 RN
- Fix Gorgone 21.04.2 RN

## Target version

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (next)

2022-02-16 16:27 UTC, cg-tw requested changes

2022-02-16 16:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- Fixed uninitialized values in Gorgone could cause error log messages.
```suggestion
- Fixed uninitialized values in Gorgone that could cause error log messages.
```

2022-02-16 16:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- Fixed an issue that prevented Gorgone from handling advanced [Service Discovery features](https://docs.centreon.com/fr/docs/21.04/monitoring/discovery/services-discovery#options-avanc%C3%A9es) corr
```suggestion
- Fixed an issue that prevented Gorgone from handling advanced [Service Discovery features](../monitoring/discovery/services-discovery#options-avanc%C3%A9es) correctly.
```

2022-02-16 16:27 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Fixed an issue that prevented Gorgone from handling advanced [Service Discovery features](http://localhost:3000/docs/monitoring/discovery/services-discovery#advanced-options) correctly.
```suggestion
- Fixed an issue that prevented Gorgone from handling advanced [Service Discovery features](../monitoring/discovery/services-discovery#advanced-options) correctly.
```

2022-02-16 16:27 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Fixed uninitialized values in Gorgone could cause error log messages.
```suggestion
- Fixed uninitialized values in Gorgone that could cause error log messages.
```

2022-02-16 16:27 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- Fixed an issue that prevented Gorgone from handling advanced [Service Discovery features](http://localhost:3000/docs/21.04/monitoring/discovery/services-discovery#advanced-options) correctly.
```suggestion
- Fixed an issue that prevented Gorgone from handling advanced [Service Discovery features](../monitoring/discovery/services-discovery#advanced-options) correctly.
```

2022-02-16 16:27 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- Fixed uninitialized values in Gorgone could cause error log messages.
```suggestion
- Fixed uninitialized values in Gorgone that could cause error log messages.
```

2022-02-16 16:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- Fixed an issue that prevented Gorgone from handling advanced [Service Discovery features](https://docs.centreon.com/fr/docs/monitoring/discovery/services-discovery#options-avanc%C3%A9es) correctly.
```suggestion
- Fixed an issue that prevented Gorgone from handling advanced [Service Discovery features](../monitoring/discovery/services-discovery#options-avanc%C3%A9es) correctly.
```

2022-02-16 16:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- Fixed uninitialized values in Gorgone could cause error log messages.
```suggestion
- Fixed uninitialized values in Gorgone that could cause error log messages.
```

2022-02-16 17:51 UTC, cg-tw approved these changes

2022-02-16 18:01 UTC, thiuyendang submitted a review, later dismissed

2022-02-17 08:49 UTC, chgautier requested changes

2022-02-17 08:49 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `February 17, 2022`

```

2022-02-17 08:49 UTC, chgautier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +
```suggestion

Release date: `February 17, 2022`

```

2022-02-17 08:49 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `February 17, 2022`

```

2022-02-17 08:49 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +
```suggestion

Release date: `February 17, 2022`

```

2022-02-17 08:54 UTC, chgautier approved these changes

2022-02-17 10:04 UTC, merged