feat(pack): monitor-your-first-windows-server-with-snmp-v3
centreon/centreon-documentation pull request #1309
Opened 2022-02-17 07:33 UTC by jeanrenemoyap

## Description

Monitor your first host windows  with SNMP

## Target version

- [ ] 20.10.x
- [ ] 21.04.x
- [X] 21.10.x
- [ X] 22.04.x (next)

2022-02-17 10:24 UTC, cg-tw requested changes

2022-02-23 09:25 UTC, pkriko requested changes

2022-02-24 12:13 UTC, jeanrenemoyap commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/getting-started/monitor-windows-server-with-snmp.md
> +	![image](../assets/getting-started/prise_en_main_windows_snmp_1777.png)
yes, it was

2022-02-24 12:24 UTC, cg-tw requested changes

2022-02-24 14:46 UTC, jeanrenemoyap commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/getting-started/monitor-windows-server-with-snmp.md
> +Dans la barre de recherche, tapez **services.msc** et appuyez sur **Entrée** pour lancer le panneau Services.
lancer le panneau des Services

2022-02-28 15:48 UTC, pkriko submitted a review, later dismissed

2022-02-28 15:49 UTC, cg-tw submitted a review, later dismissed

2022-02-28 16:02 UTC, cg-tw submitted a review, later dismissed

2022-02-28 16:04 UTC, pkriko approved these changes

2022-03-02 15:18 UTC, cg-tw approved these changes

2022-03-02 15:19 UTC, pkriko approved these changes

2022-03-02 15:20 UTC, merged