enh(release): Add Centreon Web 21.10.4 RN
centreon/centreon-documentation pull request #1337
Opened 2022-02-28 09:19 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (next)

2022-02-28 19:38 UTC, mdebauchez submitted a review, later dismissed
Is it done on purpose not to have put the ticket 10863 : Fixed SQL errors in upgrade process from Centreon version < 2.8.5 ?

2022-03-01 08:20 UTC, mdebauchez approved these changes

2022-03-01 09:37 UTC, cg-tw requested changes

2022-03-01 14:27 UTC, mdebauchez requested changes

2022-03-01 14:27 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Administration] Improve LDAP authentication and authorization
In the RN of web 21.04.12, you put [Authentication]

2022-03-01 17:58 UTC, cg-tw approved these changes

2022-03-02 09:57 UTC, cg-tw approved these changes

2022-03-02 16:41 UTC, merged