enh(release): Add Centreon Web 21.04.12 RN
centreon/centreon-documentation pull request #1338
Opened 2022-02-28 09:41 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (next)

2022-03-01 14:31 UTC, mdebauchez approved these changes

2022-03-11 12:53 UTC, cg-tw requested changes

2022-03-11 12:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Knowledge Base] Fixed llinks to knowledge base
```suggestion
- [Knowledge Base] Fixed links to knowledge base
```

2022-03-11 12:53 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Knowledge Base] Fixed llinks to knowledge base
```suggestion
- [Knowledge Base] Fixed links to knowledge base
```

2022-03-16 15:58 UTC, cg-tw submitted a review, later dismissed

2022-03-16 16:01 UTC, thiuyendang approved these changes

2022-03-16 16:02 UTC, mdebauchez submitted a review, later dismissed

2022-03-16 16:32 UTC, chgautier commented
@lpinsivy The ACL security fixes were already included in the release branch
MON-12498, MON-12499, MON-12500 and MON-12501. Could you add them in the release notes?

2022-03-16 19:35 UTC, merged