add(epp) : prerequisites for Azure monitoring in docv2 format
centreon/centreon-documentation pull request #1342
Opened 2022-02-28 16:23 UTC by lchrdn

## Description

Adding a new documentation describing how to get tokens for setting up Azure monitoring.

This procedure aims to be part of each "Prerequisites" part of any Azure Plugin Pack documentation to ease update management.

[DOCV1 previous PR that was approved ](https://github.com/centreon/centreon-documentation/pull/1293)

## Target version

- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (next)

2022-02-28 16:53 UTC, itoussies requested changes

2022-02-28 16:53 UTC, itoussies commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +[Découverte d'hôtes](../../../monitoring/discovery/hosts-discovery.md)
```suggestion
[Découverte d'hôtes](../../../monitoring/discovery/hosts-discovery)
```

2022-02-28 16:53 UTC, itoussies commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +[Découverte d'hôtes](../../../monitoring/discovery/hosts-discovery.md)
```suggestion
[Découverte d'hôtes](../../../monitoring/discovery/hosts-discovery)
```

2022-02-28 16:53 UTC, itoussies commented on versioned_docs/version-20.04/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +[Host Discovery](../../../monitoring/discovery/hosts-discovery.md)
```suggestion
[Host Discovery](../../../monitoring/discovery/hosts-discovery)
```

2022-02-28 16:53 UTC, itoussies commented on versioned_docs/version-21.04/integrations/plugin-packs/tutorials/azure-credential-configuration.md
> +[Host Discovery](../../../monitoring/discovery/hosts-discovery.md)
```suggestion
[Host Discovery](../../../monitoring/discovery/hosts-discovery)
```

2022-02-28 17:10 UTC, itoussies approved these changes

2022-03-14 14:10 UTC, Sims24 approved these changes

2022-03-28 15:49 UTC, closed without merging

2022-03-28 15:50 UTC, lchrdn commented
Outdated PR from before PP migration.
New PR https://github.com/centreon/centreon-documentation/pull/1425