doc(release): add release note for centreon-broker-20.10.12
centreon/centreon-documentation pull request #1366
Opened 2022-03-03 20:06 UTC by omercier

## Description

RN 20.10.12

## Target version

- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x

PRs for version 22.04 must be done on branch "next".

2022-03-04 09:09 UTC, cg-tw approved these changes

2022-03-10 10:17 UTC, chgautier requested changes

2022-03-10 10:17 UTC, chgautier commented on versioned_docs/version-20.10/releases/centreon-core.md
> +Release date: `null`
```suggestion
Release date: `March 10, 2022`
```

2022-03-10 10:17 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +Release date: `null`
```suggestion
Release date: `March 10, 2022`
```

2022-03-10 10:17 UTC, chgautier submitted a review, later dismissed

2022-03-10 10:36 UTC, cg-tw approved these changes

2022-03-10 12:23 UTC, cg-tw requested changes

2022-03-10 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +### 20.10.12
```suggestion
### 20.10.12
```

2022-03-10 12:23 UTC, cg-tw commented on versioned_docs/version-20.10/releases/centreon-core.md
> +### 20.10.12
```suggestion
### 20.10.12
```

2022-03-10 12:29 UTC, chgautier approved these changes

2022-03-10 13:27 UTC, merged