add(epp): hyper-v nscp api staging
centreon/centreon-documentation pull request #1375
Opened 2022-03-08 13:11 UTC by garnier-quentin

## Description

## Target version

- [X] 20.10.x (staging)
- [X] 21.04.x (staging)
- [X] 21.10.x (staging)
- [ ] 22.04.x (next)

2022-03-08 13:47 UTC, lchrdn commented on versioned_docs/version-20.04/integrations/plugin-packs/procedures/virtualization-hyperv-nscp-restapi.md
> +All available options for a given mode can be displayed by adding the
```suggestion
All available modes can be displayed by adding the 
```

2022-03-08 13:48 UTC, lchrdn commented on versioned_docs/version-20.10/integrations/plugin-packs/procedures/virtualization-hyperv-nscp-restapi.md
> +All available options for a given mode can be displayed by adding the
```suggestion
All available modes can be displayed by adding the 
```

2022-03-08 13:49 UTC, lchrdn commented on versioned_docs/version-21.04/integrations/plugin-packs/procedures/virtualization-hyperv-nscp-restapi.md
> +All available options for a given mode can be displayed by adding the
```suggestion
All available modes can be displayed by adding the 
```

2022-03-08 13:50 UTC, lchrdn commented on versioned_docs/version-21.10/integrations/plugin-packs/procedures/virtualization-hyperv-nscp-restapi.md
> +All available options for a given mode can be displayed by adding the
```suggestion
All available modes can be displayed by adding the 
```

2022-03-08 14:14 UTC, lchrdn commented
I think you have to add your new documentation name in the sidebars for each version (fr and en), for example here https://github.com/centreon/centreon-documentation/blob/staging/versioned_sidebars/version-21.10-sidebars.json#L3296

2022-03-14 13:23 UTC, Sims24 requested changes
Missing sidebar update

2022-03-21 07:56 UTC, lchrdn approved these changes

2022-04-12 16:23 UTC, Sims24 commented
Changes will be applied in another PR

2022-04-12 16:23 UTC, closed without merging