enh(release): Add Centreon Web 21.10.5 RN
centreon/centreon-documentation pull request #1397
Opened 2022-03-16 16:17 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [x] 21.10.x (staging)
- [ ] 22.04.x (next)

2022-03-18 09:11 UTC, mdebauchez submitted a review, later dismissed

2022-03-21 10:46 UTC, chgautier requested changes

2022-03-21 10:46 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Administration] SQL Injections on Knowledge Base configuration form
```suggestion
- [Administration] SQL Injection on Knowledge Base configuration form
```

2022-03-21 10:46 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Administration] SQL Injections on Knowledge Base configuration form
MON-12512 is the only ticket for the KB

2022-03-21 10:46 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Administration] SQL Injections on Knowledge Base configuration form
```suggestion
- [Administration] SQL Injection on Knowledge Base configuration form
```

2022-03-21 13:29 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `March 21, 2022`

```

2022-03-21 13:29 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `March 21, 2022`

```

2022-03-21 14:56 UTC, merged