enh(connectors): complete connector documentation for future release
centreon/centreon-documentation pull request #1411
Opened 2022-03-23 13:44 UTC by omercier

## Description

Completing connectors documentation

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (next)

2022-03-23 13:56 UTC, chgautier requested changes

2022-03-23 13:56 UTC, chgautier commented on versioned_docs/version-22.04/monitoring/basic-objects/commands.md
> +    connector_line /usr/bin/centreon-connector/centreon_connector_ssh --log-file=/var/log/centreon-engine/centreon-connector-ssh.log
```suggestion
    connector_line /usr/lib64/centreon-connector/centreon_connector_ssh --log-file=/var/log/centreon-engine/centreon-connector-ssh.log
```

2022-03-23 13:56 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/basic-objects/commands.md
> +    connector_line /usr/bin/centreon-connector/centreon_connector_ssh --log-file=/var/log/centreon-engine/centreon-connector-ssh.log
```suggestion
    connector_line /usr/lib64/centreon-connector/centreon_connector_ssh --log-file=/var/log/centreon-engine/centreon-connector-ssh.log
```

2022-04-05 07:41 UTC, chgautier approved these changes

2022-04-05 15:01 UTC, omercier commented on versioned_docs/version-22.04/monitoring/basic-objects/commands.md
> +Here are the supported arguments for `centreon_connector_perl`:
```suggestion
Here are the supported arguments for `centreon_connector_ssh`:
```

2022-04-06 09:48 UTC, merged