enh(release): Add Centreon Web 20.10.16 RN
centreon/centreon-documentation pull request #1412
Opened 2022-03-23 14:48 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [x] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (next)

2022-03-24 11:00 UTC, cg-tw requested changes

2022-03-24 11:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +- [UX] Add TheWatch url to Centreon footer
```suggestion
- [UX] Add TheWatch URL to Centreon footer
```

2022-03-24 11:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +- [Resources Status] Fixed the display of old downtimes in the details tab
```suggestion
- [Resources Status] Fixed the display of old downtimes in the Details tab
```

2022-03-24 11:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +- [Administration] SQL Injection on Knowledge Base configuration form
```suggestion
- [Administration] SQL injection on Knowledge Base configuration form
```

2022-03-24 11:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +- [Configuration] SQL Injections on SNMP traps edition form
```suggestion
- [Configuration] SQL injections on SNMP traps edition form
```

2022-03-24 11:00 UTC, cg-tw commented on versioned_docs/version-20.10/releases/centreon-core.md
> +- [UX] Add TheWatch url to Centreon footer
```suggestion
- [UX] Add TheWatch URL to Centreon footer
```

2022-03-24 11:00 UTC, cg-tw commented on versioned_docs/version-20.10/releases/centreon-core.md
> +- [Administration] SQL Injection on Knowledge Base configuration form
```suggestion
- [Administration] SQL injection on Knowledge Base configuration form
```

2022-03-24 11:00 UTC, cg-tw commented on versioned_docs/version-20.10/releases/centreon-core.md
> +- [Administration] SQL Injections on ACL group listing
```suggestion
- [Administration] SQL injections on ACL group listing
```

2022-03-24 11:00 UTC, cg-tw commented on versioned_docs/version-20.10/releases/centreon-core.md
> +- [Administration] SQL Injections on LDAP listing
```suggestion
- [Administration] SQL injections on LDAP listing
```

2022-04-01 15:08 UTC, tuntoja commented
duplicated with https://github.com/centreon/centreon-documentation/pull/1430

2022-04-01 15:08 UTC, closed without merging