enh(release): Add Centreon Web 21.04.13 RN
centreon/centreon-documentation pull request #1413
Opened 2022-03-23 14:53 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [x] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (next)

2022-03-24 10:56 UTC, cg-tw requested changes

2022-03-24 10:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Chart] Fixed a PHP warning and removed a debug text appearing at the bottom of the page when modifying a curve template in "Monitoring  >  Performances  >  Curves"
```suggestion
- [Chart] Fixed a PHP warning and removed a debug text appearing at the bottom of the page when modifying a curve template in "Monitoring > Performances > Curves"
```

2022-03-24 10:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [UX] When the user does not have the "Action access" rights for the top counter, when he connects then he gets the top counter "skeleton style"
```suggestion
- [UX] When users did not have the "Action access" rights for the top counter, the top counter was displayed "skeleton style". This has been fixed.
```

2022-03-24 10:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Administration] SQL Injections on ACL group listing
```suggestion
- [Administration] SQL injections on ACL group listing
```

2022-03-24 10:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Administration] SQL Injection on Knowledge Base configuration form
```suggestion
- [Administration] SQL injection on Knowledge Base configuration form
```

2022-03-24 10:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Administration] SQL Injections on LDAP listing
```suggestion
- [Administration] SQL injections on LDAP listing
```

2022-03-24 10:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Configuration] SQL Injection on export configuration
```suggestion
- [Configuration] SQL injection on export configuration
```

2022-03-24 10:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Configuration] SQL Injections on SNMP traps edition form
```suggestion
- [Configuration] SQL injections on SNMP traps edition form
```

2022-03-24 10:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Monitoring] SQL Injection on performance curve edition form
```suggestion
- [Monitoring] SQL injection on performance curve edition form
```

2022-03-24 10:56 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Chart] Fixed a PHP warning and removed a debug text appearing at the bottom of the page when modifying a curve template in "Monitoring  >  Performances  >  Curves"
```suggestion
- [Chart] Fixed a PHP warning and removed a debug text appearing at the bottom of the page when modifying a curve template in "Monitoring > Performances > Curves"
```

2022-03-24 10:56 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [UX] When the user does not have the "Action access" rights for the top counter, when he connects then he gets the top counter "skeleton style"
```suggestion
- [UX] When users did not have the "Action access" rights for the top counter, the top counter was displayed "skeleton style". This has been fixed.
```

2022-03-24 10:56 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Administration] SQL Injections on ACL group listing
```suggestion
- [Administration] SQL injections on ACL group listing
```

2022-03-24 10:56 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Administration] SQL Injection on Knowledge Base configuration form
```suggestion
- [Administration] SQL injection on Knowledge Base configuration form
```

2022-03-24 10:56 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Administration] SQL Injections on LDAP listing
```suggestion
- [Administration] SQL injections on LDAP listing
```

2022-03-24 10:56 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Configuration] SQL Injection on export configuration
```suggestion
- [Configuration] SQL injection on export configuration
```

2022-03-24 10:56 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Configuration] SQL Injections on SNMP traps edition form
```suggestion
- [Configuration] SQL injections on SNMP traps edition form
```

2022-03-24 10:56 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Monitoring] SQL Injection on performance curve edition form
```suggestion
- [Monitoring] SQL injection on performance curve edition form
```

2022-03-31 08:06 UTC, tuntoja commented
another PR (same content) was opened here to avoid waiting for the RFC on PR #1413 
https://github.com/centreon/centreon-documentation/pull/1429

2022-03-31 08:06 UTC, closed without merging