doc(release): add release note for centreon-autodiscovery-21.04.4
centreon/centreon-documentation pull request #1416
Opened 2022-03-24 09:47 UTC by omercier

## Description

RN for centreon-autodiscovery-21.04.4

## Target version

- [ ] 20.10.x (staging)
- [x] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (next)

2022-03-24 10:34 UTC, cg-tw requested changes

2022-03-24 10:34 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md
> +- Changed the size of a column to allow storing host discovery provider coming from Plugin Packs with names > 50 characters.
```suggestion
- Changed the size of a column to allow storing host discovery providers coming from Plugin Packs with names exceeding 50 characters
```

2022-03-24 10:34 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md
> +- ACL were not updated for items discovered by Host Discovery or Service Discovery.
```suggestion
- ACLs were not updated for items discovered by Host Discovery or Service Discovery
```

2022-03-24 10:34 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue that caused Service Discovery scans to fail because the wrong message was caught.
```suggestion
- Fixed an issue that caused Service Discovery scans to fail because the wrong message was caught
```

2022-03-24 10:34 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md
> +- Fixed a SQL injection issue  in Service Discovery rules management.
```suggestion
- Fixed an SQL injection issue in Service Discovery rules management
```

2022-03-24 10:34 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
> +- Changed the size of a column to allow storing host discovery provider coming from Plugin Packs with names > 50 characters.
```suggestion
- Changed the size of a column to allow storing host discovery providers coming from Plugin Packs with names exceeding 50 characters
```

2022-03-24 10:34 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
> +- ACL were not updated for items discovered by Host Discovery or Service Discovery.
```suggestion
- ACLs were not updated for items discovered by Host Discovery or Service Discovery
```

2022-03-24 10:34 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue that caused Service Discovery scans to fail because the wrong message was caught.
```suggestion
- Fixed an issue that caused Service Discovery scans to fail because the wrong message was caught
```

2022-03-24 10:34 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
> +- Fixed a SQL injection issue  in Service Discovery rules management.
```suggestion
- Fixed an SQL injection issue in Service Discovery rules management.
```

2022-03-25 10:46 UTC, cg-tw requested changes

2022-03-25 10:46 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
> +- Fixed an SQL injection issue in Service Discovery rules management.
```suggestion
- Fixed an SQL injection issue in Service Discovery rules management
```

2022-03-25 12:40 UTC, cg-tw approved these changes

2022-04-01 08:56 UTC, mdebauchez approved these changes

2022-04-01 10:22 UTC, tuntoja submitted a review, later dismissed

2022-04-01 10:49 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md
> +Release date: `null`
```suggestion
Release date: `April 1, 2022`
```

2022-04-01 10:49 UTC, tuntoja commented on versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
> +Release date: `null`
```suggestion
Release date: `April 1, 2022`
```

2022-04-01 11:16 UTC, tuntoja approved these changes

2022-04-01 11:17 UTC, merged