Add authorized directories for Broker Cache Directory
centreon/centreon-documentation pull request #1428
Opened 2022-03-30 15:52 UTC by s-duret

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 22.04.x (next)

2022-03-30 15:55 UTC, cg-tw requested changes

2022-03-30 15:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
> +      - */var/lib/centreon-broker/*
```suggestion
      - **/var/lib/centreon-broker/**
```

2022-03-30 15:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
> +      - */var/lib/centreon-engine/*
```suggestion
      - **/var/lib/centreon-engine/**
```

2022-03-30 15:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
> +      - */var/cache/centreon/*
```suggestion
      - **/var/cache/centreon/**
```

2022-03-30 15:55 UTC, cg-tw commented on versioned_docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
> +      - */var/lib/centreon-broker/*
```suggestion
      - **/var/lib/centreon-broker/**
```

2022-03-30 15:55 UTC, cg-tw commented on versioned_docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
> +      - */var/lib/centreon-engine/*
```suggestion
      - **/var/lib/centreon-engine/**
```

2022-03-30 15:55 UTC, cg-tw commented on versioned_docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
> +      - */var/cache/centreon/*
```suggestion
      - **/var/cache/centreon/**
```

2022-03-30 16:08 UTC, cg-tw requested changes

2022-03-30 16:08 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
>      directory specified here. Best practice is '/var/lib/centreon-broker/'
```suggestion
    directory specified here. Best practice is **/var/lib/centreon-broker/**
```

2022-03-30 16:08 UTC, cg-tw commented on versioned_docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
>      directory specified here. The best practice is */var/lib/centreon-broker/*.
```suggestion
    directory specified here. The best practice is **/var/lib/centreon-broker/**.
```

2022-03-30 16:09 UTC, cg-tw approved these changes

2022-04-01 10:03 UTC, lpinsivy approved these changes

2022-04-01 10:05 UTC, merged