known-issues(mbi): refacto known issues + add procedure for MBI bigint columns
centreon/centreon-documentation pull request #1440
Opened 2022-04-08 11:31 UTC by kduret

## Description

* Move known issues section from table to chapters
* Add procedure to upgrade MBI columns from int to bigint
* Remove BAM known issues which is not relevant anymore

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 22.04.x (next)

2022-04-08 12:22 UTC, Sims24 approved these changes

2022-04-11 09:55 UTC, kduret commented on versioned_docs/version-22.04/resources/known-issues.md
> +## Vous avez atteint le nombre maximum d'id pour les colonnes `servicemetric_id`
```suggestion
## You have reached the maximum of id for `servicemetric_id` columns
```

2022-04-11 09:56 UTC, kduret commented on versioned_docs/version-22.04/resources/known-issues.md
> +If you have a very large infrastructureSi vous possédez une très large infrastructure, it is possible that the `servicemetric_id` column size has been reached.
```suggestion
If you have a very large infrastructure, it is possible that the `servicemetric_id` column size has been reached.
```

2022-04-11 09:56 UTC, callapa approved these changes

2022-04-14 13:17 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/known-issues.md
> +* Si l'opération est intervenu pendant le lancement habituel de la tâche planifiée, exécutez la commande suivante en indiquant les bonnes dates de début et de fin :
```suggestion
* Si l'opération est intervenue pendant le lancement habituel de la tâche planifiée, exécutez la commande suivante en indiquant les bonnes dates de début et de fin :
```

2022-04-14 13:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/known-issues.md
> +> :warning: **Selon la volumétrie de vos métriques, cette opération peut être plus ou moins longue.**
```suggestion
> Selon la volumétrie de vos métriques, cette opération peut être plus ou moins longue.
```

2022-04-14 13:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/known-issues.md
> +> :warning: **Selon la volumétrie des données, cette opération peut être plus ou moins longue.**
```suggestion
> Selon la volumétrie des données, cette opération peut être plus ou moins longue.
```

2022-04-14 13:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/known-issues.md
> +* Connectez vous sur le serveur de reporting
```suggestion
* Connectez-vous sur le serveur de reporting
```

2022-04-14 13:25 UTC, cg-tw commented on versioned_docs/version-22.04/resources/known-issues.md
> +> :warning: **Depending on your metrics volumes, this operation could be more or less longer.**
```suggestion
> Depending on your metrics volumes, this operation could be more or less long.
```

2022-04-14 13:45 UTC, cg-tw approved these changes

2022-04-14 14:47 UTC, cg-tw requested changes

2022-04-14 20:30 UTC, Nohzoh commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/known-issues.md
> +* Si l'opération est intervenue pendant le lancement habituel de la tâche planifiée, exécutez la commande suivante en indiquant les bonnes dates de début et de fin :
```suggestion
* Si l'opération est effectuée pendant le lancement habituel de la tâche planifiée, exécutez la commande suivante en indiquant les bonnes dates de début et de fin :
```

2022-04-25 08:46 UTC, merged