Automatic installation of plugin packs
centreon/centreon-documentation pull request #1449
Opened 2022-04-13 07:19 UTC by cg-tw

## Description

Automatic installation of plugin packs

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 22.04.x (next)

2022-04-15 07:05 UTC, omercier requested changes

2022-04-15 07:05 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/pluginpacks.md
> +À la page **Configuration > Packs de plugins**, si **Installation automatique des plugins** est à **ON**, les plugins seront mis à jour automatiquement lorsque vous exporterez la configuration d'un c
```suggestion
À la page **Configuration > Packs de plugins**, si **Installation automatique des plugins** est à **ON**, les plugins seront mis à jour automatiquement lorsque vous exporterez la configuration d'un collecteur qui supervise un hôte ou un service qui utilise ce plugin.
```

2022-04-25 14:05 UTC, mdebauchez approved these changes

2022-04-26 07:13 UTC, omercier commented on versioned_docs/version-22.04/monitoring/pluginpacks.md
> +On page **Configuration > Plugin Packs**, if **Automatic installation of plugins** is set to **ON**, plugins will be automatically updated when you export the configuration for a poller that monitors
```suggestion
On page **Configuration > Plugin Packs**, if **Automatic installation of plugins** is set to **ON**, plugins will be automatically updated as you deploy the configuration for a poller that monitors a host that uses these plugins.
```

2022-04-26 15:26 UTC, omercier approved these changes

2022-04-26 16:03 UTC, merged