enh(release): Add Centreon Web 20.10.17 RN
centreon/centreon-documentation pull request #1452
Opened 2022-04-14 14:07 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [x] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.04.x (next)

2022-04-14 14:28 UTC, cg-tw requested changes

2022-04-14 14:28 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +- [Core] Fixed save proxy setting with empty prameters
```suggestion
- [Core] Proxy settings were saved with empty parameters
```

2022-04-14 14:28 UTC, cg-tw commented on versioned_docs/version-20.10/releases/centreon-core.md
> +- [Core] Fixed save proxy setting with empty prameters
```suggestion
- [Core] Proxy settings were saved with empty parameters
```

2022-04-14 14:28 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +- [MBI] Fixed MBI graphs reports not respecting graphs templates
```suggestion
- [MBI] MBI graphs reports were not using graph templates
```

2022-04-14 14:28 UTC, cg-tw commented on versioned_docs/version-20.10/releases/centreon-core.md
> +- [MBI] Fixed MBI graphs reports not respecting graphs templates
```suggestion
- [MBI] MBI graphs reports were not using graph templates
```

2022-04-14 14:28 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +- [Resources Status] Fixed Monitoring command not displayed in Resources Status details panel
```suggestion
- [Resources Status] Fixed monitoring command not displayed in Resources Status Details panel
```

2022-04-14 14:28 UTC, cg-tw commented on versioned_docs/version-20.10/releases/centreon-core.md
> +- [Resources Status] Fixed Monitoring command not displayed in Resources Status details panel
```suggestion
- [Resources Status] Fixed monitoring command not displayed in Resources Status Details panel
```

2022-04-15 10:07 UTC, mdebauchez approved these changes

2022-04-15 10:21 UTC, cg-tw approved these changes

2022-04-15 12:18 UTC, chgautier requested changes

2022-04-15 12:18 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +
```suggestion

Release date: `April 15, 2022`

```

2022-04-15 12:18 UTC, chgautier commented on versioned_docs/version-20.10/releases/centreon-core.md
> +
```suggestion

Release date: `April 15, 2022`

```

2022-04-15 12:21 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md
> +
```suggestion

Release date: `April 15, 2022`

```

2022-04-15 12:35 UTC, chgautier approved these changes

2022-04-15 13:04 UTC, merged