enh(release): Add Centreon Web 21.04.14 RN
centreon/centreon-documentation pull request #1466
Opened 2022-04-25 10:38 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [x] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.04.x (next)

2022-04-27 13:18 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Core] Proxy settings were saved with empty parameters
```suggestion
- [Core] Fixed an issue where proxy settings were saved with empty parameters
```

2022-04-27 13:18 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Install] Fixed database user creation with remote DBMS
```suggestion
- [Install] Fixed an issue in database user creation with remote DBMS
```

2022-04-27 13:30 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [UX] Improved interface response time if CEIP is enabled but the browser does not have internet access
```suggestion
- [UX] Fixed the internet access issue occuring since the improvement of interface response time when CEIP is enabled
```

2022-04-27 13:33 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Apache] Improve Apache configuration to enable HSTS
```suggestion
- [Apache] Fixed issues to improve Apache configuration for enabling HSTS
```

2022-04-27 13:36 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Core] Passwords are now obfuscated in the page's HTML source
```suggestion
- [Core] Fixed passwords that were not obfuscated in the HTML source page
```

2022-04-27 13:38 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Core] Replace Math.random by Crypto JS API
```suggestion
- [Core] Fixed Math.random that was to be replaced with Crypto JS API
```

2022-04-27 13:39 UTC, smau-centreon commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Core] Proxy settings were saved with empty parameters
```suggestion
- [Core] Fixed an issue where proxy settings were saved with empty parameters
```

2022-04-27 13:40 UTC, smau-centreon commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Install] Fixed database user creation with remote DBMS
```suggestion
- [Install] Fixed an issue in database user creation with remote DBMS
```

2022-04-27 13:40 UTC, smau-centreon commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Reporting] MBI graphs reports were not using graph templates
```suggestion
- [Reporting] Fixed an issue where MBI graphs reports were not using graph templates
```

2022-04-27 13:41 UTC, smau-centreon commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Resources Status] Fixed monitoring command not displayed in Resources Status Details panel
```suggestion
- [Resources Status] Fixed monitoring command that was not displayed in Resources Status Details panel
```

2022-04-27 13:42 UTC, smau-centreon commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [UX] Improved interface response time if CEIP is enabled but the browser does not have internet access
```suggestion
- [UX] Fixed the internet access issue occuring since the improvement of interface response time when CEIP is enabled
```

2022-04-27 13:44 UTC, smau-centreon commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Core] Replace Math.random by Crypto JS API
```suggestion
- [Core] Fixed Math.random that was to be replaced with Crypto JS API
```

2022-04-27 14:23 UTC, smau-centreon requested changes

2022-04-27 14:23 UTC, smau-centreon commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Apache] Improve Apache configuration to enable HSTS
```suggestion
- [Apache] HTTPS Apache configuration now includes HSTS
```

2022-04-29 13:00 UTC, mdebauchez requested changes
Should we add these tickets:
- MON-12494 : CEIP - Add IT-100 license type
- MON-11890 : [CEIP] Add a unique identifier for css objects in Resources Status listing (this one has something in the Release note field)
- MON-12129 : [CEIP] Identify Centreon Cloud platform

2022-04-29 14:05 UTC, lpinsivy commented
> Should we add these tickets:
> 
> * MON-12494 : CEIP - Add IT-100 license type
> * MON-11890 : [CEIP] Add a unique identifier for css objects in Resources Status listing (this one has something in the Release note field)
> * MON-12129 : [CEIP] Identify Centreon Cloud platform

no they are technical tickets

2022-04-29 14:09 UTC, mdebauchez approved these changes

2022-05-02 07:32 UTC, smau-centreon approved these changes

2022-05-02 08:07 UTC, cg-tw submitted a review, later dismissed

2022-05-02 08:07 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +
```suggestion

Release date: `May 2, 2022`

```

2022-05-02 08:07 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +
```suggestion

Release date: `May 2, 2022`

```

2022-05-02 08:09 UTC, smau-centreon approved these changes

2022-05-02 08:10 UTC, mdebauchez approved these changes

2022-05-02 09:01 UTC, cg-tw approved these changes

2022-05-02 15:45 UTC, merged