enh(release): Add Centreon Web 21.10.6 RN
centreon/centreon-documentation pull request #1467
Opened 2022-04-25 10:52 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [x] 21.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.04.x (next)

2022-04-27 11:48 UTC, cg-tw requested changes

2022-04-27 11:48 UTC, cg-tw requested changes

2022-04-27 11:48 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Monitoring] fixed relation issue for recurrent downtimes
```suggestion
- [Monitoring] Fixed relation issue for recurrent downtimes
```

2022-04-27 11:48 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed a SQL injection issue in Configuration > Poller > Resources
```suggestion
- [Configuration] Fixed an SQL injection issue in Configuration > Poller > Resources
```

2022-04-27 14:10 UTC, smau-centreon requested changes

2022-04-27 14:10 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [PHP] Disabling allow_url_fopen in PHP
```suggestion
- [PHP] Fixing an issue by disabling allow_url_fopen in PHP
```

2022-04-27 14:24 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Apache] Improve Apache configuration to enable HSTS
```suggestion
- [Apache] HTTPS Apache configuration now includes HSTS
```

2022-04-27 14:50 UTC, smau-centreon requested changes

2022-04-27 14:50 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Core] Proxy settings were saved with empty parameters
```suggestion
- [Core] Fixed an issue where proxy settings were saved with empty parameters
```

2022-04-29 13:18 UTC, mdebauchez requested changes
Shouldn't we add the following tickets:
- MON-12744 : Date/Time on the top-right doesn't respect user configuration
- MON-12494 : CEIP - Add IT-100 license type
- MON-12337 : [CEIP] Add a unique identifier for css objects in Resources Status listing
- MON-12448 : Synchronise update scripts between 21.10.x and develop
- MON-12129 : [CEIP] Identify Centreon Cloud platform

2022-04-29 14:14 UTC, mdebauchez submitted a review, later dismissed

2022-05-02 07:22 UTC, cg-tw approved these changes

2022-05-02 07:53 UTC, smau-centreon approved these changes

2022-05-02 08:05 UTC, cg-tw approved these changes

2022-05-02 08:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `May 2, 2022`

```

2022-05-02 08:05 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +
```suggestion


Release date: `May 2, 2022`

```

2022-05-02 08:09 UTC, mdebauchez approved these changes

2022-05-02 08:09 UTC, smau-centreon approved these changes

2022-05-02 09:01 UTC, cg-tw approved these changes

2022-05-02 15:45 UTC, merged