add(epp): backup exec nscp api
centreon/centreon-documentation pull request #1476
Opened 2022-04-29 12:30 UTC by garnier-quentin

## Description

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 22.04.x (next)

2022-05-03 11:03 UTC, Sims24 requested changes

2022-05-03 11:03 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +| Mandatory | Name                      | Description                                                                                  |
```suggestion
| Obligatoire| Nom                      | Description                                                                                  |
```

2022-05-03 11:03 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +The Centreon Pack Backup Exec brings 1 host template:
```suggestion
The Centreon Pack Backup Exec brings a host template:
```

2022-05-03 11:03 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +1. Install the Centreon Plugin package on every Centreon poller expected to monitor **Veritas Backup Exec NSCP API** resources:
```suggestion
1. Install the Centreon plugin package on every Centreon poller expected to monitor **Veritas Backup Exec NSCP API** resources:
```

2022-05-03 11:03 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +1. Install the Centreon Plugin package on every Centreon poller expected to monitor **Veritas Backup Exec NSCP API** resources:
```suggestion
1. Install the Centreon plugin package on every Centreon poller expected to monitor **Veritas Backup Exec NSCP API** resources:
```

2022-05-03 11:03 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +Once the plugin is installed, log into your Centreon Poller CLI using the
```suggestion
Once the plugin is installed, log into your Centreon poller CLI using the
```

2022-05-03 11:03 UTC, Sims24 commented on pp/sidebarsPp.js
> +        },
Preserve alphabetical order please

2022-05-06 07:14 UTC, lchrdn commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +Une fois le Plugin installé, vous pouvez tester la bonne configuration NSClient directement en ligne
```suggestion
Une fois le plugin installé, vous pouvez tester la bonne configuration NSClient directement en ligne
```

2022-05-06 07:14 UTC, lchrdn commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +Vous pouvez maintenant tester le Plugin Backup Exec :
```suggestion
Vous pouvez maintenant tester le plugin Backup Exec :
```

2022-05-06 07:16 UTC, lchrdn commented on pp/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +Check the Backup Exec Plugin by running the following command:
```suggestion
Check the Backup Exec plugin by running the following command:
```

2022-05-06 07:18 UTC, lchrdn commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +2. Sur le serveur Central Centreon, installez le RPM du Pack **Veritas Backup Exec NSCP API** :
```suggestion
2. Sur le serveur central Centreon, installez le RPM du Pack **Veritas Backup Exec NSCP API** :
```

2022-05-06 07:19 UTC, lchrdn commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
> +2. Sur l'interface Web de Centreon, installez le Pack **Veritas Backup Exec NSCP API** depuis la page **Configuration > Packs de plugins**.
```suggestion
2. Sur l'interface web de Centreon, installez le Pack **Veritas Backup Exec NSCP API** depuis la page **Configuration > Packs de plugins**.
```

2022-05-06 07:56 UTC, Sims24 approved these changes

2022-05-06 08:52 UTC, lchrdn approved these changes

2022-05-06 09:09 UTC, merged