add(epp): protocol sftp
centreon/centreon-documentation pull request #1487
Opened 2022-05-04 09:45 UTC by garnier-quentin

## Description

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 22.04.x (next)

2022-05-04 10:02 UTC, lchrdn commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +* clés publique
```suggestion
* clé publique
```

2022-05-04 10:05 UTC, lchrdn approved these changes

2022-05-04 21:32 UTC, Sims24 requested changes

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +Le Pack Centreon SFTP apporte 1 modèle d'hôte :
```suggestion
Le Pack Centreon SFTP apporte un modèle d'hôte :
```

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +| Service Alias  | Service Templat               | Default | Discovery |
s/Service Alias/Alias/
s/Service Templat/Modèle de services/
s/Default/Défaut/
s/Discovery/Découverte/

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +1. Installer le Plugin Centreon sur tous les collecteurs Centreon devant superviser des ressources **Protocol SFTP** :
```suggestion
1. Installer le plugin Centreon sur tous les collecteurs Centreon devant superviser des ressources **Protocol SFTP** :
```

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +2. Sur l'interface Web de Centreon, installer le Pack **Protocol SFTP** depuis la page **Configuration > Packs de plugins**.
```suggestion
2. Sur l'interface web de Centreon, installer le Pack **Protocol SFTP** depuis la page **Configuration > Packs de plugins**.
```

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +1. Installer le Plugin Centreon sur tous les collecteurs Centreon devant superviser des ressources **Protocol SFTP** :
```suggestion
1. Installer le plugin Centreon sur tous les collecteurs Centreon devant superviser des ressources **Protocol SFTP** :
```

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +2. Sur le serveur Central Centreon, installer le RPM du Pack **Protocol SFTP** :
```suggestion
2. Sur le serveur central Centreon, installer le RPM du Pack **Protocol SFTP** :
```

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +3. Sur l'interface Web de Centreon, installer le Pack **Protocol SFTP** depuis la page **Configuration > Packs de plugins**.
```suggestion
3. Sur l'interface web de Centreon, installer le Pack **Protocol SFTP** depuis la page **Configuration > Packs de plugins**.
```

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +* Ajoutez un Hôte à Centreon depuis la page **Configuration > Hôtes**
```suggestion
* Ajoutez un hôte à Centreon depuis la page **Configuration > Hôtes**
```

2022-05-04 21:32 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +| Mandatory | Name                     | Description                                                                |
s/Mandatory/Obligatoire/
s/Name/Nom/

2022-05-04 21:32 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +The Centreon Pack SFTP brings 1 host template:
```suggestion
The Centreon Pack SFTP brings a host template:
```

2022-05-04 21:32 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +1. Install the Centreon Plugin package on every Centreon poller expected to monitor **Protocol SFTP** resources:
```suggestion
1. Install the Centreon plugin package on every Centreon poller expected to monitor **Protocol SFTP** resources:
```

2022-05-04 21:32 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +2. On the Centreon Web interface, install the **Protocol SFTP** Centreon Pack on the **Configuration > Plugin Packs** page.
```suggestion
2. On the Centreon web interface, install the **Protocol SFTP** Centreon Pack on the **Configuration > Plugin Packs** page.
```

2022-05-04 21:32 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +1. Install the Centreon Plugin package on every Centreon poller expected to monitor **Protocol SFTP** resources:
```suggestion
1. Install the Centreon plugin package on every Centreon poller expected to monitor **Protocol SFTP** resources:
```

2022-05-04 21:32 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +3. On the Centreon Web interface, install the **Protocol SFTP** Centreon Pack on the **Configuration > Plugin Packs** page.
```suggestion
3. On the Centreon web interface, install the **Protocol SFTP** Centreon Pack on the **Configuration > Plugin Packs** page.
```

2022-05-04 21:32 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +* Log into Centreon and add a new Host through **Configuration > Hosts**.
```suggestion
* Log into Centreon and add a new host through **Configuration > Hosts**.
```

2022-05-06 07:10 UTC, lchrdn commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +Il apporte les Modèles de Service suivants :
```suggestion
Il apporte les modèles de service suivants :
```
```suggestion
Il apporte les Modèles de Service suivants :
```

2022-05-06 07:10 UTC, lchrdn commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +Il apporte les Modèles de Service suivants :
```suggestion
Il apporte les modèles de service suivants :
```
```suggestion
Il apporte les Modèles de Service suivants :
```

2022-05-06 08:51 UTC, lchrdn approved these changes

2022-05-06 09:11 UTC, Sims24 approved these changes

2022-05-06 09:11 UTC, merged