Centreon plugin for Grafana
centreon/centreon-documentation pull request #1511
Opened 2022-05-12 06:57 UTC by cg-tw

## Description

Centreon plugin for Grafana

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 22.04.x (next)

2022-05-13 09:09 UTC, nmagniezCentreon requested changes

2022-05-13 09:09 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/metrology/grafana.md
> +Un même tableau de bord Grafana peut contenir divers panneaux. Chaque panneau peut afficher des données provenant d'une source spécifique. Ainsi, vous pouvez comparer des données concernant le même h
Il faudrait sans doute dire que les possibilités de filtrage au niveau des variable sont les mêmes que celles pour filtrer les métriques dans les panels.

2022-05-13 12:31 UTC, thib3113 commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/metrology/grafana.md
> +Vous pouvez utiliser des expressions régulières pour filtrer sur plusieurs hôtes en même temps.
Non, il n'est pas possible d'utiliser des expressions régulières, on peut juste utiliser le joker ( aka : on peut faire `tes*` pour matcher `test`/`tessssst`/... mais pas `[a-z]+` )

2022-05-13 12:31 UTC, thib3113 commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/metrology/grafana.md
> +Les [variables](https://grafana.com/docs/grafana/latest/variables/) permettent de créer des listes déroulantes qui filtreront l'ensemble des données du tableau de bord. Par exemple, paramétrez une va
"déroulantes qui filtreront l'ensemble des données du tableau de bord" pas totalement d'accord avec ça ... 

ça permet de le faire, ou de faire un contexte . mais ça ne change pas forcément l'ensemble des données . ( on peut le faire par lignes, ou seulement dans des panels précis ... ) . Mais c'est plus une spécificité grafana, que du plugins . 

J'aurais plutôt mis :
```
Les variables permettent de pré selectionné certaines valeurs, que vous pouvez ensuite réutiliser dans les différents panneaux de votre tableau de bord, afin de les lier
```

2022-05-13 12:32 UTC, thib3113 commented
je rajouterais aussi que ça me semble bizarre que sur l'image des variables, on voit 3 graphs dans la légende, mais seulement 1 sur le graph

2022-05-18 07:57 UTC, nmagniezCentreon requested changes

2022-05-18 07:57 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/metrology/grafana.md
> +Pour sélectionner les données de performance à afficher, vous pouvez combiner des filtres sur divers types de données disponibles sur votre plateforme Centreon. Vous pouvez afficher des métriques, de
types de données -> types de ressources

2022-05-18 07:57 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/metrology/grafana.md
> +Pour sélectionner les données de performance à afficher, vous pouvez combiner des filtres sur divers types de données disponibles sur votre plateforme Centreon. Vous pouvez afficher des métriques, de
selon les données suivantes -> en construisant des filtres sur les types de ressources suivants

2022-05-18 08:13 UTC, nmagniezCentreon approved these changes

2022-05-18 08:16 UTC, merged