update(doc) for Lenovo XCC SNMP
centreon/centreon-documentation pull request #1536
Opened 2022-05-19 13:45 UTC by ponchoh

## Description

- use template
- update content
- add links

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] Cloud (staging)
- [x] Plugin Packs (staging)
- [ ] 22.04.x (next)

2022-10-03 13:26 UTC, Sims24 requested changes
Few things to modify as I took so much time to review this PR, it results on some extra work on our side. 

Thanks who? 🙃

2022-10-03 13:26 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +Could not retrive metrics
You have to manually add metrics when script cannot figure out which ones it should add

2022-10-03 13:26 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +spécifiques associés via la macro **SNMPEXTRAOPTIONS**.
Should be updated according to latest layout. Ref https://github.com/centreon/centreon-documentation/pull/1716/files

2022-10-03 13:26 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +OK: |
Output is probably not just OK

2022-10-03 13:26 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +Rendez-vous sur la [documentation dédiée](../getting-started/how-to-guides/troubleshooting-plugins.md)
Update link to the specific snmp troubleshooting section

2022-10-03 13:26 UTC, Sims24 commented on pp/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +import TabItem from '@theme/TabItem';
Check my comments on the FR version.

2023-01-16 16:06 UTC, omercier commented
A Jira ticket has been created
REFS: MON-16610

2023-01-27 07:42 UTC, omercier approved these changes

2023-01-27 08:19 UTC, cg-tw requested changes

2023-01-27 08:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +Lenovo développe, fabrique et vend du matériel et logiciels informatiques.
```suggestion
Lenovo développe, fabrique et vend du matériel et des logiciels informatiques.
```

2023-01-27 08:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2023-01-27 08:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +server. Please refer to the official documentation from XXX:
```suggestion
server. Please refer to the official documentation from Lenovo:
```

2023-01-27 08:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +If you are using SNMP Version 3, use the **SNMPEXTRAOPTIONS** macro to configure
```suggestion
```

2023-02-07 16:21 UTC, cg-tw approved these changes

2023-02-07 16:22 UTC, omercier approved these changes

2023-02-08 09:07 UTC, merged