Add upgrade centreon double run
centreon/centreon-documentation pull request #1547
Opened 2022-05-24 15:17 UTC by psamecentreon

## Description

This is a documentation to implement the migration of Centreon between different OS by the double-run method

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [X] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-06-06 15:12 UTC, cedricmeschin requested changes

2022-06-06 15:12 UTC, cedricmeschin commented on versioned_docs/version-22.04/upgrade/double-run/upgrade-double-run-from-20.04.md
> +mysqldump -u root -p <rootPassword> centreon > db_centreon_fresh_install_`date +%Y%m%d-%H%M`.sql
similar remarks as for version 21.10

2022-06-06 15:12 UTC, cedricmeschin commented on versioned_docs/version-22.04/upgrade/double-run/upgrade-double-run-from-20.10.md
> +mysqldump -u root -p <rootPassword> centreon > db_centreon_fresh_install_`date +%Y%m%d-%H%M`.sql
similar remarks as for version 21.10

2022-06-06 15:12 UTC, cedricmeschin commented on versioned_docs/version-22.04/upgrade/double-run/upgrade-double-run-from-21.04.md
> +mysqldump -u root -p <rootPassword> centreon > db_centreon_fresh_install_`date +%Y%m%d-%H%M`.sql
similar remarks as for version 21.10

2022-06-06 15:12 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/double-run/upgrade-double-run-from-20.04.md
> +mysqldump -u root -p <rootPassword> centreon > db_centreon_fresh_install_`date +%Y%m%d-%H%M`.sql
similar remarks as for version 21.10 EN

2022-06-06 15:12 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/double-run/upgrade-double-run-from-20.10.md
> +mysqldump -u root -p <rootPassword> centreon > db_centreon_fresh_install_`date +%Y%m%d-%H%M`.sql
similar remarks as for version 21.10 EN

2022-06-06 15:12 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/double-run/upgrade-double-run-from-20.10.md
> +mysqldump -u root -p <rootPassword> centreon > db_centreon_fresh_install_`date +%Y%m%d-%H%M`.sql
similar remarks as for version 21.10 EN

2022-06-06 15:12 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/double-run/upgrade-double-run-from-21.04.md
> +mysqldump -u root -p <rootPassword> centreon > db_centreon_fresh_install_`date +%Y%m%d-%H%M`.sql
similar remarks as for version 21.10 EN

2022-09-06 06:57 UTC, cedricmeschin approved these changes

2023-07-12 11:50 UTC, cg-tw commented
Internal doc

2023-07-12 11:50 UTC, closed without merging