Update centreon-commercial-extensions.md
centreon/centreon-documentation pull request #1551
Opened 2022-05-25 16:44 UTC by nmagniezCentreon

## Description

Release note MAP 21.10.5

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-05-25 16:55 UTC, chgautier requested changes

2022-05-30 07:51 UTC, smau-centreon requested changes

2022-05-30 07:51 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed Weather styled elements are not showing any image
```suggestion
- Fixed weather styled elements that were not showing any image
```

2022-05-30 07:51 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Change label in map home page about server ip address
```suggestion
- Changed label in MAP home page about server IP address
```

2022-05-30 07:51 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed Weather styled elements are not showing any image
```suggestion
- Fixed weather styled elements that were not showing any image
```

2022-05-30 07:51 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Change label in map home page about server ip address
```suggestion
- Changed label in MAP home page about server IP address
```

2022-05-30 16:15 UTC, chgautier requested changes

2022-05-30 16:15 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `May 30, 2022`

```

2022-05-30 16:15 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `May 30, 2022`

```

2022-05-31 07:27 UTC, smau-centreon requested changes

2022-05-31 07:27 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed regressions on API endpoints due to spring boot version
```suggestion
- Fixed regressions on API endpoints due to Spring Boot version
```

2022-05-31 07:49 UTC, smau-centreon requested changes

2022-05-31 07:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed regressions on API endpoints due to spring boot version
```suggestion
- Fixed regressions on API endpoints due to Spring Boot version
```

2022-05-31 07:51 UTC, chgautier approved these changes

2022-05-31 07:58 UTC, smau-centreon approved these changes

2022-05-31 08:27 UTC, merged