PS-34 - Add doc for centreon-HA Manual in 21.10
centreon/centreon-documentation pull request #1585
Opened 2022-06-06 10:27 UTC by cedricmeschin

## Description

Installation of centreon-HA Manual 2 nodes and 4 nodes in 21.10
EN and FR versions

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [X] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-08-31 15:56 UTC, psamecentreon requested changes

2022-08-31 15:56 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
> +* central-rrd-master` : le RRD broker qui reçoit son flux du SQL broker, et dont la seule fonction est d'écrire les fichiers RRD utilisés pour afficher les graphes.
```suggestion
* `central-rrd-master` : le RRD broker qui reçoit son flux du SQL broker, et dont la seule fonction est d'écrire les fichiers RRD utilisés pour afficher les graphes. 

```

2022-08-31 15:56 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
> +Plutôt que de mettre en place une réplication en temps réel des fichiers de données RRD, le choix technique qui a été fait pour permettre aux graphiques d'être affichés sur n'importe quel noeud dès q
```suggestion
Plutôt que de mettre en place une réplication en temps réel des fichiers de données RRD, le choix technique qui a été fait pour permettre aux graphiques d'être affichés sur n'importe quel noeud dès qu'il devient `master` a été de dupliquer le flux de sortie de `central-broker-master` vers `central-rrd-master`. Ceci est configuré dans le même menu que dans le paragraphe précédent, mais cette fois dans l'onglet *Output* de *Configuration > Collectors > Centreon Broker Configuration*.

```

2022-08-31 15:56 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
> +CENTREON   ALL = NOPASSWD: /usr/bin/nmcli
```suggestion
CENTREON   ALL = NOPASSWD: /usr/bin/nmcli

```

2022-08-31 15:56 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
> +* central-rrd-master` : le RRD broker qui reçoit son flux du SQL broker, et dont la seule fonction est d'écrire les fichiers RRD utilisés pour afficher les graphes.
```suggestion
* `central-rrd-master` : le RRD broker qui reçoit son flux du SQL broker, et dont la seule fonction est d'écrire les fichiers RRD utilisés pour afficher les graphes. 

```

2022-08-31 15:56 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
> +Plutôt que de mettre en place une réplication en temps réel des fichiers de données RRD, le choix technique qui a été fait pour permettre aux graphiques d'être affichés sur n'importe quel noeud dès q
```suggestion
Plutôt que de mettre en place une réplication en temps réel des fichiers de données RRD, le choix technique qui a été fait pour permettre aux graphiques d'être affichés sur n'importe quel noeud dès qu'il devient 'master' a été de dupliquer le flux de sortie de `central-broker-master` vers `central-rrd-master`. Ceci est configuré dans le même menu que dans le paragraphe précédent, mais cette fois dans l'onglet *Output* de *Configuration > Collectors > Centreon Broker Configuration*.

```

2022-08-31 15:56 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
> +**Note : ** sauf indication contraire, chacune des étapes suivantes doit être effectuée **sur les deux noeuds centraux**.
```suggestion
**Note :** sauf indication contraire, chacune des étapes suivantes doit être effectuée **sur les deux noeuds centraux**.

```

2022-08-31 15:56 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
> +CENTREON   ALL = NOPASSWD: /usr/bin/nmcli
```suggestion
CENTREON   ALL = NOPASSWD: /usr/bin/nmcli

```

2022-09-08 15:34 UTC, psamecentreon submitted a review, later dismissed

2022-09-13 08:50 UTC, psamecentreon approved these changes

2022-09-20 14:05 UTC, cg-tw requested changes

2022-09-20 14:05 UTC, cg-tw commented on versioned_sidebars/version-22.04-sidebars.json
> +          "label": "Installation of Centreon HA manual",
```suggestion
          "label": "Installation of a manual Centreon HA",
```

2022-09-20 14:05 UTC, cg-tw commented on versioned_docs/version-22.04/installation/installation-of-centreon-ha-manual/integrating-pollers.md
> +title: Integrating new pollers in a Centreon-HA cluster
```suggestion
title: Integrating new pollers in a manual Centreon-HA cluster
```

2022-09-20 14:24 UTC, psamecentreon submitted a review, later dismissed

2022-09-20 14:31 UTC, psamecentreon submitted a review, later dismissed

2022-09-20 16:09 UTC, cg-tw approved these changes

2022-09-20 16:09 UTC, merged