enh(release): add Centreon Web 21.10.7 RN
centreon/centreon-documentation pull request #1601
Opened 2022-06-09 09:42 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-06-09 14:02 UTC, Thebarda submitted a review, later dismissed

2022-06-09 14:14 UTC, smau-centreon requested changes

2022-06-09 14:14 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed export when host group disabled
```suggestion
- [Configuration] Fixed export when host group is disabled
```

2022-06-09 14:14 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed export when service group disabled
```suggestion
- [Configuration] Fixed export when service group is disabled
```

2022-06-09 14:14 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed export when service template disabled
```suggestion
- [Configuration] Fixed export when service template is disabled
```

2022-06-09 14:14 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Monitoring] fixed notification number in legacy pages
```suggestion
- [Monitoring] Fixed notification number in legacy pages
```

2022-06-09 14:14 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Resource Status] Fixed color of resources in downtime or acknowledged when selected
```suggestion
- [Resource Status] Fixed color when resources are selected in downtime or acknowledged
```

2022-06-09 14:14 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [UX] Respect user configuration for Date/Time display
```suggestion
- [UX] Follow user configuration for Date/Time display
```

2022-06-09 14:14 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Widget] Use ACL to get list of poller to filter display of services
```suggestion
- [Widget] Use ACL to get list of pollers to filter display of services
```

2022-06-09 14:14 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed export when host group disabled
```suggestion
- [Configuration] Fixed export when host group is disabled
```

2022-06-09 14:14 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed export when service group disabled
```suggestion
- [Configuration] Fixed export when service group is disabled
```

2022-06-09 14:14 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed export when service template disabled
```suggestion
- [Configuration] Fixed export when service template is disabled
```

2022-06-09 14:14 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Resource Status] Fixed color of resources in downtime or acknowledged when selected
```suggestion
- [Resource Status] Fixed color when resources are selected in downtime or acknowledged
```

2022-06-09 14:14 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [UX] Respect user configuration for Date/Time display
```suggestion
- [UX] Follow user configuration for Date/Time display
```

2022-06-09 14:14 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Widget] Use ACL to get list of poller to filter display of services
```suggestion
- [Widget] Use ACL to get list of pollers to filter display of services
```

2022-06-09 14:57 UTC, soukainafarouq approved these changes

2022-06-10 09:59 UTC, thiuyendang commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Widget] Use ACL to get list of poller to filter display of services
```suggestion
- [Widget] The list of pollers is now filtered according to the user's ACLs
```

2022-06-10 12:24 UTC, smau-centreon approved these changes

2022-06-10 12:31 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `June 10, 2022`

```

2022-06-10 12:31 UTC, tuntoja commented on versioned_docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `June 10, 2022`

```

2022-06-10 12:34 UTC, thiuyendang submitted a review, later dismissed

2022-06-10 12:36 UTC, smau-centreon submitted a review, later dismissed

2022-06-10 13:44 UTC, tuntoja approved these changes

2022-06-10 13:45 UTC, smau-centreon approved these changes

2022-06-10 14:18 UTC, merged