doc(release): add release note for centreon-connector-perl-21.04.4
centreon/centreon-documentation pull request #1607
Opened 2022-06-09 15:11 UTC by omercier

## Description

connector perl 21.04.4

## Target version

- [ ] 20.10.x (staging)
- [x] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-06-09 15:12 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +
```suggestion
```

2022-06-09 15:12 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- UNKNOWN status is displayed instead of WARNING and CRITICAL when using the perl connector
```suggestion
```

2022-06-09 15:22 UTC, chgautier requested changes

2022-06-09 15:22 UTC, chgautier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- UNKNOWN status is displayed instead of WARNING and CRITICAL when using the perl connector
shouldn't this not be in the release note since it is a regression that appeared with the memory leak fix below?

2022-06-09 15:22 UTC, chgautier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- Fixed an issue that could crash the SSH connector
should be in Centreon Connector SSH

2022-06-09 15:27 UTC, omercier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- Fixed an issue that could crash the SSH connector
```suggestion
```

2022-06-09 15:27 UTC, omercier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- UNKNOWN status is displayed instead of WARNING and CRITICAL when using the perl connector
```suggestion
```

2022-06-09 15:27 UTC, chgautier approved these changes

2022-06-09 15:29 UTC, cg-tw approved these changes

2022-06-10 14:04 UTC, chgautier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +Release date: `null`
```suggestion
Release date: `June 10, 2022`
```

2022-06-10 14:05 UTC, chgautier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +### 21.04.4
```suggestion
### 21.04.4
```

2022-06-10 14:17 UTC, chgautier approved these changes

2022-06-10 14:42 UTC, cg-tw approved these changes

2022-06-10 14:52 UTC, merged