doc(release): add release note for centreon-connector-ssh-21.04.4
centreon/centreon-documentation pull request #1608
Opened 2022-06-09 15:19 UTC by omercier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [x] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-06-09 15:23 UTC, omercier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +
```suggestion
#### Bug fixes

- Fixed an issue that could crash the SSH connector
```

2022-06-09 15:57 UTC, cg-tw requested changes

2022-06-09 15:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- Fixed an issue that could crash the SSH connector
```suggestion
- Fixed an issue that could cause the SSH connector to crash

```

2022-06-09 15:57 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- Fixed an issue that could crash the SSH connector
```suggestion
- Fixed an issue that could cause the SSH connector to crash

```

2022-06-10 09:56 UTC, chgautier submitted a review, later dismissed

2022-06-10 13:07 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +### 21.04.4
### 21.04.4

2022-06-10 13:07 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +### 21.04.4
```suggestion
### 21.04.4
```

2022-06-10 13:08 UTC, chgautier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +### 21.04.4
```suggestion
### 21.04.4
```

2022-06-10 13:24 UTC, cg-tw submitted a review, later dismissed

2022-06-10 14:18 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +Release date: `null`
```suggestion
Release date: `June 10, 2022`
```

2022-06-10 14:18 UTC, chgautier commented on versioned_docs/version-21.04/releases/centreon-core.md
> +Release date: `null`
```suggestion
Release date: `June 10, 2022`
```

2022-06-10 14:18 UTC, chgautier approved these changes

2022-06-10 14:41 UTC, cg-tw approved these changes

2022-06-10 14:50 UTC, merged