enh(upgrade): recent versions of broker do not support failover
centreon/centreon-documentation pull request #1622
Opened 2022-06-15 15:12 UTC by omercier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [x] 21.04.x (staging)
- [x] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-06-20 14:25 UTC, cg-tw requested changes

2022-06-20 14:25 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/upgrade/upgrade-from-3-4.md
> +Depuis le menu **Configuration > Collecteurs > Configuration de Centreon Broker**, supprimer la valeur du paramètre **Nom du processus de bascule (failover)** pour chacun des outputs de chacune des e
```suggestion
Depuis le menu **Configuration > Collecteurs > Configuration de Centreon Broker**, supprimez la valeur du paramètre **Nom du processus de bascule (failover)** pour chacun des outputs de chacune des entrées de configuration de Centreon Broker.
```

2022-06-20 14:25 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/upgrade-from-3-4.md
> +Depuis le menu **Configuration > Collecteurs > Configuration de Centreon Broker**, supprimer la valeur du paramètre **Nom du processus de bascule (failover)** pour chacun des outputs de chacune des e
```suggestion
Depuis le menu **Configuration > Collecteurs > Configuration de Centreon Broker**, supprimez la valeur du paramètre **Nom du processus de bascule (failover)** pour chacun des outputs de chacune des entrées de configuration de Centreon Broker.
```

2022-06-20 14:25 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md
> +Depuis le menu **Configuration > Collecteurs > Configuration de Centreon Broker**, supprimer la valeur du paramètre **Nom du processus de bascule (failover)** pour chacun des outputs de chacune des e
```suggestion
Depuis le menu **Configuration > Collecteurs > Configuration de Centreon Broker**, supprimez la valeur du paramètre **Nom du processus de bascule (failover)** pour chacun des outputs de chacune des entrées de configuration de Centreon Broker.
```

2022-06-20 14:25 UTC, cg-tw commented on versioned_docs/version-21.04/upgrade/upgrade-from-3-4.md
> +> In older versions of Centreon, the broker retention mechanism that stored monitoring data in files used to require manual configuration.
```suggestion
> In older versions of Centreon, the broker retention mechanism that stored monitoring data in temporary files when a network outage occurred used to require manual configuration.
```

2022-06-20 14:25 UTC, cg-tw commented on versioned_docs/version-21.10/upgrade/upgrade-from-3-4.md
> +> In older versions of Centreon, the broker retention mechanism that stored monitoring data in files used to require manual configuration.
```suggestion
> In older versions of Centreon, the broker retention mechanism that stored monitoring data in temporary files when a network outage occurred used to require manual configuration.
```

2022-06-20 14:25 UTC, cg-tw commented on versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md
> +> In older versions of Centreon, the broker retention mechanism that stored monitoring data in files used to require manual configuration.
```suggestion
> In older versions of Centreon, the broker retention mechanism that stored monitoring data in temporary files when a network outage occurred used to require manual configuration.
```

2022-07-01 13:13 UTC, chgautier requested changes

2022-07-01 13:13 UTC, chgautier commented on versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md
> +Got to **Configuration > Pollers > Broker configuration** and empty the value of "Failover name" parameter for each output of each broker configuration item.
```suggestion
Go to **Configuration > Pollers > Broker configuration** and empty the value of "Failover name" parameter for each output of each broker configuration item.
```

2022-07-01 13:13 UTC, chgautier commented on versioned_docs/version-21.10/upgrade/upgrade-from-3-4.md
> +Got to **Configuration > Pollers > Broker configuration** and empty the value of "Failover name" parameter for each output of each broker configuration item.
```suggestion
Go to **Configuration > Pollers > Broker configuration** and empty the value of "Failover name" parameter for each output of each broker configuration item.
```

2022-07-01 13:13 UTC, chgautier commented on versioned_docs/version-21.04/upgrade/upgrade-from-3-4.md
> +Got to **Configuration > Pollers > Broker configuration** and empty the value of "Failover name" parameter for each output of each broker configuration item.
```suggestion
Go to **Configuration > Pollers > Broker configuration** and empty the value of "Failover name" parameter for each output of each broker configuration item.
```

2022-07-06 13:11 UTC, chgautier submitted a review, later dismissed

2022-07-06 14:05 UTC, lpinsivy approved these changes

2022-07-06 14:16 UTC, cg-tw requested changes

2022-07-06 14:16 UTC, cg-tw commented on versioned_docs/version-21.10/upgrade/upgrade-from-3-4.md
> +Go to **Configuration > Pollers > Broker configuration** and empty the value of "Failover name" parameter for each output of each broker configuration item.
```suggestion
Go to **Configuration > Pollers > Broker configuration** and empty the value of the **Failover name** parameter for each output of each broker configuration item.
```

2022-07-06 14:16 UTC, cg-tw commented on versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md
> +Go to **Configuration > Pollers > Broker configuration** and empty the value of "Failover name" parameter for each output of each broker configuration item.
```suggestion
Go to **Configuration > Pollers > Broker configuration** and empty the value of the **Failover name** parameter for each output of each broker configuration item.
```

2022-07-06 14:20 UTC, lpinsivy approved these changes

2022-07-06 14:21 UTC, cg-tw approved these changes

2022-07-06 14:26 UTC, chgautier approved these changes

2022-07-07 07:04 UTC, merged