Debian 11 installation
centreon/centreon-documentation pull request #1625
Opened 2022-06-20 13:16 UTC by cg-tw

## Description

Debian 11 installation

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-06-24 07:02 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-poller/using-packages.md
> +apt install -y centreon-poller
```suggestion
apt install -y centreon-poller centreon-poller-centreon-engine
```

2022-06-24 08:19 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
> +apt install -y centreon-central
```suggestion
apt install -y centreon-central centreon-poller-centreon-engine
```

2022-06-24 08:20 UTC, Sims24 commented on versioned_docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
> +apt install -y centreon-central
```suggestion
apt install -y centreon-central centreon-poller-centreon-engine
```

2022-06-24 08:50 UTC, Sims24 submitted a review, later dismissed
Ca s'en va et ça revient! C'est fait de tout petits rien ...! 

Merci

2022-06-24 08:50 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
> +apt install -y centreon-central centreon-poller-centreon-engine
```suggestion
apt install -y centreon-central
```

2022-06-24 08:50 UTC, Sims24 commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-poller/using-packages.md
> +apt install -y centreon-poller centreon-poller-centreon-engine
```suggestion
apt install -y centreon-poller
```

2022-06-24 08:50 UTC, Sims24 commented on versioned_docs/version-22.04/installation/installation-of-a-poller/using-packages.md
> +apt install -y centreon-poller centreon-poller-centreon-engine
```suggestion
apt install -y centreon-poller
```

2022-06-28 15:51 UTC, thiuyendang approved these changes

2022-06-30 09:28 UTC, lpinsivy requested changes

2022-06-30 09:28 UTC, lpinsivy commented on versioned_docs/version-22.04/installation/web-and-post-installation.md
> +- **Database Host Address**: If you are using a local database, leave the field blank (the default value is **localhost**), or, if you are using Debian, enter 127.0.0.1. Otherwise, enter the IP addre
We fixed this in Broker, not necessary to put 127.0.0.1, localhost works correctly

2022-06-30 09:28 UTC, lpinsivy commented on versioned_docs/version-22.04/reporting/installation.md
> +sudo su
for other installation you don't put "sudo su"

2022-06-30 09:28 UTC, lpinsivy commented on versioned_docs/version-22.04/service-mapping/install.md
> +sudo apt update && sudo apt install centreon-bam-server
please remove "sudo" command

2022-06-30 09:28 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
> +echo "deb https://apt.centreon.com/repository/22.04/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/centreon.list
you missed:
Installez les dépendances suivantes :

```shell
apt update && apt install lsb-release ca-certificates apt-transport-https software-properties-common wget gnupg2
```

2022-06-30 09:28 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/web-and-post-installation.md
> +- **Database Host Address** : si vous utilisez une base de données locale, laissez ce champ vide (la valeur par défaut étant **localhost**), ou, si vous utilisez Debian, entrez 127.0.0.1. Sinon, rens
You can remove 127.0.0.1, it's work with localhost

2022-06-30 09:28 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
> +sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
please remove sudo

2022-07-01 07:04 UTC, thiuyendang approved these changes

2022-07-01 11:48 UTC, lpinsivy approved these changes

2022-07-01 19:07 UTC, tuntoja approved these changes

2022-07-01 19:26 UTC, merged