Add new GDPR Compliance topic in a new section named User data storage
centreon/centreon-documentation pull request #1630
Opened 2022-06-22 08:51 UTC by smau-centreon

## Description

Add GDPR Compliance topic
Translate into EN

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-06-22 10:07 UTC, cg-tw requested changes

2022-06-22 10:07 UTC, cg-tw commented on versioned_docs/version-22.04/security/user-data-storage/gdpr-compliance.md
> +If a user has the rights to configure the monitoring (defined in the user accesses), an entry in the logs stored in the database and linked to the
```suggestion
If a user has the rights to configure the monitoring (defined in the user's ACLs), an entry in the logs stored in the database and linked to the 
```

2022-06-22 10:28 UTC, cg-tw commented
@lpinsivy Is this topic only about MSPs?
Does it belong to the official doc, should be rename it, add more general info, etc.?

2022-07-05 07:26 UTC, lpinsivy approved these changes

2022-07-05 13:25 UTC, cg-tw approved these changes

2022-07-05 15:07 UTC, merged