Ps 34 manual ha installation Next
centreon/centreon-documentation pull request #1643
Opened 2022-07-04 11:05 UTC by cedricmeschin

## Description

Installation of centreon-HA Manual 2 nodes and 4 nodes in 22.10 (Next)
EN and FR versions
staging: https://github.com/centreon/centreon-documentation/pull/1585

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [X] 22.10.x (next)

2022-09-01 12:50 UTC, psamecentreon requested changes

2022-09-01 12:50 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
> +title: Intégrer des pollers dans un cluster Centreon-HA
```suggestion
title: Intégrer des Pollers dans un cluster Centreon-HA
```

2022-09-01 12:50 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
> +## Configuration de Gorgone sur le poller
```suggestion
## Configuration de Gorgone sur le Poller
```

2022-09-01 12:50 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
> +À ce stade, n'importe lequel des deux nœuds centraux doit pouvoir se connecter au service Gorgone du poller, et lui transmettre les nouvelles configurations engine/broker, redémarrer des services, ré
```suggestion
À ce stade, n'importe lequel des deux nœuds centraux doit pouvoir se connecter au service Gorgone du Poller, et lui transmettre les nouvelles configurations engine/broker, redémarrer des services, récupérer des statistiques...
```

2022-09-01 12:50 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
> +* `central-broker-master` : également appelé "central broker" ou "SQL broker", qui redirige toutes les entrées/sorties des pollers vers les bases de données, vers le broker RRD, etc.
```suggestion
* `central-broker-master` : également appelé "central broker" ou "SQL broker", qui redirige toutes les entrées/sorties des Pollers vers les bases de données, vers le broker RRD, etc.

```

2022-09-01 12:50 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
> +Dans un cluster Centreon-HA, les deux processus de broker seront chacun gérés par un service séparé qui sera piloté par le cluster :
```suggestion
Dans un cluster Centreon-HA, les deux processus de broker seront chacun géré par un service séparé qui sera piloté par le cluster :

```

2022-09-01 12:50 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
> +Une fois les actions des deux paragraphes précédents effectuées, la configuration doit être exportée (3 premières cases pour l'exportation du poller "Central") pour qu'elle soit effective.
```suggestion
Une fois les actions des deux paragraphes précédents effectuées, la configuration doit être exportée (3 premières cases pour l'exportation du Poller "Central") pour qu'elle soit effective.

```

2022-09-01 12:50 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
> +Ceci n'est peut-être pas connu de tous les utilisateurs de Centreon, mais à chaque fois qu'un rechargement de la configuration du poller central est effectué via l'interface, le service broker (`cbd`
```suggestion
Ceci n'est peut-être pas connu de tous les utilisateurs de Centreon, mais à chaque fois qu'un rechargement de la configuration du Poller central est effectué via l'interface, le service broker (`cbd`) est rechargé (et pas seulement centengine), d'où le paramètre "Centreon Broker reload command" dans *Configuration > Pollers > Central*.

```

2022-09-01 16:04 UTC, psamecentreon requested changes

2022-09-01 16:04 UTC, psamecentreon commented on versioned_docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
> +You can now [add your pollers](./integrating-pollers.md) and start monitoring!
```suggestion
You can now [add your Pollers](./integrating-pollers.md) and start monitoring!

```

2022-09-20 12:26 UTC, psamecentreon approved these changes

2022-09-20 14:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10.json
> +  "sidebar.docs.category.Installation of Centreon HA manual": {
```suggestion
  "sidebar.docs.category.Installation of a manual Centreon HA": {
```

2022-09-20 14:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
> +title: Intégrer des Pollers dans un cluster Centreon-HA
```suggestion
title: Intégrer des Pollers dans un cluster Centreon-HA
```
```suggestion
title: Intégrer des Pollers dans un cluster Centreon-HA manuel
```

2022-09-20 14:41 UTC, cg-tw commented on versioned_docs/version-22.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
> +title: Integrating new Pollers in a Centreon-HA cluster
```suggestion
title: Integrating new Pollers in a manual Centreon-HA cluster
```

2022-09-20 14:41 UTC, cg-tw commented on versioned_sidebars/version-22.10-sidebars.json
> +          "label": "Installation of Centreon HA manual",
```suggestion
          "label": "Installation of a manual Centreon HA",
```

2022-09-20 14:45 UTC, psamecentreon approved these changes

2022-09-20 16:09 UTC, merged