(debian) no need to remove this file
centreon/centreon-documentation pull request #1644
Opened 2022-07-04 15:49 UTC by lgcosta

## Description

It is not necessary to remove this file, the same is already done in the postinstall of the `centreon-web` package and it removes the symbolic link from the `/etc/apache2/sites-enabled` directory that activates the configuration in apache.

https://github.com/centreon/centreon/blob/release-debian-22.04/ci/debian/centreon-web-apache.postinst#L13

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-07-04 15:50 UTC, zguennoune02 submitted a review, later dismissed

2022-07-05 09:02 UTC, psamecentreon submitted a review, later dismissed

2022-07-05 09:27 UTC, chgautier requested changes
the post inst didn't remove the conf file, just checked on stable packages
![image](https://user-images.githubusercontent.com/33026375/177297113-d25d3bb5-a0f6-4620-8bae-2730da3bcf1a.png)

2022-07-05 09:47 UTC, lgcosta commented
> the post inst didn't remove the conf file, just checked on stable packages ![image](https://user-images.githubusercontent.com/33026375/177297113-d25d3bb5-a0f6-4620-8bae-2730da3bcf1a.png)

But it is not necessary to remove. What activates this setting is the symbolic link in `/etc/apache2/sites-enabled`

2022-07-05 09:49 UTC, chgautier submitted a review, later dismissed

2022-07-05 10:20 UTC, lgcosta commented
thanks @cg-tw

2022-07-05 12:11 UTC, psamecentreon approved these changes

2022-07-05 12:11 UTC, zguennoune02 approved these changes

2022-07-05 12:25 UTC, merged