enh(documentation): Improve installation chapters
centreon/centreon-documentation pull request #1672
Opened 2022-07-19 13:20 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-07-20 15:24 UTC, smau-centreon submitted a review, later dismissed

2022-07-21 13:09 UTC, smau-centreon requested changes

2022-07-21 13:09 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-poller/using-packages.md
> +## Étape 5 : Sécurisez votre plateforme
```suggestion
## Étape 5 : Sécuriser votre plateforme
```

2022-07-25 13:44 UTC, smau-centreon approved these changes

2022-08-04 08:35 UTC, cg-tw requested changes

2022-08-04 08:35 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
> +Enfin, dans la base de données distante, créer un utilisateur avec privilèges **root**. Renseignez cet utilisateur pendant le processus d'installation web (à [l'étape 6](../web-and-post-installation.
```suggestion
Enfin, dans la base de données distante, créez un utilisateur avec privilèges **root**. Renseignez cet utilisateur pendant le processus d'installation web (à [l'étape 6](../web-and-post-installation.md#étape-6--database-information), dans les champs **Root user** et **Root password**).
```

2022-08-04 08:35 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
> +Activer PHP 8.0 en utilisant les commandes suivantes :
```suggestion
Activez PHP 8.0 en utilisant les commandes suivantes :
```

2022-08-04 08:35 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
> +Exécutez la commande suivante :
Why not as root?

2022-08-04 08:35 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md
> +**/etc/selinux/config** et remplacer **enforcing** par **disabled**, ou bien
```suggestion
**/etc/selinux/config** et remplacez **enforcing** par **disabled**, ou bien
```

2022-08-04 08:35 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md
> +Depuis MariaDB 10.5, il est obligatoire de sécuriser l'accès en root à la base avant d'installer Centreon. Si vous utilisez une base de données locale, exécuter la commande suivante sur le serveur ce
```suggestion
Depuis MariaDB 10.5, il est obligatoire de sécuriser l'accès en root à la base avant d'installer Centreon. Si vous utilisez une base de données locale, exécutez la commande suivante sur le serveur central :
```

2022-08-04 08:42 UTC, smau-centreon approved these changes

2022-08-05 16:30 UTC, thiuyendang approved these changes

2022-08-05 16:40 UTC, cg-tw approved these changes

2022-08-08 07:28 UTC, smau-centreon approved these changes

2022-08-08 08:51 UTC, merged