enh(release): Add Centreon Web 22.04.1 RN
centreon/centreon-documentation pull request #1682
Opened 2022-07-25 14:21 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-07-25 15:54 UTC, smau-centreon requested changes

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Authentication] Allow to automatically import new users using OpenId Connect protocol
```suggestion
- [Authentication] Added the permission to import automatically new users using the OpenId Connect protocol
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Authentication] Apply ACL Group(s) definition on login for OpenID Connect users
```suggestion
- [Authentication] Applied an ACL Group(s) definition on login for OpenID Connect users
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Handle properly the switch between Resource Status repositories
```suggestion
- [Core] Properly managed the switch between Resource Status repositories
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [UX] Improved OpenId Connect form
```suggestion
- [UX] Improved the OpenId Connect form
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Administration] Fixed display of the end date of the licenses
```suggestion
- [Administration] Fixed the display of the end date of the licenses
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Administration] Fixed scroll when reduce screen size to access to all items
```suggestion
- [Administration] Fixed the scrolling when reducing the screen size to access all items
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Fixed export when service group disabled
```suggestion
- [Configuration] Fixed the export when the service group is disabled
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Fixed export when service template disabled
```suggestion
- [Configuration] Fixed the export when the service template is disabled
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] When a host receives no host template from the mappers, the default template that is hard-coded in the Plugin Pack will be applied to this host
Not sure to understand this one. What was the issue exactly?

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Database partitioning fixed for MySQL 8
```suggestion
- [Core] Fixed the database partitioning for MySQL 8
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Fixed SQL queries when databases names contain dash
```suggestion
- [Core] Fixed SQL queries when databases names contained a dash
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Install] Fixed waterfall visual effect in extension details tile
```suggestion
- [Install] Fixed the waterfall visual effect in the extension's details tile
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Monitoring] Fixed notification number in legacy pages
'the number of notifications' or 'the notification number'?

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Resources Status] Fixed timeperiod group button and custom period selectors heights
```suggestion
- [Resources Status] Fixed the timeperiod group button and custom period selectors heights
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [UI] Close the menu when a navigation item is clicked
```suggestion
- [UI] Now close the menu when a navigation item is clicked
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [UI] Fixed display of CSS code with Firefox browser
```suggestion
- [UI] Fixed the display of CSS code with Firefox browser
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [UX] Reduce the timeout preventing from closing the menu unexpectedly
```suggestion
- [UX] Reduced the timeout to prevent the menu from closing unexpectedly
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Widget] Use ACL to get list of poller to filter display of services
What was the issue exactly?

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Administration] Sanitize and bind ACL Group queries
```suggestion
- [Administration] Sanitized and bound ACL Group queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Administration] Sanitize and bind ACL resources queries
```suggestion
- [Administration] Sanitized and bound ACL resources queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Administration] Sanitize and bind escalation form queries
```suggestion
- [Administration] Sanitized and bound escalation form queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind "User" class queries
```suggestion
- [Configuration] Sanitized and bound "User" class queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind "downtime" queries
```suggestion
- [Configuration] Sanitized and bound "downtime" queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind "hostgroups" queries
```suggestion
- [Configuration] Sanitized and bound "hostgroups" queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind "hosts" queries
```suggestion
- [Configuration] Sanitized and bound "hosts" queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind "meta_service" related queries
```suggestion
- [Configuration] Sanitized and bound "meta_service" related queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind "poller" queries
```suggestion
- [Configuration] Sanitized and bound "poller" queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind "pollers" queries
```suggestion
- [Configuration] Sanitized and bound "pollers" queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind contact form queries
```suggestion
- [Configuration] Sanitized and bound contact form queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitize and bind timeperiod form queries
```suggestion
- [Configuration] Sanitized and bound timeperiod form queries
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Remove deprecated switch in encodePass() method
```suggestion
- [Core] Removed deprecated switch in encodePass() method
```

2022-07-25 15:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Updated PHP libraries for security issue
```suggestion
- [Core] Updated PHP libraries for security issues
```

2022-07-25 15:59 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Updated PHP libraries for security issue
Requested changes to be applied on the 2nd same file as well.

2022-07-26 09:26 UTC, smau-centreon requested changes

2022-07-26 09:26 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Re-added href link in menus
'Fixed href on links that were broken in menus'?

2022-07-26 09:26 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Widget] Use ACL to get list of poller in widget configuration to filter display of services
Still unable to understand the fixed issue here

2022-07-26 12:33 UTC, smau-centreon approved these changes

2022-07-27 10:10 UTC, thiuyendang approved these changes

2022-07-27 14:06 UTC, thiuyendang approved these changes

2022-07-27 14:20 UTC, smau-centreon requested changes

2022-07-27 14:20 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Administration] Fixed consistency of ACLs with new poller creation wizard structure
```suggestion
- [Administration] Added consistency in ACLs with the new structure of the poller creation wizard
```

2022-07-27 14:20 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Administration] Fixed consistency of ACLs with new poller creation wizard structure
```suggestion
- [Administration] Added consistency in ACLs with the new structure of the poller creation wizard
```

2022-07-27 14:42 UTC, smau-centreon approved these changes

2022-07-28 13:13 UTC, thiuyendang approved these changes

2022-07-28 14:39 UTC, chgautier requested changes

2022-07-28 14:39 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +
```suggestion

Release date: `July 28, 2022`

```

2022-07-28 14:39 UTC, chgautier commented on versioned_docs/version-22.04/releases/centreon-core.md
> +
```suggestion

Release date: `July 28, 2022`

```

2022-07-28 14:46 UTC, chgautier approved these changes

2022-07-28 14:46 UTC, thiuyendang approved these changes

2022-07-28 15:16 UTC, merged