enh(release): Add Centreon Web 22.04.2 RN
centreon/centreon-documentation pull request #1699
Opened 2022-08-02 14:55 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-08-02 15:07 UTC, cg-tw requested changes

2022-08-03 13:17 UTC, thiuyendang submitted a review, later dismissed

2022-08-03 13:21 UTC, thiuyendang approved these changes

2022-08-03 16:38 UTC, chgautier requested changes

2022-08-03 16:38 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +
```suggestion

Release date: `August 3, 2022`

```

2022-08-03 16:38 UTC, chgautier commented on versioned_docs/version-22.04/releases/centreon-core.md
> +
```suggestion

Release date: `August 3, 2022`

```

2022-08-03 16:39 UTC, chgautier submitted a review, later dismissed

2022-08-03 16:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +Release date: `August 3, 2022`
```suggestion
Release date: `August 3, 2022`

```

2022-08-03 16:41 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +Release date: `August 3, 2022`
```suggestion
Release date: `August 3, 2022`

```

2022-08-03 16:43 UTC, thiuyendang approved these changes

2022-08-03 16:45 UTC, cg-tw approved these changes

2022-08-03 16:57 UTC, chgautier approved these changes

2022-08-03 17:19 UTC, merged