(wip) New setup section
centreon/centreon-documentation pull request #1718
Opened 2022-08-08 20:18 UTC by Sims24

## Description

New setup section to manage all supported package manager.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [x] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-08-09 08:21 UTC, cg-tw requested changes

2022-08-09 08:21 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +instruction below as it is not required to have the Pack displayed within the
```suggestion
instruction below as it is not required to have the pack displayed within the 
```

2022-08-09 08:21 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +Use amongst commands below according to your operating system's package manager:
```suggestion
Use the commands below according to your operating system's package manager: 
```

2022-08-09 08:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +Si la plateforme est configurée avec une licence *online*. L'installation d'un paquet
```suggestion
Si la plateforme est configurée avec une licence *online*, l'installation d'un paquet 
```

2022-08-09 08:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +n'est pas requise pour voir apparaître le Pack dans le menu **Configuration > Plugin Packs > Gestionnaire**
```suggestion
n'est pas requise pour voir apparaître le pack dans le menu **Configuration > Plugin Packs > Gestionnaire**.
```

2022-08-09 08:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +sur le **serveur central** via la commande correspondante au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2022-08-09 08:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +Quelque soit le type de la licence (*online* ou *offline*), installer le Pack *DRBD SSH*
```suggestion
Quel que soit le type de la licence (*online* ou *offline*), installez le Pack **DRBD SSH** 
```

2022-08-09 08:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +A partir de Centreon 22.04, il est possible de demander le déploiement automatique
```suggestion
À partir de Centreon 22.04, il est possible de demander le déploiement automatique 
```

2022-08-09 08:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +du plugin lors de l'utilisation d'un Pack. Si cette fonctionnalité est activée, et
```suggestion
du plugin lors de l'utilisation d'un pack. Si cette fonctionnalité est activée, et 
```

2022-08-09 08:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +associé à sa distribution:
This new presentation is not user-friendly

2022-08-09 10:04 UTC, cg-tw requested changes

2022-08-09 10:04 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +<TabItem value="RHEL, Oracle Linux, Alma Linux version >= 8" label="RHEL, Oracle Linux, Alma Linux version >= 8">
Non mais en fait faut mettre explicitement les numéros des versions supportées, sinon ça sous-entend qu'on supporte tout au-dessus ou au-dessous de la version 8, donc c'est pas bon

2022-08-09 11:41 UTC, cg-tw requested changes

2022-08-09 11:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +```bash title='RHEL, Oracle Linux, Alma Linux version >= 8'
Same comment as the previous one... And the tabs are enough, you don't need a title there.

2022-08-10 08:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +Au contraire, si la plateforme utilise une licence *offline*, installer le paquet
```suggestion
Au contraire, si la plateforme utilise une licence *offline*, installez le paquet 
```

2022-08-10 08:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +À partir de Centreon 22.04, il est possible de demander le déploiement automatique
link?

2022-10-03 13:21 UTC, Sims24 commented
Will be outdated.

2022-10-03 13:21 UTC, closed without merging