PS-88 Update-centreon-HA-monitoring for resource php
centreon/centreon-documentation pull request #1739
Opened 2022-08-16 10:40 UTC by cedricmeschin

## Description

Update centreon HA monitoring procedure for php resource

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [] 22.04.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-08-16 12:15 UTC, MaxCentreon approved these changes

2022-08-16 12:21 UTC, cg-tw requested changes

2022-08-16 12:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-ha.md
>  * état des ressource :
```suggestion
* état des ressources :
```

2022-08-16 13:31 UTC, cg-tw approved these changes

2022-08-16 13:33 UTC, MaxCentreon submitted a review, later dismissed

2022-08-17 07:33 UTC, MaxCentreon approved these changes

2022-08-18 09:51 UTC, cg-tw approved these changes

2022-08-18 11:09 UTC, merged