enh(epp): aruba aoscx snmp - update doc
centreon/centreon-documentation pull request #1742
Opened 2022-08-17 14:54 UTC by garnier-quentin

## Description

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-08-17 14:56 UTC, lchrdn submitted a review, later dismissed

2022-08-17 16:57 UTC, cg-tw requested changes

2022-08-17 16:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
> +* Complétez les champs **Nom**, **Alias** & **IP Address / DNS** correspondant à votre équipement **ArubaOS-CX**.
```suggestion
* Complétez les champs **Nom**, **Alias** et **IP Address / DNS** correspondant à votre équipement **ArubaOS-CX**.
```

2022-08-17 16:57 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
> +* Fill the **Name**, **Alias** & **IP Address / DNS** fields according to your **ArubaOS-CX** equipment settings.
```suggestion
* Fill the **Name**, **Alias** and **IP Address / DNS** fields according to your **ArubaOS-CX** equipment settings.
```

2022-08-18 08:54 UTC, cg-tw approved these changes

2022-08-18 09:05 UTC, lchrdn approved these changes

2022-08-18 10:01 UTC, merged