New filters in Resources Status (22.10)
centreon/centreon-documentation pull request #1743
Opened 2022-08-18 08:36 UTC by cg-tw

## Description

New filters in Resources Status (22.10)

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 22.10.x (next)

2022-08-19 08:32 UTC, mdebauchez requested changes

2022-08-19 08:32 UTC, mdebauchez commented on versioned_docs/version-22.10/alerts-notifications/resources-status.md
> +    - [Service category](../monitoring/categories.md)
Filters name (line 123 to 128) should be in bold like the previous ones

2022-08-19 08:32 UTC, mdebauchez commented on versioned_docs/version-22.10/alerts-notifications/resources-status.md
> +    - Host [severity](../monitoring/categories.md): name of the host severity
Why the "Host" is not in the link like "Service Severity" line 127

2022-08-19 08:32 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/alerts-notifications/resources-status.md
> +    - [Criticité] d'hôte(../monitoring/categories.md): nom de la criticité de l'hôte
This link does not work and "d'hôte" should also be in the link

2022-08-19 08:32 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/alerts-notifications/resources-status.md
> +    - Niveau de criticité du service
Filters name (line 129 to 132) should be in bold like the previous ones

2022-08-19 08:56 UTC, mdebauchez approved these changes

2022-09-06 08:25 UTC, tuntoja approved these changes

2022-09-06 09:51 UTC, merged