enh(release): Add Centreon Web 21.04.17 RN
centreon/centreon-documentation pull request #1748
Opened 2022-08-19 11:59 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [x] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-08-19 12:29 UTC, cg-tw requested changes

2022-08-19 12:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Configuration] Fixed a XSS vulnerability in the broker configuration page
```suggestion
- [Configuration] Fixed an XSS vulnerability in the Broker configuration page
```

2022-08-19 12:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
> +- [Administration] Sanitized and bound ACL Group queries
```suggestion
- [Administration] Sanitized and bound ACL group queries
```

2022-08-19 12:29 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Administration] Sanitized and bound ACL Group queries
```suggestion
- [Administration] Sanitized and bound ACL group queries
```

2022-08-19 12:29 UTC, cg-tw commented on versioned_docs/version-21.04/releases/centreon-core.md
> +- [Configuration] Fixed a XSS vulnerability in the broker configuration page
```suggestion
- [Configuration] Fixed an XSS vulnerability in the Broker configuration page
```

2022-08-20 14:10 UTC, thiuyendang approved these changes

2022-08-22 07:25 UTC, cg-tw approved these changes

2022-08-22 07:47 UTC, mdebauchez approved these changes

2022-08-22 08:30 UTC, merged