enh(release): Add Centreon Web 22.04.3 RN
centreon/centreon-documentation pull request #1754
Opened 2022-08-22 10:54 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-08-22 12:43 UTC, cg-tw requested changes

2022-08-22 12:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Cron] Fixed SQL queries when databases names contain dash
```suggestion
- [Cron] Fixed SQL queries when database names contain a dash
```

2022-08-22 12:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Install] Allow to connect as centreon-engine user for Debian packaging
```suggestion
- [Install] Make it possible to connect as user centreon-engine for Debian packaging
```

2022-08-22 12:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Fixed a XSS vulnerability in the broker configuration page
```suggestion
- [Configuration] Fixed an XSS vulnerability in the Broker configuration page
```

2022-08-22 12:43 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Cron] Fixed SQL queries when databases names contain dash
```suggestion
- [Cron] Fixed SQL queries when database names contain a dash
```

2022-08-22 12:43 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Install] Allow to connect as centreon-engine user for Debian packaging
```suggestion
- [Install] Make it possible to connect as user centreon-engine for Debian packaging
```

2022-08-22 12:43 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Fixed a XSS vulnerability in the broker configuration page
```suggestion
- [Configuration] Fixed an XSS vulnerability in the broker configuration page
```

2022-08-22 15:04 UTC, cg-tw requested changes

2022-08-22 15:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [UI] Fixed OpenId configuration form with Safari
```suggestion
- [UI] Fixed OpenID configuration form with Safari
```

2022-08-22 15:04 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [UI] Fixed OpenId configuration form with Safari
```suggestion
- [UI] Fixed OpenID configuration form with Safari
```

2022-08-22 15:24 UTC, cg-tw submitted a review, later dismissed

2022-08-25 14:15 UTC, chgautier requested changes

2022-08-25 14:15 UTC, chgautier commented on versioned_docs/version-22.04/releases/centreon-core.md
> +
```suggestion

Release date: `August 25, 2022`

```

2022-08-25 14:15 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +
```suggestion

Release date: `August 25, 2022`

```

2022-08-25 14:26 UTC, chgautier approved these changes

2022-08-25 14:29 UTC, cg-tw approved these changes

2022-08-25 15:08 UTC, merged