enh(release): Add Centreon Web 21.10.9 RN
centreon/centreon-documentation pull request #1755
Opened 2022-08-22 11:04 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-08-22 14:34 UTC, cg-tw requested changes

2022-08-22 14:34 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Administration] Sanitized and bound ACL Group queries
```suggestion
- [Administration] Sanitized and bound ACL group queries
```

2022-08-22 14:34 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed a XSS vulnerability in the broker configuration page
```suggestion
- [Configuration] Fixed an XSS vulnerability in the Broker configuration page
```

2022-08-22 14:34 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Core] Clean code in centreonUser.class.php
```suggestion
- [Core] Cleaned code in centreonUser.class.php
```

2022-08-22 14:34 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Administration] Sanitized and bound ACL Group queries
```suggestion
- [Administration] Sanitized and bound ACL group queries
```

2022-08-22 14:34 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Configuration] Fixed a XSS vulnerability in the broker configuration page
```suggestion
- [Configuration] Fixed an XSS vulnerability in the Broker configuration page
```

2022-08-22 14:34 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Core] Clean code in centreonUser.class.php
```suggestion
- [Core] Cleaned code in centreonUser.class.php
```

2022-08-22 14:39 UTC, cg-tw submitted a review, later dismissed

2022-08-26 14:27 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `August 26, 2022`

```

2022-08-26 14:27 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `August 26, 2022`

```

2022-08-26 14:28 UTC, chgautier approved these changes

2022-08-26 14:59 UTC, cg-tw approved these changes

2022-08-26 15:03 UTC, merged