enh(release): Add Centreon Web 22.04.4 RN
centreon/centreon-documentation pull request #1778
Opened 2022-09-01 08:48 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-09-01 08:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Install] Fixed update process showing unable to execute SQL query
```suggestion
- [Install] Fixed update process that threw an "unable to execute SQL query" error
```

2022-09-01 08:55 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Install] Fixed update process showing unable to execute SQL query
```suggestion
- [Install] Fixed update process that threw an "unable to execute SQL query" error
```

2022-09-01 09:33 UTC, cg-tw submitted a review, later dismissed

2022-09-02 15:25 UTC, chgautier requested changes

2022-09-02 15:25 UTC, chgautier approved these changes

2022-09-02 15:26 UTC, tuntoja approved these changes

2022-09-02 16:11 UTC, cg-tw approved these changes

2022-09-02 16:12 UTC, merged