Perform Centreon update via API
centreon/centreon-documentation pull request #1783
Opened 2022-09-01 15:35 UTC by smau-centreon

## Description

Perform Centreon update via API

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-09-01 15:46 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
> +apt clean all
```suggestion
apt clean all
apt update
```

2022-09-01 15:48 UTC, lpinsivy requested changes

2022-09-01 15:48 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
> +apt install centreon\*
```suggestion
apt upgrade centreon\*
```

2022-09-01 15:48 UTC, lpinsivy commented on versioned_docs/version-22.04/update/update-centreon-platform.md
> +apt install centreon\*
```suggestion
apt upgrade centreon\*
```

2022-09-01 15:48 UTC, lpinsivy commented on versioned_docs/version-22.04/update/update-centreon-platform.md
> +apt clean all
```suggestion
apt clean all
apt update

```

2022-09-08 13:03 UTC, paul-oureib commented on versioned_docs/version-22.04/update/update-centreon-platform.md
> +#### Finalize the update using wizard
#### Finalize the update using the wizard

2022-09-08 13:09 UTC, paul-oureib commented on versioned_docs/version-22.04/update/update-centreon-platform.md
> +
line 63 is an empty, superfluous line within the code snippet

2022-09-08 13:09 UTC, paul-oureib commented on versioned_docs/version-22.04/update/update-centreon-platform.md
> +#### Finalize the update using API endpoint
#### Finalize the update using the API endpoint

2022-09-08 13:11 UTC, paul-oureib commented on versioned_docs/version-22.04/update/update-centreon-platform.md
> +This is how the result should look like:
This is what* the result should look like

2022-09-08 13:17 UTC, paul-oureib commented on versioned_docs/version-22.04/update/update-centreon-platform.md
> +> - [Using a dedicated API endpoint](#finalize-the-update-using-api-endpoint)
Now you can either perform the update: 
- [Using the wizard](#finalize-the-update-using-the-wizard)
- [Using a dedicated API endpoint](#finalize-the-update-using-the-api-endpoint)

2022-09-08 13:19 UTC, paul-oureib commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
> +Voici ce à quoi le résultat ressemble :
Voici à quoi ressemble le résultat :

2022-09-08 13:20 UTC, paul-oureib commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
> +Vous avez besoin d'un token d'authentification pour accéder au endpoint de l'API. Suivez cette procédure pour obtenir un numéro de token.
Vous avez besoin d'un token d'authentification pour accéder à l'endpoint de l'API. Suivez cette procédure pour obtenir un token.

2022-09-08 16:01 UTC, cg-tw requested changes

2022-09-12 12:37 UTC, cg-tw approved these changes

2022-09-12 13:23 UTC, cg-tw approved these changes

2022-09-12 13:31 UTC, paul-oureib approved these changes

2022-09-12 13:32 UTC, merged