Release notes for version 22.10
centreon/centreon-documentation pull request #1806
Opened 2022-09-09 12:15 UTC by cg-tw

## Description

Release notes for version 22.10

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 22.10.x (next)

2022-09-19 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [UX] Changing themes is now available by clicking on the profile icon.
```suggestion
- [UX] Changing themes is now possible by clicking on the profile icon.
```

2022-09-19 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +> The configuration of authorizations via the OpenId Connect protocol has evolved. Automatic addition to a contact
```suggestion
> The configuration of authorizations via the OpenID Connect protocol has evolved. Automatic addition to a contact
```

2022-09-19 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +> group and role management have been improved. It is necessary to review your OpenId Connect configuration.
```suggestion
> group and role management have been improved. It is necessary to review your OpenID Connect configuration.
```

2022-09-19 16:52 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [ACL] Updated ACL actions in real time for connected users
```suggestion
- [ACL] ACLs on actions are now updated in real time for connected users
```

2022-09-19 16:52 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +  - Automatic management of relationships between a user and groups of contacts based on values from the identity provider
```suggestion
  - Automatic management of relationships between a user and contact groups based on values retrieved from the identity provider
```

2022-09-19 16:52 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Install] Removed "Centreon Web Directory" parameter to use Apache configuration
```suggestion
- [Install] Removed "Centreon Web Directory" parameter and use Apache configuration instead
```

2022-09-19 16:52 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [UX] Changing themes is now available by clicking on the profile icon.
```suggestion
- [UX] Changing themes is now possible by clicking on the profile icon.
```

2022-09-19 16:52 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +> The configuration of authorizations via the OpenId Connect protocol has evolved. Automatic addition to a contact
```suggestion
> The configuration of authorizations via the OpenID Connect protocol has evolved. Automatic addition to a contact
```

2022-09-19 16:52 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +> group and role management have been improved. It is necessary to review your OpenId Connect configuration.
```suggestion
> group and role management have been improved. It is necessary to review your OpenID Connect configuration.
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [UX] The quick export button is now available by default for all users that have the admin privilege or the required ACL action acces. Deploying a configuration is now simpler for all users!
```suggestion
- [UX] The quick export button is now available by default for all users that have the admin privilege or the required ACL action access. Deploying a configuration is now simpler for all users.
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Configuration] New Broker input/output stream types available, designed to support the new gRPC stream capability of Broker, but can also be used for legacy BBDO over TCP protocol:
```suggestion
- [Configuration] New Broker input/output stream types available, designed to support the new gRPC stream capability of Broker, but that can also be used for the legacy BBDO over TCP protocol:
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Downtimes of regular services are now propageted to related Anomaly Detection service(s)
```suggestion
- Downtimes on regular services are now propagated to related Anomaly Detection service(s)
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Observations on platforms in the field showed us that the default maximum number of queries per transaction (10000) was too high and caused too much delay, so we set it 2000 by default
```suggestion
- Observations on platforms in the field showed us that the default maximum number of queries per transaction (10000) was too high and caused too much delay, so we set it to 2000 by default
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Calls to `atoi()` C function have been replaced by more secured functions
```suggestion
- Calls to the `atoi()` C function have been replaced by more secure functions
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Two new broker streams are available, meant to provide simpler configuration and support of gRPC protocol.
```suggestion
- Two new broker streams are available, meant to provide simpler configuration and support of the gRPC protocol.
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +###### Imrpoving communication
```suggestion
###### Improved communication
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Calls to `atoi()` C function have been replaced by more secured functions
```suggestion
- Calls to the `atoi()` C function have been replaced by more secure functions
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Any residues of a deleted poller can be removed definitely thanks to `RemovePoller {}` gRPC command
```suggestion
- All traces of a deleted poller can be removed permanently thanks to the `RemovePoller {}` gRPC command
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- The log levels can be accessed and changed without reloading thanks to `GetLogInfo {}` and `SetLogLevel {"logger": "<logger>", "level": "<log level>"}` gRPC commands
```suggestion
- The log levels can be accessed and changed without reloading thanks to the `GetLogInfo {}` and `SetLogLevel {"logger": "<logger>", "level": "<log level>"}` gRPC commands
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Already monitored hosts can now be updated by Host Discovery in manual mode. It had been made available in automatic mode in the [22.04 release](../../22.04/releases/centreon-commercial-extensions/
```suggestion
- Already monitored hosts can now be updated by Host Discovery in manual mode. It had been made available in automatic mode in the [22.04 release](../../22.04/releases/centreon-commercial-extensions/#centreon-auto-discovery), it is now available in manual mode. Changes can be made to macros, templates, host groups, host categories, host severity and the monitoring server
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed a typo in the french translation of the Host Discovery job creation wizeard
```suggestion
- Fixed a typo in the French translation of the Host Discovery job creation wizard
```

2022-10-17 10:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Install] Addition of dependency management between modules during installation, update and deletion
```suggestion
- [Install] Added dependency management between modules during installation, update and deletion
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Already monitored hosts can now be updated by Host Discovery in manual mode. It had been made available in automatic mode in the [22.04 release](../../22.04/releases/centreon-commercial-extensions/
```suggestion
- Already monitored hosts can now be updated by Host Discovery in manual mode. It had been made available in automatic mode in the [22.04 release](../../22.04/releases/centreon-commercial-extensions/#centreon-auto-discovery), it is now available in manual mode. Changes can be made to macros, templates, host groups, host categories, host severity and the monitoring server
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed a typo in the french translation of the Host Discovery job creation wizeard
```suggestion
- Fixed a typo in the French translation of the Host Discovery job creation wizard
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Install] Addition of dependency management between modules during installation, update and deletion
```suggestion
- [Install] Added dependency management between modules during installation, update and deletion
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [UX] The quick export button is now available by default for all users that have the admin privilege or the required ACL action acces. Deploying a configuration is now simpler for all users!
```suggestion
- [UX] The quick export button is now available by default for all users that have the admin privilege or the required ACL action access. Deploying a configuration is now simpler for all users.
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Configuration] New Broker input/output stream types available, designed to support the new gRPC stream capability of Broker, but can also be used for legacy BBDO over TCP protocol:
```suggestion
- [Configuration] New Broker input/output stream types available, designed to support the new gRPC stream capability of Broker, but that can also be used for the legacy BBDO over TCP protocol:
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Downtimes of regular services are now propageted to related Anomaly Detection service(s)
```suggestion
- Downtimes on regular services are now propagated to related Anomaly Detection service(s)
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Observations on platforms in the field showed us that the default maximum number of queries per transaction (10000) was too high and caused too much delay, so we set it 2000 by default
```suggestion
- Observations on platforms in the field showed us that the default maximum number of queries per transaction (10000) was too high and caused too much delay, so we set it to 2000 by default
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Imrpoving communication
```suggestion
###### Improved communication
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Calls to `atoi()` C function have been replaced by more secured functions
```suggestion
- Calls to the `atoi()` C function have been replaced by more secure functions
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Two new broker streams are available, meant to provide simpler configuration and support of gRPC protocol.
```suggestion
- Two new broker streams are available, meant to provide simpler configuration and support of the gRPC protocol.
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- The log levels can be accessed and changed without reloading thanks to `GetLogInfo {}` and `SetLogLevel {"logger": "<logger>", "level": "<log level>"}` gRPC commands
```suggestion
- The log levels can be accessed and changed without reloading thanks to the `GetLogInfo {}` and `SetLogLevel {"logger": "<logger>", "level": "<log level>"}` gRPC commands
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Any residues of a deleted poller can be removed definitely thanks to `RemovePoller {}` gRPC command
```suggestion
- All traces of a deleted poller can be removed permanently thanks to the `RemovePoller {}` gRPC command
```

2022-10-17 10:51 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Calls to `atoi()` C function have been replaced by more secured functions
```suggestion
- Calls to the `atoi()` C function have been replaced by more secure functions
```

2022-10-24 13:02 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Event logs] Rework CSV exporter in event logs to manage high volumetry
Reworked

2022-10-24 13:02 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Resources Status] Introduce CSV export in Timeline and Graphs
Introduced

2022-10-24 13:03 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Resources Status] New Parent Alias column and filter in listing for services
Added new Parent Alias column and filter in listing for services

2022-10-24 13:06 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Resources Status] Timeline UI in Resources Status cosmetic enhancements
Added timeline UI in Resources Status cosmetic enhancements

2022-10-24 13:06 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Anomaly Detection] New type of resources in Resource Status (display and filter)
Added new type of resources in Resource Status (display and filter)

2022-10-24 13:07 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Anomaly Detection] Prediction enveloppe size management by user from Resources Status
Added prediction enveloppe size management by user from Resources Status

2022-10-24 13:10 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +> In /monitoring/resources API, ‘severity_level’ api return key has been replaced by a json object ‘severity’ containing id, level, name and icon
The sentence is missing a period.

2022-10-24 13:19 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Anomaly Detection improvements
Title to remove and add prefixes instead on each item: [Anomaly Detection] or [Ano-Detection]?

2022-10-24 13:24 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Settings improvements
Title to remove and add prefixes instead on each item: [Settings]

2022-10-24 13:25 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Change the log level of some notification log messages
Changed

2022-10-24 13:33 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Observations on platforms in the field showed us that the default maximum number of queries per transaction (10000) was too high and caused too much delay, so we set it to 2000 by default
Optimized the delay time by setting the default maximum number of queries per transaction in the (what field?) field to 2000

2022-10-24 13:33 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Code improvements
Title to remove and add prefixes instead on each item: [Code]

2022-10-24 13:34 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Improved communication
Title to remove and add prefixes instead on each item: [Communication]

2022-10-24 13:35 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Two new broker streams are available, meant to provide simpler configuration and support of the gRPC protocol.
Added two new Broker streams to provide simpler configuration and support the gRPC protocol

2022-10-24 13:36 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- It is now possible to limit the maximum total size of Broker retention files using the `event_queues_total_size` global parameter
Added the ability to limit the maximum total size of Broker retention files using the `event_queues_total_size` global parameter

2022-10-24 13:38 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- The default `retry_interval` has been changed from 60 to 15, in the configuration WUI as well as in the source code for a shorter time to reconnect
Changed the default `retry_interval` from 60 to 15, in the configuration WUI...

2022-10-24 13:39 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### gRPC API features
Title to remove and add prefixes instead on each item: [gRPC API]

2022-10-24 13:40 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Code improvements
Title to remove and add prefixes instead on each item: [Code]

2022-10-24 13:41 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +
Add "Compatibility with other 22.10 components."?

2022-10-24 13:42 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +#### Enhancements
Remove this title

2022-10-24 13:48 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed a typo in the French translation of the Host Discovery job creation wizard
This item is not an enhancement but a bug fix. Should not be included here.

2022-10-24 13:52 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
>  #### Enhancements
Remove "Enhancements" and add "Compatibility with other 22.10 components."?

2022-10-24 13:53 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +### 22.10.0
Add "Compatibility with other 22.10 components."?

2022-10-24 13:53 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Add "Compatibility with other 22.10 components."?

2022-10-25 09:58 UTC, smau-centreon requested changes

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed a typo in the French translation of the Host Discovery job creation wizard
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed a typo in the French translation of the Host Discovery job creation wizard
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
>  #### Enhancements
```suggestion
Compatibility with other 22.10 components.
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +### 22.10.0
```suggestion
### 22.10.0

Compatibility with other 22.10 components.
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Downtimes on regular services are now propagated to related Anomaly Detection service(s)
```suggestion
- [Anomaly Detection] Downtimes on regular services are now propagated to related Anomaly Detection service(s)
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Change the log level of some notification log messages
```suggestion
- [Settings] Changed the log level of some notification log messages
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Observations on platforms in the field showed us that the default maximum number of queries per transaction (10000) was too high and caused too much delay, so we set it to 2000 by default
```suggestion
- [Settings] Optimized the delay time by setting the default maximum number of queries per transaction in the field to 2000
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Code improvements
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Improved the management of `timed_events` objects
```suggestion
- [Code] Improved the management of `timed_events` objects
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Improved the memory management of downtimes
```suggestion
- [Code] Improved the memory management of downtimes
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Calls to the `atoi()` C function have been replaced by more secure functions
```suggestion
- [Code] Calls to the `atoi()` C function have been replaced by more secure functions
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Improved communication
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Two new broker streams are available, meant to provide simpler configuration and support of the gRPC protocol.
```suggestion
- [Communication] Added two new Broker streams to provide simpler configuration and support the gRPC protocol
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- It is now possible to limit the maximum total size of Broker retention files using the `event_queues_total_size` global parameter
```suggestion
- [Communication] Added the ability to limit the maximum total size of Broker retention files using the event_queues_total_size global parameter
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- The default `retry_interval` has been changed from 60 to 15, in the configuration WUI as well as in the source code for a shorter time to reconnect
```suggestion
- [Communication] Changed the default retry_interval from 60 to 15, in the configuration WUI as well as in the source code for a shorter time to reconnect
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### gRPC API features
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- The log levels can be accessed and changed without reloading thanks to the `GetLogInfo {}` and `SetLogLevel {"logger": "<logger>", "level": "<log level>"}` gRPC commands
```suggestion
- [gRPC API] The log levels can be accessed and changed without reloading thanks to the `GetLogInfo {}` and `SetLogLevel {"logger": "<logger>", "level": "<log level>"}` gRPC commands
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- All traces of a deleted poller can be removed permanently thanks to the `RemovePoller {}` gRPC command
```suggestion
- [gRPC API] All traces of a deleted poller can be removed permanently thanks to the `RemovePoller {}` gRPC command
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +###### Code improvements
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Calls to the `atoi()` C function have been replaced by more secure functions
```suggestion
- [Code] Calls to the `atoi()` C function have been replaced by more secure functions
```

2022-10-25 09:58 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +#### Enhancements
```suggestion
Compatibility with other 22.10 components.
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Event logs] Rework CSV exporter in event logs to manage high volumetry
```suggestion
- [Event logs] Reworked CSV exporter in event logs to manage high volumetry
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Resources Status] Introduce CSV export in Timeline and Graphs
```suggestion
- [Resources Status] Introduced CSV export in Timeline and Graphs
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Resources Status] New Parent Alias column and filter in listing for services
```suggestion
- [Resources Status] Added new Parent Alias column and filter in listing for services
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Resources Status] Timeline UI in Resources Status cosmetic enhancements
```suggestion
- [Resources Status] Added timeline UI in Resources Status cosmetic enhancements
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Anomaly Detection] New type of resources in Resource Status (display and filter)
```suggestion
- [Anomaly Detection] Added new type of resources in Resource Status (display and filter)
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Anomaly Detection] Prediction enveloppe size management by user from Resources Status
```suggestion
- [Anomaly Detection] Added prediction enveloppe size management by user from Resources Status
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +> In /monitoring/resources API, ‘severity_level’ api return key has been replaced by a json object ‘severity’ containing id, level, name and icon
```suggestion
> In /monitoring/resources API, ‘severity_level’ api return key has been replaced by a json object ‘severity’ containing id, level, name and icon.
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +###### Anomaly Detection improvements
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Recheck has been implemented for Anomaly Detection services, retrieving the actual value of the metric to reevaluate the AD service's status
```suggestion
- [Anomaly Detection] Recheck has been implemented for Anomaly Detection services, retrieving the actual value of the metric to reevaluate the AD service's status
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Downtimes on regular services are now propagated to related Anomaly Detection service(s)
```suggestion
- [Anomaly Detection] Downtimes on regular services are now propagated to related Anomaly Detection service(s)
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +###### Settings improvements
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Change the log level of some notification log messages
```suggestion
- [Settings] Changed the log level of some notification log messages
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Observations on platforms in the field showed us that the default maximum number of queries per transaction (10000) was too high and caused too much delay, so we set it to 2000 by default
```suggestion
- [Settings] Optimized the delay time by setting the default maximum number of queries per transaction in the (what field?) field to 2000
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +###### Code improvements
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Improved the management of `timed_events` objects
```suggestion
- [Code] Improved the management of `timed_events` objects
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Improved the memory management of downtimes
```suggestion
- [Code] Improved the memory management of downtimes
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Calls to the `atoi()` C function have been replaced by more secure functions
```suggestion
- [Code] Calls to the `atoi()` C function have been replaced by more secure functions
```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +###### Improved communication
```suggestion

```

2022-10-25 09:58 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +#### Enhancements
```suggestion
Compatibility with other 22.10 components.
```

2022-10-25 13:19 UTC, smau-centreon submitted a review, later dismissed

2022-10-25 13:42 UTC, lpinsivy approved these changes

2022-10-25 15:25 UTC, nmagniezCentreon approved these changes

2022-10-25 15:36 UTC, lpinsivy submitted a review, later dismissed

2022-10-25 15:43 UTC, smau-centreon submitted a review, later dismissed

2022-10-26 08:36 UTC, mdebauchez submitted a review, later dismissed

2022-10-26 09:33 UTC, omercier submitted a review, later dismissed

2022-10-26 09:50 UTC, smau-centreon approved these changes

2022-10-26 09:51 UTC, lpinsivy approved these changes

2022-10-26 12:14 UTC, smau-centreon approved these changes

2022-10-26 12:16 UTC, mdebauchez approved these changes

2022-10-26 12:18 UTC, lpinsivy approved these changes

2022-10-26 12:22 UTC, nmagniezCentreon approved these changes

2022-10-26 12:22 UTC, merged