enh(release): Add Centreon Web 22.04.5 RN
centreon/centreon-documentation pull request #1817
Opened 2022-09-15 13:50 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-09-15 14:36 UTC, cg-tw requested changes

2022-09-15 14:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [UX] Improved usability to access logs and reports button in details panel
```suggestion
- [UX] Improved usability when accessing logs and reports button in details panel
```

2022-09-15 14:36 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [UX] Improved usability to access logs and reports button in details panel
```suggestion
- [UX] Improved usability when accessing logs and reports button in details panel
```

2022-09-15 14:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Fixed an error in the Configuration > Services > Templates menu causing display of HTML code
```suggestion
- [Configuration] Fixed an error in the Configuration > Services > Templates menu causing HTML code to be displayed
```

2022-09-15 14:36 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Fixed an error in the Configuration > Services > Templates menu causing display of HTML code
```suggestion
- [Configuration] Fixed an error in the Configuration > Services > Templates menu causing HTML code to be displayed
```

2022-09-15 14:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Resources Status] Fixed the "Alias" tile that was not displayed in detail panel for 22.04
```suggestion
- [Resources Status] Fixed the "Alias" tile that was not displayed in the details panel
```

2022-09-15 14:36 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Resources Status] Fixed the "Alias" tile that was not displayed in detail panel for 22.04
```suggestion
- [Resources Status] Fixed the "Alias" tile that was not displayed in details panel
```

2022-09-15 14:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Resources Status] Fixed the broken link to host right panel
```suggestion
- [Resources Status] Fixed broken link to host right panel
```

2022-09-15 14:36 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Resources Status] Fixed the broken link to host right panel
```suggestion
- [Resources Status] Fixed broken link to host right panel
```

2022-09-15 14:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [UI] Fixed HTML code appearing instead of svg icon with Firefox
```suggestion
- [UI] Fixed HTML code appearing instead of SVG icon with Firefox
```

2022-09-15 14:36 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [UI] Fixed HTML code appearing instead of svg icon with Firefox
```suggestion
- [UI] Fixed HTML code appearing instead of SVG icon with Firefox
```

2022-09-15 14:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Monitoring] Fixed XSS vulnerability reflected in deprecated services status details page
```suggestion
- [Monitoring] Fixed XSS vulnerability in deprecated services status details page
```

2022-09-15 14:36 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Monitoring] Fixed XSS vulnerability reflected in deprecated services status details page
```suggestion
- [Monitoring] Fixed XSS vulnerability in deprecated services status details page
```

2022-09-15 14:39 UTC, cg-tw requested changes

2022-09-15 14:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Fixed duplication of a Remote Server
```suggestion
- [Configuration] Fixed error that occurred when duplicating a Remote Server
```

2022-09-15 14:39 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Fixed duplication of a Remote Server
```suggestion
- [Configuration] Fixed error that occurred when duplicating a Remote Server
```

2022-09-15 14:39 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Widgets] Retrieve possibility to not select poller in preferences
```suggestion
- [Widgets] Restored possibility to not select a poller in preferences
```

2022-09-15 14:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Widgets] Retrieve possibility to not select poller in preferences
```suggestion
- [Widgets] Restored possibility to not select a poller in preferences
```

2022-09-15 14:48 UTC, cg-tw approved these changes

2022-09-20 15:11 UTC, thiuyendang approved these changes

2022-09-20 15:12 UTC, cg-tw submitted a review, later dismissed

2022-09-20 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Clean code in forMyAccount
```suggestion
- [Core] Cleaned code in forMyAccount
```

2022-09-20 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] Correct escapeSecure usage
```suggestion
- [Core] Corrected escapeSecure usage
```

2022-09-20 15:52 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Core] Clean code in forMyAccount
```suggestion
- [Core] Cleaned code in forMyAccount
```

2022-09-20 15:52 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Core] Correct escapeSecure usage
```suggestion
- [Core] Corrected escapeSecure usage
```

2022-09-20 15:53 UTC, cg-tw approved these changes

2022-09-20 16:12 UTC, thiuyendang approved these changes

2022-09-20 16:13 UTC, thiuyendang submitted a review, later dismissed

2022-09-20 16:23 UTC, cg-tw requested changes

2022-09-20 16:23 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +
```suggestion

Release date: `September 20, 2022`

```

2022-09-20 16:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +
```suggestion

Release date: `September 20, 2022`

```

2022-09-20 16:24 UTC, cg-tw approved these changes

2022-09-20 16:27 UTC, tuntoja approved these changes

2022-09-20 16:44 UTC, merged