doc(release): add release note for centreon-collect-21.10.3
centreon/centreon-documentation pull request #1818
Opened 2022-09-15 14:22 UTC by omercier

## Description

Release note

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-09-15 14:44 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Improve security of the gRPC API by listening on 127.0.0.1 by default
```suggestion
- Improved security of the gRPC API by listening on 127.0.0.1 by default
```

2022-09-15 14:45 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Allow empty strings for parameter values in stream connectors
```suggestion
- Allowed empty strings for parameter values in stream connectors
```

2022-09-15 14:45 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +### Centreon Engine
```suggestion
#### Centreon Engine
```

2022-09-15 14:45 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Improve security of the gRPC API by listening on 127.0.0.1 by default
```suggestion
- Improved security of the gRPC API by listening on 127.0.0.1 by default
```

2022-09-15 14:45 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Improve security of the gRPC API by listening on 127.0.0.1 by default
```suggestion
- Improved security of the gRPC API by listening on 127.0.0.1 by default
```

2022-09-15 14:45 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Allow empty strings for parameter values in stream connectors
```suggestion
- Allowed empty strings for parameter values in stream connectors
```

2022-09-15 14:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- Improve security of the gRPC API by listening on 127.0.0.1 by default
```suggestion
- Improved security of the gRPC API by listening on 127.0.0.1 by default
```

2022-09-15 14:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- Improve security of the gRPC API by listening on 127.0.0.1 by default
```suggestion
- Improved security of the gRPC API by listening on 127.0.0.1 by default
```

2022-09-15 14:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- Allow empty strings for parameter values in stream connectors
```suggestion
- Allowed empty strings for parameter values in stream connectors
```

2022-09-16 09:02 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- Allow empty strings for parameter values in stream connectors
```suggestion
- Empty strings are now accepted for parameter values in stream connectors
```

2022-09-16 09:02 UTC, omercier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Allow empty strings for parameter values in stream connectors
```suggestion
- Empty strings are now accepted for parameter values in stream connectors
```

2022-09-16 11:53 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +
```suggestion
```

2022-09-16 11:53 UTC, omercier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +
```suggestion
```

2022-09-16 11:57 UTC, cg-tw submitted a review, later dismissed

2022-09-16 12:49 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- Fixed an issue that caused the RRD rebuild mechanism to fail
```suggestion
- Fixed an issue causing pollers to be displayed as running, and resources to be displayed in Resources Status after stopping centengine
- Fixed an issue that caused the RRD rebuild mechanism to fail
```

2022-09-16 12:49 UTC, omercier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- Fixed an issue that caused the RRD rebuild mechanism to fail
```suggestion
- Fixed an issue causing pollers to be displayed as running, and resources to be displayed in Resources Status after stopping centengine
- Fixed an issue that caused the RRD rebuild mechanism to fail
```

2022-09-27 07:51 UTC, chgautier requested changes

2022-09-27 07:51 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +Release date: ``
```suggestion
Release date: `September 27, 2022`
```

2022-09-27 07:51 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +Release date: ``
```suggestion
Release date: `September 27, 2022`
```

2022-09-27 07:52 UTC, chgautier approved these changes

2022-09-27 08:21 UTC, cg-tw approved these changes

2022-09-27 08:26 UTC, merged