enh(release): Add Centreon Web 21.10.10 RN
centreon/centreon-documentation pull request #1819
Opened 2022-09-15 15:46 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 22.10.x (next)

2022-09-15 16:24 UTC, cg-tw approved these changes

2022-09-20 15:44 UTC, thiuyendang submitted a review, later dismissed

2022-09-20 15:45 UTC, cg-tw approved these changes

2022-09-20 16:01 UTC, cg-tw requested changes

2022-09-20 16:01 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Core] Clean code in forMyAccount
```suggestion
- [Core] Cleaned code in forMyAccount
```

2022-09-20 16:01 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Core] Correct escapeSecure usage
```suggestion
- [Core] Corrected escapeSecure usage
```

2022-09-20 16:04 UTC, cg-tw approved these changes

2022-09-20 16:14 UTC, thiuyendang submitted a review, later dismissed

2022-09-20 16:30 UTC, cg-tw requested changes

2022-09-20 16:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `September 20, 2022`

```

2022-09-20 16:30 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +
```suggestion

Release date: `September 20, 2022`

```

2022-09-20 16:31 UTC, cg-tw approved these changes

2022-09-20 16:32 UTC, tuntoja approved these changes

2022-09-20 16:57 UTC, merged