enh(oidc): Improved OIDC chapter with new features
centreon/centreon-documentation pull request #1849
Opened 2022-09-28 15:41 UTC by lpinsivy

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 22.10.x (next)

2022-10-04 17:12 UTC, cg-tw commented
waiting for FR translation of labels

2022-10-13 15:56 UTC, mdebauchez requested changes

2022-10-13 15:56 UTC, mdebauchez commented on versioned_docs/version-22.10/connect/openid.md
>  - **Scopes**: defines the scopes of the identity provider, for example `openid`. Separate scopes by spaces.
Client ID and Client Secret are mandatory too

2022-10-13 15:56 UTC, mdebauchez commented on versioned_docs/version-22.10/connect/openid.md
> +  - **Login attribute path**: defines which of the variables returned by **Introspection Token Endpoint** or **User Information Endpoint**
![image](https://user-images.githubusercontent.com/78470741/195635440-4243e7bc-d074-4db9-a059-5547b15fe3b3.png)

2022-10-13 15:56 UTC, mdebauchez commented on versioned_docs/version-22.10/connect/openid.md
> +  - **Login attribute path**: defines which of the variables returned by **Introspection Token Endpoint** or **User Information Endpoint**
I think the login attibute path should not be in the yellow part

2022-10-13 15:56 UTC, mdebauchez commented on versioned_docs/version-22.10/connect/openid.md
>  > You can enable **Authentication debug** through the **Administration > Parameters > Debug** menu to understand
Line 52 : The button name is 'Disable verify peer'

2022-10-13 15:56 UTC, mdebauchez commented on versioned_docs/version-22.10/connect/openid.md
> +If you turn on **Enable Auto import users**, users that log in to Centreon for the first time will be created in the Centreon configuration. (Turning the option on does not import automatically all u
The button name is 'Enable auto import'

2022-10-13 15:56 UTC, mdebauchez commented on versioned_docs/version-22.10/connect/openid.md
> +And to authorize the following `redirect URI` to forward your connected users to Centreon:
The letter A is uppercase

2022-10-13 15:56 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/connect/openid.md
> +L'authentification se paramètre à la page **Administration > Authentification > OpenId Connect Configuration**.
In french, the name of the page is Administration > Authentification > Configuration OpenId Connect

2022-10-13 15:56 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/connect/openid.md
> +- **Identifiant client** : définit l'ID client.
Identifiant Client et Secret de client are mandatory too

2022-10-13 15:56 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/connect/openid.md
> +- **Disable SSL verify peer** : permet de désactiver la validation des pairs SSL. Le certificat du fournisseur d'identité ne
The button name is 'Désactiver la vérification du pair'

2022-10-13 15:56 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/connect/openid.md
>  Configurer votre fournisseur d'identité pour ajouter l'application Centreon à utiliser le protocole OpenID Connect pour
Configurez*

2022-10-17 15:03 UTC, mdebauchez approved these changes

2022-10-17 16:27 UTC, merged