Add upgrade procedure for Debian
centreon/centreon-documentation pull request #1863
Opened 2022-10-04 13:49 UTC by cg-tw

## Description

Add upgrade procedure for Debian
+ fix update procedure for Debian

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 22.10.x (next)

2022-10-04 13:54 UTC, lpinsivy requested changes

2022-10-04 13:54 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md
> +  apt update centreon
```suggestion
  apt upgrade centreon
```

2022-10-04 13:54 UTC, lpinsivy commented on versioned_docs/version-22.10/update/update-centreon-platform.md
> +  apt update centreon
```suggestion
  apt upgrade centreon
```

2022-10-04 14:12 UTC, lpinsivy approved these changes

2022-10-17 11:53 UTC, tuntoja commented
@lpinsivy this line will probably fail on debian based os
`sed -ri 's/10\../10.5/' /etc/yum.repos.d/mariadb.repo`

2022-10-25 16:43 UTC, cg-tw commented
In https://github.com/centreon/centreon-documentation/pull/1911

2022-10-25 16:43 UTC, closed without merging