enh(epp): hitachi nas snmp proc v2
centreon/centreon-documentation pull request #1967
Opened 2022-11-16 14:56 UTC by garnier-quentin

## Description

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-12-05 13:23 UTC, cg-tw requested changes

2022-12-05 13:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
> +| Virtual-Volumes-Quotas | HW-Storage-Hitachi-Hnas-Virtual-Volumes-Quotas-SNMP | Contrôle l'utilisation des quotas des volumes virtuelles |        |            |
```suggestion
| Virtual-Volumes-Quotas | HW-Storage-Hitachi-Hnas-Virtual-Volumes-Quotas-SNMP | Contrôle l'utilisation des quotas des volumes virtuels |        |            |
```

2022-12-05 13:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
> +| Volume-Usage-Global    | HW-Storage-Hitachi-Hnas-Volume-Usage-Global-SNMP    | Contrôle l'utilisation des volume                        | X      |            |
```suggestion
| Volume-Usage-Global    | HW-Storage-Hitachi-Hnas-Volume-Usage-Global-SNMP    | Contrôle l'utilisation des volumes                        | X      |            |
```

2022-12-05 13:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
> +| HW-Storage-Hitachi-Hnas-SNMP-Interface-Name | Discover the disk partitions and monitor space occupation |
description en anglais

2022-12-05 13:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
> +Afin de superviser votre **Hitachi NAS** en SNMP, il est nécessaire de configurer l'agent sur le serveur comme indiqué sur la documentation officielle.
lien?

2022-12-05 13:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2022-12-05 13:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
> +server.
link?

2022-12-07 12:35 UTC, garnier-quentin commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
> +Afin de superviser votre **Hitachi NAS** en SNMP, il est nécessaire de configurer l'agent sur le serveur comme indiqué sur la documentation officielle.
we don't have a link

2022-12-07 12:35 UTC, garnier-quentin commented on pp/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
> +server.
we don't have a link

2022-12-12 18:53 UTC, cg-tw approved these changes

2022-12-14 17:34 UTC, omercier approved these changes

2022-12-15 17:51 UTC, merged