(pp) Enhancements to some Cloud M365 monitoring procedures
centreon/centreon-documentation pull request #1969
Opened 2022-11-17 15:02 UTC by Sims24

## Description

![bye-adios](https://user-images.githubusercontent.com/12429463/202481358-6e12316f-6638-4060-8e83-8ee48fa0fc07.gif)

Bring some enhancements to Cloud M365 monitoring procedures

- office365-skype - Switch FR<>EN and modernize installation section
- office365-exchange - Update installation steps & troubleshooting section
- Office365 OneDrive+Skype - Update installation steps 

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [x] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-11-17 15:38 UTC, ponchoh commented
# 👋

2022-11-21 15:43 UTC, cg-tw requested changes

2022-11-21 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +Afin de récupérer les données d'Skype Online, vous devez spécifier les
```suggestion
Afin de récupérer les données de Skype Online, vous devez spécifier les
```

2022-11-21 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +dans le Portail de gestion Azure :
```suggestion
Dans le portail de gestion Azure :
```

2022-11-21 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2022-11-21 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +Lors de la création de votre Hôte dans Centreon, choisissez le modèle
```suggestion
Lors de la création de votre hôte dans Centreon, choisissez le modèle
```

2022-11-21 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +La métrique *perfdate* enrengistre la date à laquelle celle-ci a été collectée.
```suggestion
La métrique *perfdate* enregistre la date à laquelle celle-ci a été collectée. 
```

2022-11-21 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +Une fois l'hôte créé, il est également possible de paramétrer un ensemble de m
```suggestion
Une fois l'hôte créé, il est également possible de paramétrer un ensemble de
```

2022-11-21 15:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-azuread.md
> +To collect data from Onedrive Online, you need to specify the following
```suggestion
To collect data from OneDrive Online, you need to specify the following
```

2022-11-21 15:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +provides video chat, voice calls and messages services between different types
```suggestion
provides video chat, voice calls and message services between different types
```

2022-11-21 15:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +> They're based on a 7 days reporting period
```suggestion
> They're based on a 7 days reporting period.
```

2022-11-21 15:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +Once the host created, you can configure some macros on the service to filter
```suggestion
Once the host is created, you can configure some macros on the service to filter 
```

2022-11-21 15:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +- You want to run a discovery job from a poller that doesn't monitor any resource of this kind yet
```suggestion
- You want to run a discovery job from a poller that doesn't monitor any resource of this kind yet.
```

2022-11-21 15:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +The metric perfdateY will record the date the metric was collected. You can
```suggestion
The metric perfdate will record the date the metric was collected. You can
```

2022-11-21 15:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
> +Once the host created, you can configure some Macros on the services to filter
```suggestion
Once the host is created, you can configure some macros on the services to filter
```

2022-11-21 15:47 UTC, cg-tw approved these changes

2022-11-24 15:27 UTC, itoussies approved these changes

2022-11-25 09:55 UTC, merged