PS-107 ENH Centreon-HA 22.10 2 nodes constraints mysql-status acceptance guide
centreon/centreon-documentation pull request #1971
Opened 2022-11-21 14:00 UTC by cedricmeschin

## Description

Enhance of constraints, mysql-status and acceptance guide with new informations returned by commands
EN and FR

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [X] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-11-21 14:37 UTC, cg-tw requested changes

2022-11-21 14:37 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Vous devez donc resynchroniser les bases depuis @CENTRAL_SLAVE_NAME@ vers @CENTRAL_MASTER_NAME@ en lançant le script "sync-bigdb" sur le **noeud SLAVE**.
```suggestion
Vous devez donc resynchroniser les bases depuis @CENTRAL_SLAVE_NAME@ vers @CENTRAL_MASTER_NAME@ en lançant le script "sync-bigdb" sur le **nœud SLAVE**.
```

2022-11-21 14:37 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Comme lors de l'exécution précédente de ce script, vérifiez si le snapshot LVM est correctement supprimé et l'esclave Mysql redémarré.
```suggestion
Comme lors de l'exécution précédente de ce script, vérifiez si le snapshot LVM est correctement supprimé et l'esclave MySQL redémarré.
```l

2022-11-21 14:37 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +La ressource centreon est maintenant relocalisée et le cluster est OK, vérifiez avec `crm_mon -fr` sur n'importe quel noeud.
```suggestion
La ressource centreon est maintenant relocalisée et le cluster est OK, vérifiez avec `crm_mon -fr` sur n'importe quel nœud.
```

2022-11-21 14:37 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +So, **before to do this, you must check the cluster and database replication status**.
```suggestion
So, **before you do this, you must check the cluster and database replication status**.
```

2022-11-21 14:37 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +At this time, the cluster is on degraded mode whith two slave nodes.
```suggestion
At this time, the cluster is in degraded mode whith two slave nodes.
```

2022-11-21 14:37 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Like as previous execution of this sript, verify if LVM Snapshot is correctly deleted and Mysql Slave restarted
```suggestion
As for the previous execution of this script, verify if LVM Snapshot is correctly deleted and the MySQL Slave restarted
```

2022-11-21 14:37 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Now, you can perform a failover to return in initial situation.
```suggestion
Now, you can perform a failover to return to the initial situation.
```

2022-11-21 14:37 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Do a cleanup to clear errors ans restart ms_mysql resource on @CENTRAL_MASTER_NAME@.
```suggestion
Do a cleanup to clear errors and restart the ms_mysql resource on @CENTRAL_MASTER_NAME@.
```

2022-11-21 14:37 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Situation is stabilized, you can perform a failover by moving centreon resource.
```suggestion
The situation is stabilized, you can perform a failover by moving the centreon resource.
```

2022-11-21 14:37 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +The centreon resource is now relocated and cluster is OK, verify with `crm_mon -fr` on any node.
```suggestion
The centreon resource is now relocated and the cluster is OK, verify with `crm_mon -fr` on any node.
```

2023-02-10 15:15 UTC, jeanrenemoyap approved these changes

2023-02-13 11:16 UTC, cg-tw requested changes

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +L'exécution de la commande `pcs status` sur le second noeud indique que les ressources sont arrêtées et que le noeud primaire est `offline`:
```suggestion
L'exécution de la commande `pcs status` sur le second nœud indique que les ressources sont arrêtées et que le nœud primaire est `offline`:
```

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Tout d'abord, vérifiez les contraintes
```suggestion
Tout d'abord, vérifiez les contraintes :
```

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +La commande doit retourner un résultat similaire à ceci:
```suggestion
La commande doit retourner un résultat similaire à ceci :
```

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Maintenant, vérifier le statut de réplication via la commande suivante:
```suggestion
Maintenant, vérifiez le statut de réplication via la commande suivante :
```

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +En ce moment, le cluster est en mode dégradé avec deux nœuds esclaves.
```suggestion
À ce moment, le cluster est en mode dégradé avec deux nœuds esclaves.
```

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Dans ce cas particulier, il retourne les informations suivantes car la ressource ms_mysql est arrêtée sur @CENTRAL_MASTER_NAME@:
```suggestion
Dans ce cas particulier, il retourne les informations suivantes car la ressource ms_mysql est arrêtée sur @CENTRAL_MASTER_NAME@ :
```

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +Faites un "cleanup" pour effacer les erreurs et redémarrer la ressource ms_mysql sur @CENTRAL_MASTER_NAME@.
```suggestion
Faites un "cleanup" pour effacer les erreurs et redémarrez la ressource ms_mysql sur @CENTRAL_MASTER_NAME@.
```

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +La situation est stabilisée, vous pouvez effectuer un failover en déplaçant la ressource Centreon.
```suggestion
La situation est stabilisée, vous pouvez effectuer un failover en déplaçant la ressource **centreon**.
```

2023-02-13 11:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +La ressource centreon est maintenant relocalisée et le cluster est OK, vérifiez avec `crm_mon -fr` sur n'importe quel nœud.
```suggestion
La ressource **centreon** est maintenant relocalisée et le cluster est OK, vérifiez avec `crm_mon -fr` sur n'importe quel nœud.
```

2023-02-13 11:16 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +> If the synchronization has `KO` you have to fix it with the help of the [operating-guide](operating-guide.md).
```suggestion
> If the synchronization is `KO` you have to fix it with the help of the [operating-guide](operating-guide.md).
```

2023-02-13 11:16 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +First, check the constraints
```suggestion
First, check the constraints:
```

2023-02-13 11:16 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +At this time, the cluster is in degraded mode whith two slave nodes.
```suggestion
At this time, the cluster is in degraded mode with two slave nodes.
```

2023-02-13 11:16 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +In this particular case, it return the following information because of ms_mysql resource is stopped on @CENTRAL_MASTER_NAME@:
```suggestion
In this particular case, it returns the following information because the ms_mysql resource is stopped on @CENTRAL_MASTER_NAME@:
```

2023-02-13 11:16 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +As for the previous execution of this script, verify if LVM Snapshot is correctly deleted and the MySQL Slave restarted
```suggestion
As for the previous execution of this script, verify if LVM Snapshot is correctly deleted and the MySQL Slave restarted:
```

2023-02-13 11:16 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +The situation is stabilized, you can perform a failover by moving the centreon resource.
```suggestion
The situation is stabilized, you can perform a failover by moving the **centreon** resource.
```

2023-02-13 11:16 UTC, cg-tw commented on versioned_docs/version-22.10/administration/centreon-ha/acceptance-guide.md
> +The centreon resource is now relocated and the cluster is OK, verify with `crm_mon -fr` on any node.
```suggestion
The **centreon** resource is now relocated and the cluster is OK, verify with `crm_mon -fr` on any node.
```

2023-02-14 08:45 UTC, cg-tw submitted a review, later dismissed

2023-03-31 16:30 UTC, psamecentreon approved these changes

2023-04-03 08:45 UTC, cg-tw submitted a review, later dismissed

2023-04-13 08:41 UTC, psamecentreon submitted a review, later dismissed

2023-04-13 09:49 UTC, cg-tw approved these changes

2023-05-05 15:00 UTC, psamecentreon approved these changes

2023-05-05 15:02 UTC, merged