Improve BAM stats procedure
centreon/centreon-documentation pull request #1985
Opened 2022-11-28 12:58 UTC by smau-centreon

## Description

Improve BAM stats procedure

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-11-29 17:38 UTC, omercier requested changes

2022-11-29 17:38 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/concepts.md
> +- Suivez cette procédure si vous avez récemment mis à jour Centreon BAM en version 3.0 ou que vous venez de reconstruire les statistiques de BAM.
```suggestion
- Suivez cette procédure si vous venez de reconstruire les statistiques de BAM.
```

2022-11-29 17:38 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/concepts.md
> +- Suivez cette procédure si vous avez récemment mis à jour Centreon BAM en version 3.0 ou que vous venez de reconstruire les statistiques de BAM.
BAM 3.0 is an ooooold version

2022-11-29 17:38 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/concepts.md
> +- Maintenant suivez cette procédure si les données de reporting ne semble pas à jour :
```suggestion
- Si les données de reporting ne semblent toujours pas à jour, suivez cette procédure :
```

2022-11-29 17:38 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/concepts.md
> +  1. Vous devez d'abord exécuter cette commande pour recalculer globalement les statistiques de BAM :
```suggestion
  1. Vous devez d'abord exécuter cette commande sur le serveur central pour recalculer globalement les statistiques de BAM :
```

2022-11-29 17:38 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/concepts.md
> +  2. Importez-les ensuite en exécutant cette commande sur le serveur central :
```suggestion
  2. Réimportez-les ensuite sur le serveur MBI en exécutant cette commande :
```

2022-11-29 17:38 UTC, omercier commented on versioned_docs/version-22.10/reporting/concepts.md
> +Centreon BAM statistics.
```suggestion
- Follow this procedure if you rebuilt the Centreon BAM statistics.
```

2022-11-29 17:38 UTC, omercier commented on versioned_docs/version-22.10/reporting/concepts.md
> +- Now follow this prodedure if statistics are not up to date:
```suggestion
- If statistics are not up to date, follow this prodedure:
```

2022-11-29 17:38 UTC, omercier commented on versioned_docs/version-22.10/reporting/concepts.md
> +  1. You need first to execute the following command to rebuild statistics:
```suggestion
  1. You need first to execute the following command to rebuild statistics on the central server:
```

2022-11-29 17:38 UTC, omercier commented on versioned_docs/version-22.10/reporting/concepts.md
> +  2. Then import them using this command on the central server:
```suggestion
  2. Then import them using this command on the reporting server:
```

2022-12-01 09:04 UTC, omercier commented on versioned_docs/version-21.10/reporting/concepts.md
> +  - Reimport the BAM data on the central server by running the following command:
```suggestion
  - Reimport the BAM data from the central server on the reporting server by running the following command:
```

2022-12-02 08:21 UTC, omercier approved these changes

2022-12-02 14:52 UTC, sfarouq-ext approved these changes

2022-12-02 15:12 UTC, merged