doc(release): prepare release notes for Centreon MAP 22.04.2
centreon/centreon-documentation pull request #1986
Opened 2022-11-28 14:39 UTC by tuntoja

## Description

Prepare release notes for MAP 22.04.2

## Target version

- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-11-30 13:23 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +
- Web editor
- New Server
- Migration process

2022-11-30 13:23 UTC, nmagniezCentreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +
Web editor
New Server
Migration process

2022-11-30 13:24 UTC, smau-centreon requested changes

2022-11-30 13:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed a connection problem between MAP desktop client and MAP server that could lead to timeouts on large maps
```suggestion
- Fixed a connection problem between MAP desktop client and MAP server that could lead to timeouts on large maps.
```

2022-11-30 13:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue with Java 17 that caused MAP server to fail to startup
```suggestion
- Fixed an issue with Java 17 that caused MAP server to fail to start.
```

2022-11-30 13:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue with API preventing an authenticated user from creating a resource with an image
```suggestion
- Fixed an issue with the API preventing an authenticated user from creating a resource with an image.
```

2022-11-30 13:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue on line charts not having any data displayed if chart period and chart precision values were too large
```suggestion
- Fixed an issue with the display of line charts if the period and precision values of the chart were too large.
```

2022-11-30 13:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Actuator endpoints are now disabled by default, except for health and metrics
```suggestion
- Actuator endpoints are now disabled by default, except for health and metrics.
```

2022-11-30 13:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fix the security issue CVE-2022-42889 (Text4shell)
```suggestion
- Fixed the security issue CVE-2022-42889 (Text4shell vulnerability).
```

2022-11-30 13:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Updated diagnostic.sh script to handle Java 17 installation instead of returning an error
```suggestion
- Updated the diagnostic.sh script to handle Java 17 installation instead of returning an error.
```

2022-11-30 13:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- MAP extension configuration now requires only one MAP server address to be configured
```suggestion
- MAP extension configuration now requires only one MAP server address to be configured.
```

2022-11-30 13:24 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed a connection problem between MAP desktop client and MAP server that could lead to timeouts on large maps
```suggestion
- Fixed a connection problem between MAP desktop client and MAP server that could lead to timeouts on large maps.
```

2022-11-30 13:24 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue with Java 17 that caused MAP server to fail to startup
```suggestion
- Fixed an issue with Java 17 that caused MAP server to fail to start.
```

2022-11-30 13:24 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue with API preventing an authenticated user from creating a resource with an image
```suggestion
- Fixed an issue with the API preventing an authenticated user from creating a resource with an image.
```

2022-11-30 13:24 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue on line charts not having any data displayed if chart period and chart precision values were too large
```suggestion
- Fixed an issue with the display of line charts if the period and precision values of the chart were too large.
```

2022-11-30 13:24 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Actuator endpoints are now disabled by default, except for health and metrics
```suggestion
- Actuator endpoints are now disabled by default, except for health and metrics.
```

2022-11-30 13:24 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fix the security issue CVE-2022-42889 (Text4shell)
```suggestion
- Fixed the security issue CVE-2022-42889 (Text4shell vulnerability).
```

2022-11-30 13:24 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Updated diagnostic.sh script to handle Java 17 installation instead of returning an error
```suggestion
- Updated the diagnostic.sh script to handle Java 17 installation instead of returning an error.
```

2022-11-30 13:24 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- MAP extension configuration now requires only one MAP server address to be configured
```suggestion
- MAP extension configuration now requires only one MAP server address to be configured.
```

2022-12-05 09:20 UTC, nmagniezCentreon approved these changes

2022-12-05 13:15 UTC, smau-centreon requested changes

2022-12-05 13:15 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +
```suggestion

> The new MAP extension is now available in a full web version with a new server, under the name of MAP. The former version, including desktop client and associated server, becomes MAP Legacy.

```

2022-12-05 13:15 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +
```suggestion

> The new MAP extension is now available in a full web version with a new server, under the name of MAP. The former version, including desktop client and associated server, becomes MAP Legacy.

```

2022-12-05 14:27 UTC, smau-centreon requested changes

2022-12-05 14:27 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +New server: Brand new server and data model providing better performance.
```suggestion
- New server: Brand new server and data model providing better performance.
```

2022-12-05 14:27 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +Migration process: Integrated migration process of your legacy views.
```suggestion
- Migration process: Integrated migration process of your legacy views.
```

2022-12-05 14:27 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +Web editor: Create and edit your views directly from your web browser.
```suggestion
- Web editor: Create and edit your views directly from your web browser.
```

2022-12-05 14:27 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +New server: Brand new server and data model providing better performance.
```suggestion
- New server: Brand new server and data model providing better performance.
```

2022-12-05 14:27 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +Migration process: Integrated migration process of your legacy views.
```suggestion
- Migration process: Integrated migration process of your legacy views.
```

2022-12-05 15:57 UTC, nmagniezCentreon submitted a review, later dismissed

2022-12-15 17:20 UTC, nmagniezCentreon submitted a review, later dismissed

2022-12-16 12:13 UTC, smau-centreon approved these changes

2022-12-16 17:04 UTC, smau-centreon approved these changes

2022-12-16 17:11 UTC, nmagniezCentreon approved these changes

2022-12-16 17:31 UTC, merged