commit initial
centreon/centreon-documentation pull request #1990
Opened 2022-11-30 12:40 UTC by Barbeloa

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [X] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-11-30 13:18 UTC, cg-tw requested changes

2022-11-30 13:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue where resources tooltips in MAP legacy widget could not be displayed properly
```suggestion
- Fixed an issue where resources' tooltips in the MAP legacy widget could not be displayed properly
```

2022-11-30 13:18 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue where resources tooltips in MAP legacy widget could not be displayed properly
```suggestion
- Fixed an issue where resources' tooltips in the MAP legacy widget could not be displayed properly
```

2022-11-30 13:23 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +
Web editor
New Server
Migration process

2022-11-30 13:23 UTC, nmagniezCentreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +
Web editor
New Server
Migration process

2022-12-05 09:20 UTC, nmagniezCentreon approved these changes

2022-12-05 13:13 UTC, smau-centreon requested changes

2022-12-05 13:13 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +
```suggestion

> The new MAP extension is now available in a full web version with a new server, under the name of MAP. The former version, including desktop client and associated server, becomes MAP Legacy.

```

2022-12-05 13:13 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +
```suggestion

> The new MAP extension is now available in a full web version with a new server, under the name of MAP. The former version, including desktop client and associated server, becomes MAP Legacy.

```

2022-12-05 14:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +Web editor: Create and edit your views directly from your web browser
```suggestion
- Web editor: Create and edit your views directly from your web browser.
```

2022-12-05 14:24 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +New server: Brand new server and data model providing better performance
```suggestion
- New server: Brand new server and data model providing better performance.
```

2022-12-05 14:25 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +Migration process: Integrated migration process of your legacy views
```suggestion
- Migration process: Integrated migration process of your legacy views.
```

2022-12-05 14:25 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +Web editor: Create and edit your views directly from your web browser
```suggestion
- Web editor: Create and edit your views directly from your web browser.
```

2022-12-05 14:25 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +New server: Brand new server and data model providing better performance
```suggestion
- New server: Brand new server and data model providing better performance.
```

2022-12-05 14:25 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +Migration process: Integrated migration process of your legacy views
```suggestion
- Migration process: Integrated migration process of your legacy views.
```

2022-12-05 14:41 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +> The new MAP extension is now available in a full web version with a new server, under the name of MAP. The former version, including desktop client and associated server, becomes MAP Legacy.
```suggestion
The new MAP extension is now available in a full web version with a new server, under the name of MAP. The former version, including desktop client and associated server, becomes MAP Legacy.
```

2022-12-05 14:41 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +> The new MAP extension is now available in a full web version with a new server, under the name of MAP. The former version, including desktop client and associated server, becomes MAP Legacy.
```suggestion
The new MAP extension is now available in a full web version with a new server, under the name of MAP. The former version, including desktop client and associated server, becomes MAP Legacy.
```

2022-12-05 15:56 UTC, nmagniezCentreon submitted a review, later dismissed

2022-12-06 09:16 UTC, cg-tw submitted a review, later dismissed

2022-12-06 09:19 UTC, cg-tw submitted a review, later dismissed

2022-12-06 09:24 UTC, smau-centreon approved these changes

2022-12-06 09:43 UTC, smau-centreon requested changes

2022-12-06 09:43 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fix the security issue CVE-2022-42889 (Text4shell)
```suggestion
- Fixed the security issue CVE-2022-42889 (Text4shell).
```

2022-12-06 09:43 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Actuator endpoints are now disabled by default, except for health and metrics
```suggestion
- Actuator endpoints are now disabled by default, except for health and metrics.
```

2022-12-06 09:43 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue where resources' tooltips in the MAP legacy widget could not be displayed properly
```suggestion
- Fixed an issue where resources' tooltips in the MAP legacy widget could not be displayed properly.
```

2022-12-06 09:43 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Actuator endpoints are now disabled by default, except for health and metrics
```suggestion
- Actuator endpoints are now disabled by default, except for health and metrics.
```

2022-12-06 09:43 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fix the security issue CVE-2022-42889 (Text4shell)
```suggestion
- Fixed the security issue CVE-2022-42889 (Text4shell).
```

2022-12-06 09:43 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue where resources' tooltips in the MAP legacy widget could not be displayed properly
```suggestion
- Fixed an issue where resources' tooltips in the MAP legacy widget could not be displayed properly.
```

2022-12-06 09:51 UTC, cg-tw approved these changes

2022-12-06 09:53 UTC, smau-centreon approved these changes

2022-12-06 10:15 UTC, nmagniezCentreon approved these changes

2022-12-06 10:19 UTC, merged