add(epp): network stormshield api
centreon/centreon-documentation pull request #1991
Opened 2022-11-30 14:29 UTC by garnier-quentin

## Description

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-11-30 16:24 UTC, cg-tw requested changes

2022-11-30 16:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-stormshield-api.md
> +| Net-Stormshield-Api-Interface-Username | Discover network interfaces and monitor bandwidth utilization |
description en français?

2022-11-30 16:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-stormshield-api.md
> +Pour la supervision, un utilisateur avec les droits en lecture sur l'API est nécessaire.
```suggestion
Pour la supervision, un utilisateur avec des droits de lecture sur l'API est nécessaire.
```

2022-11-30 16:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-stormshield-api.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2022-11-30 16:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-stormshield-api.md
> +To monitor, a user with read privileges on API is required.
```suggestion
To monitor, a user with read privileges on the API is required.
```

2022-11-30 16:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-stormshield-api.md
> +- You want to run a discovery job from a poller that doesn't monitor any resource of this kind yet
```suggestion
- You want to run a discovery job from a poller that doesn't monitor any resource of this kind yet.
```

2022-11-30 16:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-stormshield-api.md
> +* Fill the **Name**, **Alias** & **IP Address/DNS** fields according to your **Stormshield** server settings.
```suggestion
* Fill in the **Name**, **Alias** & **IP Address/DNS** fields according to your **Stormshield** server settings.
```

2022-12-13 17:39 UTC, omercier approved these changes

2022-12-15 11:12 UTC, cg-tw approved these changes

2022-12-15 17:07 UTC, merged