Add topic about contributing to the doc
centreon/centreon-documentation pull request #2018
Opened 2022-12-08 14:41 UTC by cg-tw

## Description

Add topic about contributing to the doc

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-12-08 15:59 UTC, smau-centreon requested changes

2022-12-08 15:59 UTC, smau-centreon commented on versioned_docs/version-22.10/resources/contribute.md
> +* an image is missing
```suggestion
* an image is missing,
```

2022-12-08 15:59 UTC, smau-centreon commented on versioned_docs/version-22.10/resources/contribute.md
> +* a link has an incorrect format
```suggestion
* a link has an incorrect format,
```

2022-12-08 15:59 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md
> +3. Créez une nouvelle branche basée sur **staging**: donnez-lui un nom parlant. Pour créer une branche et vous positionner dessus :
```suggestion
3. Créez une nouvelle branche basée sur **staging** : donnez-lui un nom significatif. Pour créer une branche et vous positionner dessus :
```

2022-12-08 15:59 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md
> +5. Buildez la version EN ou FR du site (plus rapide qu'un build complet):
```suggestion
5. Buildez la version EN ou FR du site (plus rapide qu'un build complet) :
```

2022-12-08 15:59 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md
> +   * EN: `yarn start`
```suggestion
   * EN : `yarn start`
```

2022-12-08 15:59 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md
> +   * FR: `yarn start --locale=fr`
```suggestion
   * FR : `yarn start --locale=fr`
```

2022-12-08 15:59 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md
> +* une image manque
```suggestion
* une image manque,
```

2022-12-08 15:59 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md
> +* un lien ait un format incorrect
```suggestion
* un lien ait un format incorrect,
```

2022-12-08 15:59 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md
> +* des backticks (caractères ``` autour des blocs de code) ne soit pas fermés correctement, ou bien qu'il y ait un espace en trop avant les backticks
```suggestion
* des backticks (caractères ``` autour des blocs de code) ne soit pas fermés correctement, ou bien qu'il y ait un espace en trop avant les backticks,
```

2022-12-08 16:08 UTC, smau-centreon approved these changes

2022-12-09 13:24 UTC, smau-centreon approved these changes

2022-12-09 13:26 UTC, tuntoja approved these changes

2022-12-09 14:47 UTC, merged