Document MAP for cloud version
centreon/centreon-documentation pull request #2025
Opened 2022-12-12 14:38 UTC by smau-centreon

## Description

Document MAP for cloud version

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [x] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-01-03 17:11 UTC, thiuyendang commented on cloud/graph-views/map-web-access.md
> +- Centreon administrators are creators and have Owner privileges on all maps.
Cloud users with role Administrators don't have the same rights than in Centreon Cloud context: when cloud editors create maps then cloud administrators users have by default "None" rights whereas they should get "owner" privileges

2023-01-03 17:14 UTC, thiuyendang commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/graph-views/map-web-access.md
> +- Les administrateurs Centreon sont des créateurs et disposent des privilèges de propriétaire sur toutes les cartes.
Les vrais administrateurs Centreon mais pas les administrateurs Cloud. cf https://centreon.atlassian.net/browse/MON-15047

2023-01-19 18:28 UTC, nmagniezCentreon requested changes
Je n'ai fait que en français. A ta dispo si ce n'est pas clair

2023-01-19 18:28 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/graph-views/introduction-map.md
> +- [Dépannage de MAP](map-web-troubleshooting.md) vous aide à résoudre certains incidents survenant dans MAP.
à supprimer

2023-01-19 18:28 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/graph-views/map-web-access.md
> +Les utilisateurs appartenant au groupe d'accès sélectionné sont maintenant autorisés à créer des cartes.
supprimer de mon dernier commentaire à ici

2023-01-19 18:28 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/graph-views/map-web-access.md
> +La liste des groupes d'accès disponibles s'affiche.
groupes d'accès -> rôles

2023-01-19 18:28 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/graph-views/map-web-access.md
> +3. Pour le groupe d'accès souhaité, sélectionnez le privilège à accorder dans la liste déroulante.
Pour le groupe d'accès souhaité -> Pour le rôle "user"

2023-01-20 15:39 UTC, nmagniezCentreon approved these changes

2023-01-20 15:44 UTC, Jordan91 approved these changes

2023-01-20 15:54 UTC, merged