doc(release): prepare release notes for Centreon MAP 22.10.3
centreon/centreon-documentation pull request #2034
Opened 2022-12-14 10:42 UTC by tuntoja

## Description

Prepare relese notes for Centreon MAP 22.10.3 (hotfix MON-16258)

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-12-14 11:08 UTC, smau-centreon requested changes

2022-12-14 11:08 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- no change.
```suggestion
- No change.
```

2022-12-14 12:33 UTC, smau-centreon approved these changes

2022-12-16 12:52 UTC, nmagniezCentreon approved these changes

2022-12-16 13:44 UTC, smau-centreon requested changes

2022-12-16 13:44 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed server startup error due to duplicate key.
```suggestion
- Added more fixes for server startup error due to duplicate keys.
```

2022-12-16 13:44 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed server startup error due to duplicate key.
```suggestion
- Added more fixes for server startup error due to duplicate keys.
```

2022-12-16 13:54 UTC, Jordan91 approved these changes

2022-12-16 13:59 UTC, smau-centreon approved these changes

2022-12-16 14:36 UTC, merged