doc(release): prepare release notes for MAP 21.10.8
centreon/centreon-documentation pull request #2036
Opened 2022-12-14 14:07 UTC by tuntoja

## Description

Prepare release notes for MAP 21.10.8

## Target version

- [x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-12-20 11:04 UTC, smau-centreon requested changes

2022-12-20 11:04 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Improved Centreon MAP Extension options so that only one MAP server is required to validate the form.
Already quoted in the bug fix section above?

2022-12-21 14:21 UTC, smau-centreon requested changes

2022-12-21 14:21 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue that could cause layers to not be applied properly.
```suggestion
- Fixed an issue that could prevent the correct application of layers.
```

2022-12-21 14:21 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue that could cause layers to not be applied properly.
```suggestion
- Fixed an issue that could prevent the correct application of layers.
```

2022-12-22 13:41 UTC, Barbeloa submitted a review, later dismissed

2022-12-28 08:59 UTC, Jordan91 approved these changes

2022-12-28 09:07 UTC, Jordan91 submitted a review, later dismissed

2022-12-28 16:52 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +Release date: `not yet ready`
```suggestion
Release date: `December 28, 2022`
```

2022-12-28 16:52 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +Release date: `not yet ready`
```suggestion
Release date: `December 28, 2022`
```

2022-12-29 16:11 UTC, chgautier requested changes

2022-12-29 16:11 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Improved Centreon MAP Extension options so that only one MAP server is required to validate the form.
```suggestion
```

2022-12-29 16:11 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Improved Centreon MAP Extension options so that only one MAP server is required to validate the form.
```suggestion
```

2022-12-29 16:11 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue when Sort on names when requesting the list of MAP web client.
```suggestion
- Fixed an issue where Sort on was on labels rather than names when requesting the list of maps from MAP web client.
```

2022-12-29 16:11 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue when Sort on names when requesting the list of MAP web client.
```suggestion
- Fixed an issue where Sort on was on labels rather than names when requesting the list of maps from MAP web client.
```

2022-12-29 16:11 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed the bug when switching from legacy to NG lead to broken tooltip links.
```suggestion
```

2022-12-29 16:11 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- fixed opacity migration bug for migrated url.
```suggestion
```

2022-12-29 16:11 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue when image not displayed in viewer.
```suggestion
- Fixed an issue where images were not displayed in viewer.
```

2022-12-29 16:11 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue that could cause layers to not be applied properly
```suggestion
```

2022-12-29 16:11 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed bug when url shape have unwanted concatenation inside the url.
```suggestion
- Fixed bug where url shape has unwanted concatenation inside the url.
```

2022-12-29 16:11 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
> +- Fixed the bug when acknowlegment is not displayed on the ressource.
```suggestion
- Fixed the bug where acknowledgements were not displayed on the resource.
```

2022-12-29 16:16 UTC, chgautier approved these changes

2022-12-29 16:48 UTC, merged