doc(release): prepare release notes for MAP 22.04.3
centreon/centreon-documentation pull request #2053
Opened 2022-12-23 15:09 UTC by tuntoja

## Description

Prepare release notes for MAP 22.04.3 (hotfix MON-16346)

## Target version

- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2022-12-23 15:11 UTC, nmagniezCentreon approved these changes

2022-12-23 15:16 UTC, smau-centreon requested changes

2022-12-23 15:16 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed "COPY FROM URL" button from viewer.
```suggestion
- Fixed "COPY FROM URL" feature from viewer.
```

2022-12-23 15:16 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed "COPY FROM URL" button from viewer.
```suggestion
- Fixed "COPY FROM URL" feature from viewer.
```

2022-12-23 15:29 UTC, smau-centreon approved these changes

2022-12-28 09:00 UTC, Jordan91 submitted a review, later dismissed

2022-12-28 16:50 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +Release date: `December 27, 2022`
```suggestion
Release date: `December 28, 2022`
```

2022-12-28 16:50 UTC, chgautier commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +Release date: `December 27, 2022`
```suggestion
Release date: `December 28, 2022`
```

2022-12-28 16:53 UTC, chgautier approved these changes

2022-12-28 17:29 UTC, merged