enh(epp): refactoring purestorage
centreon/centreon-documentation pull request #2055
Opened 2023-01-03 09:51 UTC by garnier-quentin

## Description

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-01-04 12:29 UTC, cg-tw requested changes

2023-01-04 12:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-legacy-restapi.md
> +Vous devez configurer l'utilisateur qui peut se connecter à la baie de stockage. Cet utilisateur doit avoir au moins un accès "en lecture seule" à la baie de stockage.
```suggestion
Vous devez configurer un utilisateur pouvant se connecter à la baie de stockage. Cet utilisateur doit avoir au moins un accès "en lecture seule" à la baie de stockage.
```

2023-01-04 12:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-legacy-restapi.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2023-01-04 12:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-v2-restapi.md
> +Vous devez configurer l'utilisateur qui peut se connecter à la baie de stockage. Cet utilisateur doit avoir au moins un accès "en lecture seule" à la baie de stockage.
```suggestion
Vous devez configurer un utilisateur pouvant se connecter à la baie de stockage. Cet utilisateur doit avoir au moins un accès "en lecture seule" à la baie de stockage.
```

2023-01-04 12:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-v2-restapi.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2023-01-04 12:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flashblade-v2-restapi.md
> +Vous devez configurer l'utilisateur qui peut se connecter à la baie de stockage. Cet utilisateur doit avoir au moins un accès "en lecture seule" à la baie de stockage.
```suggestion
Vous devez configurer un utilisateur pouvant se connecter à la baie de stockage. Cet utilisateur doit avoir au moins un accès "en lecture seule" à la baie de stockage.
```

2023-01-04 12:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flashblade-v2-restapi.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2023-01-16 15:28 UTC, omercier approved these changes

2023-01-17 10:30 UTC, cg-tw approved these changes

2023-01-17 11:11 UTC, merged