chore(release): prepare release notes for Web 22.04.8
centreon/centreon-documentation pull request #2062
Opened 2023-01-05 17:08 UTC by tuntoja

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-01-05 17:20 UTC, cg-tw requested changes

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- New API endpoint is now available to update a Centreon platform. This allows updates to take place without having the go through the Centreon Update Web Wizard.
```suggestion
- A new API endpoint is now available to update a Centreon platform. This allows updates to take place without having to go through the Centreon Update Web Wizard.
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [CEIP] Improved telemetry to know configured authentications options
```suggestion
- [CEIP] Improved telemetry to know configured authentication options
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Administration] Access group fields can now be empty for OpenId Connect configuration
```suggestion
- [Administration] Access group fields can now be empty for OpenID Connect configuration
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed a bug that blocked exporting multiple pollers configuration at the same time with a shared severity
```suggestion
- Fixed a bug that blocked exporting multiple poller configurations at the same time with a shared severity
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [ResourceStatus] Fix an issue that made users unable to Disacknowledge services
```suggestion
- [ResourceStatus] Fixed an issue that made users unable to disacknowledge services
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Authentication] Fixed authentication with complete url for token endpoint
```suggestion
- [Authentication] Fixed authentication with complete URL for token endpoint
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed an issue causing Acknowledgement/downtimes to fail without returning an error when the character case for the resource was wrong
```suggestion
- Fixed an issue causing acknowledgement/downtimes to fail without returning an error when the character case for the resource was wrong
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Core] API v2 now handles React pages.
```suggestion
- [Core] The v2 API now handles React pages.
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed an issue that cause months to be missing from the calendar selection
```suggestion
- Fixed an issue that caused months to be missing from the calendar selection
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed and issueTrying to log in to push the web upgrade/update does not return the depicted error message anymore.
```suggestion
- Fixed and issue where trying to log in to push the web upgrade/update does not return the depicted error message anymore.
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed issue when graphs could not be exported on the performance page.
```suggestion
- Fixed issue where graphs could not be exported on the performance page.
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +-	[Configuration] Fixed possibility to disable Contact/Contactgroup additive inheritance if not yet configured
```suggestion
-	[Configuration] Fixed possibility to disable contact/contact group additive inheritance if not yet configured
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [ResourceStatus] Fixed the display of command in service details panel
```suggestion
- [ResourceStatus] Fixed the display of commands in the service details panel
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Monitoring] Removed obsolete code to export of graph in CSV
```suggestion
- [Monitoring] Removed obsolete code to export graphs in CSV
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Resource-Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on Resource Status page
```suggestion
- [Resource-Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resource Status page
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +-	[API] Fixed API access when user doesn't have access to UI
```suggestion
- [API] Fixed API access when user doesn't have access to UI
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitized queries in service category
```suggestion
- [Configuration] Sanitized queries in service categories
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +-	[Core] Fixed vulnerabilities in color_picker.php
```suggestion
- [Core] Fixed vulnerabilities in color_picker.php
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +-	[Core] Fixed vulnerabilities in rename.php
```suggestion
- [Core] Fixed vulnerabilities in rename.php
```

2023-01-05 17:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +-	[Configuration] Fixed vulnerabilities in host form
```suggestion
- [Configuration] Fixed vulnerabilities in host form
```

2023-01-06 14:17 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed an issue with view contact notfications window
```suggestion
- Fixed an issue with "view contact notifications" window
```

2023-01-06 14:17 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- Fixed an issue with view contact notfications window
```suggestion
- Fixed an issue with "view contact notifications" window
```

2023-01-06 16:18 UTC, cg-tw approved these changes

2023-01-10 14:05 UTC, chgautier requested changes

2023-01-11 09:59 UTC, chgautier approved these changes

2023-01-11 12:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed and issue where trying to log in to push the web upgrade/update does not return the depicted error message anymore.
```suggestion
- Fixed an issue where trying to log in to push the web upgrade/update does not return the depicted error message anymore.
```

2023-01-11 12:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed an ACL issue allowing users to modify users even when they had read-only permissions
```suggestion
- Fixed an ACL issue with user modification permissions
```

2023-01-11 12:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- Fixed an issue preventing a user to edit a recurrent downtime if the linked host group was disabled
```suggestion
- Fixed an issue preventing a user to edit a recurrent downtime if the linked host group is disabled
```

2023-01-11 12:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Resource-Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resource Status page
```suggestion
- [Resources Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resources Status page
```

2023-01-11 12:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +[Install] Fixed app_key error during upgrade
```suggestion
- [Install] Fixed app_key error during upgrade
```

2023-01-11 12:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitized queries in the list of meta service
```suggestion
- [Configuration] Sanitized queries in the list of meta services
```

2023-01-11 12:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitized queries in the list of broker configurations
```suggestion
- [Configuration] Sanitized queries in the list of Broker configurations
```

2023-01-11 13:32 UTC, chgautier approved these changes

2023-01-11 13:37 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- Fixed and issue where trying to log in to push the web upgrade/update does not return the depicted error message anymore.
```suggestion
- Fixed an issue where trying to log in to push the web upgrade/update does not return the expected error message anymore.
```

2023-01-11 13:42 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- Fixed an ACL issue allowing users to modify users even when they had read-only permissions
```suggestion
- Fixed an ACL issue with user modification permissions
```

2023-01-11 13:42 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- Fixed issue where graphs could not be exported on the performance page.
```suggestion
- Fixed an issue where graphs could not be exported on the performance page.
```

2023-01-11 13:42 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Resource-Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resource Status page
```suggestion
- [Resources Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resources Status page
```

2023-01-11 13:42 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitized queries in the list of meta service
```suggestion
- [Configuration] Sanitized queries in the list of meta services
```

2023-01-11 13:42 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Configuration] Sanitized queries in the list of broker configurations
```suggestion
- [Configuration] Sanitized queries in the list of Broker configurations
```

2023-01-11 14:24 UTC, cg-tw approved these changes

2023-01-11 14:53 UTC, chgautier submitted a review, later dismissed

2023-01-16 09:11 UTC, cg-tw approved these changes

2023-01-16 10:11 UTC, chgautier approved these changes

2023-01-16 10:13 UTC, merged