doc(release): prepare release notes for Centreon Web 22.10.3
centreon/centreon-documentation pull request #2064
Opened 2023-01-06 16:39 UTC by tuntoja

## Description

Prepare release notes for Centreon Web 22.10.3

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-01-06 17:42 UTC, cg-tw requested changes

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed a bug that blocked exporting multiple pollers' configuration at he same time with a shared severity
```suggestion
- Fixed a bug that blocked exporting multiple pollers' configuration at the same time with a shared severity
```

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Authentication] Fixed authentication with complete url for token endpoint
```suggestion
- [Authentication] Fixed authentication with complete URL for token endpoint
```

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed bug whre it's impossible to filter on hosts and/or services in 22.10.
```suggestion
- Fixed bug where it's impossible to filter on hosts and/or services in Centreon 22.10.
```

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Bugfix of pagination on event log page
```suggestion
- Fixed bug with pagination on event log page
```

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Recurrent downtime editing issues with disabled objects
```suggestion
- Fixed recurrent downtime editing issues with disabled objects
```

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fix view contact notfications window
```suggestion
- Fixed "view contact notifications" window
```

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Resource-Status] Monitoring engine command displayed in detail regarding ACL configured
what does the sentence mean?

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed issue pagination not displayed in all legacy pages
```suggestion
- Fixed an issue where the pagination was not displayed in all legacy pages
```

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Configuration] Sanitized queries in the list of broker configurations
```suggestion
- [Configuration] Sanitized queries in the list of Broker configurations
```

2023-01-06 17:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed issue pagination not displayed in all legacy pages
already appears above

2023-01-09 08:42 UTC, mdebauchez requested changes

2023-01-09 08:42 UTC, mdebauchez commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Fixed issue pagination not displayed in all legacy pages
This line is already in the Bug fixes part (line 45)

2023-01-09 08:42 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed issue pagination not displayed in all legacy pages
This line is already in the Bug fixes part (line 44)

2023-01-09 14:46 UTC, mdebauchez approved these changes

2023-01-09 14:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Resource-Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resource Status page
```suggestion
- [Resources Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resources Status page
```

2023-01-09 14:50 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Resource-Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resource Status page
```suggestion
- [Resources Status] Fixed an issue causing ACL action "Display executed command by monitoring engine" to not be applied on the Resources Status page
```

2023-01-09 14:53 UTC, cg-tw approved these changes

2023-01-09 17:19 UTC, cg-tw submitted a review, later dismissed

2023-01-10 09:32 UTC, mdebauchez submitted a review, later dismissed

2023-01-10 10:39 UTC, cg-tw requested changes

2023-01-10 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +Release date: `January 2023, 9`
```suggestion
Release date: `January 9, 2023`
```

2023-01-10 10:39 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +Release date: `January 2023, 9`
```suggestion
Release date: `January 9, 2023`
```

2023-01-10 10:42 UTC, cg-tw approved these changes

2023-01-10 10:51 UTC, mdebauchez approved these changes

2023-01-10 15:21 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +
```suggestion

> There is currently a known issue affecting version 22.10.3. Please do not update your platform. A new version will be released shortly.

```

2023-01-10 15:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +Un problème connu affecte actuellement la version 22.10.3. Patientez avant de mettre votre plateforme à jour : une nouvelle version va être publiée sous peu.
```suggestion
> Un problème connu affecte actuellement la version 22.10.3. Patientez avant de mettre votre plateforme à jour : une nouvelle version va être publiée sous peu.
```

2023-01-10 15:23 UTC, cg-tw approved these changes

2023-01-10 15:25 UTC, mdebauchez approved these changes

2023-01-10 16:44 UTC, merged