chore-release): prepare release notes for MAP 22.10.4
centreon/centreon-documentation pull request #2075
Opened 2023-01-12 09:28 UTC by tuntoja

## Description

Prepare release notes for Centreon MAP 22.10.4 release.

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-01-12 09:37 UTC, cg-tw requested changes

2023-01-12 09:37 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed links when bendpoints are empty cause map to become not editable.
```suggestion
- Fixed issue where empty endpoints caused maps to become not editable.
```

2023-01-12 09:37 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue preventing to create MAP with API
```suggestion
- Fixed an issue preventing users to create a map with the API
```

2023-01-12 09:37 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed display label and use ressource name properties for links.
?

2023-01-12 10:09 UTC, cg-tw requested changes

2023-01-12 10:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed display label and use ressource name properties for links.
```suggestion
- Resource name properties are now used for links when saving maps.
```

2023-01-12 10:24 UTC, cg-tw approved these changes

2023-01-12 10:32 UTC, smau-centreon requested changes

2023-01-12 10:32 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue preventing users to create a map with the API
```suggestion
- Fixed an issue preventing users to create a map with the API.
```

2023-01-12 10:32 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- Fixed an issue preventing users to create a map with the API
```suggestion
- Fixed an issue preventing users to create a map with the API.
```

2023-01-12 14:01 UTC, cg-tw approved these changes

2023-01-12 14:02 UTC, smau-centreon approved these changes

2023-01-17 14:58 UTC, smau-centreon submitted a review, later dismissed

2023-01-17 17:10 UTC, cg-tw submitted a review, later dismissed

2023-01-18 07:52 UTC, smau-centreon approved these changes

2023-01-18 08:49 UTC, Jordan91 approved these changes

2023-01-18 09:22 UTC, merged