doc(release): prepare release notes for MAP 22.04.4
centreon/centreon-documentation pull request #2076
Opened 2023-01-12 09:59 UTC by tuntoja

## Description

Prepare release notes for Centreon MAP 22.04.4

## Target version

- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-01-12 10:25 UTC, cg-tw approved these changes

2023-01-12 10:32 UTC, smau-centreon requested changes

2023-01-12 10:32 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue preventing users to create a map with the API
```suggestion
- Fixed an issue preventing users to create a map with the API.
```

2023-01-12 10:32 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue preventing users to create a map with the API
```suggestion
- Fixed an issue preventing users to create a map with the API.
```

2023-01-12 13:49 UTC, smau-centreon submitted a review, later dismissed

2023-01-19 16:29 UTC, Jordan91 approved these changes

2023-01-20 15:34 UTC, smau-centreon requested changes

2023-01-20 15:34 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue that could cause layers to not be applied properly.
```suggestion
- Fixed an issue that could prevent the correct application of layers.
```

2023-01-20 15:34 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue that cause modifications to resource names in editor to not be properly updated after re opening editor.
```suggestion
- Fixed an issue where resource names modifications in the editor were not correctly updated after reopening the editor.
```

2023-01-20 15:34 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue that cause modifications to resource names in editor to not be properly updated after re opening editor.
```suggestion
- Fixed an issue where resource names modifications in the editor were not correctly updated after reopening the editor.
```

2023-01-20 15:34 UTC, smau-centreon commented on versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue that caused centreon-map-engine to require java-17-openjdk-devel rpm and prevented successful installation.
```suggestion
- Fixed an issue that caused MAP Engine server to require java-17-openjdk-devel RPM and prevented successful installation.
```

2023-01-20 15:34 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- Fixed an issue that caused centreon-map-engine to require java-17-openjdk-devel rpm and prevented successful installation.
```suggestion
- Fixed an issue that caused MAP Engine server to require java-17-openjdk-devel RPM and prevented successful installation.
```

2023-01-20 15:39 UTC, Jordan91 approved these changes

2023-01-20 15:41 UTC, smau-centreon approved these changes

2023-01-20 16:09 UTC, merged