add(epp): cloud talend tmc api
centreon/centreon-documentation pull request #2078
Opened 2023-01-13 10:01 UTC by garnier-quentin

## Description

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-01-16 15:28 UTC, omercier submitted a review, later dismissed

2023-01-17 08:27 UTC, cg-tw requested changes

2023-01-17 08:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-talend-tmc-api.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2023-01-17 08:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-talend-tmc-api.md
> +Please refer to their official documentation:: https://help.talend.com/r/en-US/Cloud/management-console-user-guide/cloud-access-token?utm_source=tadoc&utm_medium=learn_more
```suggestion
Please refer to the official documentation:: https://help.talend.com/r/en-US/Cloud/management-console-user-guide/cloud-access-token?utm_source=tadoc&utm_medium=learn_more
```

2023-01-17 09:49 UTC, omercier approved these changes

2023-01-17 10:03 UTC, cg-tw approved these changes

2023-01-17 10:29 UTC, merged