CIAM doc
centreon/centreon-documentation pull request #2080
Opened 2023-01-13 16:21 UTC by cg-tw

## Description

CIAM doc

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [x] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-01-19 18:35 UTC, nmagniezCentreon requested changes

2023-01-19 18:35 UTC, nmagniezCentreon commented on cloud/users/users.md
En fait les admin pouvaient principalement gérer les utlisateurs. C'est dans le CCIAM maintenant.
La permission de "installer des pluggin packs" se raporte aux editor aussi en fait.
Les 2 autres (time period et logs) ont été laissé tombée. 
Du coup:
Editor: can do the same things as **Users**, but they also can:
  * create hosts and services, meta-services, templates, categories...
  * disacknowledge an acknowledgement, submit a result...
  * view the list of pollers, export the configuration.
  * install plugin packs
Administrator: can do the same things as **Editors**, but they also can:
- manage users

2023-01-23 09:12 UTC, nmagniezCentreon approved these changes

2023-01-23 16:41 UTC, thiuyendang approved these changes

2023-01-23 17:12 UTC, merged