add(epp): oracle ucp jmx
centreon/centreon-documentation pull request #2103
Opened 2023-01-30 14:20 UTC by garnier-quentin

## Description

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-02-01 14:36 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
> +title: Oracle UCP JMX
@cg-tw do you think UCP is OK or should we have Universal Connection Pool?

2023-02-01 17:05 UTC, cg-tw requested changes

2023-02-01 17:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
> +Veuiller installer l'agent Jolokia sur votre JVM [Jolokia download page](https://jolokia.org/download.html).
```suggestion
Veuillez installer l'agent Jolokia sur votre JVM: [Jolokia download page](https://jolokia.org/download.html).
```

2023-02-01 17:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
> +Demander à votre administrateur de le déployer et de vous fournir l'URL.
```suggestion
Demandez à votre administrateur de le déployer et de vous fournir l'URL.
```

2023-02-01 17:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
> +sur le **serveur central** via la commande correspondant au gestionnaire de paquet
```suggestion
sur le **serveur central** via la commande correspondant au gestionnaire de paquets
```

2023-02-01 17:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
> +Please install jolokia agent on your JVM [Jolokia download page](https://jolokia.org/download.html). Ask to your admin to deploy it and give you the URL.
```suggestion
Please install the Jolokia agent on your JVM: [Jolokia download page](https://jolokia.org/download.html). Ask to your admin to deploy it and give you the URL.
```

2023-02-14 16:33 UTC, omercier requested changes

2023-02-14 16:33 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
> +Le Pack Centreon **Oracle UCP JMX** apporte un modèle d'hôte :
```suggestion
Le Pack Centreon **Oracle UCP JMX** apporte un modèle d'hôte pour la supervision d'**Oracle Universal Connection Pool** :
```

2023-02-14 16:33 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
> +The Centreon Pack **Oracle UCP JMX** brings a host template:
```suggestion
The Centreon Pack **Oracle UCP JMX** brings a host template to monitor **Oracle Universal Connection Pool**:
```

2023-02-14 16:34 UTC, cg-tw approved these changes

2023-02-14 16:34 UTC, omercier approved these changes

2023-02-15 16:20 UTC, merged