doc(release): prepare release note for MBI 22.10.1
centreon/centreon-documentation pull request #2115
Opened 2023-02-06 08:28 UTC by tuntoja

## Description

Prepare release notes for MBI 22.10.1

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-02-06 12:24 UTC, cg-tw approved these changes

2023-02-10 08:10 UTC, jdelpierre submitted a review, later dismissed

2023-02-10 09:11 UTC, smau-centreon requested changes

2023-02-10 09:11 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [ETL] Change the name of the scripts called by the ETL
```suggestion
- [ETL] Fixed the name of the scripts called by the ETL.
```

2023-02-10 09:11 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [ETL] Change the name of the scripts called by the ETL
```suggestion
- [ETL] Fixed the name of the scripts called by the ETL.
```

2023-02-10 09:48 UTC, jdelpierre commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [ETL] Change the name of the scripts called by the ETL
Yes, it's ok

2023-02-10 09:48 UTC, jdelpierre commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [ETL] Change the name of the scripts called by the ETL
Yes, it's ok

2023-02-10 09:49 UTC, jdelpierre approved these changes

2023-02-10 09:49 UTC, smau-centreon approved these changes

2023-02-10 10:18 UTC, merged