update(doc)CISCO USC SNMP
centreon/centreon-documentation pull request #2125
Opened 2023-02-08 21:56 UTC by ponchoh

## Description

- use new template
- link for SNMP config
- plugin location

## Target version

- [x] Plugin Packs (staging)

2023-03-14 16:13 UTC, cg-tw requested changes

2023-03-14 16:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md
> +If you are using SNMP Version 3, use the **SNMPEXTRAOPTIONS** macro to configure
```suggestion
```

2023-03-14 17:05 UTC, cg-tw approved these changes

2023-08-29 15:27 UTC, omercier approved these changes

2024-07-09 13:26 UTC, closed without merging

2024-07-09 13:26 UTC, cg-tw commented
Obsolete, replaced by https://github.com/centreon/centreon-documentation/pull/3419/.