MON-15626-add-azure-management-policies-pack
centreon/centreon-documentation pull request #2149
Opened 2023-02-22 09:38 UTC by sdepassio

## Description
Adding documentation for the new Azure Management Policies Pack

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [x] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-14 13:31 UTC, cg-tw requested changes

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +> Les services par "Défaut" sont automatiquement liés au(x) modèle(s) d'hôte.
```suggestion
> Les services par **Défaut** sont créés automatiquement lorsque le modèle d'hôte est appliqué.
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +* Ajoutez un hôte à Centreon depuis la page **Configuration > Hôtes**.
```suggestion
1. Ajoutez un hôte à Centreon depuis la page **Configuration > Hôtes**.
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +* Remplissez le champ **Adresse IP/DNS** avec l'adresse **127.0.0.1**.
```suggestion
2. Remplissez le champ **Adresse IP/DNS** avec l'adresse **127.0.0.1**.
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +* Appliquez le modèle d'hôte **Cloud-Azure-PolicyInsights-PolicyStates**.
```suggestion
3. Appliquez le modèle d'hôte **Cloud-Azure-PolicyInsights-PolicyStates**.
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +* Une fois le modèle appliqué, renseignez les macros correspondantes. Attention, certaines macros sont obligatoires. Elles doivent être renseignées selon le *custom mode* utilisé.
```suggestion
4. Une fois le modèle appliqué, renseignez les macros correspondantes. Attention, certaines macros sont obligatoires. Elles doivent être renseignées selon le *custom mode* utilisé.
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --explode-perfdata-max                     |     Put max perfdata (if it exist) in a specific perfdata (without values: same with '\_max' suffix) (Multiple options)
```suggestion
| --explode-perfdata-max                     |     Put max perfdata (if it exists) in a specific perfdata (without values: same with '\_max' suffix) (Multiple options)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Output       |
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --range-perfdata                           |     Change perfdata range thresholds display: 1 = start value equals to '0' is removed, 2 = threshold range is not display.
```suggestion
| --range-perfdata                           |     Change perfdata range thresholds display: 1 = start value equals to '0' is removed, 2 = threshold range is not displayed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Output       |
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --zeroed                                   |     Set metrics value to 0 if none. Usefull when Monitor does not return value when not defined.
```suggestion
| --zeroed                                   |     Set metrics value to 0 if none. Useful when Monitor does not return value when not defined.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Api          |
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --http-peer-addr                           |     Set the address you want to connect (Useful if hostname is only a vhost. no ip resolve)
```suggestion
| --http-peer-addr                           |     Set the address you want to connect to (Useful if hostname is only a vhost. No IP resolve)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Http global  |
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --proxypac                                 |     Proxy pac file (can be an url or local file)
```suggestion
| --proxypac                                 |     Proxy .pac file (can be a URL or a local file)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Http global  |
```

2023-03-14 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --redis-server                             |     Redis server to use (only one server). SYntax: address\[:port\]
```suggestion
| --redis-server                             |     Redis server to use (only one server). Syntax: address\[:port\]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Retention    |
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +> *Default* services templates are automatically linked to the host template(s).
```suggestion
> **Default** services are automatically created when the host template is applied.
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +
```suggestion
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +* Log into Centreon and add a new host through **Configuration > Hosts**.
```suggestion
1. Log into Centreon and add a new host through **Configuration > Hosts**.
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +* In the **IP Address/DNS** field, set the following IP address: **127.0.0.1**.
```suggestion
2. In the **IP Address/DNS** field, set the following IP address: **127.0.0.1**.
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +* Apply the **Cloud-Azure-PolicyInsights-PolicyStates** template to the host.
```suggestion
3. Apply the **Cloud-Azure-PolicyInsights-PolicyStates** template to the host.
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +* Once the template is applied, fill in the corresponding macros. Some macros are mandatory.
```suggestion
4. Once the template is applied, fill in the corresponding macros. Some macros are mandatory.
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +All  modes specific options are listed here:
```suggestion
All modes-specific options are listed here:
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --explode-perfdata-max                     |     Put max perfdata (if it exist) in a specific perfdata (without values: same with '\_max' suffix) (Multiple options)
```suggestion
| --explode-perfdata-max                     |     Put max perfdata (if it exists) in a specific perfdata (without values: same with '\_max' suffix) (Multiple options)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Output       |
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --range-perfdata                           |     Change perfdata range thresholds display: 1 = start value equals to '0' is removed, 2 = threshold range is not display.
```suggestion
| --range-perfdata                           |     Change perfdata range thresholds display: 1 = start value equals to '0' is removed, 2 = threshold range is not displayed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Output       |
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --source-encoding                          |     Set encoding of monitoring sources (In some case. Default: 'UTF-8').      Microsoft Azure Rest API      To connect to the Azure Rest API, you must r
```suggestion
| --source-encoding                          |     Set encoding of monitoring sources (In some cases. Default: 'UTF-8').      Microsoft Azure Rest API      To connect to the Azure Rest API, you must register an application.      Follow the 'How-to guide' in     https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal. The application needs the 'Monitoring Reader' role (see https://docs.microsoft.com/en-us/azure/azure-monitor/platform/roles-permissions-security#monitoring-reader). This custom mode is using the 'OAuth 2.0 Client Credentials Grant Flow'. For futher informations, visit     https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-client-creds-grant-flow   | Output       |
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --aggregation                              |     Set monitor aggregation (Can be multiple, Can be: 'minimum', 'maximum', 'average', 'total', 'count').
```suggestion
| --aggregation                              |     Set monitor aggregation (can be multiple, can be: 'minimum', 'maximum', 'average', 'total', 'count').                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Api          |
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --zeroed                                   |     Set metrics value to 0 if none. Usefull when Monitor does not return value when not defined.
```suggestion
| --zeroed                                   |     Set metrics value to 0 if none. Useful when Monitor does not return value when not defined.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Api          |
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --proxypac                                 |     Proxy pac file (can be an url or local file)
```suggestion
| --proxypac                                 |     Proxy .pac file (can be a URL or a local file)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Http global  |
```

2023-03-14 13:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --redis-server                             |     Redis server to use (only one server). SYntax: address\[:port\]
```suggestion
| --redis-server                             |     Redis server to use (only one server). Syntax: address\[:port\]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Retention    |
```

2023-03-14 15:20 UTC, cg-tw requested changes

2023-03-14 15:31 UTC, cg-tw approved these changes

2023-03-14 17:17 UTC, cg-tw approved these changes

2023-03-15 08:43 UTC, omercier submitted a review, later dismissed

2023-03-15 09:59 UTC, cg-tw requested changes

2023-03-15 09:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --source-encoding                          | Set encoding of monitoring sources (In some case. Default: 'UTF-8').      Microsoft Azure Rest API      To connect to the Azure Rest API, you must regis
```suggestion
| --source-encoding                          | Set encoding of monitoring sources (In some cases. Default: 'UTF-8').      Microsoft Azure Rest API.     To connect to the Azure Rest API, you must register an application.      Follow the 'How-to guide' at https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal. The application needs the 'Monitoring Reader' role (see https://docs.microsoft.com/en-us/azure/azure-monitor/platform/roles-permissions-security#monitoring-reader). This custom mode is using the 'OAuth 2.0 Client Credentials Grant Flow'. For further information, visit  https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-client-creds-grant-flow | Output       |
```

2023-03-15 09:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --http-peer-addr                           | Set the address you want to connect (Useful if hostname is only a vhost. no IP resolve)
```suggestion
| --http-peer-addr                           | Set the address you want to connect (useful if hostname is only a vhost. No IP resolve)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | Http global  |
```

2023-03-15 10:05 UTC, cg-tw requested changes

2023-03-15 10:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --source-encoding                          | Set encoding of monitoring sources (In some case. Default: 'UTF-8').      Microsoft Azure Rest API      To connect to the Azure Rest API, you must regis
```suggestion
| --source-encoding                          | Set encoding of monitoring sources (In some cases. Default: 'UTF-8').      Microsoft Azure Rest API.    To connect to the Azure Rest API, you must register an application.      Follow the 'How-to guide' at https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal. The application needs the 'Monitoring Reader' role (see https://docs.microsoft.com/en-us/azure/azure-monitor/platform/roles-permissions-security#monitoring-reader). This custom mode is using the 'OAuth 2.0 Client Credentials Grant Flow'. For further information, visit https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-client-creds-grant-flow | Output       |
```

2023-03-15 10:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +| --http-peer-addr                           | Set the address you want to connect (Useful if hostname is only a vhost. no IP resolve)
```suggestion
| --http-peer-addr                           | Set the address you want to connect (useful if hostname is only a vhost. No IP resolve)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | Http global  |
```

2023-03-15 10:40 UTC, cg-tw approved these changes

2023-03-15 12:42 UTC, itoussies requested changes

2023-03-15 12:42 UTC, itoussies commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +3. Appliquez le modèle d'hôte **Cloud-Azure-PolicyInsights-PolicyStates**.
```suggestion
3. Appliquez le modèle d'hôte **Cloud-Azure-PolicyInsights-PolicyStates-custom**.
```

2023-03-15 12:42 UTC, itoussies commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +3. Apply the **Cloud-Azure-PolicyInsights-PolicyStates** template to the host.
```suggestion
3. Apply the **Cloud-Azure-PolicyInsights-PolicyStates-custom** template to the host.
```

2023-03-15 12:49 UTC, cg-tw approved these changes

2023-03-15 12:50 UTC, itoussies approved these changes

2023-03-15 12:52 UTC, omercier approved these changes

2023-03-15 13:16 UTC, merged