Ps 112 upgrading ha rhel8 21.10 to 22.10
centreon/centreon-documentation pull request #2152
Opened 2023-02-24 09:07 UTC by cedricmeschin

## Description

PS-112 Upgrade 21.10 to 22.10 RHEL8 HA 2nodes - distinct EL8 and EL7 for export command and some typo's

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [X] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-02 14:50 UTC, psamecentreon submitted a review, later dismissed

2023-03-03 08:40 UTC, cg-tw requested changes

2023-03-03 08:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
> +> Pour le **nœud central passif** et **le nœud base de données passif s'il existe**, merdi de [suivre la documentation officielle](../../upgrade/upgrade-from-21-10.md) **jusqu'à l'étape "Mettre à jou
```suggestion
> Pour le **nœud central passif** et **le nœud base de données passif s'il existe**, merci de [suivre la documentation officielle](../../upgrade/upgrade-from-21-10.md) **jusqu'à l'étape "Mettre à jour une configuration Apache personnalisée" incluse uniquement. Ne pas procéder à l'étape "Finalisation de la mise à jour**.
```

2023-03-03 08:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
> +Uniquement sur les serveurs deux nœuds Centraux, restaurer le fichier `/etc/centreon-ha/centreon_central_sync.pm`.
```suggestion
Uniquement sur les serveurs deux nœuds centraux, restaurer le fichier `/etc/centreon-ha/centreon_central_sync.pm`.
```

2023-03-03 08:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
> +Sur le nœud central passif, déplacez le répertoire "install" pour éviter d'obtenir l'écran "upgrade" dans le WUI en cas de nouvel échange de rôles et recharger le cache Apache.
```suggestion
Sur le nœud central passif, déplacez le répertoire **install** pour éviter d'obtenir l'écran "upgrade" dans l'interface en cas de nouvel échange de rôles et rechargez le cache Apache.
```

2023-03-03 08:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
> +Réaliser une sauvegarde du cluster en exécutant les commandes suivantes :
```suggestion
Réalisez une sauvegarde du cluster en exécutant les commandes suivantes :
```

2023-03-03 08:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
>  Il est nécessaire de modifier la configuration de mysql en éditant `/etc/my.cnf.d/server.cnf` :
```suggestion
Il est nécessaire de modifier la configuration de MySQL en éditant `/etc/my.cnf.d/server.cnf` :
```

2023-03-03 08:40 UTC, cg-tw commented on versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
> +> For the **passive central node** and **passive database node if needed**, please [follow the official documentation](../../upgrade/upgrade-from-21-10.md) **until the "Update your customized Apache
```suggestion
> For the **passive central node** and **passive database node if needed**, please [follow the official documentation](../../upgrade/upgrade-from-21-10.md) **until the "Update your customized Apache configuration" step included only. Do not perform the "Finalizing the upgrade" step.**.
```

2023-03-03 08:40 UTC, cg-tw commented on versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
>  > **WARNING:** the syntax of the following command depends on the Linux Distribution you are using.
```suggestion
> **WARNING:** the syntax of the following command depends on the Linux distribution you are using.
```

2023-03-03 08:40 UTC, cg-tw commented on versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
> +> You can find @CENTRAL_MASTER_NAME@ @CENTRAL_SLAVE_NAME@ @MARIADB_REPL_USER@ @MARIADB_REPL_USER@ variable in `/etc/centreon-ha/mysql-resources.sh`
```suggestion
> You can find the @CENTRAL_MASTER_NAME@ @CENTRAL_SLAVE_NAME@ @MARIADB_REPL_USER@ @MARIADB_REPL_USER@ variables in `/etc/centreon-ha/mysql-resources.sh`
```

2023-03-03 08:40 UTC, cg-tw commented on versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
>  > **WARNING:** the syntax of the following command depends on the Linux Distribution you are using.
```suggestion
> **WARNING:** the syntax of the following command depends on the Linux distribution you are using.
```

2023-03-03 12:14 UTC, cg-tw approved these changes

2023-03-31 17:42 UTC, psamecentreon approved these changes

2023-04-03 09:34 UTC, merged