Add Cisco WLC documentation after updating Plugin-pack
centreon/centreon-documentation pull request #2153
Opened 2023-02-24 15:08 UTC by lucie-dubrunfaut

## Description

Update Plugin pack documentation to add a Service Discovery Rule to discover APs for Cisco WLC controllers

2023-03-14 09:04 UTC, cg-tw requested changes

2023-03-14 09:06 UTC, cg-tw requested changes

2023-03-14 09:06 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
> +Please refer to the official documentation from XXX:
missing link

2023-03-14 09:17 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
> +Les options globales aux modes sont listées ci-dessus :
Je pense ci-dessous car en EN on a :
All global options are listed here:
puis une liste d'option

2023-03-14 16:25 UTC, omercier submitted a review, later dismissed

2023-03-14 16:26 UTC, cg-tw approved these changes

2023-03-15 09:15 UTC, cg-tw requested changes

2023-03-15 09:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
> +Please refer to the official documentation from XXX:
```suggestion
Please refer to the official documentation:
```

2023-03-15 09:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
> +* * [CISCO WLC](https://www.cisco.com/c/en/us/td/docs/wireless/controller/8-5/config-guide/b_cg85/snmp.html)
```suggestion
* [CISCO WLC](https://www.cisco.com/c/en/us/td/docs/wireless/controller/8-5/config-guide/b_cg85/snmp.html)
```

2023-03-15 09:16 UTC, cg-tw approved these changes

2023-03-15 10:44 UTC, omercier approved these changes

2023-03-15 10:53 UTC, merged