Enhance HTTPS documentation
centreon/centreon-documentation pull request #2162
Opened 2023-03-06 16:58 UTC by itoussies

## Description

Fixes when a Centreon plateform uses HTTPS are missing. Theses fixes can be found on the internet or are only known by the Centreon members. Enhancing the documentation will reduce the number of support tickets and related thread on The Watch.

Those parts include:

* Gorgone/Auto discovery fix 
* Export your configuration” button fix (does not exists for Centreon 21.10 so no modifications here)

## Target version

- [X] 21.10.x (staging)
- [X] 22.04.x (staging)
- [X] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-09 10:27 UTC, cg-tw requested changes

2023-03-09 10:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/secure-platform.md
> +Redémarrer le daemon Gorgone :
```suggestion
Redémarrez le daemon Gorgone :
```

2023-03-09 10:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md
> +Redémarrer le daemon Gorgone :
```suggestion
Redémarrez le daemon Gorgone :
```

2023-03-09 10:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md
> +Redémarrer le daemon Gorgone :
```suggestion
Redémarrez le daemon Gorgone :
```

2023-03-09 17:08 UTC, itoussies commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/secure-platform.md
> +Redémarrer le daemon Gorgone :
Hum. Je vois de l'infinitif dans les chapitres avec des numéro mais pas dans le cors du texte

2023-03-16 11:27 UTC, rsadik-ext submitted a review, later dismissed

2023-03-29 14:42 UTC, rsadik-ext approved these changes

2023-03-29 15:18 UTC, merged