MON-16159-plugin-pack-centreon-pack-virtualization-vmware-2-esx-host-…
centreon/centreon-documentation pull request #2173
Opened 2023-03-08 14:39 UTC by YanMeddour

…autodiscovery-attributs-issue

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-08 14:45 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +> Pour découvrir les balises et les attributs personnalisés, vous devez utiliser la version 3.2.5 de centreon-vmware-daemon et ajouter --tags dans les options supplémentaires de découverte.
Can you explain how to do it?

2023-03-09 14:53 UTC, cg-tw requested changes

2023-03-09 14:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +>Allez sur la page Configuration > Hôtes > Découverte, et à la 3ème étape ("Définir les paramètres de découverte"), dans la section Paramètres supplémentaires, dans le champ Options supplémentaires,
```suggestion
>Allez à la page **Configuration > Hôtes > Découverte**, et à la 3ème étape (**Définir les paramètres de découverte**), dans la section **Paramètres supplémentaires**, dans le champ **Options supplémentaires**, saisissez **--tags**.
```

2023-03-09 15:34 UTC, cg-tw approved these changes

2023-03-15 08:28 UTC, omercier approved these changes

2023-03-15 09:43 UTC, cg-tw approved these changes

2023-03-15 10:44 UTC, omercier approved these changes

2023-03-15 13:23 UTC, cg-tw approved these changes

2023-03-15 13:58 UTC, omercier approved these changes

2023-03-15 14:04 UTC, merged