MON-14220-allow-user-to-use-ip-management-attribute-in-mapper-definit…
centreon/centreon-documentation pull request #2178
Opened 2023-03-09 14:52 UTC by YanMeddour

…ion-with-vm-ware-vm-discovery

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-09 14:57 UTC, cg-tw requested changes

2023-03-09 14:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
> +>Allez sur la page Configuration > Hôtes > Découverte, et à la 3ème étape ("Définir les paramètres de découverte"), dans la section Paramètres supplémentaires, dans le champ Options supplémentaires,
```suggestion
>Allez à la page **Configuration > Hôtes > Découverte**, et à la 3ème étape (**Définir les paramètres de découverte**), dans la section **Paramètres supplémentaires**, dans le champ **Options supplémentaires**, saisissez **--tags**.
```

2023-03-09 14:57 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
> +
```suggestion
>Go to page **Configuration > Hosts > Discovery**, and at the 3rd step (**Define discovery parameters**), in section **Additional parameters**, in the **Extra Options** field, enter **--tags**.
```

2023-03-09 15:33 UTC, cg-tw approved these changes

2023-04-11 14:05 UTC, omercier requested changes

2023-04-11 14:05 UTC, omercier commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
> +>Go to page **Configuration > Hosts > Discovery**, and at the 3rd step (**Define discovery parameters**), in section **Additional parameters**, in the **Extra Options** field, enter **--tags**.
Please review this paragraph according to my comment in the french version

2023-04-13 14:32 UTC, cg-tw approved these changes

2023-04-13 14:42 UTC, omercier approved these changes

2023-04-13 15:26 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
> +> To discover Tags and Custom Attributes, you must :
```suggestion
To discover Tags and Custom Attributes, you must : 
```

2023-04-13 15:34 UTC, omercier approved these changes

2023-04-13 15:54 UTC, merged