doc(release): Prepare release notes for oss 21.10.14
centreon/centreon-documentation pull request #2180
Opened 2023-03-10 16:06 UTC by chgautier

## Description
Release notes for 21.10.14

## Target version

- [ x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-13 10:18 UTC, smau-centreon requested changes

2023-03-13 10:18 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Core] Fixed vulnerabilities in functions.js file
```suggestion
- [Core] Fixed vulnerabilities in functions.js file.
```

2023-03-13 10:18 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Core] Fixed vulnerabilities in functions.js file
```suggestion
- [Core] Fixed vulnerabilities in functions.js file.
```

2023-03-13 10:18 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Monitoring] Removed obsolete code to export of graph in CSV
```suggestion
- [Monitoring] Removed obsolete code for exporting a graph in CSV.
```

2023-03-13 10:18 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Monitoring] Removed obsolete code to export of graph in CSV
```suggestion
- [Monitoring] Removed obsolete code for exporting a graph in CSV.
```

2023-03-13 10:18 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-os-extensions.md
> +- [Provider] Fixed default iTop url.
```suggestion
- [Provider] Fixed default iTop URL.
```

2023-03-13 10:18 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-os-extensions.md
> +- [Provider] Fixed default iTop url.
```suggestion
- [Provider] Fixed default iTop URL.
```

2023-03-14 16:34 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Core] Fixed vulnerabilities in color_picker_mb.php.
```suggestion
- [Core] Fixed vulnerabilities in color_picker.php.
- [Core] Fixed vulnerabilities in color_picker_mb.php.
```

2023-03-14 16:34 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Core] Fixed vulnerabilities in color_picker_mb.php.
```suggestion
- [Core] Fixed vulnerabilities in color_picker.php.
- [Core] Fixed vulnerabilities in color_picker_mb.php.
```

2023-03-14 16:44 UTC, rsadik-ext approved these changes

2023-03-15 15:47 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +Release date: `March before April, 2023`
```suggestion
Release date: `March 15, 2023`
```

2023-03-15 15:47 UTC, chgautier commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-os-extensions.md
> +Release date: `March of the Penguins, 2023`
```suggestion
Release date: `March 15, 2023`
```

2023-03-15 15:47 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-core.md
> +Release date: `March before April, 2023`
```suggestion
Release date: `March 15, 2023`
```

2023-03-15 15:47 UTC, chgautier commented on versioned_docs/version-21.10/releases/centreon-os-extensions.md
> +Release date: `March of the Penguins, 2023`
```suggestion
Release date: `March 15, 2023`
```

2023-03-15 15:52 UTC, smau-centreon approved these changes

2023-03-17 10:12 UTC, merged