doc(release): prepare release notes for modules 2110
centreon/centreon-documentation pull request #2181
Opened 2023-03-13 15:52 UTC by tuntoja

## Description

Prepare release notes for release of modules 21.10.next

## Target version

- [x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-17 08:55 UTC, smau-centreon approved these changes

2023-03-20 09:52 UTC, smau-centreon requested changes

2023-03-20 09:52 UTC, smau-centreon commented on versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
>  ## Centreon MAP
```suggestion
## Centreon MAP Legacy
```

2023-03-24 08:36 UTC, sfarouq-ext submitted a review, later dismissed
approving for the part Centreon Auto Discovery

2023-03-24 09:08 UTC, smau-centreon approved these changes

2023-06-01 08:23 UTC, closed without merging