doc(release): Prepare release notes for collect 22.10.1
centreon/centreon-documentation pull request #2187
Opened 2023-03-15 16:34 UTC by chgautier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-15 16:38 UTC, chgautier commented
Kindly wait for go before merging

2023-03-15 16:51 UTC, smau-centreon requested changes

2023-03-15 16:51 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed a defect in the Stream Connector mechanism that would not handle the BBDO v3 RRD rebuild events.
```suggestion
- Fixed an issue in the Stream Connector mechanism that would not handle the BBDO v3 RRD rebuild events.
```

2023-03-15 16:51 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Fixed a defect in the Stream Connector mechanism that would not handle the BBDO v3 RRD rebuild events.
```suggestion
- Fixed an issue in the Stream Connector mechanism that would not handle the BBDO v3 RRD rebuild events.
```

2023-03-17 09:32 UTC, tuntoja approved these changes

2023-03-17 10:12 UTC, merged