Install/upgrade 23.04
centreon/centreon-documentation pull request #2190
Opened 2023-03-20 15:46 UTC by cg-tw

## Description

Install/upgrade 23.04
Preview container here: http://10.25.11.244:56567/

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [x] 23.04.x (next)

2023-04-04 11:51 UTC, rsadik-ext approved these changes

2023-04-04 11:55 UTC, rsadik-ext submitted a review, later dismissed

2023-04-05 12:46 UTC, thiuyendang requested changes

2023-04-05 12:46 UTC, thiuyendang commented on versioned_docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
> +dnf config-manager --add-repo https://centreon.jfrog.io/artifactory/rpm/standard/23.04/el8/centreon.repo
```suggestion
dnf config-manager --add-repo https://centreon.jfrog.io/artifactory/rpm-standard/23.04/el8/centreon-23.04.repo
```

2023-04-05 12:46 UTC, thiuyendang commented on versioned_docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
> +dnf config-manager --set-enabled 'centreon*'
```suggestion
dnf config-manager --set-enabled 'centreon*' , this command has to be deleted, only stable repo must be enabled and should be by default in the file
```

2023-04-07 15:57 UTC, rsadik-ext submitted a review, later dismissed

2023-04-18 13:52 UTC, rsadik-ext requested changes

2023-04-18 13:52 UTC, rsadik-ext commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
> +systemctl enable php-fpm httpd mariadb centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd
systemctl enable php-fpm httpd centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd

2023-04-18 13:52 UTC, rsadik-ext commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md
> +systemctl enable php-fpm httpd mariadb centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd
systemctl enable php-fpm httpd centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd

2023-04-18 13:52 UTC, rsadik-ext commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md
> +systemctl enable php8.1-fpm apache2 mariadb centreon cbd centengine gorgoned centreontrapd snmpd snmptrapd
systemctl enable php-fpm httpd  centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd

2023-04-18 13:52 UTC, rsadik-ext commented on versioned_docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
> +systemctl enable php-fpm httpd mariadb centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd
systemctl enable php-fpm httpd  centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd

2023-04-18 13:52 UTC, rsadik-ext commented on versioned_docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md
> +systemctl enable php-fpm httpd mariadb centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd
systemctl enable php-fpm httpd centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd

2023-04-18 13:52 UTC, rsadik-ext commented on versioned_docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md
> +systemctl enable php-fpm httpd mariadb centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd
systemctl enable php-fpm httpd centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd

2023-04-18 13:52 UTC, rsadik-ext commented on versioned_docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md
> +systemctl enable php8.1-fpm apache2 mariadb centreon cbd centengine gorgoned centreontrapd snmpd snmptrapd
systemctl enable php8.1-fpm apache2 centreon cbd centengine gorgoned centreontrapd snmpd snmptrapd

2023-04-20 10:43 UTC, rsadik-ext requested changes
You can do these changes for redhat9 for central & remote server too

2023-04-20 10:43 UTC, rsadik-ext commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
> +dnf install epel-release
```suggestion
dnf install -y http://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
```

2023-04-20 10:43 UTC, rsadik-ext commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
> +```
```suggestion
dnf config-manager --set-enabled codeready-builder-for-rhel-9-rhui-rpms
```
```

2023-04-24 09:23 UTC, thiuyendang approved these changes

2023-04-24 09:25 UTC, rsadik-ext approved these changes

2023-04-24 09:48 UTC, merged