doc(release): Prepare release notes for modules next 22.10
centreon/centreon-documentation pull request #2198
Opened 2023-03-27 14:43 UTC by tuntoja

Prepare release notes for Centreon Modules next 22.04

2023-04-14 12:10 UTC, nmagniezCentreon requested changes

2023-04-14 12:10 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed a cosmetic issue in Bam & Autodiscovery table header
remove BAM?

2023-04-14 12:10 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +
manque 
- update draw.io : "Update draw.io library" (15827)
- Fixed an issue that caused the unit not matching the axis on graph widget. (12115)

2023-04-14 15:32 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [API] Removed deprecated REST endpoints.
A supprimer, ca va faire peur alors que c'est des trucs qui n'étaient pas visibles

2023-04-14 15:48 UTC, nmagniezCentreon approved these changes

2023-04-17 08:54 UTC, smau-centreon requested changes

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Editor] Update draw.io library.
To rephrase

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [CEIP] Added more details for MAP engine telemetry.
To keep as is?

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Install] Fixed an issue preventing the installation of centreon-map-engine on the same machine as centreon-map-server.
```suggestion
- [Install] Fixed an issue preventing the installation of **centreon-map-engine** on the same machine as **centreon-map-server**.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Monitoring] Fixed an issue where MAP was not supporting performance data returned  by Cisco ASA plugin.
```suggestion
- [Monitoring] Fixed an issue where MAP was not supporting performance data returned by Cisco ASA plugin.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Server] Fix migration issue with images that could stop migration process.
```suggestion
- [Server] Fixed a migration issue with images that could stop the migration process.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Server] Fix migration issue with images that could stop migration process.
```suggestion
- [Server] Fixed a migration issue with images that could stop the migration process.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Editor] Update draw.io library.
To rephrase

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Server] Fixed configure.sh script to include storage event from broker output.
```suggestion
- [Install] Fixed the **configure.sh** script to include storage event from Broker output.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Server] Fixed issue that made new hosts and services unavailable until restart.
```suggestion
- [Server] Fixed an issue that made new hosts and services unavailable until restart.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Server] Fixed issue that made new hosts and services unavailable until restart.
```suggestion
- [Server] Fixed an issue that made new hosts and services unavailable until restart.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Server] Fixed the server startup error due to PF without virtual hosts.
```suggestion
- [Server] Fixed an issue with the server startup error caused by platform without virtual hosts.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed Colors for a "Text" type element is ignored by the viewer.
```suggestion
- [Viewer] Fixed an issue with colors for a "Text" type element that was ignored by the viewer.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed an issue when tooltip don't display for "old perfdata" plugin in the graph.
```suggestion
- [UI] Fixed an issue where tooltips were not displayed for "old perfdata" plugin in the graph.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed an issue when tooltip don't display for "old perfdata" plugin in the graph.
```suggestion
- [UI] Fixed an issue where tooltips were not displayed for "old perfdata" plugin in the graph.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed an issue when updating a resource that did not display the new resource name.
```suggestion
- [UI] Fixed an issue where updating a resource was not displaying the new resource name.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed an issue when updating a resource that did not display the new resource name.
```suggestion
- [UI] Fixed an issue where updating a resource was not displaying the new resource name.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed bug who display a blank page when user click on host name inside a map.
```suggestion
- [UI] Fixed an issue where a blank page was displayed when the user clicked on a host name inside a map.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed bug who display a blank page when user click on host name inside a map.
```suggestion
- [UI] Fixed an issue where a blank page was displayed when the user clicked on a host name inside a map.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed issue when Dark Theme is not apply on tooltip in Geo Views / MAP ENGINE.
```suggestion
- [UI] Fixed an issue where dark theme was not applied on tooltips in Geo views.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed issue when Dark Theme is not apply on tooltip in Geo Views / MAP ENGINE.
```suggestion
- [UI] Fixed an issue where dark theme was not applied on tooltips in Geo views.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed the background layout not fitting large map.
```suggestion
- [UI] Fixed the background layout that was not fitting large maps.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed the background layout not fitting large map.
```suggestion
- [UI] Fixed the background layout that was not fitting large maps.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [API] Improve api response when server is starting up.
```suggestion
- [API] Improved the API response when server is starting up.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Editor] Manage font properties in editor.
```suggestion
- [Editor] You can now manage font properties in the editor.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Editor] Manage view background color.
```suggestion
- [Editor] You can now manage the view background color.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed a cosmetic issue in Bam & Autodiscovery table header
```suggestion
- [UI] Fixed a cosmetic issue in BAM and Autodiscovery table header.
```

2023-04-17 08:54 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [UI] Fixed a cosmetic issue in Bam & Autodiscovery table header
```suggestion
- [UI] Fixed a cosmetic issue in BAM and Autodiscovery table header.
```

2023-04-17 08:54 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Install] Fixed an packaging issue that prevented anomaly detection from being installed.
```suggestion
- [Install] Fixed a packaging issue that prevented Anomaly Detection from being installed.
```

2023-04-18 08:31 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [Editor] Update draw.io library.
should it be this @nmagniezCentreon ?
Fixed the security issue CVE-2022-42889 (Text4shell).

2023-04-18 08:31 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +- [CEIP] Added more details for MAP engine telemetry.
Will be removed

2023-04-18 15:49 UTC, Jordan91 submitted a review, later dismissed

2023-04-18 15:55 UTC, smau-centreon approved these changes

2023-04-21 12:46 UTC, nmagniezCentreon approved these changes

2023-04-24 18:55 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-24 18:55 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-24 18:55 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-24 18:55 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-24 18:55 UTC, tuntoja commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-24 18:55 UTC, tuntoja commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-24 18:55 UTC, tuntoja commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-24 18:55 UTC, tuntoja commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-24 18:55 UTC, tuntoja commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +Release date: `April 18, 2023`
```suggestion
Release date: `April 24, 2023`
```

2023-04-25 07:49 UTC, nmagniezCentreon submitted a review, later dismissed

2023-04-25 08:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +> You need to [execute the **configure.sh** script](../graph-views/map-web-install.md#étape-6--exécuter-le-script-configuresh) in order to apply some fixes provided by this release.
```suggestion
> You need to [execute the **configure.sh** script](../graph-views/map-web-install.md#step-6--execute-the-configuresh-script) in order to apply some fixes provided by this release.
```

2023-04-25 08:14 UTC, nmagniezCentreon submitted a review, later dismissed

2023-04-25 08:34 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
> +> You need to [execute the **configure.sh** script](../graph-views/map-web-install.md#step-6--execute-the-configuresh-script) in order to apply some fixes provided by this release.
```suggestion
> You need to [execute the **configure.sh** script](../graph-views/map-web-install.md#étape-6--exécuter-le-script-configuresh) in order to apply some fixes provided by this release.
```

2023-04-25 08:34 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
> +> You need to [execute the **configure.sh** script](../graph-views/map-web-install.md#étape-6--exécuter-le-script-configuresh) in order to apply some fixes provided by this release.
```suggestion
> You need to [execute the **configure.sh** script](../graph-views/map-web-install.md#step-6--execute-the-configuresh-script) in order to apply some fixes provided by this release.
```

2023-04-25 09:16 UTC, merged