add(epp): network-aruba-cppm-snmp
centreon/centreon-documentation pull request #2206
Opened 2023-03-31 09:48 UTC by garnier-quentin

## Description

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-03-31 12:04 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +| Memory        | Net-Aruba-Cppm-Memory-SNMP       | Check memories                             | X       |           |
```suggestion
| Memory        | Net-Aruba-Cppm-Memory-SNMP       | Check memory                            | X       |           |
```

2023-03-31 12:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +* LINK
missing link

2023-03-31 12:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +server. Please refer to the official documentation from XXX:
"from xxx"

2023-03-31 12:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +If you are using SNMP Version 3, use the **SNMPEXTRAOPTIONS** macro to configure
```suggestion
```

2023-04-12 10:18 UTC, cg-tw requested changes

2023-04-12 12:19 UTC, cg-tw approved these changes

2023-04-12 12:47 UTC, omercier approved these changes

2023-04-13 15:23 UTC, merged