add(epp): outscale
centreon/centreon-documentation pull request #2230
Opened 2023-04-14 09:29 UTC by garnier-quentin

## Description

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-05-10 20:49 UTC, smau-centreon requested changes

2023-05-10 20:49 UTC, smau-centreon commented on pp/integrations/plugin-packs/procedures/cloud-outscale.md
> +The Centreon Pack **Outscale** brings a host template:
```suggestion
The Centreon Monitoring Connector **Outscale** brings a host template:
```

2023-05-10 20:49 UTC, smau-centreon commented on pp/integrations/plugin-packs/procedures/cloud-outscale.md
> +**Configuration > Plugin Packs > Manager** menu.
```suggestion
**Configuration > Monitoring Connectors Manager** menu.
```

2023-05-10 20:49 UTC, smau-centreon commented on pp/integrations/plugin-packs/procedures/cloud-outscale.md
> +
EL9?

2023-05-10 20:49 UTC, smau-centreon commented on pp/integrations/plugin-packs/procedures/cloud-outscale.md
> +the **Configuration > Plugin Packs > Manager** menu.
```suggestion
the **Configuration > Monitoring Connectors Manager** menu.
```

2023-05-10 20:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +Le Pack Centreon **Outscale** apporte un modèle d'hôte :
```suggestion
Le connecteur de supervision Centreon **Outscale** apporte un modèle d'hôte :
```

2023-05-10 20:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +| Cloud-Outscale-Osccli-Virtual-Gateway-Name  | Découvre les paserrelles virtuelles et supervise le statut |
```suggestion
| Cloud-Outscale-Osccli-Virtual-Gateway-Name  | Découvre les passerelles virtuelles et supervise le statut |
```

2023-05-10 20:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +Veuillez suivre la procédure officielle en réalisation l'installation de ```osc-cli``` pour l'utilisateur ```centreon-engine``` :
```suggestion
Veuillez suivre la procédure officielle pour l'installation de ```osc-cli``` pour l'utilisateur ```centreon-engine``` :
```

2023-05-10 20:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +n'est pas requise pour voir apparaître le pack dans le menu **Configuration > Plugin Packs > Gestionnaire**.
```suggestion
n'est pas requise pour voir apparaître le pack dans le menu **Configuration > Gestionnaire de connecteurs de supervision**.
```

2023-05-10 20:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +
EL9 ?

2023-05-10 20:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +depuis l'interface web et le menu **Configuration > Plugin Packs > Gestionnaire**.
```suggestion
depuis l'interface web et le menu **Configuration > Gestionnaire de connecteurs de supervision**.
```

2023-05-11 11:49 UTC, omercier requested changes

2023-05-11 11:49 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +<TabItem value="CentOS 7" label="CentOS 7">
```suggestion
</TabItem>
<TabItem value="Alma / RHEL / Oracle Linux9" label="Alma / RHEL / Oracle Linux 9">

```bash
dnf install centreon-pack-cloud-outscale
```

</TabItem>
<TabItem value="CentOS 7" label="CentOS 7">
```

2023-05-11 11:49 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-outscale.md
> +<TabItem value="CentOS 7" label="CentOS 7">
```suggestion
</TabItem>
<TabItem value="Alma / RHEL / Oracle Linux 9" label="Alma / RHEL / Oracle Linux 9">

```bash
dnf install centreon-pack-cloud-outscale
```

</TabItem>
<TabItem value="CentOS 7" label="CentOS 7">
```

2023-05-11 11:50 UTC, omercier approved these changes

2023-05-11 14:46 UTC, smau-centreon commented
The topic is not positioned in the right place (in the TOC) 
![image](https://github.com/centreon/centreon-documentation/assets/102975713/20f5726e-3af9-49c0-830d-31fb7e1fed4f)

2023-05-11 14:49 UTC, smau-centreon requested changes

2023-05-11 14:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +```bash
L'onglet Centos 7 a disparu.

2023-05-11 14:49 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
> +
Onglet EL9 manquant.

2023-05-11 14:49 UTC, smau-centreon commented on pp/integrations/plugin-packs/procedures/cloud-outscale.md
> +```bash
Centos7 tab has been removed.

2023-05-11 14:49 UTC, smau-centreon commented on pp/integrations/plugin-packs/procedures/cloud-outscale.md
> +
EL9 tab still missing.

2023-05-12 09:34 UTC, smau-centreon approved these changes

2023-05-12 09:42 UTC, omercier approved these changes

2023-05-12 10:01 UTC, merged