add(epp): HMS Netbiter Argos RestAPI
centreon/centreon-documentation pull request #2261
Opened 2023-04-28 12:07 UTC by thibaults-centreon

## Description

Procedure for MC HMS Netbiter Argos RestAPI

## Target version

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] Cloud (staging)
- [X] Plugin Packs (staging)
- [ ] 23.04.x (next)

2023-05-10 16:20 UTC, smau-centreon requested changes

2023-05-10 16:20 UTC, smau-centreon commented on pp/integrations/plugin-packs/procedures/hardware-devices-hms-netbiter-argos-restapi.md
> +#### Global optionsAll global options are listed here:
```suggestion
#### Global options

All global options are listed here:
```

2023-05-10 16:20 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-hms-netbiter-argos-restapi.md
> +> Rendez-vous sur la [documentation dédiée](/docs/monitoring/discovery/hosts-discovery)
```suggestion
```

2023-05-10 16:20 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-hms-netbiter-argos-restapi.md
> +n'est pas requise pour voir apparaître le pack dans le menu **Configuration > Plugin Packs > Gestionnaire**.
```suggestion
n'est pas requise pour voir apparaître le pack dans le menu **Configuration > Gestionnaire de connecteurs de supervision**.
```

2023-05-11 11:37 UTC, omercier requested changes

2023-05-11 11:37 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-hms-netbiter-argos-restapi.md
> +> pour en savoir plus sur la découverte automatique d'hôtes.
```suggestion
> pour en savoir plus sur la découverte automatique d'hôtes.
```

2023-05-11 11:38 UTC, omercier approved these changes

2023-05-11 14:06 UTC, smau-centreon approved these changes

2023-05-12 11:28 UTC, merged