MON-18086-bug-on-azure-policies
centreon/centreon-documentation pull request #2280
Opened 2023-05-03 16:16 UTC by sdepassio

## Description

Update after adding policy-name option

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Plugin Packs (staging)
- [ ] 23.10.x (next)

2023-05-10 12:29 UTC, omercier requested changes

2023-05-10 12:29 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +*
```suggestion
* Cloud-Azure-PolicyInsights-PolicyStates
```

2023-05-10 12:29 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +Le connecteur apporte le modèle de service suivant (classés par modèle d'hôte):
```suggestion
Le connecteur apporte le modèle de service suivant :
```

2023-05-10 12:29 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +Le connecteur apporte le modèle de service suivant (classés par modèle d'hôte):
```suggestion
Le connecteur apporte le modèle de service suivant :
```

2023-05-10 12:29 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +<TabItem value="Cloud-Azure-PolicyInsights-PolicyStates" label="Cloud-Azure-PolicyInsights-PolicyStates">
```suggestion
```

2023-05-10 12:29 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +</Tabs>
```suggestion
```

2023-05-10 12:29 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +The connector brings the following service template (sorted by host template):
```suggestion
The connector brings the following service template:
```

2023-05-10 12:29 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +<TabItem value="Cloud-Azure-PolicyInsights-PolicyStates" label="Cloud-Azure-PolicyInsights-PolicyStates">
```suggestion
```

2023-05-10 12:29 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +</Tabs>
```suggestion
```

2023-05-10 12:29 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
> +*
```suggestion
* Cloud-Azure-PolicyInsights-PolicyStates
```

2023-05-10 14:30 UTC, omercier approved these changes

2023-05-11 11:27 UTC, omercier approved these changes

2023-05-11 15:02 UTC, smau-centreon approved these changes

2023-05-12 11:28 UTC, merged