MON-18734-add-standard-tcp-host-check-command-and-host-template-in-ap…
centreon/centreon-documentation pull request #2288
Opened 2023-05-05 13:15 UTC by YanMeddour

…plications-protocol-tcp

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Plugin Packs (staging)
- [ ] 23.10.x (next)

2023-05-10 14:51 UTC, omercier requested changes

2023-05-11 09:57 UTC, omercier requested changes

2023-05-11 09:57 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +OK:     | 'tcp.roundtrip.time.average.milliseconds'=52ms;;;0; 'tcp.roundtrip.time.maximum.milliseconds'=10ms;;;0; 'tcp.roundtrip.time.minimum.milliseconds'=80ms;;;0; 'tcp.packets.loss.percentage'=86%
```suggestion
OK: TCP '10.0.0.1' port 80 rta 0.633ms, lost 0% | 'tcp.roundtrip.time.average.milliseconds'=0.633ms;;;0; 'tcp.roundtrip.time.maximum.milliseconds'=2.145ms;;;0; 'tcp.roundtrip.time.minimum.milliseconds'=0.193ms;;;0; 'tcp.packets.loss.percentage'=0%;;;0;100
```

2023-05-11 09:57 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +	--port='' \
```suggestion
	--port='80' \
```

2023-05-11 09:57 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +	--port='' \
```suggestion
	--port='80' \
```

2023-05-11 09:57 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +	--port='' \
```suggestion
	--port='80' \
```

2023-05-11 09:57 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +OK:     | 'tcp.roundtrip.time.average.milliseconds'=52ms;;;0; 'tcp.roundtrip.time.maximum.milliseconds'=10ms;;;0; 'tcp.roundtrip.time.minimum.milliseconds'=80ms;;;0; 'tcp.packets.loss.percentage'=86%
```suggestion
OK: TCP '10.0.0.1' port 80 rta 0.633ms, lost 0% | 'tcp.roundtrip.time.average.milliseconds'=0.633ms;;;0; 'tcp.roundtrip.time.maximum.milliseconds'=2.145ms;;;0; 'tcp.roundtrip.time.minimum.milliseconds'=0.193ms;;;0; 'tcp.packets.loss.percentage'=0%;;;0;100
```

2023-05-11 10:19 UTC, omercier approved these changes

2023-05-11 12:21 UTC, smau-centreon approved these changes

2023-05-12 11:28 UTC, merged