chore(release): prepare release notes for OSS 22.10
centreon/centreon-documentation pull request #2350
Opened 2023-06-01 16:06 UTC by tuntoja

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-02 13:35 UTC, smau-centreon requested changes

2023-06-02 13:35 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Server] Fixed user running cron tasks on debian.
```suggestion
- [Server] Fixed a monitoring issue by updating the user running cron tasks on Debian.
```

2023-06-02 14:49 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Authentication] Made error messages generic to improve security.
Left as it is, since it comes from security audit and was not the original expected behavior.

2023-06-02 14:50 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [UI] Unifomized buttons size on legacy pages.
left as bug since buttons were originaly expected to have the same size.

2023-06-02 15:26 UTC, rsadik-ext submitted a review, later dismissed

2023-06-02 15:34 UTC, lpinsivy approved these changes

2023-06-05 07:27 UTC, lpinsivy submitted a review, later dismissed

2023-06-05 08:01 UTC, smau-centreon requested changes

2023-06-05 08:01 UTC, smau-centreon commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Packaging] Fixed dsmd configuration files on debian.
```suggestion
- [Packaging] Fixed dsmd configuration files on Debian.
```

2023-06-05 08:01 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Packaging] Fixed dsmd configuration files on debian.
```suggestion
- [Packaging] Fixed dsmd configuration files on Debian.
```

2023-06-05 08:10 UTC, rsadik-ext submitted a review, later dismissed

2023-06-05 08:34 UTC, smau-centreon approved these changes

2023-06-05 08:47 UTC, lpinsivy approved these changes

2023-06-05 09:22 UTC, merged