Mon 15847 new plugin pack aws cloud trail
centreon/centreon-documentation pull request #2355
Opened 2023-06-05 15:10 UTC by sdepassio

## Description

Adding documentation for the new AWS CloudTrail monitoring connector

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-05 16:05 UTC, cg-tw requested changes

2023-06-05 16:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudtrail.md
> +To interact with Amazon APIs, you can use either use the *awscli* binary provided by Amazon or *paws*, a Perl AWS SDK (recommended). You must install it on every poller expected to monitor AWS resour
```suggestion
To interact with the Amazon APIs, you can use either use the *awscli* binary provided by Amazon or *paws*, a Perl AWS SDK (recommended). You must install it on every poller expected to monitor AWS resources.
```

2023-06-05 16:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudtrail.md
> +> For now, it is not possible to use *paws* if you are using a proxy to reach AWS Cloudwatch APIs.
```suggestion
> For now, it is not possible to use *paws* if you are using a proxy to reach the AWS Cloudwatch APIs.
```

2023-06-05 16:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudtrail.md
> +| AWSASSUMEROLE | Set arn of the role to be assumed                                                                     |                   |             |
```suggestion
| AWSASSUMEROLE | Set ARN of the role to be assumed                                                                     |                   |             |
```

2023-06-05 16:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudtrail.md
> +5. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The host appears in the list of hosts, and on page **Resources Status**. The command that is sent by the
```suggestion
5. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The host appears in the list of hosts, and on the **Resources Status** page. The command that is sent by the connector is displayed in the details panel of the host: it shows the values of the macros.
```

2023-06-05 16:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudtrail.md
> +3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of service, and on page **Resources Status**. The command that is sent by
```suggestion
3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of services, and on the **Resources Status** page. The command that is sent by the connector is displayed in the details panel of the service: it shows the values of the macros.
```

2023-06-05 16:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudtrail.md
> +/usr/lib/centreon/plugins//centreon_aws_cloudtrail_api.pl \
no default values

2023-06-05 16:05 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudtrail.md
> +All  modes specific options are listed here:
```suggestion
All modes specific options are listed here:
```

2023-06-06 16:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudtrail.md
> +| --aws-role-arn      | Set arn of the role to be assumed.                                                                | Paws |
```suggestion
| --aws-role-arn      | Set ARN of the role to be assumed.                                                                | Paws |
```

2023-06-07 11:47 UTC, cg-tw submitted a review, later dismissed

2023-06-07 21:52 UTC, omercier approved these changes

2023-06-08 12:25 UTC, cg-tw approved these changes

2023-06-08 12:25 UTC, omercier approved these changes

2023-06-08 13:13 UTC, merged