Mon 19497 prepare rn oss 2304
centreon/centreon-documentation pull request #2358
Opened 2023-06-06 07:29 UTC by tuntoja

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [x] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-06 15:22 UTC, mdebauchez requested changes

2023-06-06 15:22 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
> +- [RessourcesStatus] Fixed h.name filter not returning hosts.
It's [ResourcesStatus] and not [RessourcesStatus]

2023-06-06 15:22 UTC, mdebauchez commented on versioned_docs/version-23.04/releases/centreon-os.md
> +- [RessourcesStatus] Fixed h.name filter not returning hosts.
It's [ResourcesStatus] and not [RessourcesStatus]

2023-06-06 15:22 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
> +- [UI] Unifomized buttons size on legacy pages.
Uniformized and not Unifomized

2023-06-06 15:22 UTC, mdebauchez commented on versioned_docs/version-23.04/releases/centreon-os.md
> +- [UI] Unifomized buttons size on legacy pages.
Uniformized and not Unifomized

2023-06-06 15:22 UTC, mdebauchez commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
> +- [Authentication] fixed HTTP method for custom endpoints for OpenId.
The first letter is not capitalized

2023-06-06 15:22 UTC, mdebauchez commented on versioned_docs/version-23.04/releases/centreon-os.md
> +- [Authentication] fixed HTTP method for custom endpoints for OpenId.
The first letter is not capitalized

2023-06-07 08:14 UTC, mdebauchez submitted a review, later dismissed

2023-06-07 11:34 UTC, rsadik-ext submitted a review, later dismissed

2023-06-07 13:08 UTC, smau-centreon requested changes

2023-06-07 13:08 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
> +#### Enhancements
```suggestion
#### Enhancement
```

2023-06-07 13:08 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
> +#### Bug fixes
```suggestion
#### Bug fix
```

2023-06-07 13:08 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
> +#### Enhancements
```suggestion
#### Enhancement
```

2023-06-07 13:08 UTC, smau-centreon commented on versioned_docs/version-23.04/releases/centreon-os.md
> +#### Enhancements
```suggestion
#### Enhancement
```

2023-06-07 13:08 UTC, smau-centreon commented on versioned_docs/version-23.04/releases/centreon-os.md
> +#### Bug fixes
```suggestion
#### Bug fix
```

2023-06-07 13:43 UTC, smau-centreon approved these changes

2023-06-07 13:43 UTC, jdelpierre approved these changes

2023-06-07 14:23 UTC, merged