enh(pack): refreshed the pack's page
centreon/centreon-documentation pull request #2365
Opened 2023-06-07 20:50 UTC by omercier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-29 15:13 UTC, cg-tw requested changes

2023-06-29 15:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +| ANSIBLETOWERCUSTOMMODE   | When a plugin offers several ways  to get the an information the desired one must be defined with this option | api               |             |
mandatory macros?

2023-06-29 15:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +| ANSIBLETOWERCUSTOMMODE   | When a plugin offers several ways  to get the an information the desired one must be defined with this option | api               |             |
```suggestion
| ANSIBLETOWERCUSTOMMODE   | When a plugin offers several ways to get information the desired one must be defined with this option | api               |             |
```

2023-06-30 16:06 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +Coming soon
Oh damn! I'll try and fix it!

2023-06-30 16:07 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +|:-------------------------|:--------------------------------------------------------------------------------------------------------------|:------------------|:------------|
I'll try and fix it!

2023-06-30 16:12 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +| FILTERNAME         | Filter job template name (Can use regexp)                                                                                                              |
It will be fixed when I'll regenerate it.

2023-06-30 16:50 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +| --hostname       | Santricity hostname.                                                                                                               | Api          |
```suggestion
| --hostname       | Host address.                                                                                                               | Api          |
```

2023-07-03 08:56 UTC, omercier commented
@cg-tw it should be better now!

2023-07-03 12:47 UTC, omercier commented
@cg-tw new update available

2023-07-04 15:19 UTC, cg-tw approved these changes

2023-07-06 11:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +| --hostname       | Santricity hostname.                                                                                                               |
```suggestion
| --hostname       | Ansible Tower hostname.                                                                                                               |
```

2023-07-06 11:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +| --hostname       | Santricity hostname.                                                                                                               |
```suggestion
| --hostname       | Ansible Tower hostname.                                                                                                               |
```

2023-07-06 11:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-ansible-tower.md
> +| --hostname       | Santricity hostname.                                                                                                               |
```suggestion
| --hostname       | Ansible Tower hostname.                                                                                                               |
```

2023-07-06 11:46 UTC, cg-tw approved these changes

2023-07-06 12:15 UTC, merged