add(epp): applications-veeam-vbem-restapi
centreon/centreon-documentation pull request #2371
Opened 2023-06-09 12:07 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-16 06:49 UTC, omercier approved these changes

2023-06-16 08:03 UTC, cg-tw requested changes

2023-06-16 08:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +| WARNINGEXECUTIONSTATUS          | Set warning threshold for last job execution status (Default: %{status} =~ /warning/i). Can used special variables like: %{status}, %{jobName}            | %{statu
```suggestion
| WARNINGEXECUTIONSTATUS          | Set warning threshold for last job execution status (Default: %{status} =~ /warning/i). Can use special variables like: %{status}, %{jobName}            | %{status} =~ /warning/i |             |
```

2023-06-16 08:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +| CRITICALEXECUTIONSTATUS         | Set critical threshold for last job execution status (Default: %{status} =~ /failed/i). Can used special variables like: %{status}, %{jobName}            | %{statu
```suggestion
| CRITICALEXECUTIONSTATUS         | Set critical threshold for last job execution status (Default: %{status} =~ /failed/i). Can use special variables like: %{status}, %{jobName}            | %{status} =~ /failed/i  |             |
```

2023-06-16 08:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +| VBEMAPIUSERNAME     | Set username                                                                                          |                   |             |
not mandatory?

2023-06-29 15:22 UTC, cg-tw requested changes

2023-06-29 15:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +* **App-Veeam-Vbem-Restapi**
```suggestion
* **App-Veeam-Vbem-Restapi-custom**
```

2023-06-29 15:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +<TabItem value="App-Veeam-Vbem-Restapi" label="App-Veeam-Vbem-Restapi">
```suggestion
<TabItem value="App-Veeam-Vbem-Restapi-custom" label="App-Veeam-Vbem-Restapi-custom">
```

2023-06-29 15:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **App-Veeam-Vbem-Restapi** est utilisé.
```suggestion
> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **App-Veeam-Vbem-Restapi-custom** est utilisé.
```

2023-06-29 15:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +| VBEMAPIPROTOCOL     | Specify https if needed                                                                               | https             |             |
```suggestion
| VBEMAPIPROTOCOL     | Specify HTTPS if needed                                                                               | https             |             |
```

2023-06-29 15:22 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +* **App-Veeam-Vbem-Restapi**
```suggestion
* **App-Veeam-Vbem-Restapi-custom**
```

2023-06-29 15:22 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +<TabItem value="App-Veeam-Vbem-Restapi" label="App-Veeam-Vbem-Restapi">
```suggestion
<TabItem value="App-Veeam-Vbem-Restapi-custom" label="App-Veeam-Vbem-Restapi-custom">
```

2023-06-29 15:22 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
> +> The services listed above are created automatically when the **App-Veeam-Vbem-Restapi** host template is used.
```suggestion
> The services listed above are created automatically when the **App-Veeam-Vbem-Restapi-custom** host template is used.
```

2023-06-30 14:36 UTC, omercier approved these changes

2023-07-04 15:22 UTC, cg-tw requested changes

2023-07-04 15:47 UTC, omercier approved these changes

2023-07-04 15:47 UTC, cg-tw approved these changes

2023-07-06 11:38 UTC, merged