enh(epp): applications-rubrik-restapi - update proc
centreon/centreon-documentation pull request #2378
Opened 2023-06-14 08:51 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-29 15:31 UTC, cg-tw requested changes

2023-06-29 15:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +* **App-Rubrik-Restapi**
```suggestion
* **App-Rubrik-Restapi-custom**
```

2023-06-29 15:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +<TabItem value="App-Rubrik-Restapi" label="App-Rubrik-Restapi">
```suggestion
<TabItem value="App-Rubrik-Restapi-custom" label="App-Rubrik-Restapi-custom">
```

2023-06-29 15:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **App-Rubrik-Restapi** est utilisé.
```suggestion
> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **App-Rubrik-Restapi-custom** est utilisé.
```

2023-06-29 15:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +|:----------------------|:------------------------------------------------------------------------------------------------------|:------------------|:------------|
are there any mandatory ones?

2023-06-29 15:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +| RUBRIKAPIEXTRAOPTIONS | Any extra option you may want to add to every command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| RUBRIKAPIEXTRAOPTIONS | Any extra option you may want to add to every command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-06-29 15:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +que le connecteur arrive bien à superviser un serveur en utilisant une commande
```suggestion
que le connecteur arrive bien à superviser la ressource en utilisant une commande
```

2023-07-05 14:15 UTC, cg-tw approved these changes

2023-07-05 14:15 UTC, omercier approved these changes

2023-07-06 11:34 UTC, merged