doc(release): prepare release notes for modules 2204
centreon/centreon-documentation pull request #2380
Opened 2023-06-14 13:00 UTC by tuntoja

## Description

Release notes for
* Centreon MAP 22.04.7
* Centreon MBI 22.04.4

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-15 14:37 UTC, nmagniezCentreon requested changes

2023-06-15 14:37 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +
il semble manquer:
[Viewer] You can now define a label for a URL shape. 
MON-19565

2023-06-15 14:58 UTC, nmagniezCentreon approved these changes

2023-06-19 12:38 UTC, nmagniezCentreon approved these changes

2023-06-19 13:41 UTC, jdelpierre approved these changes

2023-06-19 14:18 UTC, merged