enh(epp): applications-ipfabric-api
centreon/centreon-documentation pull request #2389
Opened 2023-06-16 12:41 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-29 15:38 UTC, cg-tw requested changes

2023-06-29 15:38 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +* **App-Ipfabric-Api**
```suggestion
* **App-Ipfabric-Api-custom**
```

2023-06-29 15:38 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +<TabItem value="App-Ipfabric-Api" label="App-Ipfabric-Api">
```suggestion
<TabItem value="App-Ipfabric-Api-custom" label="App-Ipfabric-Api-custom">
```

2023-06-29 15:38 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +> The services listed above are created automatically when the **App-Ipfabric-Api** host template is used.
```suggestion
> The services listed above are created automatically when the **App-Ipfabric-Api-custom** host template is used.
```

2023-06-29 15:38 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-ipfabric-api.md
>  Ensure you have a IP Fabric API Key with required privileges and IP Fabric's API address.
```suggestion
Ensure you have an IP Fabric API Key with required privileges and IP Fabric's API address.
```

2023-06-30 12:44 UTC, omercier approved these changes

2023-06-30 12:46 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +* **App-Ipfabric-Api**
Please accept the commit suggestions @garnier-quentin (Ivan's script will soon be updated with this enhancement).

2023-07-06 12:56 UTC, omercier approved these changes

2023-07-06 12:56 UTC, cg-tw approved these changes

2023-07-06 13:26 UTC, merged