MON-18599 - Documentation - Add Azure Sqldatabase cpu and memory mode
centreon/centreon-documentation pull request #2391
Opened 2023-06-16 12:53 UTC by lucie-dubrunfaut

## Description

Updating Azure Sqldatabase documentation

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-16 13:16 UTC, lucie-dubrunfaut commented
WARNING: macro '--server' is not defined in host template(s)
WARNING: macro '--subscription' is not defined in host template(s)
WARNING: macro '--tenant' is not defined in host template(s)
WARNING: macro '--client-id' is not defined in host template(s)
WARNING: macro '--client-secret' is not defined in host template(s)
CRITICAL: option '' in Monitoring Connector commands not available for this plugin

By using doc generator script.

2023-06-20 17:00 UTC, omercier requested changes

2023-06-29 15:52 UTC, cg-tw requested changes

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| EXTRAOPTIONS      | Any extra option you may want to add to the command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS      | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| EXTRAOPTIONS      | Any extra option you may want to add to the command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS      | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| EXTRAOPTIONS   | Any extra option you may want to add to the command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles)                                      |
```suggestion
| EXTRAOPTIONS   | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)                                      |                              |             |
```

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles) |                              |
```suggestion
| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                              |             |
```

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| EXTRAOPTIONS     | Any extra option you may want to add to the command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS     | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| EXTRAOPTIONS    | Any extra option you may want to add to the command (E.g. a --verbose flag). Tous les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS    | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-06-29 15:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +Les options spécifiques aux modes sont listées ci-dessus :
```suggestion
Les options spécifiques aux modes sont listées ci-dessous :
```

2023-06-29 15:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +* **Cloud-Azure-Database-SqlDatabase**
```suggestion
* **Cloud-Azure-Database-SqlDatabase-custom**
```

2023-06-29 15:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +<TabItem value="Cloud-Azure-Database-SqlDatabase" label="Cloud-Azure-Database-SqlDatabase">
```suggestion
<TabItem value="Cloud-Azure-Database-SqlDatabase-custom" label="Cloud-Azure-Database-SqlDatabase-custom">
```

2023-06-29 15:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +> The services listed above are created automatically when the **Cloud-Azure-Database-SqlDatabase** host template is used.
```suggestion
> The services listed above are created automatically when the **Cloud-Azure-Database-SqlDatabase-custom** host template is used.
```

2023-06-29 15:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +> The services listed above are not created automatically when a host template is applied. To use them, [create a service manually](/docs/monitoring/basic-objects/services), then appy the service tem
```suggestion
> The services listed above are not created automatically when a host template is applied. To use them, [create a service manually](/docs/monitoring/basic-objects/services), then apply the service template you want.
```

2023-06-29 15:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +4. Fill in the macros you want. Some macros are mandatory. For example, for this connector, you must define the **AZURECUSTOMMODE** macros (possible values are **api** or **azcli**). Indeed, 2 modes
```suggestion
4. Fill in the macros you want. Some macros are mandatory. For example, for this connector, you must define the **AZURECUSTOMMODE** macros (possible values are **api** or **azcli**). Indeed, 2 modes of communication can be used with this resource: either using the command tool azcli, or by querying the API directly.
```

2023-06-29 15:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| AZURECUSTOMMODE    | When a plugin offers several ways  to get the an information the desired one must be defined with this option | api               |             |
```suggestion
| AZURECUSTOMMODE    | When a plugin offers several ways to get information the desired one must be defined with this option | api               |             |
```

2023-06-29 15:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| AZURERESOURCE      | Set resource name or id . It is the database name                                                             |                   |             |
```suggestion
| AZURERESOURCE      | Set resource name or ID. It is the database name                                                             |                   |             |
```

2023-07-03 13:43 UTC, cg-tw requested changes

2023-07-03 13:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| Connections   | Cloud-Azure-Database-SqlDatabase-Connections-custom   | Contrôle le nombre de connexion par statut      |
```suggestion
| Connections   | Cloud-Azure-Database-SqlDatabase-Connections-custom   | Contrôle le nombre de connexions par statut      |
```

2023-07-03 13:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| AZURECUSTOMMODE    | When a plugin offers several ways  to get the an information the desired one must be defined with this option | api               |             |
```suggestion
| AZURECUSTOMMODE    | When a plugin offers several ways to get information, the desired one must be defined with this option | api               |             |
```

2023-07-03 13:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| AZURERESOURCE      | Set resource name or id . It is the database name                                                             |                   |             |
```suggestion
| AZURERESOURCE      | Set resource name or ID . It is the database name                                                             |                   |             |
```

2023-07-03 13:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +| AZURECUSTOMMODE    | When a plugin offers several ways  to get the an information the desired one must be defined with this option | api               |             |
```suggestion
| AZURECUSTOMMODE    | When a plugin offers several ways to get information, the desired one must be defined with this option | api               |             |
```

2023-07-06 09:33 UTC, cg-tw requested changes

2023-07-06 09:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--tenant='' \
```suggestion
	--tenant='xxxxxxxxx' \
```

2023-07-06 09:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--client-id='' \
```suggestion
	--client-id='xxxxxxxxx' \
```

2023-07-06 09:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--client-secret='' \
```suggestion
	--client-secret='xxxxxxxxx' \
```

2023-07-06 09:36 UTC, cg-tw requested changes

2023-07-06 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--subscription='' \
```suggestion
	--subscription='xxxxxxxxx' \
```

2023-07-06 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--tenant='' \
```suggestion
	--tenant='xxxxxxxxx' \
```

2023-07-06 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--client-id='' \
```suggestion
	--client-id='xxxxxxxxx' \
```

2023-07-06 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--client-secret='' \
```suggestion
	--client-secret='xxxxxxxxx' \
```

2023-07-06 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--resource='' \
```suggestion
	--resource='SQLDB001A' \
```

2023-07-06 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--resource-group='' \
```suggestion
	--resource-group='RSG1234' \
```

2023-07-06 09:39 UTC, omercier approved these changes

2023-07-06 09:39 UTC, cg-tw approved these changes

2023-07-06 13:31 UTC, merged