Remove obsolete CLAPI params
centreon/centreon-documentation pull request #2399
Opened 2023-06-19 15:43 UTC by cg-tw

## Description

Remove obsolete CLAPI params

## Target version (i.e. version that this PR changes)

- [x] 21.10.x (staging)
- [x] 22.04.x (staging)
- [x] 22.10.x (staging)
- [x] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-19 16:42 UTC, a-launois requested changes

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md
>  1;/var/log/centreon-broker/central-module.log
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a listoutput -v "broker cfg for poller test"
id;name
1;Storage
2;RRD
3;PerfData
4:MyFileOutput
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;/var/log/centreon-broker/central-module.log;file"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a addoutput -v "broker cfg for poller test;MyFileOutput;file"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a deloutput -v "broker cfg for poller test;4"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1;debug;no"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a setoutput -v "broker cfg for poller test;1;retry_interval;5'"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;/var/log/centreon-broker/central-module.log;file"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a addoutput -v "broker cfg for poller test;MyFileOutput;file"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;/var/log/centreon-broker/central-module.log;file"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a addoutput -v "broker cfg for poller test;MyFileOutput;file"
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-22.04/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;/var/log/centreon-broker/central-module.log;file"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a addoutput -v "broker cfg for poller test;MyFileOutput;file"
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-23.04/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;/var/log/centreon-broker/central-module.log;file"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a addoutput -v "broker cfg for poller test;MyFileOutput;file"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md
>  1;/var/log/centreon-broker/central-module.log
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a listoutput -v "broker cfg for poller test"
id;name
1;Storage
2;RRD
3;PerfData
4:MyFileOutput
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/clapi.md
>  1;/var/log/centreon-broker/central-module.log
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a listoutput -v "broker cfg for poller test"
id;name
1;Storage
2;RRD
3;PerfData
4:MyFileOutput
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/clapi.md
>  1;/var/log/centreon-broker/central-module.log
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a listoutput -v "broker cfg for poller test"
id;name
1;Storage
2;RRD
3;PerfData
4:MyFileOutput
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-21.10/api/clapi.md
>  1;/var/log/centreon-broker/central-module.log
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a listoutput -v "broker cfg for poller test"
id;name
1;Storage
2;RRD
3;PerfData
4:MyFileOutput
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-22.04/api/clapi.md
>  1;/var/log/centreon-broker/central-module.log
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a listoutput -v "broker cfg for poller test"
id;name
1;Storage
2;RRD
3;PerfData
4:MyFileOutput
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-22.10/api/clapi.md
>  1;/var/log/centreon-broker/central-module.log
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a listoutput -v "broker cfg for poller test"
id;name
1;Storage
2;RRD
3;PerfData
4:MyFileOutput
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-23.04/api/clapi.md
>  1;/var/log/centreon-broker/central-module.log
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a listoutput -v "broker cfg for poller test"
id;name
1;Storage
2;RRD
3;PerfData
4:MyFileOutput
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a deloutput -v "broker cfg for poller test;4"
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-22.04/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a deloutput -v "broker cfg for poller test;4"
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-22.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a deloutput -v "broker cfg for poller test;4"
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-23.04/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a deloutput -v "broker cfg for poller test;4"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1;debug;no"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a setoutput -v "broker cfg for poller test;1;retry_interval;5'"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1;debug;no"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a setoutput -v "broker cfg for poller test;1;retry_interval;5'"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1;debug;no"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a setoutput -v "broker cfg for poller test;1;retry_interval;5'"
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-21.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1;debug;no"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a setoutput -v "broker cfg for poller test;1;retry_interval;5'"
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-22.04/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1;debug;no"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a setoutput -v "broker cfg for poller test;1;retry_interval;5'"
```

2023-06-19 16:42 UTC, a-launois commented on versioned_docs/version-22.10/api/clapi.md
> +centreon -u admin -p 'centreon' -o CENTBROKERCFG -v "broker cfg for poller test;1;debug;no"
```suggestion
centreon -u admin -p 'centreon' -o CENTBROKERCFG -a setoutput -v "broker cfg for poller test;1;retry_interval;5'"
```

2023-06-19 16:42 UTC, a-launois commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/clapi.md
Missing example update:
`centreon -u admin -p 'centreon' -o CENTBROKERCFG -a deloutput -v "broker cfg for poller test;4"`

2023-06-19 17:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md
> +#### Addinputa and Addoutput
```suggestion
#### Addinput and Addoutput
```

2023-06-26 09:45 UTC, a-launois approved these changes

2023-06-26 10:26 UTC, merged