add(epp): hardware-sensors-rittal-cmc3-snmp
centreon/centreon-documentation pull request #2423
Opened 2023-06-29 09:07 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-30 11:46 UTC, cg-tw submitted a review, later dismissed

2023-06-30 11:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +* **HW-Sensor-Rittal-Cmc3-SNMP**
```suggestion
* **HW-Sensor-Rittal-Cmc3-SNMP-custom**
```

2023-06-30 11:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +<TabItem value="HW-Sensor-Rittal-Cmc3-SNMP" label="HW-Sensor-Rittal-Cmc3-SNMP">
```suggestion
<TabItem value="HW-Sensor-Rittal-Cmc3-SNMP-custom" label="HW-Sensor-Rittal-Cmc3-SNMP-custom">
```

2023-06-30 11:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **HW-Sensor-Rittal-Cmc3-SNMP** est utilisé.
```suggestion
> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **HW-Sensor-Rittal-Cmc3-SNMP-custom** est utilisé.
```

2023-06-30 11:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +| WARNINGUNITLOAD10M  |                                                                                                     |                   |             |
missing descriptions

2023-06-30 11:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +Afin de superviser votre équipement, le SNMP v2 ou v3 doit être configuré.
```suggestion
Afin de superviser votre ressource en SNMP,  il est nécessaire de configurer l'agent SNMP v2 ou v3
sur la ressource comme indiqué sur la documentation officielle du constructeur.
```

2023-06-30 11:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +Les options spécifiques aux modes sont listées ci-dessus :
```suggestion
Les options spécifiques aux modes sont listées ci-dessous :
```

2023-06-30 11:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +* **HW-Sensor-Rittal-Cmc3-SNMP**
```suggestion
* **HW-Sensor-Rittal-Cmc3-SNMP-custom**
```

2023-06-30 11:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +> The services listed above are created automatically when the **HW-Sensor-Rittal-Cmc3-SNMP** host template is used.
```suggestion
> The services listed above are created automatically when the **HW-Sensor-Rittal-Cmc3-SNMP-custom** host template is used.
```

2023-06-30 11:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +> The services listed above are not created automatically when a host template is applied. To use them, [create a service manually](/docs/monitoring/basic-objects/services), then appy the service tem
```suggestion
> The services listed above are not created automatically when a host template is applied. To use them, [create a service manually](/docs/monitoring/basic-objects/services), then apply the service template you want.
```

2023-06-30 11:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +To use this Pack, the SNMP service must be properly configured on your device.
```suggestion
To use this connector, the SNMP service must be properly configured on your device.
```

2023-06-30 11:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of service, and on page **Resources Status**. The command that is sent by
```suggestion
3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of services, and on the **Resources Status** page. The command that is sent by the connector is displayed in the details panel of the service: it shows the values of the macros.
```

2023-08-04 15:27 UTC, omercier requested changes

2023-08-04 15:27 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +dnf install centreon-plugin-Hardware-Sensors-Rittal-Cmc3-Snmp
```suggestion
dnf install centreon-plugin-Hardware-Sensors-Rittal-Cmc-Snmp
```

2023-08-09 14:04 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +| CRITICALSTATUS | Define the conditions to match for the status to be CRITICAL (default: '%{status} =~ /notAvail\|lost\|error/i'). You can use the following variables: %{status}                 | %{
```suggestion
| WARNINGSTATUS  | Define the conditions to match for the status to be WARNING (default: '%{status} =~ /detect\|changed\|fwUpdate\|fwUpdateRun/i'). You can use the following variables: %{status} | %{status} =~ /detect\|changed\|fwUpdate\|fwUpdateRun/i |             |
| CRITICALSTATUS | Define the conditions to match for the status to be CRITICAL (default: '%{status} =~ /notAvail\|lost\|error/i'). You can use the following variables: %{status}                 | %{status} =~ /notAvail\|lost\|error/i                 |             |
```

2023-08-09 14:04 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-sensors-rittal-cmc3-snmp.md
> +| CRITICALSTATUS | Define the conditions to match for the status to be CRITICAL (default: '%{unit\_status} =~ /failed/i \|\| %{overall\_device\_status} =~ /alarm/i'). You can use the following variab
```suggestion
| UNKNOWNSTATUS  | Define the conditions to match for the status to be UNKNOWN (default: '%{overall\_device\_status} =~ /detected\|lost\|changed\|update/i'). You can use the following variables: %{unit\_status}, %{overall\_device\_status}, %{mode}, %{available\_devices}             | %{overall\_device\_status} =~ /detected\|lost\|changed\|update/i             |             |
| WARNINGSTATUS  | Define the conditions to match for the status to be WARNING (default: '%{unit\_status} =~ /overload/i \|\| %{overall\_device\_status} =~ /warning/i'). You can use the following variables: %{unit\_status}, %{overall\_device\_status}, %{mode}, %{available\_devices} | %{unit\_status} =~ /overload/i \|\| %{overall\_device\_status} =~ /warning/i |             |
| CRITICALSTATUS | Define the conditions to match for the status to be CRITICAL (default: '%{unit\_status} =~ /failed/i \|\| %{overall\_device\_status} =~ /alarm/i'). You can use the following variables: %{unit\_status}, %{overall\_device\_status}, %{mode}, %{available\_devices}    | %{unit\_status} =~ /failed/i \|\| %{overall\_device\_status} =~ /alarm/i     |             |
```

2023-08-09 14:07 UTC, omercier approved these changes

2023-08-11 09:28 UTC, omercier approved these changes

2023-08-11 09:30 UTC, merged