add(epp): applications-tosca-restapi
centreon/centreon-documentation pull request #2428
Opened 2023-06-30 12:49 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-30 14:40 UTC, cg-tw requested changes

2023-06-30 14:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-tosca-restapi.md
> +To monitor, a user with read privileges on the Tosca Commander REST Webservice [API](https://documentation.tricentis.com/devcorner/1000/tcrsapi/) is required.
```suggestion
To monitor this type of resource, a user with read privileges on the Tosca Commander REST Webservice [API](https://documentation.tricentis.com/devcorner/1000/tcrsapi/) is required.
```

2023-08-03 14:25 UTC, cg-tw submitted a review, later dismissed

2023-08-09 21:37 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-tosca-restapi.md
> +> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **App-Tosca-Restapi-custom** est utilisé.
```suggestion
Par défaut, aucun service n'est créé automatiquement en appliquant ce modèle.
```

2023-08-09 21:37 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-tosca-restapi.md
> +> The services listed above are created automatically when the **App-Tosca-Restapi-custom** host template is used.
```suggestion
By default, no services are created automatically using this template.
```

2023-08-09 21:38 UTC, omercier approved these changes

2023-08-11 08:39 UTC, merged