doc(release): prepare release notes for collect 2210
centreon/centreon-documentation pull request #2431
Opened 2023-06-30 15:05 UTC by tuntoja

## Description

Release notes for:
* COLLECT 22.10.3

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-06-30 15:10 UTC, omercier requested changes

2023-06-30 15:10 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- With AND/OR boolean operators, we do not have always to wait for nodes to be known. An OR is always true if one of its children is true and An AND is always false if one of its children is false. T
```suggestion
- Improved the evaluation process of BAM KPIs based on boolean expressions: if an OK result is part of an OR operation, or a CRITICAL result is part of an AND operation, Broker will return the results without waiting for the other members of the operation.
```

2023-06-30 15:10 UTC, omercier commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- With AND/OR boolean operators, we do not have always to wait for nodes to be known. An OR is always true if one of its children is true and An AND is always false if one of its children is false. T
```suggestion
- Improved the evaluation process of BAM KPIs based on boolean expressions: if an OK result is part of an OR operation, or a CRITICAL result is part of an AND operation, Broker will return the results without waiting for the other members of the operation.
```

2023-07-03 07:57 UTC, omercier submitted a review, later dismissed

2023-07-03 08:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed an exception-catching issue that caused broker to fail inserting resources when the check_attempt was too high for the database column type.
```suggestion
- Fixed an exception-catching issue that caused Broker to fail inserting resources when the check_attempt was too high for the database column type.
```

2023-07-03 08:04 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Fixed an exception-catching issue that caused broker to fail inserting resources when the check_attempt was too high for the database column type.
```suggestion
- Fixed an exception-catching issue that caused Broker to fail inserting resources when the check_attempt was too high for the database column type.
```

2023-07-03 13:46 UTC, cg-tw approved these changes

2023-07-03 15:33 UTC, omercier approved these changes

2023-07-03 15:34 UTC, sfarouq-ext approved these changes

2023-07-03 15:36 UTC, merged