MON-19264 - Documentation - Depreciate the ip label datametrie monitoring connector
centreon/centreon-documentation pull request #2432
Opened 2023-07-03 07:19 UTC by lucie-dubrunfaut

## Description

Mark the ip label datametrie monitoring connector as depreciate

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-03 07:31 UTC, lucie-dubrunfaut commented
New PR link to https://github.com/centreon/centreon-documentation/pull/2416

2023-07-03 08:01 UTC, cg-tw requested changes

2023-07-03 08:01 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-iplabel-datametrie-restapi.md
> +Ce plugin-pack a été référencé obsolète, désormais le service Datamétrie
```suggestion
Ce connecteur est obsolète, car le service Datamétrie 
```

2023-07-03 08:01 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-iplabel-datametrie-restapi.md
> +This plugin pack has been marked as deprecated, since the Datamétrie online
```suggestion
This connector is deprecated, as the Datamétrie online 
```

2023-07-04 15:57 UTC, omercier requested changes

2023-07-04 15:57 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-iplabel-datametrie-restapi.md
> +online n'est plus disponible.
```suggestion
> Ce connecteur est obsolète, car le service Datamétrie 
> online n'est plus disponible.
```

2023-07-04 15:57 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-monitoring-iplabel-datametrie-restapi.md
> +service is not available any more.
```suggestion
> This connector is deprecated, as the Datamétrie online 
> service is not available any more.
```

2023-07-04 15:57 UTC, cg-tw submitted a review, later dismissed

2023-07-04 15:57 UTC, omercier approved these changes

2023-07-05 09:06 UTC, lucie-dubrunfaut commented
Can't merge because of "continuous-integration/jenkins/pr-merge"
Can't fix it on local command line instructions :
`remote: error: GH006: Protected branch update failed for refs/heads/staging.
remote: error: Changes must be made through a pull request. Required status check "continuous-integration/jenkins/pr-merge" is errored.
To github.com:centreon/centreon-documentation.git
 ! [remote rejected]     staging -> staging (protected branch hook declined)
error: failed to push some refs to 'github.com:centreon/centreon-documentation.git'
`

2023-07-06 11:55 UTC, cg-tw approved these changes

2023-07-06 14:00 UTC, omercier approved these changes

2023-07-06 14:12 UTC, merged