enh(epp): network-aruba-cppm-snmp
centreon/centreon-documentation pull request #2437
Opened 2023-07-04 07:41 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-04 09:09 UTC, cg-tw requested changes

2023-07-04 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +and in the [following chapter](/docs/monitoring/discovery/services-discovery/#discovery-rules).
```suggestion
and in the [following chapter](/docs/monitoring/discovery/services-discovery#discovery-rules).
```

2023-07-04 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +2. Fill the **Name**, **Alias** & **IP Address/DNS** fields according to your ressource settings.
```suggestion
2. Fill the **Name**, **Alias** & **IP Address/DNS** fields according to your resource's settings.
```

2023-07-04 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +| WARNINGAVERAGE  | Warning threshold average CPU utilization                                                           |                   |             |
```suggestion
| WARNINGAVERAGE  | Warning threshold for average CPU utilization                                                           |                   |             |
```

2023-07-04 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +| CRITICALAVERAGE | Critical threshold average CPU utilization                                                          |                   |             |
```suggestion
| CRITICALAVERAGE | Critical threshold for average CPU utilization                                                          |                   |             |
```

2023-07-04 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of service, and on page **Resources Status**. The command that is sent by
```suggestion
3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of services, and on page **Resources Status**. The command that is sent by the connector is displayed in the details panel of the service: it shows the values of the macros.
```

2023-07-04 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +is able to monitor a server using a command like this one (replace the sample values by yours):
```suggestion
is able to monitor the resource using a command like this one (replace the sample values by yours):
```

2023-07-04 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +All modes specific options are listed here:
```suggestion
All available options for each service template are listed below:
```

2023-07-04 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
> +| --use-ucd          | Use UCD mib for cpu average.                  | Mode |
```suggestion
| --use-ucd          | Use UCD MIB for CPU average.                  | Mode |
```

2023-08-01 09:54 UTC, cg-tw approved these changes

2023-08-09 16:24 UTC, omercier approved these changes

2023-08-11 08:43 UTC, merged