add(epp): hardware-ups-apc-snmp
centreon/centreon-documentation pull request #2453
Opened 2023-07-10 12:38 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-18 16:18 UTC, cg-tw requested changes

2023-07-18 16:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-apc-snmp.md
> +que le connecteur arrive bien à superviser un serveur en utilisant une commande
```suggestion
que le connecteur arrive bien à superviser la ressource en utilisant une commande
```

2023-07-18 16:18 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-apc-snmp.md
> +is able to monitor a server using a command like this one (replace the sample values by yours):
```suggestion
is able to monitor the resource using a command like this one (replace the sample values by yours):
```

2023-08-01 09:15 UTC, cg-tw approved these changes

2023-08-01 15:34 UTC, omercier approved these changes

2023-08-11 08:39 UTC, merged