MON-20534-refresh-snmp-protocol-topic
centreon/centreon-documentation pull request #2454
Opened 2023-07-10 15:18 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-10 15:30 UTC, cg-tw requested changes

2023-07-10 15:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +OK: |
empty output

2023-07-10 15:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +| Mode                | Modèle de service associé              |
this table looks suspicious, with "not used" everywhere

2023-07-10 15:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
>  |:------|:------------------|:------------|
you can't have an empty table here, you need to replace it by a sentence saying that no service templaes are linked to this host template

2023-07-10 15:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
>  |:------|:------------------|:------------|
same here

2023-07-10 15:31 UTC, cg-tw requested changes

2023-07-10 15:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +## Pack assets
same comments as for the FR version

2023-07-11 13:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> + Ce modèle d'hôte n'apporte pas de modèle de service.
```suggestion
Ce modèle d'hôte n'apporte pas de modèle de service.
```

2023-07-12 08:49 UTC, cg-tw requested changes

2023-07-12 08:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> + Ce modèle d'hôte n'apporte pas de modèle de service.
```suggestion
Ce modèle d'hôte n'apporte pas de modèle de service.
```

2023-07-12 08:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> + Ce modèle d'hôte n'apporte pas de modèle de service.
```suggestion
Ce modèle d'hôte n'apporte pas de modèle de service.
```

2023-07-12 08:56 UTC, cg-tw requested changes

2023-07-12 08:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +| Generic-Value | App-Protocol-SNMP-String-Value-custom  | Contrôle permettant de récupérer une chaine de caractères d'un OID |
```suggestion
| Generic-Value | App-Protocol-SNMP-String-Value-custom  | Contrôle permettant de récupérer une chaîne de caractères d'un OID |
```

2023-07-12 08:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +Coming soon
coming soon

2023-07-12 08:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
>  Coming soon
coming soon

2023-07-12 08:56 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
>  Coming soon
coming soon

2023-07-12 08:56 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +Coming soon
coming soon

2023-08-07 16:10 UTC, omercier approved these changes

2023-08-08 12:02 UTC, omercier approved these changes

2023-08-24 11:50 UTC, cg-tw requested changes

2023-08-24 11:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +This host template does not come linked to any service template but it's host check command is based on a SNMP Uptime check, thus valid even when ICMP protocol is blocked.
```suggestion
This host template does not bring any service template but its host check command is based on an SNMP uptime check, thus valid even when the ICMP protocol is blocked.
```

2023-08-24 11:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +is able to monitor a server using a command like this one (replace the sample values by yours):
```suggestion
is able to monitor a resource using a command like this one (replace the sample values by yours):
```

2023-08-24 11:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
> +que le connecteur arrive bien à superviser un serveur en utilisant une commande
```suggestion
que le connecteur arrive bien à superviser une ressource en utilisant une commande
```

2023-08-25 09:22 UTC, omercier approved these changes

2023-08-25 11:54 UTC, cg-tw approved these changes

2023-08-25 12:28 UTC, merged