add(epp): hardware-ups-ees-snmp
centreon/centreon-documentation pull request #2466
Opened 2023-07-13 12:59 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-18 15:57 UTC, cg-tw requested changes

2023-07-18 15:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +sur la ressource comme indiqué sur la documentation officielle du constructeur.
```suggestion
sur la ressource comme indiqué dans la documentation officielle du constructeur.
```

2023-08-01 09:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +que le connecteur arrive bien à superviser le ressource en utilisant une commande
```suggestion
que le connecteur arrive bien à superviser la ressource en utilisant une commande
```

2023-08-01 09:11 UTC, cg-tw approved these changes

2023-10-10 19:45 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +## Contenu du pack
```suggestion

Ce connecteur permet de superviser les onduleurs Emerson Energy Systems/Vertiv.

## Contenu du pack
```

2023-10-10 19:45 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +## Pack assets
```suggestion

This connectors monitors Emerson Energy Systems/Vertiv uninterruptible power supplies.

## Pack assets
```

2023-10-12 16:27 UTC, omercier approved these changes

2023-10-16 12:23 UTC, cg-tw requested changes

2023-10-16 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| Input       | HW-UPS-Ees-Input-SNMP-custom       | Contrôle les lignes d'entrées                             |
```suggestion
| Input       | HW-UPS-Ees-Input-SNMP-custom       | Contrôle les lignes d'entrée                             |
```

2023-10-16 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| SNMPEXTRAOPTIONS | Any extra option you may want to add to every command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| SNMPEXTRAOPTIONS | Any extra option you may want to add to every command (e.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-10-16 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS            | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)
```suggestion
| EXTRAOPTIONS            | Any extra option you may want to add to the command (e.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)                                      |                                              |             |
```

2023-10-16 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS  | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS  | Any extra option you may want to add to the command (e.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-10-16 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS          | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)             |
```suggestion
| EXTRAOPTIONS          | Any extra option you may want to add to the command (e.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)             |                                  |             |
```

2023-10-16 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). All options are listed [here](#available-options)                 |
```suggestion
| EXTRAOPTIONS         | Any extra option you may want to add to the command (e.g. a --verbose flag). All options are listed [here](#available-options)                 |                                                                                       |             |
```

2023-10-16 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS        | Any extra option you may want to add to the command (E.g. a --verbose flag). All options are listed [here](#available-options)        | --verbose                   |
```suggestion
| EXTRAOPTIONS        | Any extra option you may want to add to the command (e.g. a --verbose flag). All options are listed [here](#available-options)        | --verbose                   |             |
```

2023-10-16 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS   | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS   | Any extra option you may want to add to the command (e.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-10-16 12:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +This connectors monitors Emerson Energy Systems/Vertiv uninterruptible power supplies.
```suggestion
This connector monitors Emerson Energy Systems/Vertiv uninterruptible power supplies.
```

2023-10-16 12:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| SNMPEXTRAOPTIONS | Any extra option you may want to add to every command (E.g. a --verbose flag). All options are listed [here](#available-options) |                   |             |
```suggestion
| SNMPEXTRAOPTIONS | Any extra option you may want to add to every command (e.g. a --verbose flag). All options are listed [here](#available-options) |                   |             |
```

2023-10-16 12:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS            | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)
```suggestion
| EXTRAOPTIONS            | Any extra option you may want to add to the command (e.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)                                      |                                              |             |
```

2023-10-16 12:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS  | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
| EXTRAOPTIONS  | Any extra option you may want to add to the command (e.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```

2023-10-16 12:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS          | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)             |
```suggestion
| EXTRAOPTIONS          | Any extra option you may want to add to the command (e.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)             |                                  |             |
```

2023-10-16 12:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). All options are listed [here](#available-options)                 |
```suggestion
| EXTRAOPTIONS         | Any extra option you may want to add to the command (e.g. a --verbose flag). All options are listed [here](#available-options)                 |                                                                                       |             |
```

2023-10-16 12:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS        | Any extra option you may want to add to the command (E.g. a --verbose flag). All options are listed [here](#available-options)        | --verbose                   |
```suggestion
| EXTRAOPTIONS        | Any extra option you may want to add to the command (e.g. a --verbose flag). All options are listed [here](#available-options)        | --verbose                   |             |
```

2023-10-16 12:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
> +| EXTRAOPTIONS   | Any extra option you may want to add to the command (E.g. a --verbose flag). All options are listed [here](#available-options) |                   |             |
```suggestion
| EXTRAOPTIONS   | Any extra option you may want to add to the command (e.g. a --verbose flag). All options are listed [here](#available-options) |                   |             |
```

2023-10-16 12:28 UTC, cg-tw approved these changes

2023-10-16 20:28 UTC, merged