add(epp): applications-sahipro-restapi
centreon/centreon-documentation pull request #2469
Opened 2023-07-17 09:41 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-18 15:50 UTC, cg-tw requested changes

2023-07-18 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-sahipro-restapi.md
> +> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **App-Sahipro-Restapi-custom** est utilisé.
```suggestion
Ce modèle d'hôte n'apporte pas de modèle de service.
```

2023-07-18 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-sahipro-restapi.md
> +que le connecteur arrive bien à superviser un serveur en utilisant une commande
```suggestion
que le connecteur arrive bien à superviser la ressource en utilisant une commande
```

2023-07-18 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-sahipro-restapi.md
> +> The services listed above are created automatically when the **App-Sahipro-Restapi-custom** host template is used.
```suggestion
This host template does not bring any service template.
```

2023-07-18 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-sahipro-restapi.md
> +is able to monitor a server using a command like this one (replace the sample values by yours):
```suggestion
is able to monitor the resource using a command like this one (replace the sample values by yours):
```

2023-08-01 09:08 UTC, cg-tw approved these changes

2023-09-08 11:21 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-sahipro-restapi.md
> +### Modèles
```suggestion
## Contenu du pack

Sahi Pro est un logiciel d'automatisation de tests pour les applications de bureau, les applications mobiles et les applications Web.

### Modèles
```

2023-09-08 11:21 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-sahipro-restapi.md
> +### Templates
```suggestion
## Pack assets

Sahi Pro is a test automation software for desktop applications, mobile applications and web applications. 

### Templates
```

2023-09-08 16:31 UTC, omercier approved these changes

2023-09-08 16:32 UTC, merged