Refresh Splunk Events topic
centreon/centreon-documentation pull request #2471
Opened 2023-07-18 13:27 UTC by cg-tw

## Description

Refresh Splunk Events topic

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [x] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-04 10:08 UTC, tanguyvda requested changes

2023-09-04 10:08 UTC, tanguyvda commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/data-analytics/sc-splunk-events.md
> -| string | splunk_source     | source of the http event collector. like `http:<name_of_index>` |                                            |
we can't just remove this information without telling people that they do exist somewhere and that they have a default value

Those parameters are dedicated to the splunk stream connector therefore, they aren't liste in the github documentation with all documentation.

2023-09-04 10:08 UTC, tanguyvda commented on versioned_docs/version-23.04/integrations/data-analytics/sc-splunk-events.md
> -| string | splunk_source     | source of the http event collector. like `http:<name_of_index>` |                                            |
same problem

2024-08-20 15:07 UTC, cg-tw commented
Replaced by https://github.com/centreon/centreon-documentation/pull/3477

2024-08-20 15:07 UTC, closed without merging