enh(epp): operatingsystems-windows-snmp
centreon/centreon-documentation pull request #2482
Opened 2023-07-24 09:23 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-24 10:39 UTC, cg-tw requested changes

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Cpu    | OS-Windows-Cpu-SNMP-custom    | Contrôle du taux d'utilisation du CPU de la machine. Ce contrôle pourra remonter la moyenne du taux d'utilisation des CPU ainsi que le taux par CPU pour les
```suggestion
| Cpu    | OS-Windows-Cpu-SNMP-custom    | Contrôle du taux d'utilisation du CPU de la machine. Ce contrôle pourra remonter la moyenne du taux d'utilisation des CPU ainsi que le taux par CPU pour les CPU multi-cœur |
```

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Disk-Generic-Id      | OS-Windows-Disk-Generic-Id-SNMP-custom      | Contrôle du taux d'espace libre disponible du disque. Pour chaque contrôle apparaîtra le nom du disque
l'ID, pas le nom?

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Disk-Global          | OS-Windows-Disk-Global-SNMP-custom          | Contrôle du taux d'espace libre disponible du disque. Pour chaque contrôle apparaîtra le nom du disque
en fait on a 3 fois la même description

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Traffic-Generic-Id   | OS-Windows-Traffic-Generic-Id-SNMP-custom   | Contrôle de la bande passante de l'interface. Pour chaque contrôle apparaîtra le nom de l'interface
l'ID?

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Traffic-Global       | OS-Windows-Traffic-Global-SNMP-custom       | Contrôle de la bande passante de l'interface. Pour chaque contrôle apparaîtra le nom de l'interface
pareil, 3 fois de suite  la même description

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
>  > Les instructions ci-après peuvent changer en fonction de la version de
```suggestion
> Les instructions ci-après peuvent changer en fonction de votre version de
```

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
>  > votre Windows. Référez vous à la documentation officielle de Microsoft le cas
```suggestion
> Windows. Référez vous à la documentation officielle de Microsoft le cas
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Cpu           | OS-Windows-Cpu-SNMP-custom    | Check the rate of utilization of CPU for the machine. This check can give the average CPU utilization rate and the rate per CPU for multi-core CPU.
```suggestion
| Cpu           | OS-Windows-Cpu-SNMP-custom    | Check the rate of utilization of the CPU for the machine. This check can give the average CPU utilization rate and the rate per CPU for multi-core CPUs.  |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Disk-Generic-Id      | OS-Windows-Disk-Generic-Id-SNMP-custom      | Check the rate of free space on the disk. For each checks the name of the disk will appear              |            |
```suggestion
| Disk-Generic-Id      | OS-Windows-Disk-Generic-Id-SNMP-custom      | Check the rate of free space on the disk. For each check the name of the disk will appear              |            |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Disk-Generic-Id      | OS-Windows-Disk-Generic-Id-SNMP-custom      | Check the rate of free space on the disk. For each checks the name of the disk will appear              |            |
ID?

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Disk-Generic-Name    | OS-Windows-Disk-Generic-Name-SNMP-custom    | Check the rate of free space on the disk. For each checks the name of the disk will appear              |            |
```suggestion
| Disk-Generic-Name    | OS-Windows-Disk-Generic-Name-SNMP-custom    | Check the rate of free space on the disk. For each check the name of the disk will appear              |            |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| SNMP Agents     | Discover your resource through a SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) to get the discovery rule |
```suggestion
| SNMP Agents     | Discover your resources through a SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TRANSFORMSRC | Regexp src to transform display value. (security risk!!!)                                           | ^(..).*                                       |             |
?

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TRANSFORMSRC | Regexp src to transform display value. (security risk!!!)                                           | ^(..).*                                                 |             |
?

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TRANSFORMSRC | Regexp src to transform display value. (security risk!!!)                                           | ^(..).*                                       |             |
?

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TRANSFORMSRC | Regexp src to transform display value. (security risk!!!)                                           | ^(..).*                                       |             |
?

2023-07-24 10:39 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TRANSFORMSRC | Regexp src to transform display value. (security risk!!!)                                           | ^(..).*                                                 |             |
?

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TRANSFORMDST | Regexp dst to transform display value. (security risk!!!)                                           | $1                                            |             |
explain more

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| DISKID       | Set the storage (number expected) ex: 1, 2,... (empty means 'check all storage')                    |                                               |             |
```suggestion
| DISKID       | Set the storage (number expected) ex: 1, 2,... (empty means 'check all storages')                    |                                               |             |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TRANSFORMDST | Regexp dst to transform display value. (security risk!!!)                                           | $1                                            |             |
?

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| DISKNAME     | Set the storage (number expected) ex: 1, 2,... (empty means 'check all storage')                    |                                               |             |
```suggestion
| DISKNAME     | Set the storage (number expected) ex: 1, 2,... (empty means 'check all storages')                    |                                               |             |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| FILTER       | Set the storage (number expected) ex: 1, 2,... (empty means 'check all storage')                    | .*                                                      |             |
```suggestion
| FILTER       | Set the storage (number expected) ex: 1, 2,... (empty means 'check all storages')                    | .*                                                      |             |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TRANSFORMDST | Regexp dst to transform display value. (security risk!!!)                                           | $1                                                      |             |
?

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| NTPADDR      | Set the ntp hostname (if not set, localtime is used)                                                            |                   |             |
```suggestion
| NTPADDR      | Set the NTP hostname (if not set, localtime is used)                                                            |                   |             |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| NTPPORT      | Set the ntp port (Default: 123)                                                                                 |                   |             |
```suggestion
| NTPPORT      | Set the NTP port (Default: 123)                                                                                 |                   |             |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| TIMEZONE     | Set the timezone of distant server. For Windows, you need to set it. Can use format: 'Europe/London' or '+0100' |                   |             |
```suggestion
| TIMEZONE     | Set the timezone of distant server. For Windows, you need to set it. You can use the following format: 'Europe/London' or '+0100' |                   |             |
```

2023-07-24 10:39 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| --use-ucd          | Use UCD mib for cpu average.                  |
```suggestion
| --use-ucd          | Use UCD MIB for CPU average.                  |
```

2023-07-24 12:59 UTC, garnier-quentin commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +| Disk-Generic-Id      | OS-Windows-Disk-Generic-Id-SNMP-custom      | Contrôle du taux d'espace libre disponible du disque. Pour chaque contrôle apparaîtra le nom du disque
the ID is for the filter (not the displayed value)

2023-08-02 13:10 UTC, cg-tw approved these changes

2023-08-09 15:39 UTC, omercier submitted a review, later dismissed

2023-08-10 13:54 UTC, omercier commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +Please refer to the official documentation from the constructor.
```suggestion
To use this pack, the SNMP service must be properly configured on your Windows server. Please refer to the [Microsoft Knowledgebase to configure SNMP on your server](https://support.microsoft.com/en-us/kb/324263)
```

2023-08-10 13:54 UTC, omercier approved these changes

2023-08-10 15:07 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-snmp.md
> +> Windows. Référez- vous à la documentation officielle de Microsoft le cas
Référez-vous sans espace

2023-08-10 15:12 UTC, omercier approved these changes

2023-08-11 08:37 UTC, merged