add(epp): network-teltonika-snmp
centreon/centreon-documentation pull request #2499
Opened 2023-07-25 14:36 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-25 15:10 UTC, cg-tw requested changes

2023-07-25 15:10 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-teltonika-snmp.md
> +Afin de superviser votre ressource en SNMP,  il est nécessaire de configurer l'agent SNMP
```suggestion
Afin de superviser votre ressource en SNMP, il est nécessaire de configurer l'agent SNMP
```

2023-07-25 15:10 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-teltonika-snmp.md
> +3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of services, and on page **Resources Status**. The command that is sent b
```suggestion
3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of services, and on the **Resources Status** page. The command that is sent by the connector is displayed in the details panel of the service: it shows the values of the macros.
```

2023-08-01 08:33 UTC, cg-tw approved these changes

2023-08-09 15:49 UTC, omercier approved these changes

2023-08-11 08:42 UTC, merged