doc(release): prepare release notes for oss 23.04
centreon/centreon-documentation pull request #2505
Opened 2023-07-26 12:27 UTC by tuntoja

- add rn for web 23.04.6
- add rn for gorgone 23.04.4
- add rn for open tickets 23.04.2

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-26 13:00 UTC, cg-tw requested changes

2023-07-26 13:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Core] Removed non necessary data in custom_configuration column for SAML provider.
```suggestion
- [Core] Removed unnecessary data in custom_configuration column for SAML provider.
```

2023-07-26 13:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Resources Status] Fixed CSV export when metric name contains SQL keyword.
```suggestion
- [Resources Status] Fixed CSV export when metric name contained SQL keyword.
```

2023-07-26 13:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- Fixed a broker query.
```suggestion
- Fixed a Broker query.
```

2023-07-26 13:00 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Install] Updated size to metric_name column to 1021.
```suggestion
- [Install] Increased size of metric_name column to 1021.
```

2023-07-26 13:00 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Resources Status] Fixed CSV export when metric name contains SQL keyword.
```suggestion
- [Resources Status] Fixed CSV export when metric name contained SQL keyword.
```

2023-07-26 13:46 UTC, rsadik-ext approved these changes

2023-07-27 07:26 UTC, cg-tw requested changes

2023-07-27 07:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +</details/>
```suggestion
</details>
```

2023-07-27 07:26 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +</details/>
```suggestion
</details>
```

2023-07-28 10:20 UTC, rsadik-ext submitted a review, later dismissed

2023-07-28 12:07 UTC, jdelpierre commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +Release date: `soon`
```suggestion
Release date: `2023-07-28`
```

2023-07-28 12:07 UTC, jdelpierre commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +Release date: `soon`
```suggestion
Release date: `July 28, 2023`
```

2023-07-28 12:08 UTC, jdelpierre commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +Release date: `soon`
```suggestion
Release date: `July 28, 2023`
```

2023-07-28 12:08 UTC, jdelpierre commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `soon`
```suggestion
Release date: `July 28, 2023`
```

2023-07-28 12:08 UTC, jdelpierre commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `soon`
```suggestion
Release date: `July 28, 2023`
```

2023-07-28 12:08 UTC, jdelpierre commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `soon`
```suggestion
Release date: `July 28, 2023`
```

2023-07-28 12:10 UTC, cg-tw approved these changes

2023-07-28 13:18 UTC, jdelpierre approved these changes

2023-07-28 13:49 UTC, merged