doc(release): prepare release notes for modules 23.04
centreon/centreon-documentation pull request #2511
Opened 2023-07-28 11:53 UTC by tuntoja

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-07-28 15:51 UTC, cg-tw requested changes

2023-07-28 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- [Geoviews] Fixed an issue that made hosts not to be displayed on geoviews.
```suggestion
- [Geoviews] Fixed an issue that prevented hosts from being displayed on geoviews.
```

2023-07-28 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- [Packaging] Fixed packaging issue that caused map-engine service to fail to start on debian.
```suggestion
- [Packaging] Fixed packaging issue that caused the map-engine service to fail to start on Debian.
```

2023-07-28 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Allow elements to be grouped.
```suggestion
- Allowed elements to be grouped.
```

2023-07-28 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Fixed an issue making Business Activities size different between viewer and editor.
```suggestion
- Fixed an issue making Business Activities' size different between viewer and editor.
```

2023-07-28 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Fixed an issue that caused server to crash on duplicated centreon modules.
```suggestion
- Fixed an issue that caused server to crash because of duplicated Centreon modules.
```

2023-07-28 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Fixed Stream connector to send anomaly detection data to Centreon.
```suggestion
- Fixed Stream connector to send Anomaly Detection data to Centreon.
```

2023-07-28 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Fixed anomaly detection script that was not sending data history.
```suggestion
- Fixed Anomaly Detection script that was not sending data history.
```

2023-07-28 15:51 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- [Geoviews] Fixed an issue that made hosts not to be displayed on geoviews.
```suggestion
- [Geoviews] Fixed an issue that prevented hosts from being displayed on geoviews.
```

2023-07-28 15:51 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- [Packaging] Fixed packaging issue that caused map-engine service to fail to start on debian.
```suggestion
- [Packaging] Fixed packaging issue that caused the map-engine service to fail to start on Debian.
```

2023-07-28 15:51 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Allow elements to be grouped.
```suggestion
- Allowed elements to be grouped.
```

2023-07-28 15:51 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Fixed an issue making Business Activities size different between viewer and editor.
```suggestion
- Fixed an issue making Business Activities' size different between viewer and editor.
```

2023-07-28 15:51 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Fixed an issue that caused server to crash on duplicated centreon modules.
```suggestion
- Fixed an issue that caused server to crash because of duplicated Centreon modules.
```

2023-07-28 15:51 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Fixed Stream connector to send anomaly detection data to Centreon.
```suggestion
- Fixed Stream connector to send Anomaly Detection data to Centreon.
```

2023-07-28 15:51 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- Fixed anomaly detection script that was not sending data history.
```suggestion
- Fixed Anomaly Detection script that was not sending data history.
```

2023-07-28 15:53 UTC, cg-tw requested changes

2023-07-28 15:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +import ExpandCollapseAll from "@site/src/components/ExpandCollapseAll";
```suggestion
import ExpandCollapseAll from '@site/src/components/ExpandCollapseAll';
```

2023-07-28 15:53 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +import ExpandCollapseAll from "@site/src/components/ExpandCollapseAll";
```suggestion
import ExpandCollapseAll from '@site/src/components/ExpandCollapseAll';
```

2023-07-28 16:03 UTC, cg-tw approved these changes

2023-07-29 06:03 UTC, jdelpierre approved these changes

2023-07-31 07:03 UTC, cg-tw approved these changes

2023-07-31 07:38 UTC, merged