refresh IpFabric doc
centreon/centreon-documentation pull request #2529
Opened 2023-08-09 12:51 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-08-09 13:36 UTC, omercier requested changes

2023-08-09 13:36 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +
```suggestion
/usr/lib/centreon/plugins/centreon_ipfabric_api.pl \
    --plugin=apps::ipfabric::plugin \
    --mode=path-verification \
    --api-key='****' \
    --hostname='demo1.eu.ipfabric.io' \
    --verbose
```

2023-08-09 13:36 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +
The previous example was better

2023-08-09 13:36 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +OK:        | 'paths.detected.count'=88;;;0; 'paths.mismatch.count'=93;;;0; 'paths.state.all.count'=61;;;0; 'paths.state.part.count'=61;;;0; 'paths.state.none.count'=64;;;0; 'paths.state.error.count'=
```suggestion
CRITICAL: source 10.35.119.172:- destination 10.193.0.132:- [protocol: icmp] state: none [expected state: all] - source 10.72.126.112:1024-65535 destination 10.66.121.110:80,443 [protocol: tcp] state: none [expected state: all] - source 10.66.126.112:10000 destination 10.38.115.190:443 [protocol: tcp] state: none [expected state: all] | 'paths.detected.count'=6;;;0; 'paths.mismatch.count'=3;;;0; 'paths.state.all.count'=0;;;0; 'paths.state.part.count'=0;;;0; 'paths.state.none.count'=6;;;0; 'paths.state.error.count'=0;;;0;
source 10.35.119.172:- destination 10.193.0.132:- [protocol: icmp] state: none [expected state: all]
source 10.35.119.172/26:1024-65535 destination 10.193.0.132:1-60000 [protocol: tcp] state: none [expected state: none]
source 10.35.119.172/24:1024-65535 destination 10.193.0.132:80 [protocol: tcp] state: none [expected state: none]
source 10.72.126.112:1024-65535 destination 10.66.121.110:80,443 [protocol: tcp] state: none [expected state: all]
source 10.66.126.112:10000 destination 10.38.115.190:443 [protocol: tcp] state: none [expected state: all]
source 10.35.119.172/28:1024-65535 destination 10.193.0.132/28:1-60000 [protocol: tcp] state: none [expected state: none]
```

2023-08-09 13:36 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +
```suggestion
    --plugin=apps::ipfabric::plugin \
    --mode=path-verification \
    --api-key='****' \
    --hostname='demo1.eu.ipfabric.io' \
    --verbose
```

2023-08-09 13:36 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-ipfabric-api.md
> +OK:        | 'paths.detected.count'=88;;;0; 'paths.mismatch.count'=93;;;0; 'paths.state.all.count'=61;;;0; 'paths.state.part.count'=61;;;0; 'paths.state.none.count'=64;;;0; 'paths.state.error.count'=
```suggestion
CRITICAL: source 10.35.119.172:- destination 10.193.0.132:- [protocol: icmp] state: none [expected state: all] - source 10.72.126.112:1024-65535 destination 10.66.121.110:80,443 [protocol: tcp] state: none [expected state: all] - source 10.66.126.112:10000 destination 10.38.115.190:443 [protocol: tcp] state: none [expected state: all] | 'paths.detected.count'=6;;;0; 'paths.mismatch.count'=3;;;0; 'paths.state.all.count'=0;;;0; 'paths.state.part.count'=0;;;0; 'paths.state.none.count'=6;;;0; 'paths.state.error.count'=0;;;0;
source 10.35.119.172:- destination 10.193.0.132:- [protocol: icmp] state: none [expected state: all]
source 10.35.119.172/26:1024-65535 destination 10.193.0.132:1-60000 [protocol: tcp] state: none [expected state: none]
source 10.35.119.172/24:1024-65535 destination 10.193.0.132:80 [protocol: tcp] state: none [expected state: none]
source 10.72.126.112:1024-65535 destination 10.66.121.110:80,443 [protocol: tcp] state: none [expected state: all]
source 10.66.126.112:10000 destination 10.38.115.190:443 [protocol: tcp] state: none [expected state: all]
source 10.35.119.172/28:1024-65535 destination 10.193.0.132/28:1-60000 [protocol: tcp] state: none [expected state: none]
```

2023-08-09 13:43 UTC, omercier approved these changes

2023-08-10 13:54 UTC, smau-centreon approved these changes

2023-08-11 08:36 UTC, merged