Improve Debian commands in MAP update
centreon/centreon-documentation pull request #2548
Opened 2023-08-23 14:03 UTC by smau-centreon

## Description

Improve Debian commands in MAP update

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [x] 22.10.x (staging)
- [x] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-08-24 08:16 UTC, cedricmeschin requested changes

2023-08-24 08:16 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf /etc/mysql/map.cnf.bk
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf /etc/my.cnf.d/map.cnf.bk`

2023-08-24 08:16 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf.bk /etc/mysql/map.cnf
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf.bk /etc/my.cnf.d/map.cnf`

2023-08-24 08:16 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf /etc/mysql/map.cnf.bk
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf /etc/my.cnf.d/map.cnf.bk`

2023-08-24 08:16 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf.bk /etc/mysql/map.cnf
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf.bk /etc/my.cnf.d/map.cnf`

2023-08-24 08:16 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf /etc/mysql/map.cnf.bk
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf /etc/my.cnf.d/map.cnf.bk`

2023-08-24 08:16 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf.bk /etc/mysql/map.cnf
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf.bk /etc/my.cnf.d/map.cnf`

2023-08-24 08:16 UTC, cedricmeschin commented on versioned_docs/version-22.04/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf /etc/mysql/map.cnf.bk
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf /etc/my.cnf.d/map.cnf.bk`

2023-08-24 08:16 UTC, cedricmeschin commented on versioned_docs/version-22.04/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf.bk /etc/mysql/map.cnf
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf.bk /etc/my.cnf.d/map.cnf`

2023-08-24 08:16 UTC, cedricmeschin commented on versioned_docs/version-22.10/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf /etc/mysql/map.cnf.bk
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf /etc/my.cnf.d/map.cnf.bk`

2023-08-24 08:16 UTC, cedricmeschin commented on versioned_docs/version-22.10/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf.bk /etc/mysql/map.cnf
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf.bk /etc/my.cnf.d/map.cnf`

2023-08-24 08:16 UTC, cedricmeschin commented on versioned_docs/version-23.04/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf /etc/mysql/map.cnf.bk
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf /etc/my.cnf.d/map.cnf.bk`

2023-08-24 08:16 UTC, cedricmeschin commented on versioned_docs/version-23.04/graph-views/map-web-update.md
> +    cp /etc/mysql/map.cnf.bk /etc/mysql/map.cnf
The correct path for map.cnf on Debian is `/etc/my.cnf.d/map.cnf`
so the backup copy should be `cp /etc/my.cnf.d/map.cnf.bk /etc/my.cnf.d/map.cnf`

2023-08-24 09:45 UTC, cedricmeschin approved these changes

2023-09-12 11:50 UTC, Jordan9131 approved these changes

2023-09-12 11:55 UTC, Jordan9131 approved these changes

2023-09-12 13:26 UTC, merged