enh(epp): applications-monitoring-centreon-sql-metrics
centreon/centreon-documentation pull request #2551
Opened 2023-08-24 11:49 UTC by garnier-quentin

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-11 13:00 UTC, cg-tw requested changes

2023-09-11 13:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
old text with link to the watch?
or clearer explanations as to what the connector actually does?

2023-09-11 13:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
> +| Poller-Delay         | App-Monitoring-Centreon-SQL-Poller-Delay-custom         | Contrôle le temps de la dernière communication entre le collecteur et le serveur central |
```suggestion
| Poller-Delay         | App-Monitoring-Centreon-SQL-Poller-Delay-custom         | Contrôle le temps écoulé depuis la dernière communication entre le collecteur et le serveur central |
```

2023-09-11 13:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
> +Les métriques sont personnalisables.
text?

2023-09-11 13:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
>  L'utilisateur doit avoir les droits de réaliser un 'SELECT' sur les tables **index_data**, **metrics** et **instances** de la base **centreon_storage**.
```suggestion
L'utilisateur doit avoir le droit de réaliser un 'SELECT' sur les tables **index_data**, **metrics** et **instances** de la base **centreon_storage**. 
```

2023-11-06 14:55 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
> +Custom metrics. It depends of the service configuration.
```suggestion
Metrics depend on the service configuration. Check our [The Watch blog post](https://thewatch.centreon.com/product-how-to-21/get-to-know-app-centreon-sql-metric-pack-and-start-building-some-virtual-curves-296).
```

2023-11-06 14:56 UTC, omercier approved these changes

2023-11-08 15:02 UTC, cg-tw approved these changes

2023-11-08 15:02 UTC, merged