MC test batch - applications protocol x509
centreon/centreon-documentation pull request #2575
Opened 2023-08-31 11:49 UTC by omercier

## Description

Part of the test batch

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-08-31 12:06 UTC, cg-tw requested changes

2023-08-31 12:06 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +> To obtain this new metric format, include **--use-new-perfdata** in the **EXTRAOPTIONS** service macro.
is this necessary?

2023-08-31 12:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +> Pour obtenir ce nouveau format de métrique, incluez la valeur **--use-new-perfdata** dans la macro de service **EXTRAOPTIONS**.
besoin de ça ici?

2023-08-31 12:06 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +The remote server must have an X509's certificate.
?

2023-08-31 13:46 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +The remote server must have an X509's certificate.
* Oups
* Le serveur http

2023-08-31 14:04 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +The remote server must have an X509's certificate.
"Le serveur HTTP doit supporter HTTPS et présenter un certificat X509." ?

2023-08-31 14:05 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +> To obtain this new metric format, include **--use-new-perfdata** in the **EXTRAOPTIONS** service macro.
nope

2023-08-31 14:09 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +The remote server must have an X509's certificate.
```suggestion
The monitored resource must support HTTPS and present a X509 certificate.
```

2023-08-31 14:12 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +> Pour obtenir ce nouveau format de métrique, incluez la valeur **--use-new-perfdata** dans la macro de service **EXTRAOPTIONS**.
```suggestion
```

2023-08-31 14:12 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +The remote server must have an X509's certificate.
```suggestion
L'équipement supervisé doit supporter HTTPS et présenter un certificat X509.
```

2023-08-31 14:12 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-protocol-x509.md
> +> To obtain this new metric format, include **--use-new-perfdata** in the **EXTRAOPTIONS** service macro.
```suggestion
```

2023-09-04 08:56 UTC, cg-tw approved these changes

2023-09-05 15:20 UTC, merged