doc(release): prepare release notes for modules 23.04
centreon/centreon-documentation pull request #2583
Opened 2023-09-01 12:40 UTC by tuntoja

- add rn for map 23.04.6
- add rn for mbi 23.04.3
- add rn for autodiscovery 23.04.2

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-04 16:02 UTC, nmagniezCentreon requested changes

2023-09-04 16:02 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- [Server] Improved MAP service to make it restart automatically on exit or start failures.
à virer car non fonctionnel

2023-09-05 09:00 UTC, nmagniezCentreon approved these changes

2023-09-05 09:05 UTC, smau-centreon approved these changes

2023-09-05 09:24 UTC, nmagniezCentreon approved these changes

2023-09-05 09:26 UTC, Jordan9131 approved these changes

2023-09-05 11:35 UTC, merged