operatingsystems-linux-snmp: Adding Disk IO service discovery
centreon/centreon-documentation pull request #2591
Opened 2023-09-07 09:03 UTC by sdepassio

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-11 14:43 UTC, cg-tw requested changes

2023-09-11 14:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                               |             |
description

2023-09-11 14:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                               |             |
description

2023-09-11 14:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                                         |             |
description

2023-09-11 14:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +Le plugin apporte les modes suivants :
rubriques de troubleshooting?

2023-09-12 07:13 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                               |             |
```suggestion
| TRANSFORMSRC | Modify the disk name displayed by using a regular expression (pattern matching). |                                               |             |
```

2023-09-12 07:13 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMDST |                                                                                                     |                                               |             |
```suggestion
| TRANSFORMDST | Modify the disk name displayed by using a regular expression (pattern substitution). |                                               |             |
```

2023-09-12 07:13 UTC, omercier commented on pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMDST |                                                                                                     |                                               |             |
```suggestion
| TRANSFORMDST | Modify the disk name displayed by using a regular expression (pattern substitution). |                                               |             |
```

2023-09-12 07:13 UTC, omercier commented on pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMDST |                                                                                                     |                                                         |             |
```suggestion
| TRANSFORMDST | Modify the disk name displayed by using a regular expression (pattern substitution). |                                                         |             |
```

2023-09-12 07:13 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMDST |                                                                                                     |                                                         |             |
```suggestion
| TRANSFORMDST | Modify the disk name displayed by using a regular expression (pattern substitution). |                                                         |             |
```

2023-09-12 07:13 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMDST |                                                                                                     |                                               |             |
```suggestion
| TRANSFORMDST | Modify the disk name displayed by using a regular expression (pattern substitution). |                                               |             |
```

2023-09-12 07:13 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                               |             |
```suggestion
| TRANSFORMSRC | Modify the disk name displayed by using a regular expression (pattern matching). |                                               |             |
```

2023-09-12 07:13 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                                         |             |
```suggestion
| TRANSFORMSRC | Modify the disk name displayed by using a regular expression (pattern matching). |                                                         |             |
```

2023-09-12 07:13 UTC, omercier commented on pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                               |             |
```suggestion
| TRANSFORMSRC | Modify the disk name displayed by using a regular expression (pattern matching). |                                               |             |
```

2023-09-12 07:13 UTC, omercier commented on pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMDST |                                                                                                     |                                               |             |
```suggestion
| TRANSFORMSRC | Modify the disk name displayed by using a regular expression (pattern matching). |                                               |             |
| TRANSFORMDST | Modify the disk name displayed by using a regular expression (pattern substitution). |                                               |             |
```

2023-09-12 07:13 UTC, omercier commented on pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                               |             |
```suggestion
| TRANSFORMSRC | Modify the disk name displayed by using a regular expression (pattern matching). |                                               |             |
```

2023-09-12 07:13 UTC, omercier commented on pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +| TRANSFORMSRC |                                                                                                     |                                                         |             |
```suggestion
| TRANSFORMSRC | Modify the disk name displayed by using a regular expression (pattern matching). |                                                         |             |
```

2023-09-12 09:36 UTC, omercier commented on pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
> +</TabItem>
```suggestion
To work properly, the Inodes mode needs the following directive to be set in the SNMP server configuration file:

```includeAllDisks 10%```

</TabItem>
```

2023-09-12 09:38 UTC, omercier approved these changes

2023-09-12 09:38 UTC, cg-tw approved these changes

2023-09-12 14:54 UTC, merged