add(epp): applications-databases-mongodb
centreon/centreon-documentation pull request #2611
Opened 2023-09-14 11:31 UTC by garnier-quentin

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [X] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-14 11:59 UTC, cg-tw requested changes

2023-09-14 11:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mongodb.md
> +| Collection-Statistics | App-DB-Mongodb-Collection-Statistics-custom | Check collections statistics, per databases | X          |
```suggestion
| Collection-Statistics | App-DB-Mongodb-Collection-Statistics-custom | Check collection statistics, per database | X          |
```

2023-09-14 11:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mongodb.md
> +| Connections           | App-DB-Mongodb-Connections-custom           | Check connections number                    |            |
```suggestion
| Connections           | App-DB-Mongodb-Connections-custom           | Check the number of connections  |            |
```

2023-09-14 11:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mongodb.md
> +| Database-Statistics   | App-DB-Mongodb-Database-Statistics-custom   | Check databases statistics                  | X          |
```suggestion
| Database-Statistics   | App-DB-Mongodb-Database-Statistics-custom   | Check database statistics                  | X          |
```

2023-09-14 11:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mongodb.md
> +| Collection-Statistics | App-DB-Mongodb-Collection-Statistics-custom | Contrôle les statistiques des collections, par bases de données | X          |
```suggestion
| Collection-Statistics | App-DB-Mongodb-Collection-Statistics-custom | Contrôle les statistiques des collections, par base de données | X          |
```

2023-10-05 11:12 UTC, omercier approved these changes

2023-10-10 15:36 UTC, cg-tw approved these changes

2023-10-10 15:36 UTC, merged