doc(release): Prepare release notes for oss 23.04
centreon/centreon-documentation pull request #2628
Opened 2023-09-20 13:45 UTC by tuntoja

## Description

Prepare release notes for:
* WEB 23.04.8

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [x] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-20 14:24 UTC, cg-tw requested changes

2023-09-20 14:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Core] Added feature flag system
```suggestion
- [Core] Added feature flag system.
```

2023-09-20 14:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Configuration] Added feature flag to Vault Configuration endpoints.
```suggestion
- [Configuration] Added feature flag to vault configuration endpoints.
```

2023-09-20 14:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [authentication] Removed password fields if contact is not local type.
```suggestion
- [Authentication] Removed password fields from profile page for accounts using delegated authentication.	
```

2023-09-20 14:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Anomaly Detection] Added a feature flag to hide exclusion of periods.
```suggestion
- [Anomaly Detection] Added a feature flag to hide the period exclusion interface.
```

2023-09-20 14:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Anomaly Detection] Don't list Business Activities as service in configuration form.
```suggestion
- [Anomaly Detection] Business Activities are no longer listed as services in the configuration form.
```

2023-09-20 14:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [CLAPI] Fixed the export of severities to be able to reimport them.
```suggestion
- [CLAPI] Fixed the export of severities to make it possible to reimport them.
```

2023-09-20 14:25 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Fixed the access to Centreon UI when a default page is defined using SSO authentication (OIDC/SAML).
unclear

2023-09-20 14:32 UTC, rsadik-ext submitted a review, later dismissed

2023-09-22 07:51 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- Fixed SLQi in centreonLogAction.class.php.
```suggestion
- [Security] Fixed SLQi in centreonLogAction.class.php.
```

2023-09-22 07:51 UTC, lpinsivy commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- Fixed SLQi in centreonLogAction.class.php.
```suggestion
- [Security] Fixed SLQi in centreonLogAction.class.php.
```

2023-09-22 07:52 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Fixed the access to Centreon UI when a default page is defined using SSO authentication (OIDC/SAML).
```suggestion
- [Authentication] Fixed the access to Centreon UI when a default page is configured for the user and authentication uses SSO (OIDC/SAML).	
```

2023-09-22 08:49 UTC, cg-tw requested changes

2023-09-22 08:49 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Core] Added feature flag system
```suggestion
- [Core] Added feature flag system.
```

2023-09-22 08:49 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Configuration] Added feature flag to Vault Configuration endpoints.
```suggestion
- [Configuration] Added feature flag to vault configuration endpoints.
```

2023-09-22 08:49 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [authentication] Removed password fields if contact is not local type.
```suggestion
- [Authentication] Removed password fields from profile page for accounts using delegated authentication.
```

2023-09-22 08:49 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Anomaly Detection] Added a feature flag to hide exclusion of periods.
```suggestion
- [Anomaly Detection] Added a feature flag to hide the period exclusion interface.
```

2023-09-22 08:49 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +
```suggestion
- [CLAPI] Fixed a PHP warning that was displayed when using getparam on a service.
- [Anomaly Detection] Business Activities are no longer listed as services in the configuration form.
- [CLAPI] Fixed the export of severities to make it possible to reimport them.
- [CLAPI] Removed the possibility to link a regular resource with a template.	
- [Authentication] Fixed access to the Centreon UI when a default page is configured for the user and authentication uses SSO (OIDC/SAML).	
- [Security] Fixed SLQi in centreonLogAction.class.php.
- [Resources Status] Fixed filters on hostgroups and categories that weren't returning hosts.
- [Configuration] Fixed custom macro inheritance for hosts.

```

2023-09-22 08:50 UTC, cg-tw submitted a review, later dismissed

2023-09-22 08:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +Release date: `September 21, 2023`
```suggestion
Release date: `September 22, 2023`
```

2023-09-22 08:51 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `September 21, 2023`
```suggestion
Release date: `September 22, 2023`
```

2023-09-22 08:52 UTC, cg-tw approved these changes

2023-09-22 09:55 UTC, rsadik-ext approved these changes

2023-09-22 09:57 UTC, lpinsivy submitted a review, later dismissed

2023-09-22 09:57 UTC, cg-tw requested changes

2023-09-22 09:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +<details open>
```suggestion
<details>
```

2023-09-22 09:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +</details>
```suggestion
</details>

```

2023-09-22 09:57 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +<details open>
```suggestion
<details>
```

2023-09-22 09:57 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +
```suggestion

</details>

```

2023-09-22 09:59 UTC, cg-tw approved these changes

2023-09-22 09:59 UTC, lpinsivy approved these changes

2023-09-25 07:32 UTC, merged