MC test batch - Printer standard
centreon/centreon-documentation pull request #2629
Opened 2023-09-21 09:00 UTC by omercier

## Description

Great reboot in progress.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-11-07 15:33 UTC, cg-tw requested changes

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Cover-Status       | HW-Printer-Standard-Rfc3805-CoverStatus-SNMP-custom        | ContrÃ                                                                                             |
ContrÃ?

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Impressions        | HW-Printer-Standard-Rfc3805-Impressions-SNMP-custom        | ContrÃ                                                                                             |
ContrÃ?

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| MarkerSupply-Usage | HW-Printer-Standard-Rfc3805-Markersupply-Usage-SNMP-custom | ContrÃ                                                                                             |
ContrÃ?

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| PaperTray-Usage    | HW-Printer-Standard-Rfc3805-PaperTray-Usage-SNMP-custom    | ContrÃ                                                                                             |
ContrÃ?

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Printer-Errors     | HW-Printer-Standard-Rfc3805-Errors-SNMP-custom             | ContrÃ                                                                                             |
ContrÃ?

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Printer-Errors     | HW-Printer-Errors-standard-SNMP-custom                     | Contrôle des erreurs imprimantes liées au papier                                                   |
```suggestion
| Printer-Errors     | HW-Printer-Errors-standard-SNMP-custom                     | Contrôle des erreurs imprimante liées au papier                                                   |
```

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Printer-Hardware   | HW-Printer-Standard-Rfc3805-Hardware-SNMP-custom           | Controle diffÃ                                                                                     |
1. Contrôle
2. diffÃ?

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Printer-Hardware   | HW-Printer-Hardware-standard-SNMP-custom                   | Controle différents indicateurs matériels sur une imprimante                                       |
```suggestion
| Printer-Hardware   | HW-Printer-Hardware-standard-SNMP-custom                   | Contrôle différents indicateurs matériels sur une imprimante                                       |
```

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| SNMP Agents     | Discover your resource through a SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) to get the discovery rule and create a template mapper f
```suggestion
| SNMP Agents     | Discover your resource through a SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a template mapper for the **HW-Printer-standard-rfc3805-custom** host template |
```

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +Pas de métrique pour ce mode.
```suggestion
Pas de métrique pour ce service.
```

2023-11-07 15:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +sur la ressource comme indiqué sur la documentation officielle du constructeur.
```suggestion
sur la ressource comme indiqué dans la documentation officielle du constructeur.
```

2023-11-07 15:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +To use this pack, the SNMP service must be properly configured on your ressource.
```suggestion
To use this pack, the SNMP service must be properly configured on your resource.
```

2023-11-07 15:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +No metrics ofr this mode.
```suggestion
No metrics for this service.
```

2023-11-07 15:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| SNMP Agents     | Discover your resource through a SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) to get the discovery rule and create a template mapper f
```suggestion
| SNMP Agents     | Discover your resource through a SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a template mapper for the **HW-Printer-standard-rfc3805-custom** host template |
```

2023-11-07 16:50 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Cover-Status       | HW-Printer-Standard-Rfc3805-CoverStatus-SNMP-custom        | ContrÃ                                                                                             |
```suggestion
| Cover-Status       | HW-Printer-Standard-Rfc3805-CoverStatus-SNMP-custom        | Contrôle les états des éléments recensés dans la table "cover" de la MIB définie dans la rfc3805.                                                                                             |
```

2023-11-07 16:50 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Impressions        | HW-Printer-Standard-Rfc3805-Impressions-SNMP-custom        | ContrÃ                                                                                             |
```suggestion
| Impressions        | HW-Printer-Standard-Rfc3805-Impressions-SNMP-custom        | Contrôle le nombre d'impressions entre deux contrôles.                                                                                             |
```

2023-11-07 16:50 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| MarkerSupply-Usage | HW-Printer-Standard-Rfc3805-Markersupply-Usage-SNMP-custom | ContrÃ                                                                                             |
```suggestion
| MarkerSupply-Usage | HW-Printer-Standard-Rfc3805-Markersupply-Usage-SNMP-custom | Contrôle le niveau d'encre des cartouches.                                                                                             |
```

2023-11-07 16:50 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| PaperTray-Usage    | HW-Printer-Standard-Rfc3805-PaperTray-Usage-SNMP-custom    | ContrÃ                                                                                             |
```suggestion
| PaperTray-Usage    | HW-Printer-Standard-Rfc3805-PaperTray-Usage-SNMP-custom    | Contrôle le taux de remplissage des différents bacs à papier.                                                                                             |
```

2023-11-07 16:50 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Printer-Errors     | HW-Printer-Standard-Rfc3805-Errors-SNMP-custom             | ContrÃ                                                                                             |
```suggestion
| Printer-Errors     | HW-Printer-Standard-Rfc3805-Errors-SNMP-custom             | Contrôle des erreurs imprimante liées au papier (bourrages, etc).                                                                                             |
```

2023-11-07 16:50 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-printers-standard-rfc3805-snmp.md
> +| Printer-Hardware   | HW-Printer-Standard-Rfc3805-Hardware-SNMP-custom           | Controle diffÃ                                                                                     |
```suggestion
| Printer-Hardware   | HW-Printer-Standard-Rfc3805-Hardware-SNMP-custom           | Contrôle différents indicateurs matériels sur une imprimante.                                                                                     |
```

2023-11-08 15:05 UTC, cg-tw approved these changes

2023-11-08 15:05 UTC, merged