doc(release): Prepare release notes for oss 21.10
centreon/centreon-documentation pull request #2630
Opened 2023-09-21 09:10 UTC by pkippes

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [x] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-21 09:47 UTC, rsadik-ext submitted a review, later dismissed

2023-09-22 09:00 UTC, cg-tw requested changes

2023-09-22 09:00 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +-	Fixed SLQi in centreonLogAction.class.php
```suggestion
- [Security] Fixed SLQi in centreonLogAction.class.php
```

2023-09-22 09:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +-	[Core] Updated svg-sanitize dependency.
```suggestion
- [Core] Updated svg-sanitize dependency.
```

2023-09-22 09:02 UTC, cg-tw approved these changes

2023-09-26 12:20 UTC, closed without merging