doc(release): Prepare release notes for modules 22.04
centreon/centreon-documentation pull request #2633
Opened 2023-09-21 13:13 UTC by pkippes

Added RN for maps 22.04.11

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [x] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-22 12:40 UTC, nmagniezCentreon requested changes

2023-09-22 12:40 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +
one missing (does not convey much infos though)
[Server] Fixed vulnarable property.

2023-09-22 12:40 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +-	[Server] Fixed the diagnostic protocol test.
To remove as only for NG

2023-09-22 12:40 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +-	[Server] Fixed the diagnostic protocol test.
One missing 
[Editor] Fixed the deletion of source object when copy paste.

2023-09-22 12:41 UTC, nmagniezCentreon requested changes

2023-09-22 12:41 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
> +- [Server] Makes links anchors consistent between viewer and editor.
To remove as only NG

2023-09-25 13:57 UTC, nmagniezCentreon requested changes

2023-09-25 14:19 UTC, nmagniezCentreon approved these changes

2023-09-25 14:20 UTC, smau-centreon approved these changes

2023-09-25 14:48 UTC, merged