doc(release): Prepare release notes for collect 23.04
centreon/centreon-documentation pull request #2636
Opened 2023-09-22 07:43 UTC by pkippes

Add release notes for collect 23.04

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [x] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-22 09:07 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +-	Index data INSERT request have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled.
```suggestion
- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled.
```

2023-09-22 09:07 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +-	In services and hosts tables, at cbd startup, state is filled with real_state content only if real_state is not null.
```suggestion
- In services and hosts tables, at cbd startup, state is filled with real_state content only if real_state is not null.
```

2023-09-22 09:07 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +-	Index data INSERT request have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled.
```suggestion
- Index data INSERT request have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled.
```

2023-09-22 09:07 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +-	In services and hosts tables, at cbd startup, state is filled with real_state content only if real_state is not null.
```suggestion
-	In services and hosts tables, at cbd startup, state is filled with real_state content only if real_state is not null.
```

2023-09-22 09:08 UTC, cg-tw approved these changes

2023-09-22 09:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled.
```suggestion
- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled in.
```

2023-09-22 09:16 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- Index data INSERT request have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled.
```suggestion
- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled in.
```

2023-09-22 09:43 UTC, sfarouq-ext approved these changes

2023-09-26 08:29 UTC, omercier requested changes

2023-09-26 08:29 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled in.
```suggestion
- Fixed a bug that caused the RRD graphs not to display properly when the check interval was longer than 15 minutes.
```

2023-09-26 08:29 UTC, omercier commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled in.
```suggestion
- Fixed a bug that caused the RRD graphs not to display properly when the check interval was longer than 15 minutes.
```

2023-09-26 08:29 UTC, omercier commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- In services and hosts tables, at cbd startup, state is filled with real_state content only if real_state is not null.
```suggestion
Fixed a bug that caused services and hosts to lose their statuses at cbd startup.
```

2023-09-26 08:29 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- In services and hosts tables, at cbd startup, state is filled with real_state content only if real_state is not null.
```suggestion
Fixed a bug that caused services and hosts to lose their statuses at cbd startup.
```

2023-09-26 12:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +<details open>
```suggestion
<details>
```

2023-09-26 12:21 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +<details open>
```suggestion
<details>
```

2023-09-26 12:21 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `September 25, 2023`
```suggestion
Release date: `September 26, 2023`
```

2023-09-26 12:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- Fixed a bug that caused RRD graphs not to display properly when the check interval was longer than 15 minutes.
```suggestion
- Fixed a bug that caused RRD graphs to not display properly when the check interval was longer than 15 minutes.
```

2023-09-26 12:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +Release date: `September 25, 2023`
```suggestion
Release date: `September 26, 2023`
```

2023-09-26 12:22 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Fixed a bug that caused services and hosts to lose their status at cbd startup.
```suggestion
- Fixed a bug that caused services and hosts to lose their status at cbd startup.
```

2023-09-26 12:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +Fixed a bug that caused services and hosts to lose their status at cbd startup.
```suggestion
- Fixed a bug that caused services and hosts to lose their status at cbd startup.
```

2023-09-26 12:25 UTC, cg-tw approved these changes

2023-09-26 13:33 UTC, omercier approved these changes

2023-09-26 14:41 UTC, merged