doc(release): Prepare release notes for collect 22.10
centreon/centreon-documentation pull request #2637
Opened 2023-09-22 09:01 UTC by pkippes

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [x] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-22 09:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Index data INSERT request have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled.
```suggestion
- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled in.
```

2023-09-22 09:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +-	Fixed an issue that could cause a crash when many pollers were sending check results to a broker.
```suggestion
-	Fixed an issue that could cause a crash when many pollers were sending check results to Broker.
```

2023-09-22 09:13 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Index data INSERT request have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled.
```suggestion

- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled in.
```

2023-09-22 09:13 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +-	Fixed an issue that could cause a crash when many pollers were sending check results to a broker.
```suggestion
-	Fixed an issue that could cause a crash when many pollers were sending check results to Broker.
```

2023-09-22 09:15 UTC, cg-tw requested changes

2023-09-22 09:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +-	Fixed an issue that could cause a crash when many pollers were sending check results to Broker.
```suggestion
- Fixed an issue that could cause a crash when many pollers were sending check results to Broker.
```

2023-09-22 09:15 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +-	Fixed an issue that could cause a crash when many pollers were sending check results to Broker.
```suggestion
- Fixed an issue that could cause a crash when many pollers were sending check results to Broker.
```

2023-09-22 09:15 UTC, cg-tw approved these changes

2023-09-22 09:42 UTC, sfarouq-ext approved these changes

2023-09-26 08:21 UTC, omercier requested changes

2023-09-26 08:21 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled in.
```suggestion
- Fixed a bug that caused the RRD graphs not to display properly when the check interval was longer than 15 minutes.
```

2023-09-26 08:21 UTC, omercier commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Index data INSERT requests have been replaced by INSERT ON DUPLICATE KEY UPDATE and check_interval is always filled in.
```suggestion
- Fixed a bug that caused the RRD graphs not to display properly when the check interval was longer than 15 minutes.
```

2023-09-26 12:06 UTC, cg-tw approved these changes

2023-09-26 12:23 UTC, cg-tw requested changes

2023-09-26 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +Release date: `September 25, 2023`
```suggestion
Release date: `September 26, 2023`
```

2023-09-26 12:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed a bug that caused RRD graphs not to display properly when the check interval was longer than 15 minutes.
```suggestion
- Fixed a bug that caused RRD graphs to not display properly when the check interval was longer than 15 minutes.
```

2023-09-26 12:23 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +Release date: `September 25, 2023`
```suggestion
Release date: `September 26, 2023`
```

2023-09-26 12:23 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Fixed a bug that caused RRD graphs not to display properly when the check interval was longer than 15 minutes.
```suggestion
- Fixed a bug that caused RRD graphs to not display properly when the check interval was longer than 15 minutes.
```

2023-09-26 12:26 UTC, cg-tw approved these changes

2023-09-26 13:34 UTC, omercier approved these changes

2023-09-26 14:41 UTC, merged