doc(release): Prepare release notes for modules 23.04
centreon/centreon-documentation pull request #2639
Opened 2023-09-22 10:02 UTC by pkippes

Map 23.04.7
Autodiscovery 23.04.3
AD 23.04.4
LM 23.04.2

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [x] 23.04.x (staging)
- [ ] Cloud (staging)
- [ ] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-09-25 07:58 UTC, rsadik-ext submitted a review, later dismissed

2023-09-27 12:01 UTC, Jordan9131 approved these changes

2023-09-27 13:08 UTC, nmagniezCentreon requested changes

2023-09-27 13:08 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- [Editor] Fixed an issue where copying and pasting an object deleted it.
y'a pas un problème de tabulation?

2023-09-27 13:08 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- [Server] Fixed a vulnerable property.
celui ci est legacy only. To remove

2023-09-27 13:15 UTC, Jordan9131 submitted a review, later dismissed

2023-09-27 13:47 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
> +- [Editor] Fixed an issue where copying and pasting an object deleted it.
C'est une touche perso du release manager oui, mais tout est OK en format de sortie !

2023-09-27 14:06 UTC, nmagniezCentreon approved these changes

2023-09-27 14:09 UTC, merged