MC test batch - yet another pack refreshed
centreon/centreon-documentation pull request #2640
Opened 2023-09-22 15:34 UTC by omercier

## Description

yet another pack refreshed

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] 22.10.x (staging)
- [ ] 23.04.x (staging)
- [ ] Cloud (staging)
- [x] Monitoring Connectors (staging)
- [ ] 23.10.x (next)

2023-11-08 16:45 UTC, cg-tw requested changes

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| WARNINGSTRING   | Warning threshold if the string match
matches what?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| URLPATH         | Set path to get Webpage (Default: '/')
```suggestion
| URLPATH         | Set path to get web page (Default: '/')                                                                                                                                                                                                                                                                                                     | /                                    |             |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| WARNINGSTRING   | Warning threshold if the string match
```suggestion
| WARNINGSTRING   | Warning threshold if the string matches                                                                                                                                                                                                                                                                                                      |                                      |             |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| WARNINGSTRING   | Warning threshold if the string match
matches what?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| CRITICALSTRING  | Critical threshold if the string match
```suggestion
| CRITICALSTRING  | Critical threshold if the string matches                                                                                                                                                                                                                                                                                                     |                                      |             |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| CRITICALSTRING  | Critical threshold if the string match
matches what?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of services, and on page **Resources Status**. The command that is sent b
```suggestion
3. [Deploy the configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). The service appears in the list of services, and on the **Resources Status** page. The command that is sent by the connector is displayed in the details panel of the service: it shows the values of the macros.
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +	--hostname=10.0.0.1 \
why 10.0.0.1?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --port               | Port used by Webserver
```suggestion
| --port               | Port used by the web server                                                                                                                                                                                                                                                                      |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --credentials        | Specify this option if you access webpage with authentication
```suggestion
| --credentials        | Specify this option if you are accessing  a web page with authentication                                                                                                                                                                                                                               |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --ntlmv2             | Specify this option if you access webpage over ntlmv2 authentication (Use with --credentials and --port options)
```suggestion
| --ntlmv2             | Specify this option if you are accessing a web page using ntlmv2 authentication (Use with --credentials and --port options)                                                                                                                                                                            |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --cert-file          | Specify certificate to send to the webserver
```suggestion
| --cert-file          | Specify certificate to send to the web server                                                                                                                                                                                                                                                |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --key-file           | Specify key to send to the webserver
```suggestion
| --key-file           | Specify key to send to the web server                                                                                                                                                                                                                                                        |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --cacert-file        | Specify root certificate to send to the webserver
```suggestion
| --cacert-file        | Specify root certificate to send to the web server                                                                                                                                                                                                                                           |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --extracted-pattern  | Set pattern to extracted a number (used --warning-extracted and --critical-extracted option).
```suggestion
| --extracted-pattern  | Set pattern to extract a number (use --warning-extracted and --critical-extracted options).                                                                                                                                                                                               |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --warning-time       | Warning threshold in seconds (Webpage response time)
```suggestion
| --warning-time       | Warning threshold in seconds (web page response time)                                                                                                                                                                                                                                        |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --lookup                  | What to lookup in JSON response (JSON XPath string) (can be multiple) See: http://goessner.net/articles/JsonPath/
```suggestion
| --lookup                  | What to look up in JSON response (JSON XPath string) (can be multiple) See: http://goessner.net/articles/JsonPath/                                                                                                                                                                                                                            |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --format-lookup           | Take the output message from the JSON response (JSON XPath string) Override all the format options but substitute are still applied.
substitute?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --warning-string          | Warning threshold if the string match
```suggestion
| --warning-string          | Warning threshold if the string matches                                                                                                                                                                                                                                                                                                        |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --warning-string          | Warning threshold if the string match
matches what?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --critical-string         | Critical threshold if the string match
```suggestion
| --critical-string         | Critical threshold if the string matches                                                                                                                                                                                                                                                                                                       |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --unknown-string          | Threshold unknown if the string match
```suggestion
| --unknown-string          | Unknown threshold if the string matches                                                                                                                                                                                                                                                                                                       |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --critical-string         | Critical threshold if the string match
matches what?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --unknown-string          | Threshold unknown if the string match
matches what?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --port                    | Port used by Webserver
```suggestion
| --port                    | Port used by web server                                                                                                                                                                                                                                                                                                                       |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --basic                   | Specify this option if you access webpage over basicauthentication and don't want a '401 UNAUTHORIZED' error to be logged on your webserver.  Specify this option if you
```suggestion
| --basic                   | Specify this option if you are accessing a web page using basic authentication and don't want a '401 UNAUTHORIZED' error to be logged on your web server.  Specify this option if you are accessing a web page using hidden basic authentication or you'll get a '404 NOT FOUND' error.  (Use with --credentials)                                                    |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --ntlmv2                  | Specify this option if you access webpage over ntlmv2 authentication (Use with --credentials and --port options)
```suggestion
| --ntlmv2                  | Specify this option if you are accessing a web page using ntlmv2 authentication (Use with --credentials and --port options)                                                                                                                                                                                                                             |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --cert-file               | Specify certificate to send to the webserver
```suggestion
| --cert-file               | Specify certificate to send to the web server                                                                                                                                                                                                                                                                                                 |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --urlpath                | Set path to get webpage (Default: '/')
```suggestion
| --urlpath                | Set path to get web page (Default: '/')                                                                                                                                                                                                                                                      |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --credentials            | Specify this option if you access webpage with authentication
```suggestion
| --credentials            | Specify this option if you are accessing a web page with authentication                                                                                                                                                                                                                               |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --basic                  | Specify this option if you access webpage over basicauthentication and don't want a '401 UNAUTHORIZED' error to be logged on your webserver.  Specify this option if you a
```suggestion
| --basic                  | Specify this option if you are accessing a web page using basic authentication and don't want a '401 UNAUTHORIZED' error to be logged on your web server.  Specify this option if you are accessing a web page using hidden basic authentication or you'll get a '404 NOT FOUND' error.  (Use with --credentials)   |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --cert-file              | Specify certificate to send to the webserver
```suggestion
| --cert-file              | Specify certificate to send to the web server                                                                                                                                                                                                                                                |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --key-file               | Specify key to send to the webserver
```suggestion
| --key-file               | Specify key to send to the web server                                                                                                                                                                                                                                                        |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --cacert-file            | Specify root certificate to send to the webserver
```suggestion
| --cacert-file            | Specify root certificate to send to the web server                                                                                                                                                                                                                                           |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --lookup           | What to lookup in XML response (XPath string) (can be multiple)      FORMAT OPTIONS:
```suggestion
| --lookup           | What to look up in XML response (XPath string) (can be multiple)      FORMAT OPTIONS:                                                                                                                                                                                                                                                         |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --warning-string   | Warning threshold if the string match
```suggestion
| --warning-string   | Warning threshold if the string matches                                                                                                                                                                                                                                                                                                        |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --warning-string   | Warning threshold if the string match
matches what?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --critical-string  | Critical threshold if the string match
```suggestion
| --critical-string  | Critical threshold if the string matches                                                                                                                                                                                                                                                                                                       |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --critical-string  | Critical threshold if the string match
matches what?

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --hostname         | IP Addr/FQDN of the Webserver host
```suggestion
| --hostname         | IP address/FQDN of the web server's host                                                                                                                                                                                                                                                                                                           |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --port             | Port used by Webserver
```suggestion
| --port             | Port used by web server                                                                                                                                                                                                                                                                                                                       |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --cert-file        | Specify certificate to send to the webserver
```suggestion
| --cert-file        | Specify certificate to send to the web server                                                                                                                                                                                                                                                                                                 |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --key-file         | Specify key to send to the webserver
```suggestion
| --key-file         | Specify key to send to the web server                                                                                                                                                                                                                                                                                                         |
```

2023-11-08 16:45 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --cacert-file      | Specify root certificate to send to the webserver
```suggestion
| --cacert-file      | Specify root certificate to send to the web server                                                                                                                                                                                                                                                                                            |
```

2023-11-16 15:26 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-protocol-http.md
> +| --format-lookup           | Take the output message from the JSON response (JSON XPath string) Override all the format options but substitute are still applied.
```suggestion
| --format-lookup           | Take the output message from the JSON response (JSON XPath string) Override all the format options but substitute are still applied.                                                                                                                                                                                                         |
```
```suggestion
| --format-lookup           | Take the output message from the JSON response (JSON XPath string). Overrides all the format options but substitutions are still applied.                                                                                                                                                                                                         |
```

2023-11-16 16:03 UTC, cg-tw approved these changes

2023-11-16 17:21 UTC, cg-tw approved these changes

2023-11-16 17:21 UTC, merged