enh(mc): Refreshed Azure Functions page
centreon/centreon-documentation pull request #2686
Opened 2023-10-05 13:10 UTC by omercier

## Description

Refreshed Azure Functions page

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2023-10-10 16:02 UTC, cg-tw requested changes

2023-10-10 16:02 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +| --resource          | Set resource name or id (Required).                         |
```suggestion
| --resource          | Set resource name or ID (required).                         |
```

2023-10-10 16:02 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +| --resource-group    | Set resource group (Required if resource's name is used).   |
```suggestion
| --resource-group    | Set resource group (required if resource's name is used).   |
```

2023-10-10 16:02 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +| --resource-group | Set resource group (Required if resource's name is used).                                                                       |
```suggestion
| --resource-group | Set resource group (required if resource's name is used).                                                                       |
```

2023-10-12 16:26 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +| IO-Operations | Cloud-Azure-Compute-Functions-IO-Operations-Api-custom | Contrôle les opération E                                                           |
```suggestion
| IO-Operations | Cloud-Azure-Compute-Functions-IO-Operations-Api-custom | Contrôle les opération E/S de l'application Azure Functions.                                                           |
```

2023-10-12 16:26 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +| Métrique                             | Unité |
Parce que ce n'est plus dans le template ?

2023-10-16 15:26 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +| IO-Operations | Cloud-Azure-Compute-Functions-IO-Operations-Api-custom | Contrôle les opération E                                                           |
L'originale est `Check Azure App Service I/O operations by the app.`

2023-10-16 15:35 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +| IO-Operations | Cloud-Azure-Compute-Functions-IO-Operations-Api-custom | Check Azure Functions I                            |
```suggestion
| IO-Operations | Cloud-Azure-Compute-Functions-IO-Operations-Api-custom | Check Azure Functions I/O operations.                            |
```

2023-10-17 07:49 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +	--critical-status=''
```suggestion
    --plugin=cloud::azure::compute::functions::plugin \
    --mode=cpu-time \
    --custommode=api \
    --subscription='xxxxxxxxx' \
    --tenant='xxxxxxxxx' \
    --client-id='xxxxxxxxx' \
    --client-secret='xxxxxxxxx' \
    --resource='APP01' \
    --resource-group='xxxxxxxxx' \
    --timeframe='900' \
    --interval='PT5M' \
    --aggregation='Total' \
    --warning-cpu-time='1' \
    --critical-cpu-time='2'
```

2023-10-17 07:49 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +OK: Health check status: 96 | 'appservice.status.count'=96;;;0;
```suggestion
OK: Instance 'APP01' Statistic 'total' Metrics CPU Time: 0.08s | 'APP01~total#appservice.cpu.consumed.seconds'=0.08s;;;0;
```

2023-10-17 07:49 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +### Diagnostic des erreurs communes
```suggestion
La commande ci-dessus vérifie le temps processeur consommé sur l'instance *Functions* nommée *APP01*
(```--plugin=cloud::azure::compute::functions::plugin --mode=cpu-time --resource='APP01'```).

Le mode de connexion utilisé est 'api' (```--custommode=api```), les paramètres d'authentification nécessaires à l'utilisation de ce mode
sont donc renseignés en fonction (```--subscription='xxxxxxxxx' --tenant='xxxxxxx' --client-id='xxxxxxxx' --client-secret='xxxxxxxxxx'```).

Les statuts caculés se baseront sur les valeurs totales d'un échantillon dans un intervalle de 15 minutes / 900 secondes  (```--timeframe='900'```)
avec un état retourné par tranche de 5 minutes (```--interval='PT5M'```).

Dans cet exemple, une alarme de type WARNING sera déclenchée si le temps de processeur consommé pendant l'intervalle donné
est supérieur à 1 (```--warning-cpu-time='1'```); l'alarme sera de type CRITICAL au-delà de 2
(```--critical-cpu-time='2'```).

### Diagnostic des erreurs communes
```

2023-10-17 07:49 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +	--critical-status=''
```suggestion
    --plugin=cloud::azure::compute::functions::plugin \
    --mode=cpu-time \
    --custommode=api \
    --subscription='xxxxxxxxx' \
    --tenant='xxxxxxxxx' \
    --client-id='xxxxxxxxx' \
    --client-secret='xxxxxxxxx' \
    --resource='APP01' \
    --resource-group='xxxxxxxxx' \
    --timeframe='900' \
    --interval='PT5M' \
    --aggregation='Total' \
    --warning-cpu-time='1' \
    --critical-cpu-time='2'
```

2023-10-17 07:49 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +OK: Health check status: 96 | 'appservice.status.count'=96;;;0;
```suggestion
OK: Instance 'APP01' Statistic 'total' Metrics CPU Time: 0.08s | 'APP01~total#appservice.cpu.consumed.seconds'=0.08s;;;0;
```

2023-10-17 07:49 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
> +### Troubleshooting
```suggestion

The command above checks the *Cpu-Time* of an Azure *Functions* instance using the 'api' custom-mode
(```--plugin=cloud::azure::compute::functions::plugin --mode=cpu-time --custommode=api```).
This Functions instance is identified by its id (```--resource='APP01'```) and the authentication parameters
to be used with the custom mode are specified in the options (```--subscription='xxxxxxxxx' --tenant='xxxxxxx'
--client-id='xxxxxxxx' --client-secret='xxxxxxxxxx'```).

The calculated metrics are the total (```--aggregation='Total'```) of values on a 900 secondes / 15 min period (```--timeframe='900'```)
with one sample per 5 minutes (```--interval='PT5M'```).

This command would trigger a WARNING alarm if the *Cpu-time* is reported as over 1
(```--warning-cpu-time='1'```) and a CRITICAL alarm over 2 (```--critical-cpu-time='2'```).

### Troubleshooting
```

2023-10-17 07:53 UTC, cg-tw approved these changes

2023-10-17 08:30 UTC, merged