Update applications-databases-postgresql
centreon/centreon-documentation pull request #2703
Opened 2023-10-06 17:04 UTC by omercier

## Description

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2023-10-10 16:15 UTC, cg-tw requested changes

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| *databases*~*tables*#table.space.usage.bytes         | B     |
db_name et table_name c'est plus clair

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| POSTGRESPORT         | Database Server Port                                                                                  | 5432              |             |
```suggestion
| POSTGRESPORT         | Database server port                                                                                  | 5432              |             |
```

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| POSTGRESDATABASE     | Database Name                                                                                         | postgres          |             |
```suggestion
| POSTGRESDATABASE     | Database name                                                                                         | postgres          |             |
```

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
filter what?

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
filter what?

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTERDATABASE | Filter database to checks (Can use regexp)                                                          | .*                |             |
```suggestion
| FILTERDATABASE | Filter database to checks (can use regexp)                                                          | .*                |             |
```

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTERDATABASE | Filter database to checks (Can use regexp)                                                          | .*                |             |
?

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                                                  | ^(?!(postgres\|template1\|template0)) |
filter what?

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
filter what?

2023-10-10 16:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER              | Filter database (can be a regexp)                                                                   | ^(?!(postgres\|template1\|template0)$) |             |
filter what?

2023-10-12 16:08 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| *databases*~*indexes*#index.leaf\_density.percentage | %     |
```suggestion
| *db_name~table_name*#table.space.usage.bytes         | B     |
| *db_name~table_name*#table.space.free.bytes          | B     |
| *db_name~table_name*#table.dead\_tuple.bytes         | B     |
| *db_name~index_name*#index.space.usage.bytes        | B     |
| *db_name~index_name*#index.leaf\_density.percentage | %     |
```

2023-10-12 16:08 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
database names ?

2023-10-12 16:08 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| *databases*~*indexes*#index.leaf_density.percentage | %     |
```suggestion
| *db_name~table_name*#table.space.usage.bytes       | B     |
| *db_name~table_name*#table.space.free.bytes        | B     |
| *db_name~table_name*#table.dead_tuple.bytes        | B     |
| *db_name~index_name*#index.space.usage.bytes       | B     |
| *db_name~index_name*#index.leaf_density.percentage | %     |
```

2023-10-16 15:03 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```suggestion
| FILTER       | Filter databases by name (can be a regexp).                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```

2023-10-16 15:04 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```suggestion
| FILTER       | Filter databases by name (can be a regexp).                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```

2023-10-16 15:05 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                                                  | ^(?!(postgres\|template1\|template0)) |
```suggestion
| FILTER       | Filter databases by name (can be a regexp).                                                                                                                  | ^(?!(postgres\|template1\|template0)) |             |
```

2023-10-16 15:06 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```suggestion
| FILTER       | Filter databases by name (can be a regexp).                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```

2023-10-16 15:09 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER              | Filter database (can be a regexp)                                                                   | ^(?!(postgres\|template1\|template0)$) |             |
```suggestion
| FILTER              | Filter databases by name (can be a regexp).                                                                   | ^(?!(postgres\|template1\|template0)$) |             |
```

2023-10-16 15:10 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER              | Filter database (can be a regexp)                                                                   | ^(?!(postgres\|template1\|template0)$) |             |
```suggestion
| FILTER              | Filter databases by name (can be a regexp).                                                                  | ^(?!(postgres\|template1\|template0)$) |             |
```

2023-10-16 15:11 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```suggestion
| FILTER       | Filter databases by name (can be a regexp).                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```

2023-10-16 15:11 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                                                  | ^(?!(postgres\|template1\|template0)) |
```suggestion
| FILTER       | Filter databases by name (can be a regexp).                                                                                                                  | ^(?!(postgres\|template1\|template0)) |             |
```

2023-10-16 15:11 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```suggestion
| FILTER       | Filter databases by name (can be a regexp).                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```

2023-10-16 15:11 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md
> +| FILTER       | Filter databases                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```suggestion
| FILTER       | Filter databases by name (can be a regexp).                                                                                    | ^(?!(postgres\|template1\|template0)) |             |
```

2023-10-17 07:34 UTC, cg-tw approved these changes

2023-10-17 07:34 UTC, merged