Update EC2 MC procedure
centreon/centreon-documentation pull request #2726
Opened 2023-10-16 13:45 UTC by omercier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-10-16 14:13 UTC, cg-tw requested changes

2023-10-16 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ec2.md
> +| EC2Spot-Active-Instances | Cloud-Aws-Ec2-Spot-Instances-custom | Contrôle permettant de contrôler le nombre d'instance spot active pour une Spot Fleet Request |
```suggestion
| EC2Spot-Active-Instances | Cloud-Aws-Ec2-Spot-Instances-custom | Contrôle permettant de contrôler le nombre d'instances spot active pour une Spot Fleet Request |
```

2023-10-16 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ec2.md
> +| Ec2-Instances-Types-Global  | Cloud-Aws-Ec2-Instances-Types-Global-Api-custom  | Contrôle permettant de remonter le nombre d'instances par types |
```suggestion
| Ec2-Instances-Types-Global  | Cloud-Aws-Ec2-Instances-Types-Global-Api-custom  | Contrôle permettant de remonter le nombre d'instances par type |
```

2023-10-16 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ec2.md
> +Aucune métrique pour ce modèle.
commentaire intéressant en face?

2023-10-16 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ec2.md
> +| Métrique                           | Unité |
Why did all the descriptions disappear?

2023-10-16 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ec2.md
>  ### Dépendances du Plugin
```suggestion
### Dépendances du plugin
```

2023-10-17 07:22 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ec2.md
```suggestion
| ec2.ebs.ops.write.count    | ops   |

> **Remarque** Ces métriques sont généralement nulles lorsque collectées sur un groupe d'AutoScaling.

```

2023-10-17 07:22 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-aws-ec2.md
> +| ec2.ebs.ops.write.count    | ops   |
```suggestion
| ec2.ebs.ops.write.count    | ops   |

> These metrics are most of the time irrelevant or null when applied to an AutoscalingGroup

```

2023-10-17 07:25 UTC, cg-tw approved these changes

2023-10-17 07:51 UTC, merged