Cloud notifications
centreon/centreon-documentation pull request #2730
Opened 2023-10-16 17:06 UTC by cg-tw

## Description

Cloud notifications

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] Cloud
- [ ] Monitoring Connectors

2023-10-18 14:12 UTC, lpinsivy approved these changes

2023-11-03 15:11 UTC, sfarouq-ext submitted a review, later dismissed

2023-12-04 17:52 UTC, nmagniezCentreon requested changes

2023-12-04 17:52 UTC, nmagniezCentreon commented on cloud/alerts-notifications/notif-configuration.md
> +   - Select the users (contacts and/or contact groups) you want to be notified in case of an event.
remove contact groups

2023-12-04 17:52 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/notif-configuration.md
> +   - Sélectionnez les utilisateurs (contacts et/ou groupes de contacts) qui recevront une notification en cas d'évènement.
remove groupe de contacts

2023-12-05 09:12 UTC, nmagniezCentreon requested changes

2023-12-05 09:12 UTC, nmagniezCentreon commented on cloud/alerts-notifications/notif-configuration.md
Upper case for both "When"?

2023-12-05 09:12 UTC, nmagniezCentreon commented on cloud/alerts-notifications/notif-configuration.md
> +Notifications are sent from the central server, according to the central server's time zone.
This is confusing. Plus, if user uses "Date" macro in message, this would be poller timezone.
I suggest we remove it

2023-12-05 09:38 UTC, nmagniezCentreon requested changes

2023-12-05 09:38 UTC, nmagniezCentreon commented on cloud/alerts-notifications/notif-configuration.md
> +   - Select the host groups and/or service groups you want to send notifications for. For each type of resource, select the events that will trigger a notification.
Add: Business Views (Business Edition only)

2023-12-05 11:15 UTC, nmagniezCentreon approved these changes

2023-12-05 16:19 UTC, merged