[MON-21885] [Doc] Bad incrementation in VMware health
centreon/centreon-documentation pull request #2756
Opened 2023-10-25 15:32 UTC by lucie-dubrunfaut

Update vmware2-esx and vmware2-vcenter-generic plugin-packs and documentation after host health fix

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2023-11-09 11:14 UTC, cg-tw requested changes

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | datastore name to list                                                                                                                                     | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | datastore name to list                                                                                                                                     | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER           | datastore name to list                                                                                                                                     | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER              | datastore name to list                                                                                                                                     | .*
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                 | datastore name to check                                                                                                                                    | .*
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                     | ESX hostname to check. If not set, we check all ESX
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTERTIME                 | Don't check alarm older (value in seconds)
older than what?

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER              | ESX hostname to check. If not set, we check all ESX                                                                                                  | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTERESXNAME        | ESX hostname to check. If not set, we check all ESX                                                                                                  | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTERDATASTORENAME  | Datastore to check. If not set, we check all datastores                                                                                              | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                 | ESX hostname to check. If not set, we check all ESX                                                                                                  | .*
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                 | ESX hostname to check. If not set, we check all ESX                                                                                                  | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| WARNINGOVERHEADMEMORY  | Threshold overhead                                                                                                                                   |                   |
```suggestion
| WARNINGOVERHEADMEMORY  | Overhead threshold                                                                                                                                  |                   |             |
```

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                | ESX hostname to check. If not set, we check all ESX
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                | ESX hostname to check. If not set, we check all ESX                                                                                                               | .*
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                  | ESX hostname to check. If not set, we check all ESX
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| WARNINGLUNSDEGRADED     |
no description

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER          | ESX hostname to check. If not set, we check all ESX                                                                                                  | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER         | ESX hostname to check. If not set, we check all ESX                                                                                                  | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTERESXNAME          | ESX hostname to check. If not set, we check all ESX                                                                                                                 | .*
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER         | ESX hostname to check. If not set, we check all ESX                                                                                                  | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                 | ESX hostname to check. If not set, we check all ESX                                                                                                  | .*                |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                    | ESX hostname to check. If not set, we check all ESX                                                                                                      | .*
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| UNIT                  | Select the unit for expires threshold. May be 's' for seconds,'m' for minutes, 'h' for hours, 'd' for days, 'w' for weeks. Default is days | d                 | X
expires?

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER           | VM hostname to check. If not set, we check all VMs
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                  | VM hostname to check. If not set, we check all VMs
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                       | VM hostname to check. If not set, we check all VMs
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER               | VM hostname to check. If not set, we check all VMs
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | VM hostname to check. If not set, we check all VMs
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER       | VM hostname to check. If not set, we check all VMs                                                  | .*                                                    |             |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                | VM hostname to check. If not set, we check all VMs
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER          | VM hostname to check. If not set, we check all VMs
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER       | VM hostname to check. If not set, we check all VMs                                                  | .*                                                    |             |
unclear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | VM hostname to check. If not set, we check all VMs                                                  | .*                                                    |             |
uncleear

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| NOTUP2DATESTATUS   | Status if vmtools is not upd2date (default: warning)                                                | warning                                               |             |
```suggestion
| NOTUP2DATESTATUS   | Status if vmtools is not up to date (default: warning)                                                | warning                                               |             |
```

2023-11-09 11:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +	--plugin=apps::vmware::connector::plugin \
the old command with its explanation was interesting

2023-11-13 10:26 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| FILTERTIME                 | Don't check alarm older (value in seconds)
```
my $diff_time = $current_time - $create_time;
if (defined($self->{option_results}->{filter_time}) && $self->{option_results}->{filter_time} ne '') {
        next if ($diff_time > $self->{option_results}->{filter_time});
}
```
Ne prend en compte que si l'alarme a une date de création par rapport à la date actuelle plus "vielle" que celle définie dans le filtre.
Exemple :
- filter_time = 60 (secondes => 1h)
- current_time = 11h25
- create_time = 08h25
- diff_time = 11h25 - 8h25 = 3h (360 secondes)
diff_time > filter_time ==> 360 > 60 
Donc l'alarme n'est pas prise en compte

2023-11-13 11:19 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | VM hostname to check. If not set, we check all VMs                                                  | .*                                                    |             |
```
=head1 MODE

Check virtual machine tools.

=item B<--vm-hostname>

VM hostname to check.
If not set, we check all VMs
```
C'est un filtre sur le nom des VM

2023-11-13 13:05 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| WARNINGLUNSDEGRADED     |
Je pense Thresholds il s'agit d'une génération d'option automatisée par les nouvelles perfdata

2023-11-13 13:35 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | datastore name to list                                                                                                                                     | .*                |
C'est un filtre sur le nom des databases

2023-11-13 13:46 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                     | ESX hostname to check. If not set, we check all ESX
C'est un filtre sur les noms ESX hostname

2023-11-13 13:56 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| UNIT                  | Select the unit for expires threshold. May be 's' for seconds,'m' for minutes, 'h' for hours, 'd' for days, 'w' for weeks. Default is days | d                 | X
C'est un filtre courant pour le mode uptime qui est commun à plusieurs connecteurs vraisemblablement (snmp standard > uptime).
Dans le mode commun l'option est référencée comme ceci :
```
=item B<--unit>

Select the unit for performance data and thresholds. May be 's' for seconds, 'm' for minutes,
'h' for hours, 'd' for days, 'w' for weeks.  Default is seconds
```
https://github.com/centreon/centreon-plugins/blob/c9831fb55c905740322e949d63e612ca5c2d9371/src/snmp_standard/mode/uptime.pm

2023-11-13 15:50 UTC, cg-tw requested changes

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
```suggestion

VMWare provides cloud computing and virtualization software and services.
The Centreon Plugins and Monitoring Connectors rely on the Centreon VMWare Connector to request the vCenter API.
With this connector, Centreon can monitor VMs, Datastores, ESXs, Clusters, etc.

```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| CENTREONVMWARECONTAINER    | Container to use (it depends of the connector configuration)                                          | default           |             |
```suggestion
| CENTREONVMWARECONTAINER    | Container to use (it depends on the connector's configuration)                                          | default           |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --container                                | Container to use (it depends of the connector configuration).
```suggestion
| --container                                | Container to use (it depends on the connector's configuration).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --container                                | Container to use (it depends of the connector configuration).
```suggestion
| --container                                | Container to use (it depends on the connector's configuration).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME      | datastore name to list                                                                                                                                     |
```suggestion
| DATASTORENAME      | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                       |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME    | datastore name to list                                                                                                                                     |
```suggestion
| DATASTORENAME    | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME       | datastore name to list                                                                                                                                     |
```suggestion
| DATASTORENAME       | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name   | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                      |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name         | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name         | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name   | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name         | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name         | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | datastore name to list                                                                                                                                     | .*                |
```suggestion
| FILTER             | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                      | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | datastore name to list                                                                                                                                     | .*                |
```suggestion
| FILTER             | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER           | datastore name to list                                                                                                                                     | .*                |
```suggestion
| FILTER           | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                   | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER              | datastore name to list                                                                                                                                     | .*
```suggestion
| FILTER              | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name   | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                       |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name         | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name         | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                      |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name   | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name         | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name         | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME      | datastore name to list                                                                                                                                     |
```suggestion
| DATASTORENAME      | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                   |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME      | datastore name to list                                                                                                                                     |
```suggestion
| DATASTORENAME      | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                   |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME    | datastore name to list                                                                                                                                     |
```suggestion
| DATASTORENAME    | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                  |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME       | datastore name to list                                                                                                                                     |
```suggestion
| DATASTORENAME       | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name   | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                      |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name         | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name         | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name   | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name         | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name         | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | datastore name to list                                                                                                                                     | .*                |
```suggestion
| FILTER             | The connector will only take into account alerts coming from the datastores listed here                                                                                                                            | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER             | datastore name to list                                                                                                                                     | .*                |
```suggestion
| FILTER             | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                   | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER           | datastore name to list                                                                                                                                     | .*                |
```suggestion
| FILTER           | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER              | datastore name to list                                                                                                                                     | .*
```suggestion
| FILTER              | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                 | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name   | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name         | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name         | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name   | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name         | datastore name to list.                                                                                                                                      |
```suggestion
| --datastore-name         | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME          | datastore name to check                                                                                                                                    |
```suggestion
| DATASTORENAME          | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name   | datastore name to check.                                                                                                                                     |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                 | datastore name to check                                                                                                                                    | .*
```suggestion
| FILTER                 | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                   | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name   | datastore name to check.                                                                                                                                     |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| DATASTORENAME          | datastore name to check                                                                                                                                    |
```suggestion
| DATASTORENAME          | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |                               |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --datastore-name   | datastore name to check.                                                                                                                                     |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                     |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTER                 | datastore name to check                                                                                                                                    | .*
```suggestion
| FILTER                 | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                   | .*                |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --datastore-name   | datastore name to check.                                                                                                                                     |
```suggestion
| --datastore-name   | The connector will only take into account alerts coming from the datastores listed here                                                                                                                                    |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| FILTERTIME                 | Don't check alarm older (value in seconds)
```suggestion
| FILTERTIME                 | The connector will ignore any alert older than the time period specified here (in seconds).                                                                                                                                 | 3600                        |             |
```

2023-11-13 15:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --filter-time          | Don't check alarm older (value in seconds).
```suggestion
| --filter-time          | The connector will ignore any alert older than the time period specified here (in seconds).                                                                                                                                                                                                  |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| FILTERTIME                 | Don't check alarm older (value in seconds)
```suggestion
| FILTERTIME                 | The connector will ignore any alert older than the time period specified here (in seconds).                                                                                                                                | 3600                        |             |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
> +| --filter-time          | Don't check alarm older (value in seconds).
```suggestion
| --filter-time          | The connector will ignore any alert older than the time period specified here (in seconds).                                                                                                                                                                                               |
```

2023-11-13 15:50 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
> +| --filter-time          | Don't check alarm older (value in seconds).
```suggestion
| --filter-time          | The connector will ignore any alert older than the time period specified here (in seconds).                                                                                                                                                                                             |
```

2023-11-13 17:52 UTC, cg-tw approved these changes

2023-11-13 21:19 UTC, merged