Refresh the Splunk documentation page
centreon/centreon-documentation pull request #2775
Opened 2023-10-30 15:38 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-11-09 13:27 UTC, cg-tw requested changes

2023-11-09 13:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| Query-Matches-Number | App-Monitoring-Splunk-Query-Api-custom | Contrôle le nombre de résultats pour une requête donnée. La requête doit commencer par "search ". Par exemple  |
par exemple?

2023-11-09 13:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| --splunk-retries                           | How many times we should retry queries to splunk. To use in par with the --splunk-wait paramater (Default: 5)
```suggestion
| --splunk-retries                           | How many times we should retry queries to Splunk. To use with the --splunk-wait parameter (Default: 5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
```

2023-11-09 13:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| --splunk-wait                              | How long (in seconds) should we wait between each retry. To use in par with the --splunk-retries paramater (Default: 2)
```suggestion
| --splunk-wait                              | How long (in seconds) we should wait between each retry. To use with the --splunk-retries parameter (Default: 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2023-11-09 13:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| Splunkd-Health | App-Monitoring-Splunk-Splunkd-Health-Api-custom | Check the overall health of splunkd. The health of splunkd is based on the health of all features reporting it |
reporting it?

2023-11-09 13:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| Query-Matches-Number | App-Monitoring-Splunk-Query-Api-custom | Check number of results for a query. Query has to start with "search ".Example |
example?

2023-11-09 13:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +**Configuration > Monitoring Connectors Manager** menu.
```suggestion
**Configuration > Monitoring Connector Manager** menu.
```

2023-11-09 13:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +the **Configuration > Monitoring Connectors Manager** menu.
```suggestion
the **Configuration > Monitoring Connector Manager** menu.
```

2023-11-09 13:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| --splunk-retries                           | How many times we should retry queries to splunk. To use in par with the --splunk-wait paramater (Default: 5)
```suggestion
| --splunk-retries                           | How many times we should retry queries to Splunk. To use with the --splunk-wait parameter (Default: 5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
```

2023-11-09 13:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| --splunk-wait                              | How long (in seconds) should we wait between each retry. To use in par with the --splunk-retries paramater (Default: 2)
```suggestion
| --splunk-wait                              | How long (in seconds) we should wait between each retry. To use with the --splunk-retries parameter (Default: 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2024-02-06 16:51 UTC, cg-tw approved these changes

2024-02-06 16:51 UTC, omercier approved these changes

2024-02-06 16:51 UTC, merged