Refresh the MySQL page
centreon/centreon-documentation pull request #2778
Opened 2023-10-30 16:30 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-11-09 13:33 UTC, cg-tw requested changes

2023-11-09 13:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| Database-Size      | App-DB-MySQL-Database-Size-custom      | Contrôle permettant de vérifier la taille des bases de données. Aucunes alertes par défaut                                      |
```suggestion
| Database-Size      | App-DB-MySQL-Database-Size-custom      | Contrôle permettant de vérifier la taille des bases de données. Aucune alerte par défaut                                      |
```

2023-11-09 13:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| Password-Expiration  | App-DB-MySQL-Password-Expiration-custom          | Contrôle permettant de vérifier l'expiration des mots de passe utilisateurs
```suggestion
| Password-Expiration  | App-DB-MySQL-Password-Expiration-custom          | Contrôle permettant de vérifier l'expiration des mots de passe utilisateur                                                        |
```

2023-11-09 13:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| MariaDB-Replication  | App-DB-MySQL-MariaDB-Replication-custom          |
```suggestion
| MariaDB-Replication  | App-DB-MySQL-MariaDB-Replication-custom          |   Contrôle permettant de vérifier l'état de la réplication entre deux bases de données                                                                                                                                 |
```

2023-11-09 13:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| Sql-Statement-String | App-DB-MySQL-Sql-Statement-String-Generic-custom | Contrôle permettant d'exécuter une requête SQL personnalisée renvoyant une chaine de caractères
```suggestion
| Sql-Statement-String | App-DB-MySQL-Sql-Statement-String-Generic-custom | Contrôle permettant d'exécuter une requête SQL personnalisée renvoyant une chaîne de caractères                                    |
```

2023-11-09 13:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| FILTERDATABASE     | Filter database to checks (Can be a regexp)                                                         | ^(?!(information\_schema\|performance\_schema\|test)) |             |
```suggestion
| FILTERDATABASE     | Filter by database name (can be a regexp)                                                        | ^(?!(information\_schema\|performance\_schema\|test)) |             |
```

2023-11-09 13:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| FILTERPERFDATA     |                                                                                                     | database                                              |             |
```suggestion
| FILTERPERFDATA     |      Filter by metric name                                                                                               | database                                              |             |
```

2023-11-09 13:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| WARNINGTHREADIOSTATUS     |
description

2023-11-09 13:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| --filter-database        | Filter database to checks (Can be a regexp).                                                                           |
```suggestion
| --filter-database        | Filter by database name (can be a regexp).                                                                           |
```

2023-11-09 13:41 UTC, cg-tw requested changes

2023-11-09 13:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| MariaDB-Replication  | App-DB-MySQL-MariaDB-Replication-custom          |                                                                                                    |
```suggestion
| MariaDB-Replication  | App-DB-MySQL-MariaDB-Replication-custom          |      Check the state of the replication between two databases                                                                                              |
```

2023-11-09 13:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +**Configuration > Monitoring Connectors Manager** menu.
```suggestion
**Configuration > Monitoring Connector Manager** menu.
```

2023-11-09 13:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +the **Configuration > Monitoring Connectors Manager** menu.
```suggestion
the **Configuration > Monitoring Connector Manager** menu.
```

2023-11-09 13:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| FILTERDATABASE     | Filter database to checks (Can be a regexp)                                                         | ^(?!(information\_schema\|performance\_schema\|test)) |             |
```suggestion
| FILTERDATABASE     | Filter by database name (can be a regexp)                                                        | ^(?!(information\_schema\|performance\_schema\|test)) |             |
```

2023-11-09 13:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| WARNINGDBFREE      | Thresholds (                                                                                        |                                                       |             |
remove all parentheses

2023-11-09 13:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-mysql.md
> +| --filter-database        | Filter database to checks (Can be a regexp).                                                                           |
```suggestion
| --filter-database        | Filter by database name (can be a regexp).                                                                           |
```

2023-12-12 14:43 UTC, omercier commented
We will update the Mysql doc later, this PR would make more harm than good.

2023-12-12 14:43 UTC, closed without merging