Refresh the Mikrotik documentation
centreon/centreon-documentation pull request #2782
Opened 2023-10-31 09:58 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2023-11-09 14:09 UTC, cg-tw requested changes

2024-03-12 13:09 UTC, cg-tw requested changes

2024-03-12 13:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-mikrotik-snmp.md
> +| WARNINGINVOLUME               | "Set the warning threshold for the volume of inbound traffic. This threshold can be specified in bytes and allows you to receive a warning alert when the volume of d
```suggestion
| WARNINGINVOLUME               | Set the warning threshold for the volume of inbound traffic. This threshold can be specified in bytes and allows you to receive a warning alert when the volume of data received by an interface exceeds this limit within the monitoring interval.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                                       |             |
```

2024-03-12 13:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-mikrotik-snmp.md
> +| WARNINGINVOLUME               | "Set the warning threshold for the volume of inbound traffic. This threshold can be specified in bytes and allows you to receive a warning alert when the volume of d
```suggestion
| WARNINGINVOLUME               | Set the warning threshold for the volume of inbound traffic. This threshold can be specified in bytes and allows you to receive a warning alert when the volume of data received by an interface exceeds this limit within the monitoring interval.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                                       |             |
```

2024-03-12 16:25 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-mikrotik-snmp.md
> +| CRITICALINVOLUME              |
```suggestion
| CRITICALINVOLUME              |  Set the critical threshold for the volume of inbound traffic. This threshold can be specified in bytes and allows you to receive a critical alert when the volume of data received by an interface exceeds this limit within the monitoring interval. |                                                       |             |
```

2024-03-12 16:25 UTC, omercier commented on pp/integrations/plugin-packs/procedures/network-mikrotik-snmp.md
> +| CRITICALINVOLUME              |
```suggestion
| CRITICALINVOLUME              | Set the critical threshold for the volume of inbound traffic. This threshold can be specified in bytes and allows you to receive a critical alert when the volume of data received by an interface exceeds this limit within the monitoring interval. |                                                       |             |
```

2024-03-12 16:26 UTC, omercier approved these changes

2024-03-12 16:26 UTC, cg-tw approved these changes

2024-03-12 16:39 UTC, merged