MON-21233 - Add "Azure Tenant Discovery" host autodisco provider
centreon/centreon-documentation pull request #2806
Opened 2023-11-09 18:33 UTC by sdepassio

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2023-11-13 21:24 UTC, omercier approved these changes

2023-11-14 09:24 UTC, cg-tw requested changes

2023-11-14 09:28 UTC, cg-tw requested changes

2023-11-14 09:28 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
> +Le connecteur de supervision Centreon *Azure Discover* comprend deux *fournisseurs* de découverte d'Hôtes :
```suggestion
Le connecteur de supervision Centreon *Azure Discover* comprend deux fournisseurs de découverte d'Hôtes :
```

2023-11-14 09:28 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
> +<Tabs groupId="syncOS">
```suggestion
<Tabs groupId="sync">
```

2023-11-14 09:28 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
> +<Tabs groupId="syncOS">
```suggestion
<Tabs groupId="sync">
```

2023-11-14 09:28 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
> +<Tabs groupId="syncOS">
```suggestion
<Tabs groupId="sync">
```

2023-11-14 09:28 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
> +<Tabs groupId="provider">
```suggestion
<Tabs groupId="sync">
```

2023-11-14 09:28 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
> +<Tabs groupId="provider">
```suggestion
<Tabs groupId="sync">
```

2023-11-14 15:45 UTC, merged