doc(release): Prepare release notes for oss 22.10
centreon/centreon-documentation pull request #2821
Opened 2023-11-16 13:03 UTC by pkippes

Release web : 22.10.15

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-11-16 13:29 UTC, cg-tw requested changes

2023-11-16 13:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [UI] Renamed "massive change" to "mass change" in the "more actions" selection box.
```suggestion
- [UI] Renamed "massive change" to "mass change" in the "More actions" selection box.
```

2023-11-16 13:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Recurrent Downtimes] Fixed downtime when it contains a service group and this service group is linked to a service template.
```suggestion
- [Recurrent Downtimes] Fixed an issue that occurred when a downtime period contained a service group and this service group was linked to a service template.
```

2023-11-16 13:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Ressources Status] Fixed list of resources when using h.alias filter.
```suggestion
- [Ressources Status] Fixed an issue that occurred when using an h.alias filter on the list of resources.
```

2023-11-16 13:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Packaging] Updated centreontrapd mode on debian central.
```suggestion
- [Packaging] Updated centreontrapd mode on Debian central.
```

2023-11-16 13:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Security] Fixed SQLi in getHostServicesName method.
```suggestion
- [Security] Fixed SQLi in a method.
```

2023-11-16 13:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- Fixed potential vulnerability in listing of discovered hosts.
```suggestion
- Fixed potential vulnerability in the list of discovered hosts.
```

2023-11-16 13:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [API] Added service search in hostGroups / serviceGroups endpoints.
```suggestion
- [API] Added the possibility to search for a service in hostGroups/serviceGroups endpoints.
```

2023-11-16 13:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [UX] Fixed incorrect day displayed in calendar component.
```suggestion
- [UX] Fixed an issue where an incorrect day was displayed in the calendar component.	
```

2023-11-16 13:29 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [API] Added service search in hostGroups / serviceGroups endpoints.
```suggestion
- [API] Added the possibility to search for a service in hostGroups/serviceGroups endpoints.
```

2023-11-16 13:29 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [UX] Fixed incorrect day displayed in calendar component.
```suggestion
- [UX] Fixed an issue where an incorrect day was displayed in the calendar component.
```

2023-11-16 13:29 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [UI] Renamed "massive change" to "mass change" in the "more actions" selection box.
```suggestion
- [UI] Renamed "massive change" to "mass change" in the "More actions" selection box.
```

2023-11-16 13:29 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Recurrent Downtimes] Fixed downtime when it contains a service group and this service group is linked to a service template.
```suggestion
- [Recurrent Downtimes] Fixed an issue that occurred when a downtime period contained a service group and this service group was linked to a service template.
```

2023-11-16 13:29 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Ressources Status] Fixed list of resources when using h.alias filter.
```suggestion
- [Ressources Status] Fixed an issue that occurred when using an h.alias filter on the list of resources.
```

2023-11-16 13:29 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Packaging] Updated centreontrapd mode on debian central.
```suggestion
- [Packaging] Updated centreontrapd mode on Debian central.
```

2023-11-16 13:29 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Security] Fixed SQLi in getHostServicesName method.
```suggestion
- [Security] Fixed SQLi in a method.
```

2023-11-16 13:29 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- Fixed potential vulnerability in listing of discovered hosts.
```suggestion
- Fixed potential vulnerability in the list of discovered hosts.
```

2023-11-16 13:44 UTC, rsadik-ext submitted a review, later dismissed

2023-11-17 14:54 UTC, cg-tw approved these changes

2023-11-17 15:05 UTC, rsadik-ext approved these changes

2023-11-17 16:19 UTC, merged