doc(release): prepare release notes for OSS 21.10
centreon/centreon-documentation pull request #2822
Opened 2023-11-16 13:14 UTC by pkippes

Centreon web: 21.10.17

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [x] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-11-16 13:46 UTC, rsadik-ext approved these changes

2023-11-16 14:42 UTC, cg-tw requested changes

2023-11-16 14:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
> +- [Security] Fixed SQLi in getHostServicesName method.
```suggestion
- [Security] Fixed SQLi in a method.
```

2023-11-16 14:42 UTC, cg-tw commented on versioned_docs/version-21.10/releases/centreon-core.md
> +- [Security] Fixed SQLi in getHostServicesName method.
```suggestion
- [Security] Fixed SQLi in a method.
```

2023-11-17 15:05 UTC, rsadik-ext submitted a review, later dismissed

2023-11-17 15:06 UTC, rsadik-ext approved these changes

2023-11-17 15:31 UTC, cg-tw approved these changes

2023-11-17 16:43 UTC, merged