doc(release): prepare release notes for OSS 22.04
centreon/centreon-documentation pull request #2823
Opened 2023-11-16 13:30 UTC by pkippes

release centreon web : 22.04.17

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [x] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-11-16 13:48 UTC, rsadik-ext submitted a review, later dismissed

2023-11-16 16:07 UTC, cg-tw requested changes

2023-11-16 16:07 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +- [Install] Fixed SQL permissions for centreon database user to work with MBI product.
```suggestion
- [Install] Fixed SQL permissions to allow the "centreon" database user to use MBI.
```

2023-11-16 16:07 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +- [Install] Fixed SQL permissions for centreon database user to work with MBI product.
```suggestion
- [Install] Fixed SQL permissions to allow the "centreon" database user to use MBI.
```

2023-11-17 14:57 UTC, cg-tw approved these changes

2023-11-17 15:05 UTC, rsadik-ext submitted a review, later dismissed

2023-11-20 10:43 UTC, cg-tw requested changes

2023-11-20 10:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +Release date: `November 17, 2023`
```suggestion
Release date: `November 20, 2023`
```

2023-11-20 10:43 UTC, cg-tw commented on versioned_docs/version-22.04/releases/centreon-core.md
> +Release date: `November 17, 2023`
```suggestion
Release date: `November 20, 2023`
```

2023-11-20 10:43 UTC, cg-tw approved these changes

2023-11-20 10:58 UTC, cg-tw requested changes

2023-11-20 10:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
> +Release date: `November 17, 2023`
```suggestion
Release date: `November 20, 2023`
```

2023-11-20 10:59 UTC, cg-tw approved these changes

2023-11-20 11:48 UTC, rsadik-ext approved these changes

2023-11-20 12:02 UTC, merged