doc(release): prepare release notes for OSS 23.04
centreon/centreon-documentation pull request #2824
Opened 2023-11-16 13:58 UTC by pkippes

release web version 23.04.10

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-11-16 15:00 UTC, rsadik-ext approved these changes

2023-11-16 15:01 UTC, rsadik-ext approved these changes

2023-11-16 16:52 UTC, cg-tw requested changes

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [API] Fixed an issue with broker output type when creating an output using CLAPI.
```suggestion
- [API] Fixed an issue with Broker output types when creating an output using CLAPI.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [API] Fixed an issue with password clearly displayed in Host & Service API response.
```suggestion
- [API] Fixed a security issue concerning some API responses.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Fixed authentication conditions that doesn't work with multiple values (SAML/OpenID Connect).
```suggestion
- [Authentication] Fixed authentication conditions that did not work with multiple values (SAML/OpenID Connect).
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Enabled GUI access option for imported users authenticated through SSO.
```suggestion
- [Authentication] The "Reach Centreon Front-end" option is now automatically enabled for imported users authenticated through SSO.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Fixed match with attribute used to identify users.
```suggestion
- [Authentication] Fixed an issue with the retrieval of attributes used to identify users.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Core] Fixed access to pages when Symfony debug mode is enabled.
```suggestion
- [Core] Fixed access to pages when Symfony debug mode was enabled.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Install] Fixed SQL permissions for centreon database user to work with MBI product.
```suggestion
- [Install] Fixed SQL permissions to allow the "centreon" database user to use MBI.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Install] Fixed SQL issue during update process.
```suggestion
- [Install] Fixed an SQL issue occurring during the update process.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Reduced logs messages for better understanding.
```suggestion
- [Authentication] Removed incorrect log message.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Packaging] Updated centreontrapd mode on debian central.
```suggestion
- [Packaging] Fixed an issue where centreontrapd was configured for a poller rather than for a central on Debian.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Recurrent Downtimes] Fixed downtime when it contains a service group and this service group is linked to a service template.
```suggestion
- [Recurrent Downtimes] Fixed an issue that occurred when a downtime period contained a service group and this service group was linked to a service template.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Ressources Status] Fixed list of resources when using h.alias filter.
```suggestion
- [Ressources Status] Fixed an issue that occurred when using an h.alias filter on the list of resources.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [UX] Fixed the closure of top menus in the banner after clicking on a link.
```suggestion
- [UX] Fixed an issue where top menus in the banner were not closed after clicking on a link.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Security] Fixed SQLi in getHostServicesName method.
```suggestion
- [Security] Fixed SQLi in a method.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- Fixed potential XSS vulnerability in listing of discovered hosts.
```suggestion
- Fixed potential XSS vulnerability in the list of discovered hosts.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Monitoring] Fixed display on Firefox when information contains single quote.
```suggestion
- [Monitoring] Fixed a display issue on Firefox that occurred when the Information column in the Resources Status page contained a single quote.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Resources Status] Fixed monitoring server filter when user belong to ACL.
```suggestion
- [Resources Status] Fixed an issue where the "monitoring server" filter did not display all pollers authorized by the user's ACLs.
```

2023-11-16 16:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- Events propagation in BAM has been improved and should be faster.
```suggestion
- Event propagation in BAM has been improved and should be faster.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [API] Added service search in hostGroups / serviceGroups endpoints.
```suggestion
- [API] Added the possibility to search for a service in hostGroups/serviceGroups endpoints.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [API] Fixed an issue with broker output type when creating an output using CLAPI.
```suggestion
- [API] Fixed an issue with Broker output types when creating an output using CLAPI.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [API] Fixed an issue with password clearly displayed in Host & Service API response.
```suggestion
- [API] Fixed a security issue concerning some API responses.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Fixed authentication conditions that doesn't work with multiple values (SAML/OpenID Connect).
```suggestion
- [Authentication] Fixed authentication conditions that did not work with multiple values (SAML/OpenID Connect).
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Enabled GUI access option for imported users authenticated through SSO.
```suggestion
- [Authentication] The "Reach Centreon Front-end" option is now automatically enabled for imported users authenticated through SSO.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Fixed match with attribute used to identify users.
```suggestion
- [Authentication] Fixed an issue with the retrieval of attributes used to identify users.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Authentication] Reduced logs messages for better understanding.
```suggestion
- [Authentication] Removed incorrect log message.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Core] Fixed access to pages when Symfony debug mode is enabled.
```suggestion
- [Core] Fixed access to pages when Symfony debug mode was enabled.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Install] Fixed SQL permissions for centreon database user to work with MBI product.
```suggestion
- [Install] Fixed SQL permissions to allow the "centreon" database user to use MBI.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Install] Fixed SQL issue during update process.
```suggestion
- [Install] Fixed an SQL issue occurring during the update process.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Monitoring] Fixed display on Firefox when information contains single quote.
```suggestion
- [Monitoring] Fixed a display issue on Firefox that occurred when the Information column in the Resources Status page contained a single quote.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Packaging] Updated centreontrapd mode on debian central.
```suggestion
- [Packaging] Fixed an issue where centreontrapd was configured for a poller rather than for a central on Debian.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Recurrent Downtimes] Fixed downtime when it contains a service group and this service group is linked to a service template.
```suggestion
- [Recurrent Downtimes] Fixed an issue that occurred when a downtime period contained a service group and this service group was linked to a service template.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Ressources Status] Fixed list of resources when using h.alias filter.
```suggestion
- [Ressources Status] Fixed an issue that occurred when using an h.alias filter on the list of resources.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Resources Status] Fixed monitoring server filter when user belong to ACL.
```suggestion
- [Resources Status] Fixed an issue where the "monitoring server" filter did not display all pollers authorized by the user's ACLs.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [UX] Fixed the closure of top menus in the banner after clicking on a link.
```suggestion
- [UX] Fixed an issue where top menus in the banner were not closed after clicking on a link.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Security] Fixed SQLi in getHostServicesName method.
```suggestion
- [Security] Fixed SQLi in a method.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- Fixed potential XSS vulnerability in listing of discovered hosts.
```suggestion
- Fixed potential XSS vulnerability in the list of discovered hosts.
```

2023-11-16 16:52 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- Events propagation in BAM has been improved and should be faster.
```suggestion
- Event propagation in BAM has been improved and should be faster.
```

2023-11-17 14:57 UTC, cg-tw approved these changes

2023-11-17 15:05 UTC, rsadik-ext approved these changes

2023-11-17 15:35 UTC, merged