doc(release): prepare release notes for OSS 23.10
centreon/centreon-documentation pull request #2825
Opened 2023-11-16 14:10 UTC by pkippes

release centreon web: 23.10.1

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-11-16 17:51 UTC, cg-tw requested changes

2023-11-16 17:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Core] Fixed access to pages when Symfony debug mode is enabled.
```suggestion
- [Core] Fixed access to pages when Symfony debug mode was enabled.
```

2023-11-16 17:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Packaging] Updated centreontrapd mode on debian central.
```suggestion
- [Packaging] Fixed an issue where centreontrapd was configured for a poller rather than for a central on Debian.
```

2023-11-16 17:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- Fixed crash in partitioning script when database server does not support partitioning.
```suggestion
- Fixed crash caused by partitioning script when database server did not support partitioning.
```

2023-11-16 17:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- Fixed potential XSS vulnerability in listing of discovered hosts.
```suggestion
- Fixed potential XSS vulnerability in the list of discovered hosts.
```

2023-11-16 17:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Widget] Fixed issue when loading widget.
```suggestion
- [Widget] Fixed an issue that prevented a widget from loading correctly.
```

2023-11-16 17:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- Fixed widgets get cloned when creating a new dashboard while editing a dashboard.
```suggestion
- Fixed an issue where widgets were cloned in a new dashboard that was created while another dashboard was being edited at the same time.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [API] Added new endpoint to list all metrics of a given service.
```suggestion
- [API] Added new endpoint to list all metrics for a given service.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Widgets] simplified resource selection.
```suggestion
- [Widgets] Simplified the selection of resources.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [UX] Made the widget edition more accessible.
```suggestion
- [UX] Made the widget edition command more accessible.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [UX] Displayed warning message when dashboard modifications have not been saved yet.
```suggestion
- [UX] A warning message is now displayed when dashboard modifications have not been saved yet.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [API] Fixed an issue with password clearly displayed in Host & Service API response.
```suggestion
- [API] Fixed a security issue concerning some API responses.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Authentication] Fixed match with attribute used to identify users.
```suggestion
- [Authentication] Fixed an issue with the retrieval of attributes used to identify users.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Authentication] Enabled GUI access option for imported users authenticated through SSO.
```suggestion
- [Authentication] The "Reach Centreon Front-end" option is now automatically enabled for imported users authenticated through SSO.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [API] Fixed issue when using special characters in metric name.
```suggestion
- [API] Fixed issue occurring when using special characters in metric names.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Core] Fixed access to pages when Symfony debug mode is enabled.
```suggestion
- [Core] Fixed access to pages when Symfony debug mode was enabled.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Packaging] Updated centreontrapd mode on debian central.
```suggestion
- [Packaging] Fixed an issue where centreontrapd was configured for a poller rather than for a central on Debian.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Widget] Fixed issue when loading widget.
```suggestion
- [Widget] Fixed an issue that prevented a widget from loading correctly.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- Fixed crash in partitioning script when database server does not support partitioning.
```suggestion
- Fixed crash caused by partitioning script when database server did not support partitioning.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- Fixed widgets get cloned when creating a new dashboard while editing a dashboard.
```suggestion
- Fixed an issue where widgets were cloned in a new dashboard that was created while another dashboard was being edited at the same time.
```

2023-11-16 17:51 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- Fixed potential XSS vulnerability in listing of discovered hosts.
```suggestion
- Fixed potential XSS vulnerability in the list of discovered hosts.
```

2023-11-16 17:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [API] Fixed issue when using special characters in metric name.
```suggestion
- [API] Fixed issue occurring when using special characters in metric names.
```

2023-11-17 09:16 UTC, rsadik-ext submitted a review, later dismissed

2023-11-17 14:58 UTC, cg-tw approved these changes

2023-11-17 15:05 UTC, rsadik-ext approved these changes

2023-11-17 15:34 UTC, merged