MON-24120-Updated installation 4 nodes
centreon/centreon-documentation pull request #2827
Opened 2023-11-18 01:08 UTC by thearchit3ct

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-11-23 10:10 UTC, itoussies requested changes

2023-11-23 10:10 UTC, itoussies commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
> +dnf config-manager --enable ha
```suggestion
dnf config-manager --enable highavailability
```

2023-12-05 14:00 UTC, omercier requested changes

2023-12-05 14:00 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
> +    node_list="@CENTRAL_MASTER_NAME@ @CENTRAL_SLAVE_NAME@" \
```suggestion
    node_list="@DATABASE_MASTER_NAME@ @DATABASE_SLAVE_NAME@" \
```

2023-12-05 14:00 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
> +    node_list="@CENTRAL_MASTER_NAME@ @CENTRAL_SLAVE_NAME@" \
Cf MON-32722 and please update it in all other occurrences of node_list definition

2023-12-05 14:02 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
> +    node_list="@CENTRAL_MASTER_NAME@ @CENTRAL_SLAVE_NAME@" \
this command is valid for 2 nodes clusters only (where mysql is running on the centrals)

2023-12-08 09:16 UTC, omercier submitted a review, later dismissed

2023-12-11 10:33 UTC, omercier approved these changes

2023-12-11 13:08 UTC, smau-centreon submitted a review, later dismissed

2024-01-11 09:01 UTC, cedricmeschin approved these changes

2024-01-19 10:28 UTC, merged