Refresh the vmware vcsa restapi doc
centreon/centreon-documentation pull request #2859
Opened 2023-11-30 14:51 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

EDIT by @omercier 
REFS: CTOR-169

2023-12-12 15:59 UTC, cg-tw requested changes

2023-12-12 15:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
sample text

2023-12-12 15:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| FILTERSERVICE  | Filter service (can be a regexp)                                                                                                                           |                      |
?

2023-12-12 15:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +```bash
is this ok?

2023-12-12 15:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --filter-perfdata-adv                      | Filter perfdata based on a "if" condition using the following variables: label, value, unit, warning, critical, min, max. Variables must be written eith
```suggestion
| --filter-perfdata-adv                      | Filter perfdata based on an "if" condition using the following variables: label, value, unit, warning, critical, min, max. Variables must be written either %{variable} or %(variable). Eg: adding --filter-perfdata-adv='not (%(value) == 0 and %(max) eq "")' will remove all metrics whose value equals 0 and that don't have a maximum value.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
```

2023-12-12 15:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --hostname                                 | Set hostname or IP of vsca.
```suggestion
| --hostname                                 | Specify the hostname or IP address of the VSCA server you want to monitor.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
```

2023-12-12 15:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --redis-attribute                          | Set Redis Options (--redis-attribute="cnx\_timeout=5").
```suggestion
| --redis-attribute                          | Set Redis options (--redis-attribute="cnx\_timeout=5").                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2023-12-12 15:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --filter-service                           | Filter service (can be a regexp).
?

2023-12-12 15:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
sample text

2023-12-12 15:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| FILTERSERVICE  | Filter service (can be a regexp)                                                                                                                           |                      |
?

2023-12-12 15:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --filter-service                           | Filter service (can be a regexp).
?

2023-12-12 15:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --filter-perfdata-adv                      | Filter perfdata based on a "if" condition using the following variables: label, value, unit, warning, critical, min, max. Variables must be written eith
```suggestion
| --filter-perfdata-adv                      | Filter perfdata based on an "if" condition using the following variables: label, value, unit, warning, critical, min, max. Variables must be written either %{variable} or %(variable). Eg: adding --filter-perfdata-adv='not (%(value) == 0 and %(max) eq "")' will remove all metrics whose value equals 0 and that don't have a maximum value.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
```

2023-12-12 15:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --hostname                                 | Set hostname or IP of vsca.
```suggestion
| --hostname                                 | Specify the hostname or IP address of the VSCA server you want to monitor.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
```

2023-12-12 15:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --redis-attribute                          | Set Redis Options (--redis-attribute="cnx\_timeout=5").
```suggestion
| --redis-attribute                          | Set Redis options (--redis-attribute="cnx\_timeout=5").                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2023-12-12 15:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +OK: All services are ok | '*service*#status'=;;;;
is this ok?

2024-01-16 16:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| FILTERSERVICE  | Filter service (can be a regexp)                                                                                                                           |                      |
```suggestion
| FILTERSERVICE  | Define which services should be monitored based on the services' names. This option will be treated as a regular expression.                                                                                                                        |                      |             |
```

2024-01-16 16:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --filter-service                           | Filter service (can be a regexp).
```suggestion
| --filter-service                           | Define which services should be monitored based on the services' names. This option will be treated as a regular expression.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
```

2024-01-16 16:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| --filter-service                           | Filter service (can be a regexp).
```suggestion
| --filter-service                           | Define which services should be monitored based on the services' names. This option will be treated as a regular expression.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
```

2024-01-16 16:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +| FILTERSERVICE  | Filter service (can be a regexp)                                                                                                                           |                      |
```suggestion
| FILTERSERVICE  | Define which services should be monitored based on the services' names. This option will be treated as a regular expression.                                                                                                                        |                      |             |
```

2024-03-05 16:49 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +## Contenu du pack
```suggestion
vCenter Server Appliance (VCSA) est une machine virtuelle Linux préconfigurée et optimisée pour l'exécution de VMware vCenter Server et des services associés sur Linux.

## Contenu du pack
```

2024-03-05 16:49 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
> +## Pack assets
```suggestion
The vCenter Server Appliance (VCSA) is a preconfigured Linux virtual machine, which is optimized for running VMware vCenter Server and the associated services on Linux.

## Pack assets
```

2024-03-05 16:50 UTC, omercier approved these changes

2024-03-05 16:50 UTC, cg-tw approved these changes

2024-03-05 17:04 UTC, merged