Inactive notifications in BAM Cloud
centreon/centreon-documentation pull request #2887
Opened 2023-12-13 13:55 UTC by cg-tw

## Description

Inactive notifications in BAM Cloud

## Target version (i.e. version that this PR changes)

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] Cloud
- [ ] Monitoring Connectors

2023-12-14 13:22 UTC, nmagniezCentreon requested changes

2023-12-14 13:22 UTC, nmagniezCentreon commented on cloud/service-mapping/ba-management.md
> +This feature is not currently active.
mettre un commentaire du genre 
"BAs use common notification mechanism see [here ](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/)for more details

2023-12-14 13:22 UTC, nmagniezCentreon commented on cloud/service-mapping/ba-settings.md
> +| Notification Interval    | This option is currently inactive                                                                   |
same as above

2023-12-18 14:49 UTC, cg-tw commented on cloud/service-mapping/ba-management.md
> +This feature is not currently active.
```suggestion
This screen is not currently active. In Centreon Cloud, BAs use [the same notification mechanism as hosts and services](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/).
```

2023-12-18 14:49 UTC, cg-tw commented on cloud/service-mapping/ba-settings.md
> +| Notification Time Period | This option is currently inactive                                                                   |
```suggestion
| Notification Time Period | This option is currently inactive. In Centreon Cloud, BAs use [the same notification mechanism as hosts and services](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/).                                                                  |
```

2023-12-18 14:49 UTC, cg-tw commented on cloud/service-mapping/ba-settings.md
> +| Contact Groups           | This option is currently inactive                                                                   |
```suggestion
| Contact Groups           | This option is currently inactive. In Centreon Cloud, BAs use [the same notification mechanism as hosts and services](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/).                                                                  |
```

2023-12-18 14:49 UTC, cg-tw commented on cloud/service-mapping/ba-settings.md
> +| Notification Interval    | This option is currently inactive                                                                   |
```suggestion
| Notification Interval    | This option is currently inactive. In Centreon Cloud, BAs use [the same notification mechanism as hosts and services](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/).                                                                   |
```

2023-12-18 14:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/service-mapping/ba-management.md
> +Cette fonctionnalité n'est pas active actuellement.
```suggestion
Cet écran n'est pas actif actuellement. Dans Centreon Cloud, les BA utilisent [le même mécanisme de notification que les hôtes et les services](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/).
```

2023-12-18 14:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/service-mapping/ba-settings.md
> +| Période de notification | Option actuellement inactive                                                          |
```suggestion
| Période de notification | Option actuellement inactive. Dans Centreon Cloud, les BA utilisent [le même mécanisme de notification que les hôtes et les services](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/).                                                          |
```

2023-12-18 14:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/service-mapping/ba-settings.md
> +| Groupes de contact      | Option actuellement inactive                                                        |
```suggestion
| Groupes de contact      | Option actuellement inactive. Dans Centreon Cloud, les BA utilisent [le même mécanisme de notification que les hôtes et les services](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/).                                                       |
```

2023-12-18 14:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/service-mapping/ba-settings.md
> +| Intervalle entre deux   | Option actuellement inactive                                                           |
```suggestion
| Intervalle entre deux   | Option actuellement inactive. Dans Centreon Cloud, les BA utilisent [le même mécanisme de notification que les hôtes et les services](https://docs.centreon.com/cloud/alerts-notifications/notif-configuration/).                                                          |
```

2023-12-19 10:18 UTC, nmagniezCentreon approved these changes

2023-12-19 10:20 UTC, merged