doc(release): Prepare release notes for oss 23.10
centreon/centreon-documentation pull request #2909
Opened 2023-12-20 13:53 UTC by pkippes

Release:
web 23.10.4
gorgone 23.10.2

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-12-20 14:08 UTC, rsadik-ext submitted a review, later dismissed

2023-12-21 12:50 UTC, cg-tw requested changes

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [API] Added new endpoint to create a Playlist of dashboards.
```suggestion
- [API] Added new endpoint to create a playlist of dashboards.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [API] Added new endpoint to share playlist of dashboards to contact/contactgroup.
```suggestion
- [API] Added new endpoint to share playlist of dashboards to contacts/contact groups.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Widget] added new widget "Status Grid".
```suggestion
- [Widget] Added new "Status Grid" widget.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Widget edit] Renamed "add resource" button to "refine filter".
```suggestion
- [Widget edit] Renamed "Add resource" button to "Refine filter".
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [API] POST /administration/tokens endpoint documentation now includes 201 response details.
```suggestion
- [API] POST/administration/tokens endpoint documentation now includes 201 response details.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [API] Fixed an visibility issue on configuration/users endpoint.
```suggestion
- [API] Fixed a visibility issue with configuration/users endpoint.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [API] Fixed an issue on Service Template Service group update.
```suggestion
- [API] Fixed an issue with the "Service group update" service template.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [UI] Fixed cursor issue when editing a widget
```suggestion
- [UI] Fixed a cursor issue that occurred when editing a widget.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Widget edition] Fixed issue when removing resource/metric.
```suggestion
- [Widget edition] Fixed an issue that occurred when removing a resource or a metric.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Security] Prevented the command injection in SENDTRAPCFG gorgone event.
```suggestion
- [Security] Prevented a command injection.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Metrics Graph widget] Fixed cropping issue on ordinate.
```suggestion
- [Metrics Graph widget] Fixed an issue where labels for the ordinate axis were cropped.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [API] Added new endpoint to create a Playlist of dashboards.
```suggestion
- [API] Added new endpoint to create a playlist of dashboards.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [API] Added new endpoint to share playlist of dashboards to contact/contactgroup.
```suggestion
- [API] Added new endpoint to share playlist of dashboards to contacts/contact groups.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Widget] added new widget "Status Grid".
```suggestion
- [Widget] Added new "Status Grid" widget.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Widget edit] Renamed "add resource" button to "refine filter".
```suggestion
- [Widget edit] Renamed "Add resource" button to "Refine filter".
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [API] Fixed an issue on Service Template Service group update.
```suggestion
- [API] Fixed an issue with the "Service group update" service template.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [API] POST /administration/tokens endpoint documentation now includes 201 response details.
```suggestion
- [API] POST/administration/tokens endpoint documentation now includes 201 response details.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [API] Fixed an visibility issue on configuration/users endpoint.
```suggestion
- [API] Fixed a visibility issue with configuration/users endpoint.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Metrics Graph widget] Fixed cropping issue on ordinate.
```suggestion
- [Metrics Graph widget] Fixed an issue where labels for the ordinate axis were cropped.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [UI] Fixed cursor issue when editing a widget
```suggestion
- [UI] Fixed a cursor issue that occurred when editing a widget.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Widget edition] Fixed issue when removing resource/metric.
```suggestion
- [Widget edition] Fixed an issue that occurred when removing a resource or a metric.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Security] Prevented the command injection in SENDTRAPCFG gorgone event.
```suggestion
- [Security] Prevented a command injection.
```

2023-12-21 12:50 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Gorgone] Fixed a stability issue causing the kernel to kill the gorgone process.
```suggestion
- [Gorgone] Fixed a stability issue causing the kernel to kill the **gorgoned** process.
```

2023-12-21 12:50 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Gorgone] Fixed a stability issue causing the kernel to kill the gorgone process.
```suggestion
- [Gorgone] Fixed a stability issue causing the kernel to kill the **gorgoned** process.
```

2023-12-21 12:53 UTC, cg-tw approved these changes

2023-12-21 12:56 UTC, rsadik-ext approved these changes

2023-12-21 12:57 UTC, rsadik-ext approved these changes

2023-12-21 13:58 UTC, merged