doc(release): prepare release notes for OSS 23.04
centreon/centreon-documentation pull request #2910
Opened 2023-12-21 08:41 UTC by pkippes

gorgone: 23.04.9

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2023-12-21 09:43 UTC, rsadik-ext approved these changes

2023-12-21 09:47 UTC, cg-tw requested changes

2023-12-21 09:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Gorgone] Created package to install selinux rules.
```suggestion
- [Gorgone] Created package to install SELinux rules.
```

2023-12-21 09:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +Release date: `Novembre 17, 2023`
```suggestion
Release date: `November 17, 2023`
```

2023-12-21 09:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +Release date: `Octobre 5, 2023`
```suggestion
Release date: `October 5, 2023`
```

2023-12-21 09:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +No release notes for this version.
```suggestion
No changes for this module in this version.
```

2023-12-21 09:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
>  No release notes for this version.
```suggestion
No changes for this module in this version.
```

2023-12-21 09:47 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Gorgone] Created package to install selinux rules.
```suggestion
- [Gorgone] Created package to install SELinux rules.
```

2023-12-21 09:47 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `Novembre 17, 2023`
```suggestion
Release date: `November 17, 2023`
```

2023-12-21 09:47 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +No release notes for this version.
```suggestion
No changes for this module in this version.
```

2023-12-21 09:47 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `Octobre 5, 2023`
```suggestion
Release date: `October 5, 2023`
```

2023-12-21 09:47 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
>  No release notes for this version.
```suggestion
No changes for this module in this version.
```

2023-12-21 09:48 UTC, cg-tw approved these changes

2023-12-21 10:09 UTC, cg-tw requested changes

2023-12-21 10:09 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Security] Prevented the command injection.
```suggestion
- [Security] Prevented a command injection.
```

2023-12-21 10:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Security] Prevented the command injection.
```suggestion
- [Security] Prevented a command injection.
```

2023-12-21 10:10 UTC, cg-tw submitted a review, later dismissed

2023-12-22 09:22 UTC, cg-tw approved these changes

2023-12-22 09:47 UTC, jdelpierre approved these changes

2023-12-22 09:48 UTC, rsadik-ext approved these changes

2023-12-22 09:49 UTC, merged