Refresh the network aruba instant snmp documentation
centreon/centreon-documentation pull request #2918
Opened 2023-12-27 10:25 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-08 16:55 UTC, cg-tw requested changes

2024-01-08 16:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
>  Le connecteur de supervision *Aruba Instant SNMP* utilise le protocole SNMP pour se connecter, récupérer des informations et les métriques relatives aux bornes d'accès sans fil de marque Aruba.
```suggestion
Le connecteur de supervision *Aruba Instant SNMP* utilise le protocole SNMP pour se connecter et récupérer des informations et des métriques relatives aux bornes d'accès sans fil de marque Aruba.
```

2024-01-08 16:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +| FILTERNAME           | Filter access point name (can be a regexp)                                                                                                               |
unclear

2024-01-08 16:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +| FILTERNAME     | Filter SSID name (can be a regexp)                                                                                                                           |
unclear

2024-01-08 16:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +	--warning-clients='' \
why did the the thresholds disappear?

2024-01-08 16:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +| --filter-name            | Filter access point name (can be a regexp).                                                                                                                |
unclear

2024-01-08 16:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +| --filter-name     | Filter SSID name (can be a regexp).                                                                                                                             |
unclear

2024-01-08 16:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +The Centreon Monitoring Connector *Aruba Instant SNMP* relies on the SNMP protocol to query and collect status and metrics of the Aruba Wireless Access Point equipments.
```suggestion
The Centreon Monitoring Connector *Aruba Instant SNMP* relies on the SNMP protocol to query and collect status and metrics for the Aruba Wireless Access Point devices.
```

2024-01-08 16:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +| FILTERNAME           | Filter access point name (can be a regexp)                                                                                                               |
unclear

2024-01-08 16:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +| --filter-name            | Filter access point name (can be a regexp).                                                                                                                |
unclear

2024-01-08 16:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +| FILTERNAME     | Filter SSID name (can be a regexp)                                                                                                                           |
unclear

2024-01-08 16:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +| --filter-name     | Filter SSID name (can be a regexp).                                                                                                                             |
unclear

2024-01-08 16:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
> +	--warning-clients='' \
thresholds?

2024-01-23 16:38 UTC, omercier approved these changes

2024-01-23 16:55 UTC, merged