refresh the network-firewalls-pfsense-snmp documentation
centreon/centreon-documentation pull request #2919
Opened 2023-12-27 13:38 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-25 16:30 UTC, cg-tw requested changes

2024-01-25 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
>  entirely configurable throught a user-friendly web interface.
```suggestion
is entirely configurable through a user-friendly web interface.
```

2024-01-25 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
>  and the several number of packets per second using with the SNMP protocol.
```suggestion
and the number of packets per second using with the SNMP protocol.
```

2024-01-25 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
> +| Match-Packets                 | Net-FW-Pfsense-Match-Packets-SNMP-custom                 | Check number of packets that matched a filter rule.            |            |
```suggestion
| Match-Packets                 | Net-FW-Pfsense-Match-Packets-SNMP-custom                 | Check number of packets that match a filter rule.            |            |
```

2024-01-25 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
> +| Memory-Dropped-Packets        | Net-FW-Pfsense-Memory-Dropped-Packets-SNMP-custom        | Check count of packets dropped due to memory limitations.      |            |
```suggestion
| Memory-Dropped-Packets        | Net-FW-Pfsense-Memory-Dropped-Packets-SNMP-custom        | Check number of packets dropped due to memory limitations.      |            |
```

2024-01-30 17:09 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
>  SNMP (UDP/161) du serveur Kaspersky Security Center.
```suggestion
La communication doit être possible sur le port UDP 161 depuis le collecteur
Centreon vers la ressource supervisée.
```

2024-01-30 17:11 UTC, cg-tw approved these changes

2024-01-30 17:11 UTC, omercier approved these changes

2024-01-30 17:39 UTC, merged