refresh the network-fortinet-fortimanager-snmp documentation
centreon/centreon-documentation pull request #2922
Opened 2023-12-27 15:21 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-08 14:55 UTC, cg-tw requested changes

2024-01-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fortinet-fortimanager-snmp.md
> +| Device-Status | Net-Fortinet-Fortimanager-Device-Status-SNMP-custom | Check fortinet device status. |
```suggestion
| Device-Status | Net-Fortinet-Fortimanager-Device-Status-SNMP-custom | Check Fortinet device status. |
```

2024-01-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fortinet-fortimanager-snmp.md
> +| --filter-perfdata                          | Filter perfdata that match the regexp. Example: adding --filter-perfdata='avg' will remove all metrics that do not contain 'avg' from performance data.
```suggestion
| --filter-perfdata                          | Keep only perfdata that match the regexp. Example: adding --filter-perfdata='avg' will remove all metrics that do not contain 'avg' from performance data.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2024-01-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fortinet-fortimanager-snmp.md
> +| --source-encoding                          | Define the character encoding of the response sent by the monitored resource Default: 'UTF-8'.
```suggestion
| --source-encoding                          | Define the character encoding of the response sent by the monitored resource. Default: 'UTF-8'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
```

2024-01-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortimanager-snmp.md
> +| --source-encoding                          | Define the character encoding of the response sent by the monitored resource Default: 'UTF-8'.
```suggestion
| --source-encoding                          | Define the character encoding of the response sent by the monitored resource. Default: 'UTF-8'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
```

2024-01-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fortinet-fortimanager-snmp.md
> +| --critical-device-status                | Set critical threshold for device status You can use the following variables: %{status}, %{name}                                                 |
```suggestion
| --critical-device-status                | Set critical threshold for device status. You can use the following variables: %{status}, %{name}                                                 |
```

2024-01-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortimanager-snmp.md
> +| --critical-device-status                | Set critical threshold for device status You can use the following variables: %{status}, %{name}                                                 |
```suggestion
| --critical-device-status                | Set critical threshold for device status. You can use the following variables: %{status}, %{name}                                                 |
```

2024-01-30 17:41 UTC, omercier approved these changes

2024-01-30 17:41 UTC, cg-tw approved these changes

2024-01-31 08:01 UTC, merged