refresh the network-firewalls-stonesoft documentation
centreon/centreon-documentation pull request #2923
Opened 2023-12-27 15:39 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-25 17:07 UTC, cg-tw requested changes

2024-01-25 17:07 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
> +| Disk-Global          | Net-Stonesoft-Disk-Global-SNMP-custom          | Contrôle du taux d'utilization des disques     |            |
```suggestion
| Disk-Global          | Net-Stonesoft-Disk-Global-SNMP-custom          | Contrôle du taux d'utilisation des disques     |            |
```

2024-01-25 17:07 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
> +| Disk-Name            | Net-Stonesoft-Disk-Name-SNMP-custom            | Contrôle du taux d'utilization des disques     |            |
```suggestion
| Disk-Name            | Net-Stonesoft-Disk-Name-SNMP-custom            | Contrôle du taux d'utilisation des disques     |            |
```

2024-01-25 17:07 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
missing prerequisites

2024-01-25 17:07 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
missing prerequisites

2024-02-06 17:02 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
> +as possible here as it will save time to everybody.*
```suggestion
### Configuration SNMP

Le service SNMP doit être activé et configuré sur l'équipement. Veuillez vous référer à la documentation officielle du constructeur/éditeur.

### Flux réseau

La communication doit être possible sur le port UDP 161 depuis le collecteur Centreon vers la ressource supervisée.
```

2024-02-06 17:02 UTC, omercier commented on pp/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
> +as possible here as it will save time to everybody.*
```suggestion
### SNMP Configuration

The SNMP service must be configured and activated on the host. Please refer to the official documentation from the manufacturer/publisher.

### Network flow

The target resource must be reachable from the Centreon poller on the UDP/161 SNMP port.
```

2024-02-06 17:03 UTC, omercier approved these changes

2024-02-06 17:03 UTC, cg-tw approved these changes

2024-02-06 17:36 UTC, merged