refresh network-firewalls-cisco-asa-snmp documentation
centreon/centreon-documentation pull request #2924
Opened 2023-12-27 16:15 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-25 17:17 UTC, cg-tw requested changes

2024-01-25 17:17 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-cisco-asa-snmp.md
> +| Packet-Errors-Generic-Id   | Net-FW-Cisco-Asa-Packet-Errors-Generic-Id-SNMP-custom   | Contrôle le pourcentage de paquets en erreur/écarté d'une interface réseau.         |            |
```suggestion
| Packet-Errors-Generic-Id   | Net-FW-Cisco-Asa-Packet-Errors-Generic-Id-SNMP-custom   | Contrôle le pourcentage de paquets en erreur/écartés d'une interface réseau.         |            |
```

2024-01-25 17:17 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-cisco-asa-snmp.md
> +| Packet-Errors-Generic-Name | Net-FW-Cisco-Asa-Packet-Errors-Generic-Name-SNMP-custom | Contrôle le pourcentage de paquets en erreur/écarté d'une interface réseau.         |            |
```suggestion
| Packet-Errors-Generic-Name | Net-FW-Cisco-Asa-Packet-Errors-Generic-Name-SNMP-custom | Contrôle le pourcentage de paquets en erreur/écartés d'une interface réseau.         |            |
```

2024-01-25 17:17 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-cisco-asa-snmp.md
> +| Packet-Errors-Global       | Net-FW-Cisco-Asa-Packet-Errors-Global-SNMP-custom       | Contrôle le pourcentage de paquets en erreur/écarté de plusieurs interfaces réseau. | X          |
```suggestion
| Packet-Errors-Global       | Net-FW-Cisco-Asa-Packet-Errors-Global-SNMP-custom       | Contrôle le pourcentage de paquets en erreur/écartés de plusieurs interfaces réseau. | X          |
```

2024-01-25 17:17 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-firewalls-cisco-asa-snmp.md
> +| Cpu           | Net-FW-Cisco-Asa-Cpu-SNMP-custom      | Check the rate of utilization of CPU for the machine. This check can give the average utilization rate of CPU. |
```suggestion
| Cpu           | Net-FW-Cisco-Asa-Cpu-SNMP-custom      | Check the rate of utilization of the CPU for the machine. This check can give the average utilization rate of the CPU. |
```

2024-02-06 17:07 UTC, omercier approved these changes

2024-02-06 17:07 UTC, cg-tw approved these changes

2024-02-06 17:36 UTC, merged