Refresh the network-routers-redback-snmp documentation
centreon/centreon-documentation pull request #2925
Opened 2023-12-28 08:51 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-25 17:22 UTC, cg-tw requested changes

2024-01-25 17:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
> +| Packet-Errors-Generic-Id   | Net-Redback-Packet-Errors-Generic-Id-SNMP-custom   | Contrôle le pourcentage de paquets en erreur/écarté d'une interface réseau.         |            |
```suggestion
| Packet-Errors-Generic-Id   | Net-Redback-Packet-Errors-Generic-Id-SNMP-custom   | Contrôle le pourcentage de paquets en erreur/écartés d'une interface réseau.         |            |
```

2024-01-25 17:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
> +| Packet-Errors-Generic-Name | Net-Redback-Packet-Errors-Generic-Name-SNMP-custom | Contrôle le pourcentage de paquets en erreur/écarté d'une interface réseau.         |            |
```suggestion
| Packet-Errors-Generic-Name | Net-Redback-Packet-Errors-Generic-Name-SNMP-custom | Contrôle le pourcentage de paquets en erreur/écartés d'une interface réseau.         |            |
```

2024-01-25 17:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
> +| Packet-Errors-Global       | Net-Redback-Packet-Errors-Global-SNMP-custom       | Contrôle le pourcentage de paquets en erreur/écarté de plusieurs interfaces réseau. | X          |
```suggestion
| Packet-Errors-Global       | Net-Redback-Packet-Errors-Global-SNMP-custom       | Contrôle le pourcentage de paquets en erreur/écartés de plusieurs interfaces réseau. | X          |
```

2024-01-25 17:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
> +| Traffic-Generic-Id         | Net-Redback-Traffic-Generic-Id-SNMP-custom         | Contrôle le traffic réseau d'une interface réseau.                                  |            |
```suggestion
| Traffic-Generic-Id         | Net-Redback-Traffic-Generic-Id-SNMP-custom         | Contrôle le trafic réseau d'une interface réseau.                                  |            |
```

2024-01-25 17:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
> +| Traffic-Generic-Name       | Net-Redback-Traffic-Generic-Name-SNMP-custom       | Contrôle le traffic réseau d'une interface réseau.                                  |            |
```suggestion
| Traffic-Generic-Name       | Net-Redback-Traffic-Generic-Name-SNMP-custom       | Contrôle le trafic réseau d'une interface réseau.                                  |            |
```

2024-01-25 17:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
> +| Traffic-Global             | Net-Redback-Traffic-Global-SNMP-custom             | Contrôle le traffic réseau de plusieurs interfaces réseau.                          | X          |
```suggestion
| Traffic-Global             | Net-Redback-Traffic-Global-SNMP-custom             | Contrôle le trafic réseau de plusieurs interfaces réseau.                          | X          |
```

2024-01-25 17:22 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
> +| Disk-Usage-Global | Net-Redback-Disk-Usage-Global-SNMP-custom | Check disk usages.                                    |
```suggestion
| Disk-Usage-Global | Net-Redback-Disk-Usage-Global-SNMP-custom | Check disk usage.                                    |
```

2024-01-25 17:22 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
> +| Memory            | Net-Redback-Memory-SNMP-custom            | Check the rate of the utilization of memories.        |
```suggestion
| Memory            | Net-Redback-Memory-SNMP-custom            | Check the rate of utilization of memories.        |
```

2024-02-20 16:31 UTC, cg-tw approved these changes

2024-02-20 16:33 UTC, omercier approved these changes

2024-02-20 16:53 UTC, merged