Refresh the network-silverpeak-snmp documentation
centreon/centreon-documentation pull request #2926
Opened 2023-12-28 09:11 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-25 17:26 UTC, cg-tw requested changes

2024-01-25 17:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
> +| OperStatus | Net-Silverpeak-OperStatus-SNMP-custom | Contrôle le statut operationnel d'une appliance Silverpeak            |
```suggestion
| OperStatus | Net-Silverpeak-OperStatus-SNMP-custom | Contrôle le statut opérationnel d'une appliance Silverpeak            |
```

2024-01-25 17:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
> +| Uptime     | Net-Silverpeak-Uptime-SNMP-custom     | Durée depuis laquelle l'appliance est initialisée sans inrterruption  |
```suggestion
| Uptime     | Net-Silverpeak-Uptime-SNMP-custom     | Durée depuis laquelle l'appliance est initialisée sans interruption  |
```

2024-01-25 17:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
> +| Traffic-Generic-Id   | Net-Silverpeak-Traffic-Generic-Id-SNMP-custom   | Contrôle le traffic réseau d'une interface réseau |
```suggestion
| Traffic-Generic-Id   | Net-Silverpeak-Traffic-Generic-Id-SNMP-custom   | Contrôle le trafic réseau d'une interface réseau |
```

2024-01-25 17:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
> +| Traffic-Generic-Name | Net-Silverpeak-Traffic-Generic-Name-SNMP-custom | Contrôle le traffic réseau d'une interface réseau |
```suggestion
| Traffic-Generic-Name | Net-Silverpeak-Traffic-Generic-Name-SNMP-custom | Contrôle le trafic réseau d'une interface réseau |
```

2024-01-25 17:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
> +| Traffic-Global       | Net-Silverpeak-Traffic-Global-SNMP-custom       | Contrôle le traffic réseau d'une interface réseau |
```suggestion
| Traffic-Global       | Net-Silverpeak-Traffic-Global-SNMP-custom       | Contrôle le trafic réseau d'une interface réseau |
```

2024-02-20 16:33 UTC, omercier approved these changes

2024-02-20 16:33 UTC, cg-tw approved these changes

2024-02-20 16:53 UTC, merged