Refresh the network-ucopia-snmp documentation
centreon/centreon-documentation pull request #2930
Opened 2023-12-28 14:17 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-29 09:09 UTC, cg-tw requested changes

2024-01-29 09:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ucopia-snmp.md
> +| DISPLAYOKCOUNTERS          |                                                                                                                                                              |
description?

2024-01-29 09:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ucopia-snmp.md
> +| DISPLAYOKCOUNTERS          |                                                                                                                                                              |
description?

2024-01-29 09:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ucopia-snmp.md
> +| DISPLAYOKCOUNTERS          |                                                                                                                                                              | temperatu
description?

2024-01-29 09:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ucopia-snmp.md
> +| DISPLAYOKCOUNTERS          |                                                                                                                                                              |
description?

2024-01-29 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ucopia-snmp.md
> +| DISPLAYOKCOUNTERS          |                                                                                                                                                              |
description?

2024-01-29 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ucopia-snmp.md
> +| DISPLAYOKCOUNTERS          |                                                                                                                                                              |
description?

2024-01-29 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ucopia-snmp.md
> +| DISPLAYOKCOUNTERS          |                                                                                                                                                              | temperatu
description?

2024-01-29 09:09 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ucopia-snmp.md
> +| DISPLAYOKCOUNTERS          |                                                                                                                                                              |
description?

2024-03-05 17:07 UTC, omercier approved these changes

2024-03-05 17:07 UTC, cg-tw approved these changes

2024-03-05 17:07 UTC, merged