enh: update applications-monitoring-poller
centreon/centreon-documentation pull request #2948
Opened 2024-01-04 14:55 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-01-29 14:23 UTC, cg-tw requested changes

2024-01-29 14:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
> +| proc-sshd       | App-Monitoring-Centreon-Process-sshd-custom        | Check sshd process                         |
```suggestion
| proc-sshd       | App-Monitoring-Centreon-Process-sshd-custom        | Check SSHD process                         |
```

2024-01-29 14:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
> +| proc-sshd       | App-Monitoring-Centreon-Process-sshd-custom        | Contrôle permettant de vérifier le fonctionnement du processus sshd            |
```suggestion
| proc-sshd       | App-Monitoring-Centreon-Process-sshd-custom        | Contrôle permettant de vérifier le fonctionnement du processus SSHD |
```

2024-01-29 14:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
>  ##
empty section?

2024-01-29 14:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
```suggestion

Les collecteurs Centreon doivent être supervisés par le serveur central.

```

2024-01-29 14:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
> +Un des services accompagnant le pack dispose d'une vérification réalisée à l'aide de SSH. Le serveur central doit pouvoir se connecter à tous les collecteurs supervisés.
de quel service on parle? dans que cas on doit faire l'échange de clés?

2024-01-29 14:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
> +2. Depuis le central, créer et copier la nouvelle clef SSH de l'utilisateur **centreon-engine** vers le collecteur :
interaction entre les 2 utilisateurs?

2024-03-05 16:35 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
> +Centreon collectors must be supervised by the central server.
```suggestion
Centreon collectors must be monitored by the central server.
```

2024-03-05 16:37 UTC, omercier approved these changes

2024-03-05 16:37 UTC, cg-tw approved these changes

2024-03-05 16:57 UTC, merged