add(epp): Operating system Linux SSH - FR
centreon/centreon-documentation pull request #295
Opened 2020-08-06 15:32 UTC by psamecentreon

Version FR

2020-08-11 15:12 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| system.files.open.count     | Counter files open. Unit: counter                 |
```suggestion
| system.files.open.count     | Number of files opened on the system                 |
```

2020-08-11 15:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| swap.usage.bytes            | Swap usage. Unit: bytes (b)                    |
```suggestion
| swap.usage.bytes            | Swap usage. Unit: B                |
```

2020-08-11 15:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| swap.free.bytes             | Swap free. Unit: bytes (b)                     |
```suggestion
| swap.free.bytes             | Swap free. Unit: B                    |
```

2020-08-11 15:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| swap.usage.percentage       | Swap usage in percentage. Unit: percentage (%) |
```suggestion
| swap.usage.percentage       | Swap usage in percentage. Unit: % |
```

2020-08-11 15:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| load1                       | Load average on 1 minute. Unit : percentage (%)    |
```suggestion
| load1                       | Load average on 1 minute.   |
```

2020-08-11 15:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| load5                       | Load average on 5 minutes. Unit : percentage (%)   |
```suggestion
| load5                       | Load average on 5 minutes.  |
```

2020-08-11 15:14 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| load15                      | Load average on 15 minutes. Unit : percentage (%)  |
```suggestion
| load15                      | Load average on 15 minutes. %  |
```

2020-08-11 15:14 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| uptime                      | Duration of system has been working and available. Unit : second (s)  |
```suggestion
| uptime                      | Duration of system has been working and available. Unit : s  |
```

2020-08-11 15:17 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| system.pgpgin.usage.bytespersecond     | Usage of the number of pgpgin in bytes per second. Unit : byte per second (b/s)   |
```suggestion
| system.pgpgin.usage.bytespersecond     | Usage of the number of pgpgin in Bytes per second. Unit: B/s   |
```

2020-08-11 15:17 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| system.pgpgout.usage.bytespersecond    | Usage of the number of pgpgout in bytes per second. Unit : byte per second (b/s)  |
```suggestion
| system.pgpgout.usage.bytespersecond    | Usage of the number of pgpgout in Bytes per second. Unit: B/s |
```

2020-08-11 15:18 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| system.pswpin.usage.bytespersecond     | Usage of the number of pswpin in bytes per second. Unit : byte per second (b/s)   |
```suggestion
| system.pswpin.usage.bytespersecond     | Usage of the number of pswpin in Bytes per second. Unit: B/s   |
```

2020-08-11 15:18 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| system.pswpout.usage.bytespersecond    | Usage of the number of pages in bytes per second. Unit : byte per second (b/s)    |
```suggestion
| system.pswpout.usage.bytespersecond    | Usage of the number of pages in Bytes per second. Unit: B/s |
```

2020-08-11 15:18 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| system.pgfault.usage.bytespersecond    | Usage pgfault in bytes per second. Unit : byte per second (b/s)                   |
```suggestion
| system.pgfault.usage.bytespersecond    | Usage pgfault in Bytes per second. Unit: B/s                  |
```

2020-08-11 15:18 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| system.pgmajfault.usage.bytespersecond | Usage pgmajfault in bytes per second. Unit : byte per second (b/s)                |
```suggestion
| system.pgmajfault.usage.bytespersecond | Usage pgmajfault in Bytes per second. Unit: B/s                          |
```

2020-08-11 15:19 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| used                        | Inodes space usage on partitions. Unit : percentage(%)  |
```suggestion
| used                        | Inodes space usage on partitions. Unit: %  |
```

2020-08-11 15:19 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| nbproc                      |  Number of current processes. Units: Count         |
```suggestion
| nbproc                      |  Number of current processes.         |
```

2020-08-11 15:19 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| offset                | Offset of ntpd service. Unit : milliseconds (ms)  |
```suggestion
| offset                | Offset of ntpd service. Unit: ms  |
```

2020-08-11 15:19 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| data_used             | Quota usage on partitions. Unit : bytes (b) |
```suggestion
| data_used             | Quota usage on partitions. Unit: B |
```

2020-08-11 15:19 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| used                  | Storage usages. Unit : bytes (b) |
```suggestion
| used                  | Storage usages. Unit: B |
```

2020-08-11 15:20 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| traffic               | Storage usages. Unit : bytes per second (b/s) |
traffic_in/traffic_out ?
La description ne correspond pas à la métrique.

2020-08-11 15:20 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +<!--Autentification Utilisateur/Mot de passe-->
Pas nécessaire, puisque tout est défini dans la partie configuration sur Centreon

2020-08-11 15:23 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +En ajoutant un nouvel hôte dans Centreon, appliquer le modèle d'hôte correspondant à votre type d'instance/cluster. Tous les modèles d'hôtes commencent par *Os-Linux-SSH-custom*.
```suggestion
Créer un nouvel hôte dans Centreon et lui appliquer le modèle d'hôte "OS-Linux-SSH-custom".
```

2020-08-11 15:24 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +Avec ce backend, vous n'avez pas à valider manuellement le fingerprint du serveur cible. Sympa :)
```suggestion
Avec ce backend, vous n'avez pas à valider manuellement le fingerprint du serveur cible. 
```

2020-08-24 12:28 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +### Règles de découvertes
Oki doki.
Done.

2020-08-24 12:29 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| traffic               | Storage usages. Unit : bytes per second (b/s) |
Nous avons mis status, traffic_in et traffic_out

2020-08-24 13:38 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +<!--Autentification Utilisateur/Mot de passe-->
La formulation a été changée afin d'expliquer les deux façons d'initier les vérifications.

2020-08-28 08:13 UTC, pkriko requested changes
As discussed, maybe you should force the new perfdata in the pack.

2020-08-28 08:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +## Contenu du pack de supervision
```suggestion
## Contenu du Plugin-Pack
```

2020-08-28 08:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +### Objets supervisés
```suggestion

### Objets supervisés

Ce Plugin-Pack est compatible avec n'importe quelle distribution Linux avec un daemon SSH installé :
```

2020-08-28 08:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| total_cpu             | Average total CPUs. Unit : %            |
Cpu detailed il y a que ces métriques ?

2020-08-28 08:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| device.io.utils.percentage             | IO utilization for  different usage type of CPU. Unit : ms   |
mauvaise unité.

2020-08-28 08:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| load15                      | Load average on 15 minutes. Unit : %  |
Pas d'unité pour la load ;-)

2020-08-28 08:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +    --plugin=os::linux::local::plugin \
```suggestion
      --plugin=os::linux::local::plugin \
```

2020-08-28 08:13 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +La commande ci-dessus donne la moyenne d'un CPU SSH Linux (```--mode=CPU```).
Expliquer peut être les options SSH ;-)

2020-08-28 08:18 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| interface.traffic.out.bitspersecond | Outgoing traffic going through the interface. Units: B/s & %     |
```suggestion
| interface.traffic.in.bitspersecond  | Incoming traffic going through the interface. Units: B/s    |
| interface.traffic.out.bitspersecond | Outgoing traffic going through the interface. Units: B/s     |
```

2020-08-28 13:09 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| total_cpu             | Average total CPUs. Unit : %            |
Comme vu cela été mis à jour.
* Per CPU :

| Metric name     | Description                           |
| :---------------| :------------------------------------ |
| cpu_user        | Average user for CPU. Unit : %       |
| cpu_nice		  | Average nice for CPU. Unit : %       |
| cpu_system	  | Average system for CPU. Unit : %     |
| cpu_idle		  | Average idle for CPU. Unit : %       |
| cpu_wait		  | Average wait for CPU. Unit : %       |
| cpu_interrupt	  | Average interrupt for CPU. Uni.t : %  |
| cpu_softirq	  | Average softirq for CPU. Unit : %    |
| cpu_steal       | Average steal for CPU. Unit : %      |
| cpu_guest       | Average guest for CPU. Unit : %      |
| cpu_guestnice   | Average guest nice for CPU. Unit : % |


* Total :
 
| Metric name              | Description                             |
| :----------------------- | :-------------------------------------- |
| total_cpu_guest_avg      | Total average guest CPU. Unit : %      |
| total_cpu_guestnice_avg  | Total average guest nice CPU. Unit : % |
| total_cpu_idle_avg	   | Total average idle CPU. Unit : %       |
| total_cpu_interrupt_avg  | Total average interrupt CPU. Unit : %  |
| total_cpu_nice_avg       | Total average nice CPU. Unit : %       |
| total_cpu_softirq_avg	   | Total average softirq CPU. Unit : %    |
| total_cpu_steal_avg      | Total average steal CPU. Unit : %      |
| total_cpu_system_avg     | Total average system CPU. Unit : %     |
| total_cpu_user_avg 	   | Total average user CPU. Unit : %       |
| total_cpu_wait_avg       | Total average wait CPU. Unit : %       |

2020-08-28 13:09 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| load15                      | Load average on 15 minutes. Unit : %  |
Done! ^^

2020-08-28 13:11 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
> +| device.io.utils.percentage             | IO utilization for  different usage type of CPU. Unit : ms   |
Done ^^

2020-08-31 15:25 UTC, pkriko approved these changes

2020-09-01 12:40 UTC, merged