doc(release): Prepare release notes for cloud release January 24.04
centreon/centreon-documentation pull request #2979
Opened 2024-01-19 15:37 UTC by pkippes

mon-34024
mon-34022
mon-34027

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] Cloud
- [ ] Monitoring Connectors

2024-01-19 17:33 UTC, nmagniezCentreon requested changes

2024-01-19 17:33 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
> +
### Centreon IT Edition

* **More configurations options for hosts and services**;

When configuring your hosts and services, you can now configure the interval between checks both when the resource is OK and when it is needed to validate a non-OK state. You can also configure the number of checks to validate a non-ok state before triggering and alert.
Finally, you can also  assign your resources with a dedicated icon to ease readability of the interface.

* **Dashboards Beta**:

As we keep improving our new proposition for effortlessly create and share intuitive dashboards, you can now benefit of multiple improvement, new widgets and bug fixes for the Centreon Dashboards feature.

2024-01-22 09:53 UTC, nmagniezCentreon requested changes

2024-01-22 09:53 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
> +- [Viewer] You can now perform delete and duplicate actions from the viewer.
PAs de more details. Seul ce que tu as appelé "highlights" doit être conservé, et le terme highlights doit aussi être supprimé

2024-02-23 16:49 UTC, nmagniezCentreon requested changes

2024-02-23 16:49 UTC, nmagniezCentreon commented on cloud/releases/cloud-release-notes.md
> +## January 22, 2024
mettre à jour la date: lundi 26 février

2024-02-23 16:49 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
> +## January 22, 2024
same same

2024-02-26 08:16 UTC, cg-tw commented on cloud/releases/cloud-release-notes.md
> +## January 22, 2024
```suggestion
## February 26, 2024
```

2024-02-26 08:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
> +## January 22, 2024
```suggestion
## February 26, 2024
```

2024-02-26 08:18 UTC, cg-tw approved these changes

2024-02-26 08:33 UTC, nmagniezCentreon approved these changes

2024-02-26 08:54 UTC, merged