enh(mc): update Azure AKS pack
centreon/centreon-documentation pull request #3009
Opened 2024-02-02 08:43 UTC by omercier

## Description

update Azure AKS pack

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-02-07 10:13 UTC, cg-tw requested changes

2024-02-07 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +## Contenu du pack
do we not keep the first section?

2024-02-07 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Health                | Cloud-Azure-Compute-Aks-Health-Api-custom                | Contrôle le statut du Cluster AKS                                               |
```suggestion
| Health                | Cloud-Azure-Compute-Aks-Health-Api-custom                | Contrôle le statut du cluster AKS                                               |
```

2024-02-07 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Memory                | Cloud-Azure-Compute-Aks-Memory-Api-custom                | Contrôle le taux d'utilisation mémoire du Cluster AKS                           |
```suggestion
| Memory                | Cloud-Azure-Compute-Aks-Memory-Api-custom                | Contrôle le taux d'utilisation mémoire du cluster AKS                           |
```

2024-02-07 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Pod-State             | Cloud-Azure-Compute-Aks-Pod-State-Api-custom             | Contrôle l'état des Pods du cluster AKS                                         |
```suggestion
| Pod-State             | Cloud-Azure-Compute-Aks-Pod-State-Api-custom             | Contrôle l'état des pods du cluster AKS                                         |
```

2024-02-07 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Storage               | Cloud-Azure-Compute-Aks-Storage-Api-custom               | Contrôle les statistiques de stockage du Cluster AKS                            |
```suggestion
| Storage               | Cloud-Azure-Compute-Aks-Storage-Api-custom               | Contrôle les statistiques de stockage du cluster AKS                            |
```

2024-02-07 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Unneeded-nodes        | Cloud-Azure-Compute-Aks-Unneeded-Nodes-Api-custom        | Contrôle du nombre de noeuds inutiles sur le Cluster AKS                        |
```suggestion
| Unneeded-nodes        | Cloud-Azure-Compute-Aks-Unneeded-Nodes-Api-custom        | Contrôle du nombre de noeuds inutiles sur le cluster AKS                        |
```

2024-02-07 10:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Allocatable-resources | Cloud-Azure-Compute-Aks-Allocatable-Resources-Api-custom | Check memory and CPU cores allocatable for AKS Cluster         |
```suggestion
| Allocatable-resources | Cloud-Azure-Compute-Aks-Allocatable-Resources-Api-custom | Check memory and CPU cores allocatable for AKS cluster         |
```

2024-02-07 10:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Health                | Cloud-Azure-Compute-Aks-Health-Api-custom                | Check AKS Cluster state                                        |
```suggestion
| Health                | Cloud-Azure-Compute-Aks-Health-Api-custom                | Check AKS cluster state                                        |
```

2024-02-07 10:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Memory                | Cloud-Azure-Compute-Aks-Memory-Api-custom                | Monitors the memory usage of the AKS Cluster                   |
```suggestion
| Memory                | Cloud-Azure-Compute-Aks-Memory-Api-custom                | Monitors the memory usage of the AKS cluster                   |
```

2024-02-07 10:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Pod-State             | Cloud-Azure-Compute-Aks-Pod-State-Api-custom             | Monitors the state of the AKS cluster Pods                     |
```suggestion
| Pod-State             | Cloud-Azure-Compute-Aks-Pod-State-Api-custom             | Monitors the state of the AKS cluster pods                     |
```

2024-02-07 10:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Traffic               | Cloud-Azure-Compute-Aks-Traffic-Api-custom               | Check AKS Cluster network usage                                |
```suggestion
| Traffic               | Cloud-Azure-Compute-Aks-Traffic-Api-custom               | Check AKS cluster network usage                                |
```

2024-02-07 10:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Unneeded-nodes        | Cloud-Azure-Compute-Aks-Unneeded-Nodes-Api-custom        | Check amount of unneeded nodes on AKS Cluster                  |
```suggestion
| Unneeded-nodes        | Cloud-Azure-Compute-Aks-Unneeded-Nodes-Api-custom        | Check amount of unneeded nodes on AKS cluster                  |
```

2024-02-07 10:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +| Unschedulable-Pods    | Cloud-Azure-Compute-Aks-Unschedulable-Pods-Api-custom    | Monitors the presence of unschedulable Pods on the AKS cluster |
```suggestion
| Unschedulable-Pods    | Cloud-Azure-Compute-Aks-Unschedulable-Pods-Api-custom    | Monitors the presence of unschedulable pods on the AKS cluster |
```

2024-02-09 13:35 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +## Contenu du pack
```suggestion
Azure Kubernetes Service (AKS) simplifie le déploiement d’un cluster Kubernetes managé en déléguant la charge opérationnelle à Azure. En tant que service Kubernetes hébergé, Azure gère des tâches critiques telles que l’analyse de l’intégrité et la maintenance.

Le connecteur de supervision Centreon *Azure Kubernetes Service* peut s'appuyer sur l'API d'Azure ou bien Azure CLI pour collecter les métriques relatives à AKS.

## Contenu du pack
```

2024-02-09 13:35 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
> +## Pack assets
```suggestion
Azure Kubernetes Service (AKS) simplifies deploying a managed Kubernetes cluster in Azure by offloading the operational overhead to Azure. As a hosted Kubernetes service, Azure handles critical tasks, like health monitoring and maintenance.

The Centreon Plugin *Azure Kubernetes Service* can rely on Azure API or Azure CLI to collect the metrics related to the *AKS* service.

## Pack assets
```

2024-02-09 13:54 UTC, merged