Feat(doc) update doc update centreon ha.md
centreon/centreon-documentation pull request #3015
Opened 2024-02-05 15:53 UTC by psamecentreon

## Description

Enhancement documentation for Centreon minor version update as part of Centreon HA

## Target version (i.e. version that this PR changes)

- [X] 22.04.x
- [X] 22.10.x
- [X] 23.04.x
- [X] 23.10.x
- [X] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-02-09 08:07 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md
> +sudo -u apache /usr/share/centreon/bin/console cache:clear
Pour le rafraichissement du cache il faut aussi prendre en compte Debian avec le compte www-data

2024-02-09 08:07 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md
> +```
Après suppression des crons il faut redémarrer le démon crond (ou cron sur debian)

2024-02-09 08:09 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:09 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-ha.md
> +```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:10 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-ha.md
>  ```
sur la HA c'est cbd-sql qu'il faut redémarrer

2024-02-09 08:10 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md
>  ```
sur la HA c'est cbd-sql qu'il faut redémarrer

2024-02-09 08:12 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:13 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-ha.md
> +```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:13 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-ha.md
>  ```
sur la HA c'est cbd-sql qu'il faut redémarrer

2024-02-09 08:14 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:14 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-ha.md
>  ```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:15 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-ha.md
>  ```
sur la HA c'est cbd-sql qu'il faut redémarrer

2024-02-09 08:15 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:16 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md
>  ```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:16 UTC, cedricmeschin commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md
>  ```
sur la HA c'est cbd-sql qu'il faut redémarrer

2024-02-09 08:16 UTC, cedricmeschin commented on versioned_docs/version-22.04/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:17 UTC, cedricmeschin commented on versioned_docs/version-22.04/update/update-centreon-ha.md
> +```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:20 UTC, cedricmeschin commented on versioned_docs/version-22.10/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:20 UTC, cedricmeschin commented on versioned_docs/version-22.10/update/update-centreon-ha.md
> +```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:21 UTC, cedricmeschin commented on versioned_docs/version-23.04/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:21 UTC, cedricmeschin commented on versioned_docs/version-23.04/update/update-centreon-ha.md
> +```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:22 UTC, cedricmeschin commented on versioned_docs/version-23.10/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:22 UTC, cedricmeschin commented on versioned_docs/version-23.10/update/update-centreon-ha.md
>  ```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:22 UTC, cedricmeschin commented on versioned_docs/version-24.04/update/update-centreon-ha.md
>  ```
Pour le rafraichissement du cache, il faut prendre en compte debian avec le compte www-data

2024-02-09 08:23 UTC, cedricmeschin commented on versioned_docs/version-24.04/update/update-centreon-ha.md
>  ```
redémarrage de crond (ou cron sur debian) pour prise en compte

2024-02-09 08:25 UTC, cedricmeschin requested changes
Ajouter la gestion de purge du cache pour debian (www-data)
redémarrage de cbd-sql en lieu et place de cbd sur le central

2024-02-12 17:21 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md
> +sudo -u apache /usr/share/centreon/bin/console cache:clear
Done ^^

2024-02-12 17:22 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md
> +```
Added ^^

2024-02-12 17:23 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-ha.md
>  ```
Done ^^

2024-02-12 17:24 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md
>  ```
Mais c'est bien cbd sur les RS ^^

2024-02-12 17:25 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-ha.md
>  ```
Done! ^^

2024-02-12 17:25 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-ha.md
>  ```
Done ^^

2024-02-12 17:26 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-ha.md
>  ```
done!

2024-02-12 17:26 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-ha.md
>  ```
cbd sur les RS

2024-02-12 17:27 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md
>  ```
Added! ^^

2024-02-12 17:27 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md
>  ```
Done ^^

2024-02-12 17:27 UTC, psamecentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md
>  ```
cbd sur les RS

2024-02-12 17:27 UTC, psamecentreon commented on versioned_docs/version-22.04/update/update-centreon-ha.md
>  ```
Done ^^

2024-02-12 17:28 UTC, psamecentreon commented on versioned_docs/version-22.04/update/update-centreon-ha.md
> +```
Added ^^

2024-02-12 17:28 UTC, psamecentreon commented on versioned_docs/version-22.10/update/update-centreon-ha.md
>  ```
Changed ^^

2024-02-12 17:28 UTC, psamecentreon commented on versioned_docs/version-22.10/update/update-centreon-ha.md
> +```
Changed

2024-02-12 17:28 UTC, psamecentreon commented on versioned_docs/version-23.04/update/update-centreon-ha.md
>  ```
Added ^^

2024-02-12 17:29 UTC, psamecentreon commented on versioned_docs/version-24.04/update/update-centreon-ha.md
>  ```
Done ^^

2024-02-12 17:29 UTC, psamecentreon commented on versioned_docs/version-24.04/update/update-centreon-ha.md
>  ```
Changed ^^

2024-02-12 17:30 UTC, psamecentreon commented on versioned_docs/version-23.10/update/update-centreon-ha.md
>  ```
Done ^^

2024-02-12 17:31 UTC, psamecentreon commented on versioned_docs/version-23.10/update/update-centreon-ha.md
>  ```
done ^^

2024-02-12 17:31 UTC, psamecentreon commented on versioned_docs/version-23.04/update/update-centreon-ha.md
> +```
Changed ^^

2024-03-01 09:06 UTC, cedricmeschin approved these changes

2024-03-01 10:53 UTC, cedricmeschin approved these changes

2024-03-01 13:12 UTC, merged