feat(monitoring-connector) add documentation for Datacore new plugin …
centreon/centreon-documentation pull request #3107
Opened 2024-03-07 09:34 UTC by Evan-Adam

## Description

Documentation of new Datacore plugin pack

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [X] Monitoring Connectors

2024-03-08 14:55 UTC, cg-tw requested changes

2024-03-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| Monitors Status | HW-Storage-Datacore-Sansymphony-Status-Monitor-RESTAPI-custom | Contrôle le status des éléments filtré en paramètres |
```suggestion
| Monitors Status | HW-Storage-Datacore-Sansymphony-Status-Monitor-RESTAPI-custom | Contrôle le statut des éléments filtrés en paramètres |
```

2024-03-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| Datacore-Sansymphony-Restapi-Pool | découvre les identifiant de pools disponible sur le serveur Datacore Sansymphony via l'api Rest |
```suggestion
| Datacore-Sansymphony-Restapi-Pool | Découvre les identifiants de pools disponibles sur le serveur Datacore Sansymphony via l'API Rest |
```

2024-03-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
sample text

2024-03-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| APIPROTO        | HTTP protocol, either http or https.                                                                                                               | https             |
```suggestion
| APIPROTO        | Either HTTP or HTTPS.                                                                                                               | https             |             |
```

2024-03-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| MAXALERTAGE     | filter alerts to check those newer than this parameter (s)                                                                                                     | 86400
```suggestion
| MAXALERTAGE     | Filter alerts to check those newer than this parameter (s)                                                                                                     | 86400             |             |
```

2024-03-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| FILTERSERVER    | Define which devices should be monitored based on the MachineName. This option will be treated as a regular expression. By default all machine will be checked |
```suggestion
| FILTERSERVER    | Define which devices should be monitored based on the MachineName. This option will be treated as a regular expression. By default all machines will be checked |                   |             |
```

2024-03-08 14:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| FILTERSERVER    | Define which devices should be monitored based on the MachineName. This option will be treated as a regular expression. By default all machine will be checked |
Is MachineName a parameter?

2024-03-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| Monitors Status | HW-Storage-Datacore-Sansymphony-Status-Monitor-RESTAPI-custom | Check elements filtered by parameters |
unclear

2024-03-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| Datacore-Sansymphony-Restapi-Pool | discover pools id from your Datacore Sansymphony rest api. |
```suggestion
| Datacore-Sansymphony-Restapi-Pool | Discover the IDs of the pools from your Datacore Sansymphony Rest API. |
```

2024-03-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +
sample text

2024-03-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| FILTERSERVER    | Define which devices sh ould be monitored based on the MachineName. This option willbe treated as a regular expression. By default all machine will be checked |
```suggestion
| FILTERSERVER    | Define which devices should be monitored based on the MachineName. This option will be treated as a regular expression. By default all machines will be checked. |                   |             |
```

2024-03-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| FILTERSERVER    | Define which devices sh ould be monitored based on the MachineName. This option willbe treated as a regular expression. By default all machine will be checked |
same comment as in FR

2024-03-08 14:55 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| WARNINGWARNING  | thresholds                                                                                                                                                      |
Capital T for all instances of "threshold" (and it should be threshold in the singular, shouldn't it?)

2024-03-11 09:28 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +Configure Datacore Rest Api : https://docs.datacore.com/RESTSupport-WebHelp/RESTSupport-WebHelp/Installation_Instructions.htm
```suggestion
To be able to monitor Datacore SANsymphony, you must configure an [access to the REST API](https://docs.datacore.com/RESTSupport-WebHelp/RESTSupport-WebHelp/Installation_Instructions.htm).
```

2024-03-11 09:28 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +Configurer l'Api Datacore Rest : https://docs.datacore.com/RESTSupport-WebHelp/RESTSupport-WebHelp/Installation_Instructions.htm
```suggestion
Pour pouvoir superviser Datacore SANsymphony, il vous faut [configurer l'API REST Datacore](https://docs.datacore.com/RESTSupport-WebHelp/RESTSupport-WebHelp/Installation_Instructions.htm).
```

2024-03-11 09:37 UTC, omercier approved these changes

2024-03-11 10:18 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +| Monitors Status | HW-Storage-Datacore-Sansymphony-Status-Monitor-RESTAPI-custom | Check Datacore "monitors" object filtered by parameters |
```suggestion
| Monitors-Status | HW-Storage-Datacore-Sansymphony-Status-Monitor-RESTAPI-custom | Monitor Datacore "monitors" object. |
```

2024-03-11 10:18 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
> +<TabItem value="Monitors Status" label="Monitors Status">
```suggestion
<TabItem value="Monitors-Status" label="Monitors-Status">
```

2024-03-11 10:22 UTC, cg-tw approved these changes

2024-03-11 10:36 UTC, merged