MBI monitoring procedure v2
centreon/centreon-documentation pull request #311
Opened 2020-08-20 14:04 UTC by itoussies

2020-08-26 08:15 UTC, pkriko requested changes
Maybe we're going to wait the return of @Sims24.
What are your thoughts @thibaults-centreon ?

2020-08-26 08:15 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-monitoring-centreon-mbi.md
> +### NRPE3
Maybe for the NRPE3, simply add link to the NRPE3 monitoring procedure and just add the part :
```
Futhermore, add the following lines at the end of the file:

command[check_partitions]=/usr/share/centreon-bi/etl/centreonbiMonitoring.pl --partitions
command[check_db]=/usr/share/centreon-bi/etl/centreonbiMonitoring.pl --db-content
command[check_jobs]=/usr/share/centreon-bi/etl/centreonbiMonitoring.pl --jobs
```

2020-08-26 08:15 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-monitoring-centreon-mbi.md
> +### SNMP
Same remark for SNMP, maybe just add link to send the user on the Linux SNMP monitoring Proc.

2020-08-26 08:15 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-monitoring-centreon-mbi.md
> +### Collected metrics
Missing metrics/services from MBI pack :)

2020-08-26 08:15 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-monitoring-centreon-mbi.md
> +### Métriques collectées
Missing metrics/services from MBI pack

2020-08-26 08:15 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-monitoring-centreon-mbi.md
> +### SNMP
Maybe add link to send the user on the Linux SNMP Monitoring Proc.

2020-08-26 08:15 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-monitoring-centreon-mbi.md
> +### NRPE3
Maybe add link to send the user on the Linux NRPE3 Monitoring Proc and add just the necessary configuration:
```
command[check_partitions]=/usr/share/centreon-bi/etl/centreonbiMonitoring.pl --partitions
command[check_db]=/usr/share/centreon-bi/etl/centreonbiMonitoring.pl --db-content
command[check_jobs]=/usr/share/centreon-bi/etl/centreonbiMonitoring.pl --jobs
```

2020-08-26 08:35 UTC, thibaults-centreon commented
In the former version of the documentation, all of the configuration information was embedded in only one procedure, which was pretty handy. 
But keeping this format kinda conflicts with the way we now want to focus only on the Plugin-Packs assets in the monitoring procedures.
This should indeed be discussed with @Sims24 to make the call.

2020-10-16 15:44 UTC, Sims24 commented
Sorry but we will rework this. Let's talk about it internally to make the right decisions.

2020-10-16 15:44 UTC, closed without merging