enh(mc): automatic commit - Open LDAP
centreon/centreon-documentation pull request #3113
Opened 2024-03-11 14:04 UTC by omercier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-03-12 13:04 UTC, cg-tw requested changes

2024-03-12 13:04 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-openldap-ldap.md
>  password dedicated to monitoring is needed for security reasons.
```suggestion
password dedicated to monitoring are needed for security reasons.
```

2024-03-15 15:49 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-openldap-ldap.md
> +| System-Usage | App-Openldap-System-Usage-LDAP-custom | Contrôler l'utilisation du Système OpenLDAP via LDAP Protocol |
Je crois ce [LDAP](https://fr.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol) là daprès la page wiki [OpenLDAP](https://fr.wikipedia.org/wiki/OpenLDAP)

2024-03-26 16:47 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-openldap-ldap.md
> +| System-Usage | App-Openldap-System-Usage-LDAP-custom | Contrôler l'utilisation du Système OpenLDAP via LDAP Protocol |
```suggestion
| System-Usage | App-Openldap-System-Usage-LDAP-custom | Contrôler l'utilisation du système OpenLDAP via le protocole LDAP |
```

2024-03-26 16:47 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-openldap-ldap.md
> +| System-Usage  | App-Openldap-System-Usage-LDAP-custom | Check System Usage of OpenLDAP using LDAP |
```suggestion
| System-Usage  | App-Openldap-System-Usage-LDAP-custom | Monitor system usage of OpenLDAP using the LDAP protocol |
```

2024-03-26 16:52 UTC, omercier commented on pp/integrations/plugin-packs/procedures/applications-openldap-ldap.md
> +| System-Usage  | App-Openldap-System-Usage-LDAP-custom | Check system usage of OpenLDAP using LDAP |
```suggestion
| System-Usage  | App-Openldap-System-Usage-LDAP-custom | Check system usage of OpenLDAP using the LDAP protocol |
```

2024-03-26 16:53 UTC, cg-tw approved these changes

2024-03-26 17:15 UTC, merged