enh(mc): automatic commit for network-cisco-wap-snmp
centreon/centreon-documentation pull request #3117
Opened 2024-03-11 15:57 UTC by omercier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-03-11 16:17 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
> +## Contenu du pack
```suggestion
Cisco est un fournisseur de solutions réseau.

Le connecteur de supervision *Cisco Wap SNMP* utilise le protocole SNMP pour se connecter, récupérer des informations et les métriques relatives aux point d'accès de marque Cisco.

## Contenu du pack
```

2024-03-11 16:17 UTC, omercier commented on pp/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
> +## Pack assets
```suggestion
Cisco  is a provider of network solutions.

The Centreon Monitoring Connector *Cisco Wap SNMP* relies on the SNMP protocol to query and collect the status and metrics of the Cisco Wireless Access Point equipment.

## Pack assets
```

2024-03-12 09:59 UTC, cg-tw requested changes

2024-03-12 09:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
> +| Virtual Access Points | Net-Cisco-Wap-Virtual-Access-Point-SNMP-custom | Contrôle les points d'accès virtuel                         |
```suggestion
| Virtual Access Points | Net-Cisco-Wap-Virtual-Access-Point-SNMP-custom | Contrôle les points d'accès virtuels                         |
```

2024-03-12 09:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
> +| Net-Cisco-Wap-SNMP-Interface-Name | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Cisco-Wap-SNMP-Interface-Name | Découvre les interfaces réseau et supervise le statut et l'utilisation |
```

2024-03-12 09:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
>  The Centreon Monitoring Connector *Cisco Wap SNMP* relies on the SNMP protocol to query and collect the status and metrics of the Cisco Wireless Access Point equipment.
```suggestion
The Centreon Monitoring Connector *Cisco Wap SNMP* relies on the SNMP protocol to query and collect the status and metrics of Cisco Wireless Access Point devices.
```

2024-03-12 09:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
>  Le connecteur de supervision *Cisco Wap SNMP* utilise le protocole SNMP pour se connecter, récupérer des informations et les métriques relatives aux point d'accès de marque Cisco.
c'est des appareils qui s'appellent Wireless Access Point? (cf version anglaise)

2024-03-12 09:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
>  The SNMP agent must be configured and running. Please refer to the manufacturer documentation to achieve this.
1. I think this is not the standard text, is it?
2. FR and EN are different

2024-03-26 16:58 UTC, omercier commented on pp/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
>  The SNMP agent must be configured and running. Please refer to the manufacturer documentation to achieve this.
```suggestion
The SNMP service must be configured and activated on the host. Please refer to the official documentation from the manufacturer/publisher.

```

2024-03-26 16:58 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
>  Le connecteur de supervision *Cisco Wap SNMP* utilise le protocole SNMP pour se connecter, récupérer des informations et les métriques relatives aux point d'accès de marque Cisco.
```suggestion
Le connecteur de supervision *Cisco WAP SNMP* utilise le protocole SNMP pour se connecter, récupérer des informations et les métriques relatives aux point d'accès de marque Cisco.
```

2024-03-26 17:16 UTC, cg-tw approved these changes

2024-03-26 17:17 UTC, merged