enh(mc): automatic commit for network-routers-juniper-mseries-snmp
centreon/centreon-documentation pull request #3124
Opened 2024-03-11 15:59 UTC by omercier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-03-12 10:52 UTC, cg-tw requested changes

2024-03-12 10:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| Memory-Routing | Net-Juniper-Mseries-Memory-Routing-custom | Contrôle l'utilisation mémoire du 'Routing Engine' |
```suggestion
| Memory-Routing | Net-Juniper-Mseries-Memory-Routing-custom | Contrôle l'utilisation mémoire du 'routing engine' |
```

2024-03-12 10:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| Bgp-Peer-Prefix-Statistics | Net-Juniper-Mseries-SNMP-Bgp-Peer-Prefix-Statistics-custom | Contrôle les statistiques des prefix des pairs BGP
```suggestion
| Bgp-Peer-Prefix-Statistics | Net-Juniper-Mseries-SNMP-Bgp-Peer-Prefix-Statistics-custom | Contrôle les statistiques des préfixes des pairs BGP                                                               |            |
```

2024-03-12 10:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| Net-Juniper-Mseries-Storage-Name | Discover the disk partitions and monitor space occupation               |
English + French?

2024-03-12 10:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| Net-Juniper-Mseries-Traffic-Name | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Juniper-Mseries-Traffic-Name | Découvre les interfaces réseau et supervise le statut et l'utilisation |
```

2024-03-12 10:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| Cpu-Routing    | Net-Juniper-Mseries-Cpu-Routing-custom    | Check CPU Usage of routing engine    |
```suggestion
| Cpu-Routing    | Net-Juniper-Mseries-Cpu-Routing-custom    | Check CPU usage of routing engine    |
```

2024-03-12 10:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| Memory-Routing | Net-Juniper-Mseries-Memory-Routing-custom | Check Memory Usage of routing engine |
```suggestion
| Memory-Routing | Net-Juniper-Mseries-Memory-Routing-custom | Check memory usage of routing engine |
```

2024-03-12 10:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| Traffic-Global             | Net-Juniper-Mseries-Traffic-Global-custom                  | Check the bandwidth of  interfaces. For each checks the name of the interface will appear    | X          |
```suggestion
| Traffic-Global             | Net-Juniper-Mseries-Traffic-Global-custom                  | Check the bandwidth of the interfaces. For each checks the name of the interface will appear    | X          |
```

2024-03-12 10:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| FILTERREMOTEIP | Filter by remote ip address (can be regexp)
```suggestion
| FILTERREMOTEIP | Filter by remote IP address (can be regexp)                                                                                                                                                                                                                                                                              |                                                                 |             |
```

2024-03-19 16:56 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
> +| Net-Juniper-Mseries-Storage-Name | Discover the disk partitions and monitor space occupation               |
```suggestion
| Net-Juniper-Mseries-Storage-Name | Découvre les partitions des disques et supervise leur taux d'occupation        |
```

2024-03-19 17:17 UTC, merged