enh(mc): automatic commit for network-switchs-juniper-ex-snmp
centreon/centreon-documentation pull request #3129
Opened 2024-03-11 16:00 UTC by omercier

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-03-12 09:13 UTC, cg-tw requested changes

2024-03-12 09:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Memory-Routing | Net-Juniper-Ex-Memory-Routing-custom | Contrôle l'utilisation mémoire du 'Routing Engine' |
```suggestion
| Memory-Routing | Net-Juniper-Ex-Memory-Routing-custom | Contrôle l'utilisation mémoire du 'routing engine' |
```

2024-03-12 09:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Net-Juniper-Ex-Storages-Name | Discover the disk partitions and monitor space occupation               |
why one in English and one in French?

2024-03-12 09:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Net-Juniper-Ex-Traffic-Name  | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Juniper-Ex-Traffic-Name  | Découvre les interfaces réseau et supervise le statut et l'utilisation |
```

2024-03-12 09:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| FILTER          | Filter operating (default: 'routing\|fpc')                                                         | routing           |             |
filter operating what?

2024-03-12 09:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Cpu-Routing    | Net-Juniper-Ex-Cpu-Routing-custom    | Check CPU Usage of routing engine    |
```suggestion
| Cpu-Routing    | Net-Juniper-Ex-Cpu-Routing-custom    | Check CPU usage of routing engine    |
```

2024-03-12 09:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Memory-Routing | Net-Juniper-Ex-Memory-Routing-custom | Check Memory Usage of routing engine |
```suggestion
| Memory-Routing | Net-Juniper-Ex-Memory-Routing-custom | Check memory usage of routing engine |
```

2024-03-12 09:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Traffic-Generic-Id   | Net-Juniper-Ex-Traffic-Generic-Id-custom   | Check the bandwidth of the interface. For each checks the name of the interface will appear  |            |
```suggestion
| Traffic-Generic-Id   | Net-Juniper-Ex-Traffic-Generic-Id-custom   | Check the bandwidth of the interface. For each check the name of the interface will appear  |            |
```

2024-03-12 09:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Traffic-Generic-Name | Net-Juniper-Ex-Traffic-Generic-Name-custom | Check the bandwidth of the interface. For each checks the name of the interface will appear  |            |
```suggestion
| Traffic-Generic-Name | Net-Juniper-Ex-Traffic-Generic-Name-custom | Check the bandwidth of the interface. For each check the name of the interface will appear  |            |
```

2024-03-12 09:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Traffic-Global       | Net-Juniper-Ex-Traffic-Global-custom       | Check the bandwidth of  interfaces. For each checks the name of the interface will appear    | X          |
```suggestion
| Traffic-Global       | Net-Juniper-Ex-Traffic-Global-custom       | Check the bandwidth of  interfaces. For each check the name of the interface will appear    | X          |
```

2024-03-12 15:07 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| FILTER          | Filter operating (default: 'routing\|fpc')                                                         | routing           |             |
```suggestion
| FILTER          | Define which elements should be monitored based on their name. This option will be treated as a regular expression. 'routing\|fpc' is applied if left empty.   | routing           |             |
```

2024-03-12 15:07 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Net-Juniper-Ex-Storages-Name | Discover the disk partitions and monitor space occupation               |
```suggestion
| Net-Juniper-Ex-Storages-Name | Découvre les disques pour en faciliter la mise en supervision.               |
```

2024-03-12 15:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
> +| Memory-Routing | Net-Juniper-Ex-Memory-Routing-custom | Contrôle l'utilisation mémoire du 'Routing Engine' |
In that case you should have the capital letters everywhere and not just on that line

2024-03-19 16:45 UTC, cg-tw approved these changes

2024-03-19 17:14 UTC, merged