doc(release): prepare release notes for OSS 23.10
centreon/centreon-documentation pull request #3135
Opened 2024-03-12 15:52 UTC by pkippes

"web 23.10.10
gorgone 23.10.4"

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-03-12 16:04 UTC, cg-tw requested changes

2024-03-12 16:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [CLAPI] Fixed a decoding issue on HTML entities export.
```suggestion
- [CLAPI] Fixed a decoding issue affecting the export of HTML entities.
```

2024-03-12 16:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [CLAPI] While exporting services and hosts, duplicates were generated.
```suggestion
- [CLAPI] Duplicates are no longer generated when exporting services and hosts.
```

2024-03-12 16:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [API] Fixed a visibility issue on UserFilter endpoint.
```suggestion
- [API] Fixed a visibility issue with the UserFilter endpoint.
```

2024-03-12 16:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Resource Status] Improved update of filters by removing useless dialog
```suggestion
- [Resource Status] Improved the update of filters by removing unnecessary dialog box.
```

2024-03-12 16:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Dashboards - Map widget] Fixed Map, Geoview and perspective save.
To be improved

2024-03-12 16:09 UTC, rsadik-ext approved these changes

2024-03-12 16:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Dashboards - Map widget] Fixed Map, Geoview and perspective save.
```suggestion
- [Dashboards - Map widget] Fixed an issue where Map, Geoview and perspectives couldn't be saved.
```

2024-03-12 16:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Dashboards - Map widget] Fixed an issue where Map, Geoview and perspectives couldn't be saved.
```suggestion
- [Dashboards - Map widget] Fixed an issue where Maps, Geoviews and perspectives couldn't be saved.
```

2024-03-12 16:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Resource Status] Improved the update of filters by removing unnecessary dialog box.
```suggestion
- [Resource Status] Improved the update of filters by removing an unnecessary dialog box.
```

2024-03-12 16:15 UTC, cg-tw requested changes

2024-03-12 16:15 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +</details>
```suggestion
<details open>
  <summary>Enhancements</summary>

- [Resource Status] Improved the update of filters by removing an unnecessary dialog box.

</details>

<details>
  <summary>Bug fixes</summary>

- [Authentication] Fixed issue with SSO authentication.
- [API] Fixed a visibility issue with the UserFilter endpoint.
- [API] Fixed an issue where an error 500 was returned when a host had no alias.
- [CLAPI] Fixed a decoding issue affecting the export of HTML entities.
- [CLAPI] Duplicates are no longer generated when exporting services and hosts.
- [Dashboards - Map widget] Fixed an issue where Maps, Geoviews and perspectives couldn't be saved.

</details>

<details open>
  <summary>Security fixes</summary>

- [Security] Improved allowed commands for Centreon Gorgone.

</details>
```

2024-03-12 16:15 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Packaging] Fixed missing perl dependency for centreon-web installation on debian 11.
```suggestion
- Added the Auto Discovery patterns to the default commands whitelist.
- Improved list of allowed commands for Auto Discovery.
- [Packaging] Fixed missing perl dependency for centreon-web installation on Debian 11.
```

2024-03-12 16:16 UTC, cg-tw approved these changes

2024-03-13 08:52 UTC, rsadik-ext approved these changes

2024-03-13 08:54 UTC, rsadik-ext approved these changes

2024-03-13 08:55 UTC, rsadik-ext approved these changes

2024-03-14 14:23 UTC, merged