Add MAP Upgrade topic
centreon/centreon-documentation pull request #3167
Opened 2024-03-22 10:23 UTC by smau-centreon

## Description

Add MAP Upgrade topic

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-02 14:28 UTC, Jordan9131 submitted a review, later dismissed

2024-04-26 07:32 UTC, Jordan9131 requested changes

2024-04-26 07:42 UTC, Jordan9131 approved these changes

2024-04-26 11:40 UTC, Jordan9131 approved these changes

2024-04-30 12:57 UTC, cg-tw requested changes

2024-04-30 12:57 UTC, cg-tw commented on versioned_docs/version-22.10/graph-views/map-web-upgrade.md
> +> repository.
```suggestion
> If you're updating to a new major version (i.e: A.B.x with A or B that
> changes) you need to install the new Business
> repository. You can find its address on the [support portal](https://support.centreon.com/hc/en-us/categories/10341239833105-Repositories).
```

2024-04-30 12:57 UTC, cg-tw commented on versioned_docs/version-24.04/graph-views/map-web-upgrade.md
> +> repository.
```suggestion
> If you're updating to a new major version (i.e: A.B.x with A or B that
> changes) you need to install the new Business
> repository. You can find its address on the [support portal](https://support.centreon.com/hc/en-us/categories/10341239833105-Repositories).
```

2024-04-30 12:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-upgrade.md
> +le support pour récupérer l'adresse du nouveau dépôt.
```suggestion
> Lorsque vous mettez à jour une nouvelle version majeure (c'est à dire version A.B.x avec A ou B qui évolue), vous devez installer le nouveau dépôt Business. Vous pouvez trouver l'adresse du dépôt sur le [portail support Centreon](https://support.centreon.com/hc/fr/categories/10341239833105-D%C3%A9p%C3%B4ts).
```

2024-04-30 12:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-upgrade.md
> +le support pour récupérer l'adresse du nouveau dépôt.
```suggestion
> Lorsque vous mettez à jour une nouvelle version majeure (c'est à dire version A.B.x avec A ou B qui évolue), vous devez installer le nouveau dépôt Business. Vous pouvez trouver l'adresse du dépôt sur le [portail support Centreon](https://support.centreon.com/hc/fr/categories/10341239833105-D%C3%A9p%C3%B4ts).
```

2024-04-30 12:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-upgrade.md
> +le support pour récupérer l'adresse du nouveau dépôt.
```suggestion
> Lorsque vous mettez à jour une nouvelle version majeure (c'est à dire version A.B.x avec A ou B qui évolue), vous devez installer le nouveau dépôt Business. Vous pouvez trouver l'adresse du dépôt sur le [portail support Centreon](https://support.centreon.com/hc/fr/categories/10341239833105-D%C3%A9p%C3%B4ts).
```

2024-04-30 12:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-upgrade.md
> +le support pour récupérer l'adresse du nouveau dépôt.
```suggestion
> Lorsque vous mettez à jour une nouvelle version majeure (c'est à dire version A.B.x avec A ou B qui évolue), vous devez installer le nouveau dépôt Business. Vous pouvez trouver l'adresse du dépôt sur le [portail support Centreon](https://support.centreon.com/hc/fr/categories/10341239833105-D%C3%A9p%C3%B4ts).
```

2024-04-30 12:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-upgrade.md
> +le support pour récupérer l'adresse du nouveau dépôt.
```suggestion
> Lorsque vous mettez à jour une nouvelle version majeure (c'est à dire version A.B.x avec A ou B qui évolue), vous devez installer le nouveau dépôt Business. Vous pouvez trouver l'adresse du dépôt sur le [portail support Centreon](https://support.centreon.com/hc/fr/categories/10341239833105-D%C3%A9p%C3%B4ts).
```

2024-04-30 13:13 UTC, Jordan9131 submitted a review, later dismissed

2024-04-30 13:20 UTC, Jordan9131 submitted a review, later dismissed

2024-04-30 13:24 UTC, cg-tw commented
Approved because I have to since I requested changes, but I did not review the whole PR.

2024-04-30 13:24 UTC, cg-tw approved these changes

2024-04-30 15:07 UTC, merged