add(mc): new cloud-azure-database-postgresql MC
centreon/centreon-documentation pull request #3173
Opened 2024-03-26 08:57 UTC by omercier

## Description

New Monitoring Connector

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-04-08 09:58 UTC, cg-tw requested changes

2024-04-08 09:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +> Paramétrez les options suivantes dans la macro EXTRAOPTIONS si vous superviser des ressources Microsoft Azure géré par 21Vianet (Azure China):
```suggestion
> Paramétrez les options suivantes dans la macro EXTRAOPTIONS si vous souhaitez superviser des ressources Microsoft Azure gérées par 21Vianet (Azure China):
```

2024-04-08 09:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| WARNINGSERVERLOGUSAGE  | Thresholds where '*'                                                                               |                   |             |
where what?

2024-04-08 09:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| WARNINGTRAFFICIN   | Thresholds where '*'                                                                               |                   |             |
where what?

2024-04-08 09:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| Connections    | Cloud-Azure-Database-PostgreSQL-Connections-Api-custom    | Monitor Azure Database for PostgreSQL connections statistics |
```suggestion
| Connections    | Cloud-Azure-Database-PostgreSQL-Connections-Api-custom    | Monitor Azure Database for PostgreSQL connection statistics |
```

2024-04-08 09:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| Connections    | Cloud-Azure-Database-PostgreSQL-Connections-Api-custom    | Contrôle les statistiques de connexions de l'instance Azure Database for PostgreSQL |
```suggestion
| Connections    | Cloud-Azure-Database-PostgreSQL-Connections-Api-custom    | Contrôle les statistiques de connexion de l'instance Azure Database for PostgreSQL |
```

2024-04-08 09:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +> Set the following options in the EXTRAOPTIONS macro if you are monitoring resource from Microsoft Azure operated by 21Vianet (Azure China):
```suggestion
> Set the following options in the EXTRAOPTIONS macro if you are monitoring resources from Microsoft Azure operated by 21Vianet (Azure China):
```

2024-04-08 09:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| WARNINGSERVERLOGUSAGE  | Thresholds where '*'                                                                               |                   |             |
where what?

2024-04-08 09:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| WARNINGTRAFFICIN   | Thresholds where '*'                                                                               |                   |             |
where what?

2024-04-08 09:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +	--subscription='' \
dummy values for mandatory parameters?

2024-04-08 09:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +	--subscription='' \
dummy values for mandatory parameters?

2024-04-08 11:31 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| CRITICALSTORAGEUSED    | Thresholds where '*'                                                                               |                   |             |
```suggestion
| WARNINGSERVERLOGUSAGE  | Thresholds                                                                               |                   |             |
| CRITICALSERVERLOGUSAGE | Thresholds                                                                               |                   |             |
| WARNINGSTORAGEBACKUP   | Thresholds                                                                              |                   |             |
| CRITICALSTORAGEBACKUP  | Thresholds                                                                               |                   |             |
| WARNINGSTORAGEPERCENT  | Thresholds                                                                               |                   |             |
| CRITICALSTORAGEPERCENT | Thresholds                                                                               |                   |             |
| WARNINGSTORAGEUSED     | Thresholds                                                                                |                   |             |
| CRITICALSTORAGEUSED    | Thresholds                                                                                |                   |             |
```

2024-04-08 11:31 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| CRITICALTRAFFICOUT | Thresholds where '*'                                                                               |                   |             |
```suggestion
| WARNINGTRAFFICIN   | Thresholds                                                                                 |                   |             |
| CRITICALTRAFFICIN  | Thresholds                                                                                 |                   |             |
| WARNINGTRAFFICOUT  | Thresholds                                                                                |                   |             |
| CRITICALTRAFFICOUT | Thresholds                                                                                |                   |             |
```

2024-04-08 11:31 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| Connections    | Cloud-Azure-Database-PostgreSQL-Connections-Api-custom    | Monitor Azure Database for PostgreSQL connections statistics |
On ne teste pas la connexion, mais on donne des stats sur le nombre de connexions

2024-04-08 11:31 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| CRITICALSTORAGEUSED    | Thresholds where '*'                                                                               |                   |             |
```suggestion
| WARNINGSERVERLOGUSAGE  | Thresholds                                                                                  |                   |             |
| CRITICALSERVERLOGUSAGE | Thresholds                                                                                 |                   |             |
| WARNINGSTORAGEBACKUP   | Thresholds                                                                                 |                   |             |
| CRITICALSTORAGEBACKUP  | Thresholds                                                                                 |                   |             |
| WARNINGSTORAGEPERCENT  | Thresholds                                                                                |                   |             |
| CRITICALSTORAGEPERCENT | Thresholds                                                                                 |                   |             |
| WARNINGSTORAGEUSED     | Thresholds                                                                                   |                   |             |
| CRITICALSTORAGEUSED    | Thresholds                                                                                 |                   |             |
```

2024-04-08 11:31 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| CRITICALTRAFFICOUT | Thresholds where '*'                                                                               |                   |             |
```suggestion
| WARNINGTRAFFICIN   | Thresholds                                                                                |                   |             |
| CRITICALTRAFFICIN  | Thresholds                                                                                 |                   |             |
| WARNINGTRAFFICOUT  | Thresholds                                                                                |                   |             |
| CRITICALTRAFFICOUT | Thresholds                                                                                |                   |             |
```

2024-04-08 11:33 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +	--client-secret='' \
```suggestion
	--subscription='xxxxxxxxxxxxxx' \
	--tenant='xxxxxxxxxxxxxx' \
	--client-id='xxxxxxxxxxxxxx' \
	--client-secret='xxxxxxxxxxxxxx' \
```

2024-04-08 11:33 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +	--client-secret='' \
```suggestion
	--subscription='xxxxxxxxxxxxxx' \
	--tenant='xxxxxxxxxxxxxx' \
	--client-id='xxxxxxxxxxxxxx' \
	--client-secret='xxxxxxxxxxxxxx' \
```

2024-04-09 08:03 UTC, cg-tw requested changes

2024-04-09 08:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md
> +| Connections    | Cloud-Azure-Database-PostgreSQL-Connections-Api-custom    | Monitor Azure Database for PostgreSQL connections statistics |
```suggestion
| Connections    | Cloud-Azure-Database-PostgreSQL-Connections-Api-custom    | Monitor the number of connections to the Azure PostgreSQL Database |
```

2024-04-09 08:03 UTC, cg-tw approved these changes

2024-04-09 08:47 UTC, merged