add(mc): new applications-veeam-wsman MC
centreon/centreon-documentation pull request #3174
Opened 2024-03-26 09:16 UTC by omercier

## Description

New MC

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-04-08 09:48 UTC, cg-tw requested changes

2024-04-08 09:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| FILTERENDTIME   | Filter job with end time greater than current time less value in seconds (Default: 86400)
less?

2024-04-08 09:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| FILTERSTARTTIME | Filter job with start time greater than current time less value in seconds
less

2024-04-08 09:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| OKSTATUS        | Set ok threshold for status. Can used special variables like: %{display}, %{status}, %{type}, %{is\_running}, %{scheduled}
```suggestion
| OKSTATUS        | Set OK threshold for status. Can use special variables like: %{display}, %{status}, %{type}, %{is\_running}, %{scheduled}                                                                        |                                                     |             |
```

2024-04-08 09:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| WARNINGLONG     | Set warning threshold for long jobs. Can used special variables like: %{display}, %{status}, %{type}, %{elapsed}
```suggestion
| WARNINGLONG     | Set warning threshold for long jobs. Can use special variables like: %{display}, %{status}, %{type}, %{elapsed}                                                                                  |                                                     |             |
```

2024-04-08 09:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| CRITICALLONG    | Set critical threshold for long jobs. Can used special variables like: %{display}, %{status}, %{type}, %{elapsed}
```suggestion
| CRITICALLONG    | Set critical threshold for long jobs. Can use special variables like: %{display}, %{status}, %{type}, %{elapsed}                                                                                 |                                                     |             |
```

2024-04-08 09:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| CRITICALSTATUS  | Set critical threshold for status (Default: '%{is\_running} == 0 and not %{status} =~ /Success/i'). Can used special variables like: %{display}, %{status}, %{type}, %{is\_running}
```suggestion
| CRITICALSTATUS  | Set critical threshold for status (Default: '%{is\_running} == 0 and not %{status} =~ /Success/i'). Can use special variables like: %{display}, %{status}, %{type}, %{is\_running}, %{scheduled} | %{is\_running} == 0 and not %{status} =~ /Success/i |             |
```

2024-04-08 09:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| WARNINGSTATUS   | Set warning threshold for status. Can used special variables like: %{display}, %{status}, %{type}, %{is\_running}, %{scheduled}
```suggestion
| WARNINGSTATUS   | Set warning threshold for status. Can use special variables like: %{display}, %{status}, %{type}, %{is\_running}, %{scheduled}                                                                   |                                                     |             |
```

2024-04-08 09:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| UNIT                              | Select the unit for expires threshold. May be 's' for seconds,'m' for minutes, 'h' for hours, 'd' for days, 'w' for weeks. Default is seconds |
expired thresholds?

2024-04-08 09:48 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| Tape-Jobs     | App-Veeam-Tape-Jobs-WSMAN-custom    | Monitor job tape status                 |
```suggestion
| Tape-Jobs     | App-Veeam-Tape-Jobs-WSMAN-custom    | Monitor the status of tape jobs             |
```

2024-04-08 09:48 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| FILTERENDTIME   | Filter job with end time greater than current time less value in seconds (Default: 86400)
less?

2024-04-08 09:48 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| FILTERSTARTTIME | Filter job with start time greater than current time less value in seconds
less?

2024-04-08 09:48 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-wsman.md
> +| UNIT                              | Select the unit for expires threshold. May be 's' for seconds,'m' for minutes, 'h' for hours, 'd' for days, 'w' for weeks. Default is seconds |
```suggestion
| UNIT                              | Select the unit for expired thresholds. May be 's' for seconds,'m' for minutes, 'h' for hours, 'd' for days, 'w' for weeks. Default is seconds |                                  |             |
```

2024-04-09 07:58 UTC, cg-tw requested changes

2024-04-09 07:59 UTC, cg-tw approved these changes

2024-04-09 08:13 UTC, lucie-dubrunfaut approved these changes

2024-04-09 08:15 UTC, merged