enh(mc): refresh cloud-azure-database-sqldatabase
centreon/centreon-documentation pull request #3175
Opened 2024-03-26 12:37 UTC by omercier

## Description

Refreshed the procedure.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-04-08 09:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
>  | App-Resources | Cloud-Azure-Database-SqlDatabase-App-Resources-custom | Contrôle les métriques CPU et Mémoire de l'App  |
```suggestion
| App-Resources | Cloud-Azure-Database-SqlDatabase-App-Resources-custom | Contrôle les métriques CPU et mémoire de l'app  |
```

2024-04-08 09:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
>  | App-Resources | Cloud-Azure-Database-SqlDatabase-App-Resources-custom | Contrôle les métriques CPU et Mémoire de l'App  |
de l'application?

2024-04-08 16:47 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
>  | App-Resources | Cloud-Azure-Database-SqlDatabase-App-Resources-custom | Contrôle les métriques CPU et Mémoire de l'App  |
la contraction semble assumée et sans la majuscule https://azure.microsoft.com/en-us/products/azure-sql/database/

2024-04-09 09:43 UTC, cg-tw requested changes

2024-04-09 09:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--mode=workers \
not many parameters here, is that normal? the mandatory ones should be filled in, at least

2024-04-09 09:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +> Set the following options in the EXTRAOPTIONS macro if you are monitoring resource from Microsoft Azure operated by 21Vianet (Azure China):
```suggestion
> Set the following options in the EXTRAOPTIONS macro if you are monitoring resources from Microsoft Azure operated by 21Vianet (Azure China):
```

2024-04-09 09:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--mode=workers \
same as for FR

2024-04-09 10:02 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--client-secret='' \
```suggestion
	--resource='XXXXXXXXXXXXXXXX' \
	--resource-group='' \
	--subscription='XXXXXXXXXXXXXXXX' \
	--tenant='XXXXXXXXXXXXXXXX' \
	--client-id='XXXXXXXXXXXXXXXX' \
	--client-secret='XXXXXXXXXXXXXXXX' \
```

2024-04-09 10:02 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-sqldatabase.md
> +	--client-secret='' \
```suggestion
	--resource='XXXXXXXXXXXXXXXX' \
	--resource-group='' \
	--subscription='XXXXXXXXXXXXXXXX' \
	--tenant='XXXXXXXXXXXXXXXX' \
	--client-id='XXXXXXXXXXXXXXXX' \
	--client-secret='XXXXXXXXXXXXXXXX' \
```

2024-04-09 11:20 UTC, cg-tw approved these changes

2024-04-09 11:21 UTC, merged