enh(mc): updated VerneMQ procedure
centreon/centreon-documentation pull request #3182
Opened 2024-03-28 16:27 UTC by omercier

## Description

OT connector update

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-04-02 16:23 UTC, cg-tw requested changes

2024-04-02 16:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +Le connecteur de supervision, supervise les Clusters, Listeners, Plugins et sessions en utilisant l'API Rest de VerneMQ.
```suggestion
Le connecteur de supervision supervise les Clusters, Listeners, Plugins et sessions en utilisant l'API REST de VerneMQ.
```

2024-04-02 16:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +Le connecteur de supervision, supervise les Clusters, Listeners, Plugins et sessions en utilisant l'API Rest de VerneMQ.
plugin ici, sonde après

2024-04-02 16:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
>  VerneMQ is a scalable and open source MQTT broker that connects IoT, M2M, Mobile, and web applications
```suggestion
VerneMQ is a scalable and open source MQTT broker that connects IoT, M2M, mobile and web applications.
```

2024-04-02 16:23 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
>  The VerneMQ Monitoring Connector monitors Clusters, Listeners, Plugins, and sessions using the RestAPI.
```suggestion
The VerneMQ Monitoring Connector monitors Clusters, Listeners, Plugins and sessions using the RestAPI.
```

2024-04-02 16:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
>  </Tabs>
HTTP or REST API?

2024-04-02 16:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +L'utilisateur **centreon-engine** effectue une connexion à ce système.
EN and FR are different

2024-04-03 12:33 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +| Plugins   | App-Vernemq-Plugins-Restapi-custom   | Contrôle les sondes    |
```suggestion
| Plugins   | App-Vernemq-Plugins-Restapi-custom   | Contrôle les plugins    |
```

2024-04-03 13:32 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +L'utilisateur **centreon-engine** effectue une connexion à ce système.
```suggestion
L'utilisateur **centreon-engine** effectue une requête RestAPI à ce système.
```

2024-04-03 14:04 UTC, cg-tw approved these changes

2024-04-03 14:06 UTC, lucie-dubrunfaut approved these changes

2024-04-03 14:54 UTC, merged