Refresh the ups-powerware-snmp doc
centreon/centreon-documentation pull request #3193
Opened 2024-04-03 13:37 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-04 11:53 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-ups-powerware-snmp.md
> +| Alarms        | HW-UPS-Powerware-Alarms-SNMP-custom | Check if alarms present |
```suggestion
| Alarms        | HW-UPS-Powerware-Alarms-SNMP-custom | Check if alarms are present |
```

2024-04-04 12:42 UTC, omercier approved these changes

2024-04-09 09:02 UTC, cg-tw requested changes

2024-04-09 09:02 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-powerware-snmp.md
> +| Environment    | HW-UPS-Powerware-Environment-SNMP-custom    | Contrôle le taux d'humidité et la témperature        |
```suggestion
| Environment    | HW-UPS-Powerware-Environment-SNMP-custom    | Contrôle le taux d'humidité et la température        |
```

2024-04-09 09:02 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-powerware-snmp.md
> +| Battery-Status | HW-UPS-Powerware-Battery-Status-SNMP-custom | Check battery status and battery charge remaining |
```suggestion
| Battery-Status | HW-UPS-Powerware-Battery-Status-SNMP-custom | Check battery status and remaining battery charge |
```

2024-04-09 09:03 UTC, cg-tw approved these changes

2024-04-09 09:57 UTC, omercier approved these changes

2024-04-09 11:21 UTC, merged