Refresh the Qnap documentation
centreon/centreon-documentation pull request #3196
Opened 2024-04-04 08:51 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-04 16:03 UTC, omercier submitted a review, later dismissed

2024-05-03 11:34 UTC, cg-tw requested changes

2024-05-03 11:34 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| Traffic-Generic-Id   | HW-Storage-Qnap-Traffic-Generic-Id-SNMP-custom   | Check traffic of an network interface                                                        |            |
```suggestion
| Traffic-Generic-Id   | HW-Storage-Qnap-Traffic-Generic-Id-SNMP-custom   | Check traffic of a network interface                                                        |            |
```

2024-05-03 11:34 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| Disk-Global          | HW-Storage-Qnap-Disk-Global-SNMP-custom          | Check the rate of free space on disks. For each checks the mount point of disks will appear  | X          |
```suggestion
| Disk-Global          | HW-Storage-Qnap-Disk-Global-SNMP-custom          | Check the rate of free space on disks. For each check the mount point of disks will appear  | X          |
```

2024-05-03 11:34 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| Traffic-Generic-Name | HW-Storage-Qnap-Traffic-Generic-Name-SNMP-custom | Check traffic of an network interface                                                        |            |
```suggestion
| Traffic-Generic-Name | HW-Storage-Qnap-Traffic-Generic-Name-SNMP-custom | Check traffic of a network interface                                                        |            |
```

2024-05-07 15:22 UTC, lucie-dubrunfaut approved these changes

2024-05-07 15:23 UTC, merged