Refresh the Netbotz Sensor documentation
centreon/centreon-documentation pull request #3198
Opened 2024-04-04 12:39 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-04 12:41 UTC, YanMeddour commented
command output: `OK: |`

2024-04-04 13:03 UTC, omercier submitted a review, later dismissed

2024-04-09 08:21 UTC, cg-tw requested changes

2024-04-09 08:21 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
> +| Sensors-Global | HW-Sensors-Netbotz-Sensors-Global-SNMP-custom | Check all sensors of equipment |
```suggestion
| Sensors-Global | HW-Sensors-Netbotz-Sensors-Global-SNMP-custom | Check all the sensors of the device |
```

2024-04-09 08:58 UTC, cg-tw approved these changes

2024-04-09 09:57 UTC, omercier approved these changes

2024-04-09 11:22 UTC, merged