Refresh the Office 365 documentation
centreon/centreon-documentation pull request #3199
Opened 2024-04-04 13:20 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-04 16:04 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
> +## Contenu du pack
```suggestion
Office 365 est une suite de services en ligne proposés par Microsoft dans le cadre de sa ligne de produit Microsoft Office.
Les informations de monitoring de la suite Office sont mises à disposition par Microsoft à travers une API de gestion Office 365.

## Contenu du pack
```

2024-04-04 16:04 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
> +## Pack assets
```suggestion
Office 365 is a line of online subscription services offered by Microsoft in their Microsoft Office product suite. 
Office 365 covers document creation and management, emailing, video conferencing and many more collaboration offerings.
The Centreon Plugin relies on the Office 365 Graph API to collect and monitor the Office 365 information and metrics.

## Pack assets
```

2024-04-04 16:06 UTC, omercier submitted a review, later dismissed

2024-05-03 11:44 UTC, cg-tw requested changes

2024-05-03 11:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
>  Office 365 est une suite de services en ligne proposés par Microsoft dans le cadre de sa ligne de produit Microsoft Office.
```suggestion
Office 365 est une suite de services en ligne proposés par Microsoft dans le cadre de sa ligne de produits Microsoft Office.
```

2024-05-03 11:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
> +| App-Credentials | Cloud-Microsoft-Office365-Management-App-Credentials-Api-custom | Contrôle les credentials des applications |
```suggestion
| App-Credentials | Cloud-Microsoft-Office365-Management-App-Credentials-Api-custom | Contrôle les informations de connexion des applications |
```

2024-05-03 11:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
>  Office 365 covers document creation and management, emailing, video conferencing and many more collaboration offerings.
```suggestion
```

2024-05-03 11:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
> +	--client-secret=''  \
fill in a sample value, as these are mandatory fields

2024-05-03 11:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
> +	--client-secret=''  \
fill in a sample value, as these are mandatory fields

2024-05-07 13:30 UTC, cg-tw requested changes

2024-05-07 13:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
> +	--client-secret='9/kRTASjPxx9FJfQZg6iznX\AkzCGertBgNq5r3tPfECJfKxj6zA='  \
```suggestion
	--tenant='xxxxxxxx-xxxxxxxx-xxxxxxxx-xxxx-xxxxxxxxxxxx' \
	--client-id='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-xxxx' \
	--client-secret='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'  \
```

2024-05-07 13:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
> +	--client-secret='9/kRTASjPxx9FJfQZg6iznX\AkzCGertBgNq5r3tPfECJfKxj6zA='  \
```suggestion
	--tenant='xxxxxxxx-xxxxxxxx-xxxxxxxx-xxxx-xxxxxxxxxxxx' \
	--client-id='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-xxxx' \
	--client-secret='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'  \
```

2024-05-07 13:31 UTC, omercier approved these changes

2024-05-07 13:31 UTC, cg-tw approved these changes

2024-05-07 14:51 UTC, merged