Refresh the base-generic documentation
centreon/centreon-documentation pull request #3226
Opened 2024-04-12 12:36 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-23 15:41 UTC, omercier commented on pp/integrations/plugin-packs/procedures/base-generic.md
> +This Monitoring Connector has no specific prerequisites, providing all basic templates required for monitoring. However, it is necessary to have Nagios'ICMP check.
```suggestion
This Monitoring Connector has no specific prerequisites except the Nagios ICMP plugin, which is installed by default on Centreon servers.
```

2024-04-25 08:01 UTC, cg-tw requested changes

2024-04-25 08:01 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/base-generic.md
> +| PACKETNUMBER | Number of packet   | 5             |
```suggestion
| PACKETNUMBER | Number of packets   | 5             |
```

2024-04-25 08:01 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/base-generic.md
> +| PACKETNUMBER | Number of packet   | 5             |
```suggestion
| PACKETNUMBER | Number of packets   | 5             |
```

2024-04-30 07:46 UTC, omercier approved these changes

2024-05-03 12:02 UTC, cg-tw approved these changes

2024-05-03 12:02 UTC, merged