(new): versa monic proc v2
centreon/centreon-documentation pull request #323
Opened 2020-08-27 15:19 UTC by pkriko

2020-08-28 08:05 UTC, thibaults-centreon requested changes

2020-08-28 08:05 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-snmp.md
> +| interface.traffic.out.bitspersecond       | Outgoing traffic going through the interface           | B/s  |
b/s

2020-08-28 08:05 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-snmp.md
> +| ipsec.traffic.out.bytespersecond | Outcoming taffic going through the IPsec tunnel    | Count |
B/s

2020-08-28 08:05 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-snmp.md
> +* par Application Qos Policy
```suggestion
* Par application Qos Policy

```

2020-08-28 08:05 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-snmp.md
> +La documentation officielle Versa Networks détaille les étapes pour activer et configurer le service SNMP.
URL link ;-)

2020-08-28 08:05 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-snmp.md
> +  --mode devices \
```suggestion
  --plugin=network::versa::snmp::plugin \
  --mode=devices \

```

2020-08-28 08:05 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-snmp.md
> +Dans cet exemple, le Plugin récupère l'utilisation d'un équipement Versa Networks (```--plugin network::versa::snmp::plugin --mode devices```)
```suggestion
Dans cet exemple, le Plugin récupère l'utilisation d'un équipement Versa Networks (```--plugin=network::versa::snmp::plugin --mode=devices```)

```

2020-08-28 08:05 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-snmp.md
> +L'alarme sera de type CRITICAL au delà de 90% de cette même utilisation (```--critical-sessions-active-prct='90'```).
```suggestion
l'alarme sera de type CRITICAL au delà de 90% de cette même utilisation (```--critical-sessions-active-prct='90'```).

```

2020-08-28 08:05 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-snmp.md
> +/usr/lib/centreon/plugins/centreon_versa_snmp.pl --plugin network::versa::snmp::plugin --mode devices --help
```suggestion
/usr/lib/centreon/plugins/centreon_versa_snmp.pl --plugin=network::versa::snmp::plugin --mode=devices --help

```

2020-08-28 08:05 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/network-versa-snmp.md
> +/usr/lib/centreon/plugins/centreon_versa_snmp.pl --plugin network::versa::snmp::plugin --mode devices --help
```suggestion
/usr/lib/centreon/plugins/centreon_versa_snmp.pl --plugin=network::versa::snmp::plugin --mode=devices --help

```

2020-09-07 11:41 UTC, Sims24 reviewed
Thanks for the great work. 

Few questions: 
- Any URL link available to explain how to configure SNMP? (as requested by @thibaults-centreon) 
- Why alphabetical order isn't keep in the sidebar ? 
- Don't you think "By monitor" would be more understandable that "by health monitor" ?

2020-10-05 07:42 UTC, Sims24 commented
Metrics have changed recently, I'll update the PR accordingly.

2020-10-05 15:16 UTC, Sims24 approved these changes

2020-10-05 15:35 UTC, thibaults-centreon requested changes

2020-10-05 15:35 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +collect status and metrics of the Versa equipements managed by the Director.
```suggestion
collect status and metrics of the Versa equipments managed by the Director.

```

2020-10-05 15:35 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +| policy.violation.packets.dropped.slaaction.count   | Number of packets dropped by sla action    | Count |
```suggestion
| Metric name                                        | Description                                 | Unit  |
|:-------------------------------------------------- |:------------------------------------------- |:----- |
| status                                             | Status of the device                        |       |
| memory.usage.bytes                                 | Memory usage on the device                  | B     |
| memory.free.bytes                                  | Free memory on the device                   | B     |
| memory.usage.percentage                            | Percentage of memory usage on the device    | %     |
| disk.usage.bytes                                   | Disk usage on the device                    | B     |
| disk.free.bytes                                    | Free disk space on the device               | B     |
| disk.usage.percentage                              | Percentage of disk usage on the device      | %     |
| alarms.critical.count                              | Number of critical alarms on the device     | Count |
| alarms.major.count                                 | Number of major alarms on the device        | Count |
| alarms.minor.count                                 | Number of minor alarms on the device        | Count |
| alarms.warning.count                               | Number of warning alarms on the device      | Count |
| alarms.indeterminate.count                         | Number of indeterminate alarm on the device | Count |
| policy.violation.packets.dropped.novalidlink.count | Number of packets dropped by no valid link  | Count |
| policy.violation.packets.dropped.slaaction.count   | Number of packets dropped by sla action     | Count |

```

2020-10-05 15:35 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/network-versa-snmp.md
> +The Centreon Plugin-Pack relies on the SNMP protocol to query and collect status and metrics of the Versa equipements.
```suggestion
The Centreon Plugin-Pack relies on the SNMP protocol to query and collect status and metrics of the Versa equipments.

```

2020-10-05 15:35 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/network-versa-snmp.md
> +Please refer to the manufacturer documentation to achieve this
```suggestion
Please refer to the manufacturer documentation to achieve this.

```

2020-10-05 15:35 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +| policy.violation.packets.dropped.slaaction.count   | Number of packets dropped by sla action    | Count |
```suggestion
| Metric name                                        | Description                                 | Unit  |
|:-------------------------------------------------- |:------------------------------------------- |:----- |
| status                                             | Status of the device                        |       |
| memory.usage.bytes                                 | Memory usage on the device                  | B     |
| memory.free.bytes                                  | Free memory on the device                   | B     |
| memory.usage.percentage                            | Percentage of memory usage on the device    | %     |
| disk.usage.bytes                                   | Disk usage on the device                    | B     |
| disk.free.bytes                                    | Free disk space on the device               | B     |
| disk.usage.percentage                              | Percentage of disk usage on the device      | %     |
| alarms.critical.count                              | Number of critical alarms on the device     | Count |
| alarms.major.count                                 | Number of major alarms on the device        | Count |
| alarms.minor.count                                 | Number of minor alarms on the device        | Count |
| alarms.warning.count                               | Number of warning alarms on the device      | Count |
| alarms.indeterminate.count                         | Number of indeterminate alarm on the device | Count |
| policy.violation.packets.dropped.novalidlink.count | Number of packets dropped by no valid link  | Count |
| policy.violation.packets.dropped.slaaction.count   | Number of packets dropped by sla action     | Count |

```

2020-10-05 15:35 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +2. Installer le Plugin-Pack 'Versa Director Restapi' depuis la page "Configuration > Plugin packs > Manager" sur l'interface Web de Centreon.
```suggestion
2. Installer le Plugin-Pack *Versa Director Restapi* depuis la page "Configuration > Plugin packs > Manager" sur l'interface Web de Centreon.

```

2020-10-05 15:35 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +3. Installer le Plugin-Pack 'Versa Director Restapi' depuis la page "Configuration > Plugin packs > Manager" sur l'interface Web de Centreon.
```suggestion
3. Installer le Plugin-Pack *Versa Director Restapi* depuis la page "Configuration > Plugin packs > Manager" sur l'interface Web de Centreon.

```

2020-10-05 15:35 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +A partir du moment ou le Plugin est installé, vous pouvez tester directement celui-ci en ligne de commande depuis votre collecteur Centreon avec l'utilisateur *centreon-engine*:
```suggestion
Une fois le Plugin installé, vous pouvez tester directement celui-ci en ligne de commande depuis votre collecteur Centreon avec l'utilisateur *centreon-engine*:

```

2020-10-05 15:35 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +Un équipement Versa peut être lié à plusieurs organisations, nous utilisons une widlcard (```--organization='.*'```).
```suggestion
Un équipement Versa peut être lié à plusieurs organisations, nous utilisons une *wildcard* (```--organization='.*'```).

```

2020-10-05 15:38 UTC, thibaults-centreon approved these changes

2020-10-05 15:59 UTC, merged