[CTOR-499] Update Himoinsa UPS page
centreon/centreon-documentation pull request #3242
Opened 2024-04-22 13:58 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-26 15:55 UTC, omercier approved these changes

2024-05-03 09:31 UTC, cg-tw requested changes

2024-05-03 09:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-himoinsa-snmp.md
> +| Phase         | HW-UPS-Himoinsa-Phase-SNMP-custom      | Check 1 phase, 2 phase et 3 phase |
?

2024-05-03 09:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-himoinsa-snmp.md
> +| Phase      | HW-UPS-Himoinsa-Phase-SNMP-custom      | Contrôle phase 1, phase 2 et phase 3        |
?

2024-05-06 13:36 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-ups-himoinsa-snmp.md
> +| Phase         | HW-UPS-Himoinsa-Phase-SNMP-custom      | Check 1 phase, 2 phase et 3 phase |
Pas mieux :')

2024-05-14 13:20 UTC, omercier approved these changes

2024-05-14 13:30 UTC, cg-tw approved these changes

2024-05-21 15:19 UTC, merged