[CTOR-500] Update HP UPS SNMP page
centreon/centreon-documentation pull request #3246
Opened 2024-04-23 08:38 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-26 15:54 UTC, omercier submitted a review, later dismissed

2024-05-03 09:40 UTC, cg-tw requested changes

2024-05-03 09:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-hp-snmp.md
> +| Environment    | HW-UPS-HP-Environment-SNMP-custom    | Contrôle le taux d'humidité et la témperature        |
```suggestion
| Environment    | HW-UPS-HP-Environment-SNMP-custom    | Contrôle le taux d'humidité et la température        |
```

2024-05-03 09:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-hp-snmp.md
>  Le flux SNMP UDP/161 doit être ouvert entre le Collecteur et l'équipement.
```suggestion
### Configuration SNMP

Le service SNMP doit être activé et configuré sur l'équipement. Veuillez vous référer à la documentation officielle du constructeur/éditeur.

### Flux réseau

La communication doit être possible sur le port UDP 161 depuis le collecteur
Centreon vers la ressource supervisée.
```

2024-05-03 09:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-ups-hp-snmp.md
>  The Poller should be able to perform SNMP requests toward the HP device over SNMP UDP/161 port.
```suggestion
### SNMP Configuration

The SNMP service must be configured and activated on the host. Please refer to the official documentation from the manufacturer/publisher.

### Network flow

The target resource must be reachable from the Centreon poller on the UDP/161
SNMP port.
```

2024-05-07 13:36 UTC, omercier approved these changes

2024-05-07 13:36 UTC, cg-tw approved these changes

2024-05-07 13:36 UTC, merged