[CTOR-526] Update Splunk doc page
centreon/centreon-documentation pull request #3250
Opened 2024-04-23 13:48 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-30 07:58 UTC, omercier submitted a review, later dismissed

2024-05-03 13:49 UTC, cg-tw requested changes

2024-05-03 13:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| --splunk-retries                           | How many times we should retry queries to splunk. To use in par with the --splunk-wait paramater (default: 5)
```suggestion
| --splunk-retries                           | How many times we should retry queries to splunk. To use with the --splunk-wait parameter (default: 5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
```

2024-05-03 13:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| --splunk-wait                              | How long (in seconds) should we wait between each retry. To use in par with the --splunk-retries paramater (default: 2)
```suggestion
| --splunk-wait                              | How long (in seconds) should we wait between each retry. To use with the --splunk-retries parameter (default: 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2024-05-03 13:49 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| --splunk-retries                           | How many times we should retry queries to splunk. To use in par with the --splunk-wait paramater (default: 5)
```suggestion
| --splunk-retries                           | How many times we should retry queries to splunk. To use with the --splunk-wait parameter (default: 5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
```

2024-05-03 13:49 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
> +| --splunk-wait                              | How long (in seconds) should we wait between each retry. To use in par with the --splunk-retries paramater (default: 2)
```suggestion
| --splunk-wait                              | How long (in seconds) should we wait between each retry. To use with the --splunk-retries parameter (default: 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2024-05-07 15:01 UTC, cg-tw approved these changes

2024-05-07 15:02 UTC, merged