doc(release): prepare release notes for oss 24.04 on prem
centreon/centreon-documentation pull request #3253
Opened 2024-04-24 14:34 UTC by pkippes

gorgone
web

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-26 16:05 UTC, cg-tw requested changes

2024-04-29 12:39 UTC, cg-tw requested changes

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +- **Playlists feature:** you can now create dashboards playlists. Selected dashboards will be displayed sequentially without any interaction allowing to broadcast them on TV set on public spaces.
```suggestion
- **Playlists feature:** you can now create dashboard playlists. Selected dashboards will be displayed sequentially without any interaction, allowing you to broadcast them on TVs in public spaces.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - A warning modal is now preventing user from quitting the dashboard without saving it first.
```suggestion
  - A warning modal is now preventing users from leaving the dashboard without saving it first.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Optimized the widget rendering.
```suggestion
  - Optimized the rendering of widgets.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Moved the parameter used for hiding widget's description.
```suggestion
  - Moved the parameter used for hiding widgets' descriptions.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Made the widget edition more accessible.
```suggestion
  - Made widget edition more accessible.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Made the dashboards library view as list the default one.
```suggestion
 - Made the dashboard library's "view as list" the default view.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Reorganized rich text options for widget description.
```suggestion
  - Reorganized rich text options for widget descriptions.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - [MAP widget] Added information message when editing.
```suggestion
  - [MAP widget] Added an information message displayed when editing the widget.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +- **Improvements made on specific widgets**
```suggestion
- **Improvements made to specific widgets**.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - [Metrics Graph widget] Added an information tooltip when hovering an element on the graph.
```suggestion
  - [Metrics Graph widget] Added an information tooltip when hovering over an element on the graph.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Added a new endpoint to list playlist shares.
```suggestion
  - Added new endpoints to manage [playlists](centreon-commercial-extensions.md#centreon-it-edition-extensions).
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Added a new endpoint to duplicate dashboard.
```suggestion
  - Added a new endpoint to duplicate dashboards.
```

2024-04-29 12:39 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +- Added the support of Debian 12 as operating system.
```suggestion
- Added support for the Debian 12 operating system.
```

2024-04-29 14:53 UTC, cg-tw requested changes

2024-04-29 14:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +- **Resource Status**: you can now access links to Resource Status page on widgets filtered by widget resource parameters.
```suggestion
- **Resource Status**: Widgets now include a link to the Resource Status page. When you access this link, Resources Status will be filtered according to the criteria used in the widget.
```

2024-04-29 14:53 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +- **Resource Status**: you can now access links to Resource Status page on widgets filtered by widget resource parameters.
```suggestion
- **Resource Status**: Widgets now include a link to the Resource Status page. When you access this link, Resources Status will be filtered according to the criteria used in the widget.
```

2024-04-29 14:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +  - Added new endpoints to manage [playlists](centreon-commercial-extensions.md#centreon-it-edition-extensions).
```suggestion
  - Added new endpoints to manage [playlists](centreon-commercial-extensions.mdx#centreon-it-edition-extensions).
```

2024-04-29 14:53 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Added new endpoints to manage [playlists](centreon-commercial-extensions.md#centreon-it-edition-extensions).
```suggestion
  - Added new endpoints to manage [playlists](centreon-commercial-extensions.mdx#centreon-it-edition-extensions).
```

2024-04-29 15:28 UTC, cg-tw requested changes

2024-04-29 15:28 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +  - Added metrics by service listing endpoint to service resource type.
```suggestion
  - Metrics linked to a resource are now retrieved by the endpoint that lists resources.
```

2024-04-29 15:28 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Added metrics by service listing endpoint to service resource type.
```suggestion
  - Metrics linked to a resource are now retrieved by the endpoint that lists resources.
```

2024-04-30 08:19 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> + - Made the dashboard library's "view as list" the default view.
```suggestion
  - Made the dashboard library's "view as list" the default view.
```

2024-04-30 08:19 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  -When sharing a dashboard, only contacts and contact groups that have access to the dashboard are displayed.
```suggestion
  - When sharing a dashboard, only contacts and contact groups that have access to the dashboard are displayed.
```

2024-04-30 08:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +- **Playlists feature:** you can now create dashboard playlists. Selected dashboards will be displayed sequentially without any interaction, allowing you to broadcast them on TVs in public spaces.
```suggestion
- **Playlists feature:** You can now create dashboard playlists. Selected dashboards will be displayed sequentially without any interaction, allowing you to broadcast them on TVs in public spaces.
```

2024-04-30 08:19 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +- **Playlists feature:** you can now create dashboard playlists. Selected dashboards will be displayed sequentially without any interaction, allowing you to broadcast them on TVs in public spaces.
```suggestion
- **Playlists feature:** You can now create dashboard playlists. Selected dashboards will be displayed sequentially without any interaction, allowing you to broadcast them on TVs in public spaces.
```

2024-04-30 08:25 UTC, cg-tw requested changes

2024-04-30 08:25 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +- Moved custom gorgone whitelists to a dedicated file.
```suggestion
- Moved gorgone whitelists to a dedicated file.
```

2024-04-30 08:25 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +- Moved custom gorgone whitelists to a dedicated file.
```suggestion
- Moved gorgone whitelists to a dedicated file.
```

2024-04-30 08:42 UTC, lpinsivy approved these changes

2024-04-30 08:44 UTC, cg-tw approved these changes

2024-04-30 09:14 UTC, cg-tw requested changes

2024-04-30 09:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +  - Made widget edition more accessible.
```suggestion
  - Widgets now have an "Edit widget" command that allows you to enter edition mode quickly.
```

2024-04-30 09:14 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Made widget edition more accessible.
```suggestion
  - Widgets now have an "Edit widget" command that allows you to enter edition mode quickly.
```

2024-04-30 09:14 UTC, cg-tw approved these changes

2024-04-30 09:37 UTC, cg-tw requested changes

2024-04-30 09:37 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +  - Widgets now have an "Edit widget" command that allows you to enter edition mode quickly.
```suggestion
  - Widgets can now be edited quickly and easily by using an "Edit widget" shortcut that opens widget edition mode.
```

2024-04-30 09:37 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +  - Widgets now have an "Edit widget" command that allows you to enter edition mode quickly.
```suggestion
  - Widgets can now be edited quickly and easily by using an "Edit widget" shortcut that opens widget edition mode.
```

2024-04-30 09:38 UTC, cg-tw approved these changes

2024-04-30 09:39 UTC, lpinsivy approved these changes

2024-04-30 12:17 UTC, cg-tw approved these changes

2024-04-30 12:19 UTC, lpinsivy approved these changes

2024-04-30 12:33 UTC, merged