doc(release) prepare release notes for modules 24.04 on premise
centreon/centreon-documentation pull request #3255
Opened 2024-04-24 14:44 UTC by pkippes

map 
anomaly detection
bam
mbi
IT Edition Extensions

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-26 15:09 UTC, nmagniezCentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
> +- [API] Added a new endpoint to list shares of playlists.
J'aurais ajouté une sous section "Dashboard Playlists"

2024-04-26 15:36 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
> +- To facilitate smooth transition from MAP Legacy to MAP, we have made sure that features and enhancements already available in previous versions are fully compatible.
```suggestion
- To facilitate a smooth transition from MAP Legacy to MAP, we have made sure that features and enhancements already available in previous versions are fully compatible.
```

2024-04-26 15:36 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
> +- [API] Added an endpoint to UPDATE Cloud Token.
```suggestion
- [API] Added an endpoint to UPDATE Cloud tokens.
```

2024-04-26 15:37 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
> +- [API] Added a new endpoint to revoke the share of a contact group on a playlist.
```suggestion
New playlist feature: dashboard playlists allow you to display several dashboards sequentially without any interaction. Ideal for broadcast on a TV screen. 
	
You can now:
- create dashboard playlists.
- display the list of dashboard playlists.
- share playlists.
- display the list of playlist shares.
- revoke the sharing of a playlist to a contact group.
```

2024-04-29 08:45 UTC, lpinsivy requested changes

2024-04-29 08:45 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
> +- [API] Added an endpoint to GET Business Activities.
```suggestion
```

2024-04-29 08:45 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
> +- [API] Added an endpoint to GET Business Activities.
already present in BAM

2024-04-29 08:45 UTC, lpinsivy commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
>  ## Centreon Monitoring Connectors Manager (formerly Plugin Packs Manager)
```suggestion
## Centreon Monitoring Connectors Manager
```

2024-04-29 08:45 UTC, lpinsivy commented on versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
>  ## Centreon Monitoring Connectors Manager (formerly Plugin Packs Manager)
```suggestion
## Centreon Monitoring Connectors Manager
```

2024-04-29 08:45 UTC, lpinsivy commented on versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
> +- [API] Added an endpoint to GET Business Activities.
```suggestion
```

2024-04-30 08:31 UTC, cg-tw approved these changes

2024-04-30 08:44 UTC, lpinsivy approved these changes

2024-04-30 08:45 UTC, nmagniezCentreon approved these changes

2024-04-30 12:18 UTC, merged