Initial doc
centreon/centreon-documentation pull request #3256
Opened 2024-04-25 08:33 UTC by lucie-dubrunfaut

## Description

New pack Avigilon-Camera-SNMP monitoring:

- uptime
- interfaces
- storage
- memory
- temperature

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-04-25 09:31 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +| WARNINGINVOLUME        |
@cg-tw J'ai demandé à Olivier car je ne vois pas ces paramètres côté mode interface (qui est générique) donc les 4 qui sont vides sont sujets d'une enquête je les compléterais ou virerais selon ce qu'il en dit [ici](https://github.com/centreon/centreon-plugin-packs/pull/1542/files#r1579159611)

2024-04-26 07:29 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créer un modèle map
J'ai pas trouvé comment traduire ça :'(

2024-04-26 09:25 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créer un modèle map
J'ai tenté une nouvelle version: "modèle associatif"
Ca c'ets la phrase en anglais : "Discover your resources through an SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a template mapper for the **HW-Device-Camera-Avigilon-SNMP-custom** host template"

2024-04-26 09:26 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +> Pour obtenir ce nouveau format de métrique, incluez la valeur **--use-new-perfdata** dans la macro de service **EXTRAOPTIONS**.
C'est ajouté automatiquement par le script d'Ivan j'ai l'imperssion

2024-04-26 09:26 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +| Memory             | HW-Device-Camera-Avigilon-Memory-SNMP-custom      | Check system memory available                        |
En fait je suis revenu dessus parce que littéralement le mode Memory ne mesure **QUE** la mémoire totale du système qui est disponible (rien d'autre)

2024-04-26 09:27 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +| Storage state      | HW-Device-Camera-Avigilon-Storage-SNMP-custom     | Contrôle l'état de stockage de la carte SD                                    |
Je l'ai changé dans le modèle de service de pp-imp

2024-04-26 09:55 UTC, cg-tw requested changes

2024-04-26 09:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créer un modèle ass
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **HW-Device-Camera-Avigilon-SNMP-custom** |
```

2024-04-26 09:56 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créer un modèle map
mapper de autoisco c'est "modificateur" l'appellation officielle

2024-04-26 09:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-avigilon-snmp.md
> +> Pour obtenir ce nouveau format de métrique, incluez la valeur **--use-new-perfdata** dans la macro de service **EXTRAOPTIONS**.
mais je suis pas sûre qu'il s'agisse d'un "nouveau" format. @omercier ?

2024-04-26 16:11 UTC, omercier approved these changes

2024-04-29 08:46 UTC, cg-tw approved these changes

2024-04-29 08:46 UTC, merged