[CTOR-504] Update the ABB CMS-700 doc page
centreon/centreon-documentation pull request #3260
Opened 2024-04-29 09:09 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-04-30 07:54 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-abb-cms700-snmp.md
> +| HW-Device-Abb-Cms700-SNMP-Sensors-Measurements |             |
```suggestion
| HW-Device-Abb-Cms700-SNMP-Sensors-Measurements |  Découvre les capteurs proposés par l'équipement. |
```

2024-04-30 07:54 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-devices-abb-cms700-snmp.md
> +| HW-Device-Abb-Cms700-SNMP-Sensors-Measurements |             |
```suggestion
| HW-Device-Abb-Cms700-SNMP-Sensors-Measurements | Discovers the sensors that are provided by the device. |
```

2024-04-30 07:55 UTC, omercier approved these changes

2024-05-03 09:57 UTC, cg-tw requested changes

2024-05-03 09:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-abb-cms700-snmp.md
> +| Sensors-Measurements | HW-Device-Abb-Cms700-Sensors-Measurements-SNMP-custom | Contrôle les données collectées pour chaque capteurs | X          |
```suggestion
| Sensors-Measurements | HW-Device-Abb-Cms700-Sensors-Measurements-SNMP-custom | Contrôle les données collectées pour chaque capteur | X          |
```

2024-05-03 09:57 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-devices-abb-cms700-snmp.md
> +| Mains-Measurements   | HW-Device-Abb-Cms700-Mains-Measurements-SNMP-custom   | Check mains/phases collected data     |            |
```suggestion
| Mains-Measurements   | HW-Device-Abb-Cms700-Mains-Measurements-SNMP-custom   | Check collected data for mains/phases      |            |
```

2024-05-03 09:57 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-devices-abb-cms700-snmp.md
> +| Sensors-Measurements | HW-Device-Abb-Cms700-Sensors-Measurements-SNMP-custom | Check branches/sensors collected data | X          |
```suggestion
| Sensors-Measurements | HW-Device-Abb-Cms700-Sensors-Measurements-SNMP-custom | Check collected data for branches/sensors  | X          |
```

2024-05-07 13:52 UTC, omercier approved these changes

2024-05-07 15:09 UTC, merged