[CTOR-554] Update the Prometheus kubernetes doc page
centreon/centreon-documentation pull request #3263
Opened 2024-04-30 15:01 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-03 14:01 UTC, cg-tw requested changes

2024-05-03 14:01 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-prometheus-kubernetes-api.md
> +as possible here as it will save time to everybody.*
no prerequisites

2024-05-03 14:01 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-prometheus-kubernetes-api.md
> +OK: All nodes status are ok | '*nodes*#pods.allocated.count'=;;;;
@omercier is that sufficient?

2024-05-07 13:54 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-prometheus-kubernetes-api.md
> +OK: All nodes status are ok | '*nodes*#pods.allocated.count'=;;;;
```suggestion
OK: All nodes status are ok | '*nodes*#pods.allocated.count'=42;;;;
```

2024-05-07 13:54 UTC, omercier commented on pp/integrations/plugin-packs/procedures/cloud-prometheus-kubernetes-api.md
> +OK: All nodes status are ok | '*nodes*#pods.allocated.count'=;;;;
```suggestion
OK: All nodes status are ok | '*nodes*#pods.allocated.count'=42;;;;
```

2024-05-07 13:54 UTC, omercier approved these changes

2024-05-07 14:58 UTC, cg-tw approved these changes

2024-05-07 14:58 UTC, merged