[CTOR-514] [Doc] New Pack RRDCached
centreon/centreon-documentation pull request #3264
Opened 2024-04-30 15:04 UTC by lucie-dubrunfaut

## Description

Initial pack release for this plugin already existing.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-05-03 14:13 UTC, cg-tw requested changes

2024-05-03 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Stats | App-Rrdcached-Stats-custom | Check Updates cache of rrdcached daemon  |
- unclear
- EN in FR

2024-05-03 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +Pour utiliser ce connecteur, vous devez installer et configurer RRDCached (voir cette [documentation](https://oss.oetiker.ch/rrdtool/doc/rrdcached.en.html)).
```suggestion
Pour utiliser ce connecteur, vous devez [installer et configurer RRDCached](https://oss.oetiker.ch/rrdtool/doc/rrdcached.en.html).
```

2024-05-03 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| WARNINGQUEUE   | Warning number of nodes in RRDCached queue                                                                                                       | 70                |             |
unclear

2024-05-03 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| CRITICALQUEUE  | Critical number of nodes in RRDCached queue                                                                                                      | 100               |             |
unclear

2024-05-03 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| WARNINGUPDATE  | Warning number of cached RRD updates (One update can include several values)                                                                     | 3000              |             |
unclear

2024-05-03 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| CRITICALUPDATE | Critical number of cached RRD updates (One update can include several values)                                                                    | 5000              |             |
unclear

2024-05-03 14:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +OK:  | 'UpdatesWaiting'=10updates;;;0;
is that sufficient?

2024-05-03 14:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Stats         | App-Rrdcached-Stats-custom | Affiche les mise à jour du cache d'un daemon rrdcached  |
FR in EN

2024-05-03 14:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Stats         | App-Rrdcached-Stats-custom | Affiche les mise à jour du cache d'un daemon rrdcached  |
```suggestion
| Stats         | App-Rrdcached-Stats-custom | Affiche les mises à jour du cache d'un daemon rrdcached  |
```

2024-05-03 14:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rrdcached.md
> +To use this connector you must have installed and configured RRDCached (see this [documentation](https://oss.oetiker.ch/rrdtool/doc/rrdcached.en.html)).
```suggestion
To use this connector you must have [installed and configured RRDCached](https://oss.oetiker.ch/rrdtool/doc/rrdcached.en.html).
```

2024-05-03 14:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| EXTRAOPTIONS   | Any extra option you may want to add to the command (a --verbose flag for example). All options are listed [here](#available-options). | --verbose         |             |
unclear

2024-05-03 14:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rrdcached.md
> +OK:  | 'UpdatesWaiting'=10updates;;;0;
is that sufficient?

2024-05-14 12:27 UTC, cg-tw requested changes

2024-05-14 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Ping-Socket | App-Rrdcached-Ping-Socket-Tcp-custom  | Check Updates cache of rrdcached daemon  |
```suggestion
| Ping-Socket | App-Rrdcached-Ping-Socket-Tcp-custom  | Monitor status and performance of RRDcached daemon  |
```

2024-05-14 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Stats       | App-Rrdcached-Stats-Tcp-custom        | Check Updates cache of rrdcached daemon  |
```suggestion
| Stats       | App-Rrdcached-Stats-Tcp-custom        | Monitor status and performance of RRDcached daemon  |
```

2024-05-14 12:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Ping-Socket | App-Rrdcached-Ping-Socket-Tcp-custom  | Check Updates cache of rrdcached daemon  |
```suggestion
| Ping-Socket | App-Rrdcached-Ping-Socket-Tcp-custom  | Monitor status and performance of RRDcached daemon  |
```

2024-05-14 12:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Stats       | App-Rrdcached-Stats-Tcp-custom        | Check Updates cache of rrdcached daemon  |
```suggestion
| Stats       | App-Rrdcached-Stats-Tcp-custom        | Monitor status and performance of RRDcached daemon  |
```

2024-05-14 12:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Ping-Socket | App-Rrdcached-Ping-Socket-Unix-custom | Check Updates cache of rrdcached daemon  |
```suggestion
| Ping-Socket | App-Rrdcached-Ping-Socket-Unix-custom | CMonitor status and performance of RRDcached daemon |
```

2024-05-14 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Ping-Socket | App-Rrdcached-Ping-Socket-Unix-custom | Check Updates cache of rrdcached daemon  |
```suggestion
| Ping-Socket | App-Rrdcached-Ping-Socket-Unix-custom | Monitor status and performance of RRDcached daemon |
```

2024-05-14 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md
> +| Stats       | App-Rrdcached-Stats-Unix-custom       | Check Updates cache of rrdcached daemon  |
```suggestion
| Stats       | App-Rrdcached-Stats-Unix-custom       | Monitor status and performance of RRDcached daemon |
```

2024-05-14 15:23 UTC, omercier approved these changes

2024-05-14 15:24 UTC, cg-tw approved these changes

2024-05-14 15:40 UTC, merged