CTOR-258-escalation-centreon-plugin-applications-protocol-cifs-mode-files-count-filter-file-not-working-with-max-depth
centreon/centreon-documentation pull request #3269
Opened 2024-05-03 07:21 UTC by Evan-Adam

CTOR:258

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] Cloud
- [X] Monitoring Connectors

2024-05-03 14:29 UTC, cg-tw requested changes

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| Files-Count | App-Protocol-Cifs-Files-Count-custom | Contrôle permettant le nombre de fichiers dans un répertoire         |
```suggestion
| Files-Count | App-Protocol-Cifs-Files-Count-custom | Contrôle permettant de vérifier le nombre de fichiers dans un répertoire         |
```

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
>  Pour superviser votre serveur CIFS, il est possible de réaliser une authentification par :
?

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| PROTOCOLCIFSTIMEOUT      | Timeout                                                                                                                                  |                   |
?

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| CRITICALSTATUS | Define the conditions to match for the status to be CRITICAL You can use the following variables: %{status}, %{message}                | %{message} !~ /authentication succeeded/i |
```suggestion
| CRITICALSTATUS | Define the conditions to match for the status to be CRITICAL. You can use the following variables: %{status}, %{message}                | %{message} !~ /authentication succeeded/i |             |
```

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| MAXDEPTH              | Number of level of directory to check. 0 mean current directory only.                                                                  | 0                 | X           |
```suggestion
| MAXDEPTH              | Number of levels of directories to check. 0 means current directory only.                                                                  | 0                 | X           |
```

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| DIRECTORY             | Directory name to check.                                                                                                               |                   | X           |
```suggestion
| DIRECTORY             | Name of the directory  to check.                                                                                                               |                   | X           |
```

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| FILTERFILE            | Filter files (can be a regexp. Directory in the name).                                                                                 |                   |             |
?

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| DIRECTORY         | Check files in the directory (no recursive)                                                                                            |                   | X           |
```suggestion
| DIRECTORY         | Check files in the directory (no recursion)                                                                                            |                   | X           |
```

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| MAXDEPTH     | Number of level of directory to check. 0 mean current directory only.                                                                  | 0                 | X           |
```suggestion
| MAXDEPTH     | Number of levels of directories to check. 0 means current directory only.                                                                  | 0                 | X           |
```

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| Option | Description |
empty

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +</Tabs>
empty

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| FTP-Commands   | App-Protocol-FTP-Commands-custom   | Contrôle permettant d'executer une commande sur un serveur FTP distant                                                         |
```suggestion
| FTP-Commands   | App-Protocol-FTP-Commands-custom   | Contrôle permettant d'exécuter une commande sur un serveur FTP distant                                                         |
```

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +</TabItem>
coming soon

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +as possible here as it will save time to everybody.*
no prerequisites

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| DIRECTORY    | Check files in the directory (no recursive)                                                                                                   |                   |             |
```suggestion
| DIRECTORY    | Check files in the directory (no recursion)                                                                                                   |                   |             |
```

2024-05-03 14:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| DIRECTORY    | Check files in the directory (no recursive)                                                                                            |                   |             |
```suggestion
| DIRECTORY    | Check files in the directory (no recursion)                                                                                            |                   |             |
```

2024-05-03 14:30 UTC, cg-tw commented
@Evan-Adam lots of problems here. I only reviewed the FR version, but all comments apply to the EN version too.

2024-05-15 11:40 UTC, cg-tw requested changes

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +	--cifs-password='' \
```suggestion
        --cifs-username='my-username' \
        --cifs-password='my-password' \
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| FTP-Login | App-Protocol-FTP-Login-custom | Contrôle la connexion FTP à distance via login/password |
```suggestion
| FTP-Login | App-Protocol-FTP-Login-custom | Contrôle la connexion FTP à distance via login/mot de passe|
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +User and password to connect to the ftp share.
```suggestion
Un identifiant et un mot de passe sont nécessaires pour se connecter au serveur FTP.
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| FTPUSERNAME     | Specify username for authentification.                                                                                                             |                   |
```suggestion
| FTPUSERNAME     | Specify username for authentication.                                                                                                             |                   |             |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| FTPPASSWORD     | Specify password for authentification.                                                                                                             |                   |
```suggestion
| FTPPASSWORD     | Specify password for authentication.                                                                                                             |                   |             |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --username    | Specify username for authentification
```suggestion
| --username    | Specify username for authentication                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --password    | Specify password for authentification
```suggestion
| --password    | Specify password for authentication                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --username    | Specify username for authentification                                               |
```suggestion
| --username    | Specify username for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --password    | Specify password for authentification                                               |
```suggestion
| --password    | Specify password for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --username    | Specify username for authentification                                               |
```suggestion
| --username    | Specify username for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --password    | Specify password for authentification                                               |
```suggestion
| --password    | Specify password for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --username    | Specify username for authentification                                               |
```suggestion
| --username    | Specify username for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --password    | Specify password for authentification                                               |
```suggestion
| --password    | Specify password for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| FTPUSERNAME     | Specify username for authentification.                                                                                                   |                   |             |
```suggestion
| FTPUSERNAME     | Specify username for authentication.                                                                                                   |                   |             |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| FTPPASSWORD     | Specify password for authentification.                                                                                                   |                   |             |
```suggestion
| FTPPASSWORD     | Specify password for authentication.                                                                                                   |                   |             |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --username    | Specify username for authentification
```suggestion
| --username    | Specify username for authentication                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --password    | Specify password for authentification
```suggestion
| --password    | Specify password for authentication                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --username    | Specify username for authentification                                               |
```suggestion
| --username    | Specify username for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --password    | Specify password for authentification                                               |
```suggestion
| --password    | Specify password for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --username    | Specify username for authentification                                               |
```suggestion
| --username    | Specify username for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --password    | Specify password for authentification                                               |
```suggestion
| --password    | Specify password for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --username    | Specify username for authentification                                               |
```suggestion
| --username    | Specify username for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| --password    | Specify password for authentification                                               |
```suggestion
| --password    | Specify password for authentication                                               |
```

2024-05-15 11:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +	--ssh-password=''  \
```suggestion
	--ssh-username='my-username' \
	--ssh-password='my-password' \
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| Files-Date    | App-Protocol-Cifs-Files-Date-custom  | Check modified time of files         |
```suggestion
| Files-Date    | App-Protocol-Cifs-Files-Date-custom  | Check last modified time of files         |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +	--cifs-password='' \
```suggestion
	--cifs-username='my-username' \
        --cifs-password='my-password' \
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-cifs.md
>  To monitor your CIFS server, you can use username authentication.
```suggestion
To monitor your CIFS server, the plugin needs to log in to it using a username and a password.
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +| FTP-Commands   | App-Protocol-FTP-Commands-custom   | Check several commands execution on a remote FTP server                          |
```suggestion
| FTP-Commands   | App-Protocol-FTP-Commands-custom   | Check  the execution of several commands on a remote FTP server                          |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +	--password='' \
```suggestion
	--username='username' \
	--password=password' \
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +| Files-Date    | App-Protocol-Sftp-Files-Date-custom  | Check modified time of files         |
```suggestion
| Files-Date    | App-Protocol-Sftp-Files-Date-custom  | Check last modified time of files         |
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
>  To monitor your SFTP server, you can use pubkey authentication and/or username authentication.
```suggestion
To monitor your SFTP server, the plugin can either log in using an SSH key, or use username authentication.
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +	--ssh-username='' \
```suggestion
	--ssh-username='my-username' \
```

2024-05-15 11:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
> +	--ssh-password=''  \
```suggestion
	--ssh-password='my-password'  \
```

2024-05-15 11:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| FILTERFILE            | Filter files (can be a regexp. Directory in the name).                                                                                 |                   |             |
@Evan-Adam filter files according to what?

2024-05-15 11:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
> +| PROTOCOLCIFSTIMEOUT      | Timeout                                                                                                                                  |                   |
@Evan-Adam what timeout? what does the plugin do?

2024-05-15 11:49 UTC, cg-tw requested changes

2024-05-15 11:49 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +<TabItem value="FTP-Commands" label="FTP-Commands">
there is a problem here

2024-05-15 11:49 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +User and password to connect to the ftp share.
```suggestion
The plugin will need a username and password to connect to the FTP share.
```

2024-05-15 11:51 UTC, cg-tw requested changes

2024-05-15 11:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ftp.md
> +</TabItem>
```suggestion
```

2024-05-16 08:56 UTC, omercier approved these changes

2024-05-16 08:57 UTC, merged