[CTOR-509] Update Jacarta Sensor page
centreon/centreon-documentation pull request #3276
Opened 2024-05-13 09:47 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-14 13:46 UTC, cg-tw requested changes

2024-05-14 13:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
> +| Sensors-Global | HW-Sensors-Jacarta-Sensors-Global-SNMP-custom | Check all sensors of equipment |
```suggestion
| Sensors-Global | HW-Sensors-Jacarta-Sensors-Global-SNMP-custom | Check all sensors on the equipment |
```

2024-05-14 13:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
```suggestion
```

2024-05-14 13:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
```suggestion
```

2024-05-14 13:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
> +
```suggestion
```

2024-05-21 15:20 UTC, cg-tw approved these changes

2024-05-21 15:22 UTC, omercier approved these changes

2024-05-21 15:23 UTC, merged