[CTOR-507] Update Geist p8000 sensor SNMP page
centreon/centreon-documentation pull request #3277
Opened 2024-05-13 14:33 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-14 16:14 UTC, omercier approved these changes

2024-05-15 12:41 UTC, cg-tw requested changes

2024-05-15 12:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-comet-p8000-snmp.md
> +| Sensors       | HW-Sensors-Comet-P8000-Sensors-SNMP-custom | Check all sensors of equipment |
```suggestion
| Sensors       | HW-Sensors-Comet-P8000-Sensors-SNMP-custom | Check all the sensors of the device |
```

2024-05-21 15:25 UTC, omercier approved these changes

2024-05-21 15:26 UTC, cg-tw approved these changes

2024-05-21 15:26 UTC, merged