[CTOR-511] Update Sensormetrix doc page
centreon/centreon-documentation pull request #3280
Opened 2024-05-14 14:53 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-15 12:15 UTC, cg-tw requested changes

2024-05-15 12:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-sensormetrix-em01-web.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
no prerequisites!

2024-05-15 12:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-sensors-sensormetrix-em01-web.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
no prerequisites!

2024-05-21 15:31 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-sensormetrix-em01-web.md
> +OK:  | 'voltage'=54V;;;;
```suggestion
OK: Voltage: 54V | 'voltage'=54V;;;;
```

2024-05-21 15:31 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-sensors-sensormetrix-em01-web.md
> +OK:  | 'voltage'=54V;;;;
```suggestion
OK: Voltage: 54V | 'voltage'=54V;;;;
```

2024-05-21 15:31 UTC, omercier approved these changes

2024-05-21 15:35 UTC, cg-tw approved these changes

2024-05-23 13:53 UTC, merged