doc(release): Prepare release notes for web 22.10.22, gorgone 22.10.7
centreon/centreon-documentation pull request #3284
Opened 2024-05-15 14:42 UTC by pkippes

…one 22.10.7)

web 22.10.22
gorgone 22.10.7

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-15 15:10 UTC, rsadik-ext approved these changes

2024-05-15 15:15 UTC, cg-tw requested changes

2024-05-15 15:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Security] Fixed SQLi in media management.
```suggestion
- [Security] Fixed several SQLi issues.
```

2024-05-15 15:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Enhancement] unattended.sh script now allows new options (Debian12, MariaDB versionalization, MySQL 8)
```suggestion
- [Enhancement] The unattended.sh script now offers new options (Debian12, MariaDB versioning, MySQL 8).
```

2024-05-15 15:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [API] Fixed an issue on downtimes for services linked to service group via service template.
```suggestion
- [API] Fixed an issue affecting downtimes on services linked to a service group via a service template.
```

2024-05-15 15:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
> +- [Configuration] Fixed an issue in Service Categories configuration page (blank page in some cases).
```suggestion
- [Configuration] Fixed an issue where the Service Categories configuration page could appear blank.
```

2024-05-15 15:15 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Enhancement] unattended.sh script now allows new options (Debian12, MariaDB versionalization, MySQL 8)
```suggestion
- [Enhancement] The unattended.sh script now offers new options (Debian12, MariaDB versioning, MySQL 8).
```

2024-05-15 15:15 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Configuration] Fixed an issue in Service Categories configuration page (blank page in some cases).
```suggestion
- [Configuration] Fixed an issue where the Service Categories configuration page could appear blank.
```

2024-05-15 15:15 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [API] Fixed an issue on downtimes for services linked to service group via service template.
```suggestion
- [API] Fixed an issue affecting downtimes on services linked to a service group via a service template.
```

2024-05-15 15:15 UTC, cg-tw commented on versioned_docs/version-22.10/releases/centreon-os.md
> +- [Security] Fixed SQLi in media management.
```suggestion
- [Security] Fixed several SQLi issues.
```

2024-05-16 15:39 UTC, cg-tw approved these changes

2024-05-16 15:39 UTC, merged