Add Easyvista Rest topic in 24.04 and 24.10 versions
centreon/centreon-documentation pull request #3295
Opened 2024-05-17 13:40 UTC by smau-centreon

## Description

Add Easyvista Rest topic in 24.04 and 24.10 versions

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x
- [x] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-17 13:48 UTC, fmattesct requested changes

2024-05-17 13:48 UTC, fmattesct commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/itsm/ot-easyvista-rest-api.md
> +## Configurer votre serveur Elasticsearch
```suggestion
## Configurer votre serveur EasyVista
```

2024-05-17 13:48 UTC, fmattesct commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/itsm/ot-easyvista-rest-api.md
> +## Configurer votre serveur Elasticsearch
```suggestion
## Configurer votre serveur EasyVista
```

2024-05-17 15:18 UTC, fmattesct approved these changes

2024-05-21 07:49 UTC, cg-tw approved these changes

2024-05-21 07:50 UTC, merged