[CTOR-571] Create Symbol WiNG SNMP doc page
centreon/centreon-documentation pull request #3301
Opened 2024-05-21 08:39 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-11 15:40 UTC, lucie-dubrunfaut approved these changes

2024-06-12 11:44 UTC, cg-tw requested changes

2024-06-12 11:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-symbol-wing-snmp.md
> +| Packet-Errors        | Net-Symbol-wing-Packet-Errors-Global-SNMP-custom | Contrôle le pourcentage de paquets en erreur/écarté de plusieurs interfaces réseau | X          |
```suggestion
| Packet-Errors        | Net-Symbol-wing-Packet-Errors-Global-SNMP-custom | Contrôle le pourcentage de paquets en erreur/écartés de plusieurs interfaces réseau | X          |
```

2024-06-12 11:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-symbol-wing-snmp.md
> +| Net-Symbol-Wing-SNMP-Packet-Errors-Name | Découvre les interfaces réseau et supervise les paquets erronés et rejetés  |
signale au lieu de supervise?

2024-06-12 11:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-symbol-wing-snmp.md
> +| Packet-Errors        | Net-Symbol-wing-Packet-Errors-Global-SNMP-custom | Check packets on errors/discards of multiple network interfaces | X          |
```suggestion
| Packet-Errors        | Net-Symbol-wing-Packet-Errors-Global-SNMP-custom | Check packets in error/discarded from multiple network interfaces | X          |
```

2024-06-12 11:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-symbol-wing-snmp.md
> +| Traffic-Generic-Id   | Net-Symbol-Wing-Traffic-Generic-Id-SNMP-custom   | Check traffic of an network interface                           |            |
```suggestion
| Traffic-Generic-Id   | Net-Symbol-Wing-Traffic-Generic-Id-SNMP-custom   | Check traffic of a network interface                           |            |
```

2024-06-12 11:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-symbol-wing-snmp.md
> +| Traffic-Generic-Name | Net-Symbol-Wing-Traffic-Generic-Name-SNMP-custom | Check traffic of an network interface                           | X          |
```suggestion
| Traffic-Generic-Name | Net-Symbol-Wing-Traffic-Generic-Name-SNMP-custom | Check traffic of a network interface                           | X          |
```

2024-06-12 11:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-symbol-wing-snmp.md
> +| Traffic-Global       | Net-Symbol-Wing-Traffic-Global-SNMP-custom       | Check traffic of an network interface                           |            |
```suggestion
| Traffic-Global       | Net-Symbol-Wing-Traffic-Global-SNMP-custom       | Check traffic of a network interface                           |            |
```

2024-06-18 15:19 UTC, lucie-dubrunfaut approved these changes

2024-06-18 15:19 UTC, merged