doc(release): Prepare release notes for web 23.04.18 / gorgone 23.04.14
centreon/centreon-documentation pull request #3313
Opened 2024-05-24 14:17 UTC by pkippes

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-24 15:05 UTC, cg-tw requested changes

2024-05-24 15:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +
```suggestion
```

2024-05-24 15:05 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +</details>
```suggestion
```

2024-05-27 12:27 UTC, smau-centreon approved these changes

2024-05-27 12:51 UTC, merged