doc(release): Prepare release notes for collect 23.10.7
centreon/centreon-documentation pull request #3315
Opened 2024-05-27 14:09 UTC by pkippes

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-27 14:16 UTC, sfarouq-ext submitted a review, later dismissed

2024-05-27 14:31 UTC, smau-centreon submitted a review, later dismissed

2024-05-28 07:17 UTC, smau-centreon approved these changes

2024-05-28 07:30 UTC, cg-tw requested changes

2024-05-28 07:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Broker] Fixed a stability issue that could occur when a LVM snapshot is launched to backup the database.
```suggestion
- [Broker] Fixed a stability issue that could occur when a LVM snapshot was launched to backup the database.
```

2024-05-28 07:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Broker] Fixed an issue that caused MySQL errors in Broker logs due to attempts to insert relations between BAs and disabled time periods.
```suggestion
- [Broker] Fixed an issue that caused MySQL errors in Broker logs, due to attempts to insert relations between BAs and disabled time periods.
```

2024-05-28 07:30 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Broker] Fixed a stability issue that could occur when a LVM snapshot is launched to backup the database.
```suggestion
- [Broker] Fixed a stability issue that could occur when a LVM snapshot was launched to backup the database.
```

2024-05-28 07:30 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Broker] Fixed an issue that caused MySQL errors in Broker logs due to attempts to insert relations between BAs and disabled time periods.
```suggestion
- [Broker] Fixed an issue that caused MySQL errors in Broker logs, due to attempts to insert relations between BAs and disabled time periods.
```

2024-05-28 09:59 UTC, smau-centreon approved these changes

2024-05-28 10:07 UTC, cg-tw requested changes

2024-05-28 10:07 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Broker] Fixed a stability issue that could occur when a LVM snapshot was launched to backup the database.
```suggestion
- [Broker] Fixed a stability issue that could occur when an LVM snapshot was launched to backup the database.
```

2024-05-28 10:07 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Broker] Fixed a stability issue that could occur when a LVM snapshot was launched to backup the database.
```suggestion
- [Broker] Fixed a stability issue that could occur when an LVM snapshot was launched to backup the database.
```

2024-05-28 10:08 UTC, cg-tw approved these changes

2024-05-28 10:32 UTC, merged