[CTOR-610] Refresh Veeam doc page
centreon/centreon-documentation pull request #3317
Opened 2024-05-27 14:41 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-05-28 15:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-nrpe.md
```suggestion

The *Veeam* Monitoring Connector works with the Centreon NSClient++ monitoring agent and 
Powershell to check the operating status of a Veeam Server.

```

2024-05-28 15:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-nrpe.md
> +/usr/lib64/nagios/plugins//check_centreon_nrpe -H 10.0.0.1 -p 5666 -t 55  -c check_centreon_plugins -a 'apps::backup::veeam::local::plugin' 'tape-jobs'  ' \
problem here too

2024-05-28 15:35 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-nrpe.md
> +	--list-mode
```suggestion
	--list-mode'
```

2024-05-30 09:43 UTC, cg-tw requested changes

2024-05-30 09:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-nrpe.md
```suggestion

Le connecteur de supervision *Veeam* fonctionne avec l'agent de supervision Centreon NSClient++ et Powershell, et contrôle le statut opérationnel d'un serveur Veeam.

```

2024-05-30 09:43 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-veeam-nrpe.md
> +Powershell to check the operating status of a Veeam Server.
```suggestion
Powershell to check the operating status of a Veeam server.
```

2024-05-30 09:44 UTC, cg-tw approved these changes

2024-05-30 09:44 UTC, cg-tw approved these changes

2024-06-04 15:51 UTC, omercier approved these changes

2024-06-04 15:51 UTC, merged