Monic 178
centreon/centreon-documentation pull request #332
Opened 2020-08-31 10:06 UTC by mhuber-centreon

Waiting for more info on the outputs

2020-10-05 07:19 UTC, Sims24 requested changes
Metrics name are wrong. 
Few indents issus

2020-10-20 12:31 UTC, thibaults-centreon commented
A lot of fixes and changed have been made. @Sims24 please let me know if this sounds better.
Thanks

2020-10-20 15:09 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-sccm-nsclient.md
> +<!--DOCUSAURUS_CODE_TABS-->
I can't find the closing docusaurus tab at the end.

2020-10-20 15:10 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-sccm-nsclient.md
> +* [RestAPI](https://docs.centreon.com/current/en/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-restapi.html)
Could you use relative paths instead ? ../../

2020-10-20 15:20 UTC, Sims24 approved these changes

2020-10-21 11:31 UTC, Sims24 approved these changes

2020-10-26 12:51 UTC, merged