[Cloud] Stream connectors
centreon/centreon-documentation pull request #3339
Opened 2024-06-05 12:02 UTC by cg-tw

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [x] Cloud
- [ ] Monitoring Connectors

2024-06-05 12:10 UTC, nmagniezCentreon requested changes

2024-06-05 12:10 UTC, nmagniezCentreon commented on cloud/integrations/stream-connectors-cloud.md
> +* Warp10
La liste est pas à jour...dommage.
Je te laisse voir avec Florian pour la doc on-prem. Pour Cloud, la liste est ici => https://github.com/centreon/centreon-stream-connector-scripts/tree/develop/centreon-certified

2024-06-06 08:04 UTC, fmattesct approved these changes

2024-06-06 08:31 UTC, nmagniezCentreon approved these changes

2024-06-06 08:33 UTC, merged