[CTOR-609] refresh Protocol TCP doc page
centreon/centreon-documentation pull request #3340
Opened 2024-06-05 13:17 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-11 15:46 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
>  |:------|:------------------|:------------|
```suggestion
```

2024-06-11 15:46 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **App-Protocol-Tcp-custom** est utilisé.
```suggestion
Aucun modèle de service n'est lié à ce modèle d'hôte.
```

2024-06-11 15:46 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
>  |:------|:------------------|:------------|
```suggestion
```

2024-06-11 15:46 UTC, omercier commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **App-Protocol-Tcp-Only-custom** est utilisé.
```suggestion
Aucun modèle de service n'est lié à ce modèle d'hôte.
```

2024-06-11 15:46 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +| TIMEOUT      | Connection timeout in seconds (default: 3)                                                         | 5                 |             |
description said 3 and default value 5

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +| TIMEOUT      | Connection timeout in seconds (default: 3)                                                         | 5                 |             |
```suggestion
| TIMEOUT      | Connection timeout in seconds                                                         | 5                 |             |
```

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +| PACKETS       | Number of packets to send (default: 5)                                                             | 5                 |             |
```suggestion
| PACKETS       | Number of packets to send                                                            | 5                 |             |
```

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +| TIMEOUT       | Set timeout in seconds (default: 5)                                                                | 5                 |             |
```suggestion
| TIMEOUT       | Set timeout in seconds                                                                | 5                 |             |
```

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +                                                                                                   |                   |             |
```suggestion
```

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
>  |:--------------|:------------------|:--------------------|
```suggestion
No service template is linked to this host template.
```

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
>  |:--------------|:------------------|:--------------------|
```suggestion
No service template is linked to this host template.
```

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +| TIMEOUT      | Connection timeout in seconds (default: 3)                                                         | 5                 |             |
```suggestion
| TIMEOUT      | Connection timeout in seconds                                                         | 5                 |             |
```

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +| PACKETS       | Number of packets to send (default: 5)                                                             | 5                 |             |
```suggestion
| PACKETS       | Number of packets to send                                                            | 5                 |             |
```

2024-06-11 15:56 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +| TIMEOUT       | Set timeout in seconds (default: 5)                                                                | 5                 |             |
```suggestion
| TIMEOUT       | Set timeout in seconds                                                                 | 5                 |             |
```

2024-06-12 11:31 UTC, cg-tw requested changes

2024-06-12 11:31 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-12 11:31 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-12 11:31 UTC, cg-tw approved these changes

2024-06-18 15:32 UTC, merged