Ctor 619 refresh applications pfsense fauxapi
centreon/centreon-documentation pull request #3350
Opened 2024-06-10 14:20 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-12 12:26 UTC, cg-tw requested changes

2024-06-12 12:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
>  Dans son principe, FauxAPI lit simplement le fichier config.xml de pfSense, le convertit en JSON et retourne à l'appelant de l'API.
le?

2024-06-12 12:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-12 12:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-12 12:26 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +| Backup-Files  | App-Pfsense-Backup-Files-Fauxapi-custom | Check the Backup files Pfsense using Fauxapi |
```suggestion
| Backup-Files  | App-Pfsense-Backup-Files-Fauxapi-custom | Check the Pfsense Backup files using Fauxapi |
```

2024-06-12 12:26 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +| Gateways      | App-Pfsense-Gateways-Fauxapi-custom     | Check the Gateways Pfsense using Fauxapi     |
```suggestion
| Gateways      | App-Pfsense-Gateways-Fauxapi-custom     | Check the Pfsense Gateways using Fauxapi     |
```

2024-06-12 12:26 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +| Rules         | App-Pfsense-Rules-Fauxapi-custom        | Check the rules Pfsense using Fauxapi        |
```suggestion
| Rules         | App-Pfsense-Rules-Fauxapi-custom        | Check the Pfsense rules using Fauxapi        |
```

2024-06-12 12:26 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-18 15:37 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +At its core FauxAPI simply reads the core pfSense config.xml file, converts it to JSON and returns to the API caller.
```suggestion
```

2024-06-18 15:38 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +FauxAPI provides easy backup and restore API interfaces that by default store configuration backups on all configuration write operations thus it is very easy to roll-back even if the API user manage
```suggestion
```

2024-06-18 15:39 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
>  Dans son principe, FauxAPI lit simplement le fichier config.xml de pfSense, le convertit en JSON et retourne à l'appelant de l'API.
```suggestion
```

2024-06-18 15:39 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
> +sur toutes les opérations d'écriture de la configuration ; il est donc très facile de revenir en arrière même si l'utilisateur de l'API parvient à déployer une configuration "très cassée".
```suggestion
```

2024-06-18 15:40 UTC, cg-tw approved these changes

2024-06-18 15:41 UTC, omercier approved these changes

2024-06-18 15:57 UTC, merged