[CTOR-621] refresh OSPF Protocol doc page
centreon/centreon-documentation pull request #3360
Opened 2024-06-12 14:26 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-13 12:03 UTC, cg-tw requested changes

2024-06-18 15:44 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ospf.md
> +Pour utiliser ce Pack, le service SNMP doit être correctement configuré sur votre appareil.
```suggestion
### Configuration SNMP

Afin de superviser votre ressource en SNMP, il est nécessaire de configurer l'agent SNMP
sur la ressource comme indiqué sur la documentation officielle du constructeur.

### Flux réseau

La communication doit être possible sur le port UDP 161 depuis le collecteur
Centreon vers la ressource supervisée.
```

2024-06-18 15:45 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-protocol-ospf.md
> +To use this Pack, the SNMP service must be properly configured on your device.
```suggestion
### SNMP Configuration

To use this pack, the SNMP service must be properly configured on your ressource.
Please refer to the official documentation from the constructor.

### Network flow

The target resource must be reachable from the Centreon poller on the UDP/161
SNMP port.

## Installing the monitoring connector
```

2024-06-18 15:45 UTC, cg-tw approved these changes

2024-06-18 15:45 UTC, omercier approved these changes

2024-06-18 17:23 UTC, merged