[CTOR-618] refresh Oracle VM Manager API doc page
centreon/centreon-documentation pull request #3361
Opened 2024-06-12 14:34 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-13 12:06 UTC, cg-tw requested changes

2024-06-13 12:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ovm-api.md
>  Afin de contrôler l'application Oracle VM Manager, l'API Rest doit être configuré (cf: https://docs.oracle.com/en/virtualization/oracle-vm/3.4/developer/vmapi-preface)
```suggestion
Afin de contrôler l'application Oracle VM Manager, l'API Rest doit être configurée (cf: https://docs.oracle.com/en/virtualization/oracle-vm/3.4/developer/vmapi-preface)
```

2024-06-18 15:53 UTC, cg-tw approved these changes

2024-06-18 15:54 UTC, omercier approved these changes

2024-06-18 17:22 UTC, merged