[CTOR-615] refresh Node Exporter linux Metrics doc page
centreon/centreon-documentation pull request #3390
Opened 2024-06-19 08:31 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-19 11:25 UTC, cg-tw requested changes

2024-06-19 11:25 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-linux.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-19 11:25 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-linux.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-20 08:00 UTC, lucie-dubrunfaut submitted a review, later dismissed

2024-06-25 15:28 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-linux.md
> +| NODEEXPORTERPORT  | Port used (default: 80)                                                                              | 9100              |             |
```suggestion
| NODEEXPORTERPORT  | Port used                                                                              | 9100              |             |
```

2024-06-25 15:28 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-linux.md
> +| NODEEXPORTERPORT  | Port used (default: 80)                                                                              | 9100              |             |
```suggestion
| NODEEXPORTERPORT  | Port used                                                                             | 9100              |             |
```

2024-06-25 15:29 UTC, lucie-dubrunfaut approved these changes

2024-06-25 15:30 UTC, omercier approved these changes

2024-06-25 15:56 UTC, merged