[CTOR-614] refresh Keepalived SNMP doc page
centreon/centreon-documentation pull request #3391
Opened 2024-06-19 09:22 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-19 11:29 UTC, cg-tw requested changes

2024-06-19 11:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-19 11:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-19 11:29 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
> +OK: All VRRP instances are ok | '*vrrp*#status'=;;;;
'*vrrp*#status'=;;;; -> rien du tout?

2024-06-19 11:29 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-19 11:29 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-06-19 11:29 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
> +OK: All VRRP instances are ok | '*vrrp*#status'=;;;;
same

2024-06-25 15:33 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
> +| SNMP Agents     | Discover your resources through an SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a templ
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](https://docs.centreon.com/fr/pp/integrations/plugin-packs/procedures/applications-protocol-snmp/) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **App-Keepalived-SNMP-custom** |
```

2024-06-25 15:35 UTC, lucie-dubrunfaut approved these changes

2024-06-25 15:35 UTC, cg-tw approved these changes

2024-06-25 15:36 UTC, omercier approved these changes

2024-06-25 15:57 UTC, merged