[CTOR-613] refresh Gorgone Rest API doc page
centreon/centreon-documentation pull request #3392
Opened 2024-06-19 13:23 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-24 12:40 UTC, cg-tw requested changes

2024-06-24 12:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-gorgone-restapi.md
>  </Tabs>
Prérequis imprécis : il faut ajouter ça où?

2024-06-24 12:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-gorgone-restapi.md
> +| Nodes         | App-Gorgone-Nodes-Restapi-custom  | Check nodes status  |
```suggestion
| Nodes         | App-Gorgone-Nodes-Restapi-custom  | Check the status of the nodes  |
```

2024-06-25 15:39 UTC, omercier approved these changes

2024-06-25 15:40 UTC, merged