[CTOR-612] refresh Informix DB SNMP doc page
centreon/centreon-documentation pull request #3393
Opened 2024-06-19 13:46 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-24 13:47 UTC, cg-tw requested changes

2024-06-24 13:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +OK: All instances are ok | '*global*#sessions'=;;;0;
;;;0;?

2024-06-24 13:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +| Global-Cache  | App-DB-Informix-Global-Cache-SNMP-custom  | Check write/read cached |
```suggestion
| Global-Cache  | App-DB-Informix-Global-Cache-SNMP-custom  | Check write/read cache |
```

2024-06-24 13:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +| Logfile-Usage | App-DB-Informix-Logfile-Usage-SNMP-custom | Check log files usage   |
```suggestion
| Logfile-Usage | App-DB-Informix-Logfile-Usage-SNMP-custom | Check log file usage   |
```

2024-06-24 13:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +OK: All instances are ok | '*global*#sessions'=;;;0;
same as FR

2024-06-25 15:41 UTC, omercier approved these changes

2024-06-25 15:42 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +| SNMP Agents     | Discover your resources through an SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a templ
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](https://docs.centreon.com/fr/pp/integrations/plugin-packs/procedures/applications-protocol-snmp/) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **App-DB-Informix-SNMP-custom** |
```

2024-06-25 15:44 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +| WARNINGSTATUS  | Define the conditions to match for the status to be WARNING (default: ''). You can use the following variables: %{status}, %{display}                             |
```suggestion
| WARNINGSTATUS  | Define the conditions to match for the status to be WARNING. You can use the following variables: %{status}, %{display}                             |                             |             |
```

2024-06-25 15:44 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +| UNKNOWNSTATUS  | Define the conditions to match for the status to be UNKNOWN (default: ''). You can use the following variables: %{status}, %{display}                             |
```suggestion
| UNKNOWNSTATUS  | Define the conditions to match for the status to be UNKNOWN. You can use the following variables: %{status}, %{display}                             |                             |             |
```

2024-06-25 15:44 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +| UNKNOWNSTATUS  | Define the conditions to match for the status to be UNKNOWN (default: ''). You can use the following variables: %{status}, %{display}                             |
```suggestion
| UNKNOWNSTATUS  | Define the conditions to match for the status to be UNKNOWN. You can use the following variables: %{status}, %{display}                             |                             |             |
```

2024-06-25 15:44 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +| WARNINGSTATUS  | Define the conditions to match for the status to be WARNING (default: ''). You can use the following variables: %{status}, %{display}                             |
```suggestion
| WARNINGSTATUS  | Define the conditions to match for the status to be WARNING. You can use the following variables: %{status}, %{display}                             |                             |             |
```

2024-06-25 15:46 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +	--critical-sessions=''
```suggestion
	--warning-sessions='10' \
	--critical-sessions='20'
```

2024-06-25 15:47 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
> +	--critical-sessions=''
```suggestion
	--warning-sessions='10' \
	--critical-sessions='20'
```

2024-06-25 15:48 UTC, lucie-dubrunfaut approved these changes

2024-06-25 15:48 UTC, cg-tw approved these changes

2024-06-25 18:01 UTC, merged