[CTOR-606] refresh LDAP Server doc page
centreon/centreon-documentation pull request #3396
Opened 2024-06-24 09:26 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-24 13:41 UTC, cg-tw requested changes

2024-06-24 13:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ldap.md
>  The remote server must have an LDAP service running and available. A user and
FR

2024-06-24 13:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ldap.md
> +| LDAP-Search | App-Protocol-LDAP-Search-custom | Contrôle une recherche vers un serveur LDAP |
si ça correspond à ldap.request.entries.count, c'est sans doute "retourne le nombre d'entrées dans une instance LDAP" ou un truc du genre

2024-06-24 13:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ldap.md
> +| LDAP-Search   | App-Protocol-LDAP-Search-custom | Check search to a LDAP server |
see FR

2024-06-24 13:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ldap.md
> +password dedicated to monitoring is needed for security reasons.
```suggestion
password dedicated to the monitoring are needed for security reasons.
```

2024-06-28 13:14 UTC, YanMeddour commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ldap.md
> +| LDAP-Search | App-Protocol-LDAP-Search-custom | Contrôle une recherche vers un serveur LDAP |
en lisant le code je comprend que ca permet de vérifier les résultats des recherches LDAP sur un serveur LDAP.

2024-07-02 15:26 UTC, cg-tw requested changes

2024-07-02 15:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ldap.md
> +| LDAP-Search | App-Protocol-LDAP-Search-custom | Contrôle une recherche vers un serveur LDAP |
```suggestion
| LDAP-Search | App-Protocol-LDAP-Search-custom | Effectue une recherche dans un annuaire LDAP et contrôle la cohérence des résultats |
```

2024-07-02 15:26 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-protocol-ldap.md
> +| LDAP-Search   | App-Protocol-LDAP-Search-custom | Check search to a LDAP server |
```suggestion
| LDAP-Search   | App-Protocol-LDAP-Search-custom | Performs a search in a LDAP server ans check that the results are consistent |
```

2024-07-02 15:27 UTC, cg-tw approved these changes

2024-07-02 15:27 UTC, omercier approved these changes

2024-07-02 15:42 UTC, merged