[CTOR-602] refresh Microsoft DHCP SNMP doc page
centreon/centreon-documentation pull request #3400
Opened 2024-06-25 13:08 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-06-25 15:55 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md
> +| SNMP Agents     | Discover your resources through an SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a templ
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](https://docs.centreon.com/fr/pp/integrations/plugin-packs/procedures/applications-protocol-snmp/) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **App-Microsoft-Dhcp-SNMP-custom** |
```

2024-06-26 09:49 UTC, cg-tw requested changes

2024-06-26 09:49 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md
>  To control your Microsoft DHCP software, the SNMP must be configured.
Standard SNMP prerequisites

2024-06-26 09:49 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md
> +OK: All subnets are ok | '*subnets*#subnet.addresses.usage.count'=;;;0;total'*subnets*#subnet.addresses.free.count'=;;;0;total'*subnets*#subnet.addresses.usage.percentage'=%;;;0;100'*subnets*#subnet.
is the example ok?

2024-06-26 09:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md
>  Afin de contrôler votre application Microsoft DHCP, le SNMP doit être configuré.
mettre les prérequis standard SNMP

2024-06-26 09:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md
> +OK: All subnets are ok | '*subnets*#subnet.addresses.usage.count'=;;;0;total'*subnets*#subnet.addresses.free.count'=;;;0;total'*subnets*#subnet.addresses.usage.percentage'=%;;;0;100'*subnets*#subnet.
exemple ok?

2024-07-02 15:20 UTC, cg-tw approved these changes

2024-07-02 15:21 UTC, omercier approved these changes

2024-07-02 15:43 UTC, merged