[CTOR-654] refresh Azure Elastic Pool doc page
centreon/centreon-documentation pull request #3409
Opened 2024-06-27 14:32 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-07-09 13:18 UTC, cg-tw requested changes

2024-07-09 13:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +| Log-Usage | Cloud-Azure-Database-Elasticpool-Log-Api-custom      | Contrôle l'utilisation des fichiers et bases logs Elastic Pools Azure |
bases logs?

2024-07-09 13:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +| Cpu   | Cloud-Azure-Database-Elasticpool-Cpu-Api-custom | Contrôle l'utilisation CPU des Elastic Pools vCore Azure |
vCore?

2024-07-09 13:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +> Paramétrez les options suivantes dans la macro EXTRAOPTIONS si vous superviser des ressources Microsoft Azure géré par 21Vianet (Azure China):
```suggestion
> Paramétrez les options suivantes dans la macro EXTRAOPTIONS si vous supervisez des ressources Microsoft Azure gérées par 21Vianet (Azure China):
```

2024-07-09 13:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +OK: Allocated data storage percentage: 29 % Allocated data storage: 99 B Storage usage percentage: 2 % Storage usage: 21 B | 'elasticpool.storage.data.allocated.percentage'=29%;;;;'elasticpool.storag
l'exemple est bon?

2024-07-09 13:18 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +OK: Allocated data storage percentage: 29 % Allocated data storage: 99 B Storage usage percentage: 2 % Storage usage: 21 B | 'elasticpool.storage.data.allocated.percentage'=29%;;;;'elasticpool.storag
l'exemple est bon?

2024-07-09 14:28 UTC, cg-tw submitted a review, later dismissed

2024-07-09 15:51 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +| AZURERESOURCE      | Set resource name or ID (required)                                                                                         |                   |             |
```suggestion
| AZURERESOURCE      | Set resource name or ID (required)                                                                                         |                   |      X      |
```

2024-07-09 15:51 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +| AZURERESOURCE      | Set resource name or ID (required)                                                                                         |                   |             |
```suggestion
| AZURERESOURCE      | Set resource name or ID (required)                                                                                         |                   |      X      |
```

2024-07-09 15:52 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +| AZURERESOURCE      | Set resource name or ID (required)                                                                                         |                   |             |
```suggestion
| AZURERESOURCE      | Set resource name or ID (required)                                                                                         |                   |      X      |
```

2024-07-09 15:52 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
> +| AZURERESOURCE      | Set resource name or ID (required)                                                                                         |                   |             |
```suggestion
| AZURERESOURCE      | Set resource name or ID (required)                                                                                         |                   |      X      |
```

2024-07-09 16:02 UTC, lucie-dubrunfaut approved these changes

2024-07-10 13:49 UTC, cg-tw approved these changes

2024-07-10 13:49 UTC, merged