[CTOR-657] refresh Azure Cache for Redis doc page
centreon/centreon-documentation pull request #3415
Opened 2024-07-01 14:44 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-07-09 13:47 UTC, cg-tw requested changes

2024-07-09 13:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
> +données à faible latence et à haut débit critique pour les applications modernes.
```suggestion
```

2024-07-09 13:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
>  les données fréquemment utilisées dans la mémoire du serveur, qui peut être écrite et lue rapidement. Redis constitue une solution de stockage de
```suggestion
```

2024-07-09 13:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
>  Cosmos DB. Il est possible d'utiliser les 2 modes proposés par Microsoft: RestAPI ou Azure CLI.
Cosmos DB?

2024-07-09 13:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
>  Azure Cache for Redis provides an in-memory data store based on the Redis software. Redis improves the performance and scalability of an application
```suggestion
```

2024-07-09 13:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
> +> Set the following options in the EXTRAOPTIONS macro if you are monitoring resource from Microsoft Azure operated by 21Vianet (Azure China):
```suggestion
> Set the following options in the EXTRAOPTIONS macro if you are monitoring resources from Microsoft Azure operated by 21Vianet (Azure China):
```

2024-07-16 15:25 UTC, lucie-dubrunfaut approved these changes

2024-07-16 15:25 UTC, cg-tw approved these changes

2024-07-16 15:25 UTC, merged