CTOR-728 Plugin(network::sonus::sbc::snmp) - Mode(cpu) : Unknown option
centreon/centreon-documentation pull request #3436
Opened 2024-07-16 12:32 UTC by lucie-dubrunfaut

## Description

fix mode cpu

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-07-16 15:40 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +Le connecteur de supervision **Sonus SBC ** apporte un modèle d'hôte :
```suggestion
Le connecteur de supervision **Sonus SBC** apporte un modèle d'hôte :
```

2024-07-16 15:40 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +The Monitoring Connector **Sonus SBC ** brings a host template:
```suggestion
The Monitoring Connector **Sonus SBC** brings a host template:
```

2024-07-16 15:41 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) cpour obtenir la règle de découverte et créez un modificat
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **Net-Sonus-Sbc-SNMP-custom**. |
```

2024-07-16 15:42 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
TabItem value="Debian 11 & 12" label="Debian 11 & 12"
```

2024-07-16 15:42 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
TabItem value="Debian 11 & 12" label="Debian 11 & 12"
```

2024-07-16 15:43 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-07-16 15:43 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +<TabItem value="Debian 11" label="Debian 11">
```suggestion
<TabItem value="Debian 11 & 12" label="Debian 11 & 12">
```

2024-07-16 15:45 UTC, omercier approved these changes

2024-07-22 12:33 UTC, cg-tw requested changes

2024-07-22 12:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| Call-Statistics | Net-Sonus-Sbc-Call-Statistics-SNMP-custom | Contrôle les statistiques liés aux appels passés au travers de l'équipement
```suggestion
| Call-Statistics | Net-Sonus-Sbc-Call-Statistics-SNMP-custom | Contrôle les statistiques liées aux appels passés via l'équipement                                                                                                  |
```

2024-07-22 12:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| Dsp-Statistics  | Net-Sonus-Sbc-Dsp-Statistics-SNMP-custom  | Contrôle les statistiques liés au traitement du signal effectué par la SBC Sonus
```suggestion
| Dsp-Statistics  | Net-Sonus-Sbc-Dsp-Statistics-SNMP-custom  | Contrôle les statistiques liées au traitement du signal effectué par la SBC Sonus                                                                                             |
```

2024-07-22 12:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| Cpu-Detailed | Net-Sonus-Sbc-Cpu-Detailed-SNMP-custom | Contrôle du taux d'utilisation du CPU de la machine. Ce contrôle pourra remonter d'avantage de détails sur son utilisation  |            |
```suggestion
| Cpu-Detailed | Net-Sonus-Sbc-Cpu-Detailed-SNMP-custom | Contrôle du taux d'utilisation du CPU de la machine. Ce contrôle pourra remonter davantage de détails sur son utilisation  |            |
```

2024-07-22 12:33 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
>  | Net-Sonus-Sbc-SNMP-Interface-Name | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Sonus-Sbc-SNMP-Interface-Name | Découvre les interfaces réseau et supervise le statut et l'utilisation |
```

2024-07-22 12:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| Call-Statistics | Net-Sonus-Sbc-Call-Statistics-SNMP-custom | Check statistics of calls managed through this equipement
```suggestion
| Call-Statistics | Net-Sonus-Sbc-Call-Statistics-SNMP-custom | Check statistics of calls managed through the device                                                                                          |
```

2024-07-22 12:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| Channels        | Net-Sonus-Sbc-Channels-SNMP-custom        | Check state and status of channels configured on the equipment
```suggestion
| Channels        | Net-Sonus-Sbc-Channels-SNMP-custom        | Check state and status of channels configured on the device |
```

2024-07-22 12:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| Cpu             | Net-Sonus-Sbc-Cpu-SNMP-custom             | Check the rate of utilization of CPU for the machine. This check can give the average CPU utilization rate and the rate per CPU for mul
```suggestion
| Cpu             | Net-Sonus-Sbc-Cpu-SNMP-custom             | Check the rate of utilization of the CPU for the machine. This check can give the average CPU utilization rate and the rate per CPU for multi-core CPUs |
```

2024-07-22 12:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| Swap            | Net-Sonus-Sbc-Swap-SNMP-custom            | Check the rate of utilization of SWAP memory on the Sonus
```suggestion
| Swap            | Net-Sonus-Sbc-Swap-SNMP-custom            | Check the rate of utilization of the SWAP memory on the Sonus                                                                                          |
```

2024-07-22 12:33 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
> +| Cpu-Detailed  | Net-Sonus-Sbc-Cpu-Detailed-SNMP-custom | Check the rate of utilization of CPU for the machine. This check can give further details on its utilization  |            |
```suggestion
| Cpu-Detailed  | Net-Sonus-Sbc-Cpu-Detailed-SNMP-custom | Check the rate of CPU utilization for the machine. This check can give further details on its utilization  |            |
```

2024-07-23 15:23 UTC, cg-tw approved these changes

2024-07-23 15:46 UTC, merged