doc(release): Prepare release notes for collect 23.04
centreon/centreon-documentation pull request #3438
Opened 2024-07-16 15:47 UTC by tuntoja

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [x] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-07-16 18:32 UTC, sfarouq-ext commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `July 7, 2024`
Hello is it July 17 ?

2024-07-17 13:48 UTC, cg-tw requested changes

2024-07-17 13:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Broker] If a metric can't be inserted in the database, the metric is dropped with an error log but Broker continues to work, and others metrics are still inserted.
```suggestion
- [Broker] Fixed an issue that occurred when inserting too large metrics into the database, which resulted in an error log.
```

2024-07-17 13:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
> +- [Broker] Fixed an issue while trying to Connect to MySQL 8.0.35.
```suggestion
- [Broker] Added support for the default connection method to MySQL 8.0.35.
```

2024-07-17 13:48 UTC, cg-tw requested changes

2024-07-17 13:48 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +Release date: `July 7, 2024`
```suggestion
Release date: `July 17, 2024`
```

2024-07-17 13:48 UTC, cg-tw commented on versioned_docs/version-23.04/releases/centreon-os.mdx
> +- [Broker] Fixed an issue while trying to Connect to MySQL 8.0.35.
```suggestion
- [Broker] Fixed an issue that occurred when inserting too large metrics into the database, which resulted in an error log.
- [Broker] Added support for the default connection method to MySQL 8.0.35.
```

2024-07-17 13:49 UTC, cg-tw approved these changes

2024-07-17 13:57 UTC, sfarouq-ext approved these changes

2024-07-17 14:36 UTC, merged