doc(release): Release notes for OSS 23.10
centreon/centreon-documentation pull request #3446
Opened 2024-07-18 13:10 UTC by tuntoja

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-07-18 15:32 UTC, rsadik-ext submitted a review, later dismissed

2024-07-18 16:20 UTC, cg-tw requested changes

2024-07-18 16:21 UTC, cg-tw requested changes

2024-07-18 16:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Gorgone] Fixed an issue where a host category was not present in MBI if it was applied on a host template instead of directly on the host.
```suggestion
```

2024-07-18 16:21 UTC, cg-tw requested changes

2024-07-18 16:21 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Unattended] Backported recent bug fixes on unattended (http services not restarting, it-edition-extensions installation, unattended issue on Oracle Linux distributions).
```suggestion
- [Menu] Updated the URLs of help buttons in the web interface.
- [Unattended] Backported recent bug fixes on the Unattended script (http services not restarting, it-edition-extensions installation, unattended issue on Oracle Linux distributions).
```

2024-07-19 08:20 UTC, rsadik-ext approved these changes

2024-07-19 11:36 UTC, cg-tw approved these changes

2024-07-19 11:36 UTC, merged