doc(release): release notes for collect 24.04
centreon/centreon-documentation pull request #3450
Opened 2024-07-26 14:33 UTC by tuntoja

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-07-26 14:35 UTC, sfarouq-ext approved these changes

2024-07-29 07:10 UTC, tuntoja commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +Release date: `July 27, 2024`
```suggestion
Release date: `July 29, 2024`
```

2024-07-29 07:10 UTC, tuntoja commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +Release date: `July 27, 2024`
```suggestion
Release date: `July 29, 2024`
```

2024-07-29 07:38 UTC, cg-tw requested changes

2024-07-29 07:38 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +- [Engine] fix(engine): output of external commands are sometimes truncated
```suggestion
- [Engine] The output of external commands is no longer truncated.
```

2024-07-29 07:38 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +- [Engine] fix (common): anomaly config files are open in readonly mode
```suggestion
- [Engine] Configuration files for Anomaly Detection are now opened in read-only mode.
```

2024-07-29 07:38 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +- [Engine] fix (common): all logger configs are taken into account (runtime and otl)
```suggestion
- [Engine] All log file configurations are now taken into account (including runtime and otl).
```

2024-07-29 07:38 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +- [Engine] If a service contains several times the same metric name, some of them were overwritten. Now during the parsing, a warning log explains the issue and only the first occurence of the metric
```suggestion
```

2024-07-29 07:40 UTC, cg-tw requested changes

2024-07-29 07:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
> +- [Engine] The output of external commands is no longer truncated.
```suggestion
- [Engine] The output of external commands is no longer truncated after a backslash.
```

2024-07-29 07:40 UTC, cg-tw commented on versioned_docs/version-24.04/releases/centreon-os.mdx
> +- [Engine] fix (common): all logger configs are taken into account (runtime and otl)
```suggestion
- [Engine] Configuration files for Anomaly Detection are now opened in read-only mode.
- [Engine] All log file configurations are now taken into account (including runtime and otl).
```

2024-07-29 07:41 UTC, cg-tw approved these changes

2024-07-29 12:38 UTC, merged