new(mc): added HPE Primera MC doc
centreon/centreon-documentation pull request #3457
Opened 2024-08-01 12:47 UTC by omercier

## Description

New MC

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-08-01 16:46 UTC, cg-tw requested changes

2024-08-01 16:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-hpe-primera-restapi.md
> +| HW-Storage-HPE-Primera-RESTAPI-Disk-Status-Id       | Découvre les disques physiques et supervise le statut.     |
EN dans FR pour tout le tableau

2024-08-02 07:18 UTC, omercier commented on pp/integrations/plugin-packs/procedures/hardware-storage-hpe-primera-restapi.md
> +| HW-Storage-HPE-Primera-RESTAPI-Volume-Usage-Name    | Découvre les volumes et supervise l'utilisation.           |
```suggestion
| HW-Storage-HPE-Primera-RESTAPI-Disk-Status-Id       | Discover the physical disks and monitor their state.     |
| HW-Storage-HPE-Primera-RESTAPI-Disk-Status-Position | Discover the physical disks and monitor their state.     |
| HW-Storage-HPE-Primera-RESTAPI-Disk-Usage-Id        | Discover the physical disks and monitor their usage. |
| HW-Storage-HPE-Primera-RESTAPI-Disk-Usage-Position  | Discover the physical disks and monitor their usage. |
| HW-Storage-HPE-Primera-RESTAPI-Volume-Usage-Id      | Discover the volumes and monitor their usage.           |
| HW-Storage-HPE-Primera-RESTAPI-Volume-Usage-Name    | Discover the volumes and monitor their usage.           |
```

2024-08-02 07:23 UTC, cg-tw requested changes

2024-08-02 07:23 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hpe-primera-restapi.md
> +| HW-Storage-HPE-Primera-RESTAPI-Volume-Usage-Name    | Discover the storage volumes and monitor space occupation. |
```suggestion
| HW-Storage-HPE-Primera-RESTAPI-Disk-Status-Id       | Découvre les disques physiques et en supervise le statut.     |
| HW-Storage-HPE-Primera-RESTAPI-Disk-Status-Position | Découvre les disques physiques et en supervise le statut.     |
| HW-Storage-HPE-Primera-RESTAPI-Disk-Usage-Id        | Découvre les disques physiques et en supervise l'utilisation. |
| HW-Storage-HPE-Primera-RESTAPI-Disk-Usage-Position  | Découvre les disques physiques et en supervise l'utilisation. |
| HW-Storage-HPE-Primera-RESTAPI-Volume-Usage-Id      | Découvre les volumes et en supervise l'utilisation.           |
| HW-Storage-HPE-Primera-RESTAPI-Volume-Usage-Name    | Découvre les volumes et en supervise l'utilisation.
```

2024-08-02 07:24 UTC, cg-tw approved these changes

2024-08-02 07:49 UTC, merged