doc(release): Prepare release notes for cloud 24.07
centreon/centreon-documentation pull request #3466
Opened 2024-08-06 14:59 UTC by pkippes

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [x] Cloud
- [ ] Monitoring Connectors

2024-08-07 15:38 UTC, nmagniezCentreon requested changes

2024-08-07 15:38 UTC, nmagniezCentreon commented on cloud/releases/cloud-release-notes.md
> +
## August xx, 2024

### Open Access to Centreon APIs

It is now possible to interact with Centreon through APIs and therefore integrate Centreon with any monitoring or data processing tool you may use, automatize monitoring configuration updates and any other use case you may have in mind. Access to APIs is granted thanks to tokens linked to contacts for access right management, but completely independent in terms of lifecycle.
API documentation is available here (link)

### Centreon Dashboards

It is now possible to declare dashboards playlists as public. An URL is genrated and give access to the dashboard playlist without authentication. This feature is ideal to display dahboards on big screens.
Note that this feature was implemented in a completely secured way. No confidential information is carried by the URL, nor it is possible to have access to any other information or data than the one displayed.
Note: MAP widget is not supported yet on public playlists.

This version of Centreon Dashboards comes with many other improvements. 
Graph widget allows much more configuration (automatic curves color adjustement for metric of same kind, bar chart and stacked bar chart presentation, 3 different curves design, and many others).
Widgets are also now more compact, allowing to display more of them on a single display.
And finally, freshness of data is now exposed and user can reload data at the widget level.

2024-08-19 09:01 UTC, cg-tw commented on cloud/releases/cloud-release-notes.md
> +In standard maps, it is now possible to hide container labels and to display status as background color for resources in weather style.
```suggestion
In standard maps, it is now possible to hide container labels and to use the status as background color for resources in weather style.
```

2024-08-19 09:03 UTC, cg-tw commented on cloud/releases/cloud-release-notes.md
> +  Resource Access Management allows administrators to assign specific access permissions to each user or user group. This enables control over which users can access particular monitored resources. A
```suggestion
Resource Access Management allows administrators to assign specific access permissions to each user or user group. This enables control over which users can access particular monitored resources. An intuitive interface helps manage these permissions, while audit logs provide a record of access activities. This feature supports organizations in maintaining security and efficiency by allowing tailored access control.
```

2024-08-22 08:44 UTC, cg-tw commented on cloud/releases/cloud-release-notes.md
> +## August xx, 2024
```suggestion
## August 22, 2024
```

2024-08-22 08:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
> +## August xx, 2024
```suggestion
## August 22, 2024
```

2024-08-22 08:57 UTC, merged