CTOR-732 : Refresh infrastructure-active-directory-nsclient-05-restapi
centreon/centreon-documentation pull request #3484
Opened 2024-08-21 14:50 UTC by lucie-dubrunfaut

## Description

Refresh infrastructure-active-directory-nsclient-05-restapi

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-08-21 15:31 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +Coming soon
Le code du mode est pas vraiment clair sur ce sujet... j'ai l'impression que ce sont des status mais il n'y a pas de counter à proprement parlé. Et quand je le lance en local sur mon ordi ça fonctionne pas sans la lib win32

2024-08-23 13:40 UTC, cg-tw requested changes

2024-08-23 13:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +Pour surveiller une ressource via NSClient++ API, installez la version Centreon de l'agent NSClient++.
```suggestion
Pour superviser une ressource via NSClient++ API, installez la version Centreon de l'agent NSClient++.
```

2024-08-23 13:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| NSCPRESTAPIPORT           | Port use by the REST API NSClient++                                                                                                       | 8443              |
```suggestion
| NSCPRESTAPIPORT           | Port used by the REST API NSClient++                                                                                                       | 8443              |             |
```

2024-08-23 13:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| REPLICATEDFOLDER | Name name for the replicated folder.                                                                                                             |                   | X
```suggestion
| REPLICATEDFOLDER | Name for the replicated folder.                                                                                                             |                   | X           |
```

2024-08-23 13:40 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| Dfsr-Backlog | Infra-ActiveDirectory-Dfsr-Backlog-NSClient05-Restapi-custom | Contrôle permettant le backlog dfsr |
```suggestion
| Dfsr-Backlog | Infra-ActiveDirectory-Dfsr-Backlog-NSClient05-Restapi-custom | Contrôle le backlog dfsr |
```

2024-08-23 13:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| Ad-Domain-Controller | Infra-ActiveDirectory-Domain-Controller-NSClient05-Restapi-custom | This check makes to diagnose the domain controller. It executes the command "dcdiag"  |
```suggestion
| Ad-Domain-Controller | Infra-ActiveDirectory-Domain-Controller-NSClient05-Restapi-custom | This check runs diagnostics on the domain controller. It executes the "dcdiag" command  |
```

2024-08-23 13:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| Dfsr-Backlog  | Infra-ActiveDirectory-Dfsr-Backlog-NSClient05-Restapi-custom | Check dfsr backlog  |
```suggestion
| Dfsr-Backlog  | Infra-ActiveDirectory-Dfsr-Backlog-NSClient05-Restapi-custom | Checks the dfsr backlog  |
```

2024-08-23 13:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| NSCPRESTAPIPORT           | Port use by the REST API NSClient++                                                                                                       | 8443              |
```suggestion
| NSCPRESTAPIPORT           | Port used by the REST API NSClient++                                                                                                       | 8443              |             |
```

2024-08-23 13:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| REPLICATEDFOLDER | Name name for the replicated folder.                                                                                                   |                   | X           |
```suggestion
| REPLICATEDFOLDER | Name for the replicated folder.                                                                                                   |                   | X           |
```

2024-09-06 07:32 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| Dfsr-Backlog  | Infra-ActiveDirectory-Dfsr-Backlog-NSClient05-Restapi-custom | Checks the dfsr backlog  |
```suggestion
| Dfsr-Backlog  | Infra-ActiveDirectory-Dfsr-Backlog-NSClient05-Restapi-custom | Check the Distributed File Systems Replication backlog  |
```

2024-09-06 07:33 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +Coming soon
```suggestion
| Metric name        | Unit  |
|:-------------------|:------|
| domain controller status | N/A |
```

2024-09-06 07:34 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +Coming soon
```suggestion
| Métrique           | Unité |
|:-------------------|:------|
| domain controller status | N/A |
```

2024-09-06 07:34 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md
> +| Dfsr-Backlog | Infra-ActiveDirectory-Dfsr-Backlog-NSClient05-Restapi-custom | Contrôle le backlog dfsr |
```suggestion
| Dfsr-Backlog | Infra-ActiveDirectory-Dfsr-Backlog-NSClient05-Restapi-custom | Contrôle du backlog de réplication des Distributed File Systems |
```

2024-09-06 08:45 UTC, cg-tw approved these changes

2024-09-09 07:03 UTC, merged