CTOR-823 : Refresh hardware-storage-bdt-multistak-snmp
centreon/centreon-documentation pull request #3488
Opened 2024-08-23 08:18 UTC by lucie-dubrunfaut

## Description

Refresh hardware-storage-bdt-multistak-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-08-23 09:52 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md
> +| status                | Components global status  |       |
```suggestion
| Metric name   | Unit |
|:--------------|:-----|
| module.status | N/A  |
| device.status | N/A  |
```

2024-08-23 09:52 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md
> +| status                | Components global status  |       |
```suggestion
| Métrique      | Unité |
|:--------------|:------|
| module.status | N/A   |
| device.status | N/A   |
```

2024-08-23 14:04 UTC, cg-tw requested changes

2024-08-23 14:04 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md
>  </Tabs>
same as FR

2024-08-27 15:29 UTC, cg-tw approved these changes

2024-08-27 15:29 UTC, merged