CTOR-824 : Refresh hardware-storage-dell-compellent-snmp
centreon/centreon-documentation pull request #3489
Opened 2024-08-23 09:22 UTC by lucie-dubrunfaut

## Description

Refresh hardware-storage-dell-compellent-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-08-23 11:40 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-snmp.md
> +
```suggestion
```

2024-08-23 14:12 UTC, cg-tw requested changes

2024-08-23 14:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-snmp.md
> +| Traffic-Generic-Id   | HW-Storage-Dell-Compellent-Traffic-Generic-Id-SNMP-custom   | Contrôle le traffic réseau d'une interface réseau         |            |
```suggestion
| Traffic-Generic-Id   | HW-Storage-Dell-Compellent-Traffic-Generic-Id-SNMP-custom   | Contrôle le trafic réseau d'une interface réseau         |            |
```

2024-08-23 14:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-snmp.md
> +| Traffic-Generic-Name | HW-Storage-Dell-Compellent-Traffic-Generic-Name-SNMP-custom | Contrôle le traffic réseau d'une interface réseau         |            |
```suggestion
| Traffic-Generic-Name | HW-Storage-Dell-Compellent-Traffic-Generic-Name-SNMP-custom | Contrôle le trafic réseau d'une interface réseau         |            |
```

2024-08-23 14:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-snmp.md
> +| Traffic-Global       | HW-Storage-Dell-Compellent-Traffic-Global-SNMP-custom       | Contrôle le traffic réseau de plusieurs interfaces réseau |     X      |
```suggestion
| Traffic-Global       | HW-Storage-Dell-Compellent-Traffic-Global-SNMP-custom       | Contrôle le trafic réseau de plusieurs interfaces réseau |     X      |
```

2024-08-23 14:12 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-snmp.md
> +| Traffic-Generic-Id   | HW-Storage-Dell-Compellent-Traffic-Generic-Id-SNMP-custom   | Check traffic of an network interface        |            |
```suggestion
| Traffic-Generic-Id   | HW-Storage-Dell-Compellent-Traffic-Generic-Id-SNMP-custom   | Check traffic of a network interface        |            |
```

2024-08-23 14:12 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-snmp.md
> +| Traffic-Generic-Name | HW-Storage-Dell-Compellent-Traffic-Generic-Name-SNMP-custom | Check traffic of an network interface        |            |
```suggestion
| Traffic-Generic-Name | HW-Storage-Dell-Compellent-Traffic-Generic-Name-SNMP-custom | Check traffic of a network interface        |            |
```

2024-08-27 15:31 UTC, cg-tw approved these changes

2024-08-27 15:31 UTC, merged