CTOR-825 : Refresh hardware-storage-emc-clariion-navisphere
centreon/centreon-documentation pull request #3490
Opened 2024-08-23 11:48 UTC by lucie-dubrunfaut

## Description

Refresh hardware-storage-emc-clariion-navisphere

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-08-23 13:27 UTC, lucie-dubrunfaut commented
Attention pour les tableaux de métriques : 
- Faults
- Hardware Global
- HBA state
- Port state

J'ai extrapolé manuellement les métriques d'après ce que je voyais dans le code...

2024-08-23 14:24 UTC, cg-tw requested changes

2024-08-23 14:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-emc-clariion-navisphere.md
> +| Disks           | HW-Storage-EMC-Clariion-Disks-Navisphere-custom           | Check disks status and performances | X          |
```suggestion
| Disks           | HW-Storage-EMC-Clariion-Disks-Navisphere-custom           | Check disk status and performance | X          |
```

2024-08-23 14:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-emc-clariion-navisphere.md
> +| Controller      | HW-Storage-EMC-Clariion-Controller-Navisphere-custom      | Contrôle le contrôleur                          |            |
```suggestion
| Controller      | HW-Storage-EMC-Clariion-Controller-Navisphere-custom      | Contrôle le contrôleur Navisphere                          |            |
```

2024-08-23 14:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-emc-clariion-navisphere.md
> +| Controller      | HW-Storage-EMC-Clariion-Controller-Navisphere-custom      | Check global controller             |            |
```suggestion
| Controller      | HW-Storage-EMC-Clariion-Controller-Navisphere-custom      | Check the global Navisphere controller             |            |
```

2024-08-23 14:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-emc-clariion-navisphere.md
> +The plugin need the installation of Navisphere client (ask to your EMC Support).
```suggestion
The plugin needs the Navisphere client to be installed (ask your EMC Support).
```

2024-08-23 14:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-emc-clariion-navisphere.md
> +The plugin uses by default the path `/opt/Navisphere/bin`.
```suggestion
 By default , the plugin uses the following path: `/opt/Navisphere/bin`.
```

2024-08-27 15:33 UTC, cg-tw approved these changes

2024-08-27 15:34 UTC, merged