CTOR-836 : Refresh hardware-storage-hp-3par-ssh
centreon/centreon-documentation pull request #3501
Opened 2024-08-27 11:13 UTC by lucie-dubrunfaut

## Description

Refresh hardware-storage-hp-3par-ssh

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-08-27 12:38 UTC, cg-tw requested changes

2024-08-27 12:38 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
> +exchanging the SSH key from **centreon-engine** user to the target resource, or by
```suggestion
exchanging the SSH key of the **centreon-engine** user to the target resource, or by
```

2024-08-27 12:40 UTC, cg-tw requested changes

2024-08-27 12:40 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
> +exchanging the SSH key from **centreon-engine** user to the target resource, or by
ça ne dit pas exactement la même chose entre EN et FR

2024-09-17 12:27 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
> +setting your unique user and password directly in the host macros.
```suggestion
Using this connector requires a user to be created on the monitored resource, which will be used by the Centreon poller to authenticate and execute the SSH requests. There is no need for root or sudo
privileges. There are two possible ways to log in through SSH, either by
exchanging the SSH key of the **centreon-engine** user to the target resource, or by
setting your unique user and password directly in the host macros.
```

2024-09-26 13:48 UTC, cg-tw approved these changes

2024-09-26 13:48 UTC, merged