CTOR-445 : Document InfluxDB SC in official documentation
centreon/centreon-documentation pull request #3504
Opened 2024-08-27 14:57 UTC by lucie-dubrunfaut

## Description

Document InfluxDB SC in official documentation

## Target version (i.e. version that this PR changes)

- [x] 22.10.x
- [x] 23.04.x
- [x] 23.10.x
- [x] 24.04.x
- [x] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-08-28 07:43 UTC, lucie-dubrunfaut commented
Je m'occuperais de dupliquer les docs sur les différentes versions Centreon quand la version EN et FR seront validées.

2024-08-28 09:54 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +title: Influxdb 2 Metrics
```suggestion
title: - InfluxdDB 2 Metrics
```

2024-08-28 09:55 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +| Name            | Influxdb2 metrics                                          |
```suggestion
| Name            | InfluxdDB 2 metrics                                          |
```

2024-08-28 09:55 UTC, lucie-dubrunfaut commented on versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +title: Influxdb 2 Metrics
```suggestion
title: InfluxdDB 2 Metrics
```

2024-08-28 09:58 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +Le stream connector Influxdb 2 Metrics vous permet d'envoyer des données depuis Centreon vers des instances Influxdb 2.
```suggestion
Le stream connector InfluxdDB 2 Metrics vous permet d'envoyer des données depuis Centreon vers des instances InfluxdDB 2.
```

2024-08-28 09:58 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +- Par défaut, le stream connector Influxdb 2 Metrics envoie des métriques des évènements Broker [**host_status**](../../developer/developer-broker-mapping.md#host-status)
```suggestion
- Par défaut, le stream connector InfluxdDB 2 Metrics envoie des métriques des évènements Broker [**host_status**](../../developer/developer-broker-mapping.md#host-status) 
```

2024-08-28 09:58 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +Faites l'installation sur le serveur qui enverra les données à Influxdb 2 (serveur central, serveur distant, collecteur).
```suggestion
Faites l'installation sur le serveur qui enverra les données à InfluxdDB 2 (serveur central, serveur distant, collecteur).
```

2024-08-28 09:58 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +## Configurer votre équipement Influxdb 2
```suggestion
## Configurer votre équipement InfluxdDB 2
```

2024-08-28 09:59 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +Assurez-vous que Influxdb 2 puisse recevoir les données envoyées par Centreon : les flux ne doivent pas être bloqués par la configuration de Influxdb 2 ou par un équipement de sécurité.
```suggestion
Vous devrez paramétrer votre équipement InfluxdDB 2 pour qu'il puisse recevoir des données de la part de Centreon. Reportez-vous à la documentation InfluxdDB 2.
Assurez-vous que InfluxdDB 2 puisse recevoir les données envoyées par Centreon : les flux ne doivent pas être bloqués par la configuration de InfluxdDB 2 ou par un équipement de sécurité.
```

2024-08-28 09:59 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +5. Pour permettre à Centreon de se connecter à votre équipement Influxdb 2, remplissez les paramètres obligatoires suivants. La première entrée existe déjà. Cliquez sur le lien **+Add a new entry** e
```suggestion
5. Pour permettre à Centreon de se connecter à votre équipement InfluxdDB 2, remplissez les paramètres obligatoires suivants. La première entrée existe déjà. Cliquez sur le lien **+Add a new entry** en-dessous du tableau **Filter category** pour en ajouter un autre.
```

2024-08-28 09:59 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +| string | org_name        | The name of the influxdb organization         | `centreon`                                                                              |
```suggestion
| string | org_name        | The name of the InfluxdDB organization         | `centreon`                                                                              |
```

2024-08-28 10:00 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +7. Utilisez les paramètres optionnels du stream connector pour [filtrer ou adapter les données que vous voulez que Centreon envoie à Influxdb 2](#filtrer-ou-adapter-les-données-que-vous-voulez-envoye
```suggestion
7. Utilisez les paramètres optionnels du stream connector pour [filtrer ou adapter les données que vous voulez que Centreon envoie à InfluxdDB 2](#filtrer-ou-adapter-les-données-que-vous-voulez-envoyer-à-influxdb2).
```

2024-08-28 10:00 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +   Influxdb 2 reçoit maintenant des données de Centreon. Pour tester le bon fonctionnement de l'intégration, voir [Commandes curl : tester le stream connector](#commandes-curl--tester-le-stream-conne
```suggestion
   InfluxdDB 2 reçoit maintenant des données de Centreon. Pour tester le bon fonctionnement de l'intégration, voir [Commandes curl : tester le stream connector](#commandes-curl--tester-le-stream-connector).
```

2024-08-28 10:00 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +### Filtrer ou adapter les données que vous voulez envoyer à Influxdb 2
```suggestion
### Filtrer ou adapter les données que vous voulez envoyer à InfluxdDB 2
```

2024-08-28 10:00 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +Tous les stream connectors ont un jeu de [paramètres optionnels](https://github.com/centreon/centreon-stream-connector-scripts/blob/master/modules/docs/sc_param.md#default-parameters) qui vous permet
```suggestion
Tous les stream connectors ont un jeu de [paramètres optionnels](https://github.com/centreon/centreon-stream-connector-scripts/blob/master/modules/docs/sc_param.md#default-parameters) qui vous permettent de filtrer les données que vous enverrez à votre équipement InfluxdDB 2, de reformater les données, de définir un proxy...
```

2024-08-28 10:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +* Pour le stream connector Influxdb 2 Metrics, les données suivantes surchargent toujours les valeurs par défaut (il n'est pas nécessaire de les redéfinir dans l'interface).
```suggestion
* Pour le stream connector InfluxdDB 2 Metrics, les données suivantes surchargent toujours les valeurs par défaut (il n'est pas nécessaire de les redéfinir dans l'interface).
```

2024-08-28 10:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +Si vous voulez tester que les évènements sont envoyés correctement à Influxdb 2 :
```suggestion
Si vous voulez tester que les évènements sont envoyés correctement à InfluxdDB 2 :
```

2024-08-28 10:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +1. Connectez-vous au serveur que vous avez configuré pour envoyer les évènements à Influxdb 2 (le serveur central, un serveur distant ou un collecteur)
```suggestion
1. Connectez-vous au serveur que vous avez configuré pour envoyer les évènements à InfluxdDB 2 (le serveur central, un serveur distant ou un collecteur)
```

2024-08-28 10:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +3. Vérifiez que l'évènement a bien été reçu par Influxdb 2.
```suggestion
3. Vérifiez que l'évènement a bien été reçu par InfluxdDB 2.
```

2024-08-28 10:03 UTC, cg-tw requested changes

2024-08-28 10:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +Ce stream connector n'est pas compatible avec le formatage d'événements personnalisés.
```suggestion
Ce stream connector n'est pas compatible avec le format d'événements personnalisé.
```

2024-08-28 10:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +Si vous voulez tester que les évènements sont envoyés correctement à Influxdb 2 :
```suggestion
Si vous voulez tester que les évènements sont envoyés correctement à InfluxDB 2 :
```

2024-08-28 10:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +1. Connectez-vous au serveur que vous avez configuré pour envoyer les évènements à Influxdb 2 (le serveur central, un serveur distant ou un collecteur)
```suggestion
1. Connectez-vous au serveur que vous avez configuré pour envoyer les évènements à InfluxDB 2 (le serveur central, un serveur distant ou un collecteur)
```

2024-08-28 10:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +3. Vérifiez que l'évènement a bien été reçu par Influxdb 2.
```suggestion
3. Vérifiez que l'évènement a bien été reçu par InfluxDB 2.
```

2024-08-28 10:13 UTC, cg-tw requested changes

2024-08-28 10:13 UTC, cg-tw commented on versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +| string | bucket_id       | The bucket id where metrics will be sent      | `65f5f748e28c92f0`                                                                      |
```suggestion
| string | bucket_id       | The ID of the bucket where metrics will be sent      | `65f5f748e28c92f0`                                                                      |
```

2024-08-28 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +| string | bucket_id       | The bucket ID where metrics will be sent      | `65f5f748e28c92f0`                                                                      |
```suggestion
| string | bucket_id       | The ID of the bucket where metrics will be sent      | `65f5f748e28c92f0`                                                                      |
```

2024-08-28 10:13 UTC, cg-tw commented on versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +   InfluxdDB 2 should now receive data from Centreon. To test if it is working, see [Curl commands: testing the stream connector](#curl-commands-testing-the-stream-connector).
```suggestion
   InfluxDB 2 should now receive data from Centreon. To test if it is working, see [Curl commands: testing the stream connector](#curl-commands-testing-the-stream-connector).
```

2024-08-28 10:13 UTC, cg-tw commented on versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +| string | http_server_url | The InfluxdDB address with the port at the end | `https://myinfluxdb2.local:8086`                                                        |
```suggestion
| string | http_server_url | The InfluxDB address with the port at the end | `https://myinfluxdb2.local:8086`                                                        |
```

2024-08-28 10:13 UTC, cg-tw commented on versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +| string | org_name        | The name of the InfluxdDB organization         | `centreon`                                                                              |
```suggestion
| string | org_name        | The name of the InfluxDB organization         | `centreon`                                                                              |
```

2024-08-28 10:13 UTC, cg-tw commented on versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +All stream connectors have a set of [optional parameters](https://github.com/centreon/centreon-stream-connector-scripts/blob/master/modules/docs/sc_param.md#default-parameters), that allow you to fil
```suggestion
All stream connectors have a set of [optional parameters](https://github.com/centreon/centreon-stream-connector-scripts/blob/master/modules/docs/sc_param.md#default-parameters), that allow you to filter the data you will send to your InfluxdDB 2 device, to reformat the data, to define a proxy...
```

2024-08-28 10:13 UTC, cg-tw commented on versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +> According to [best practice](https://docs.influxdata.com/influxdb/cloud/write-data/best-practices/optimize-writes/#batch-writes) `max_buffer_size` is set at 5000 lines by default. But you should lo
```suggestion
> According to [best practice](https://docs.influxdata.com/influxdb/cloud/write-data/best-practices/optimize-writes/#batch-writes), `max_buffer_size` is set at 5000 lines by default. But you should lower this value to a few hundred if you have less than 10 000 services.
```

2024-08-28 10:18 UTC, cg-tw requested changes

2024-08-28 10:18 UTC, cg-tw commented on versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +All stream connectors have a set of [optional parameters](https://github.com/centreon/centreon-stream-connector-scripts/blob/master/modules/docs/sc_param.md#default-parameters), that allow you to fil
```suggestion
All stream connectors have a set of [optional parameters](https://github.com/centreon/centreon-stream-connector-scripts/blob/master/modules/docs/sc_param.md#default-parameters), that allow you to filter the data you will send to your InfluxDB 2 device, to reformat the data, to define a proxy...
```

2024-08-28 11:12 UTC, cg-tw requested changes

2024-08-28 11:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
> +title: - InfluxDB 2 Metrics
```suggestion
title: InfluxDB 2 Metrics
```

2024-08-29 08:08 UTC, cg-tw approved these changes

2024-09-16 13:44 UTC, tanguyvda approved these changes

2024-09-16 14:32 UTC, merged