CTOR-736 : Refresh hardware-servers-hp-snmp
centreon/centreon-documentation pull request #3528
Opened 2024-09-04 13:18 UTC by lucie-dubrunfaut

## Description

Refresh hardware-servers-hp-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-09-04 13:42 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificate
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **HW-Server-Hp-Server-SNMP-custom** |
```

2024-09-24 16:03 UTC, cg-tw requested changes

2024-09-24 16:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
> +| Hardware-Cpu         | HW-Hp-Server-Hardware-Cpu-SNMP-custom         | Check cpu hardware             |
```suggestion
| Hardware-Cpu         | HW-Hp-Server-Hardware-Cpu-SNMP-custom         | Check CPU hardware             |
```

2024-09-24 16:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
> +| Hardware-Temperature | HW-Hp-Server-Hardware-Temperature-SNMP-custom | Check hardware temperatures    |
```suggestion
| Hardware-Temperature | HW-Hp-Server-Hardware-Temperature-SNMP-custom | Check hardware temperature    |
```

2024-09-26 13:42 UTC, cg-tw approved these changes

2024-09-26 16:04 UTC, merged