CTOR-832 : Refresh hardware-storage-nimble-snmp
centreon/centreon-documentation pull request #3529
Opened 2024-09-04 13:39 UTC by lucie-dubrunfaut

## Description

Refresh hardware-storage-nimble-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-09-24 16:17 UTC, cg-tw requested changes

2024-09-24 16:17 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
>  Il est nécessaire de se référer à la documentation officielle du constructeur pour activer le SNMP:
prérequis

2024-09-24 16:17 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +| SNMPEXTRAOPTIONS | Any extra option you may want to add to every command (a --verbose flag for example). Toutes les options sont listées [ici](#options-disponibles). |                   |
FR?

2024-09-24 16:17 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +```bash
est-ce cohérent avec la commande?

2024-09-24 16:17 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +| Volume-Usage-Global | HW-Storage-Nimble-Volume-Usage-Global-SNMP-custom | Check volume usages              |
```suggestion
| Volume-Usage-Global | HW-Storage-Nimble-Volume-Usage-Global-SNMP-custom | Check volume usage              |
```

2024-09-24 16:17 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
>  Enable SNMP on the Nimble device following the official HPE documentation:
prerequisites?

2024-09-24 16:17 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +OK: Volume 'Volume-A' Total: 40960.00 TB Used: 20480.00 TB (50.00%) Free: 20480.00 TB (50.00%) | 'used'=22517998138949632B;0:36028797019802832;0:40532396647278184;0;45035996274753536
est-ce cohérent avec la commande?

2024-10-01 13:53 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +```bash
Ok en fait les valeurs sont WTf car :

```
my $mapping = {
    volName         => { oid => '.1.3.6.1.4.1.37447.1.2.1.3' },
    volSizeLow      => { oid => '.1.3.6.1.4.1.37447.1.2.1.4' }, # seems in MB
    volSizeHigh     => { oid => '.1.3.6.1.4.1.37447.1.2.1.5' }, # seems in MB
    volUsageLow     => { oid => '.1.3.6.1.4.1.37447.1.2.1.6' }, # seems in MB
    volUsageHigh    => { oid => '.1.3.6.1.4.1.37447.1.2.1.7' }, # seems in MB
};
```

Alors que côté MIB je vois : 
```
1.3.6.1.4.1.37447.1.2.1.4 => Maximum defined size of a volume in bytes - low order bytes.
1.3.6.1.4.1.37447.1.2.1.5 => Maximum defined size of a volume in bytes - high order bytes
1.3.6.1.4.1.37447.1.2.1.6 => Current number of bytes a volume is using - low order bytes.
1.3.6.1.4.1.37447.1.2.1.7 => Current number of bytes a volume is using - high order bytes.
```

Donc je me demande si le plugin a pas un problème de conversion

2024-10-18 12:54 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +```bash
https://centreon.atlassian.net/browse/CTOR-949

2025-10-07 09:49 UTC, lucie-tirand commented on pp/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +OK: Volume 'Volume-A' Total: 40960.00 TB Used: 20480.00 TB (50.00%) Free: 20480.00 TB (50.00%) | 'used'=22517998138949632B;0:36028797019802832;0:40532396647278184;0;45035996274753536
Fixed

2025-10-07 09:49 UTC, lucie-tirand commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +```bash
Fixed

2025-10-07 09:51 UTC, lucie-tirand commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +Volume 'Volume-A' Total: 4.35 GB Used: 1.95 GB (44.89%) Free: 2.40 GB (55.11%)
```suggestion
OK: Volume 'Volume-A' Total: 4.35 GB Used: 1.95 GB (44.89%) Free: 2.40 GB (55.11%) | 'used'=2097152000B;0:3737124864;0:4204265472;0;4671406080
Volume 'Volume-A' Total: 4.35 GB Used: 1.95 GB (44.89%) Free: 2.40 GB (55.11%)
```

2025-10-07 09:51 UTC, lucie-tirand commented on pp/integrations/plugin-packs/procedures/hardware-storage-nimble-snmp.md
> +Volume 'Volume-A' Total: 4.35 GB Used: 1.95 GB (44.89%) Free: 2.40 GB (55.11%)
```suggestion
OK: Volume 'Volume-A' Total: 4.35 GB Used: 1.95 GB (44.89%) Free: 2.40 GB (55.11%) | 'used'=2097152000B;0:3737124864;0:4204265472;0;4671406080
Volume 'Volume-A' Total: 4.35 GB Used: 1.95 GB (44.89%) Free: 2.40 GB (55.11%)
```

2025-10-07 12:34 UTC, closed without merging