CTOR-833 : Refresh hardware-storage-purestorage-snmp
centreon/centreon-documentation pull request #3530
Opened 2024-09-04 14:16 UTC by lucie-dubrunfaut

## Description

Refresh hardware-storage-purestorage-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-01 15:00 UTC, cg-tw requested changes

2024-10-16 15:27 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-snmp.md
>  </Tabs>
Je te laisse regarder en dessous et resolve

2024-10-22 12:11 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-snmp.md
> +Afin de superviser votre **Pure Storage** en SNMP, il est nécessaire de configurer l'agent sur l'équipement.
```suggestion
Afin de superviser votre **Pure Storage** en SNMP, il est nécessaire de configurer l'agent sur l'équipement. Veuillez vous référer à la documentation officielle du constructeur/éditeur.
```

2024-10-22 12:12 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-snmp.md
> +To use this pack, the SNMP service must be properly configured on your **Pure Storage** equipment.
```suggestion
To use this pack, the SNMP service must be properly configured on your **Pure Storage** equipment. Please refer to the official documentation from the manufacturer/publisher.
```

2024-10-22 12:38 UTC, cg-tw approved these changes

2024-10-22 12:38 UTC, merged