CTOR 775: Fix apps::backup::rubrik::restapi::mode::jobs long output when a job is not detected
centreon/centreon-documentation pull request #3539
Opened 2024-09-06 13:59 UTC by itoussies

## Description

Refresh Rubrik Rest API following the plugins changes.

Needs https://github.com/centreon/centreon-plugins/pull/5171 to be merged before merging this one.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [X] Monitoring Connectors

2024-09-09 12:44 UTC, cg-tw requested changes

2024-09-09 12:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +depuis l'interface web et le menu **Configuration > Gestionnaire de connecteurs de supervision** :
```suggestion
depuis la page **Configuration > Gestionnaire de connecteurs de supervision** :
```

2024-09-09 12:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +	--api-username='' \
mandatory?

2024-09-09 12:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +## Connector Dependencies
```suggestion
## Connector dependencies
```

2024-09-09 12:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +	--api-username='' \
mandatory?

2024-10-01 12:45 UTC, cg-tw requested changes

2024-10-01 12:45 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +Voici le tableau des services pour ce connecteur, détaillant les métriques et statuts rattachées à chaque service.
```suggestion
Voici le tableau des services pour ce connecteur, détaillant les métriques et statuts rattachés à chaque service.
```

2024-10-01 15:04 UTC, cg-tw approved these changes, later dismissed

2024-10-08 07:29 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
> +| RUBRIKAPIEXTRAOPTIONS   | Any extra option you may want to add to every command (a --verbose flag for example). Toutes les options sont listées [ici](#options-disponibles). |                   |
```suggestion
| Macro                   | Description                                                                                                                                        | Valeur par défaut | Obligatoire |
|:------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------|:------------------|:-----------:|
| RUBRIKAPIUSERNAME       | API username (Mandatory with API password for the first authentication way)                                                                        |                   | X           |
| RUBRIKAPIPASSWORD       | API password (Mandatory with API username for the first authentication way)                                                                        |                   | X           |
| RUBRIKAPISERVICEACCOUNT | Service account ID (Mandatory with API service account secret for the second authentication way)                                                   |                   | X           |
| RUBRIKAPISECRET         | Service account secret (Mandatory with API service account ID for the second authentication way)                                                   |                   | X           |
| RUBRIKAPITOKEN          | Use token authentication (the third way to authenticate). If option is empty, token is created.                                                    |                   | X           |
| RUBRIKAPIPROTO          | Specify https if needed                                                                                                         | https             |             |
| RUBRIKAPIPORT           | Port used                                                                                                                            | 443               |             |
| RUBRIKAPIEXTRAOPTIONS   | Any extra option you may want to add to every command (a --verbose flag for example). Toutes les options sont listées [ici](#options-disponibles). |                   |             |
```

2024-10-08 09:37 UTC, lucie-dubrunfaut commented
Rebase here https://github.com/centreon/centreon-documentation/pull/3637

2024-10-08 09:37 UTC, closed without merging