enh(registrer): Add registration of servers
centreon/centreon-documentation pull request #354
Opened 2020-09-28 13:23 UTC by lpinsivy

2020-09-29 14:58 UTC, loiclau commented on en/reporting/installation.md
> +-t Poller -h <IP_CENTREON_CENTRAL> -n <REMOTE_SERVER_NAME>
-t mbi

2020-09-29 15:00 UTC, lpinsivy commented on en/reporting/installation.md
> +-t Poller -h <IP_CENTREON_CENTRAL> -n <REMOTE_SERVER_NAME>
GG, I made the same for map...

2020-10-02 07:40 UTC, sc979 commented on en/installation/installation-of-a-poller/using-centreon-iso.md
> +> You credetials are incorrect for the **<API_ACCOUNT>**.
```suggestion
> Your credentials are incorrect for the **<API_ACCOUNT>**.
```

2020-10-02 08:35 UTC, sc979 commented on en/installation/installation-of-a-poller/using-packages.md
> +> You credetials are incorrect for the **<API_ACCOUNT>**.
```suggestion
> Your credentials are incorrect for the **<API_ACCOUNT>**.
```

2020-10-02 08:37 UTC, sc979 commented on en/installation/installation-of-a-remote-server/using-centreon-iso.md
> +> You credetials are incorrect for the **<API_ACCOUNT>**.
```suggestion
> Your credentials are incorrect for the **<API_ACCOUNT>**.
```

2020-10-02 08:38 UTC, sc979 commented on en/installation/installation-of-a-remote-server/using-packages.md
> +> You credetials are incorrect for the **<API_ACCOUNT>**.
```suggestion
> Your credentials are incorrect for the **<API_ACCOUNT>**.
```

2020-10-13 07:13 UTC, sc979 requested changes
MBI registering is not achieved

2020-10-13 07:13 UTC, sc979 commented on en/reporting/installation.md
> +```
```suggestion
```

2020-10-14 14:22 UTC, quanghungb commented on en/installation/installation-of-a-poller/using-packages.md
> +-t Poller -h <IP_CENTREON_CENTRAL> -n <REMOTE_SERVER_NAME>
-n <REMOTE_SERVER_NAME>

here we are registering a Poller, so this is a Poller name ?

2020-10-15 13:48 UTC, sc979 commented on en/installation/installation-of-a-poller/using-centreon-iso.md
> +> want to link your server to it..
I can't find where the software collection repository installation is explained for a poller
As php-cli-72 is required

2020-10-19 08:45 UTC, jeremyjaouen requested changes

2020-10-19 08:45 UTC, jeremyjaouen commented on en/graph-views/install.md
> +-t map -h <IP_CENTREON_CENTRAL> -n <SERVER_NAME>
```suggestion
-t map -h <IP_TARGET_NODE> -n <SERVER_NAME>
```
The IP could be a Central or Remote

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-poller/using-centreon-iso.md
> +-t Poller -h <IP_CENTREON_CENTRAL> -n <POLLER_NAME>
```suggestion
-t Poller -h <IP_TARGET_NODE> -n <POLLER_NAME>
```

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-poller/using-centreon-iso.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-poller/using-centreon-iso.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-poller/using-centreon-iso.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-poller/using-packages.md
> +-t Poller -h <IP_CENTREON_CENTRAL> -n <POLLER_NAME>
```suggestion
-t Poller -h <IP_TARGET_NODE> -n <POLLER_NAME>
```

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-poller/using-packages.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-poller/using-packages.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-poller/using-packages.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-remote-server/using-centreon-iso.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-remote-server/using-centreon-iso.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-remote-server/using-centreon-iso.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-remote-server/using-packages.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-remote-server/using-packages.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on en/installation/installation-of-a-remote-server/using-packages.md
> +```
This section isn't up to date

2020-10-19 08:45 UTC, jeremyjaouen commented on fr/graph-views/install.md
> +-t map -h <IP_CENTREON_CENTRAL> -n <SERVER_NAME>
```suggestion
-t map -h <IP_TARGET_NODE> -n <SERVER_NAME>
```

2020-10-19 08:45 UTC, jeremyjaouen commented on fr/graph-views/install.md
> +Install the Software Collections repository using this command:
All this doc shouldn't be in french ?

2020-10-19 08:45 UTC, jeremyjaouen commented on fr/installation/installation-of-a-poller/using-centreon-iso.md
> +-t Poller -h <IP_CENTREON_CENTRAL> -n <POLLER_NAME>
```suggestion
-t Poller -h <IP_TARGET_NODE> -n <POLLER_NAME>
```

2020-10-19 08:45 UTC, jeremyjaouen commented on fr/installation/installation-of-a-poller/using-packages.md
> +-t Poller -h <IP_CENTREON_CENTRAL> -n <POLLER_NAME>
```suggestion
-t Poller -h <IP_TARGET_NODE> -n <POLLER_NAME>
```

2020-10-20 08:04 UTC, lpinsivy commented on fr/graph-views/install.md
> +Install the Software Collections repository using this command:
Yes but we need time to translate ;)

2020-10-20 09:30 UTC, Fxdpt approved these changes

2020-10-20 09:48 UTC, sc979 approved these changes

2020-10-20 10:08 UTC, jeremyjaouen approved these changes

2020-10-21 08:03 UTC, merged

2020-10-21 08:03 UTC, Thebarda approved these changes