Ctor 398 backbox
centreon/centreon-documentation pull request #3541
Opened 2024-09-09 11:01 UTC by sdepassio

## Description

New monitoring connector Backbox

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-09-09 12:17 UTC, cg-tw commented on pp/sidebarsPp.js
> +          id: 'integrations/plugin-packs/procedures/network-backbox-rest'
```suggestion
          id: 'integrations/plugin-packs/procedures/network-backbox-restapi'
```

2024-09-09 12:22 UTC, cg-tw requested changes

2024-09-09 12:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +depuis l'interface web et le menu **Configuration > Gestionnaire de connecteurs de supervision** :
```suggestion
depuis la page **Configuration > Gestionnaire de connecteurs de supervision** :
```

2024-09-09 12:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-09-09 12:22 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
prérequis

2024-09-09 12:22 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +## Connector Dependencies
```suggestion
## Connector dependencies
```

2024-09-09 12:22 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +*Specify prerequisites that are relevant. You may want to just provide a link\n\
prerequisites

2024-09-09 13:20 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +| CRITICALTOTAL   |                                                                                                    |                   |             |
```suggestion
| WARNINGTOTAL    | Set warning threshold for 'total'                                                                                                     |                   |             |
| CRITICALTOTAL   | Set warning threshold for 'total'                                                                                                     |                   |             |
```

2024-09-09 13:20 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +| CRITICALSUCCESS |                                                                                                    |                   |             |
```suggestion
| WARNINGSUCCESS  | Set warning threshold for 'succes'                                                                                                   |                   |             |
| CRITICALSUCCESS | Set critical threshold for 'succes'                                                                                                     |                   |             |
```

2024-09-09 13:21 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +| CRITICALTOTAL   |                                                                                                    |                   |             |
```suggestion
| WARNINGTOTAL    | Set warning threshold for 'total'                                                                                                     |                   |             |
| CRITICALTOTAL   | Set warning threshold for 'total'                                                                                                     |                   |             |
```

2024-09-09 13:21 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +| CRITICALTOTAL   |                                                                                                    |                   |             |
```suggestion
| WARNINGTOTAL    | Set warning threshold for 'total'                                                                                                     |                   |             |
| CRITICALTOTAL   | Set warning threshold for 'total'                                                                                                     |                   |             |
```

2024-09-09 13:21 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +| CRITICALTOTAL   |                                                                                                    |                   |             |
```suggestion
| WARNINGTOTAL    | Set warning threshold for 'total'                                                                                                     |                   |             |
| CRITICALTOTAL   | Set warning threshold for 'total'                                                                                                     |                   |             |
```

2024-09-09 13:21 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +| CRITICALSUCCESS |                                                                                                    |                   |             |
```suggestion
| WARNINGSUCCESS  | Set warning threshold for 'succes'                                                                                                   |                   |             |
| CRITICALSUCCESS | Set critical threshold for 'succes'                                                                                                     |                   |             |
```

2024-09-09 13:22 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +| CRITICALSUCCESS |                                                                                                    |                   |             |
```suggestion
| WARNINGSUCCESS  | Set warning threshold for 'succes'                                                                                                   |                   |             |
| CRITICALSUCCESS | Set critical threshold for 'succes'                                                                                                     |                   |             |
```

2024-09-09 14:57 UTC, cg-tw requested changes

2024-09-09 14:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +Pour utiliser le connecteur **Backbox**, vous devez generer un jeton API : rendez-vous sur votre tableau de bord Backbox puis sur la page Administrative / Authentication / API Tokens.
```suggestion
Pour utiliser le connecteur **Backbox**, vous devez générer un jeton d'API : rendez-vous sur votre tableau de bord Backbox puis sur la page **Administrative > Authentication > API Tokens**.
```

2024-09-09 14:57 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +To monitor a **Backbox** resource, you need to generate an API token: go to your Backbox dashboard and then on Administrative / Authentication / API Tokens page.
```suggestion
To monitor a **Backbox** resource, you need to generate an API token: go to your Backbox dashboard and then to the **Administrative > Authentication > API Tokens** page.
```

2024-09-09 14:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
> +Le jeton API est associé à un compte utilisateur. Il est recommandé de créer un compte utilisateur dédié à la supervision.
```suggestion
Le jeton d'API est associé à un compte utilisateur. Il est recommandé de créer un compte utilisateur dédié à la supervision.
```

2024-09-09 15:27 UTC, cg-tw approved these changes

2024-09-10 07:22 UTC, lucie-dubrunfaut approved these changes

2024-09-10 07:23 UTC, merged