Add applications drbd ssh fr
centreon/centreon-documentation pull request #355
Opened 2020-09-30 14:52 UTC by psamecentreon

2020-10-02 14:46 UTC, pkriko requested changes

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +title: DRBD
```suggestion
title: DRBD SSH
```

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +permettant la réplication de périphériques de bloc (disques, partitions, volumes logiques etc.) entre des serveurs. DRBD est un logiciel libre, mais un support existe. DRBD est composé d'un module no
```suggestion
permettant la réplication de périphériques de bloc (disques, partitions, volumes logiques etc.) entre des serveurs.
DRBD est un logiciel libre, mais un support existe. DRBD est composé d'un module noyau, 
```

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +2. Sur l'interface Web de Centreon, installer le Plugin-Pack *DRBD* depuis la page "Configuration > Plugin packs > Manager"
```suggestion
2. Sur l'interface Web de Centreon, installer le Plugin-Pack *DRBD SSH* depuis la page "Configuration > Plugin packs > Manager"
```

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +3. Sur l'interface Web de Centreon, installer le Plugin-Pack *DRBD* depuis la page "Configuration > Plugin packs > Manager"
```suggestion
3. Sur l'interface Web de Centreon, installer le Plugin-Pack *DRBD SSH* depuis la page "Configuration > Plugin packs > Manager"
```

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +et l'utilisateur applicatif créé sur le serveur Linux. (Macro SSHUSERNAME).
Wrong traduction in the description fields

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +|             | SSHEXTRAOPTIONS | Personnalisez-le avec le vôtre si nécessaire. E.g.: ```--ssh-priv-key=/user/.ssh/id_rsa```      |
Wrong trad

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +|             | SSHEXTRAOPTIONS | Personnalisez-le avec le vôtre si nécessaire. E.g.: ```--ssh-priv-key=/user/.ssh/id_rsa```      |
Wrong trad'

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +	--verbose
```suggestion
/usr/lib/centreon/plugins/centreon_drbd_ssh.pl \
    --plugin=apps::drbd::local::plugin.pm \
    --mode=resources \
    --hostname=10.30.2.81 \
    --ssh-username=centreon \
    --ssh-password=centreon-password \
    --ssh-backend=libssh \
    --legacy-proc \
    --verbose
```

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +L'option _legacy-proc_ (```--legacy-proc```) permet de pouvoir utiliser l'ancien fichier proc (```/proc/drbd```). Ce qui permet d'utiliser une version les versions antérieurs à la version 9.
```suggestion
L'option _legacy-proc_ (```--legacy-proc```) permet de pouvoir utiliser l'ancien fichier proc (```/proc/drbd```). Ce qui permet d'utiliser une version les versions antérieures à la version 9 de DRBD.
```

2020-10-02 14:46 UTC, pkriko commented on fr/integrations/plugin-packs/procedures/applications-drbd-ssh.md
> +--mode=resources --help
```suggestion
  --mode=resources --help
```

2020-10-05 08:10 UTC, Sims24 requested changes
Please see my review here: https://github.com/centreon/centreon-documentation/pull/363

2020-10-05 19:08 UTC, Sims24 approved these changes

2020-10-06 06:30 UTC, pkriko approved these changes

2020-10-06 06:30 UTC, merged