CTOR-835 : Refresh hardware-storage-wd-nas-snmp
centreon/centreon-documentation pull request #3559
Opened 2024-09-17 07:21 UTC by lucie-dubrunfaut

## Description

Refresh hardware-storage-wd-nas-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-09-17 07:47 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +Les autres équipements peuvent être supportés mais sans garanties.
J'ai ajouté les modèles d'équipement qui étaient supportés pour plus de visibilité pour l'utilisateur (sachant que la PR Communautaire du ticket https://centreon.atlassian.net/browse/CTOR-397 se rapporte justement au fait d'ajouter en plus le mode EX4100 (noté ici). Donc on ne pourra merge cette doc qu'une fois la PR sortie (on peut rebase sur la branche de Release 24.10 si besoin)

2024-10-11 14:41 UTC, cg-tw requested changes

2024-10-11 14:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +Les autres équipements peuvent être supportés mais sans garanties.
```suggestion
Les autres équipements peuvent être supportés mais sans garantie.
```

2024-10-11 14:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +| *volumes*#volume.space.usage.percentage | %     |
prérequis snmp standard

2024-10-11 14:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +OK: volume 'Volume_1' space usage total: 7.20 TB used: 5.60 TB (77.78%) free: 1.60 TB (22.22%) | 'Volume_1#volume.space.usage.bytes'=6157265115545B;;;0;7916483719987.2%20'Volume_1#volume.space.free.b
2%20?

2024-10-11 14:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +Other equipment can be supported but without guarantees.
```suggestion
Other devices may be supported but without guarantee.
```

2024-10-11 14:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
>  </Tabs>
standard snmp prerequisites

2024-10-11 14:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
>  ```bash
2%20?

2024-10-16 15:47 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +OK: volume 'Volume_1' space usage total: 7.20 TB used: 5.60 TB (77.78%) free: 1.60 TB (22.22%) | 'Volume_1#volume.space.usage.bytes'=6157265115545B;;;0;7916483719987.2%20'Volume_1#volume.space.free.b
```suggestion
OK: volume 'Volume_1' space usage total: 7.20 TB used: 5.30 TB (73.61%) free: 1.90 TB (26.39%) | 'Volume_1#volume.space.usage.bytes'=5827411627212B;;;0;7916483719987.2 'Volume_1#volume.space.free.bytes'=2089072092774B;;;0;7916483719987.2 'Volume_1#volume.space.usage.percentage'=73.61%;;;0;100
```

2024-10-16 15:47 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +OK: volume 'Volume_1' space usage total: 7.20 TB used: 5.60 TB (77.78%) free: 1.60 TB (22.22%) | 'Volume_1#volume.space.usage.bytes'=6157265115545B;;;0;7916483719987.2%20'Volume_1#volume.space.free.b
```suggestion
OK: volume 'Volume_1' space usage total: 7.20 TB used: 5.30 TB (73.61%) free: 1.90 TB (26.39%) | 'Volume_1#volume.space.usage.bytes'=5827411627212B;;;0;7916483719987.2 'Volume_1#volume.space.free.bytes'=2089072092774B;;;0;7916483719987.2 'Volume_1#volume.space.usage.percentage'=73.61%;;;0;100
```

2024-10-16 15:50 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +| *volumes*#volume.space.usage.percentage | %     |
J'ai l'impression de ne jamais trouvé la formulation exacte que tu attends ^^' donc j'attends qu'on voit ensemble pour me garder le bon exemple de côté

2024-10-22 12:20 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +OK: volume 'Volume_1' space usage total: 7.20 TB used: 5.30 TB (73.61%) free: 1.90 TB (26.39%) | 'Volume_1#volume.space.usage.bytes'=5827411627212B;;;0;7916483719987.2 'Volume_1#volume.space.free.byt
```suggestion
OK: volume 'Volume_1' space usage total: 7.20 TB used: 5.60 TB (77.78%) free: 1.60 TB (22.22%) | 'Volume_1#volume.space.usage.bytes'=6157265115545B;;;0;7916483719987.2 'Volume_1#volume.space.free.bytes'=1759218604441B;;;0;7916483719987.2 'Volume_1#volume.space.usage.percentage'=77.78%;;;0;100
```

2024-10-22 12:40 UTC, cg-tw approved these changes

2024-10-22 12:40 UTC, merged