CTOR-896 : Refresh network-cisco-firepower-fmc-restapi
centreon/centreon-documentation pull request #3561
Opened 2024-09-17 08:50 UTC by lucie-dubrunfaut

## Description

Refresh network-cisco-firepower-fmc-restapi

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-11 15:03 UTC, cg-tw requested changes

2024-10-11 15:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
>  OK: Domain 'Global' devices are ok | 'devices.total.count'=2;;;0; 'devices.status.green.count'=0;;;0;2 'devices.status.black.count'=0;;;0;2 'devices.status.blue.count'=0;;;0;2 'devices.status.red.cou
checking domain global, mais on l'a pas défini dans la commande, c'est normal?
et les chiffres sont bons? (2 au total mais 0 pour tous les autres)

2024-10-11 15:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +To control the Cisco Firepower Management Center application, the Rest API must be configured as described in the official documentation:
```suggestion
To monitor the Cisco Firepower Management Center application, the Rest API must be configured as described in the official documentation: 
```

2024-10-11 15:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +Afin de contrôler l'application Cisco Firepower Management Center, l'API Rest doit être configurée comme indiqué dans la documentation officielle :
```suggestion
Afin de superviser l'application Cisco Firepower Management Center, l'API Rest doit être configurée comme indiqué dans la documentation officielle : 
```

2024-10-11 15:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +The expected command output is shown below:
same as FR

2024-10-11 15:03 UTC, cg-tw requested changes

2024-10-11 15:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +| *domains*~*devices*#device-status | N/A   |
same as FR

2024-10-16 15:57 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
>  OK: Domain 'Global' devices are ok | 'devices.total.count'=2;;;0; 'devices.status.green.count'=0;;;0;2 'devices.status.black.count'=0;;;0;2 'devices.status.blue.count'=0;;;0;2 'devices.status.red.cou
En théorie on peut n'avoir qu'un domaine appelé 'Global' je pense on est pas obligé de filtrer dessus ?
Pour les valeurs j'ai seulement récupéré la commande telle qu'elle était dans la [doc actuelle](https://docs.centreon.com/fr/pp/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi/#comment-faire-le-test-en-ligne-de-commande-et-que-signifient-les-principales-options-) (en espérant que ce soit basé sur un vrai exemple oO) mais je n'ai pas d'accès API qui me permettrait de tester moi même la commande

2024-10-16 16:08 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +| *domains*~*devices*#device-status | N/A   |
```suggestion
| devices.total.count               | count |
| devices.status.green.count | count |
| devices.status.black.count | count |
| devices.status.blue.count | count |
| devices.status.red.count | count |
| devices.status.yellow.count | count |
| *domains*~*devices*#device-status | N/A   |
```

2024-10-16 16:09 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +| *domains*~*devices*#device-status | N/A   |
```suggestion
| devices.total.count               | count |
| devices.status.green.count | count |
| devices.status.black.count | count |
| devices.status.blue.count | count |
| devices.status.red.count | count |
| devices.status.yellow.count | count |
| *domains*~*devices*#device-status | N/A   |
```

2024-10-16 16:10 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +| *domains*~*devices*#device-status | N/A   |
Normalement good je te laisse resolve

2024-10-18 13:06 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +	--filter-device-name='' \
```suggestion
	--filter-device-name='Global' \
```

2024-10-18 13:06 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
> +	--filter-device-name='' \
```suggestion
	--filter-device-name='Global' \
```

2024-10-18 13:07 UTC, cg-tw approved these changes

2024-10-18 13:26 UTC, merged