CTOR-897 : Refresh network-cisco-firepower-snmp
centreon/centreon-documentation pull request #3562
Opened 2024-09-17 09:25 UTC by lucie-dubrunfaut

## Description

Refresh network-cisco-firepower-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-11 15:18 UTC, cg-tw requested changes

2024-10-11 15:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +| Faults   | Net-Cisco-Firepower-Faults-SNMP-custom   | Contrôle les messages d'erreurs                |
```suggestion
| Faults   | Net-Cisco-Firepower-Faults-SNMP-custom   | Contrôle les messages d'erreur                |
```

2024-10-11 15:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +| Memory   | Net-Cisco-Firepower-Memory-SNMP-custom   | Contrôle du taux d'utilisation des mémoire     |
```suggestion
| Memory   | Net-Cisco-Firepower-Memory-SNMP-custom   | Contrôle du taux d'utilisation des mémoires     |
```

2024-10-11 15:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +| Net-Cisco-Firepower-SNMP-Packet-Errors-Name | Découvrir les interfaces réseaux et supervise les paquets erronés et rejetés |
```suggestion
| Net-Cisco-Firepower-SNMP-Packet-Errors-Name | Découvre les interfaces réseau et supervise les paquets erronés et rejetés |
```

2024-10-11 15:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +| Net-Cisco-Firepower-SNMP-Traffic-Name       | Découvre les interfaces réseaux et supervise le statut et l'utilisation      |
```suggestion
| Net-Cisco-Firepower-SNMP-Traffic-Name       | Découvre les interfaces réseau et supervise leur statut et leur utilisation      |
```

2024-10-11 15:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +Pour utiliser ce connecteur de supervision, le service SNMP doit démarré et configuré sur le serveur **HP Proliant**.
Proliant???
prérequis snmp standard

2024-10-11 15:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +Afin de contrôler vos équipements Cisco Firepower, le SNMP doit être configuré (voir la documentation officielle : https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snm
le lien est mort

2024-10-11 15:18 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +| Cpu           | Net-Cisco-Firepower-Cpu-SNMP-custom      | Check the rate of the utilization of CPU    |
```suggestion
| Cpu           | Net-Cisco-Firepower-Cpu-SNMP-custom      | Check the rate of the utilization of the CPU    |
```

2024-10-11 15:18 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +| Memory        | Net-Cisco-Firepower-Memory-SNMP-custom   | Check the rate of the utilization of memory |
```suggestion
| Memory        | Net-Cisco-Firepower-Memory-SNMP-custom   | Check the rate of the utilization of the memory |
```

2024-10-11 15:18 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +To control your Cisco Firepower, the SNMP must be configured (see official documentation: https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/213971-configure-snmp-o
```suggestion
To monitor your Cisco Firepower, SNMP must be configured (see official documentation: https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/213971-configure-snmp-on-firepower-ngfw-applian.html?dtid=osscdc000283).
```

2024-10-11 15:18 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +To control your Cisco Firepower, the SNMP must be configured (see official documentation: https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/213971-configure-snmp-o
le mettre au-dessus, c'est la même chose que la 1è sous-partie

2024-10-16 16:11 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +Pour utiliser ce connecteur de supervision, le service SNMP doit démarré et configuré sur le serveur **HP Proliant**.
```suggestion
Pour utiliser ce connecteur de supervision, le service SNMP doit démarré et configuré sur le serveur **Cisco Firepower**.
```

2024-10-16 16:12 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +Afin de contrôler vos équipements Cisco Firepower, le SNMP doit être configuré (voir la documentation officielle : https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snm
```suggestion
Afin de contrôler vos équipements Cisco Firepower, le SNMP doit être configuré.
```

2024-10-18 13:10 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
> +Pour utiliser ce connecteur de supervision, le service SNMP doit démarré et configuré sur le serveur **Cisco Firepower**.
```suggestion
Pour utiliser ce connecteur de supervision, le service SNMP doit démarré et configuré sur le serveur **Cisco Firepower** (voir la [documentation officielle)](https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/213971-configure-snmp-on-firepower-ngfw-applian.html?dtid=osscdc000283).
```

2024-10-18 13:28 UTC, cg-tw approved these changes

2024-10-18 13:28 UTC, merged