[CTOR-886]- refresh SAP HANA doc page
centreon/centreon-documentation pull request #3572
Opened 2024-09-23 08:56 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-10-11 16:08 UTC, cg-tw requested changes

2024-10-11 16:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
> +| Blocked-Transactions | App-DB-Sap-Hana-Blocked-Transactions-custom | Check total  blocked transactions       |
```suggestion
| Blocked-Transactions | App-DB-Sap-Hana-Blocked-Transactions-custom | Check total blocked transactions       |
```

2024-10-11 16:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
> +| Host-Cpu             | App-DB-Sap-Hana-Host-Cpu-custom             | Check host cpu usage                    |
```suggestion
| Host-Cpu             | App-DB-Sap-Hana-Host-Cpu-custom             | Check host CPU usage                    |
```

2024-10-11 16:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
>  To monitor Sap Hana DB, you need to install SAP Hana Linux Client. The client is
```suggestion
To monitor SAP Hana DB, you need to install the SAP Hana Linux Client. The client is available
```

2024-10-11 16:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
>  on SAP support website (an account is needed).
```suggestion
on the SAP support website (an account is needed).
```

2024-10-11 16:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
>  on SAP support website (an account is needed).
same as FR, what is the command just below?

2024-10-11 16:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
>  ### Configuration of freetds.conf file
freetds.conf or odbcinst.ini?

2024-10-18 13:24 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
> +### Configuration of odbcinst.ini file
```suggestion
### Configuration file
```

2024-10-18 13:25 UTC, cg-tw approved these changes

2024-10-22 12:25 UTC, merged