CTOR-900 : Refresh network-cisco-umbrella-snmp
centreon/centreon-documentation pull request #3575
Opened 2024-09-23 10:02 UTC by lucie-dubrunfaut

## Description

Refresh network-cisco-umbrella-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-14 12:56 UTC, cg-tw requested changes

2024-10-22 12:28 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
> +| Local DNS connectivity status | N/A   |
```suggestion
| Local DNS connectivity status | N/A   |
| Umbrella dashboard (cloud) connectivity status | N/A |
| AD connectors connectivity status              | N/A |
```

2024-10-22 12:29 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
> +| Local DNS connectivity status | N/A  |
```suggestion
| Local DNS connectivity status | N/A  |
| Umbrella dashboard (cloud) connectivity status | N/A  |
| AD connectors connectivity status              | N/A  |
```

2024-10-22 13:38 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
> +| load.1m.average.count  | count |
https://github.com/centreon/centreon-plugins/blob/develop/src/snmp_standard/mode/loadaverage.pm#L115
https://github.com/centreon/centreon-plugins/blob/develop/tests/os/linux/snmp/load.robot

2024-10-28 14:11 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
> +| load.1m.average.count  | count |
C'est le nombre de processus en attente dans la file en moyenne sur X minutes et sur les X coeurs

2024-10-29 13:09 UTC, cg-tw approved these changes

2024-10-29 13:10 UTC, merged