CTOR-915 : Refresh network-acmepacket-snmp
centreon/centreon-documentation pull request #3589
Opened 2024-09-25 08:17 UTC by lucie-dubrunfaut

## Description

Refresh network-acmepacket-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-14 13:44 UTC, cg-tw requested changes

2024-10-14 13:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
> +| Net-Acmepacket-SNMP-Interface-Name     | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Acmepacket-SNMP-Interface-Name     | Découvre les interfaces réseau et en supervise le statut et l'utilisation |
```

2024-10-14 13:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
> +| Net-Acmepacket-SNMP-Realm-Name         | Découvre les Realms et supervise l'utilisation                          |
```suggestion
| Net-Acmepacket-SNMP-Realm-Name         | Découvre les Realms et en supervise l'utilisation                          |
```

2024-10-14 13:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
> +| Net-Acmepacket-SNMP-Sip-Name           | Découvre les interfaces Sip et supervise le statut et l'utilisation     |
```suggestion
| Net-Acmepacket-SNMP-Sip-Name           | Découvre les interfaces Sip et en supervise le statut et l'utilisation     |
```

2024-10-14 13:44 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
>  Afin de contrôler votre équipement Acme Packet, le SNMP doit être configuré.
standard snmp prerequisites + UDP 161

2024-10-14 13:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
> +| Policy-Servers | Net-Acmepacket-Policy-Servers-SNMP-custom | Check external policy servers statitics | X          |
```suggestion
| Policy-Servers | Net-Acmepacket-Policy-Servers-SNMP-custom | Check external policy server statistics | X          |
```

2024-10-14 13:44 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
>  To control your Acme Packet, the SNMP must be configured.
standard snmp prerequisites

2024-10-22 12:48 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
>  Afin de contrôler votre équipement Acme Packet, le SNMP doit être configuré.
```suggestion
### Configuration SNMP

L'agent SNMP doit être activé et configuré sur l'équipement. Veuillez vous référer à la documentation officielle du constructeur/éditeur.

### Flux réseau

La communication doit être possible sur le port UDP 161 depuis le collecteur Centreon vers le serveur supervisé.
```

2024-10-22 12:49 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
>  To control your Acme Packet, the SNMP must be configured.
```suggestion
### SNMP Configuration

The SNMP agent must be configured and activated on the host. Please refer to the official documentation from the manufacturer/publisher.

### Network flow

The target resource must be reachable from the Centreon poller on the UDP/161 SNMP port.
```

2024-10-22 12:51 UTC, cg-tw approved these changes

2024-10-22 13:04 UTC, merged