CTOR-918 : Refresh network-allied-snmp
centreon/centreon-documentation pull request #3595
Opened 2024-09-25 14:33 UTC by lucie-dubrunfaut

## Description

Refresh network-allied-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-14 16:21 UTC, cg-tw requested changes

2024-10-14 16:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-allied-snmp.md
> +| SNMP Agents     | Discover your resources through an SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a templ
FR

2024-10-14 16:21 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-allied-snmp.md
> +| Net-Allied-SNMP-Traffic-Name | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Allied-SNMP-Traffic-Name | Découvre les interfaces réseau et supervise leur statut et leur utilisation |
```

2024-10-22 12:56 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-allied-snmp.md
> +| SNMP Agents     | Discover your resources through an SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a templ
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **Net-Allied-SNMP-custom** |
```

2024-10-22 12:57 UTC, cg-tw approved these changes

2024-10-22 15:35 UTC, merged