CTOR-920 : Refresh network-switchs-arista-snmp
centreon/centreon-documentation pull request #3598
Opened 2024-09-25 15:06 UTC by lucie-dubrunfaut

## Description

Refresh network-switchs-arista-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-14 16:30 UTC, cg-tw requested changes

2024-10-14 16:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Packet-Errors-Generic-Id   | Net-Arista-Packet-Errors-Generic-Id-SNMP-custom   | Contrôle le pourcentage de paquets en erreur/écarté d'une interface réseau                           |
```suggestion
| Packet-Errors-Generic-Id   | Net-Arista-Packet-Errors-Generic-Id-SNMP-custom   | Contrôle le pourcentage de paquets en erreur/écartés d'une interface réseau                           |
```

2024-10-14 16:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Packet-Errors-Generic-Name | Net-Arista-Packet-Errors-Generic-Name-SNMP-custom | Contrôle le pourcentage de paquets en erreur/écarté d'une interface réseau                           |
```suggestion
| Packet-Errors-Generic-Name | Net-Arista-Packet-Errors-Generic-Name-SNMP-custom | Contrôle le pourcentage de paquets en erreur/écartés d'une interface réseau                           |
```

2024-10-14 16:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Packet-Errors-Global       | Net-Arista-Packet-Errors-Global-SNMP-custom       | Contrôle le pourcentage de paquets en erreur/écarté de plusieurs interfaces réseau                   |
```suggestion
| Packet-Errors-Global       | Net-Arista-Packet-Errors-Global-SNMP-custom       | Contrôle le pourcentage de paquets en erreur/écartés de plusieurs interfaces réseau                   |
```

2024-10-14 16:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Tcpcon-Generic             | Net-Arista-Tcpcon-Generic-SNMP-custom             | Contrôle permettant de vérifier les connexions tcp                                                   |
```suggestion
| Tcpcon-Generic             | Net-Arista-Tcpcon-Generic-SNMP-custom             | Contrôle permettant de vérifier les connexions TCP                                                   |
```

2024-10-14 16:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +OK: All interfaces are ok | *interface_name*#interface.traffic.in.bitspersecond'=4212b/s;;;;' *interface_name*#interface.traffic.out.bitspersecond'=1242b/s;;;;
thresholds

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Cpu           | Net-Arista-Cpu-SNMP-custom     | Check the rate of utilization of CPU for the equipment. This check can give the average CPU utilization rate and the rate per CPU for multi-core CPU
```suggestion
| Cpu           | Net-Arista-Cpu-SNMP-custom     | Check the rate of utilization of the CPU for the resource. This check can give the average CPU utilization rate and the rate per CPU for multi-core CPU |
```

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Memory        | Net-Arista-Memory-SNMP-custom  | Check the rate of the utilization of memory
```suggestion
| Memory        | Net-Arista-Memory-SNMP-custom  | Check the rate of the utilization of the memory                                                                                                          |
```

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Packet-Errors-Generic-Id   | Net-Arista-Packet-Errors-Generic-Id-SNMP-custom   | Check packets on errors/discards of a network interface                                      |
```suggestion
| Packet-Errors-Generic-Id   | Net-Arista-Packet-Errors-Generic-Id-SNMP-custom   | Check packets in error/discarded from a network interface                                      |
```

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Packet-Errors-Generic-Name | Net-Arista-Packet-Errors-Generic-Name-SNMP-custom | Check packets on errors/discards of a network interface                                      |
```suggestion
| Packet-Errors-Generic-Name | Net-Arista-Packet-Errors-Generic-Name-SNMP-custom | Check packets in error/discarded from a network interface                                     |
```

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Packet-Errors-Global       | Net-Arista-Packet-Errors-Global-SNMP-custom       | Check packets on errors/discards of multiple network interfaces                              |
```suggestion
| Packet-Errors-Global       | Net-Arista-Packet-Errors-Global-SNMP-custom       | Check packets in error/discarded from multiple network interfaces                              |
```

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Tcpcon-Generic             | Net-Arista-Tcpcon-Generic-SNMP-custom             | Check current tcp connections                                                                |
```suggestion
| Tcpcon-Generic             | Net-Arista-Tcpcon-Generic-SNMP-custom             | Check current TCP connections                                                                |
```

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Traffic-Generic-Id         | Net-Arista-Traffic-Generic-Id-SNMP-custom         | Check the bandwidth of the interface. For each checks the name of the interface will appear  |
```suggestion
| Traffic-Generic-Id         | Net-Arista-Traffic-Generic-Id-SNMP-custom         | Check the bandwidth of the interface. For each check the name of the interface will appear  |
```

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Traffic-Generic-Name       | Net-Arista-Traffic-Generic-Name-SNMP-custom       | Check the bandwidth of the interface. For each checks the name of the interface will appear  |
```suggestion
| Traffic-Generic-Name       | Net-Arista-Traffic-Generic-Name-SNMP-custom       | Check the bandwidth of the interface. For each check the name of the interface will appear  |
```

2024-10-14 16:30 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +| Traffic-Global             | Net-Arista-Traffic-Global-SNMP-custom             | Check the bandwidth of interfaces. For each checks the name of the interface will appear     |
```suggestion
| Traffic-Global             | Net-Arista-Traffic-Global-SNMP-custom             | Check the bandwidth of interfaces. For each check the name of the interface will appear     |
```

2024-10-22 12:59 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
> +OK: All interfaces are ok | *interface_name*#interface.traffic.in.bitspersecond'=4212b/s;;;;' *interface_name*#interface.traffic.out.bitspersecond'=1242b/s;;;;
```suggestion
OK: All interfaces are ok | *interface_name*#interface.traffic.in.bitspersecond'=4212b/s;80;90;;' *interface_name*#interface.traffic.out.bitspersecond'=1242b/s;80;90;;
```

2024-10-22 13:00 UTC, cg-tw approved these changes

2024-10-22 13:28 UTC, merged