[OnPrem 24.10] Add public playlist + known issue for MAP widget
centreon/centreon-documentation pull request #3607
Opened 2024-09-27 10:25 UTC by smau-centreon

## Description

[OnPrem 24.10] Add public playlist + known issue for MAP widget

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-10-02 09:15 UTC, rbignotticentreon requested changes

2024-10-02 09:15 UTC, rbignotticentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/dashboards.md
> -> Vous ne pouvez partager votre liste de diffusion qu'avec des contacts ayant accès à votre plateforme Centreon, et les droits de viewer sur les tableaux de bord.
Pourquoi retirer cette partie ? Si tu n'es pas viewer Dashboards on ne peut pas te partager un DB

2024-10-02 09:15 UTC, rbignotticentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/dashboards.md
> +> Le lien que vous partagez affichera le contenu de la liste de diffusion en fonction des droits d'accès. Toute personne disposant de ce lien peut consulter la liste de diffusion. Soyez vigilant lors
Je ne suis pas sûr que ce soit clair que les droits d'accès utilisés pour afficher un lien public sont ceux de la personne qui a activé le lien public

2024-10-17 12:09 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/dashboards.md
> +> Le lien que vous partagez affichera le contenu de la liste de diffusion en fonction des droits d'accès. Toute personne disposant de ce lien peut consulter la liste de diffusion. Soyez vigilant lors
Ok j'ai remplacé par :
"Le lien que vous partagez affichera le contenu de la liste de diffusion en fonction des droits d'accès de l'utilisateur qui active le lien."

2024-10-17 12:09 UTC, smau-centreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/dashboards.md
> -> Vous ne pouvez partager votre liste de diffusion qu'avec des contacts ayant accès à votre plateforme Centreon, et les droits de viewer sur les tableaux de bord.
Ok j'ai rétabli cette partie.

2024-10-18 15:43 UTC, rbignotticentreon approved these changes

2024-10-23 07:24 UTC, merged