CTOR-397 : [Plugin(storage::wd::nas::snmp) - Modes(volumes, listvolumes, hardware) : add support for ex4100 model
centreon/centreon-documentation pull request #3618
Opened 2024-10-01 09:57 UTC by lucie-dubrunfaut

## Description

Add support for ex4100 model in Modes: volumes, listvolumes and hardware

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-07 15:49 UTC, cg-tw requested changes

2024-10-07 15:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +> D'autres modèles d'équipement peuvent être compatibles mais nous ne pouvons le garantir à priori
```suggestion
> D'autres modèles d'équipement peuvent être compatibles, mais nous ne pouvons le garantir à priori.
```

2024-10-07 15:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificate
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **HW-Storage-Wd-Nas-SNMP-custom** |
```

2024-10-07 15:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
>  </Tabs>
prérequis standard SNMP

2024-10-07 15:49 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
>  </Tabs>
standard SNMP prerequisites

2024-10-08 08:38 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
>  </Tabs>
![image](https://github.com/user-attachments/assets/2219d4cb-be65-4f8c-97a6-8a8c02f52ea2)

2024-10-08 08:38 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
>  </Tabs>
![image](https://github.com/user-attachments/assets/c699fbff-c437-4dda-8957-9b936e5e788b)

2024-10-08 11:54 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +Pour utiliser ce connecteur de supervision, le service SNMP doit démarré et configuré sur le serveur **WD NAS**.
```suggestion
Pour utiliser ce connecteur de supervision, le service SNMP doit être démarré et configuré sur le serveur **WD NAS**.
```

2024-10-08 12:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
> +Pour utiliser ce connecteur de supervision, le service SNMP doit démarré et configuré sur le serveur **WD NAS**.
il manque l'histoire du manufacturer/publisher

2024-10-08 14:02 UTC, omercier approved these changes

2024-10-08 15:00 UTC, cg-tw approved these changes

2024-10-08 15:01 UTC, merged