CTOR - 815 : add(network::cisco::standard::snmp): add option --add-fc-fe-errors
centreon/centreon-documentation pull request #3620
Opened 2024-10-01 15:40 UTC by lucie-dubrunfaut

## Description

Monitor OID fcIfTxWaitCount (.1.3.6.1.4.1.9.9.289.1.2.1.1.15)

CTOR-815

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-09 15:51 UTC, cg-tw requested changes

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| Arp           | Net-Cisco-Standard-Arp-SNMP-custom           | Contrôle la table arp                                         |            |
```suggestion
| Arp           | Net-Cisco-Standard-Arp-SNMP-custom           | Contrôle la table ARP                                         |            |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| Net-Cisco-Standard-SNMP-Interface-Name  | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Cisco-Standard-SNMP-Interface-Name  | Découvre les interfaces réseau et supervise leur statut et leur utilisation |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| FILTERNAME                       | Filter AAA server by name (E.g.: 10.199.126.100:1812:1813. Format: \[address\]:\[authPort\]:\[accPort\])                                         |
```suggestion
| FILTERNAME                       | Filter AAA server by name (Example: 10.199.126.100:1812:1813. Format: \[address\]:\[authPort\]:\[accPort\])                                         |                      |             |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error if HSRPs are 'standby' states. Ifrole is 'secondary', an error if HSRPs are 'active' states.                      | primary           | X           |
```suggestion
| ROLE         | If role is 'primary', an error if HSRPs are 'standby' states. If role is 'secondary', an error if HSRPs are 'active' states.                      | primary           | X           |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error if HSRPs are 'standby' states. Ifrole is 'secondary', an error if HSRPs are 'active' states.                      | primary           | X           |
the sentences make no sense

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| UNITSTRAFFIC            | Units of thresholds for the traffic ('percent\_delta', 'bps', 'counter')                                                                                                 |
```suggestion
| UNITSTRAFFIC            | Units in which the thresholds are given for the traffic ('percent\_delta', 'bps', 'counter')                                                                                                 | percent\_delta                                        |             |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --filter-name            | Filter AAA server by name (E.g.: 10.199.126.100:1812:1813. Format: \[address\]:\[authPort\]:\[accPort\]).
```suggestion
| --filter-name            | Filter AAA server by name (Example: 10.199.126.100:1812:1813. Format: \[address\]:\[authPort\]:\[accPort\]).                                                                                                                                     |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --filter-ipaddr          | Filter ip addresses (can be a regexp).                                           |
```suggestion
| --filter-ipaddr          | Filter IP addresses (can be a regexp).                                           |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --role        | If role is 'primary', an error if HSRPs are 'standby' states. Ifrole is 'secondary', an error if HSRPs are 'active' states. (default: 'primary')    |
```suggestion
| --role        | If role is 'primary', an error if HSRPs are 'standby' states. If role is 'secondary', an error if HSRPs are 'active' states. (default: 'primary')    |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --role        | If role is 'primary', an error if HSRPs are 'standby' states. Ifrole is 'secondary', an error if HSRPs are 'active' states. (default: 'primary')    |
same here, doesn't make sense

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --check-order    | Check memory in standard cisco mib. If you have some issue (wrong memory information in a specific mib), you can change the order (default: 'enhanced\_pool,pool,process,system\_e
```suggestion
| --check-order    | Check memory in standard cisco MIB. If you have some issue (wrong memory information in a specific MIB), you can change the order (default: 'enhanced\_pool,pool,process,system\_ext').    |
```

2024-10-09 15:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --warning-* --critical-* | Set thresholds for members count for each states.can be: 'waiting', 'progressing', 'added', 'ready', 'sdm-mismatch', 'version-mismatch', 'feature-mismatch', 'new-master-i
```suggestion
| --warning-* --critical-* | Set thresholds on members count for each states. (Can be: 'waiting', 'progressing', 'added', 'ready', 'sdm-mismatch', 'version-mismatch', 'feature-mismatch', 'new-master-init', 'provisioned', 'invalid', 'removed')                                                                                                                                                                                 |
```

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| Cpu           | Net-Cisco-Standard-Cpu-SNMP-custom         | Check the rate of utilization of CPU for the machine. This check can give the average utilization rate of CPU |
```suggestion
| Cpu           | Net-Cisco-Standard-Cpu-SNMP-custom         | Check the rate of utilization of the CPU for the machine. This check can give the average utilization rate of the CPU |
```

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| Arp           | Net-Cisco-Standard-Arp-SNMP-custom           | Check arp table.                                                       |            |
```suggestion
| Arp           | Net-Cisco-Standard-Arp-SNMP-custom           | Check ARP table.                                                       |            |
```

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| FILTERNAME                       | Filter AAA server by name (E.g.: 10.199.126.100:1812:1813. Format: \[address\]:\[authPort\]:\[accPort\])                                |                      |
```suggestion
| FILTERNAME                       | Filter AAA server by name (Example: 10.199.126.100:1812:1813. Format: \[address\]:\[authPort\]:\[accPort\])                                |                      |             |
```

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error if HSRPs are 'standby' states. Ifrole is 'secondary', an error if HSRPs are 'active' states.            | primary           | X           |
```suggestion
| ROLE         | If role is 'primary', an error if HSRPs are 'standby' states. If role is 'secondary', an error if HSRPs are 'active' states.            | primary           | X           |
```

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error if HSRPs are 'standby' states. Ifrole is 'secondary', an error if HSRPs are 'active' states.            | primary           | X           |
makes no sense

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --filter-name            | Filter AAA server by name (E.g.: 10.199.126.100:1812:1813. Format: \[address\]:\[authPort\]:\[accPort\]).
```suggestion
| --filter-name            | Filter AAA server by name (Example: 10.199.126.100:1812:1813. Format: \[address\]:\[authPort\]:\[accPort\]).                                                                                                                                     |
```

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --check-order            | Check CPU in standard cisco mib. If you have some issue (wrong CPU information in a specific mib), you can change the order (default: 'process,old\_sys,system\_ext').   |
```suggestion
| --check-order            | Check CPU in standard cisco MIB. If you have some issue (wrong CPU information in a specific MIB), you can change the order (default: 'process,old\_sys,system\_ext').   |
```

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --role        | If role is 'primary', an error if HSRPs are 'standby' states. Ifrole is 'secondary', an error if HSRPs are 'active' states. (default: 'primary')    |
```suggestion
| --role        | If role is 'primary', an error if HSRPs are 'standby' states. If role is 'secondary', an error if HSRPs are 'active' states. (default: 'primary')    |
```

2024-10-09 15:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --role        | If role is 'primary', an error if HSRPs are 'standby' states. Ifrole is 'secondary', an error if HSRPs are 'active' states. (default: 'primary')    |
same here, makes no sense

2024-10-10 07:22 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error if HSRPs are 'standby' states. If role is 'secondary', an error if HSRPs are 'active' states.                      | primary           | X           |
```suggestion
| ROLE         | If role is 'primary', an error is return if HSRPs are 'standby' states. If role is 'secondary', an error is returb if HSRPs are 'active' states.                      | primary           | X           |
```

2024-10-10 07:22 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --role        | If role is 'primary', an error if HSRPs are 'standby' states. If role is 'secondary', an error if HSRPs are 'active' states. (default: 'primary')    |
```suggestion
| --role        | If role is 'primary', an error is return if HSRPs are 'standby' states. If role is 'secondary', an error is returb if HSRPs are 'active' states. (default: 'primary')    |
```

2024-10-10 07:23 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error if HSRPs are 'standby' states. If role is 'secondary', an error if HSRPs are 'active' states.            | primary           | X           |
```suggestion
| ROLE         | If role is 'primary', an error is return if HSRPs are 'standby' states. If role is 'secondary', an error is returb if HSRPs are 'active' states.           | primary           | X           |
```

2024-10-10 07:23 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --role        | If role is 'primary', an error if HSRPs are 'standby' states. If role is 'secondary', an error if HSRPs are 'active' states. (default: 'primary')    |
```suggestion
| --role        | If role is 'primary', an error is return if HSRPs are 'standby' states. If role is 'secondary', an error is returb if HSRPs are 'active' states. (default: 'primary')    |
```

2024-10-10 08:12 UTC, omercier approved these changes

2024-10-10 09:46 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error is returned when HSRPs are 'standby' states. If role is 'secondary', an error is returned when HSRPs are 'active' states.                      | primar
```suggestion
| ROLE         | If role is 'primary', an error is returned when HSRPs are in a 'standby' states. If role is 'secondary', an error is returned when HSRPs are in a 'active' states.                      | primary           | X           |
```

2024-10-10 09:47 UTC, cg-tw requested changes

2024-10-10 09:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error is returned when HSRPs are 'standby' states. If role is 'secondary', an error is returned when HSRPs are 'active' states.                      | primar
```suggestion
| ROLE         | If role is 'primary', an error is returned when HSRPs are in a 'standby' state. If role is 'secondary', an error is returned when HSRPs are in an 'active' state.                      | primary           | X           |
```

2024-10-10 09:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --role        | If role is 'primary', an error is returned when HSRPs are 'standby' states. If role is 'secondary', an error is returned when HSRPs are 'active' states. Default: 'primary'.    |
```suggestion
| --role        | If role is 'primary', an error is returned when HSRPs are in a 'standby' state. If role is 'secondary', an error is returned when HSRPs are in an 'active' state. Default: 'primary'.    |
```

2024-10-10 09:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| ROLE         | If role is 'primary', an error is returned when HSRPs are 'standby' states. If role is 'secondary', an error is returned when HSRPs are 'active' states.           | primary
```suggestion
| ROLE         | If role is 'primary', an error is returned when HSRPs are in a 'standby' state. If role is 'secondary', an error is returned when HSRPs are in an 'active' state.           | primary           | X           |
```

2024-10-10 09:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
> +| --role        | If role is 'primary', an error is returned when HSRPs are 'standby' states. If role is 'secondary', an error is returned when HSRPs are 'active' states. Default: 'primary'.    |
```suggestion
| --role        | If role is 'primary', an error is returned when HSRPs are in a 'standby' state. If role is 'secondary', an error is returned when HSRPs are in an 'active' state. Default: 'primary'.    |
```

2024-10-10 09:48 UTC, cg-tw approved these changes

2024-10-10 11:25 UTC, merged