CTOR-922 : Refresh network-aruba-orchestrator-restapi
centreon/centreon-documentation pull request #3623
Opened 2024-10-02 07:58 UTC by lucie-dubrunfaut

## Description

Refresh network-aruba-orchestrator-restapi

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-15 12:47 UTC, cg-tw requested changes

2024-10-15 12:47 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
> +	--access-token=''  \
--access-token or --api-token? mandatory value?

2024-10-15 12:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
> +| Aruba Orchestrator Appliance | Discover Aruba Orchestrator Appliances |
```suggestion
| Aruba Orchestrator Appliance | Discover Aruba Orchestrator appliances |
```

2024-10-15 12:47 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
> +	--access-token=''  \
same as FR

2024-10-29 13:22 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
> +	--access-token=''  \
```suggestion
	--access-token='XXXX'  \
```

2024-10-29 13:23 UTC, cg-tw approved these changes

2024-10-29 13:43 UTC, merged