CTOR-924 : Refresh network-routers-atrica-snmp
centreon/centreon-documentation pull request #3624
Opened 2024-10-02 09:35 UTC by lucie-dubrunfaut

## Description

Refresh network-routers-atrica-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-15 12:52 UTC, cg-tw requested changes

2024-10-15 12:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +|:------|:------------------|:------------|
nothing

2024-10-15 12:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +| Connections-Generic-Id   | Net-Atrica-Connections-Generic-Id-SNMP-custom   | Contrôle le traffic  |
```suggestion
| Connections-Generic-Id   | Net-Atrica-Connections-Generic-Id-SNMP-custom   | Contrôle le trafic  |
```

2024-10-15 12:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +| Connections-Generic-Name | Net-Atrica-Connections-Generic-Name-SNMP-custom | Contrôle le traffic  |
```suggestion
| Connections-Generic-Name | Net-Atrica-Connections-Generic-Name-SNMP-custom | Contrôle le trafic  |
```

2024-10-15 12:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +| Connections-Global       | Net-Atrica-Connections-Global-SNMP-custom       | Contrôle le traffic  |
```suggestion
| Connections-Global       | Net-Atrica-Connections-Global-SNMP-custom       | Contrôle le trafic  |
```

2024-10-15 12:52 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +|:--------------|:------------------|:--------------------|
nothing

2024-10-15 12:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +| Connections-Generic-Name | Net-Atrica-Connections-Generic-Name-SNMP-custom | Contrôle le traffic  |
we have 3 times the same description for 3 different things

2024-10-29 13:28 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +|:------|:------------------|:------------|
```suggestion
Pas de modèle de service rattaché à ce modèle d'hôte.
```

2024-10-29 13:39 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +| Connections-Global       | Net-Atrica-Connections-Global-SNMP-custom       | Contrôle le trafic  |
```suggestion
| Connections-Generic-Id   | Net-Atrica-Connections-Generic-Id-SNMP-custom   | Contrôle le trafic de l'équipement ayant un ID spécifié |
| Connections-Generic-Name | Net-Atrica-Connections-Generic-Name-SNMP-custom | Contrôle le trafic de l'équipement ayant un nom spécifié |
| Connections-Global       | Net-Atrica-Connections-Global-SNMP-custom       | Contrôle le trafic  |
```

2024-10-29 13:40 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +|:--------------|:------------------|:--------------------|
```suggestion
No service template linked to this host template.
```

2024-10-29 13:41 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +| Connections-Global       | Net-Atrica-Connections-Global-SNMP-custom       | Check traffic       |
```suggestion
| Connections-Generic-Id   | Net-Atrica-Connections-Generic-Id-SNMP-custom   | Check device traffic using a specified ID       |
| Connections-Generic-Name | Net-Atrica-Connections-Generic-Name-SNMP-custom | Check device traffic using a specified name      |
| Connections-Global       | Net-Atrica-Connections-Global-SNMP-custom       | Check traffic       |
```

2024-10-31 10:26 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +| FILTER                | Set the interface (number expected) example: 1,2,... (empty means 'check all interfaces')
```suggestion
| FILTER                | Set the interface (number expected) example: 1,2,... (empty means 'check all connections'). Can be a regex                                                                                                                                                                                              | .+                 |             |
```

2024-10-31 10:27 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +| FILTER                | Set the interface (number expected) example: 1,2,... (empty means 'check all interfaces')
```suggestion
| FILTER                | Set the interface (number expected) example: 1,2,... (empty means 'check all connections'). Can be a regex                                                                                                                                                                                             | .+                 |             |
```

2024-10-31 10:59 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +> Les services listés ci-dessus sont créés automatiquement lorsque le modèle d'hôte **Net-Atrica-SNMP-custom** est utilisé.
```suggestion
```

2024-10-31 11:00 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md
> +> The services listed above are created automatically when the **Net-Atrica-SNMP-custom** host template is used.
```suggestion
```

2024-11-05 13:05 UTC, cg-tw approved these changes

2024-11-05 13:05 UTC, merged