CTOR-950 : Pack(Applications-rapidrecovery-snmp) : Fix commands typo for both modes
centreon/centreon-documentation pull request #3628
Opened 2024-10-02 15:33 UTC by lucie-dubrunfaut

## Description

Refresh Doc page for the occasion

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-02 16:03 UTC, cg-tw requested changes

2024-10-02 16:03 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md
> +	--unknown-status='%{status} =~ /unknown/i' \
same as FR

2024-10-07 09:27 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md
> +	--unknown-status='%{status} =~ /unknown/i' \
![image](https://github.com/user-attachments/assets/284ae562-23b8-4fa3-b328-48f9908ced14)
C'est parce que le status unknown peut être sur la variable display également. Sinon j'ai pas compris ta question ^^'

2024-10-07 09:27 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md
> +	--critical-status='%{status} =~ /error/i' \
![image](https://github.com/user-attachments/assets/498d668f-ff83-4db3-b155-1e2988883497)
Pareil

2024-10-08 06:42 UTC, omercier approved these changes

2024-10-08 07:57 UTC, cg-tw approved these changes

2024-10-08 08:29 UTC, merged