Refresh network-atto-fibrebridge-snmp
centreon/centreon-documentation pull request #3642
Opened 2024-10-09 08:22 UTC by lucie-dubrunfaut

## Description

Refresh network-atto-fibrebridge-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-09 09:35 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-atto-fibrebridge-snmp.md
> +	--mode=fcport-usage \
```suggestion
	--mode=hardware \
```

2024-10-09 09:36 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-atto-fibrebridge-snmp.md
> +	--mode=fcport-usage \
```suggestion
	--mode=hardware \
```

2024-10-09 09:50 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-atto-fibrebridge-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificate
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **Net-Atto-Fibrebridge-SNMP-custom** |
```

2024-10-15 12:57 UTC, cg-tw requested changes

2024-10-15 12:57 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-atto-fibrebridge-snmp.md
> +| Fcport-Usage    | Net-Atto-Fibrebridge-Fcport-Usage-SNMP-custom    | Check fc port usage |
```suggestion
| Fcport-Usage    | Net-Atto-Fibrebridge-Fcport-Usage-SNMP-custom    | Check fiber channel port usage |
```

2024-10-29 14:00 UTC, merged