Refresh network-cyberoam-snmp
centreon/centreon-documentation pull request #3672
Opened 2024-10-16 08:00 UTC by lucie-dubrunfaut

## Description

Refresh network-cyberoam-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-16 16:48 UTC, cg-tw requested changes

2024-10-16 16:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-16 16:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
> +| Traffic-Global | Net-Cyberoam-Traffic-Global-SNMP-custom | Contrôle le traffic réseau de plusieurs interfaces réseau | X          |
```suggestion
| Traffic-Global | Net-Cyberoam-Traffic-Global-SNMP-custom | Contrôle le trafic réseau de plusieurs interfaces réseau | X          |
```

2024-10-16 16:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
> +| Net-Cyberoam-SNMP-Traffic-Name | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Cyberoam-SNMP-Traffic-Name | Découvre les interfaces réseau et supervise leur statut et leur utilisation |
```

2024-10-16 16:48 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
> +	--warning-in-traffic='80' \
is that a percentage?

2024-10-16 16:48 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
> +| Cpu           | Net-Cyberoam-Cpu-SNMP-custom      | Check the rate of utilization of CPU for the machine |
```suggestion
| Cpu           | Net-Cyberoam-Cpu-SNMP-custom      | Check the rate of CPU utilization for the machine |
```

2024-10-16 16:48 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
> +	--warning-in-traffic='80' \
is this a percentage?

2024-11-05 15:42 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
> +OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=54590b/s;80;90;; 'interface_name2#interface.traffic.in.bitspersecond'=67975b/s;80;90;; 'interface_name1#interface.traf
```suggestion
OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=20b/s;80;90;; 'interface_name2#interface.traffic.in.bitspersecond'=20b/s;80;90;; 'interface_name1#interface.traffic.out.bitspersecond'=20b/s;80;90;; 'interface_name2#interface.traffic.out.bitspersecond'=20b/s;80;90;;
```

2024-11-05 15:43 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
> +OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=54590b/s;80;90;; 'interface_name2#interface.traffic.in.bitspersecond'=67975b/s;80;90;; 'interface_name1#interface.traf
```suggestion
OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=20b/s;80;90;; 'interface_name2#interface.traffic.in.bitspersecond'=20b/s;80;90;; 'interface_name1#interface.traffic.out.bitspersecond'=20b/s;80;90;; 'interface_name2#interface.traffic.out.bitspersecond'=20b/s;80;90;;
```

2024-11-12 13:06 UTC, cg-tw approved these changes

2024-11-12 13:06 UTC, merged