Refresh network-dell-nseries-snmp
centreon/centreon-documentation pull request #3674
Opened 2024-10-16 12:00 UTC by lucie-dubrunfaut

## Description

Refresh network-dell-nseries-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-16 17:02 UTC, cg-tw requested changes

2024-10-16 17:02 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md
>  </Tabs>
prérequis standard SNMP

2024-10-16 17:02 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md
> +| Cpu           | Net-Dell-Nseries-Cpu-SNMP-custom         | Check the rate of utilization of CPU for the machine. This check can give the average utilization rate of CPU |
```suggestion
| Cpu           | Net-Dell-Nseries-Cpu-SNMP-custom         | Check the rate of CPU utilization for the machine. This check can give the average utilization rate of the CPU |
```

2024-10-16 17:02 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificate
FR in EN

2024-10-29 14:55 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md
> +| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificate
```suggestion
| SNMP Agents     | Discover your resources through an SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule and create a template mapper for the **Net-Dell-Nseries-SNMP-custom** host template |
```

2024-10-29 14:56 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md
> +| SNMP Agents     | Discover your resources through an SNMP subnet scan. You need to install the [Generic SNMP](./applications-protocol-snmp.md) connector to get the discovery rule |
```suggestion
| SNMP Agents     | Découvre les ressources via un scan réseau SNMP. Installez le connecteur [Generic SNMP](./applications-protocol-snmp.md) pour obtenir la règle de découverte et créez un modificateur pour le modèle d'hôte **Net-Dell-Nseries-SNMP-custom** |
```

2024-11-05 13:25 UTC, merged