Refresh network-denyall-snmp
centreon/centreon-documentation pull request #3675
Opened 2024-10-16 12:21 UTC by lucie-dubrunfaut

## Description

Refresh network-denyall-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-16 17:11 UTC, cg-tw requested changes

2024-10-16 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-16 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +| Load    | Net-Denyall-Load-SNMP-custom    | Contrôle la load average          |
```suggestion
| Load    | Net-Denyall-Load-SNMP-custom    | Contrôle la charge moyenne          |
```

2024-10-16 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +| Swap    | Net-Denyall-Swap-SNMP-custom    | Contrôle la swap                  |
```suggestion
| Swap    | Net-Denyall-Swap-SNMP-custom    | Contrôle le swap                  |
```

2024-10-16 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +| Net-Denyall-SNMP-Interface-Name    | Découvre les interfaces réseaux et supervise le statut et l'utilisation |
```suggestion
| Net-Denyall-SNMP-Interface-Name    | Découvre les interfaces réseau et en supervise le statut et l'utilisation |
```

2024-10-16 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +Afin de superviser votre **DenyAll** en SNMP, il est nécessaire de configurer l'agent sur l'équipement.
l'agent?

2024-10-16 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +| WARNINGCOUNT   | Warning threshol                                                                                                                                 |                              |
```suggestion
| WARNINGCOUNT   | Warning threshold                                                                                                                                 |                              |             |
```

2024-10-16 17:11 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +| Cpu           | Net-Denyall-Cpu-SNMP-custom     | Check cpu usage     |
```suggestion
| Cpu           | Net-Denyall-Cpu-SNMP-custom     | Check CPU usage     |
```

2024-10-16 17:11 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +| Load          | Net-Denyall-Load-SNMP-custom    | Check load-average  |
```suggestion
| Load          | Net-Denyall-Load-SNMP-custom    | Check load average  |
```

2024-10-16 17:11 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +### SNMP Configuration
missing sentence

2024-10-16 17:11 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +To use this pack, the SNMP service must be properly configured on your **DenyAll** equipment.
```suggestion
To use this pack, the SNMP service must be properly configured on your **DenyAll** respurce.
```

2024-10-29 14:57 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-denyall-snmp.md
> +Afin de superviser votre **DenyAll** en SNMP, il est nécessaire de configurer l'agent sur l'équipement.
```suggestion
### Configuration SNMP

L'agent SNMP doit être activé et configuré sur l'équipement. Veuillez vous référer à la documentation officielle du constructeur/éditeur.
```

2024-11-05 13:26 UTC, cg-tw approved these changes

2024-11-05 13:26 UTC, merged