Refresh network-digi-sarian-snmp
centreon/centreon-documentation pull request #3676
Opened 2024-10-16 12:34 UTC by lucie-dubrunfaut

## Description

Refresh network-digi-sarian-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-17 09:02 UTC, cg-tw requested changes

2024-10-17 09:02 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +2. Whatever the license type (*online* or *offline*), install the **Digi Sarian** connector through
```suggestion
2. Whatever the license type (*online* or *offline*), install the **Digi Sarian SNMP** connector through
```

2024-10-17 09:02 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +2. Quel que soit le type de la licence (*online* ou *offline*), installez le connecteur **Digi Sarian**
```suggestion
2. Quel que soit le type de la licence (*online* ou *offline*), installez le connecteur **Digi Sarian SNMP**
```

2024-10-17 09:02 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=48034b/s;;80;90; 'interface_name2#interface.traffic.in.bitspersecond'=79181b/s;;80;90; 'interface_name1#interface.traf
place des valeurs?

2024-10-17 09:02 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +	--warning-out-traffic='80' \
pourcentage?

2024-10-29 15:00 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +Afin de superviser votre **Digi Sarian** en SNMP, il est nécessaire de configurer l'agent sur l'équipement.
```suggestion
L'agent SNMP doit être activé et configuré sur l'équipement. Veuillez vous référer à la documentation officielle du constructeur/éditeur.
```

2024-10-29 15:00 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +Centreon vers le serveur supervisé.
```suggestion
La communication doit être possible sur le port UDP 161 depuis le collecteur Centreon vers le serveur supervisé.
```

2024-10-29 15:01 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +To use this pack, the SNMP service must be properly configured on your **Digi Sarian** equipment.
```suggestion
The SNMP agent must be configured and activated on the host. Please refer to the official documentation from the manufacturer/publisher.
```

2024-10-29 15:01 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +SNMP port.
```suggestion
The target resource must be reachable from the Centreon poller on the UDP/161 SNMP port.
```

2024-10-29 15:22 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=48034b/s;;80;90; 'interface_name2#interface.traffic.in.bitspersecond'=79181b/s;;80;90; 'interface_name1#interface.traf
```suggestion
OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=48034b/s;80;90;; 'interface_name2#interface.traffic.in.bitspersecond'=79181b/s;80;90;;  'interface_name1#interface.traffic.out.bitspersecond'=60438b/s;80;90;;  'interface_name2#interface.traffic.out.bitspersecond'=1708b/s;80;90;;  
```

2024-10-29 15:23 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=48034b/s;;80;90; 'interface_name2#interface.traffic.in.bitspersecond'=79181b/s;;80;90; 'interface_name1#interface.traf
```suggestion
OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=48034b/s;80;90;; 'interface_name2#interface.traffic.in.bitspersecond'=79181b/s;80;90;;  'interface_name1#interface.traffic.out.bitspersecond'=60438b/s;80;90;;  'interface_name2#interface.traffic.out.bitspersecond'=1708b/s;80;90;;  
```

2024-11-05 15:45 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
> +OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=48034b/s;80;90;; 'interface_name2#interface.traffic.in.bitspersecond'=79181b/s;80;90;;  'interface_name1#interface.tra
```suggestion
OK: All interfaces are ok | 'interface_name1#interface.traffic.in.bitspersecond'=20b/s;80;90;; 'interface_name2#interface.traffic.in.bitspersecond'=20b/s;80;90;;  'interface_name1#interface.traffic.out.bitspersecond'=20b/s;80;90;;  'interface_name2#interface.traffic.out.bitspersecond'=20b/s;80;90;;  
```

2024-11-12 13:06 UTC, cg-tw approved these changes

2024-11-12 13:07 UTC, merged