Refresh network-evertz-fc7800-snmp
centreon/centreon-documentation pull request #3678
Opened 2024-10-16 12:56 UTC by lucie-dubrunfaut

## Description

Refresh network-evertz-fc7800-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-17 09:15 UTC, cg-tw requested changes

2024-10-17 09:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-17 09:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +Les connecteurs de supervision suivants sont automatiquement installés lors de l'installation du connecteur **Evertz FC7800**
```suggestion
Les connecteurs de supervision suivants sont automatiquement installés lors de l'installation du connecteur **Evertz FC7800 SNMP** 
```

2024-10-17 09:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +Le connecteur de supervision **Evertz FC7800** apporte un modèle d'hôte :
```suggestion
Le connecteur de supervision **Evertz FC7800 SNMP** apporte un modèle d'hôte :
```

2024-10-17 09:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +Afin de superviser votre **Evertz FC7800** en SNMP, il est nécessaire de configurer l'agent sur l'équipement.
prérequis standard

2024-10-17 09:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +## Connector Dependencies
```suggestion
## Connector dependencies
```

2024-10-17 09:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +The following monitoring connectors will be installed when you install the **Evertz FC7800** connector through the
```suggestion
The following monitoring connectors will be installed when you install the **Evertz FC7800 SNMP** connector through the
```

2024-10-17 09:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +The Monitoring Connector **Evertz FC7800** brings a host template:
```suggestion
The Monitoring Connector **Evertz FC7800 SNMP** brings a host template:
```

2024-10-17 09:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +
standard prerequisites

2024-10-17 09:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +To use this pack, the SNMP service must be properly configured on your **Evertz FC7800** equipment.
```suggestion
To use this pack, the SNMP service must be properly configured on your **Evertz FC7800** resource.
```

2024-10-29 15:04 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +Afin de superviser votre **Evertz FC7800** en SNMP, il est nécessaire de configurer l'agent sur l'équipement.
```suggestion
L'agent SNMP doit être activé et configuré sur l'équipement. Veuillez vous référer à la documentation officielle du constructeur/éditeur.
```

2024-10-29 15:04 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +Centreon vers le serveur supervisé.
```suggestion
La communication doit être possible sur le port UDP 161 depuis le collecteur Centreon vers le serveur supervisé.
```

2024-10-29 15:05 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-evertz-fc7800-snmp.md
> +SNMP port.
```suggestion
The target server must be reachable from the Centreon poller on the UDP/161 SNMP port.
```

2024-11-05 13:29 UTC, merged