Refresh network-fortinet-fortiauthenticator-snmp
centreon/centreon-documentation pull request #3680
Opened 2024-10-16 14:03 UTC by lucie-dubrunfaut

## Description

Refresh network-fortinet-fortiauthenticator-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-17 09:36 UTC, cg-tw requested changes

2024-10-17 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-17 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
> +| Ha            | Net-Fortinet-Fortiauthenticator-Ha-SNMP-custom            | Contrôle le statut de la haute-disponibilité |
```suggestion
| Ha            | Net-Fortinet-Fortiauthenticator-Ha-SNMP-custom            | Contrôle le statut de la haute disponibilité |
```

2024-10-17 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
> +| Disk-Log      | Net-Fortinet-Fortiauthenticator-Disk-Log-SNMP-custom      | Contrôle l'utilisation du disque de log      |
c'est quoi un disque de log?

2024-10-17 09:36 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
>  </Tabs>
agent?

2024-10-17 09:36 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
> +## Connector Dependencies
```suggestion
## Connector dependencies
```

2024-10-17 09:36 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
> +| Cpu           | Net-Fortinet-Fortiauthenticator-Cpu-SNMP-custom           | Check cpu usage                |
```suggestion
| Cpu           | Net-Fortinet-Fortiauthenticator-Cpu-SNMP-custom           | Check CPU usage                |
```

2024-10-17 09:36 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
> +| Ha            | Net-Fortinet-Fortiauthenticator-Ha-SNMP-custom            | Check high-availability status |
```suggestion
| Ha            | Net-Fortinet-Fortiauthenticator-Ha-SNMP-custom            | Check high availability status |
```

2024-10-29 15:11 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
> +| Disk-Log      | Net-Fortinet-Fortiauthenticator-Disk-Log-SNMP-custom      | Contrôle l'utilisation du disque de log      |
```suggestion
| Disk-Log      | Net-Fortinet-Fortiauthenticator-Disk-Log-SNMP-custom      | Vérifier l'utilisation du disque d'enregistrement      |
```

2024-11-05 13:37 UTC, cg-tw approved these changes

2024-11-05 13:52 UTC, merged