Refresh network-fritzbox-upnp
centreon/centreon-documentation pull request #3681
Opened 2024-10-16 14:43 UTC by lucie-dubrunfaut

## Description

Refresh network-fritzbox-upnp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-17 09:42 UTC, cg-tw requested changes

2024-10-17 09:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fritzbox-upnp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-17 09:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fritzbox-upnp.md
> +| Traffic | Net-Fritzbox-Traffic-UPNP-custom | Contrôle le traffic réseau de l'interface WAN |
```suggestion
| Traffic | Net-Fritzbox-Traffic-UPNP-custom | Contrôle le trafic réseau de l'interface WAN |
```

2024-10-17 09:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fritzbox-upnp.md
>  Afin de contrôler votre équipement Fritz!Box, l'UPnP doit être configuré.
?

2024-10-17 09:42 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fritzbox-upnp.md
> +| Traffic       | Net-Fritzbox-Traffic-UPNP-custom | Check wan traffic interface |
```suggestion
| Traffic       | Net-Fritzbox-Traffic-UPNP-custom | Check wan interface traffic |
```

2024-10-17 09:42 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-fritzbox-upnp.md
>  To control your Fritz!Box, the UPnP must be configured.
?

2024-11-05 13:40 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fritzbox-upnp.md
>  Afin de contrôler votre équipement Fritz!Box, l'UPnP doit être configuré.
```suggestion
Afin de contrôler votre équipement Fritz!Box, l'UPnP doit être configuré. Référez vous à la [documentation officielle](https://en.avm.de/service/manuals/fritzbox/).
```

2024-11-05 13:42 UTC, cg-tw approved these changes

2024-11-05 13:59 UTC, merged