Revise documentation for Opsgenie
centreon/centreon-documentation pull request #3686
Opened 2024-10-21 08:16 UTC by lucie-dubrunfaut

## Description

Revise documentation for Opsgenie

## Target version (i.e. version that this PR changes)

- [x] 22.10.x
- [x] 23.04.x
- [x] 23.10.x
- [x] 24.04.x
- [x] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-10-21 08:34 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | default_priority            |
@tanguyvda j'ai pas vraiment compris ce qu'il y avait dans ce paramètre :/

2024-10-21 08:34 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | accepted_elements           | Élément Centreon géré par ce connecteur (pour en ajouter, vous devez regarder la section des format d'événement personnalisé, voir ci-dessous), la iste de élé
@tanguyvda Je suis pas sûre sur les "ba" comme valeur possible dans ce paramètre

2024-10-21 09:50 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | integration_api_token | Clé d'authentification à l'API pour les incidents (nécessite le module Centreon BAM) | `an_authkey`      |
@tanguyvda d'après le code j'ai l'impression que cet argument n'est pas utilisé ?
Juste initialisé [ici](https://github.com/centreon/centreon-stream-connector-scripts/blob/develop/centreon-certified/opsgenie/opsgenie-events-apiv2.lua#L62).

2024-10-21 10:17 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +curl -X POST -H 'content-type: application/json' -H 'Authorization: GenieKey <app_api_token>' 'https://api.opsgenie.com/v2/alerts' -d '{"description":"Output returned from plugin","message":"2024-10-
@tanguyvda 
Pas si sûre de la commande car l'option `log_curl_command` n'a pas voulu fonctionner...
```
User parameter: nil is not handled by this stream connector
```

2024-10-22 07:32 UTC, lucie-dubrunfaut commented
A dupliquer sur les autres versions quand les pages FR et EN seront validées

2024-10-22 09:45 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +> Replace all the <xxxx> inside the above command with the appropriate value.
```suggestion
> Replace all the ** \<xxxx\>** inside the above command with the appropriate value.
```

2024-10-22 09:45 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +> Remplacez tous les *`<xxxx>`* dans la commande ci-dessus par la valeur correcte.
```suggestion
> Remplacez tous les **\<xxxx\>** dans la commande ci-dessus par la valeur correcte.
```

2025-02-12 13:13 UTC, lucie-tirand commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | accepted_elements           | Élément Centreon géré par ce connecteur (pour en ajouter, vous devez regarder la section des format d'événement personnalisé, voir ci-dessous), la liste de él
```suggestion
| string | accepted_elements           | Élément Centreon géré par ce connecteur (pour en ajouter, vous devez regarder la section des format d'événement personnalisé, voir ci-dessous), la liste de éléments à séparer par des virgules sans espaces | host_status,service_status                          | host_status ou service_status ou ba_status |
```

2025-02-12 13:17 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | default_priority            |
```suggestion
| string | default_priority            |  Priorité par défaut utilisée pour le ticket Opsgenie                                                                                                                                                                                                            |                                                     |                                     |
```

2025-02-12 13:31 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +Sauvegardez votre coniguration ainsi que votre **API Key** qui est obligatoire pour l'envoi
```suggestion
Sauvegardez votre configuration ainsi que votre **API Key** qui est obligatoire pour l'envoi 
```

2025-02-12 13:37 UTC, lucie-dubrunfaut commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | default_priority            |
```suggestion
| string | default_priority            |  Default priority use for Opsgenie ticket                                                                                                                                                                                 |                                                     |                                     |
```

2025-02-12 13:37 UTC, lucie-dubrunfaut commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | accepted_elements           | Centreon item managed by this connector (to add more, you need to look at the custom event format section, see below), the list of items to be separated by co
```suggestion
| string | accepted_elements           | Centreon item managed by this connector (to add more, you need to look at the custom event format section, see below), the list of items to be separated by commas without spaces | host_status,service_status                          | host_status or service_status or ba_status |
```

2025-02-18 14:15 UTC, cg-tw requested changes

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +Cette intégration doit avoir les droits **Create and Update Access**. la seconde clé est une clé
```suggestion
Cette intégration doit avoir les droits **Create and Update Access**. La seconde clé est une clé 
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +## Configuration de Opsgenie
```suggestion
## Configuration d'Opsgenie 
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
>  * Un alias est généré pour chaque alerte afin de profiter de la déduplication d'Opsgenie
```suggestion
* Un alias est généré pour chaque alerte afin de profiter de la déduplication d'Opsgenie.
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
>  * A chaque fois que le statut d'un service, hôte ou BA est contrôlé, l'évènement passe par Centreon Broker qui utilise le Stream Connector pour envoyer ce changement d'état.
```suggestion

* À chaque fois que le statut d'un service, hôte ou BA est contrôlé, l'évènement passe par Centreon Broker qui utilise le Stream Connector pour envoyer ce changement d'état à Opsgenie.
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +### Opsgenie intégration : alerts
```suggestion
### Intégration Opsgenie : alerts
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +1. Depuis le menu **Setting**, selectionnez **Integration list**
```suggestion
1. Depuis le menu **Settings**, sélectionnez **Integration list**
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +2. Dans la liste des intégrations, ajoutez l'intégraiton **API** (Rest API HTTPS over JSON)
```suggestion
2. Dans la liste des intégrations, ajoutez l'intégration **API** (Rest API HTTPS over JSON)
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +d'alertes depuis Centreon vers Opsgenie. Cette **API Key** est référrée en tant
référée en tant que???

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +### Opsgenie intégration : incidents
```suggestion
### Intégration Opsgenie : incidents
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +1. Avant de commencer, cette intégration ne marchera que si vous utilisez le module Centreon BAM
```suggestion
1. Avant de commencer, cette intégration ne marchera que si vous utilisez le module Centreon BAM.
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +2. Depuis le menu **Settings**, allez dans la sous catégorie **APP SETTINGS** pour y trouver le menu **API key management**
```suggestion
2. Depuis le menu **Settings**, allez dans la sous-catégorie **APP SETTINGS** pour y trouver le menu **API key management**.
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +3. Dans le menu **API key management** ajoutez une nouvelle **API key** avec les droits **Create and Update**
```suggestion
3. Dans le menu **API key management** ajoutez une nouvelle **API key** avec les droits **Create and Update**.
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +Centreon vers Opsgenie. Cette **API key** est référrée en tant qu'**app_api_token** dans le configuration Centreon.
référée???

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +8. [Déployez la configuration](https://docs.centreon.com/fr/docs/monitoring/monitoring-servers/deploying-a-configuration/).
```suggestion
8. [Déployez la configuration](/docs/monitoring/monitoring-servers/deploying-a-configuration). 
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | accepted_elements           | Élément Centreon géré par ce connecteur (pour en ajouter, vous devez regarder la section des format d'événement personnalisé, voir ci-dessous), la liste de él
```suggestion
| string | accepted_elements           | Élément Centreon géré par ce connecteur (pour en ajouter, vous devez regarder la section des formats d'événements personnalisés, voir ci-dessous), la liste de éléments à séparer par des virgules sans espaces | host_status,service_status                          | host_status ou service_status ou ba_status |
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| number | enable_incident_tags        | Ajoute les tags pour les incidents si est à ` 1`
```suggestion
| number | enable_incident_tags        | Ajoute les tags pour les incidents si la valeur est ` 1`                                                                                                                                                             | 1                                                   | 1 ou 0                              |
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
>  > Warning, this documentation was written in February 2021, it is possible that certain elements described below became obsoletes due to changes on Opsgenie.
```suggestion
> Warning: this documentation was written in February 2021. It is possible that some elements described below have become obsolete due to changes to Opsgenie.
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +You can let us know by using the documentation feedback tools at the bottom right of this page.
```suggestion
> You can let us know by using the documentation feedback tools at the bottom right of this page.
```

2025-02-18 14:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +Vous pouvez nous le signaler en utilisant les outils de feedback de documentation en bas à droite de cette page.
```suggestion
> Vous pouvez nous le signaler en utilisant les outils de feedback de documentation en bas à droite de cette page.
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +requires two different API key. The first one is an integration API key coming from the **Rest API HTTPS over JSON**
```suggestion
requires two different API keys. The first one is an integration API key coming from the **Rest API HTTPS over JSON**
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +integration. This integration must have the **Create and Update Access**. The second access is an
```suggestion
integration. This integration must have the **Create and Update Access** right. The second key is an 
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +1. From the **Settings** menu, select **Integration list**.
```suggestion
1. In the **Settings** menu, select **Integration list**.
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +2. In the integration list, add an **API** integration (Rest API HTTPS over JSON).
```suggestion
2. In the integration list, add an **API** integration (**Rest API HTTPS over JSON**).
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +3. Head over the **Configured integrations** menu and edit your **API** integration to enable
```suggestion
3. Go to **Configured integrations** and edit your **API** integration to enable 
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +it if it is not. You also must to give it a **Create and Update Access**. Save your configuration
```suggestion
it (if it is not enabled already). You also must give it a **Create and Update Access** right. Save your configuration 
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +is referred as **integration_api_token** in the Centreon configuration.
```suggestion
is referred to as **integration_api_token** in the Centreon configuration.
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +1. Before starting, this integration will only work if you are using the Centreon BAM module.
```suggestion
1. Before starting, be aware that this integration will only work if you are using the Centreon BAM module.
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +2. From the **Settings** menu, select **API key management** in the subcategory **APP SETTINGS**.
```suggestion
2. In the **Settings** menu, select **API key management** in the **APP SETTINGS** subcategory.
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +3. In the **API key management** menu, add a new API key with **Create and Update** access
```suggestion
3. In the **API key management** menu, add a new API key with **Create and Update** access.
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +to Opsgenie. This **API key** is referred as **app_api_token** in the Centreon configuration.
```suggestion
to Opsgenie. This **API key** is referred to as **app_api_token** in the Centreon configuration.
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +5. To enable Centreon to connect to your Opsgenie equipment, fill in the following
```suggestion
5. To enable Centreon to connect to your Opsgenie device, fill in the following 
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | integration_api_token | Clé d'authentification à l'API pour les incidents (nécessite le module Centreon BAM) | `an_authkey`     |
FR in EN

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| number | log_level | Niveau de verbosité des logs : de 1 (erreurs) à 3 (debug) | 1                                                  |
FR in EN

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +, that allow you to filter the data you will send to your Opsgenie equipment, to reformat
```suggestion
, that allow you to filter the data you will send to your Opsgenie device, to reformat 
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | accepted_elements           | Centreon item managed by this connector (to add more, you need to look at the custom event format section, see below), the list of items to be separated by co
```suggestion
| string | accepted_elements           | Centreon item managed by this connector (to add more, you need to look at the custom event format section, see below), the list of items must be separated by commas without spaces | host_status,service_status                          | host_status or service_status or ba_status |
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | ba_incident_tags            | List of tags for an incident. Must use comma as separator. BV names will be automatically added to the tags
```suggestion
| string | ba_incident_tags            | List of tags for an incident. Must use a comma as a separator. BV names will be automatically added to the tags                                                                       | centreon,application                                | -                                   |
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | default_priority            |  Default priority use for Opsgenie ticket
```suggestion
| string | default_priority            |  Default priority used for Opsgenie tickets                                                                                                                                                                                 |                                                     |                                     |
```

2025-02-18 14:15 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +This stream connector is compatible with event bulking. Meaning that it is able to send more that one event in each call to the EOpsgenie REST API.
```suggestion
This stream connector is compatible with event bulking. Meaning that it is able to send more that one event in each call to the Opsgenie REST API.
```

2025-02-19 09:15 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +d'alertes depuis Centreon vers Opsgenie. Cette **API Key** est référrée en tant
```suggestion
d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champs
```

2025-02-19 09:15 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +qu'**integration_api_token** dans la configuration Centreon
```suggestion
 **integration_api_token** dans la configuration Centreon
```

2025-02-19 09:16 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +Centreon vers Opsgenie. Cette **API key** est référrée en tant qu'**app_api_token** dans le configuration Centreon.
```suggestion
4. Sauvegardez votre configuration et votre **Api key** qui est obligatoire pour envoyer des incidents depuis 
Centreon vers Opsgenie. Cette **API key** correspond au champs **app_api_token** dans le configuration Centreon.
```

2025-02-19 09:23 UTC, lucie-tirand commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| string | integration_api_token | Clé d'authentification à l'API pour les incidents (nécessite le module Centreon BAM) | `an_authkey`     |
```suggestion
| string | app_api_token         | API Authentication key for alerts                                       | `an_authkey`     |
| string | integration_api_token | API Authentication key for incidents (require Centreon BAM module) | `an_authkey`     |
```

2025-02-19 09:24 UTC, lucie-dubrunfaut commented on versioned_docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +| number | log_level | Niveau de verbosité des logs : de 1 (erreurs) à 3 (debug) | 1                                                  |
```suggestion
| string | logfile   | File in which logs are written                  | /var/log/centreon-broker/opsgenie-events-apiv2.log |
| number | log_level | Logging level from 1 (errors) to 3 (debug) | 1                                                  |
```

2025-02-19 09:28 UTC, cg-tw approved these changes

2025-02-19 09:57 UTC, cg-tw requested changes

2025-02-19 09:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champs
```suggestion
d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champ
```

2025-02-19 09:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md
> +Centreon vers Opsgenie. Cette **API key** correspond au champs **app_api_token** dans le configuration Centreon.
```suggestion
Centreon vers Opsgenie. Cette **API key** correspond au champ **app_api_token** dans la configuration Centreon.
```

2025-02-19 09:57 UTC, cg-tw approved these changes, later dismissed

2025-02-19 12:27 UTC, cg-tw requested changes

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/event-management/sc-opsgenie.md
> +d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champs
```suggestion
d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champ
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/event-management/sc-opsgenie.md
> +Centreon vers Opsgenie. Cette **API key** correspond au champs **app_api_token** dans le configuration Centreon.
```suggestion
Centreon vers Opsgenie. Cette **API key** correspond au champ **app_api_token** dans le configuration Centreon.
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/event-management/sc-opsgenie.md
> +d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champs
```suggestion
d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champ
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/event-management/sc-opsgenie.md
> +Centreon vers Opsgenie. Cette **API key** correspond au champs **app_api_token** dans le configuration Centreon.
```suggestion
Centreon vers Opsgenie. Cette **API key** correspond au champ **app_api_token** dans le configuration Centreon.
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/event-management/sc-opsgenie.md
> +d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champs
```suggestion
d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champ
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/event-management/sc-opsgenie.md
> +Centreon vers Opsgenie. Cette **API key** correspond au champs **app_api_token** dans le configuration Centreon.
```suggestion
Centreon vers Opsgenie. Cette **API key** correspond au champ **app_api_token** dans le configuration Centreon.
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/event-management/sc-opsgenie.md
> +d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champs
```suggestion
d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champ
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/event-management/sc-opsgenie.md
> +Centreon vers Opsgenie. Cette **API key** correspond au champs **app_api_token** dans le configuration Centreon.
```suggestion
Centreon vers Opsgenie. Cette **API key** correspond au champ **app_api_token** dans le configuration Centreon.
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/integrations/event-management/sc-opsgenie.md
> +d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champs
```suggestion
d'alertes depuis Centreon vers Opsgenie. Cette **API Key** correspond au champ
```

2025-02-19 12:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/integrations/event-management/sc-opsgenie.md
> +Centreon vers Opsgenie. Cette **API key** correspond au champs **app_api_token** dans le configuration Centreon.
```suggestion
Centreon vers Opsgenie. Cette **API key** correspond au champ **app_api_token** dans le configuration Centreon.
```

2025-02-19 12:29 UTC, cg-tw approved these changes

2025-02-26 09:15 UTC, merged