CTOR-989 : Refresh network-h3c-snmp
centreon/centreon-documentation pull request #3702
Opened 2024-10-22 15:34 UTC by lucie-dubrunfaut

## Description

Refresh network-h3c-snmp

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-05 13:56 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +| temp_<instance>   | C     |
```suggestion
| count_component | count |
| temp_instance   | C     |
```

2024-11-18 12:24 UTC, cg-tw requested changes

2024-11-18 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-11-18 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +| Traffic-Generic-Id   | Net-H3C-Traffic-Generic-Id-SNMP-custom   | Contrôle le traffic réseau d'une interface réseau         |            |
```suggestion
| Traffic-Generic-Id   | Net-H3C-Traffic-Generic-Id-SNMP-custom   | Contrôle le trafic réseau d'une interface réseau         |            |
```

2024-11-18 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +| Traffic-Generic-Name | Net-H3C-Traffic-Generic-Name-SNMP-custom | Contrôle le traffic réseau d'une interface réseau         |            |
```suggestion
| Traffic-Generic-Name | Net-H3C-Traffic-Generic-Name-SNMP-custom | Contrôle le trafic réseau d'une interface réseau         |            |
```

2024-11-18 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +| Traffic-Global       | Net-H3C-Traffic-Global-SNMP-custom       | Contrôle le traffic réseau de plusieurs interfaces réseau | X          |
```suggestion
| Traffic-Global       | Net-H3C-Traffic-Global-SNMP-custom       | Contrôle le trafic réseau de plusieurs interfaces réseau | X          |
```

2024-11-18 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +> A appliquer aux modèles de services suivants : Traffic-Generic-Id, Traffic-Generic-Name, Traffic-Global
```suggestion
> S'applique aux modèles de services suivants : Traffic-Generic-Id, Traffic-Generic-Name, Traffic-Global
```

2024-11-18 12:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +| Cpu             | Net-H3C-Cpu-SNMP-custom             | Check the rate of utilization of CPU for the machine |
```suggestion
| Cpu             | Net-H3C-Cpu-SNMP-custom             | Check the rate of CPU utilization for the machine |
```

2024-11-18 12:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +| Memory          | Net-H3C-Memory-SNMP-custom          | Check the rate of the utilization of memories        |
```suggestion
| Memory          | Net-H3C-Memory-SNMP-custom          | Check the rate of memory utilization        |
```

2024-11-18 12:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +| Traffic-Generic-Id   | Net-H3C-Traffic-Generic-Id-SNMP-custom   | Check traffic of an network interface        |            |
```suggestion
| Traffic-Generic-Id   | Net-H3C-Traffic-Generic-Id-SNMP-custom   | Check traffic of a network interface        |            |
```

2024-11-18 12:24 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-h3c-snmp.md
> +| Traffic-Generic-Name | Net-H3C-Traffic-Generic-Name-SNMP-custom | Check traffic of an network interface        |            |
```suggestion
| Traffic-Generic-Name | Net-H3C-Traffic-Generic-Name-SNMP-custom | Check traffic of a network interface        |            |
```

2024-11-19 13:16 UTC, merged