doc(release) Release notes 24.10.0 Modules
centreon/centreon-documentation pull request #3720
Opened 2024-10-28 08:48 UTC by pkippes

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-10-28 13:43 UTC, cg-tw requested changes

2024-10-28 13:43 UTC, cg-tw commented on versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- [MBI] Improved the starting of CBIS by using systemd configuration.
```suggestion
- [MBI] The CBIS service is now started using systemd's configuration.
```

2024-10-28 13:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- [MBI] Improved the starting of CBIS by using systemd configuration.
```suggestion
- [MBI] The CBIS service is now started using systemd's configuration.
```

2024-10-28 14:14 UTC, cg-tw requested changes

2024-10-28 14:14 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- [Server] Fixed Servicegroup status when configured using Service Templates or Hostgroup Services.
```suggestion
- [Server] When using Service Templates or Hostgroup Services, the status of Service groups is now displayed correctly.
```

2024-10-28 14:40 UTC, cg-tw commented on versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +Read more about version 24.10 in our [blog post](https://www.centreon.com/en/blog/centreon-fall24-whats-new-in-the-24-10-software-version/).
```suggestion
Read more about version 24.10 in our [blog post](https://www.centreon.com/centreon-announces-its-latest-software-release-centreon-24-10/).
```

2024-10-28 16:55 UTC, cg-tw requested changes

2024-10-28 16:55 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- Redesigned the edit modal.
```suggestion
- Redesigned the edit window.
```

2024-10-28 16:57 UTC, cg-tw requested changes

2024-10-28 16:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +</details>
```suggestion

</details>
```

2024-10-28 16:57 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
>  <details open>
```suggestion

<details open>
```

2024-10-28 16:59 UTC, cg-tw requested changes

2024-10-28 16:59 UTC, cg-tw commented on versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +</details>
```suggestion

</details>
```

2024-10-29 11:35 UTC, rsadik-ext submitted a review, later dismissed

2024-10-30 09:30 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- **MAP Legacy is no longer available.**
```suggestion
> **MAP Legacy is no longer available.**
```

2024-10-30 09:30 UTC, cg-tw commented on versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- **MAP Legacy is no longer available.**
```suggestion
> **MAP Legacy is no longer available.**
```

2024-10-30 10:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +Playlists of Dashboards
```suggestion
**Dashboard playlists**
```

2024-10-30 10:07 UTC, cg-tw commented on versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- [Dashboards] A new PATCH endpoint has been added for updating playlists.
```suggestion
**Dashboard playlists**
- Added unauthenticated playlists for TV projection.
- A new PATCH endpoint has been added for updating playlists.
```

2024-10-30 13:49 UTC, cg-tw commented on versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- Added the handling of Business Activities and Business Views in the Status Grid widget.
```suggestion
- Business Activities and Business Views can now be displayed in the Status Grid widget.
```

2024-10-30 13:49 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
> +- Added the handling of Business Activities and Business Views in the Status Grid widget.
```suggestion
- Business Activities and Business Views can now be displayed in the Status Grid widget.
```

2024-10-30 13:52 UTC, cg-tw approved these changes

2024-10-30 13:53 UTC, rbignotticentreon reviewed
Parties MAP et DASHBOARDS => OK

2024-10-30 14:00 UTC, rbignotticentreon approved these changes
Parties MAP et DASHBOARDS => OK

2024-10-30 14:10 UTC, rsadik-ext approved these changes

2024-10-31 15:41 UTC, merged