Rework the SSH key exchange section in applications-monitoring-centreon-central
centreon/centreon-documentation pull request #3722
Opened 2024-10-28 15:37 UTC by lucie-dubrunfaut

## Description

Rework the SSH key exchange section in applications-monitoring-centreon-central

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-31 09:16 UTC, cg-tw requested changes

2024-10-31 09:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +Les vérifications liées au service **Broker-Stats** devraient être effectuées depuis un collecteur et sont réalisées par SSH.
```suggestion
Les contrôles liés au service **Broker-Stats** devraient être effectués depuis un collecteur et sont réalisés par SSH. 
```

2024-10-31 09:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +Si vous ne disposez que d'un central, les vérifications seront faites depuis et sur le central lui-même.
```suggestion
Si vous ne disposez que d'un central, les contrôles seront faits depuis et sur le central lui-même. 
```

2024-10-31 09:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +> NB : Il est très fortement recommandé de surveiller le cluster à partir d'un poller plutôt qu'à partir du cluster.
```suggestion
> NB : Il est très fortement recommandé de superviser le central à partir d'un collecteur plutôt qu'à partir du central.
```

2024-10-31 09:16 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +L'utilisateur `centreon-engine` du poller est alors capable d'ouvrir une session SSH sur les deux nœuds centraux.
on n'a pas de cluster là

2024-10-31 09:17 UTC, cg-tw requested changes

2024-10-31 09:17 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +The checks related to **Broker-Stats** service should be done from a poller and it is done through SSH.
```suggestion
The checks related to the **Broker-Stats** service should be done from a poller and are done through SSH. 
```

2024-10-31 09:17 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +You can skip below steps for SSH key exchange if the central server monitors itself.
```suggestion
You can skip the steps below for SSH key exchange if the central server monitors itself.
```

2024-10-31 09:17 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +The `centreon-engine` user is now able to log in *via* SSH to both central nodes.
no cluster

2024-10-31 15:54 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +* chaque nœud de ce cluster
```suggestion
```

2024-10-31 15:55 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +Ouvrir une session en ligne de commande sur :
```suggestion
Ouvrir une session en ligne de commande et lancer cette commande :
```

2024-10-31 15:55 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +Une fois ces sessions ouvertes, lancer cette commande :
```suggestion
```

2024-10-31 16:00 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +Ouvrir une session en ligne de commande et lancer cette commande :
```suggestion
Ouvrir une session en ligne de commande sur :
- le poller qui sera chargé de superviser le central
- le central

Une fois ces sessions ouvertes, lancer cette commande :
```

2024-10-31 16:00 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +- le central
```suggestion
* le poller qui sera chargé de superviser le central
* le central
```

2024-10-31 16:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +
```suggestion
```

2024-10-31 16:02 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +Après avoir lancé cette commande, copier le contenu du fichier qui s'est affiché sous la commande `cat` et le coller à la fin du fichier (probablement à créer) `~/.ssh/authorized_keys` des nœuds cent
```suggestion
Après avoir lancé cette commande, copier le contenu du fichier qui s'est affiché sous la commande `cat` et le coller à la fin du fichier (probablement à créer) `~/.ssh/authorized_keys` du central, puis appliquer les bons droits sur le fichier (toujours en tant que `centreon-engine`) :
```

2024-10-31 16:03 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +Une fois cette étape effectuée sur chaque nœud central, il ne reste plus qu'à initialiser une première connexion depuis le poller vers chacun des nœuds :
```suggestion
Une fois cette étape effectuée sur le central, il ne reste plus qu'à initialiser une première connexion depuis le poller vers celui-ci :
```

2024-10-31 16:03 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +ssh <cluster-node-ip-address>
```suggestion
ssh <central-ip-address>
```

2024-10-31 16:03 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +L'utilisateur `centreon-engine` du poller est alors capable d'ouvrir une session SSH sur les deux nœuds centraux.
```suggestion
L'utilisateur `centreon-engine` du poller est alors capable d'ouvrir une session SSH sur le central. 
```

2024-11-12 13:15 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
> +> NB : It is strongly recommended to monitor the central from an external poller rather than from the central itself.
```suggestion
> NB : It is strongly recommended to monitor the central from an external poller rather than from the central server itself.
```

2024-11-12 13:21 UTC, cg-tw approved these changes

2024-11-12 13:35 UTC, merged