CTOR-1049 : Refresh cloud-aws-apigateway
centreon/centreon-documentation pull request #3724
Opened 2024-10-30 15:11 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-apigateway

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-31 08:05 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
> +| Amazon AWS API Gateway | Discover Amazon AWS API Gateway instances |
```suggestion
| Amazon AWS API Gateway | Découvre les instances Amazon AWS API Gateway |
```

2024-10-31 09:03 UTC, cg-tw requested changes

2024-11-05 14:29 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
> +	--aws-access-key='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
```

2024-11-05 14:29 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
> +	--aws-access-key='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
```

2024-11-05 14:36 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
> +| AWSACCESSKEY  | Set AWS access key                                                                                                         |                   |             |
```suggestion
| APINAME       | Set the api name (required) (can be defined multiple times)                                                                |                   | X           |
| AWSACCESSKEY  | Set AWS access key                                                                                                         |                   | X           |
```

2024-11-05 14:36 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                         |                   |             |
```suggestion
| AWSSECRETKEY  | Set AWS secret key                                                                                                         |                   | X           |
```

2024-11-05 14:37 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
> +	--api-name='' \
```suggestion
	--api-name='XXXX' \
```

2024-11-05 14:37 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                                       |                   |             |
```suggestion
| APINAME       | Set the api name (required) (can be defined multiple times)                                                                              |                   | X           |
| AWSACCESSKEY  | Set AWS access key                                                                                                                       |                   | X           |
| AWSASSUMEROLE | Set Amazon Resource Name of the role to be assumed                                                                                       |                   |             |
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option               | awscli            |             |
| AWSREGION     | Set the region name (required)                                                                                                           | us-east-1         | X           |
| AWSSECRETKEY  | Set AWS secret key                                                                                                                       |                   | X           |
```

2024-11-05 14:38 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
> +	--api-name='' \
```suggestion
	--api-name='XXXX' \
```

2024-11-05 14:38 UTC, cg-tw approved these changes

2024-11-05 15:25 UTC, merged