CTOR-1050 : Refresh cloud-aws-backup
centreon/centreon-documentation pull request #3725
Opened 2024-10-31 08:00 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-backup

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-31 08:51 UTC, cg-tw requested changes

2024-10-31 08:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-backup.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-31 08:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-backup.md
> +| Amazon Web Service Backup Vault | Discover AWS Backup Vault |
```suggestion
| Amazon Web Service Backup Vault | Discover AWS Backup Vaults |
```

2024-10-31 15:02 UTC, cg-tw requested changes

2024-10-31 15:02 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-backup.md
> +	--aws-access-key='' \
?

2024-10-31 15:02 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-backup.md
> +	--aws-access-key='' \
?

2024-11-05 14:45 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-backup.md
> +| AWSSECRETKEY    | Set AWS secret key                                                                                                                                 |                   |
```suggestion
| AWSACCESSKEY    | Set AWS access key                                                                                                                                 |                   | X           |
| AWSASSUMEROLE   | Set Amazon Resource Name of the role to be assumed                                                                                                 |                   |             |
| AWSCUSTOMMODE   | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option                         | awscli            |             |
| AWSREGION       | Set the region name (required)                                                                                                                     |                   | X           |
| AWSSECRETKEY    | Set AWS secret key                                                                                                                                 |                   | X           |
```

2024-11-05 14:46 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-backup.md
> +	--aws-access-key='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
```

2024-11-05 14:46 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-backup.md
> +| AWSSECRETKEY    | Set AWS secret key                                                                                                                       |                   |             |
```suggestion
| AWSACCESSKEY    | Set AWS access key                                                                                                                       |                   | X           |
| AWSASSUMEROLE   | Set Amazon Resource Name of the role to be assumed                                                                                       |                   |             |
| AWSCUSTOMMODE   | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option               | awscli            |             |
| AWSREGION       | Set the region name (required)                                                                                                           |                   | X           |
| AWSSECRETKEY    | Set AWS secret key                                                                                                                       |                   | X           |
```

2024-11-05 14:47 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-backup.md
> +	--aws-access-key='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
```

2024-11-05 14:47 UTC, cg-tw approved these changes

2024-11-05 15:26 UTC, merged