CTOR-1051 : Refresh cloud-aws-cloudfront
centreon/centreon-documentation pull request #3726
Opened 2024-10-31 08:13 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-cloudfront

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-31 08:46 UTC, cg-tw requested changes

2024-10-31 08:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-31 08:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
>  ### Dépendances du Plugin
```suggestion
### Dépendances du plugin
```

2024-10-31 08:46 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +
```suggestion
```

2024-10-31 08:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +| Cloudfront-Errors     | Cloud-Aws-Cloudfront-Errors-Api-custom     | Check pages access errors             |
```suggestion
| Cloudfront-Errors     | Cloud-Aws-Cloudfront-Errors-Api-custom     | Check page access errors             |
```

2024-10-31 08:46 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +| Cloudfront-Requests   | Cloud-Aws-Cloudfront-Requests-Api-custom   | Check requests number                 |
```suggestion
| Cloudfront-Requests   | Cloud-Aws-Cloudfront-Requests-Api-custom   | Check the number of requests                 |
```

2024-10-31 15:03 UTC, cg-tw requested changes

2024-10-31 15:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +	--aws-access-key='' \
?

2024-10-31 15:03 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +	--id='' \
?

2024-11-05 14:39 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                                                 |                   |
```suggestion
| AWSACCESSKEY  | Set AWS access key                                                                                                                                 |                   | X           |
| AWSASSUMEROLE | Set Amazon Resource Name of the role to be assumed                                                                                                 |                   |             |
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option                         | paws              |             |
| AWSINSTANCEID | Set the instance ID (required) (can be defined multiple times)                                                                                     |                   | X           |
| AWSREGION     | Set the region name (required)                                                                                                                     |                   | X           |
| AWSSECRETKEY  | Set AWS secret key                                                                                                                                 |                   | X           |
```

2024-11-05 14:39 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +	--aws-access-key='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
```

2024-11-05 14:39 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +	--id='' \
```suggestion
	--id='XXXX' \
```

2024-11-05 14:40 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                                       |                   |             |
```suggestion
| AWSACCESSKEY  | Set AWS access key                                                                                                                       |                   | X           |
| AWSASSUMEROLE | Set Amazon Resource Name of the role to be assumed                                                                                       |                   |             |
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option               | paws              |             |
| AWSINSTANCEID | Set the instance ID (required) (can be defined multiple times)                                                                           |                   | X           |
| AWSREGION     | Set the region name (required)                                                                                                           |                   | X           |
| AWSSECRETKEY  | Set AWS secret key                                                                                                                       |                   | X           |
```

2024-11-05 14:40 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
> +	--id='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--region='' \
	--id='XXXX' \
```

2024-11-05 14:45 UTC, cg-tw approved these changes

2024-11-05 15:25 UTC, merged