CTOR-1052 : Refresh cloud-aws-cloudwatch
centreon/centreon-documentation pull request #3727
Opened 2024-10-31 09:37 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-cloudwatch

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-31 14:51 UTC, cg-tw requested changes

2024-10-31 14:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-31 14:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +Configurez un compte de service (via une combinaison d'access et secret key) et affectez-lui les privilèges suivants :
```suggestion
Configurez un compte de service (via une combinaison d'access key et secret key) et affectez-lui les privilèges suivants :
```

2024-10-31 14:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +### Dépendances du Plugin
```suggestion
### Dépendances du plugin
```

2024-10-31 14:51 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +| AWSSECRETKEY | Set AWS secret key |                   |             |
not mandatory?

2024-10-31 14:51 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +| AWSSECRETKEY | Set AWS secret key |                   |             |
not mandatory?

2024-10-31 15:04 UTC, cg-tw requested changes

2024-10-31 15:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +	--region='' \
?

2024-10-31 15:04 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +	--aws-access-key='' \
?

2024-11-05 15:36 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +| AWSSECRETKEY | Set AWS secret key |                   |             |
```suggestion
| AWSACCESSKEY | Set AWS access key |                   | X           |
| AWSSECRETKEY | Set AWS secret key |                   | X           |
```

2024-11-05 15:37 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +	--aws-access-key='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
```

2024-11-05 15:39 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +| AWSSECRETKEY | Set AWS secret key |                   |             |
```suggestion
| AWSACCESSKEY | Set AWS access key |                   | X           |
| AWSSECRETKEY | Set AWS secret key |                   | X           |
```

2024-11-05 15:40 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +	--region='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--proxyurl=''  \
	--region='eu-west-1' \
```

2024-11-05 15:46 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +| metric | N/A   |
```suggestion
```

2024-11-05 15:46 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
> +| metric | N/A   |
```suggestion
```

2024-11-12 13:23 UTC, cg-tw approved these changes

2024-11-12 13:24 UTC, merged