CTOR-1053 : Refresh cloud-aws-cloudwatchlogs
centreon/centreon-documentation pull request #3728
Opened 2024-10-31 11:06 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-cloudwatchlogs

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-31 13:26 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +## Dépendances du Connecteur de supervision
```suggestion

CloudWatch Logs vous permet de centraliser les journaux de tous vos systèmes ainsi que les applications et les services AWSque vous utilisez au sein d’un seul service hautement évolutif. Vous pouvez ensuite facilement les consulter, y effectuer des recherches pour identifier des codes d’erreur spécifiques ou des modèles, les filtrer en fonction de champs spécifiques ou les archiver en toute sécurité à des fins d’analyse ultérieure.

> **Attention** Ce Plugin est susceptible de générer un volume importants de données lors des requêtes API.
> Il est indispensable d'utiliser les fonctionnalités de filtrage de celui-ci (```--group-name``` and ```--stream-name```) afin
> de limiter les résultats retournés par l'API.

## Dépendances du Connecteur de supervision
```

2024-10-31 13:27 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +CloudWatch Logs vous permet de centraliser les journaux de tous vos systèmes ainsi que les applications et les services AWSque vous utilisez au sein d’un seul service hautement évolutif. Vous pouvez
```suggestion
CloudWatch Logs vous permet de centraliser les journaux de tous vos systèmes ainsi que les 
applications et les services AWSque vous utilisez au sein d’un seul service hautement évolutif. 
Vous pouvez ensuite facilement les consulter, y effectuer des recherches pour identifier des 
codes d’erreur spécifiques ou des modèles, les filtrer en fonction de champs spécifiques ou 
les archiver en toute sécurité à des fins d’analyse ultérieure.
```

2024-10-31 14:59 UTC, cg-tw requested changes

2024-10-31 14:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
>  applications et les services AWSque vous utilisez au sein d’un seul service hautement évolutif.
```suggestion
applications et les services AWS que vous utilisez au sein d’un seul service hautement évolutif. 
```

2024-10-31 14:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-31 14:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +Configurez un compte de service (via une combinaison d'access et secret key) et affectez-lui les privilèges suivants :
```suggestion
Configurez un compte de service (via une combinaison d'access key et secret key) et affectez-lui les privilèges suivants :
```

2024-10-31 14:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
>  > This Plugin may generate very huge queries toward CloudWatch Logs API. Make sure to use filtering capability
```suggestion
> This plugin may generate very huge queries toward the CloudWatch Logs API. Make sure you use the plugin's filtering capabilities
```

2024-10-31 14:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
>  > with ```--group-name``` and ```--stream-name``` options.
```suggestion
> using the```--group-name``` and ```--stream-name``` options. 
```

2024-10-31 14:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +There is no service template linked to this host template.
```suggestion
No service template is linked to this host template.
```

2024-10-31 14:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +	--verbose
the previous example was better

2024-10-31 14:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +	--verbose
same as EN

2024-10-31 15:05 UTC, cg-tw requested changes

2024-10-31 15:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +	--stream-name='' \
?

2024-11-05 15:47 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                         |                   |             |
```suggestion
| AWSACCESSKEY  | Set AWS access key                                                                                                         |                   | X           |
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option | awscli            |             |
| AWSREGION     | Set the region name (required)                                                                                             |                   | X           |
| AWSSECRETKEY  | Set AWS secret key                                                                                                         |                   | X           |
```

2024-11-05 15:48 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +	--region='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--proxyurl=''  \
	--region='eu-west-1' \
```

2024-11-05 15:49 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +	--region='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--proxyurl=''  \
	--region='eu-west-1' \
```

2024-11-05 15:49 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                         |                   |             |
```suggestion
| AWSACCESSKEY  | Set AWS access key                                                                                                         |                   | X           |
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option | awscli            |             |
| AWSREGION     | Set the region name (required)                                                                                             |                   | X           |
| AWSSECRETKEY  | Set AWS secret key                                                                                                         |                   | X           |
```

2024-11-12 13:24 UTC, cg-tw approved these changes

2024-11-12 13:24 UTC, merged