CTOR-1054 : Refresh cloud-aws-directconnect
centreon/centreon-documentation pull request #3729
Opened 2024-10-31 11:12 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-directconnect

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-31 15:10 UTC, cg-tw requested changes

2024-10-31 15:10 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-directconnect.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-31 15:10 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-directconnect.md
> +Configurez un compte de service (via une combinaison d'access et secret key) et affectez-lui les privilèges suivants :
```suggestion
Configurez un compte de service (via une combinaison d'access key et secret key) et affectez-lui les privilèges suivants :
```

2024-10-31 15:10 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-directconnect.md
> +	--region='' \
?

2024-10-31 15:10 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-directconnect.md
> +	--proxyurl=''  \
?

2024-11-05 15:51 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-directconnect.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                                                 |                   |
```suggestion
| AWSACCESSKEY  | Set AWS access key                                                                                                                                 |                   | X           |
| AWSASSUMEROLE | Set Amazon Resource Name of the role to be assumed                                                                                                 |                   |             |
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option                         | awscli            |             |
| AWSREGION     | Set the region name (required)                                                                                                                     |                   | X           |
| AWSSECRETKEY  | Set AWS secret key                                                                                                                                 |                   | X           |
```

2024-11-05 15:52 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-directconnect.md
> +	--aws-access-key='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
```

2024-11-05 15:52 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-directconnect.md
> +	--region='' \
```suggestion
	--region='eu-west-1' \
```

2024-11-12 13:24 UTC, cg-tw approved these changes

2024-11-12 13:25 UTC, merged