CTOR-1055 : Refresh cloud-aws-ebs
centreon/centreon-documentation pull request #3730
Opened 2024-10-31 13:21 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-ebs

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-10-31 13:28 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +## Dépendances du Connecteur de supervision
```suggestion

Amazon Elastic Block Store (EBS) est un service de stockage par bloc hautes performances et simple d'utilisation conçu en vue d'une utilisation avec Amazon Elastic Compute Cloud (EC2) 
pour les charges de travail exigeantes en débit et en transactions à n'importe quelle échelle.
Des charges de travail variées, telles que des bases de données relationnelles et non relationnelles, des applications d'entreprise, des applications conteneurisées, des moteurs d'analyse Big Data, 
des systèmes de fichiers et des workflows multimédias, sont largement déployées sur Amazon EBS.

## Dépendances du Connecteur de supervision
```

2024-10-31 13:28 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +## Connector dependencies
```suggestion

Amazon Elastic Block Store (Amazon EBS) provides block level storage volumes for use with EC2 instances. 
EBS volumes behave like raw, unformatted block devices. You can mount these volumes as devices on your instances. 
You can mount multiple volumes on the same instance, and you can mount a volume to multiple instances at a time. 
You can create a file system on top of these volumes, or use them in any way you would use a block device (like a hard drive). 
You can dynamically change the configuration of a volume attached to an instance.

## Connector dependencies
```

2024-10-31 15:15 UTC, cg-tw requested changes

2024-10-31 15:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-10-31 15:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +Configurez un compte de service (via une combinaison d'access et secret key) et affectez-lui les privilèges suivants :
```suggestion
Configurez un compte de service (via une combinaison d'access key et secret key) et affectez-lui les privilèges suivants :
```

2024-10-31 15:15 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +	--volume-id='' \
?

2024-10-31 15:15 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +	--volume-id='' \
?

2024-11-05 16:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +	--region='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--region='eu-west-1' \
```

2024-11-05 16:02 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                                                 |                   |
```suggestion
| AWSACCESSKEY  | Set AWS access key                                                                                                                                 |                   | X           |
| AWSASSUMEROLE | Set Amazon Resource Name of the role to be assumed                                                                                                 |                   |             |
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option                         | awscli            |             |
| AWSREGION     | Set the region name (required)                                                                                                                     |                   | X           |
| AWSSECRETKEY  | Set AWS secret key                                                                                                                                 |                   | X           |
```

2024-11-05 16:02 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +| AWSSECRETKEY  | Set AWS secret key                                                                                                                       |                   |             |
```suggestion
| AWSACCESSKEY  | Set AWS access key                                                                                                                       |                   | X           |
| AWSASSUMEROLE | Set Amazon Resource Name of the role to be assumed                                                                                       |                   |             |
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option               | awscli            |             |
| AWSREGION     | Set the region name (required)                                                                                                           |                   | X           |
| AWSSECRETKEY  | Set AWS secret key                                                                                                                       |                   | X           |
```

2024-11-05 16:03 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-ebs.md
> +	--region='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--region='eu-west-1' \
```

2024-11-12 13:25 UTC, cg-tw approved these changes

2024-11-12 13:27 UTC, merged