translate troubleshooting-plugins.md
centreon/centreon-documentation pull request #3733
Opened 2024-10-31 15:22 UTC by emgcentreon

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-11-28 16:30 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +La raison la plus commune de cette erreur sont des droits inadaptés dans le répertoire de cache (`/var/lib/centreon/centplugins`)  ou dans le ficher cache lui-même. Cela peut ausi être dû à une insta
```suggestion
La raison la plus commune de cette erreur sont des droits inadaptés dans le répertoire de cache (`/var/lib/centreon/centplugins`)  ou dans le fichier cache lui-même. Cela peut aussi être dû à une installation inconsistante ou alors le directoire n'existe tout simplement pas.
```

2025-01-20 13:09 UTC, cg-tw requested changes

2025-01-20 13:09 UTC, cg-tw commented on pp/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +On RPM-based systems, you can use the following command to identify what is the
```suggestion
On RPM-based systems, you can use the following command to identify which package provides the missing binary: 
```

2025-01-20 13:09 UTC, cg-tw commented on pp/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +package's missing binary: `yum whatprovides "*/the_binary_name"`
```suggestion
`yum whatprovides "*/the_binary_name"`
```

2025-01-20 13:09 UTC, cg-tw commented on pp/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +When a Plugin execution looks incomplete, it usually means that there's
?

2025-01-20 13:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Généralement, une mauvaise configuration ou un dispositif tiers sont la source du problème. Cette section décrit les erreurs le plus communes que vous pourriez rencontrer et peut vous aider à identif
il manque la fin de la phrase

2025-01-20 13:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Généralement, une mauvaise configuration ou un dispositif tiers sont la source du problème. Cette section décrit les erreurs le plus communes que vous pourriez rencontrer et peut vous aider à identif
```suggestion
Généralement, une mauvaise configuration ou un dispositif tiers sont la source du problème. Cette section décrit les erreurs les plus communes que vous pourriez rencontrer et peut vous aider à identifier 
```

2025-01-20 13:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Mais avant tout, rappelons que la majorité des connecteurs ont leur propre documentation contenant des sections de "Prérequis" et "Configuration" pour vous aider à éviter les erreurs courantes.
```suggestion
Mais avant tout, rappelons que la majorité des connecteurs ont leur propre documentation contenant des sections "Prérequis" et "Configuration" pour vous aider à éviter les erreurs courantes.
```

2025-01-20 13:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Les pollers Centreon emploient un ordonnanceur planifier et exécuter les checks.
```suggestion
Les collecteurs Centreon emploient un ordonnanceur qui planifie et exécute les contrôles.
```

2025-01-20 13:09 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Lorsque vous utilisez des plugins et que vous deployez une nouvelle sonde de supervisions, des erreurs peuvent apparaitre.
```suggestion
Lorsque vous utilisez des plugins et que vous déployez une nouvelle sonde de supervision, des erreurs peuvent apparaître.
```

2025-01-20 15:42 UTC, cg-tw requested changes

2025-01-20 15:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Les pollers Centreon emploient un ordonnanceur planifier et exécuter les checks.
I only reviewed up to there.

2025-02-04 10:13 UTC, cg-tw requested changes

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +title: Dépannage des erreurs de plugin
```suggestion
title: Dépanner les erreurs de plugin
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* Copier/coller la commande du UI Centreon Web pour tenter dépanner le problème avec le CLI
```suggestion
* Copier/coller la commande de l'interface Centreon web pour tenter dépanner le problème en ligne de commande
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* Employez l'utilisateur Centreon-engine pour exécuter manuellement le plugin (et jamais root !)
```suggestion
* Employer l'utilisateur **centreon-engine** pour exécuter manuellement le plugin (et jamais root !)
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +### (pas de résultat renvoyé par le plugin)
```suggestion
### No output returned from plugin
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Pour cette erreur, vérifiez la ligne de commande qui a été exécutée et verifiez que le binaire qu'elle contient existe et qu'elle ne présente pas de fautes de frappe.
```suggestion
Pour cette erreur, vérifiez la ligne de commande qui a été exécutée et vérifiez que le binaire qu'elle contient existe et qu'elle ne présente pas de fautes de frappe.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Pour les systèmes basés sur RPM, vous pouvez utiliser la commande `yum whatprovides "*/the_binary_name"` pour identifier le binaire manquant du paquet.
```suggestion
Pour les systèmes basés sur RPM, vous pouvez utiliser la commande `yum whatprovides "*/the_binary_name"` pour identifier quel paquet fournit le binaire manquant.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +La raison la plus commune de cette erreur sont des droits inadaptés dans le répertoire de cache (`/var/lib/centreon/centplugins`)  ou dans le fichier cache lui-même. Cela peut aussi être dû à une ins
```suggestion
La raison la plus commune de cette erreur sont des droits incorrects dans le répertoire de cache (`/var/lib/centreon/centplugins`)  ou dans le fichier cache lui-même. Cela peut aussi être dû à une installation incohérente ou au fait que le répertoire n'existe tout simplement pas.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Vérifiez que le directoire existe bien et qu'il a les droits appropriés avec la commande stat suivante :
```suggestion
Vérifiez que le répertoire existe bien et qu'il a les droits appropriés avec la commande **stat** : 
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +`stat /var/lib/centreon/centplugins`. Vous devriez obtenir le résultat suivant :
```suggestion
`stat /var/lib/centreon/centplugins`.

Vous devriez obtenir le résultat suivant : 
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Si les droits du directoire sont corrects, vérifiez les droits du fichier de cache :
```suggestion
Si les droits du répertoire sont corrects, vérifiez les droits du fichier de cache : 
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +`stat /var/lib/centreon/centplugins/<cache_file_name>`. Le résultat devrait être :
```suggestion
`stat /var/lib/centreon/centplugins/<cache_file_name>`.

Le résultat devrait être : 
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Cette erreur signifie qu'une commande a atteint le délai d'attente établi par Centreon-engine.
```suggestion
Cette erreur signifie qu'une commande a atteint le délai d'attente défini sur le moteur de supervision.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Centreon-engine possède un délai d'attente interne qui lui permet de mettre fin à l'exécution d'un plugin lorsque celle-ci dépasse un certain nombre de secondes. Ceci sert à éviter l'exécution infini
```suggestion
Centreon-engine possède un délai d'attente interne qui lui permet de mettre fin à l'exécution d'un plugin lorsque celle-ci dépasse un certain nombre de secondes. Ceci sert à éviter l'exécution infinie de plugins.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +La configuration par défaut établit une attente de 60 secondes pour les **Services** et 10 secondes pour les **Hôtes**.
```suggestion
La configuration par défaut établit une attente de 60 secondes pour les services et 10 secondes pour les hôtes.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Dans certains cas, ceci peut être normal en raison de la complexité du check à effectuer ou du temps de traitement du côté de l'objet chargé de la supervision.
```suggestion
Dans certains cas, ceci peut être normal en raison de la complexité du contrôle à effectuer ou du temps de traitement du côté de l'objet chargé de la supervision.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Pour mesurer le temps nécessaire pour compléter un check, copiez/collez la ligne de commande et executez-la depuis CLI avec un utilisateur Centreon-engine
```suggestion
Pour mesurer le temps nécessaire pour effectuer un contrôle, copiez/collez la ligne de commande et exécutez-la depuis votre terminal avec l'utilisateur **centreon-engine**.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Vous pouvez modifier le délai d'attente d'engine dans le menu **Configuration > Pollers > Engine Configuration**.
```suggestion
Vous pouvez modifier le délai d'attente d'engine dans le menu **Configuration > Collecteurs > Configuration du moteur de collecte**.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Pour que vos changements soient appliqués, exportez la configuration et **redémarrez** le collecteur
```suggestion
Pour que vos changements soient appliqués, déployez la configuration pour ce collecteur avec l'option **Redémarrer**.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +### Le résultat ou metrique du check est incomplet
```suggestion
### Le résultat du contrôle ou les métriques sont incomplets
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Si l'exécution du plugin semble incomplète, c'est qu'il y a probablement un bug quelque part dans le code. Si c'est le cas, vous verrez probablement des lignes *stderr* s'afficher lorsque vous exécut
```suggestion
Si l'exécution du plugin semble incomplète, c'est qu'il y a probablement un bug quelque part dans le code. Si c'est le cas, vous verrez probablement des lignes *stderr* s'afficher lorsque vous exécuterez le contrôle en ligne de commande.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Si c'est le cas, contactez-nous sur notre [plateforme communautaire The Watch](https://thewatch.centreon.com/) ou, encore mieux, aidez-nous à traquer le problème dans notre répositoire Github [centre
```suggestion
Si c'est le cas, contactez-nous sur notre [plateforme communautaire The Watch](https://thewatch.centreon.com/) ou, encore mieux, ouvrez une *issue* dans notre dépôt GitHub [centreon-plugins](https://github.com/centreon/centreon-plugins/issues). 
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
>  ### SNMPv3 options mapping
```suggestion
### Mapping des options SNMPv3
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Pour configurer SNMPv3, Centreon vous recommande d'interroger votre appareil avec la commande "snmpwalk" et ses options. Vous pouvez ensuite utiliser le tableau suivant pour la faire marcher avec le
```suggestion
Pour configurer SNMPv3, Centreon vous recommande d'interroger votre appareil avec la commande "snmpwalk" et ses options. Vous pouvez ensuite utiliser le tableau suivant pour la faire marcher avec le plugin.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Configurez les options SNMP additionnelles dans la macro SNMPEXTRAOPTIONS dans la partie de configuration de l'hôte/modèle d'hôte.
```suggestion
Configurez les options SNMP additionnelles dans la macro SNMPEXTRAOPTIONS de l'hôte/du modèle d'hôte.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* Une mauvaise configuration de l'Agent SNMP ou de l'hôte Centreon dû à un port SNMP, une version ou une chaîne communautaire incorrecte.
```suggestion
* Une mauvaise configuration de l'Agent SNMP ou de l'hôte Centreon dû à un port SNMP, une version ou une communauté SNMP incorrecte.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* Un équipement tiers (par exemple, un firewall) qui empêche la communication entre le collecteur et l'appareil à distance.
```suggestion
* Un équipement tiers (par exemple, un firewall) qui empêche la communication entre le collecteur et l'appareil distant.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Voici une commande échantillon :
```suggestion
Voici une commande d'exemple :
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Les plugins font une requête pour un ou plusieurs OIDs au MIB de l'objet ciblé. Si le
```suggestion

Les plugins font une requête pour un ou plusieurs OIDs à la MIB de l'objet ciblé. Si le 
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Un problème fréquent est un objet qui ne renvoie pas le MIB ou l'un des OID utilisé par le plugin. C'est-à-dire, le plugin employé n'est pas adapté pour cet objet.
```suggestion
Un problème fréquent est un objet qui n'inclut pas la MIB ou l'un des OID utilisés par le plugin. En d'autres termes, le plugin employé n'est pas adapté à cet objet.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
>  ### UNKNOWN: SNMP Session: Unable to create
```suggestion
### UNKNOWN: SNMP Session: Unable to create

```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Pour inspecter le stockage d'un appareil ou d'un système, les plugins Centreon employent des OID standard. Occasionnellement, le manufactureur n'implémente qu'une partie de ces OIDs.
```suggestion
Pour contrôler le stockage d'un appareil ou d'un système, les plugins Centreon emploient des OIDs standard. Parfois, le fabricant n'implémente qu'une partie de ces OIDs.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Utilisez la commande `snmpwalk` pour vérifier quels sont les OIDs disponibles et adaptez la commande de check en conséquence.
```suggestion
Utilisez la commande `snmpwalk` pour vérifier quels sont les OIDs disponibles et adaptez la commande de contrôle en conséquence.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +La bande passante et la supervision de status sont l'exemple parfait pour ce problème : le comportement par défaut du plugin utilise l'OID `ifname` pour construire son cache, s'il ne peut pas le trou
```suggestion
La supervision de la bande passante et des statuts des interfaces sont un exemple parfait de ce problème : par défaut, le plugin utilise l'OID `ifname` pour construire son cache. S'il ne peut pas le trouver, vous obtiendrez cette erreur.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Pour les contrôles d'interface et de stockage, il est possible de demander à la sonde d'utiliser un autre OID (par exemple `--oid-filter='ifDesc' --oid-display='ifDesc'`).
```suggestion
Pour les contrôles d'interface et de stockage, des options permettent de demander à la sonde d'utiliser un autre OID (par exemple `--oid-filter='ifDesc' --oid-display='ifDesc'`).
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +### UNKNOWN: Cannot decode response (ajoutez l'option --debug pour voir le contenu reçu)
```suggestion
### UNKNOWN: Cannot decode response (add --debug option to display returned content)
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Les plugins réalisent des appels API et déchiffrent le contenu rendu par l'API pour l'utiliser comme un statut, une message ou une metrique. Le plugin s'attend à un format spécifique pour les données
```suggestion
Les plugins réalisent des appels API et déchiffrent le contenu renvoyé par l'API pour l'utiliser comme un statut, un message ou une métrique. Le plugin s'attend à un format spécifique pour les données selon ce qui est supporté par l'API (XML ou JSON).
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +La raison la plus commune de ce problème est qu'un proxy bloque la requête principale et rend un message d'erreur qui n'est pas dans le format attendu. L'option `--proxyurl=<proto>://<address>:<port>
```suggestion
La raison la plus commune de ce problème est qu'un proxy bloque la requête principale et renvoie un message d'erreur qui n'est pas dans le format attendu. L'option `--proxyurl=<proto>://<address>:<port>` vous permet de spécifier l'adresse et le port d'un proxy.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Vous pouvez investiguer ça en ajoutant le flag `--debug` à votre ligne de commande pour obtenir plus d'informations à propos de la requête et des données reçues.
```suggestion
Vous pouvez investiguer cela en ajoutant le flag `--debug` à votre ligne de commande pour obtenir plus d'informations à propos de la requête et des données reçues.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Lorsque vous récuperez des metriques ou des données d'un API, divers problèmes peuvent appraitre. Ils sont souvent causés par des proxy, des appareils distants, des certificats ou tout simplement la
```suggestion
Lorsque vous récupérez des métriques ou des données d'une API, divers problèmes peuvent apparaître. Ils sont souvent causés par des proxys, des appareils distants, des certificats ou tout simplement la configuration du contrôle.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Ce que vous devez retenir est que les plugins peuvent dépendre de plusieurs *backends* pour réaliser leur requêtes HTTP. Vous pouvez spécifier quel backend vous souhaitez utiliser pour vos contrôles
```suggestion
Ce que vous devez retenir est que les plugins peuvent dépendre de plusieurs *backends* pour réaliser leur requêtes HTTP. Vous pouvez spécifier quel backend vous souhaitez utiliser pour vos contrôles avec l'option `--http-backend` dont la valeur par défaut est `lwp`, mais `curl` est également disponible et est, généralement, plus facile à dépanner.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Si vous utilisez un proxy vous pouvez également spécifier au plugin comment communiquer avec en ajoutant l'option `--proxyurl` à votre ligne de commande. Le format attendu est :
```suggestion
Si vous utilisez un proxy, vous pouvez également spécifier au plugin comment communiquer avec en ajoutant l'option `--proxyurl` à votre ligne de commande. Le format attendu est : 
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Ce problème a tendance à appraître lorsque le port ou protocole employé par le plugin est incorrect, mal configuré ou n'est pas supporté par le plugin.
```suggestion
Ce problème a tendance à apparaître lorsque le port ou protocole employé par le plugin est incorrect, mal configuré ou n'est pas supporté par le plugin.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Dans ce cas, vérifiez les configurations suivantes au niveau de la configuration de l'hôte :
```suggestion
Dans ce cas, au niveau de la configuration de l'hôte, vérifiez que :
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* le port utilisé est le bon, principalement si vous utilisez un port spécial pour des raisons de sécurité
```suggestion
* le port utilisé est le bon, surtout si vous utilisez un port spécial pour des raisons de sécurité
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* le protocole employé (http ou https) correspond à celui employé du côté de l'API
```suggestion
* le protocole employé (http ou https) correspond à celui employé du côté de l'API.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +que tous les plugins utilisant des backend HTTP ont les options `--proto` et `--port` vous permettant de spécifier ces valeurs.
```suggestion
Tous les plugins utilisant des backends HTTP ont les options `--proto` et `--port` vous permettant de spécifier ces valeurs.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +L'erreur SSL indique que le plugin rencontre des problèmes pour établir un connexion sécurisée pour obtenir les données de supervision.
```suggestion
L'erreur SSL indique que le plugin rencontre des problèmes pour établir un connexion sécurisée afin d'obtenir les données de supervision.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +La cause est probablement le certificat employé, dans ce cas, les meilleures pratiques sont :
```suggestion
La cause est probablement le certificat employé. Dans ce cas, les meilleures pratiques sont :
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* renouveler le certificat lorsu'il a expiré
```suggestion
* renouveler le certificat lorsqu'il a expiré
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* signer officiellement la certification à distance
```suggestion
* signer officiellement le certificat distant
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* deployer le certificat localement pour que le plugin puisse le reconnaître
```suggestion
* deployer le certificat localement pour que le plugin puisse le reconnaître.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Indépendament du backend HTTP que vous employez, il est possible d'ignorer les erreurs de certificat SSL en ajoutant des flags specifiques :
```suggestion
Indépendamment du backend HTTP que vous employez, il est possible d'ignorer les erreurs de certificat SSL en ajoutant des flags spécifiques : 
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Occasionnellement, l'hôte distant ne suppoorte pas la négotiation de l'implémentation SSL. Vous devez alors spécifier explicitement au plugin lequel utiliser avec l'option `--ssl` (e.g. `--ssl='tlsv1
```suggestion
Parfois, l'hôte distant ne supporte pas la négociation de l'implémentation SSL. Vous devez alors spécifier explicitement au plugin lequel utiliser avec l'option `--ssl` (e.g. `--ssl='tlsv1'`). Référez-vous à la documentation du fabricant ou de l'éditeur du logiciel.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Cette erreur indique que le plugin n'est pas capble d'executer `<commande_name>` care la commande n'existe pas dans PATH ou n'est pas installée.
```suggestion
Cette erreur indique que le plugin n'est pas capable d'exécuter `<command_name>` car la commande n'existe pas dans PATH ou n'est pas installée.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Les contrôles basés sur SSH peuvent utiliser de nombreux *backends*, peu importe que vous utilisez le backend `ssh` ou `plink`, vous devez valider manuellement l'empreinte digitale du système distant
```suggestion
Les contrôles basés sur SSH peuvent utiliser plusieurs *backends*. Que vous utilisiez le backend `ssh` ou `plink`, vous devez valider manuellement l'empreinte du système distant sur le collecteur de supervision et depuis l'utilisateur **centreon-engine**. Pour des raisons de sécurité, si vous ne suivez pas ces instructions, le plugin reste en attente jusqu'à déclencher un timeout car il ne peut accepter l'empreinte.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* Est-ce que le daemon NRPE est actif dans le système distant ?
```suggestion
* Est-ce que le daemon NRPE est actif sur le système distant ?
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +* Est-ce qu'il y a un firewall ou une politique de sécurité qui pourrait être en train de bloquer la requête ?
```suggestion
* Est-ce qu'un firewall ou une politique de sécurité pourrait être en train de bloquer la requête ?
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Cela est généralement dû au fait que le client essaie d'établir une connexion avec le serveur depuis une IP non-autorisée.
```suggestion
Cela est généralement dû au fait que le client essaie d'établir une connexion avec le serveur depuis une IP non autorisée.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Verifiez que le directif `allowed_hosts` défini dans le fichier config du serveur NRPE autorise votre serveur de supervision à envoyer des commandes d'exécution à distance.
```suggestion
Vérifiez que la directive `allowed_hosts` définie dans le fichier de configuration du serveur NRPE autorise votre serveur de supervision à envoyer des commandes d'exécution à distance.
```

2025-02-04 10:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Vérifiez la configuration du serveur NRPE pour confirmer que la commande existe :
```suggestion
Vérifiez la configuration du serveur NRPE pour confirmer que la commande existe :

```

2025-02-04 10:14 UTC, cg-tw commented
Check the anchors in the FR topics

2025-02-10 14:28 UTC, cg-tw approved these changes

2025-02-10 14:28 UTC, merged