CTOR-1014 : Problem with windows-winrm-wsman-tutorial page
centreon/centreon-documentation pull request #3742
Opened 2024-11-05 11:09 UTC by lucie-dubrunfaut

## Description

Add debian 12 support

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-05 11:09 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
> +
```suggestion

```

2024-11-05 11:10 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
> +```
```suggestion
```

```

2024-11-12 13:29 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
> +> In case of Debian 12:
```suggestion
> If you are using Debian 12:
```

2024-11-12 13:32 UTC, lucie-dubrunfaut commented
@omercier Est-ce qu'on a un moyen de tester si la ligne de commande est bonne quand même ?

2024-11-18 16:12 UTC, cg-tw requested changes

2024-11-18 16:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
> +> Dans le cas de Debian 12 :
```suggestion
> Dans le cas de Debian 12 :

```

2024-11-18 16:12 UTC, cg-tw commented on pp/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
> +> If you are using Debian 12:
```suggestion
> If you are using Debian 12:

```

2024-11-19 13:16 UTC, cg-tw approved these changes

2024-11-19 13:31 UTC, merged