CTOR-967 : November release note
centreon/centreon-documentation pull request #3745
Opened 2024-11-06 11:07 UTC by lucie-dubrunfaut

## Description

November Release note

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-06 11:08 UTC, lucie-dubrunfaut commented
Actuellement il me manque les PR de packs de : 
- Mosquitto (PR Plugins + Pack)
- DataDomain (PR Pack + Documentation)

2024-11-06 12:52 UTC, cg-tw requested changes

2024-11-06 12:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**Linux Telegraf Agent**](../procedures/operatingsystems-linux-telegraf-agent.md) - Changed the inherited template to passive.
```suggestion
- [**Linux Telegraf Agent**](../procedures/operatingsystems-linux-telegraf-agent.md) - The default inherited templates are now passive.
```

2024-11-06 12:52 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**Windows Telegraf Agent**](../procedures/operatingsystems-windows-telegraf-agent.md) - Changed the inherited template to passive.
```suggestion
- [**Windows Telegraf Agent**](../procedures/operatingsystems-windows-telegraf-agent.md) - The default inherited templates are now passive.
```

2024-11-06 12:52 UTC, cg-tw commented on pp/integrations/plugin-packs/releases/release-notes.md
> +- [**Linux Telegraf Agent**](../procedures/operatingsystems-linux-telegraf-agent.md) - Changed the inherited template to passive.
```suggestion
- [**Linux Telegraf Agent**](../procedures/operatingsystems-linux-telegraf-agent.md) - The default inherited templates are now passive.
```

2024-11-06 12:52 UTC, cg-tw commented on pp/integrations/plugin-packs/releases/release-notes.md
> +- [**Windows Telegraf Agent**](../procedures/operatingsystems-windows-telegraf-agent.md) - Changed the inherited template to passive.
```suggestion
- [**Windows Telegraf Agent**](../procedures/operatingsystems-windows-telegraf-agent.md) - The default inherited templates are now passive.
```

2024-11-06 13:02 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**PostgreSQL**](../procedures/applications-databases-postgresql.md) - Fixed exclude options working as includes.
```suggestion
- [**PostgreSQL**](../procedures/applications-databases-postgresql.md) - Fixed `exclude` option working as includes.
```

2024-11-06 13:02 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/releases/release-notes.md
> +- [**PostgreSQL**](../procedures/applications-databases-postgresql.md) - Fixed exclude options working as includes.
```suggestion
- [**PostgreSQL**](../procedures/applications-databases-postgresql.md) - Fixed `exclude` option working as includes.
```

2024-11-07 10:19 UTC, cg-tw requested changes

2024-11-07 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**EMC Data Domain SNMP**](../procedures/hardware-storage-emc-datadomain-snmp.md) - Added several new modes and services discovery rules.
```suggestion
- [**EMC Data Domain SNMP**](../procedures/hardware-storage-emc-datadomain-snmp.md) - Added several new modes and service discovery rules.
```

2024-11-07 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**MySQL/MariaDB**](../procedures/applications-databases-mysql.md) - Used the proper mariadb message when checking mysql replication state.
```suggestion
- [**MySQL/MariaDB**](../procedures/applications-databases-mysql.md) - Used the correct MariaDB message when checking MySQL replication state.
```

2024-11-07 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**Centreon Database**](../procedures/applications-monitoring-centreon-database.md) - Used the proper mariadb message when checking mysql replication state.
```suggestion
- [**Centreon Database**](../procedures/applications-monitoring-centreon-database.md) - Used the correct MariaDB message when checking MySQL replication state.
```

2024-11-07 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**Atrica Routeur**](../procedures/network-routers-atrica-snmp.md) - Added service discovery rule for connections mode.
```suggestion
- [**Atrica Routeur**](../procedures/network-routers-atrica-snmp.md) - Added service discovery rule for **connections** mode.
```

2024-11-07 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**EMC Data Domain SNMP**](../procedures/hardware-storage-emc-datadomain-snmp.md) - Changed modes name and dependencies paths.
```suggestion
- [**EMC Data Domain SNMP**](../procedures/hardware-storage-emc-datadomain-snmp.md) - Changed mode names and dependencies paths.
```

2024-11-07 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**PostgreSQL**](../procedures/applications-databases-postgresql.md) - Fixed `exclude` option working as includes.
```suggestion
- [**PostgreSQL**](../procedures/applications-databases-postgresql.md) - Fixed `exclude` option working as "include".
```

2024-11-07 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**Amazon CloudTrail**](../procedures/cloud-aws-cloudtrail.md) - Fixed command for event lookup from community feedback [PR 5086](https://github.com/centreon/centreon-plugins/pull/5086).
```suggestion
- [**Amazon CloudTrail**](../procedures/cloud-aws-cloudtrail.md) - Fixed command for event lookup, from community feedback [PR 5086](https://github.com/centreon/centreon-plugins/pull/5086).
```

2024-11-07 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
> +- [**HPE Primera REST API**](../procedures/hardware-storage-hpe-primera-restapi.md) - Fixed status handling & retry on invalid token from community feedback [PR 5256](https://github.com/centreon/cent
```suggestion
- [**HPE Primera REST API**](../procedures/hardware-storage-hpe-primera-restapi.md) - Fixed status handling & retry on invalid token, from community feedback [PR 5256](https://github.com/centreon/centreon-plugins/pull/5256).
```

2024-11-07 10:21 UTC, cg-tw requested changes

2024-11-07 10:21 UTC, cg-tw commented on pp/integrations/plugin-packs/releases/release-notes.md
> +</Tabs>
```suggestion
<Tabs groupId="sync">
<TabItem value="Enhancements" label="Enhancements">

- [**Atrica Routeur**](../procedures/network-routers-atrica-snmp.md) - Added service discovery rule for **connections** mode.
- [**Centreon Database**](../procedures/applications-monitoring-centreon-database.md) - Used the correct MariaDB message when checking MySQL replication state.
- [**EMC Data Domain SNMP**](../procedures/hardware-storage-emc-datadomain-snmp.md) - Added several new modes and service discovery rules.
- [**MySQL/MariaDB**](../procedures/applications-databases-mysql.md) - Used the correct MariaDB message when checking MySQL replication state.

</TabItem>
<TabItem value="Breaking changes" label="Breaking changes">

- [**EMC Data Domain SNMP**](../procedures/hardware-storage-emc-datadomain-snmp.md) - Changed mode names and dependencies paths.
- [**Linux Telegraf Agent**](../procedures/operatingsystems-linux-telegraf-agent.md) - The default inherited templates are now passive.
- [**PostgreSQL**](../procedures/applications-databases-postgresql.md) - Fixed `exclude` option working as "include".
- [**Windows Telegraf Agent**](../procedures/operatingsystems-windows-telegraf-agent.md) - The default inherited templates are now passive.

</TabItem>
<TabItem value="Fix" label="Fix">

- [**Amazon CloudTrail**](../procedures/cloud-aws-cloudtrail.md) - Fixed command for event lookup, from community feedback [PR 5086](https://github.com/centreon/centreon-plugins/pull/5086).
- [**Eclipse Mosquitto MQTT**](../procedures//applications-eclipse-mosquitto-mqtt.md) - Fixed ` warning-regexp` and `critical-regexp` options.
- [**HPE Primera REST API**](../procedures/hardware-storage-hpe-primera-restapi.md) - Fixed status handling & retry on invalid token, from community feedback [PR 5256](https://github.com/centreon/centreon-plugins/pull/5256).
- [**Speedtest**](../procedures/applications-monitoring-speedtest.md) - Fixed packaging issue leading to conflict between speedtest and speedtest-cli binaries.
- [**Cisco WLC**](../procedures/network-cisco-wlc-snmp.md) - Fixed wrong unit for roundtrip-time.

</TabItem>
</Tabs>
```

2024-11-07 10:21 UTC, cg-tw approved these changes

2024-11-07 11:31 UTC, merged