doc(release) Release notes for web 24.10.1
centreon/centreon-documentation pull request #3748
Opened 2024-11-07 11:17 UTC by pkippes

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-11-07 11:26 UTC, cg-tw requested changes

2024-11-07 11:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
> +<details>
```suggestion
</details>
```

2024-11-07 11:26 UTC, cg-tw commented on versioned_docs/version-24.10/releases/centreon-os.mdx
> +<details>
```suggestion
</details>
```

2024-11-08 09:40 UTC, rsadik-ext approved these changes

2024-11-08 10:41 UTC, cg-tw approved these changes

2024-11-08 10:41 UTC, merged