Add network cisco callmanager sxml fr
centreon/centreon-documentation pull request #375
Opened 2020-10-06 14:25 UTC by psamecentreon

2020-10-12 12:09 UTC, Sims24 requested changes

2020-10-12 12:09 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +1. Installer le Plugin sur tous les collecteurs Centreon supervisant des ressources Cisco Callmanager :
Uppercase C

2020-10-12 12:09 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +1. Installer le Plugin sur tous les collecteurs Centreon supervisant des ressources Cisco Callmanager :
Uppercase C

2020-10-12 12:09 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +Une fois le Plugin installé, vous pouvez tester celui-ci directement en ligne de commande depuis votre collecteur Centreon avec l'utilisateur *centreon-engine*
Uppercase C

2020-10-12 12:09 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +```bash
1 option / line

2020-10-12 12:09 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +De ce fait, des perfdatas "globales" sur les statistiques des objets sont ajoutées par défaut. Il est possible de supprimer ces données de performance en appliquant le filtre suivant: ```--filter-per
Copy / Paste ?

2020-10-15 09:58 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +1. Installer le Plugin sur tous les collecteurs Centreon supervisant des ressources Cisco Callmanager :
Uppercase C => OK ✔️

2020-10-15 09:58 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +1. Installer le Plugin sur tous les collecteurs Centreon supervisant des ressources Cisco Callmanager :
Uppercase C => OK ✔️

2020-10-15 09:58 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +Une fois le Plugin installé, vous pouvez tester celui-ci directement en ligne de commande depuis votre collecteur Centreon avec l'utilisateur *centreon-engine*
Uppercase C => OK ✔️

2020-10-15 09:58 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +```bash
Added 1 option / line

2020-10-15 12:26 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +De ce fait, des perfdatas "globales" sur les statistiques des objets sont ajoutées par défaut. Il est possible de supprimer ces données de performance en appliquant le filtre suivant: ```--filter-per
Senteces removed

2020-10-15 18:25 UTC, Sims24 approved these changes

2020-10-15 18:25 UTC, merged