Add network cisco callmanager sxml
centreon/centreon-documentation pull request #376
Opened 2020-10-06 15:31 UTC by psamecentreon

2020-10-12 12:07 UTC, Sims24 requested changes

2020-10-12 12:07 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +Using SXML, this Cisco Call Manager Plugin-Pack monitors alerts from the Cisco Unified Communications component.
componentS

2020-10-12 12:07 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +/usr/lib/centreon/plugins//centreon_cisco_cucm_sxml.pl --plugin=network::cisco::callmanager::sxml::plugin \
One option / line

2020-10-12 12:07 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +By default, the backend method is _curl_ (```--http-backend=curl``).
Missing `

2020-10-15 12:23 UTC, psamecentreon commented on en/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +Using SXML, this Cisco Call Manager Plugin-Pack monitors alerts from the Cisco Unified Communications component.
Fixed ^^

2020-10-15 12:23 UTC, psamecentreon commented on en/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +/usr/lib/centreon/plugins//centreon_cisco_cucm_sxml.pl --plugin=network::cisco::callmanager::sxml::plugin \
Done

2020-10-15 12:24 UTC, psamecentreon commented on en/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
> +By default, the backend method is _curl_ (```--http-backend=curl``).
` added too

2020-10-15 18:24 UTC, Sims24 approved these changes

2020-10-15 18:24 UTC, merged