CTOR-1061 : Refresh cloud-aws-sns
centreon/centreon-documentation pull request #3766
Opened 2024-11-13 14:34 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-sns

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-14 10:11 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-sns.md
> +| Amazon Web Service SNS | Découvre les Topics iscover AWS SNS |
```suggestion
| Amazon Web Service SNS | Découvre les Topics AWS SNS |
```

2024-11-14 10:12 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-sns.md
> +* sns:ListTopics
```suggestion
* cloudwatch:getMetricStatistics
* cloudwatch:listMetrics
* sns:ListTopics
```

2024-11-18 17:06 UTC, cg-tw requested changes

2024-11-18 17:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-sns.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-11-18 17:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-sns.md
> +Configurez un compte de service (via une combinaison d'access et secret key) et affectez-lui les privilèges suivants :
```suggestion
Configurez un compte de service (via une combinaison d'access key et de secret key) et affectez-lui les privilèges suivants :
```

2024-11-19 13:36 UTC, cg-tw approved these changes

2024-11-19 13:51 UTC, merged