CTOR-1062 : Refresh cloud-aws-sqs
centreon/centreon-documentation pull request #3767
Opened 2024-11-13 14:48 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-sqs

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-14 10:15 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-sqs.md
> +* sqs:ListQueues
```suggestion
* cloudwatch:getMetricStatistics
* cloudwatch:listMetrics
* sqs:ListQueues
```

2024-11-14 10:16 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-sqs.md
> +* sqs:ListQueues
```suggestion
* cloudwatch:getMetricStatistics
* cloudwatch:listMetrics
* sqs:ListQueues
```

2024-11-18 17:11 UTC, cg-tw requested changes

2024-11-18 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-sqs.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-11-18 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-sqs.md
> +| Amazon Web Service SQS | Découvre les Topics AWS SNS |
topics sns??

2024-11-18 17:11 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-sqs.md
> +Configurez un compte de service (via une combinaison d'access et secret key) et affectez-lui les privilèges suivants :
```suggestion
Configurez un compte de service (via une combinaison d'access key et de secret key) et affectez-lui les privilèges suivants :
```

2024-11-18 17:11 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-sqs.md
> +| Amazon Web Service SQS | Discover AWS SNS Topics |
SNS topics??

2024-11-19 13:37 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-sqs.md
> +| Amazon Web Service SQS | Discover AWS SNS Topics |
```suggestion
| Amazon Web Service SQS | Discover AWS SQS Topics |
```

2024-11-19 13:40 UTC, cg-tw approved these changes

2024-11-19 13:55 UTC, merged