Mon 19915 update acl filters options
centreon/centreon-documentation pull request #3785
Opened 2024-11-19 16:40 UTC by emgcentreon

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-11-25 16:26 UTC, cg-tw requested changes

2024-11-25 16:26 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
Tu n'as pas exprimé cette notion de droits cumulatifs

2024-11-26 14:37 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services. Plus de services peuvent être ajoutés mais les services déjà inclus ne peuvent être exclus.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-11-26 14:37 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services. Plus de services peuvent être ajoutés mais les services déjà inclus ne peuvent être exclus.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-11-26 14:37 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services. Plus de services peuvent être ajoutés mais les services déjà inclus ne peuvent être exclus.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-11-26 14:37 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services. Plus de services peuvent être ajoutés mais les services déjà inclus ne peuvent être exclus.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-11-26 14:37 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services. Plus de services peuvent être ajoutés mais les services déjà inclus ne peuvent être exclus.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-11-26 14:37 UTC, emgcentreon commented on versioned_docs/version-22.10/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services. More services can be added after this but already included services can not be excluded.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>  <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>                                                                       |
```

2024-11-26 14:37 UTC, emgcentreon commented on versioned_docs/version-23.04/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services. More services can be added after this but already included services can not be excluded.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>                                                                       |
```

2024-11-26 14:37 UTC, emgcentreon commented on versioned_docs/version-23.10/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services. More services can be added after this but already included services can not be excluded.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>
```

2024-11-26 14:37 UTC, emgcentreon commented on versioned_docs/version-24.04/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services. More services can be added after this but already included services can not be excluded.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>
```

2024-11-26 14:37 UTC, emgcentreon commented on versioned_docs/version-24.10/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services. More services can be added after this but already included services can not be excluded.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>
```

2024-11-26 14:37 UTC, emgcentreon commented on versioned_docs/version-25.10/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services. More services can be added after this but already included services can not be excluded.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>
```

2024-12-17 16:27 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-12-17 16:27 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-12-17 16:27 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-12-17 16:27 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-12-17 16:27 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-12-17 16:27 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2024-12-17 16:27 UTC, emgcentreon commented on versioned_docs/version-22.10/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>  <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>                                                                       |
```

2024-12-17 16:27 UTC, emgcentreon commented on versioned_docs/version-23.04/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>                                                                       |
```

2024-12-17 16:27 UTC, emgcentreon commented on versioned_docs/version-23.10/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>
```

2024-12-17 16:27 UTC, emgcentreon commented on versioned_docs/version-24.04/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>
```

2024-12-17 16:27 UTC, emgcentreon commented on versioned_docs/version-24.10/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>
```

2024-12-17 16:27 UTC, emgcentreon commented on versioned_docs/version-25.10/administration/access-control-lists.md
> +| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected,
```suggestion
| **Hosts Resources**    | <ul><li>Define which hosts and hosts groups users will be able to see in the Centreon interface.</li><li>If **Include all hosts** or **Include all hostgroups** is selected, any newly created host or host group will be added to the filter automatically.</li><li>Adding a host automatically includes all its services.</li><li>Adding multiple host groups will grant access to all the hosts contained within those groups.</li></ul>   <p>When **Include all hosts** or **Include all hostgroups** is selected, you can explicitly exclude hosts from the filter (e.g. when only 1 or 2 hosts should not be included in the filter). </p>
```

2025-01-06 16:05 UTC, cg-tw requested changes

2025-01-06 16:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes.</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2025-01-06 16:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes.</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2025-01-06 16:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes.</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2025-01-06 16:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes.</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2025-01-06 16:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes.</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2025-01-06 16:05 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/administration/access-control-lists.md
> +| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tou
```suggestion
| **Gestion des hôtes**    | <ul><li>Définissez quels hôtes et quels groupes d'hôtes l'utilisateur pourra voir dans l'interface Centreon</li><li>Si la case **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** est cochée, alors tout hôte ou groupe d'hôtes nouvellement créé sera automatiquement ajouté au filtre.</li><li>Ajouter un hôte ajoute automatiquement tous ses services.</li><li>Ajouter plusieurs groupes d'hôtes donne accès à la totalité des hôtes contenus dans ces groupes.</li></ul>   <p>Dans le cas où les options **Inclure tous les hôtes** ou **Inclure tous les groupes d'hôtes** sont cochées, il est possible d'exclure explicitement des hôtes du filtre (par exemple dans le cas où seulement 1 ou 2 hôtes ne doivent pas faire partie du filtre). </p>                                                                       |
```

2025-01-06 16:06 UTC, cg-tw approved these changes

2025-01-13 08:58 UTC, merged