CTOR-1065 : Refresh cloud-aws-elb
centreon/centreon-documentation pull request #3786
Opened 2024-11-20 08:37 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-elb

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-20 09:09 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-elb.md
> +	--region='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--region='us-east-1' \
```

2024-11-20 09:09 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-elb.md
> +	--region='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--region='us-east-1' \
```

2024-11-20 09:16 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-elb.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-11-25 10:19 UTC, cg-tw requested changes

2024-11-26 13:03 UTC, cg-tw approved these changes

2024-11-26 13:03 UTC, merged