CTOR-1066 : Refresh cloud-aws-health
centreon/centreon-documentation pull request #3787
Opened 2024-11-20 09:05 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-health

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-20 09:10 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-health.md
>  	--filter-region='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
	--proxyurl=''  \
	--filter-service='' \
	--filter-region='' \
```

2024-11-20 09:11 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-health.md
> +	--aws-role-arn='' \
```suggestion
	--aws-secret-key='XXXX' \
	--aws-access-key='XXXX' \
	--aws-role-arn='' \
```

2024-11-20 09:16 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-health.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2024-11-25 13:08 UTC, cg-tw requested changes

2024-11-25 13:08 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-health.md
>  	--filter-region='' \
c'est pas obligatoire de spécifier une région?

2024-11-25 13:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-health.md
> +This host template doesn't have services set automatically.
```suggestion
This host template doesn't have any associated services.
```

2024-11-25 13:08 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-health.md
>  	--filter-region='' \
same as FR

2024-11-26 12:53 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-health.md
>  	--filter-region='' \
De ce que je viens de tester il semble réussir à se lancer sans (en tout cas il le requiert pas comme mandatory)
```
perl centreon_plugins.pl --plugin=cloud::aws::health::plugin --mode=events
UNKNOWN: Need to specify '--custommode'. 

perl centreon_plugins.pl --plugin=cloud::aws::health::plugin --mode=events --custommode='awscli'
UNKNOWN: Command error: Can't exec "aws": No such file or directory at /home/ldubrunfaut/centreon-plugins/src/centreon/plugins/misc.pm line 303. 
```

2025-10-06 14:58 UTC, lucie-tirand commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-health.md
>  	--filter-region='' \
La région n'est pas obligatoire car il prend EU-West-1 par défaut (par contre si tu lui donnes region='' là ça pète)

2025-10-07 12:14 UTC, lucie-tirand commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-health.md
> +| --region                                   |   Set the region name (required).
```suggestion
| --region                                   |   Set the region name (if not set, the default value applied is EU-West-1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
```

2025-10-07 12:14 UTC, lucie-tirand commented on pp/integrations/plugin-packs/procedures/cloud-aws-health.md
> +| --region                                   |   Set the region name (required).
```suggestion
| --region                                   |   Set the region name (if not set, the default value applied is EU-West-1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
```

2025-10-07 13:01 UTC, closed without merging