[CTOR-1088] Refresh network-firewalls-paloalto-standard-ssh doc page
centreon/centreon-documentation pull request #3788
Opened 2024-11-20 09:12 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-11-25 13:13 UTC, cg-tw requested changes

2024-11-25 13:13 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md
> +	--ssh-username='' \
username & password

2024-11-25 13:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md
> +| Ha            | Net-PaloAlto-Standard-Ha-SSH-custom          | Check high-availability  |
```suggestion
| Ha            | Net-PaloAlto-Standard-Ha-SSH-custom          | Check high availability  |
```

2024-11-25 13:13 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md
> +	--ssh-username='' \
username & password

2024-11-26 11:02 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md
> +	--ssh-password='' \
```suggestion
	--ssh-username='XXXX' \
	--ssh-password='XXXX' \
```

2024-11-26 11:02 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md
> +	--ssh-password='' \
```suggestion
	--ssh-username='XXXX' \
	--ssh-password='XXXX' \
```

2024-11-26 13:16 UTC, cg-tw approved these changes

2024-11-26 13:16 UTC, merged