CTOR-1068 : Refresh cloud-aws-transitgateway
centreon/centreon-documentation pull request #3790
Opened 2024-11-20 09:29 UTC by lucie-dubrunfaut

## Description

Refresh cloud-aws-transitgateway

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-25 13:27 UTC, cg-tw requested changes

2024-11-25 13:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
> +Configurez un compte de service (via une combinaison d'access et secret key) et affectez-lui les privilèges suivants :
```suggestion
Configurez un compte de service (via une combinaison d'access key et de secret key) et affectez-lui les privilèges suivants :
```

2024-11-25 13:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
> +	--custommode='' \
pas de custom mode?

2024-11-25 13:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
> +	--custommode='' \
custom mode?

2024-11-26 12:57 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
> +	--custommode='' \
```suggestion
	--custommode='awscli' \
```

2024-11-26 12:57 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
> +| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option               |                   |           |
```suggestion
| AWSCUSTOMMODE | When a plugin offers several ways (CLI, library, etc.) to get information the desired one must be defined with this option               |                   | X          |
```

2024-11-26 12:57 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
> +	--custommode='' \
```suggestion
	--custommode='awscli' \
```

2024-11-26 13:17 UTC, cg-tw approved these changes

2024-11-26 13:18 UTC, merged