New(mp) VerneMQ Restapi
centreon/centreon-documentation pull request #380
Opened 2020-10-08 08:26 UTC by psamecentreon

2020-10-12 12:05 UTC, Sims24 requested changes

2020-10-12 12:05 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +1. Installer le Plugin sur tous les collecteurs Centreon supervisant des ressources VerneMQ :
Uppercase C ;)

2020-10-12 12:05 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +1. Installer le Plugin sur tous les collecteurs Centreon supervisant des ressources VerneMQ :
Uppercase C

2020-10-12 12:05 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +L'API HTTP de VerneMQ est activée par défaut et installe un gestionnaire HTTP sur `http://localhost:8888/api/v1`.
Cf EN review

2020-10-12 12:05 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +/usr/lib/centreon/plugins/centreon_vernemq_restapi.pl --plugin=apps::mq::vernemq::restapi::plugin \
cf EN review

2020-10-12 12:05 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +De ce fait, des perfdatas "globales" sur les statistiques des objets sont ajoutées par défaut. Il est possible de supprimer ces données de performance en appliquant le filtre suivant: ```--filter-per
cf EN review

2020-10-15 12:10 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +1. Installer le Plugin sur tous les collecteurs Centreon supervisant des ressources VerneMQ :
Done ^^

2020-10-15 12:10 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +1. Installer le Plugin sur tous les collecteurs Centreon supervisant des ressources VerneMQ :
Done ^^

2020-10-15 12:10 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +L'API HTTP de VerneMQ est activée par défaut et installe un gestionnaire HTTP sur `http://localhost:8888/api/v1`.
Yes, it's OK now

2020-10-15 12:10 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +De ce fait, des perfdatas "globales" sur les statistiques des objets sont ajoutées par défaut. Il est possible de supprimer ces données de performance en appliquant le filtre suivant: ```--filter-per
Yes, it's OK now

2020-10-15 12:11 UTC, psamecentreon commented on fr/integrations/plugin-packs/procedures/applications-vernemq-restapi.md
> +/usr/lib/centreon/plugins/centreon_vernemq_restapi.pl --plugin=apps::mq::vernemq::restapi::plugin \
Yes, it's ok

2020-10-15 18:22 UTC, Sims24 approved these changes

2020-10-15 18:22 UTC, merged