indicate when one should update BAM and MAP with links
centreon/centreon-documentation pull request #3812
Opened 2024-11-22 10:17 UTC by emgcentreon

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-12-10 16:42 UTC, jdelpierre approved these changes, later dismissed

2024-12-12 10:42 UTC, cg-tw requested changes

2024-12-12 10:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-20-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
- "trouvez ici" n'est pas idiomatique
- il manque MBI
- ça doit être lié à un autre ticket qu'il faut que je retrouve

2024-12-18 16:26 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-20-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-21-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-21-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-20-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-21-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-21-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-23-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-20-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-21-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-20-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-21-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-21-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-22-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-22-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-24-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-20-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-21-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-21-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-22-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-22-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-23-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-23-10.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-24-04.md
> +> Trouvez ici les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```suggestion
> Nous avons des articles dédiés pour les procédures de montée de version pour [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md).
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-23.04/upgrade/upgrade-from-20-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-23.04/upgrade/upgrade-from-21-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-23.04/upgrade/upgrade-from-21-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-23.04/upgrade/upgrade-from-22-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-23.04/upgrade/upgrade-from-22-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-23.10/upgrade/upgrade-from-21-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.04/upgrade/upgrade-from-23-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.04/upgrade/upgrade-from-23-10.md
> +  > Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-20-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-21-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-21-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-22-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-22-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-23-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-23-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-24-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-20-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-21-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-21-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-22-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-22-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-23-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-23-10.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2024-12-19 09:45 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-24-04.md
> +> Refer to the [Centreon BAM](../service-mapping/update.md) and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```suggestion
> Refer to the [Centreon BAM](../service-mapping/update.md), [Centreon MBI](../reporting/update.md)  and [Centreon MAP](../graph-views/map-web-upgrade.md) dedicated procedures to update these modules.
```

2025-01-10 17:02 UTC, jdelpierre approved these changes, later dismissed

2025-02-13 10:53 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-04.md
> +6. Supprimer les fichiers de rétention présents :
```suggestion
6. Supprimez les fichiers de rétention présents :
```

2025-02-13 10:53 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-04.md
> +rm /etc/yum.repos.d/centreon-business-21.10.repo
```suggestion
rm /etc/yum.repos.d/centreon-business-22.04.repo
```

2025-02-13 10:53 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-04.md
> +rm /etc/yum.repos.d/centreon-business-21.10.repo
```suggestion
rm /etc/yum.repos.d/centreon-business-22.04.repo
```

2025-02-13 10:53 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-04.md
> +2. Si vous avez des extensions Business installées, eliminez la configuration du dépôt 21.10 :
```suggestion
2. Si vous avez des extensions Business installées, éliminez la configuration du dépôt 22.04 :
```

2025-02-13 10:53 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-21-04.md
> +6. Supprimer les fichiers de rétention présents :
```suggestion
6. Supprimez les fichiers de rétention présents :
```

2025-02-13 10:53 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-21-10.md
> +6. Supprimer les fichiers de rétention présents :
```suggestion
6. Supprimez les fichiers de rétention présents :
```

2025-02-13 10:55 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-20-10.md
> +6. Supprimer les fichiers de rétention présents :
```suggestion
6. Supprimez les fichiers de rétention présents :
```

2025-02-14 12:22 UTC, emgcentreon commented on versioned_docs/version-24.04/upgrade/upgrade-from-21-04.md
> +3. Install the 23.10 Business repository: visit the [support portal](https://support.centreon.com/hc/en-us/categories/10341239833105-Repositories) to get its address.
```suggestion
3. Install the 24.04 Business repository: visit the [support portal](https://support.centreon.com/hc/en-us/categories/10341239833105-Repositories) to get its address.
```

2025-02-14 12:22 UTC, emgcentreon commented on versioned_docs/version-24.04/upgrade/upgrade-from-20-10.md
> +3. Install the 23.10 Business repository: visit the [support portal](https://support.centreon.com/hc/en-us/categories/10341239833105-Repositories) to get its address.
```suggestion
3. Install the 24.04 Business repository: visit the [support portal](https://support.centreon.com/hc/en-us/categories/10341239833105-Repositories) to get its address.
```

2025-02-14 13:00 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-22-04.md
> +2. If you have installed Business extensions, delete the configuration of repository 21.10 :
```suggestion
2. If you have installed Business extensions, delete the configuration of repository 22.04 : 
```

2025-02-14 13:00 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-22-04.md
> +rm /etc/yum.repos.d/centreon-business-21.10.repo
```suggestion
rm /etc/yum.repos.d/centreon-business-22.04.repo
```

2025-02-14 13:00 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-22-04.md
> +rm /etc/yum.repos.d/centreon-business-21.10.repo
```suggestion
rm /etc/yum.repos.d/centreon-business-22.04.repo
```

2025-02-18 10:20 UTC, cg-tw submitted a review, later dismissed

2025-02-18 10:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-20-10.md
> +2. Si vous avez des extensions Business installées, éliminez la configuration du dépôt 20.10 :
```suggestion
2. Si vous avez des extensions Business installées, supprimez la configuration du dépôt 20.10 :
```

2025-02-18 10:20 UTC, cg-tw commented on versioned_docs/version-25.10/upgrade/upgrade-from-21-04.md
> +2. If you have installed Business extensions, delete the configuration of repository 21.04 :
```suggestion
2. If you have installed Business extensions, delete the configuration of the 21.04 repository: 
```

2025-02-18 10:20 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-20-10.md
> +Référez-vous à la documentation de mise à jour pour [Centreon BAM](../service-mapping/upgrade.md), [Centreon MBI](../reporting/update.md) et [Centreon MAP](../graph-views/map-web-upgrade.md) pour met
BAM is supposed to be upgraded before connecting to the interface (the correct link is to the upgrade topic, not the update one)
![image](https://github.com/user-attachments/assets/614b48ba-95bf-482a-ad62-d56dbb664086)

2025-03-04 20:47 UTC, jdelpierre approved these changes

2025-03-10 12:56 UTC, smau-centreon approved these changes

2025-03-11 09:13 UTC, merged