[CTOR-1141]-Refresh network-ruggedcom doc page
centreon/centreon-documentation pull request #3814
Opened 2024-11-22 13:52 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-11-22 13:53 UTC, YanMeddour commented
not sure about the prerequisites

2024-11-25 17:12 UTC, cg-tw requested changes

2024-11-25 17:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruggedcom.md
> +| Traffic-Global       | Net-Ruggedcom-Traffic-Global-SNMP-custom       | Contrôle de la bande passante de l'interface. Pour chaque contrôle apparaîtra le nom de l'interface  | X          |
no difference at all

2024-11-25 17:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruggedcom.md
> +| Net-Ruggedcom-SNMP-Traffic-Name | Découvre les interfaces réseau et supervise le statut et l'utilisation |
```suggestion
| Net-Ruggedcom-SNMP-Traffic-Name | Découvre les interfaces réseau et en supervise le statut et l'utilisation |
```

2024-11-25 17:12 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruggedcom.md
> +Le service SNMP doit être activé et configuré sur l'équipement. Veuillez vous référer à la documentation officielle du constructeur/éditeur.
port 161

2024-11-25 17:12 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ruggedcom.md
> +| Memory          | Net-Ruggedcom-Memory-SNMP-custom          | Check the rate of the utilization of memory  |
```suggestion
| Memory          | Net-Ruggedcom-Memory-SNMP-custom          | Check the rate of memory utilization |
```

2024-11-25 17:12 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ruggedcom.md
> +| Traffic-Generic-Id   | Net-Ruggedcom-Traffic-Generic-Id-SNMP-custom   | Check the bandwidth of the interface. For each checks the name of the interface will appear  |            |
```suggestion
| Traffic-Generic-Id   | Net-Ruggedcom-Traffic-Generic-Id-SNMP-custom   | Check the bandwidth of the interface. For each check the name of the interface will appear  |            |
```

2024-11-25 17:12 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ruggedcom.md
> +| Traffic-Generic-Name | Net-Ruggedcom-Traffic-Generic-Name-SNMP-custom | Check the bandwidth of the interface. For each checks the name of the interface will appear  |            |
```suggestion
| Traffic-Generic-Name | Net-Ruggedcom-Traffic-Generic-Name-SNMP-custom | Check the bandwidth of the interface. For each check the name of the interface will appear  |            |
```

2024-11-25 17:12 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ruggedcom.md
> +| Traffic-Global       | Net-Ruggedcom-Traffic-Global-SNMP-custom       | Check the bandwidth of the interface. For each checks the name of the interface will appear  | X          |
```suggestion
| Traffic-Global       | Net-Ruggedcom-Traffic-Global-SNMP-custom       | Check the bandwidth of the interface. For each check the name of the interface will appear  | X          |
```

2024-11-25 17:12 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-ruggedcom.md
> +The SNMP service must be configured and activated on the host. Please refer to the official documentation from the constructor/editor.
port 161

2024-11-26 14:03 UTC, merged