CTOR-1178 : Add unsupported model for hardware-storage-qnap-snmp
centreon/centreon-documentation pull request #3815
Opened 2024-11-22 14:03 UTC by lucie-dubrunfaut

## Description

Add unsupported model for hardware-storage-qnap-snmp
And update the documentation

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-22 14:04 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| Metric name                        | Unit |
```suggestion
| Name                       | Unit |
```

2024-11-26 08:58 UTC, cg-tw requested changes

2024-11-26 08:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +* EKI utilisant le système d'opération QTS
c'est quoi un EKI?

2024-11-26 08:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +* **Uniquement pour le service volume** : LAGMT utilisant le système d'opération QuTS hero (L'information "volume" n'est pas présente dans le fichier MIB du QuTS hero)
```suggestion
* **Uniquement pour le service volume** : LAGMT utilisant le système d'opération QuTS hero (L'information "volume" n'est pas présente dans le fichier MIB du QuTS hero).
```

2024-11-26 08:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +* EKI utilisant le système d'opération QTS
```suggestion
* EKI utilisant le système d'opération QTS.
```

2024-11-26 08:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| HW-Storage-Qnap-SNMP-Disk-Name    | Découvre les partitions du disque et superviser l'occupation de son espace |
```suggestion
| HW-Storage-Qnap-SNMP-Disk-Name    | Découvre les partitions du disque et supervise l'occupation de son espace |
```

2024-11-26 08:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| HW-Storage-Qnap-SNMP-Disk-Name_1  | Découvre les partitions du disque et superviser l'occupation de son espace |
```suggestion
| HW-Storage-Qnap-SNMP-Disk-Name_1  | Découvre les partitions du disque et supervise l'occupation de son espace |
```

2024-11-26 08:58 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| HW-Storage-Qnap-SNMP-Traffic-Name | Découvre les interfaces réseau et supervise le statut et l'utilisation     |
```suggestion
| HW-Storage-Qnap-SNMP-Traffic-Name | Découvre les interfaces réseau et en supervise le statut et l'utilisation     |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +* **Only for volume service** : LAGMT using the QuTS hero operating system (The volume information isn't present in the QuTS hero MIB file)
```suggestion
* **Only for volume service** : LAGMT using the QuTS hero operating system (The volume information isn't present in the QuTS hero MIB file).
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +* EKI using the QTS operating system
```suggestion
* EKI using the QTS operating system.
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| Disk-Global          | HW-Storage-Qnap-Disk-Global-SNMP-custom          | Check the rate of free space on disks. For each checks the mount point of disks will appear  | X          |
```suggestion
| Disk-Global          | HW-Storage-Qnap-Disk-Global-SNMP-custom          | Check the rate of free space on disks. For each check the mount point of disks will appear  | X          |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| Traffic-Generic-Id   | HW-Storage-Qnap-Traffic-Generic-Id-SNMP-custom   | Check traffic of an network interface                                                        |            |
```suggestion
| Traffic-Generic-Id   | HW-Storage-Qnap-Traffic-Generic-Id-SNMP-custom   | Check traffic of a network interface                                                        |            |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| Traffic-Generic-Name | HW-Storage-Qnap-Traffic-Generic-Name-SNMP-custom | Check traffic of an network interface                                                        |            |
```suggestion
| Traffic-Generic-Name | HW-Storage-Qnap-Traffic-Generic-Name-SNMP-custom | Check traffic of a network interface                                                        |            |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| HW-Storage-Qnap-SNMP-Disk-Name_1  | Discover the disk partitions and monitor space occupation     |
what's the difference between name and name_1?

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| CRITICAL     | Critical  threshold average CPU utilization                                                                                            | 90                |             |
```suggestion
| CRITICAL     | Critical threshold for average CPU utilization                                                                                            | 90                |             |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| TRANSFORMDST | Modify the storage name displayed by using a regular expression.  Example: adding --display-transform-src='dev' --display-transform-dst='run'  will replace all occurrences of 'dev' w
```suggestion
| TRANSFORMDST | Modify the storage name displayed by using a regular expression.  Example: adding --display-transform-src='dev' --display-transform-dst='run' will replace all occurrences of 'dev' with 'run' |                   |             |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| TRANSFORMSRC | Modify the storage name displayed by using a regular expression.  Example: adding --display-transform-src='dev' --display-transform-dst='run'  will replace all occurrences of 'dev' w
```suggestion
| TRANSFORMSRC | Modify the storage name displayed by using a regular expression.  Example: adding --display-transform-src='dev' --display-transform-dst='run' will replace all occurrences of 'dev' with 'run' |                   |             |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| INTERFACEID  | Define the interface filter on IDs (OID indexes, e.g.: 1,2,...). If empty, all interfaces will be monitored.  To filter on interface names, see --name |                   |
```suggestion
| INTERFACEID  | Define the interface filter on IDs (OID indexes, e.g.: 1,2,...). If empty, all interfaces will be monitored. To filter on interface names, see --name |                   |             |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| INTERFACENAME | Define the interface filter on IDs (OID indexes, e.g.: 1,2,...). If empty, all interfaces will be monitored.  To filter on interface names, see --name |                   |
```suggestion
| INTERFACENAME | Define the interface filter on IDs (OID indexes, e.g.: 1,2,...). If empty, all interfaces will be monitored. To filter on interface names, see --name |                   |             |
```

2024-11-26 08:58 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| FILTER         | Define the interface filter on IDs (OID indexes, e.g.: 1,2,...). If empty, all interfaces will be monitored.  To filter on interface names, see --name
```suggestion
| FILTER         | Define the interface filter on IDs (OID indexes, e.g.: 1,2,...). If empty, all interfaces will be monitored. To filter on interface names, see --name                                                              | .*                |             |
```

2024-11-26 13:46 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| HW-Storage-Qnap-SNMP-Traffic-Name | Découvre les interfaces réseau et en supervise le statut et l'utilisation     |
```suggestion
| HW-Storage-Qnap-SNMP-Disk-Name    | Découvre les partitions du disque et supervise l'occupation de son espace |
| HW-Storage-Qnap-SNMP-Traffic-Name | Découvre les interfaces réseau et en supervise le statut et l'utilisation     |
```

2024-11-26 13:46 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| HW-Storage-Qnap-SNMP-Disk-Name_1  | Discover the disk partitions and monitor space occupation     |
```suggestion
| HW-Storage-Qnap-SNMP-Disk-Name    | Discover the disk partitions and monitor space occupation     |
```

2024-11-26 13:47 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
> +| HW-Storage-Qnap-SNMP-Disk-Name_1  | Discover the disk partitions and monitor space occupation     |
```suggestion
| HW-Storage-Qnap-SNMP-Disk-Name    | Discover the disk partitions and monitor space occupation     |
```

2024-11-26 14:06 UTC, merged