CTOR-1117 : Update EN version an add a french version for sc-datadog-events
centreon/centreon-documentation pull request #3835
Opened 2024-11-26 10:43 UTC by lucie-dubrunfaut

## Description

- Update EN version 
- Add a french version for sc-datadog-events

## Target version (i.e. version that this PR changes)

- [x] 22.10.x
- [x] 23.04.x
- [x] 23.10.x
- [x] 24.04.x
- [x] 24.10.x
- [x] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-12-10 13:42 UTC, cg-tw requested changes

2024-12-10 13:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +- - Les événements mentionnés ci-dessus sont déclenchés chaque fois qu'un hôte ou un service est contrôlé. Divers paramètres permettent de filtrer les événements.
```suggestion
```

2024-12-10 13:42 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
>  - Aformentioned events are fired each time a host or a service is checked. Various parameters let you filter out events.
```suggestion
```

2024-12-10 13:42 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +You must replace all the *`<xxxx>`* inside the above command with their appropriate value. *<http_server_url>* may become *https://api.datadoghq.com*.
```suggestion
You must replace all the *`<xxxx>`* inside the above command with the correct value. *<http_server_url>* may become *https://api.datadoghq.com*.
```

2025-02-18 14:27 UTC, cg-tw requested changes

2025-02-18 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +| string | api_key | the datadog api key | OGwOM8nse3FHjxyGw5ODLWWXS1oEpcPs |
```suggestion
| string | api_key | the datadog api key | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |
```

2025-02-18 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +   Datadog reçoit maintenant des données de Centreon. Pour tester le bon fonctionnement de l'intégration, voir [Commandes curl : tester le stream connector](#commandes-curl--tester-le-stream-connecto
```suggestion
Datadog reçoit maintenant des données de Centreon. Pour tester le bon fonctionnement de l'intégration, voir [Commandes curl : tester le stream connector](#commandes-curl--tester-le-stream-connector).
```

2025-02-18 14:27 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +## Configuring your Datadog equipment
```suggestion
## Configuring your Datadog server
```

2025-02-18 14:27 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +You may need to configure your Datadog equipment so that it can receive data from Centreon. Please refer to Datadog's documentation.
```suggestion
You may need to configure your Datadog server so that it can receive data from Centreon. Please refer to Datadog's documentation.
```

2025-02-18 14:27 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +Make sure Datadog is able to receive data sent by Centreon: flows must not be blocked by Datadog's configuration or by a security equipment.
```suggestion
Make sure Datadog is able to receive data sent by Centreon: flows must not be blocked by Datadog's configuration or by a security device.
```

2025-02-18 14:27 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +| string | api_key | the datadog api key | OGwOM8nse3FHjxyGw5ODLWWXS1oEpcPs |
```suggestion
| string | api_key | the datadog api key | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |
```

2025-02-18 14:27 UTC, cg-tw commented on versioned_docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +   Datadog should now receive data from Centreon. To test if it is working, see [Curl commands: testing the stream connector](#curl-commands-testing-the-stream-connector).
```suggestion
Datadog should now receive data from Centreon. To test if it is working, see [Curl commands: testing the stream connector](#curl-commands-testing-the-stream-connector).
```

2025-02-19 09:28 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-datadog-events.md
> +| number | log_level | Logging level from 1 (errors) to 3 (debug) | 1                                           |
```suggestion
| string | logfile   | Fichier dans lequel les logs sont écrits         | /var/log/centreon-broker/datadog-events.log |
| number | log_level | Niveau de verbosité des logs : de 1 (erreurs) à 3 (debug) | 1                                           |
```

2025-02-26 09:14 UTC, cg-tw approved these changes

2025-02-26 09:29 UTC, merged