CTOR-1148 : Refresh network-versa-director-restapi
centreon/centreon-documentation pull request #3843
Opened 2024-11-27 10:57 UTC by lucie-dubrunfaut

## Description

Refresh network-versa-director-restapi

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-12-10 15:00 UTC, cg-tw requested changes

2024-12-10 15:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +| Paths | Net-Versa-Director-Paths-Restapi-custom | Contrôle le statut des paths | X          |
```suggestion
| Paths | Net-Versa-Director-Paths-Restapi-custom | Contrôle le statut des chemins | X          |
```

2024-12-10 15:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-versa-director-restapi.md
>  </Tabs>
Référez-vous, pas référencez-vous

2024-12-10 15:00 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +	--api-password='' \
username and password

2024-12-10 15:00 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +	--api-password='' \
username and password

2024-12-11 08:40 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +	--api-password='' \
```suggestion
	--hostname='10.0.0.1' \
	--port='9182' \
	--proto='https' \
	--api-username='XXXX' \
	--api-password='XXXX' \
```

2024-12-11 08:41 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/network-versa-director-restapi.md
> +	--api-password='' \
```suggestion
	--hostname='10.0.0.1' \
	--port='9182' \
	--proto='https' \
	--api-username='XXXX' \
	--api-password='XXXX' \
```

2024-12-17 13:27 UTC, cg-tw submitted a review, later dismissed

2024-12-19 11:05 UTC, cg-tw approved these changes

2024-12-19 11:06 UTC, merged