CTOR-1153 : Refresh cloud-cloudfoundry-api
centreon/centreon-documentation pull request #3848
Opened 2024-11-27 14:41 UTC by lucie-dubrunfaut

## Description

Refresh cloud-cloudfoundry-api

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-11-27 15:20 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Autorisez l'accès sortant vers l'URL de l'API (https://api.<domain>) via les ports nécessaires (généralement 443 pour HTTPS).
```suggestion
Autorisez l'accès sortant vers l'URL de l'API (https://api./<domain/>) via les ports nécessaires (généralement 443 pour HTTPS).
```

2024-12-10 15:19 UTC, cg-tw requested changes

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Les connecteurs de supervision suivants sont automatiquement installés lors de l'installation du connecteur **Cloud Foundry**
```suggestion
Les connecteurs de supervision suivants sont automatiquement installés lors de l'installation du connecteur **Cloud Foundry API** 
```

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Le connecteur de supervision **Cloud Foundry** apporte un modèle d'hôte :
```suggestion
Le connecteur de supervision **Cloud Foundry API** apporte un modèle d'hôte :
```

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Votre collecteur Centreon doit être en mesure d'accéder à votre instance Cloud Foundry (disposer de son url d'hébergement).
```suggestion
* Votre collecteur Centreon doit être en mesure d'accéder à votre instance Cloud Foundry (vous devez disposer de son URL d'hébergement).
```

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Vous devez disposer d'un compte utilisateur Cloud Foundry ayant les permissions nécessaires pour accéder aux données supervisées via l'API (applications, etc.).
```suggestion
* Vous devez également disposer d'un compte utilisateur Cloud Foundry ayant les permissions nécessaires pour accéder aux données supervisées via l'API (applications, etc.). 
```

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Pour plus d'information, référez-vous à la [documentation officielle](https://docs.cloudfoundry.org/)
```suggestion
* Pour plus d'information, référez-vous à la [documentation officielle Cloud Foundry](https://docs.cloudfoundry.org/).
```

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Assurez-vous que le serveur Centreon peut communiquer avec l’API Cloud Foundry via le réseau.
```suggestion
* Assurez-vous que le serveur Centreon peut communiquer avec l’API Cloud Foundry via le réseau. 
```

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Autorisez l'accès sortant vers l'URL de l'API (https://api./<domain/>) via les ports nécessaires (généralement 443 pour HTTPS).
```suggestion
* Autorisez l'accès sortant vers l'URL de l'API (https://api./<domain/>) via les ports nécessaires (généralement 443 pour HTTPS).
```

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +Vérifiez que le certificat SSL de l’API Cloud Foundry est valide et, si nécessaire, ajoutez-le aux certificats approuvés du collecteur Centreon.
```suggestion
* Vérifiez que le certificat SSL de l’API Cloud Foundry est valide et, si nécessaire, ajoutez-le aux certificats approuvés du collecteur Centreon.
```

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +	--hostname='' \
hostname

2024-12-10 15:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +	--api-password='' \
username and password

2024-12-10 15:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +The following monitoring connectors will be installed when you install the **Cloud Foundry** connector through the
```suggestion
The following monitoring connectors will be installed when you install the **Cloud Foundry API** connector through the
```

2024-12-10 15:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +The Monitoring Connector **Cloud Foundry** brings a host template:
```suggestion
The Monitoring Connector **Cloud Foundry API** brings a host template:
```

2024-12-10 15:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +| Apps-State      | Cloud-Cloudfoundry-Apps-State-Api-custom      | Check applications state |
```suggestion
| Apps-State      | Cloud-Cloudfoundry-Apps-State-Api-custom      | Check the state of applications |
```

2024-12-10 15:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +| Instances-State | Cloud-Cloudfoundry-Instances-State-Api-custom | Check instances state    |
```suggestion
| Instances-State | Cloud-Cloudfoundry-Instances-State-Api-custom | Check the state of instances |
```

2024-12-10 15:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +For more informations, refers to the [official documentation](https://docs.cloudfoundry.org/)
```suggestion
* Your Centreon poller must be able to access your Cloud Foundry instance (have its hosting URL ready).
* You must have a Cloud Foundry user account with the necessary permissions to access the data monitored via the API (applications, etc.).
* Ensure that the Centreon server can communicate with the Cloud Foundry API over the network.
* Allow outbound access to the API URL (https://api./<domain/>) through the required ports (typically 443 for HTTPS).
* Check that the Cloud Foundry API's SSL certificate is valid and, if necessary, add it to the trusted certificates of the Centreon poller.
* For more information, refer to the [official Cloud Foundry documentation](https://docs.cloudfoundry.org/)
```

2024-12-10 15:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +	--hostname='' \
hostname

2024-12-10 15:19 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +	--api-password='' \
username and password

2024-12-11 08:31 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +	--api-password='' \
```suggestion
	--hostname='10.0.0.1' \
	--api-path='/v2' \
	--api-username='XXXX' \
	--api-password='XXXX' \
```

2024-12-11 08:32 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
> +	--api-password='' \
```suggestion
	--hostname='10.0.0.1' \
	--api-path='/v2' \
	--api-username='XXXX' \
	--api-password='XXXX' \
```

2024-12-17 13:31 UTC, cg-tw approved these changes

2024-12-17 13:31 UTC, merged