CTOR-1075 : Doc(operatingsystems-linux-snmp) : Add troubleshooting section for snmp uptime issue
centreon/centreon-documentation pull request #3850
Opened 2024-11-27 16:42 UTC by lucie-dubrunfaut

## Description

Add troubleshooting section for snmp uptime issue

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-12-10 15:43 UTC, cg-tw requested changes

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Ainsi l'uptime atteint sa valeur maximale après environ 497 jours d'uptime
```suggestion
Ainsi l'uptime atteint sa valeur maximale après environ 497 jours 
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Vous pouvez identifier que l'uptime a dépassé la limite de 497 en vérifiant directement
```suggestion
Vous pouvez identifier que l'uptime a dépassé la limite de 497 jours en vérifiant directement 
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +sur l'équipement (si c'est possible) son uptime (sans intérroger via SNMP). Par exemple
```suggestion
sur l'équipement (si c'est possible) son uptime (sans interroger via SNMP). Par exemple
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +pour Linux la commande suivante :
```suggestion
pour Linux, utilisez la commande suivante :
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +qui va permettre de gérer le débordement de l'uptime après 497 jours. Pour cela il va utiliser le cache
```suggestion
qui va permettre de gérer le débordement de l'uptime après 497 jours. Pour cela ils vont utiliser le cache
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +fausse alerte vis à vis de l'uptime et l'utilisateur n'a rien à faire de particulier.
```suggestion
fausse alerte vis-à-vis de l'uptime et l'utilisateur n'a rien à faire de particulier.
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +### Si le dépassement a eu lieu mais l'option --check-overload n'était pas dans la commande du plugin
```suggestion
### Si le dépassement a eu lieu mais l'option --check-overload n'était pas présente dans la commande du plugin
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Dans le cas où l'option ` --check-overload` n'était pas dans la commande du plugin avant que le
```suggestion
Dans le cas où l'option ` --check-overload` n'était pas présente dans la commande du plugin avant que le 
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +dépassement ait lieu, il est possible de corriger la situation avec la démarche suivante :
```suggestion
dépassement ait lieu, il est possible de corriger la situation de la façon suivante : 
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +Vous pouvez ensuite relancer la commande du plugin avec l'option ` --check-overload` et le
```suggestion
Vous pouvez ensuite relancer la commande du plugin avec l'option ` --check-overload` : le 
```

2024-12-10 15:43 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
> +### Uptime issue
```suggestion
### Problème d'uptime
```

2024-12-17 13:36 UTC, cg-tw approved these changes

2024-12-17 14:44 UTC, omercier approved these changes

2024-12-17 14:46 UTC, merged