add explanation of the . wildcard feature for curve definition
centreon/centreon-documentation pull request #3851
Opened 2024-11-28 10:58 UTC by emgcentreon

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-12-12 09:18 UTC, cg-tw requested changes

2024-12-12 09:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-12 09:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-12 09:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-12 09:18 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-12 09:18 UTC, cg-tw commented on versioned_docs/version-23.04/metrology/chart_curves.md
> +  list can be used to choose the already existing metrics used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to many curves with a simi
```suggestion
  list can be used to choose the already existing metrics used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to several curves with a similar name. For example, if you have DataSource-Name1 and DataSource-Name2, writing DataSource-. here will apply the settings to all curves with a name that starts with "DataSource-".
```

2024-12-12 09:18 UTC, cg-tw commented on versioned_docs/version-23.10/metrology/chart_curves.md
> +  list can be used to choose the existing metrics already used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to many curves with a simi
```suggestion
  list can be used to choose the existing metrics already used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to several curves with a similar name. For example, if you have DataSource-Name1 and DataSource-Name2, writing DataSource-. here will apply the settings to all curves with a name that starts with "DataSource-".
```

2024-12-12 09:18 UTC, cg-tw commented on versioned_docs/version-24.04/metrology/chart_curves.md
> +  list can be used to choose the existing metrics already used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to many curves with a simi
```suggestion
  list can be used to choose the existing metrics already used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to several curves with a similar name. For example, if you have DataSource-Name1 and DataSource-Name2, writing DataSource-. here will apply the settings to all curves with a name that starts with "DataSource-".
```

2024-12-12 09:18 UTC, cg-tw commented on versioned_docs/version-24.10/metrology/chart_curves.md
> +  list can be used to choose the existing metrics already used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to many curves with a simi
```suggestion
  list can be used to choose the existing metrics already used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to several curves with a similar name. For example, if you have DataSource-Name1 and DataSource-Name2, writing DataSource-. here will apply the settings to all curves with a name that starts with "DataSource-".
```

2024-12-12 09:18 UTC, cg-tw commented on versioned_docs/version-25.10/metrology/chart_curves.md
> +  list can be used to choose the existing metrics already used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to many curves with a simi
```suggestion
  list can be used to choose the existing metrics already used by the services. If you wish to reuse a definition for other curves, you can use the wildcard "." to apply it to several curves with a similar name. For example, if you have DataSource-Name1 and DataSource-Name2, writing DataSource-. here will apply the settings to all curves with a name that starts with "DataSource-".
```

2024-12-16 10:19 UTC, cg-tw requested changes

2024-12-16 10:19 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autres courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-17 10:14 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une définition pour d'autres courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-17 10:14 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une définition pour d'autres courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-17 10:14 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une définition pour d'autres courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-17 10:14 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autres courbes, vous pouvez utiliser un point
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une définition pour d'autres courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2024-12-17 10:14 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/metrology/chart_curves.md
> +  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une défition pour d'autre courbes, vous pouvez utiliser un point "
```suggestion
  **List of known metrics** permet de choisir les métriques déjà existantes utilisées par les services. Si vous souhaitez réutiliser une définition pour d'autres courbes, vous pouvez utiliser un point "." comme joker dans le nom. Par exemple, si vous avez DataSource-Nom1 et DataSource-Nom2, vous pouvez écrire ici DataSource-. pour appliquer les mêmes réglages à toutes les courbes dont le nom commence par "DataSource-".
```

2025-01-06 16:07 UTC, cg-tw approved these changes

2025-01-13 08:58 UTC, merged