CTOR-1022 : Pack(operatingsystems-windows-centreon-monitoring-agent) : Add Natives checks
centreon/centreon-documentation pull request #3868
Opened 2024-12-03 09:44 UTC by lucie-dubrunfaut

## Description

Add Natives checks :
- CPU
- CPU detailed
- Memory
- Storage
- Swap
- Uptime

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2024-12-05 13:27 UTC, cg-tw requested changes

2024-12-05 13:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| Memory         | OS-Windows-Memory-Centreon-Monitoring-Agent-custom         | Contrôle le du taux d'utilisation de la mémoire
```suggestion
| Memory         | OS-Windows-Memory-Centreon-Monitoring-Agent-custom         | Contrôle du taux d'utilisation de la mémoire                                                                                                                           |
```

2024-12-05 15:09 UTC, cg-tw approved these changes

2024-12-05 16:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS    | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
```

2024-12-05 16:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS          | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
```

2024-12-05 16:01 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS          | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
```

2024-12-05 16:02 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
```

2024-12-05 16:02 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS    | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |                   |             |
```suggestion
```

2024-12-05 16:02 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS    | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |               |           |
```suggestion
```

2024-12-05 16:02 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS          | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |               |           |
```suggestion
```

2024-12-05 16:03 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS          | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |               |           |
```suggestion
```

2024-12-05 16:03 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS      | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles)
```suggestion
```

2024-12-05 16:03 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS         | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |               |           |
```suggestion
```

2024-12-05 16:03 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| EXTRAOPTIONS   | Any extra option you may want to add to the command (E.g. a --verbose flag). Toutes les options sont listées [ici](#options-disponibles) |               |           |
```suggestion
```

2024-12-05 16:18 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| CRITICALUPTIME | Critical threshold                                                                                                                       |               |           |
```suggestion
| WARNINGUPTIME  | Warning threshold, if computer has been up for less than this time, service will be in warning state                                     | 3600          |           |
| CRITICALUPTIME | Critical threshold                                                                                                                       |               | 600       |
```

2024-12-05 16:19 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
> +| FILTERFS          | Case insensitive regex to filter filesystem. Example: [C-D]:\\.*
```suggestion
| WARNING           | Thresholds                                                                                                                                                                                                                                                                                     | 80            |           |
| CRITICAL          | Thresholds                                                                                                                                                                                                                                                                                     | 90            |           |
| FILTERSTORAGETYPE | Case insensitive regex to filter storage type it includes drive type (fixed, network...). Types recognized by agent: hrunknown, hrstoragefixeddisk, hrstorageremovabledisk, hrstoragecompactdisc, hrstorageramdisk, hrstoragenetworkdisk, hrfsunknown, hrfsfat, hrfsntfs, hrfsfat32, hrfsexfat | .*            |           |
| FILTERFS          | Case insensitive regex to filter filesystem. Example: [C-D]:\\.*                                                                                                                                                                                                                               | .*            |           |
```

2024-12-06 16:12 UTC, cg-tw approved these changes

2024-12-06 16:13 UTC, merged