CTOR-533 : Plugin(storage::netapp::ontap::snmp): Add uptime packaging - Fix Disk-Failed command - Enhance documenation page
centreon/centreon-documentation pull request #3906
Opened 2024-12-17 11:12 UTC by lucie-dubrunfaut

## Description

Update documentation

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2025-01-06 16:29 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +
```suggestion

> Le plugin actuel n'est pas totalement compatible avec les versions d'équipement supérieures à 8.2.5. Vous pouvez voter pour son amélioration sur cette idée [TheWatch](https://thewatch.centreon.com/ideas/mise-a-jour-plugin-pack-netapp-ontap-snmp-3571).

```

2025-01-06 16:30 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +
@cg-tw Dis moi si ça te convient comme message de compatibilité

2025-01-06 16:30 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +
```suggestion

> The current plugin is not fully compatible with equipment versions higher than 8.2.5. You can vote for its improvement on this idea [TheWatch](https://thewatch.centreon.com/ideas/mise-a-jour-plugin-pack-netapp-ontap-snmp-3571).

```

2025-01-09 10:53 UTC, cg-tw requested changes

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Cache-Age     | HW-Storage-NetApp-Ontap-Cache-Age-SNMP-custom     | Contrôle en minutes le dernier bloc en lecture-seul dans le 'cache buffer' |
```suggestion
| Cache-Age     | HW-Storage-NetApp-Ontap-Cache-Age-SNMP-custom     | Contrôle l'âge en minutes du dernier bloc en lecture seule dans le 'cache buffer' |
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Psu                    | HW-Storage-NetApp-Ontap-Psu-SNMP-custom                    | Contrôle le status de l'alimentation éléctrique          |            |
```suggestion
| Psu                    | HW-Storage-NetApp-Ontap-Psu-SNMP-custom                    | Contrôle le statut de l'alimentation électrique          |            |
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Partner-Status         | HW-Storage-NetApp-Ontap-Partner-Status-SNMP-custom         | Contrôle le status du failover                           |            |
```suggestion
| Partner-Status         | HW-Storage-NetApp-Ontap-Partner-Status-SNMP-custom         | Contrôle le statut du failover                           |            |
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Global-status | HW-Storage-NetApp-Ontap-Global-status-SNMP-custom | Contrôle le status global du NetApp                                        |
```suggestion
| Global-status | HW-Storage-NetApp-Ontap-Global-status-SNMP-custom | Contrôle le statut global du NetApp                                        |
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Nvram         | HW-Storage-NetApp-Ontap-Nvram-SNMP-custom         | Contrôle le status de la NVRAM                                             |
```suggestion
| Nvram         | HW-Storage-NetApp-Ontap-Nvram-SNMP-custom         | Contrôle le statut de la NVRAM                                             |
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Share-Calls            | HW-Storage-NetApp-Ontap-Share-Calls-SNMP-custom            | Contrôle le nombre d'appels 'CIFS' et 'NFS' par secondes |            |
```suggestion
| Share-Calls            | HW-Storage-NetApp-Ontap-Share-Calls-SNMP-custom            | Contrôle le nombre d'appels 'CIFS' et 'NFS' par seconde |            |
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Temperature            | HW-Storage-NetApp-Ontap-Temperature-SNMP-custom            | Contrôle la temperature du materiel                      |            |
```suggestion
| Temperature            | HW-Storage-NetApp-Ontap-Temperature-SNMP-custom            | Contrôle la température du materiel                      |            |
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +Pas de métrique pour ce service
```suggestion
Pas de métrique pour ce service.
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +Pas de métrique pour ce service
```suggestion
Pas de métrique pour ce service.
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +Pas de métrique pour ce service
```suggestion
Pas de métrique pour ce service.
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +
@lucie-dubrunfaut ça va

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Disk-Failed   | HW-Storage-NetApp-Ontap-Disk-Failed-SNMP-custom   | Check the current number of disk broken                                  |
```suggestion
| Disk-Failed   | HW-Storage-NetApp-Ontap-Disk-Failed-SNMP-custom   | Check the current number of malfunctioning disks                                  |
```

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Nvram         | HW-Storage-NetApp-Ontap-Nvram-SNMP-custom         | Check current status of the NVRAM batteries                              |
```suggestion
| Nvram         | HW-Storage-NetApp-Ontap-Nvram-SNMP-custom         | Check the current status of the NVRAM batteries                              |
```

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Fan                    | HW-Storage-NetApp-Ontap-Fan-SNMP-custom                    | Check if fans are failed                                                              |           |
```suggestion
| Fan                    | HW-Storage-NetApp-Ontap-Fan-SNMP-custom                    | Check if fans have failed                                                              |           |
```

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Ndmpsessions           | HW-Storage-NetApp-Ontap-Ndmpsessions-SNMP-custom           | Check current total of ndmp sessions opened                                           |           |
```suggestion
| Ndmpsessions           | HW-Storage-NetApp-Ontap-Ndmpsessions-SNMP-custom           | Check current total of open NDMP sessions                                           |           |
```

2025-01-09 10:53 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Ndmpsessions           | HW-Storage-NetApp-Ontap-Ndmpsessions-SNMP-custom           | Contrôle le nombre de sessions ndmp                      |            |
```suggestion
| Ndmpsessions           | HW-Storage-NetApp-Ontap-Ndmpsessions-SNMP-custom           | Contrôle le nombre de sessions NDMP                      |            |
```

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Psu                    | HW-Storage-NetApp-Ontap-Psu-SNMP-custom                    | Check if power supplies are failed                                                    |           |
```suggestion
| Psu                    | HW-Storage-NetApp-Ontap-Psu-SNMP-custom                    | Check if power supplies have failed                                                    |           |
```

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Share-Calls            | HW-Storage-NetApp-Ontap-Share-Calls-SNMP-custom            | Check cifs and nfs calls per seconds.                                                 |           |
```suggestion
| Share-Calls            | HW-Storage-NetApp-Ontap-Share-Calls-SNMP-custom            | Check CIFS and NFS calls per second.                                                 |           |
```

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Snapshot-Age-Global    | HW-Storage-NetApp-Ontap-Snapshot-Age-Global-SNMP-custom    | Check snapshot age of volumes                                                         |           |
```suggestion
| Snapshot-Age-Global    | HW-Storage-NetApp-Ontap-Snapshot-Age-Global-SNMP-custom    | Check the age of volume snapshots |           |
```

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Snapshot-Age-Name      | HW-Storage-NetApp-Ontap-Snapshot-Age-Name-SNMP-custom      | Check snapshot age of volumes                                                         |           |
```suggestion
| Snapshot-Age-Name      | HW-Storage-NetApp-Ontap-Snapshot-Age-Name-SNMP-custom      | Check the age of volume snapshots                                                         |           |
```

2025-01-09 10:53 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
> +| Net-Netapp-Ontap-SNMP-Disk-Name         | Discover disk broken and monitor them   |
```suggestion
| Net-Netapp-Ontap-SNMP-Disk-Name         | Discover malfunctioning disks and monitor them   |
```

2025-01-13 12:38 UTC, cg-tw approved these changes

2025-01-13 15:04 UTC, merged