Replace central server by user interface or SaaS platform
centreon/centreon-documentation pull request #3909
Opened 2024-12-17 16:07 UTC by emgcentreon

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [X] Cloud
- [ ] Monitoring Connectors

2024-12-23 12:56 UTC, emgcentreon commented on cloud/getting-started/platform.md
> +2. Wait while your [platform](architecture.md) is being built.
review

2024-12-23 16:04 UTC, emgcentreon commented
l'entrée du glossaire Poller dit
Un collecteur est un serveur de supervision installé dans votre infrastructure, qui supervise vos ressources. Un collecteur est rattaché à un serveur central.
Un collecteur Centreon supervise des ressources. Il possède un moteur de supervision.
Il n’a pas d’interface graphique : les ressources qu’il supervise s’affichent dans l’interface du serveur central auquel il est rattaché.
**On appelle aussi “collecteur” le moteur de supervision présent dans un serveur central ou un collecteur.**
Cela me semble déroutant en soi et le devient encore plus si l'on supprime serveur central car la phrase devient "un collecteur est aussi présent dans les collecteurs"

J'ai opté pour supprimer complétement cette dernière phrase

2024-12-23 16:21 UTC, emgcentreon commented
J'ai modifié quelques "serveur central" par "poller central". Ils sont utilisés comme synonymes quelques fois et je crois que l'utilisateur a besoin de savoir que le poller central existe, notamment parce que s'il le supprime, Centreon cesse de fonctionner.
La page de doc [supprimer un collecteur](https://docs.centreon.com/fr/cloud/installation/poller-remove/) dit que "Nous sommes en train de mettre en place des mesures de sécurité pour empêcher la suppression accidentelle du central."

Tant que ces mesures ne sont pas en place, je pense que l'utilisateur devrait être au courant de l'existence du poller central

2025-01-14 15:32 UTC, emgcentreon commented on cloud/getting-started/interface.md
> +* whether all pollers are running or not: the icon becomes red when a poller has not sent data to the platform for at least 15 minutes
```suggestion
* whether all pollers are running or not: the icon becomes red when a poller has not sent data to the SaaS platform for at least 15 minutes
```

2025-01-14 15:32 UTC, emgcentreon commented on cloud/getting-started/platform.md
> +2. Wait while your [platform](architecture.md) is being built.
```suggestion
2. Wait while your [SaaS platform](architecture.md) is being built.
```

2025-01-15 10:30 UTC, emgcentreon commented on cloud/getting-started/architecture.md
> +Centreon Cloud consists mainly of a user interface provided by Centreon, and pollers that you install in your infrastructure. In addition, the Centreon [CIAM](../ciam/ciam.md) module allows you to ma
```suggestion
Centreon Cloud consists mainly of a SaaS platform provided by Centreon, and pollers that you install in your infrastructure. In addition, the Centreon [CIAM](../ciam/ciam.md) module allows you to manage organizations and users, and to log in to Centreon Cloud.
```

2025-01-15 12:54 UTC, emgcentreon commented on cloud/getting-started/interface.md
> +## Accessing the Centreon interface
```suggestion
## Accessing the user interface
```

2025-01-15 12:54 UTC, emgcentreon commented on cloud/installation/deploy-poller.md
> +With Centreon Cloud, your user interface is already ready to use. All you have to do is to install pollers in your infrastructure, and that is very easy: just execute a script and then export the con
```suggestion
With Centreon Cloud, your SaaS platform is already ready to use. All you have to do is to install pollers in your infrastructure, and that is very easy: just execute a script and then export the configuration, and there you are!
```

2025-01-15 12:54 UTC, emgcentreon commented on cloud/installation/deploy-poller.md
> +   * The address in the **IP Address** column is that of the poller as seen by the platform.
```suggestion
   * The address in the **IP Address** column is that of the poller as seen by the SaaS platform.
```

2025-01-15 12:54 UTC, emgcentreon commented on cloud/installation/poller-update-upgrade.md
> +1. On your user interface, click the arrow next to **Pollers** at the left of the header bar.
procédure incomplète ou obsolète

2025-01-15 14:24 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/platform.md
> +2. Patientez pendant que votre [plateforme SaaS](architecture.md) est généré.
```suggestion
2. Patientez pendant que votre [plateforme SaaS](architecture.md) est générée.
```

2025-01-15 14:24 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/architecture.md
> +  * Centreon installe et met à jour La plateforme SaaS.
```suggestion
  * Centreon installe et met à jour la plateforme SaaS.
```

2025-01-15 14:24 UTC, emgcentreon commented on cloud/monitoring/monitoring-servers/deploying-a-configuration.md
> +      - **Restart**: when you have made changes to the way a poller and the SaaS server communicate together, or
```suggestion
      - **Restart**: when you have made changes to the way a poller and the SaaS platform communicate together, or 
```

2025-01-15 14:24 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/monitoring-servers/deploying-a-configuration.md
> +automatique (ni sur le poller sur que vous avez modifié, ni sur aucun collecteur qui en dépendrait). Pour que les modifications soient prises en compte, il est nécessaire d'exporter la configuration.
```suggestion
automatique (ni sur le collecteur central, ni sur aucun collecteur ou serveur distant qui en dépendrait). Pour que les modifications soient prises en compte, il est nécessaire d'exporter la configuration.
```

2025-01-15 14:24 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/glossary.md
> +Dans Centreon, l'interface utilisateur est la console principale de votre supervision. Il permet :
```suggestion
Dans Centreon, l'interface utilisateur est la console principale de votre supervision. Elle permet :
```

2025-01-15 14:24 UTC, emgcentreon commented on cloud/resources/glossary.md
> +Centreon Engine is present on [pollers](#poller) and the [SaaS platform](#SaaS-platform).
```suggestion
Centreon Engine is present on the [pollers](#poller) and the SaaS platform.
```

2025-01-15 14:24 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/glossary.md
> +Un collecteur est un serveur de supervision installé dans votre infrastructure, qui supervise vos resources. Un collecteur est rattaché à un [interface utilisateur](#interface-utilisateur).
```suggestion
Un collecteur est un serveur de supervision installé dans votre infrastructure, qui supervise vos ressources. Un collecteur est rattaché à une plateforme SaaS.
```

2025-01-15 14:24 UTC, emgcentreon commented on cloud/resources/glossary.md
> +A poller is a monitoring server installed in your infrastructure to monitor your resources. A poller is attached to the [SaaS platform](#SaaS-platform).
```suggestion
A poller is a monitoring server installed in your infrastructure to monitor your resources. A poller is attached to the SaaS platform.
```

2025-01-15 14:24 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/glossary.md
> +On appelle aussi “collecteur” le moteur de supervision présent dans un collecteur central ou un collecteur.
```suggestion
```

2025-01-15 14:24 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/glossary.md
> +- Il n’a pas d’interface graphique : les ressources qu’il supervise s’affichent dans l’interface du collecteur central ou du serveur distant auquel il est rattaché.
```suggestion
- Il n’a pas d’interface graphique : les ressources qu’il supervise s’affichent dans l’interface utilisateur.
```

2025-01-15 14:50 UTC, emgcentreon commented on cloud/service-mapping/ba-monitoring.md
> +configuration files, and push them to the SaaS platform.
```suggestion
configuration files, and push them to the **Central** poller.
```

2025-01-15 14:50 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/monitoring-servers/deploying-a-configuration.md
> +      - **Redémarrer** : lorsque vous avez apporté des changements à la communication entre un collecteur et le collecteur central, ou à la configuration du moteur de collecte. Un redémarrage prend p
```suggestion
      - **Redémarrer** : lorsque vous avez apporté des changements à la communication entre un collecteur et la plateforme SaaS, ou à la configuration du moteur de collecte. Un redémarrage prend plus de temps qu'un rechargement.
```

2025-01-15 14:50 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/glossary.md
> +Il est présent sur les [collecteurs](#collecteur) et les [serveur distants](#serveur-distant).
```suggestion
Il est présent sur les [collecteurs](#collecteur) et la plateforme SaaS.
```

2025-01-20 12:24 UTC, cg-tw requested changes

2025-01-20 12:24 UTC, cg-tw commented on cloud/getting-started/architecture.md
> +* Centreon installs and upgrades SaaS platform.
```suggestion
* Centreon installs and upgrades your SaaS platform.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/getting-started/architecture.md
> +* Pollers do not have a user interface (you see the pollers' activity on the user interface).
```suggestion
* Pollers do not have an individual user interface (you see the pollers' activity on the SaaS platform's user interface).
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/getting-started/architecture.md
> +* The [CIAM](../ciam/ciam.md) has a user interface that is separate from the SaaS platform.
```suggestion
* The [CIAM](../ciam/ciam.md) has a user interface that is separate from the SaaS platform's.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/installation/deploy-poller.md
> +1. On the user interface, go to **Configuration > Pollers > Pollers**, then select the poller you have just created.
```suggestion
1. In the user interface, go to **Configuration > Pollers > Pollers**, then select the poller you have just created.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/installation/poller-remove.md
> +4. [Deploy the configuration](../monitoring/monitoring-servers/deploying-a-configuration.md) for the SaaS platform. The poller is removed for good. This cannot be undone.
yeah but this is the one place where they will see "central"

2025-01-20 12:24 UTC, cg-tw commented on cloud/installation/poller-update-upgrade.md
> +1. On your user interface, click the arrow next to **Pollers** at the left of the header bar.
```suggestion
1. In your user interface, click the arrow next to **Pollers** at the left of the header bar.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/monitoring/monitoring-servers/deploying-a-configuration.md
> +When you create, delete or edit objects in the **Configuration** menu, changes are not applied automatically (either on the central poller on which you have made the change or on any remote server or
```suggestion
When you create, delete or edit objects in the **Configuration** menu, changes are not applied automatically. For the changes to be taken into account, you must deploy the configuration.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/monitoring/monitoring-servers/deploying-a-configuration.md
>  1. Go to the **Configuration > Pollers > Pollers** page. The page shows the state of your central
```suggestion
1. Go to the **Configuration > Pollers > Pollers** page. The page shows the state of your SaaS platform (**Central** poller)
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/monitoring/monitoring-servers/deploying-a-configuration.md
> +poller and of all pollers linked to it: changes are shown in the **Conf changed** column.
```suggestion
and of all pollers linked to it: changes are shown in the **Conf changed** column.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/installation/poller-remove.md
> +4. [Deploy the configuration](../monitoring/monitoring-servers/deploying-a-configuration.md) for the SaaS platform. The poller is removed for good. This cannot be undone.
```suggestion
4. [Deploy the configuration](../monitoring/monitoring-servers/deploying-a-configuration.md) for the SaaS platform (**Central** poller). The poller is removed for good. This cannot be undone.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/monitoring/pluginpacks.md
> +fine-tuned later on). If you want to use a pack, you must install it on the user interface.
```suggestion
fine-tuned later on). If you want to use a pack, you must install it through the user interface.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/resources/glossary.md
> +- A poller has no graphical interface: the resources it monitors are displayed in the user interface.
```suggestion
- A poller has no graphical interface: the resources it monitors are displayed in the SaaS platform's user interface.
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/resources/known-issues.md
> +* It is not possible yet to define a default poller. When you create a host, make sure you define the correct poller to monitor it instead of the central poller.
```suggestion
* It is not possible yet to define a default poller. When you create a host, make sure you define the correct poller to monitor it instead of the SaaS platform itself (**Central** poller).
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/service-mapping/ba-monitoring.md
> +configuration files, and push them to the **Central** poller.
```suggestion
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/service-mapping/ba-monitoring.md
>  linked to Centreon BAM, go to **Configuration > Poller**, generate the
```suggestion
linked to Centreon BAM, go to **Configuration > Poller** and [deploy the configuration](../monitoring/monitoring-servers/deploying-a-configuration.md).
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/architecture.md
> +  * Les collecteurs n'ont pas d'interface utilisateur (l'activité des pollers est visible sur l'interface utilisateur).
```suggestion
  * Les collecteurs eux-mêmes n'ont pas d'interface utilisateur (l'activité des collecteurs est visible sur l'interface utilisateur de la plateforme SaaS).
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
> +4. [Sur votre interface utilisateur](../getting-started/interface.md#accéder-à-linterface-du-serveur-central), cliquez sur la flèche à côté de **Collecteurs** dans le bandeau en haut à gauche.
```suggestion
4. [Dans votre interface utilisateur](../getting-started/interface.md#accéder-à-linterface-du-serveur-central), cliquez sur la flèche à côté de **Collecteurs** dans le bandeau en haut à gauche.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
> +7. Une fois le script exécuté, sur l'interface utilisateur, allez à la page **Configuration > Collecteurs > Collecteurs**. Le nouveau collecteur apparaît dans la liste des collecteurs.
```suggestion
7. Une fois le script exécuté, dans l'interface utilisateur, allez à la page **Configuration > Collecteurs > Collecteurs**. Le nouveau collecteur apparaît dans la liste des collecteurs.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
> +1. Sur l'interface utilisateur, allez à la page **Configuration > Collecteurs > Collecteurs**, puis sélectionnez le collecteur que vous venez de créer.
```suggestion
1. Dans l'interface utilisateur, allez à la page **Configuration > Collecteurs > Collecteurs**, puis sélectionnez le collecteur que vous venez de créer.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-remove.md
> +> Pour assurer la stabilité et l'intégrité de votre environnement de supervision, ne supprimez pas le poller central. Le poller central joue un rôle crucial dans le fonctionnement global de la platef
```suggestion
> Pour assurer la stabilité et l'intégrité de votre environnement de supervision, ne supprimez pas le collecteur **Central**. Celui-ci joue un rôle crucial dans le fonctionnement global de la plateforme Centreon. Le supprimer peut entraîner des interruptions de service imprévues et une perte de données. Nous sommes en train de mettre en place des mesures de sécurité pour empêcher la suppression accidentelle du collecteur **Central**.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-remove.md
> +4. [Déployez la configuration](../monitoring/monitoring-servers/deploying-a-configuration.md) pour la plateforme SaaS. Le collecteur est supprimé pour de bon : cette action est irréversible.
```suggestion
4. [Déployez la configuration](../monitoring/monitoring-servers/deploying-a-configuration.md) pour la plateforme SaaS (collecteur **Central**). Le collecteur est supprimé pour de bon : cette action est irréversible.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-update-upgrade.md
> +1. [Sur votre interface utilisateur](../getting-started/interface.md#accéder-à-linterface-du-serveur-central), cliquez sur la flèche à côté de **Collecteurs** dans le bandeau en haut à gauche.
```suggestion
1. [Dans votre interface utilisateur](../getting-started/interface.md#accéder-à-linterface-du-serveur-central), cliquez sur la flèche à côté de **Collecteurs** dans le bandeau en haut à gauche.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/monitoring-servers/deploying-a-configuration.md
> +automatique (ni sur le collecteur central, ni sur aucun collecteur ou serveur distant qui en dépendrait). Pour que les modifications soient prises en compte, il est nécessaire d'exporter la configura
```suggestion
automatique. Pour que les modifications soient prises en compte, il est nécessaire d'exporter la configuration.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/monitoring-servers/deploying-a-configuration.md
> +1. Allez à la page **Configuration > Collecteurs > Collecteurs**. La page affiche l'état de votre collecteur central et de tous les collecteurs qui y sont reliés : les changements sont signalés dans
```suggestion
1. Allez à la page **Configuration > Collecteurs > Collecteurs**. La page affiche l'état de votre plateforme SaaS (collecteur **Central**) et de tous les collecteurs qui y sont reliés : les changements sont signalés dans la colonne **Changement de configuration**.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/glossary.md
> +- Il n’a pas d’interface graphique : les ressources qu’il supervise s’affichent dans l’interface utilisateur.
```suggestion
- Il n’a pas d’interface graphique : les ressources qu’il supervise s’affichent dans l’interface utilisateur de la plateforme SaaS.
```

2025-01-20 12:24 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/known-issues.md
> +* Il n'est pas encore possible de définir un collecteur par défaut. Lorsque vous créez un hôte, assurez-vous de définir le bon collecteur pour le superviser au lieu du collecteur central.
```suggestion
* Il n'est pas encore possible de définir un collecteur par défaut. Lorsque vous créez un hôte, assurez-vous de définir le bon collecteur pour le superviser au lieu de la plateforme SaaS elle-même (collecteur **Central**).
```

2025-01-20 12:24 UTC, cg-tw commented on cloud/installation/poller-remove.md
> +> In order to ensure the stability and integrity of your monitoring environment, do not delete the "Central" poller. This poller plays a critical role in the overall operation of the Centreon platfor
```suggestion
> In order to ensure the stability and integrity of your monitoring environment, do not delete the **Central** poller. This poller plays a critical role in the overall operation of the Centreon platform. Removing it can lead to unintended disruptions in service. We are in the process of implementing safeguards to prevent the accidental deletion of the **Central** poller.
```

2025-01-20 13:34 UTC, cg-tw approved these changes

2025-01-20 13:35 UTC, merged