doc(Release) Release notes for web 23.10.19
centreon/centreon-documentation pull request #3926
Opened 2024-12-20 09:25 UTC by pkippes

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2024-12-20 13:01 UTC, cg-tw requested changes

2024-12-20 13:01 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
> +- [Authentication] Fixed SSO authentication when user have a legacy page as default page with SAML protocol.
```suggestion
- [Authentication] Fixed an issue with SSO authentication with SAML that occurred when users had a legacy page as default page.
```

2024-12-20 13:01 UTC, cg-tw commented on versioned_docs/version-23.10/releases/centreon-os.mdx
> +- [Authentication] Fixed SSO authentication when user have a legacy page as default page with SAML protocol.
```suggestion
- [Authentication] Fixed an issue with SSO authentication with SAML that occurred when users had a legacy page as default page.
```

2024-12-20 13:01 UTC, cg-tw approved these changes

2025-01-09 15:53 UTC, rsadik-ext approved these changes

2025-01-09 16:45 UTC, merged