update description in step 6 of finalizing the upgrade
centreon/centreon-documentation pull request #3932
Opened 2024-12-20 14:49 UTC by emgcentreon

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2025-01-13 10:06 UTC, cg-tw requested changes

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-10.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-10.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-23-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-10.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-10.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-22-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-22-10.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-10.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-24-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-22-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-22-10.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-23-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 10:06 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-23-10.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-24-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-23-10.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-23-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-22-10.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-25.10/upgrade/upgrade-from-22-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-24-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-23-10.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-23-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-22-10.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.10/upgrade/upgrade-from-22-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.04/upgrade/upgrade-from-23-10.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.04/upgrade/upgrade-from-23-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.04/upgrade/upgrade-from-22-10.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-24.04/upgrade/upgrade-from-22-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-23.10/upgrade/upgrade-from-23-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-23.10/upgrade/upgrade-from-22-10.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on versioned_docs/version-23.10/upgrade/upgrade-from-22-04.md
> +Add the apache user to the centreon-broker group and vice versa.
```suggestion
Add the **apache** user to the **centreon-broker** group and vice versa.
```

2025-01-13 12:59 UTC, emgcentreon commented on i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-24-04.md
> +Ajoutez l'utilisateur apache au groupe centreon-broker et vice versa.
```suggestion
Ajoutez l'utilisateur **apache** au groupe **centreon-broker** et vice versa.
```

2025-01-16 15:03 UTC, cg-tw approved these changes

2025-01-20 09:01 UTC, merged