CTOR-1259: Refresh hardware-servers-hp-ilo-restapi
centreon/centreon-documentation pull request #3939
Opened 2024-12-23 16:19 UTC by lucie-dubrunfaut

## Description

Update documentation

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [x] Monitoring Connectors

2025-01-22 10:59 UTC, cg-tw requested changes

2025-01-22 10:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
>  title: HP Ilo Rest API
```suggestion
title: HP iLO Rest API
```

2025-01-22 10:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +Les connecteurs de supervision suivants sont automatiquement installés lors de l'installation du connecteur **HP Ilo Rest API**
```suggestion
Les connecteurs de supervision suivants sont automatiquement installés lors de l'installation du connecteur **HP iLO Rest API** 
```

2025-01-22 10:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +Le connecteur de supervision **HP Ilo Rest API** apporte un modèle d'hôte :
```suggestion
Le connecteur de supervision **HP iLO Rest API** apporte un modèle d'hôte :
```

2025-01-22 10:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +### Configuration réseau :
```suggestion
### Configuration réseau :

```

2025-01-22 10:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +	--api-password=''  \
username and password

2025-01-22 10:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +```bash
no output

2025-01-22 10:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
>  title: HP Ilo Rest API
```suggestion
title: HP iLO Rest API
```

2025-01-22 10:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +The following monitoring connectors will be installed when you install the **HP Ilo Rest API** connector through the
```suggestion
The following monitoring connectors will be installed when you install the **HP iLO Rest API** connector through the
```

2025-01-22 10:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +The Monitoring Connector **HP Ilo Rest API** brings a host template:
```suggestion
The Monitoring Connector **HP iLO Rest API** brings a host template:
```

2025-01-22 10:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +  * Verify that REST access is enabled and that the necessary ports (default is 443) are open.
```suggestion
  * Verify that REST access is enabled and that the necessary ports are open (default is 443). 
```

2025-01-22 10:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +2. Whatever the license type (*online* or *offline*), install the **HP Ilo Rest API** connector through
```suggestion
2. Whatever the license type (*online* or *offline*), install the **HP iLO Rest API** connector through
```

2025-01-22 10:59 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +2. Quel que soit le type de la licence (*online* ou *offline*), installez le connecteur **HP Ilo Rest API**
```suggestion
2. Quel que soit le type de la licence (*online* ou *offline*), installez le connecteur **HP iLO Rest API**
```

2025-01-22 10:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +	--api-password=''  \
username and password

2025-01-22 10:59 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +```
no output

2025-01-28 13:16 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +	--api-password=''  \
```suggestion
	--api-username='XXXX' \
	--api-password='XXXX'  \
```

2025-01-28 13:16 UTC, lucie-tirand commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +	--api-password=''  \
```suggestion
	--api-username='XXXX' \
	--api-password='XXXX'  \
```

2025-02-04 13:05 UTC, lucie-dubrunfaut commented
Blocked : Waiting for plugin output

2025-04-18 13:16 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +OK:
```suggestion
WARNING: Device 'chassis:5/PowerSupply1' status is 'Warning' - Storage 'system:3/NVMe0' status is 'Warning' | 'hardware.chassis.count'=2;;;; 'hardware.device.count'=3;;;; 'hardware.drive.count'=3;;;; 'hardware.storage.count'=3;;;;
```

2025-04-18 13:16 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
> +OK:
```suggestion
WARNING: Device 'chassis:5/PowerSupply1' status is 'Warning' - Storage 'system:3/NVMe0' status is 'Warning' | 'hardware.chassis.count'=2;;;; 'hardware.device.count'=3;;;; 'hardware.drive.count'=3;;;; 'hardware.storage.count'=3;;;;
```

2025-04-29 12:04 UTC, cg-tw approved these changes

2025-04-29 12:05 UTC, merged