CTOR-666-hardware-server-lenovo-xcc
centreon/centreon-documentation pull request #3940
Opened 2024-12-23 17:22 UTC by Evan-Adam

Refs:CTOR-666

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [X] Monitoring Connectors

2025-01-09 12:42 UTC, cg-tw requested changes

2025-01-09 12:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2025-01-09 12:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +OK:
y'a que "ok", c'est pas suffisant

2025-01-09 12:42 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +| Hardware-Global | HW-Lenovo-Xcc-Hardware-Global-SNMP-custom | Contrôle l'ensemble des sondes matériel |
```suggestion
| Hardware-Global | HW-Lenovo-Xcc-Hardware-Global-SNMP-custom | Contrôle l'ensemble des sondes |
```

2025-01-09 12:42 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +OK:
same as FR

2025-01-09 16:22 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +OK:
```suggestion
OK: All 40 components are ok [1/1 cpu, 2/2 disk, 12/12 fans, 8/8 memory, 2/2 psu, 1/1 raidvolume, 10/10 temperatures, 4/4 voltages].
```

2025-01-09 16:23 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
> +OK:
```suggestion
OK: All 40 components are ok [1/1 cpu, 2/2 disk, 12/12 fans, 8/8 memory, 2/2 psu, 1/1 raidvolume, 10/10 temperatures, 4/4 voltages].
```

2025-01-13 12:40 UTC, cg-tw approved these changes

2025-01-13 15:26 UTC, merged