[CTOR-1166]-Refresh hardware-servers-dell-cmc-snmp doc page
centreon/centreon-documentation pull request #3944
Opened 2024-12-26 10:43 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2025-01-28 09:41 UTC, cg-tw requested changes

2025-01-28 09:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-dell-cmc-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2025-01-28 09:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-dell-cmc-snmp.md
> +| Hardware-Global | HW-Dell-CMC-Hardware-Global-SNMP-custom | Contrôle l'ensemble des sondes ('chassis', 'alimentation', 'statut', 'température') |
il faut mettre les valeurs en français?

2025-01-28 09:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-dell-cmc-snmp.md
> +Coming soon
coming soon

2025-01-28 09:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-dell-cmc-snmp.md
> +Coming soon
coming soon

2025-01-28 13:32 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-dell-cmc-snmp.md
> +| Hardware-Global | HW-Dell-CMC-Hardware-Global-SNMP-custom | Contrôle l'ensemble des sondes ('chassis', 'alimentation', 'statut', 'température') |
```suggestion
| Hardware-Global | HW-Dell-CMC-Hardware-Global-SNMP-custom | Contrôle l'ensemble des sondes de l'équipement |
```

2025-01-28 13:32 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-servers-dell-cmc-snmp.md
> +| Hardware-Global | HW-Dell-CMC-Hardware-Global-SNMP-custom | Check all sensors ('chassis', 'power supply', 'status', 'temperature') |
```suggestion
| Hardware-Global | HW-Dell-CMC-Hardware-Global-SNMP-custom | Check all hardware sensors |
```

2025-02-11 13:11 UTC, cg-tw approved these changes

2025-02-11 13:11 UTC, merged