[CTOR-1165] Refresh hardware-kvm-avocent-acs-6000-snmp doc page
centreon/centreon-documentation pull request #3947
Opened 2024-12-26 14:14 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2025-01-28 12:41 UTC, cg-tw requested changes

2025-01-28 12:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-6000-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2025-01-28 12:41 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-6000-snmp.md
> +```bash
thresholds?

2025-01-28 12:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-6000-snmp.md
> +| Cpu-Detailed  | HW-Kvm-Avocent-Acs-6000-Cpu-Detailed-SNMP-custom | Check the detailed rate of utilization of CPU for the machine |
```suggestion
| Cpu-Detailed  | HW-Kvm-Avocent-Acs-6000-Cpu-Detailed-SNMP-custom | Check the detailed rate of CPU utilization for the machine |
```

2025-01-28 12:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-6000-snmp.md
> +| Memory        | HW-Kvm-Avocent-Acs-6000-Memory-SNMP-custom       | Check the rate of the utilization of memory (RAM)             |
```suggestion
| Memory        | HW-Kvm-Avocent-Acs-6000-Memory-SNMP-custom       | Check the rate of memory utilization |
```

2025-01-28 12:41 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-6000-snmp.md
> +OK: User 34947 % Nice 51577 % System 62701 % Idle 36054 % Wait 40431 % Kernel 52232 % Interrupt 72826 % Soft Irq 37513 % Steal 81789 % Guest 76641 % Guest Nice 46537 % | 'cpu.user.utilization.percent
thresholds

2025-01-28 13:48 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-6000-snmp.md
> +```bash
Are the percentages realistic ?

2025-01-28 13:48 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-6000-snmp.md
> +OK: User 34947 % Nice 51577 % System 62701 % Idle 36054 % Wait 40431 % Kernel 52232 % Interrupt 72826 % Soft Irq 37513 % Steal 81789 % Guest 76641 % Guest Nice 46537 % | 'cpu.user.utilization.percent
Are the percentages realistic ?

2025-02-11 13:12 UTC, cg-tw approved these changes

2025-02-11 13:13 UTC, merged