[CTOR-1172]-Refresh hardware-servers-ibm-imm-snmp doc page
centreon/centreon-documentation pull request #3951
Opened 2024-12-27 15:30 UTC by YanMeddour

## Description

Please include a short summary of the changes and what is the purpose of the PR. Any relevant information should be added to help reviewers.

## Target version (i.e. version that this PR changes)

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] 25.10.x
- [ ] Cloud
- [ ] Monitoring Connectors

2025-01-28 14:27 UTC, cg-tw requested changes

2025-01-28 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +## Dépendances du Connecteur de supervision
```suggestion
## Dépendances du connecteur de supervision
```

2025-01-28 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| Environment-Global | HW-IBM-IMM-Environment-Global-SNMP-custom | Contrôle l'ensemble des sondes ('statut globale', 'ventilateur', 'température', 'voltage') de la carte IBM IMM |
```suggestion
| Environment-Global | HW-IBM-IMM-Environment-Global-SNMP-custom | Contrôle l'ensemble des sondes ('statut global', 'ventilateur', 'température', 'voltage') de la carte IBM IMM |
```

2025-01-28 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| Environment-GlobalStatus | HW-IBM-IMM-Environment-GlobalStatus-SNMP-custom | Contrôle la sonde 'statut globale' de la carte IBM IMM |
```suggestion
| Environment-GlobalStatus | HW-IBM-IMM-Environment-GlobalStatus-SNMP-custom | Contrôle la sonde 'statut global' de la carte IBM IMM |
```

2025-01-28 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | fan               |             |
default value

2025-01-28 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | global            |             |
default value

2025-01-28 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | temperature       |             |
default value

2025-01-28 14:27 UTC, cg-tw commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | voltage           |             |
default value

2025-01-28 14:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | fan               |             |
default value

2025-01-28 14:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | global            |             |
default value

2025-01-28 14:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | temperature       |             |
default value

2025-01-28 14:27 UTC, cg-tw commented on pp/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | voltage           |             |
default value

2025-02-04 13:08 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | fan               |             |
```suggestion
| COMPONENT    | Which component to check. Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | fan               |             |
```

2025-02-04 13:09 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | global            |             |
```suggestion
| COMPONENT    | Which component to check. Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | global            |             |
```

2025-02-04 13:09 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | temperature       |             |
```suggestion
| COMPONENT    | Which component to check. Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | temperature       |             |
```

2025-02-04 13:09 UTC, lucie-dubrunfaut commented on i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | voltage           |             |
```suggestion
| COMPONENT    | Which component to check. Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | voltage           |             |
```

2025-02-04 13:10 UTC, lucie-tirand commented on pp/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | fan               |             |
```suggestion
| COMPONENT    | Which component to check. Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | fan               |             |
```

2025-02-04 13:10 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | global            |             |
```suggestion
| COMPONENT    | Which component to check. Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | global            |             |
```

2025-02-04 13:10 UTC, lucie-dubrunfaut commented on pp/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | temperature       |             |
```suggestion
| COMPONENT    | Which component to check. Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | temperature       |             |
```

2025-02-04 13:10 UTC, lucie-tirand commented on pp/integrations/plugin-packs/procedures/hardware-servers-ibm-imm-snmp.md
> +| COMPONENT    | Which component to check (default: '.*'). Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | voltage           |             |
```suggestion
| COMPONENT    | Which component to check. Can be: 'cpu', 'disk', 'fan', 'global', 'memory', 'power', 'temperature', 'voltage' | voltage           |             |
```

2025-02-04 13:11 UTC, cg-tw approved these changes

2025-02-04 13:57 UTC, merged