enh(centreon-ha)4-nodes-setup_and_upgrade_from_centreon-failover
centreon/centreon-documentation pull request #397
Opened 2020-10-16 10:08 UTC by Sims24

## Description

This PR introduces 4 nodes HA setup and gives a very standard procedure about migration process from legacy centreon-failover to centreon-ha architecture. 

## Target serie

- [X] 20.04.x
- [X] 20.10.x (master)

2020-10-19 08:19 UTC, tanguyvda requested changes
not reviewed everything but that's a start

2020-10-19 08:19 UTC, tanguyvda commented on en/administration/centreon-ha/installation-4-nodes.md
> +Now that both of the central nodes **and** the *quorum device* server are sharing the same password, you will run this command **only on one of the central nodes** in order to authenticate on all the
only on one of the cluster nodes, we don't care if it's on a central server nor the qdevice nor a database server

2020-10-19 08:19 UTC, tanguyvda commented on en/administration/centreon-ha/installation-4-nodes.md
> +The following command creates the cluster. It must be run **only on one of the central nodes**.
I say it again 
only on one of the cluster nodes, we don't care if it's on a central server nor the qdevice nor a database server

but perhaps I've missed something

2020-10-19 08:19 UTC, tanguyvda commented on en/administration/centreon-ha/installation-4-nodes.md
> +Then start the `pacemaker` service **on both central nodes**:
you sure you don't want to start pacemaker on your databases servers ?

2020-10-19 08:19 UTC, tanguyvda commented on en/administration/centreon-ha/installation-4-nodes.md
> +```
you've glued ms_mysql-master with centreon and not the vip, we don't want to link mysql resource with centreon resources when using a 4 nodes cluster

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +Réaliser la montée de version de vos bases de données en suivant [la documentation officielle](../upgrade/upgrade-from-19-10.html#upgrade-mariadb-server).
J'aurais mis "la montée de version **des** bases" pour respecter la forme infinitive impersonnelle.

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * [Déployer les dépôts 20.04](../upgrade/upgrade-from-19-10.html#update-the-centreon-repository). Il est également nécessaire de mettre à jour les dépôts des modules de l'édition Business.
Le repère dans la page ne fonctionnera pas en français :
     * [Déployer les dépôts 20.04](../upgrade/upgrade-from-19-10.html#mise-à-jour-des-dépôts). Il est également nécessaire de mettre à jour les dépôts des modules de l'édition Business.

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * [Mettre à jour les paquets Centreon](../upgrade/upgrade-from-19-10.html#upgrade-the-centreon-solution)
Idem:
     * [Mettre à jour les paquets Centreon](../upgrade/upgrade-from-19-10.html#montée-de-version-de-la-solution-centreon)

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * [Réaliser les étapes supplémentaires](../upgrade/upgrade-from-19-10.html#additional-actions)
Idem:
#actions-complémentaires

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * [Déployer les dépôts 20.04](../upgrade/upgrade-from-19-04.html#update-the-centreon-repository). Also those of the Business Edition modules if installed.
#mise-à-jour-des-dépôts

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * [Mettre à jour les paquets Centreon](../upgrade/upgrade-from-19-04.html#upgrade-the-centreon-solution)
#montée-de-version-de-la-solution-centreon

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * [Réaliser les étapes supplémentaires](../upgrade/upgrade-from-19-04.html#additional-actions)
#actions-complémentaires

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * Si Centreon et les bases de données sont sur le même noeud, suivez ce [guide d'installation](../installation-2-nodes.html#setting-up-the-centreon-cluster)
#mise-en-place-du-cluster-centreon

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * Si les bases de données tournent sur un serveur dédié, suivez ce [guide d'installation](../installation-4-nodes.html#setting-up-the-centreon-cluster)
#mise-en-place-du-cluster-centreon aussi j'imagine

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * [Echnages de clés SSH pour le Cluster](../installation-2-nodes.html#ssh-keys-exchange)
#échanges-de-clefs-ssh

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * [Droits et privilèges des utilisateurs de bases de données](../installation-2-nodes.html#creating-the-centreon-mariadb-account)
#création-du-compte-centreon

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +décrite [ici](../installation-2-nodes.html#customizing-poller-reload-command). Celle-ci est configurable via le menu
#modification-de-la-commande-de-rechargement-de-cbd

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * Si vous êtiez en version 19.10, suivez ce [chapitre](../upgrade/upgrade-from-19-10.html#finalizing-the-upgrade).
#finalisation-de-la-mise-à-jour

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +    * Si vous êtiez en version 20.04, suivez ce [chapitre](../upgrade/upgrade-from-19-04.html#finalizing-the-upgrade).
#finalisation-de-la-mise-à-jour

2020-10-20 08:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +Enfin, [mettez à jour vos Pollers](../upgrade/upgrade-from-19-04.html#upgrade-the-poller), redéployer la configuration et redémarrer le processus centengine.
#montée-de-version-des-pollers

2020-10-20 10:25 UTC, omercier requested changes

2020-10-20 10:25 UTC, omercier commented on fr/administration/centreon-ha/upgrade-from-centreon-failover.md
> +
J'ai oublié d'ajouter dans la version FR:

Une fois que les clés SSH des utilisateurs `centreon` et `mysql` ont bien été échangées, penser à supprimer la clef publique de `root` de `/root/.ssh/authorized_keys`.

2020-10-20 12:52 UTC, omercier approved these changes

2020-10-20 14:06 UTC, tanguyvda approved these changes

2020-10-20 14:13 UTC, merged