enh(install): support for CentOS v8
centreon/centreon-documentation pull request #427
Opened 2020-10-27 12:55 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x (master)

2020-12-01 14:27 UTC, thiuyendang requested changes

2020-12-01 14:27 UTC, thiuyendang commented on en/installation/installation-of-a-poller/using-packages.md
> +dnf install -y http://yum.centreon.com/standard/20.10/el8/stable/noarch/RPMS/centreon-release-20.10-2.el7.centos.noarch.rpm
el8 instead of el7

2020-12-02 16:57 UTC, thiuyendang commented on en/installation/installation-of-a-poller/using-packages.md
> +dnf install -y http://yum.centreon.com/standard/20.10/el8/stable/noarch/RPMS/centreon-release-20.10-2.el7.centos.noarch.rpm
dnf install -y http://yum.centreon.com/standard/20.10/el8/stable/noarch/RPMS/centreon-release-20.10-2.el8.noarch.rpm

2020-12-08 15:10 UTC, cgagnaire requested changes

2020-12-08 15:10 UTC, cgagnaire commented on fr/reporting/installation.md
> +Run the following command:
```suggestion
```

2020-12-08 15:10 UTC, cgagnaire commented on fr/reporting/installation.md
> +systemctl restart mysql
```suggestion
systemctl restart mariadb
```

2020-12-08 15:10 UTC, cgagnaire commented on fr/reporting/installation.md
> +systemctl restart mysql
```suggestion
systemctl restart mariadb
```

2020-12-08 15:10 UTC, cgagnaire commented on fr/reporting/installation.md
> +systemctl start mysql
```suggestion
systemctl start mariadb
```

2020-12-08 15:10 UTC, cgagnaire commented on en/installation/installation-of-a-remote-server/using-packages.md
>  <!--With a local database-->
Tab usage is not the same than Central install

2020-12-08 15:10 UTC, cgagnaire commented on en/installation/installation-of-a-central-server/using-packages.md
> +<!--DOCUSAURUS_CODE_TABS-->
I think we should split this into 2 double tabs section so the tabs are tied to the commands (ie the text "Run the following..." is outside the tabs).
Rendering is better on Docusorus this way.

2020-12-08 15:10 UTC, cgagnaire commented on en/reporting/installation.md
> +Run the following command:
```suggestion
```

2020-12-08 15:10 UTC, cgagnaire commented on en/reporting/installation.md
> +<!--DOCUSAURUS_CODE_TABS-->
```suggestion
Run the following command:

<!--DOCUSAURUS_CODE_TABS-->
```

2020-12-08 15:12 UTC, cgagnaire requested changes

2020-12-08 15:12 UTC, cgagnaire commented on en/reporting/installation.md
> +systemctl restart mysql
```suggestion
systemctl restart mariadb
```

2020-12-08 15:12 UTC, cgagnaire commented on en/reporting/installation.md
> +systemctl restart mysql
```suggestion
systemctl restart mariadb
```

2020-12-08 15:12 UTC, cgagnaire commented on en/reporting/installation.md
> +systemctl restart mysql
```suggestion
systemctl restart mariadb
```

2020-12-08 15:19 UTC, cgagnaire commented
You should add 4 spaces indentation in the content of the numbered lists where they are used, like:

1. Entering your password:

    ``` shell
   192.168.0.1: please enter your password
   ```

2. Define if you use a proxy to connect to Centreon central or the Remote Server:

   ```shell
   Are you using a proxy ? (y/n)n
   ```

   If you use a proxy, please define credentials:

   ...

2020-12-11 11:00 UTC, cgagnaire approved these changes

2021-01-15 09:19 UTC, cgagnaire approved these changes

2021-01-26 09:41 UTC, cgagnaire approved these changes

2021-01-26 09:44 UTC, merged