release(mbi): Add 20.04.3 release note
centreon/centreon-documentation pull request #428
Opened 2020-10-27 16:26 UTC by chgautier

2020-10-27 16:31 UTC, cgagnaire reviewed
Can you copy it to fr tree please ?

2020-10-27 16:50 UTC, tuntoja approved these changes

2020-10-27 17:10 UTC, tuntoja requested changes

2020-10-27 17:10 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +* Correction des problèmes liées au caractères accentués
Correction des problèmes liés au caractères accentués

2020-10-27 17:10 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +* Correction de l'erreur au lancement du script diagnostique due au mode strict MYSQL
Correction de l'erreur au lancement du script de diagnostique dûe au mode strict MYSQL

2020-10-27 17:12 UTC, chgautier commented on fr/releases/centreon-commercial-extensions.md
> +* Correction de l'erreur au lancement du script diagnostique due au mode strict MYSQL
```suggestion
* Correction de l'erreur au lancement du script de diagnostique dûe au mode strict MYSQL
```

2020-10-27 17:13 UTC, chgautier commented on fr/releases/centreon-commercial-extensions.md
> +* Correction des problèmes liées au caractères accentués
### 
```suggestion
* Correction des problèmes liés aux caractères accentués
```

2020-10-27 17:19 UTC, tuntoja approved these changes

2020-10-28 15:45 UTC, tuntoja requested changes

2020-10-28 15:45 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +* Correction de l'erreur au lancement du script de diagnostique dûe au mode strict MYSQL
diagnostic

2020-10-28 15:47 UTC, chgautier commented on fr/releases/centreon-commercial-extensions.md
> +* Correction de l'erreur au lancement du script de diagnostique dûe au mode strict MYSQL
```suggestion
* Correction de l'erreur au lancement du script de diagnostic dûe au mode strict MYSQL
```

2020-10-28 16:08 UTC, cgagnaire approved these changes

2020-10-28 16:26 UTC, merged