enh(release): preprare bam 20.04.4 release notes
centreon/centreon-documentation pull request #435
Opened 2020-10-29 13:59 UTC by cgagnaire

## Description

Prepare BAM 20.04.4 release notes

## Target serie

- [x] 20.04.x
- [ ] 20.10.x (master)

2020-10-29 14:13 UTC, chgautier approved these changes

2020-10-30 08:38 UTC, tuntoja requested changes

2020-10-30 08:38 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +  rafraîchit
rafraîchie

2020-10-30 08:38 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
>  * Gestion de la compatibility avec HTTP2
compatibilité

2020-10-30 08:56 UTC, cgagnaire commented on fr/releases/centreon-commercial-extensions.md
>  * Gestion de la compatibility avec HTTP2
```suggestion
* Gestion de la compatibilité avec HTTP2
```

2020-10-30 08:56 UTC, cgagnaire commented on fr/releases/centreon-commercial-extensions.md
> +  rafraîchit
```suggestion
  rafraîchie
```

2020-10-30 09:32 UTC, merged