enh(release): add Centreon Web 20.10.2 release notes
centreon/centreon-documentation pull request #469
Opened 2020-12-01 10:22 UTC by lpinsivy

## Description

Release notes for Centreon Web 20.10.2

## Target serie

- [ ] 20.04.x
- [x] 20.10.x (master)

2020-12-01 17:00 UTC, tuntoja approved these changes

2021-01-08 14:27 UTC, thiuyendang requested changes

2021-01-08 14:27 UTC, thiuyendang commented on en/releases/centreon-core.md
> +- [Resources Status] Display issue when resource has a configured icon
Missing mention for ticket MON-5812 

[Frontend][Backend][events view] Incorrect default downtime duration
--

2021-01-08 14:27 UTC, thiuyendang commented on en/releases/centreon-core.md
> +### 20.10.2
Add a known bug section to warn about an issue related to macros not replaced in url built in Resources status: https://centreon.atlassian.net/browse/MON-6532 (not fixed yet)

2021-01-11 13:04 UTC, thiuyendang requested changes

2021-01-11 13:04 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +> -   Les liens "url notes" et "url actions" maintenant visible dans la page "Resources Status"
visbleS

2021-01-12 09:00 UTC, thiuyendang approved these changes

2021-01-12 09:19 UTC, merged