enh(release): prepare broker 20.10.2 release notes
centreon/centreon-documentation pull request #479
Opened 2020-12-03 14:53 UTC by cgagnaire

## Description

Prepare Broker 20.10.2 release notes

## Target serie

- [ ] 20.04.x
- [x] 20.10.x (master)

2020-12-10 09:27 UTC, chgautier requested changes

2020-12-10 09:27 UTC, chgautier commented on en/releases/centreon-core.md
> +>     20.04.5.
```suggestion
>     20.10.2.
```

2020-12-10 09:28 UTC, chgautier requested changes

2020-12-10 09:28 UTC, chgautier commented on fr/releases/centreon-core.md
> +>     serveur MAP à la version >= 20.04.5.
```suggestion
>     serveur MAP à la version >= 20.10.2.
```

2020-12-10 14:08 UTC, chgautier requested changes

2020-12-10 14:08 UTC, chgautier commented on en/releases/centreon-core.md
> +Credentials were no more loaded by the TLS connector. This is fixed with this
```suggestion
Credentials were not loaded by the TLS connector anymore. This is fixed with this
```

2020-12-10 16:02 UTC, cgagnaire commented on en/releases/centreon-core.md
> +-   Events exchanges are really faster, especially when Broker has
```suggestion
-   Events exchanges are much faster, especially when Broker has
```

2020-12-10 16:02 UTC, cgagnaire commented on fr/releases/centreon-core.md
> +-   Events exchanges are really faster, especially when Broker has
```suggestion
-   Events exchanges are much faster, especially when Broker has
```

2020-12-11 09:30 UTC, chgautier approved these changes

2020-12-16 08:38 UTC, merged