add(epp): hms ewon snmp monitoring proc
centreon/centreon-documentation pull request #517
Opened 2020-12-23 12:46 UTC by garnier-quentin

## Description

-

## Target serie

- [X] 20.04.x
- [X] 20.10.x (master)

2020-12-28 08:21 UTC, Sims24 requested changes

2020-12-28 08:21 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md
> +The plugin-pack HMS Ewon including monitoring of Tags.
Uppercase Plugin-Pack

2020-12-28 08:21 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md
> +The plugin-pack HMS Ewon including monitoring of Tags.
ing form misused

2020-12-28 08:21 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md
> +To control your HMS Ewon, the SNMP must be configured.
Add some public manufacturer documentation if any

2020-12-28 08:21 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md
> +The command above monitors a HMS Ewon tags (```--plugin=hardware::devices::hms::ewon::snmp::plugin --mode=tags```) identified
remove 'a'

2020-12-28 08:21 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md
> +
Uppercase Plugin-Pack

2020-12-28 12:25 UTC, garnier-quentin commented on en/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md
> +To control your HMS Ewon, the SNMP must be configured.
i don't have documentation link

2021-01-14 08:06 UTC, Sims24 approved these changes

2021-01-14 08:07 UTC, merged