enh(release): Add Centreon web 20.04.8 RN
centreon/centreon-documentation pull request #538
Opened 2021-01-11 15:42 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [ ] 20.10.x (master)

2021-01-11 17:04 UTC, thiuyendang requested changes

2021-01-11 17:04 UTC, thiuyendang commented on en/releases/centreon-core.md
> +- [Configuration] Massive change on contact uses replacement instead of incremental method
As it is a check if the bug still exists or not. @jeremyjaouen When you tell it is OK, does it mean that the issue behaviour is still present or that issue has been fixed ? (does incremental option works as replacement or as it should work ? )

2021-01-12 08:13 UTC, jeremyjaouen commented on en/releases/centreon-core.md
> +- [Configuration] Massive change on contact uses replacement instead of incremental method
The issue has been fixed.

2021-01-12 08:37 UTC, thiuyendang commented on en/releases/centreon-core.md
> +- [Configuration] Massive change on contact uses replacement instead of incremental method
OK, thanks

2021-01-12 08:57 UTC, thiuyendang approved these changes

2021-01-12 09:19 UTC, merged