feat(pack): add new-procedure-database-oracle-v3
centreon/centreon-documentation pull request #542
Opened 2021-01-13 15:53 UTC by jeanrenemoyap

## Description

The current monitoring procedure for Oracle Database does not correctly describe the export of the two variables: ORACLE_HOME and LD_LIBRARY_PATH. This request fixes the paths and rewrites all in the new documentation format.

## Target serie

- [x] 20.04.x
- [x] 20.10.x (master)

2021-01-14 07:55 UTC, garnier-quentin commented
Please update the procedure with last instantclient and oracle dbd versions.

2021-01-14 08:21 UTC, pkriko requested changes
Hello @jeanrenemoyap see my request changes for the EN part, please report them on the french part.

2021-01-14 08:21 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-databases-oracle.md
> +| rman_backup_problems     | RMAN backup errors number of the server during the last three days  | Count  |
```suggestion
| Metric name          | Description                                                         | Unit   |
| :----------------------- | :------------------------------------------------------------------ | :----  |
| #backup_backup_problems     | Number of problems per backup (last 3 days by default)  | Count  |
```

2021-01-14 08:21 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-databases-oracle.md
> +| usage       | Check the 'Data Buffer Cache Hit Ratio' of the server|  %    |
```suggestion
| Metric name | Description                                          | Unit |
| :---------- | :--------------------------------------------------- | :--- |
| sga_data_buffer_hit_ratio       | Check the 'Data Buffer Cache Hit Ratio' of the server|   %    |
```

2021-01-14 08:21 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-databases-oracle.md
> +The check provides a warning if the percentage of used space exceeds 90% and a critical if this percentage exceeds 98%.
add the option just like you did for Oracle informations :)

2021-01-15 08:04 UTC, pkriko requested changes

2021-01-15 08:04 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-databases-oracle.md
> +The check provides a warning if the percentage of used space exceeds 90% and a critical if this percentage exceeds 98%.
Add the options just like you did previously

2021-01-15 08:04 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-databases-oracle.md
> +### ```CRITICAL: Cannot connect: (no error string) |```
```suggestion
#### ```CRITICAL: Cannot connect: (no error string) |```
```

2021-01-15 08:04 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-databases-oracle.md
> +### ```DBD::Oracle is not root directory |```
```suggestion
#### ```DBD::Oracle is not root directory |```
```

2021-01-15 08:04 UTC, pkriko commented on en/integrations/plugin-packs/procedures/applications-databases-oracle.md
> +Check that an Oracle database is installed on this host.
```suggestion
Check that an Oracle database is installed on this host.
Check that no third party device (such as a firewall) is blocking the connection.
```

2021-01-15 16:11 UTC, pkriko approved these changes

2021-01-19 19:21 UTC, Sims24 requested changes

2021-01-19 19:21 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-databases-oracle.md
> +You just have to enter in the file : /usr/lib/oracle/21.1/client64/lib/
@pkriko @jeanrenemoyap I think it's not clear. Could you rephrase it please?

2021-02-11 07:49 UTC, Sims24 approved these changes

2021-02-12 14:42 UTC, merged