add missing date for web 20.10.3 release notes
centreon/centreon-documentation pull request #576
Opened 2021-02-08 16:30 UTC by tuntoja

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x (master)

2021-02-08 16:36 UTC, thiuyendang approved these changes

2021-02-09 09:02 UTC, cgagnaire requested changes

2021-02-09 09:02 UTC, cgagnaire commented on en/releases/centreon-core.md
> +`February 08, 2021`
```suggestion
`February 8, 2021`
```

2021-02-09 09:02 UTC, cgagnaire commented on fr/releases/centreon-core.md
> +`08 février 2021`
```suggestion
`8 février 2021`
```

2021-09-28 14:54 UTC, cg-tw commented
Already fixed

2021-09-28 14:54 UTC, closed without merging