enh(release): Add Centreon Web 20.10.4 RN
centreon/centreon-documentation pull request #602
Opened 2021-02-22 10:57 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x (master)

2021-02-22 12:12 UTC, tuntoja requested changes

2021-02-22 12:12 UTC, tuntoja commented on en/releases/centreon-core.md
> +- [Configuration] Creation forms generate 400 errors
```suggestion
- [Configuration] Creation forms generate satus code 400 errors
```

2021-02-22 12:12 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- [Configuration] Creation forms generate 400 errors
```suggestion
- [Configuration] Creation forms generate satus code 400 errors
```

2021-02-22 12:12 UTC, tuntoja commented on en/releases/centreon-core.md
> +- [Apache] remove deprecated TLS cyphers
```suggestion
- [Apache] Remove deprecated TLS cyphers
```

2021-02-22 12:12 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- [Apache] remove deprecated TLS cyphers
```suggestion
- [Apache] Remove deprecated TLS cyphers
```

2021-02-22 12:12 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- [Remote Server] Import task failed when a Poller is link to additional RS
```suggestion
- [Remote Server] Import task failed when a Poller is linked to additional RS
```

2021-02-22 12:12 UTC, tuntoja commented on en/releases/centreon-core.md
> +- [Remote Server] Import task failed when a Poller is link to additional RS
```suggestion
- [Remote Server] Import task failed when a Poller is linked to additional RS
```

2021-02-23 16:05 UTC, chgautier requested changes

2021-02-23 16:05 UTC, chgautier commented on en/releases/centreon-core.md
> +- [Top counters] Displayed values for services don't consider host acknowledgments
```suggestion
- [Top counters] Displayed values for services don't consider host acknowledgements
```

2021-02-23 16:05 UTC, chgautier commented on en/releases/centreon-core.md
> +- [Resources Status] Display of comments in the host details page
```suggestion
- [Status Details] Display of comments in the host details page
```

2021-02-23 16:05 UTC, chgautier commented on en/releases/centreon-core.md
> +- [Remote Server] Import task failed when a Poller is linked to additional RS
```suggestion
- [Remote Server] Import task failed when a Poller is linked to an additional RS
```

2021-02-23 16:05 UTC, chgautier commented on en/releases/centreon-core.md
> +- [Apache] Remove deprecated TLS cyphers
```suggestion
- [Apache] Remove deprecated TLS ciphers
```

2021-02-23 16:05 UTC, chgautier commented on fr/releases/centreon-core.md
> +- [Resources Status] Display of comments in the host details page
```suggestion
- [Status Details] Display of comments in the host details page
```

2021-02-23 16:05 UTC, chgautier commented on fr/releases/centreon-core.md
> +- [Top counters] Displayed values for services don't consider host acknowledgments
```suggestion
- [Top counters] Displayed values for services don't consider host acknowledgements
```

2021-02-23 16:05 UTC, chgautier commented on fr/releases/centreon-core.md
> +- [Remote Server] Import task failed when a Poller is linked to additional RS
```suggestion
- [Remote Server] Import task failed when a Poller is linked to an additional RS
```

2021-02-23 16:05 UTC, chgautier commented on fr/releases/centreon-core.md
> +- [Apache] Remove deprecated TLS cyphers
```suggestion
- [Apache] Remove deprecated TLS ciphers
```

2021-02-24 15:09 UTC, thiuyendang approved these changes

2021-02-25 15:35 UTC, thiuyendang approved these changes

2021-02-25 15:39 UTC, merged