enh(pack)rewrite-prom-mp-and-misc[en]
centreon/centreon-documentation pull request #606
Opened 2021-02-24 13:31 UTC by Sims24

## Description

This PR introduces the new version of the Prometheus Api monitoring procedure. 

Also add information in the GCP Prerequisites

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x (master)

2021-03-02 17:25 UTC, cgagnaire requested changes

2021-03-02 17:25 UTC, cgagnaire commented on en/integrations/plugin-packs/procedures/cloud-prometheus-api.md
> +    - Check returning an error
```suggestion
The output-related options gives ability to tune output messages of the
check in the following cases:

- Check a metric on multiple instances
- Check returning an error
```

2021-03-02 17:25 UTC, cgagnaire commented on en/integrations/plugin-packs/procedures/cloud-prometheus-api.md
> +    - the PromQL query (```sum by (node) (kube_pod_container_resource_requests_cpu_cores) / sum by (node) (kube_node_status_capacity_cpu_cores) * 100```)
```suggestion
The ```--query``` option allows to define two things:

- the Centreon metric name (```cpu_requests```)
- the PromQL query (```sum by (node) (kube_pod_container_resource_requests_cpu_cores) / sum by (node) (kube_node_status_capacity_cpu_cores) * 100```)
```

2021-03-02 17:25 UTC, cgagnaire commented on en/integrations/plugin-packs/procedures/cloud-prometheus-api.md
> +* Once the template applied, some Macros marked as 'Mandatory' hereafter have to be configured.
```suggestion
- Log into Centreon and add a new Host through "Configuration > Hosts".
- Select the *Cloud-Prometheus-Api-custom* template to apply to the Host.
- Once the template applied, some Macros marked as 'Mandatory' hereafter have to be configured.
```

2021-03-02 17:25 UTC, cgagnaire commented on en/integrations/plugin-packs/procedures/cloud-prometheus-api.md
> +* Status of the targets
```suggestion
- All metrics stored by Prometheus
- Status of the targets
```

2021-03-17 09:29 UTC, garnier-quentin approved these changes

2021-03-17 09:48 UTC, merged