enh(release): prepare Autodisco 20.10.3 release notes
centreon/centreon-documentation pull request #610
Opened 2021-02-25 13:57 UTC by omercier

## Description

Release note for the new version

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x (master)

2021-02-25 15:40 UTC, cgagnaire reviewed
It looks like a note is missing in the french ones.

Try to also apply the 60-80 characters per line.

2021-03-01 07:51 UTC, omercier commented
> It looks like a note is missing in the french ones.

Indeed! 

> 
> Try to also apply the 60-80 characters per line.
:+1:

2021-03-01 09:00 UTC, cgagnaire approved these changes

2021-03-17 11:29 UTC, thiuyendang requested changes

2021-03-17 11:29 UTC, thiuyendang commented on en/releases/centreon-commercial-extensions.md
> +
Missing mention to those fixes : 
[HD/Provider/Install/Upgrade] Limit provider definition version that is imported to 2.0 in 20.10/20.04
[Core] Creation forms generate 400 errors

2021-03-17 11:29 UTC, thiuyendang commented on fr/releases/centreon-commercial-extensions.md
> +
Missing mention to those fixes : 
[HD/Provider/Install/Upgrade] Limit provider definition version that is imported to 2.0 in 20.10/20.04
[Core] Creation forms generate 400 errors

2021-03-17 13:48 UTC, thiuyendang approved these changes

2021-03-17 14:51 UTC, merged