enh(release): prepare Autodisco 20.04.8 release notes
centreon/centreon-documentation pull request #611
Opened 2021-02-25 13:58 UTC by omercier

## Description

Release note for new version

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x (master)

2021-02-25 15:41 UTC, cgagnaire reviewed
Try to keep lines between 60-80 characters wide.

2021-03-01 09:00 UTC, cgagnaire approved these changes

2021-03-17 11:15 UTC, thiuyendang requested changes

2021-03-17 11:15 UTC, thiuyendang commented on en/releases/centreon-commercial-extensions.md
> +
Missing this ticket [HD/Provider/Install/Upgrade] Limit provider definition version that is imported to 2.0 in 20.10/20.04

2021-03-17 11:15 UTC, thiuyendang commented on fr/releases/centreon-commercial-extensions.md
> +
Missing this ticket : [HD/Provider/Install/Upgrade] Limit provider definition version that is imported to 2.0 in 20.10/20.04

2021-03-17 13:51 UTC, thiuyendang approved these changes

2021-03-17 14:51 UTC, merged