fix(doc): small corrections
centreon/centreon-documentation pull request #613
Opened 2021-03-01 15:54 UTC by tuntoja

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x (master)

2021-03-02 07:30 UTC, sc979 commented on en/alerts-notifications/resources-status.md
>  -   By directly acknowledging on the line, a "Acknowledgement" button
```suggestion
-   By directly acknowledging on the line, an "Acknowledgement" button
```

2021-03-02 07:30 UTC, sc979 commented on en/alerts-notifications/resources-status.md
> +    appear on mouseover
```suggestion
    appears on mouseover
```

2021-03-02 07:42 UTC, sc979 approved these changes

2021-03-02 10:28 UTC, chgautier requested changes

2021-03-02 10:28 UTC, chgautier commented on en/alerts-notifications/resources-status.md
> +The colour of the lines for resources with an acknownledgement set is changed
```suggestion
The color of the line for acknowledged resources is changed
```

2021-03-02 10:28 UTC, chgautier commented on en/alerts-notifications/resources-status.md
> +-   By directly acknowledging on the line, an "Acknowledgement" button
```suggestion
-   By directly acknowledging the line, an "Acknowledgement" button
```

2021-03-02 10:28 UTC, chgautier commented on en/alerts-notifications/resources-status.md
> +> You can not acknowledge a resource already acknowledged
```suggestion
> You cannot acknowledge a resource already acknowledged
```

2021-03-02 10:28 UTC, chgautier commented on en/alerts-notifications/resources-status.md
>  -   By directly setting a planned downtime on the line when the mouse is
```suggestion
-   By directly setting a planned downtime on the line,
```

2021-03-02 10:28 UTC, chgautier commented on en/alerts-notifications/resources-status.md
> +    over it
```suggestion
    a "Set Downtime" button appears on mouseover
```

2021-03-02 10:28 UTC, chgautier commented on en/alerts-notifications/resources-status.md
> +colour of lines for resources with a downtime set is changed to light purple.
```suggestion
color of lines for resources with a planned downtime is changed to light purple.
```

2021-03-02 10:28 UTC, chgautier commented on en/alerts-notifications/resources-status.md
>  -   Save the current filter so that it's updated using your current
```suggestion
-   Save the current filter so that it is updated using your current
```

2021-03-02 10:28 UTC, chgautier commented on en/alerts-notifications/resources-status.md
> +It's possible to add a comment directly on the graph, by left clicking anywhere at the time you want to add it, and select "Add a comment" on the tooltip that appears:
```suggestion
It is possible to add a comment directly on the graph, by left clicking anywhere at the time you want to add it, and select "Add a comment" on the tooltip that appears:
```

2021-03-02 10:28 UTC, chgautier commented on fr/alerts-notifications/resources-status.md
>  -   Resource problems: Le statut de la ressources est Warning ou
```suggestion
-   Resource problems: Le statut de la ressource est Warning ou
```

2021-03-04 15:01 UTC, bdauria approved these changes

2021-03-08 14:30 UTC, chgautier approved these changes

2021-03-08 16:59 UTC, merged