Move secure chapter
centreon/centreon-documentation pull request #615
Opened 2021-03-02 15:21 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x (master)

2021-03-02 16:23 UTC, sc979 approved these changes

2021-03-02 17:05 UTC, cgagnaire requested changes
Relative paths don't seem right.

2021-03-04 11:40 UTC, lpinsivy commented
> Relative paths don't seem right.

the links are now functional

2021-03-04 13:26 UTC, cgagnaire approved these changes

2021-03-04 13:32 UTC, merged