enh(discovery/service): add custom parameters with example
centreon/centreon-documentation pull request #616
Opened 2021-03-03 15:35 UTC by cgagnaire

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [x] 21.04.x (master)

2021-03-03 15:49 UTC, kabreu approved these changes

2021-03-03 16:51 UTC, chgautier requested changes

2021-03-03 16:51 UTC, chgautier commented on en/monitoring/discovery/administration.md
> +| no\_generate\_config | No configuration generation (even if there is some changes) ('0': generation, '1': no generation) |
```suggestion
| no\_generate\_config | No configuration generation (even if there are some changes) ('0': generation, '1': no generation) |
```

2021-03-03 16:51 UTC, chgautier commented on fr/monitoring/discovery/administration.md
> +| filter\_pollers      | Tableau de Pollers pour lesquels les hôtes attachés se verront lancé la découverte (vide pour tous les utiliser) |
```suggestion
| filter\_pollers      | Tableau de collecteurs pour lesquels les hôtes attachés se verront lancé la découverte (vide pour tous les utiliser) |
```

2021-03-03 16:51 UTC, chgautier commented on en/monitoring/discovery/administration.md
> +| filter\_pollers      | Array of pollers for which linked hosts will be discovered against (empty means all)              |
```suggestion
| filter\_pollers      | Array of pollers for which linked hosts will undergo discovery (empty means all)              |
```

2021-03-03 16:51 UTC, chgautier commented on en/monitoring/discovery/administration.md
> +| filter\_hosts        | Array of hosts against which run the discovery (empty means all)                                  |
```suggestion
| filter\_hosts        | Array of hosts which will run the discovery (empty means all)                                  |
```

2021-03-05 12:03 UTC, chgautier approved these changes

2021-03-05 13:24 UTC, merged