enh(install): improve servers installation
centreon/centreon-documentation pull request #668
Opened 2021-04-14 14:30 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x (master)

2021-04-15 07:34 UTC, kduret commented on fr/monitoring/monitoring-servers/move-poller.md
> +DAns l'onglet **Output** , ajoutez ou modifiez l'entrée **TCP - IPv4** pour se connecter au nouveau serveur :
```suggestion
Dans l'onglet **Output** , ajoutez ou modifiez l'entrée **TCP - IPv4** pour se connecter au nouveau serveur :
```

2021-04-15 07:36 UTC, kduret approved these changes

2021-04-15 13:09 UTC, bdauria requested changes
We should add the mysql command to execute before the privilege step here: 
![image](https://user-images.githubusercontent.com/8367233/114874118-4a5f2180-9dfc-11eb-891a-c042182bd8a5.png)

```
mysql <database username> -u centreon -p
```
ex:
```
mysql root -u centreon -p
```

2021-04-19 12:55 UTC, lpinsivy commented
@bdauria we didn't add this before because it was explicit

2021-04-21 09:42 UTC, thiuyendang approved these changes

2021-04-21 10:24 UTC, bdauria approved these changes

2021-04-21 10:25 UTC, merged