enh(release): Add Centreon Web 20.04.13 RN
centreon/centreon-documentation pull request #696
Opened 2021-04-27 09:45 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x (master)

2021-04-27 10:56 UTC, kduret approved these changes

2021-05-10 06:34 UTC, tuntoja requested changes

2021-05-10 06:34 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`May 10, 2021`

```

2021-05-10 06:35 UTC, tuntoja requested changes

2021-05-10 06:35 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`10 mai 2021`

```

2021-05-10 06:35 UTC, tuntoja approved these changes

2021-05-10 06:35 UTC, merged