enh(release): Add Centreon Web 20.10.7 RN
centreon/centreon-documentation pull request #697
Opened 2021-04-27 10:01 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x (master)

2021-05-06 15:01 UTC, mdebauchez requested changes
In english and french version : 
Ligns 46 and 47 are the same

2021-05-07 08:40 UTC, tuntoja requested changes

2021-05-07 08:40 UTC, tuntoja commented on en/releases/centreon-core.md
> +- [Resources Status] Service link to multiple hosts or service by hostgroup won't be listed
```suggestion
```

2021-05-07 08:40 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- [Resources Status] Service link to multiple hosts or service by hostgroup won't be listed
```suggestion
```

2021-05-07 08:45 UTC, mdebauchez approved these changes

2021-05-07 08:48 UTC, thiuyendang approved these changes

2021-05-07 09:03 UTC, tuntoja approved these changes

2021-05-07 10:00 UTC, tuntoja requested changes

2021-05-07 10:00 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`May 7, 2021`

```

2021-05-07 10:00 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`7 mai 2021`

```

2021-05-07 10:08 UTC, tuntoja approved these changes

2021-05-07 10:08 UTC, merged