enh(release): Add Centreon Anomaly Detection 20.10.1 RN
centreon/centreon-documentation pull request #711
Opened 2021-04-27 14:29 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x (master)

2021-04-27 14:31 UTC, Nohzoh approved these changes

2021-12-20 10:37 UTC, mdebauchez approved these changes

2021-12-23 17:33 UTC, tuntoja requested changes

2021-12-23 17:33 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 23, 2021`

```

2021-12-23 17:33 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

Release date: `December 23, 2021`

```

2021-12-23 17:34 UTC, tuntoja approved these changes

2021-12-23 17:43 UTC, merged