enh(installation): make user read "Secure your platform" page
centreon/centreon-documentation pull request #744
Opened 2021-05-12 11:28 UTC by cg-tw

## Description

Moved "Secure your platform" in the TOC to make it part of the chapter on installation. Moved a paragraph from "Web And Post Installation" to "Secure your platform". Added a paragraph in "Installation and first steps".

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x (master)

2021-05-12 13:55 UTC, lpinsivy commented on fr/sidebars.json
> +            "Sécurisez votre plate-forme": [
I didn't understand this change

2021-05-12 13:57 UTC, lpinsivy requested changes

2021-05-12 13:57 UTC, lpinsivy commented on en/sidebars.json
> +            "Secure your platform": [
I didn't understand this change

2021-05-12 13:57 UTC, lpinsivy commented on en/administration/secure-platform.md
> +
For me, the shortcut to the getting started chapter should not be present in the security chapter

2021-05-12 13:57 UTC, lpinsivy commented on fr/administration/secure-platform.md
> +
For me, the shortcut to the getting started chapter should not be present in the security chapter

2021-05-12 15:03 UTC, lpinsivy commented
In the past we choose to move the "Administration > Security" chapter to a level 1 to be more visible.
This PR choose to move "Security" to "Installation > Security". So the visibility will be impacted.

2021-05-24 12:47 UTC, thiuyendang approved these changes

2021-05-24 12:57 UTC, lpinsivy approved these changes

2021-05-24 13:06 UTC, merged