fix(installation): fix broken switch between FR and EN topic, and bro…
centreon/centreon-documentation pull request #748
Opened 2021-05-18 09:33 UTC by cg-tw

fix broken switch between FR and EN topic, and broken links

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-05-18 09:50 UTC, omercier approved these changes

2021-05-19 07:29 UTC, tuntoja commented on en/integrations/plugin-packs/procedures/applications-monitoring-centreon-ha.md
> +Centreon-HA is Centreon central server's high availability implementation. More information available [here](administration/centreon-ha/overview.md).
shouldn't it be this `installation/installation-of-centreon-ha/overview.md` instead of `administration/centreon-ha/overview.md` here ?

2021-05-19 07:39 UTC, tuntoja requested changes
Missing updated sidebar.json with the new path `installation/installation-of-centreon-ha/overview` for the EN language

2021-05-19 07:41 UTC, tuntoja approved these changes

2021-05-19 07:58 UTC, merged