enh(installation): improve topic on installing from a VM
centreon/centreon-documentation pull request #759
Opened 2021-05-21 16:14 UTC by cg-tw

## Description
Improved topic on installing from a VM.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-06-28 13:38 UTC, tuntoja reviewed
It may be a good idea to add that default locale is en_GB.UTF-8 and keyboard layout is gb so that user knows he should use qwerty keys to type 'ip addr'

2021-07-01 09:00 UTC, mdebauchez approved these changes

2021-07-07 11:55 UTC, tuntoja requested changes

2021-07-07 11:55 UTC, tuntoja commented on fr/installation/installation-of-a-central-server/using-virtual-machines.md
> +5. Le fichier téléchargé est une archive zippée : extrayez son contenu dans le répertoire désiré.
```suggestion
5. Le fichier téléchargé est une archive compressée: extrayez son contenu dans le répertoire désiré.
```

2021-07-07 11:55 UTC, tuntoja commented on en/installation/installation-of-a-central-server/using-virtual-machines.md
> +1. Import the **centreon-central.ova** file into VMWare. A terminal window opens: wait for the server to start. When it is ready, the terminal shows the following message:
```suggestion
1. Import the **centreon-central.ova** file into VMWare.
```

2021-07-07 11:55 UTC, tuntoja commented on fr/installation/installation-of-a-central-server/using-virtual-machines.md
> +1. Importez le fichier `centreon-central.ova` dans VMWare. Un terminal s’ouvre : attendez que le serveur démarre. Lorsque celui-ci est prêt, le terminal affiche le message suivant :
```suggestion
1. Importez le fichier `centreon-central.ova` dans VMWare. 
```

2021-07-07 11:55 UTC, tuntoja commented on fr/installation/installation-of-a-central-server/using-virtual-machines.md
> +1. Importez le fichier `centreon-central.ova` dans VMWare. Un terminal s’ouvre : attendez que le serveur démarre. Lorsque celui-ci est prêt, le terminal affiche le message suivant :
at this point there is no terminal window yet

2021-07-07 11:55 UTC, tuntoja commented on en/installation/installation-of-a-central-server/using-virtual-machines.md
> +1. Import the **centreon-central.ova** file into VMWare. A terminal window opens: wait for the server to start. When it is ready, the terminal shows the following message:
at this point there is no terminal window yet

2021-07-07 16:24 UTC, tuntoja requested changes
to discuss on thursday

2021-07-08 09:35 UTC, tuntoja approved these changes

2021-07-08 09:37 UTC, merged