enh(release): Prepare Centreon Web 20.04.14 RN
centreon/centreon-documentation pull request #763
Opened 2021-05-25 09:35 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-05-26 11:40 UTC, mdebauchez reviewed
There's a spelling mistake lign 40  in french and english : wizard and not wirard

2021-05-28 12:29 UTC, thiuyendang requested changes

2021-05-28 12:29 UTC, thiuyendang commented on en/releases/centreon-core.md
> +- [Configuration] Unserialize() are not sanitized in poller wirard
```suggestion
- [Configuration] Unserialize() are not sanitized in poller wizard
```

2021-05-28 12:29 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +- [Configuration] Unserialize() are not sanitized in poller wirard
```suggestion
- [Configuration] Unserialize() are not sanitized in poller wizard
```

2021-05-28 12:29 UTC, thiuyendang commented on en/releases/centreon-core.md
> +
```suggestion : MON-7199, missing ticket
[SECU][WEB] Packaging, remove . gitignore files
```

2021-05-28 12:29 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +
```suggestion : MON-7199, missing ticket
[SECU][WEB] Packaging, remove . gitignore files
```

```

2021-05-28 14:25 UTC, tuntoja commented on en/releases/centreon-core.md
> +[SECU][WEB] Packaging, remove . gitignore files
```suggestion
- [SECU][WEB] Packaging, remove . gitignore files

```

2021-05-28 14:27 UTC, tuntoja commented on fr/releases/centreon-core.md
> +[SECU][WEB] Packaging, remove . gitignore files
```suggestion
- [SECU][WEB] Packaging, remove . gitignore files

```

2021-06-01 15:29 UTC, thiuyendang requested changes

2021-06-01 15:29 UTC, thiuyendang commented on en/releases/centreon-core.md
> +
Missing this ticket too:https://centreon.atlassian.net/browse/MON-7368

2021-06-01 15:29 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +
Missing: https://centreon.atlassian.net/browse/MON-7368

2021-06-02 21:52 UTC, thiuyendang approved these changes

2021-06-03 08:45 UTC, tuntoja approved these changes

2021-06-03 08:52 UTC, tuntoja requested changes

2021-06-03 08:52 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- [Reporting] SQL Injection on reporting export
```suggestion
- [Reporting] SQL Injection on reporting export

```

2021-06-03 08:53 UTC, tuntoja approved these changes

2021-06-03 09:04 UTC, merged