enh(release): Prepare Centreon Web 20.10.8 RN
centreon/centreon-documentation pull request #764
Opened 2021-05-25 10:22 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-06-01 15:40 UTC, thiuyendang requested changes

2021-06-01 15:40 UTC, thiuyendang commented on en/releases/centreon-core.md
> +
Missing: https://centreon.atlassian.net/browse/MON-7368

2021-06-01 15:40 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +
Missing: https://centreon.atlassian.net/browse/MON-7368

2021-06-01 15:40 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +
Missing: https://centreon.atlassian.net/browse/MON-7199

2021-06-01 15:40 UTC, thiuyendang commented on en/releases/centreon-core.md
> +
Missing: https://centreon.atlassian.net/browse/MON-7199

2021-06-01 15:40 UTC, thiuyendang commented on en/releases/centreon-core.md
> +- [Configuration] Unserialize() are not sanitized in poller wirard
```suggestion
- [Configuration] Unserialize() are not sanitized in poller wizard
```

2021-06-01 15:40 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +- [Configuration] Unserialize() are not sanitized in poller wirard
```suggestion
- [Configuration] Unserialize() are not sanitized in poller wizard
```

2021-06-07 07:38 UTC, mdebauchez approved these changes

2021-06-07 13:14 UTC, thiuyendang approved these changes

2021-06-07 14:23 UTC, tuntoja requested changes

2021-06-07 14:23 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 7, 2021`

```

2021-06-07 14:23 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`7 Juin 2021`

```

2021-06-07 14:24 UTC, tuntoja approved these changes

2021-06-07 14:40 UTC, merged