enh(doc)ha FR translation
centreon/centreon-documentation pull request #767
Opened 2021-05-26 09:24 UTC by psamecentreon

## Description

Let's rewrite the Centreon HA introduction in FR to describe:

- what do we support
- main concepts

Schema and architecture update included

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [X] 21.04.x

2021-05-27 15:07 UTC, Sims24 requested changes

2021-05-27 15:07 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +Par conséquent, les utilisateurs, les Pollers et les Daemons interagissent constamment avec le nœud primaire.
s/Pollers/Collecteurs/ 
s/Daemons/Démons

2021-05-27 15:07 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +fonctionnent dans le même datacenter, voire dans la même baie.
s/voire/voir

2021-05-27 15:07 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +### VIP et équilibrage de charge
Remplacer par VIP et Bascule (ce n'est pas de l'équilibrage de charge)

2021-05-27 15:07 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +Centreon recommande d'utiliser des adresses VIP.
s/VIP/virtuelles/

2021-05-27 15:07 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +### Organisation du serveur
Préférer 'Placement des serveurs'

2021-05-27 15:07 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +L'utilisation d'un load balancer est une option, mais il doit prendre en charge des règles personnalisées afin d'acheminer les flux d'applications.
load balancer en italique

2021-05-27 15:07 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +* Ressources _unique_, faisant partie d'un _groupe_ et fonctionnant sur un seul nœud.
Pas d'italique pour groupe

2021-05-27 15:07 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +sauf si votre organisation exige une séparation systématique des serveurs frontaux et arrière ou si votre périmètre de surveillance
conserver frontend & backend

2021-05-27 15:09 UTC, Sims24 requested changes

2021-05-27 15:09 UTC, Sims24 commented on fr/installation/installation-of-centreon-ha/overview.md
> +* Serveur de Map Centreon
Centreon-Map

2021-05-28 13:56 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +* Colocation : comment les ressources se comportent les unes par rapport aux autres.
Done ;)

2021-05-28 13:56 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +de base de données dois être opérationnel sur les nœuds arrière, mais pas sur les nœuds frontaux.
Changed :)

2021-05-28 13:57 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +En ce qui concerne les contraintes de colocation, ils peuvent s'assurer qu'une IP virtuelle (VIP) est attribuée aux nœuds maîtres et/ou au rôle.
J'ai supprimé et/ou rôle car ça n'avait pas de sens.
Le remplacement avec primaire est OK

2021-05-28 13:57 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +fonctionnent dans le même datacenter, voire dans la même baie.
Done

2021-05-28 13:58 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +### VIP et équilibrage de charge
Oki doki. Je comprends.
Changer

2021-05-28 13:58 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +Centreon recommande d'utiliser des adresses VIP.
Done

2021-05-28 13:58 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +### Organisation du serveur
Changed

2021-05-28 13:59 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +L'utilisation d'un load balancer est une option, mais il doit prendre en charge des règles personnalisées afin d'acheminer les flux d'applications.
Done!

2021-05-28 13:59 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +* Ressources _unique_, faisant partie d'un _groupe_ et fonctionnant sur un seul nœud.
Done

2021-05-28 13:59 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +sauf si votre organisation exige une séparation systématique des serveurs frontaux et arrière ou si votre périmètre de surveillance
Consever ^^

2021-05-28 13:59 UTC, psamecentreon commented on fr/installation/installation-of-centreon-ha/overview.md
> +* Serveur de Map Centreon
Changed!

2021-05-31 15:29 UTC, Sims24 approved these changes

2021-05-31 15:29 UTC, merged