chore(version): add release notes of open tickets 21.04.1
centreon/centreon-documentation pull request #772
Opened 2021-05-27 13:36 UTC by kduret

## Description

add release notes of open tickets 21.04.1

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-05-27 14:08 UTC, kduret commented on fr/releases/centreon-os-extensions.md
> +## Centreon Open Tickets
```suggestion
## Centreon Open Ticket
```

2021-05-27 14:08 UTC, kduret commented on en/releases/centreon-os-extensions.md
> +## Centreon Open Tickets
```suggestion
## Centreon Open Ticket
```

2021-05-28 07:19 UTC, jeremyjaouen approved these changes

2021-05-28 07:27 UTC, adr-mo approved these changes

2021-05-28 08:15 UTC, tuntoja requested changes

2021-05-28 08:15 UTC, tuntoja commented on en/releases/centreon-os-extensions.md
> +
```suggestion
```

2021-05-28 09:08 UTC, tuntoja approved these changes

2021-05-28 09:09 UTC, merged