enh(rn): release notes engine 21.04.2
centreon/centreon-documentation pull request #778
Opened 2021-05-28 14:12 UTC by omercier

## Description

Release notes

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-05-28 14:32 UTC, tuntoja requested changes

2021-05-28 14:32 UTC, tuntoja commented on en/releases/centreon-core.md
> +- Engine burns 100% of the CPU when check_period set to none
```suggestion
- Engine cpu usage increased to 100% when `check_period` is set to `none`
```

2021-05-31 14:26 UTC, chgautier approved these changes

2021-06-01 07:08 UTC, jeremyjaouen approved these changes

2021-06-01 07:42 UTC, tuntoja approved these changes

2021-06-03 15:04 UTC, chgautier approved these changes

2021-06-04 09:23 UTC, tuntoja requested changes

2021-06-04 09:23 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 09:23 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 09:36 UTC, tuntoja approved these changes

2021-06-04 09:57 UTC, merged