enh(release): prepare engine 20.10.5 release notes
centreon/centreon-documentation pull request #779
Opened 2021-05-28 14:13 UTC by omercier

## Description

Release notes

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-05-28 14:32 UTC, tuntoja requested changes

2021-05-28 14:32 UTC, tuntoja commented on en/releases/centreon-core.md
> +- Engine burns 100% of the CPU when check_period set to none
```suggestion
- Engine cpu usage increased to 100% when `check_period` is set to `none`
```

2021-05-31 14:25 UTC, chgautier approved these changes

2021-06-01 07:09 UTC, jeremyjaouen approved these changes

2021-06-01 07:41 UTC, tuntoja approved these changes

2021-06-02 09:04 UTC, chgautier requested changes

2021-06-02 09:04 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

> Cette version nécessite Centreon Clib 20.10.2 et Centreon-Connector 20.10.2 ou supérieur.

```

2021-06-02 09:04 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

> This version requires Centreon Clib and Centreon-Connector versions to be 20.10.2 or higher.

```

2021-06-03 09:30 UTC, chgautier requested changes

2021-06-03 09:30 UTC, chgautier commented on en/releases/centreon-core.md
> +> This version requires Centreon Clib and Centreon-Connector versions to be 20.10.2 or higher.
```suggestion
> This version requires Centreon Clib version to be 20.10.2 or higher.
> This version requires Centreon-Connector version to be 20.10.1 or higher.
```

2021-06-03 09:30 UTC, chgautier commented on fr/releases/centreon-core.md
> +> Cette version nécessite Centreon Clib 20.10.2 et Centreon-Connector 20.10.2 ou supérieur.
```suggestion
> Cette version nécessite Centreon Clib 20.10.2 ou supérieur.
> Cette version nécessite Centreon-Connector 20.10.1 ou supérieur.
```

2021-06-03 15:04 UTC, chgautier approved these changes

2021-06-04 08:15 UTC, tuntoja requested changes

2021-06-04 08:15 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 08:15 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 08:52 UTC, tuntoja approved these changes

2021-06-04 08:53 UTC, merged