enh(rn): prepare release notes for broker 20.10.5
centreon/centreon-documentation pull request #784
Opened 2021-06-01 10:00 UTC by omercier

## Description

Release notes

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-06-01 11:51 UTC, tuntoja requested changes

2021-06-01 11:51 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- Blocage des injecions SQL depuis des *custom variables*
```suggestion
- Blocage des injections SQL depuis des *custom variables*
```

2021-06-01 16:17 UTC, chgautier requested changes

2021-06-01 16:17 UTC, chgautier commented on en/releases/centreon-core.md
> +- Limit the values of downtimes start date, end date and duration to fit the database columns' types
```suggestion
- Limit the values of downtimes' start date, end date and duration to fit the database columns' types
```

2021-06-02 07:14 UTC, chgautier approved these changes

2021-06-03 14:46 UTC, chgautier approved these changes

2021-06-04 08:12 UTC, tuntoja requested changes

2021-06-04 08:12 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 08:12 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 08:52 UTC, tuntoja approved these changes

2021-06-04 08:52 UTC, merged