enh(rn): prepare release notes for broker 20.04.14
centreon/centreon-documentation pull request #785
Opened 2021-06-01 10:01 UTC by omercier

## Description

Release notes
## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-06-01 11:50 UTC, tuntoja requested changes

2021-06-01 11:50 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- Blocage des injecions SQL depuis des *custom variables*
```suggestion
- Blocage des injections SQL depuis des *custom variables*
```

2021-06-01 16:18 UTC, chgautier approved these changes

2021-06-04 06:54 UTC, tuntoja requested changes

2021-06-04 06:54 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 06:54 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 07:04 UTC, tuntoja approved these changes

2021-06-04 07:07 UTC, merged