enh(rn): prepare release notes for centreon-broker 21.04.1
centreon/centreon-documentation pull request #786
Opened 2021-06-01 10:02 UTC by omercier

## Description

Release notes

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-06-01 11:46 UTC, tuntoja requested changes

2021-06-01 11:46 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- Blocage des injecions SQL depuis des *custom variables*
```suggestion
- Blocage des injecitons SQL depuis des *custom variables*
```

2021-06-01 16:14 UTC, chgautier approved these changes

2021-06-04 09:19 UTC, tuntoja requested changes

2021-06-04 09:19 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 09:19 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 09:36 UTC, tuntoja approved these changes

2021-06-04 09:36 UTC, merged