enh(rh): prepare release notes for centreon connectors 21.04.1
centreon/centreon-documentation pull request #794
Opened 2021-06-03 09:50 UTC by omercier

## Description

Release notes

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-06-03 15:08 UTC, chgautier approved these changes

2021-06-04 09:21 UTC, tuntoja requested changes

2021-06-04 09:21 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 09:21 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 09:21 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 09:21 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 09:36 UTC, tuntoja approved these changes

2021-06-04 09:36 UTC, merged