enh(rn): prepare release notes for centreon connectors 20.10.1
centreon/centreon-documentation pull request #795
Opened 2021-06-03 09:58 UTC by omercier

## Description

Release notes

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-06-03 14:59 UTC, chgautier requested changes

2021-06-03 14:59 UTC, chgautier commented on en/releases/centreon-core.md
> +- Compatibility with other 21.04 components.
```suggestion
- Compatibility with other 20.10 components.
```

2021-06-03 15:09 UTC, chgautier approved these changes

2021-06-04 08:13 UTC, tuntoja requested changes

2021-06-04 08:13 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 08:13 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 08:13 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 08:13 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 juin 2021`

```

2021-06-04 08:52 UTC, tuntoja approved these changes

2021-06-04 08:53 UTC, merged