enh(rn): prepare release notes for connectors 20.04.1
centreon/centreon-documentation pull request #796
Opened 2021-06-03 10:02 UTC by omercier

## Description

Release notes

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-06-03 15:07 UTC, chgautier approved these changes

2021-06-04 07:10 UTC, tuntoja requested changes

2021-06-04 07:10 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 07:10 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 4, 2021`

```

2021-06-04 07:10 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 Juin 2021`

```

2021-06-04 07:10 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`4 Juin 2021`

```

2021-06-04 07:12 UTC, tuntoja approved these changes

2021-06-04 07:21 UTC, merged