enh(release): Prepare Centreon Gorgone 20.10.4 RN
centreon/centreon-documentation pull request #800
Opened 2021-06-07 08:28 UTC by tuntoja

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-06-07 08:36 UTC, cg-tw requested changes

2021-06-07 08:36 UTC, cg-tw commented on fr/releases/centreon-core.md
> +- [anomaly] Le host id était null dans les filtres de detection.
ID, détection

2021-06-07 08:36 UTC, cg-tw commented on en/releases/centreon-core.md
> +- [anomaly] Host id was null in detection filters
ID

2021-06-07 08:47 UTC, tuntoja commented on en/releases/centreon-core.md
> +- [anomaly] Host id was null in detection filters
```suggestion
- [anomaly] Host ID was null in detection filters
```

2021-06-07 08:47 UTC, tuntoja commented on fr/releases/centreon-core.md
> +### Bugfixes
```suggestion
#### Correctifs
```

2021-06-07 08:47 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- [anomaly] Le host id était null dans les filtres de detection.
```suggestion
- [anomaly] Le host ID était null dans les filtres de détection.
```

2021-06-07 08:47 UTC, tuntoja commented on fr/releases/centreon-core.md
> +### Enhancements
```suggestion
#### Améliorations
```

2021-06-07 08:47 UTC, tuntoja commented on en/releases/centreon-core.md
> +### Enhancements
```suggestion
#### Enhancements
```

2021-06-07 08:47 UTC, tuntoja commented on en/releases/centreon-core.md
> +### Bugfixes
```suggestion
#### Bugfixes
```

2021-06-07 09:39 UTC, cg-tw approved these changes

2021-06-07 14:12 UTC, omercier requested changes

2021-06-07 14:12 UTC, omercier commented on en/releases/centreon-core.md
> +- [anomaly] Host ID was null in detection filters
```suggestion
- [Anomaly] Host ID was null in detection filters
```

2021-06-07 14:12 UTC, omercier commented on en/releases/centreon-core.md
> +- add logging option to better handle logging that could cause SQLite database to grow too large
```suggestion
- Add logging option to better handle logs that could cause SQLite database to grow too large
```

2021-06-07 14:12 UTC, omercier commented on en/releases/centreon-core.md
> +- added dependency for perl-Libssh-Session-0.8
```suggestion
- Added dependency for perl-Libssh-Session-0.8
```

2021-06-07 14:12 UTC, omercier commented on fr/releases/centreon-core.md
> +- [anomaly] Le host ID était null dans les filtres de détection.
```suggestion
- [Anomaly] Le host ID était null dans les filtres de détection.
```

2021-06-07 14:12 UTC, omercier commented on fr/releases/centreon-core.md
> +- ajout d'une option de journalisation pour éviter une taille trop grande de la base SQLite
```suggestion
- Ajout d'une option de journalisation pour éviter une taille trop grande de la base SQLite
```

2021-06-07 14:12 UTC, omercier commented on fr/releases/centreon-core.md
> +- ajout de la dépendance pour perl-Libssh-Session-0.8
```suggestion
- Ajout de la dépendance pour perl-Libssh-Session-0.8
```

2021-06-10 14:04 UTC, mdebauchez approved these changes

2021-06-10 14:36 UTC, thiuyendang approved these changes

2021-06-10 15:20 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 10, 2021`

```

2021-06-10 15:20 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`10 juin 2021`

```

2021-06-10 15:32 UTC, merged