enh(release): Prepare Centreon Gorgone 21.04.1 RN
centreon/centreon-documentation pull request #801
Opened 2021-06-07 08:44 UTC by tuntoja

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-06-07 08:49 UTC, tuntoja commented on en/releases/centreon-core.md
> +- [anomaly] Host id was null in detection filters
```suggestion
- [anomaly] Host ID was null in detection filters
```

2021-06-07 08:49 UTC, tuntoja commented on fr/releases/centreon-core.md
> +- [anomaly] Le host id était null dans les filtres de detection.
```suggestion
- [anomaly] Le host ID était null dans les filtres de détection.
```

2021-06-07 09:38 UTC, cg-tw approved these changes

2021-06-07 14:09 UTC, omercier requested changes

2021-06-07 14:09 UTC, omercier commented on en/releases/centreon-core.md
> +- [anomaly] Host ID was null in detection filters
```suggestion
- [Anomaly] Host ID was null in detection filters
```

2021-06-07 14:09 UTC, omercier commented on fr/releases/centreon-core.md
> +- [anomaly] Le host ID était null dans les filtres de détection.
```suggestion
- [Anomaly] Le host ID était null dans les filtres de détection.
```

2021-06-10 15:22 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 10, 2021`

```

2021-06-10 15:22 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`10 juin 2021`

```

2021-06-10 15:33 UTC, merged