Rework deploying a configuration
centreon/centreon-documentation pull request #805
Opened 2021-06-08 09:14 UTC by cg-tw

## Description

Reworked "deploying a configuration"

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-06-24 14:24 UTC, cg-tw commented
https://jenkins.centreon.com/job/centreon-documentation/view/change-requests/job/PR-805/Centreon_20documentation_20preview/

2021-06-28 15:36 UTC, tuntoja requested changes

2021-06-28 15:36 UTC, tuntoja commented on en/monitoring/monitoring-servers/deploying-a-configuration.md
> +      - **Reload** : when you have created, deleted or edited supervised objects
```suggestion
      - **Reload** : when you have created, deleted or edited monitored objects
```

2021-06-28 15:36 UTC, tuntoja commented on en/monitoring/monitoring-servers/deploying-a-configuration.md
> +      - **Restart** : when you have made changes to the way a poller and the central server communicate, or
the way a poller and the central server communicate together ?

2021-07-01 09:18 UTC, mdebauchez approved these changes

2021-07-01 19:27 UTC, tuntoja commented on en/monitoring/monitoring-servers/deploying-a-configuration.md
> +For changes to remote servers or pollers, you must export the configuration on the central server.
```suggestion
For changes to remote servers or pollers, you must export their configuration on the central server.
```

2021-07-01 19:27 UTC, tuntoja commented on fr/monitoring/monitoring-servers/deploying-a-configuration.md
> +Pour des changements apportés à des serveurs distants ou des collecteurs, l'export doit se faire sur le serveur central.
```suggestion
Pour des changements apportés à des serveurs distants ou des collecteurs, l'export de leur configuration doit se faire sur le serveur central.
```

2021-07-01 19:31 UTC, tuntoja approved these changes

2021-07-05 12:11 UTC, omercier requested changes

2021-07-05 12:11 UTC, omercier commented on fr/monitoring/monitoring-servers/deploying-a-configuration.md
> +    moteur de supervision de vérifier la configuration générée.
```suggestion
  - **Lancer le débogage du moteur de supervision (-v)** : Effectue une vérification de l'intégrité des fichiers de configuration du moteur de supervision.
```

2021-07-05 12:11 UTC, omercier commented on fr/monitoring/monitoring-servers/deploying-a-configuration.md
>    - **Deplacer les fichiers générés** : Déplace les fichiers de configuration du
```suggestion
  - **Déplacer les fichiers générés** : Déplace les fichiers générés d'un répertoire temporaire vers le répertoire de configuration du moteur de supervision
```

2021-07-05 12:11 UTC, omercier commented on fr/monitoring/monitoring-servers/deploying-a-configuration.md
> +    répertoire temporaire vers le répertoire du moteur de supervision.
```suggestion
```

2021-07-05 12:11 UTC, omercier commented on fr/monitoring/monitoring-servers/deploying-a-configuration.md
> +  - **Redémarrer l'ordonnanceur** : Redémarre le moteur de supervision afin d’appliquer
```suggestion
  - **Redémarrer l'ordonnanceur** : Redémarre ou recharge le moteur de supervision afin d’appliquer
```

2021-07-05 12:11 UTC, omercier commented on fr/monitoring/monitoring-servers/deploying-a-configuration.md
> +    les nouveaux fichiers de configuration.
```suggestion
    la nouvelle configuration.
```

2021-07-05 12:11 UTC, omercier commented on fr/monitoring/monitoring-servers/deploying-a-configuration.md
> +    paramétrée au niveau de la configuration du moteur de supervision.
```suggestion
    paramétrée au niveau de la configuration du collecteur.
```

2021-07-06 09:30 UTC, tuntoja approved these changes

2021-07-06 09:32 UTC, tuntoja commented on en/monitoring/monitoring-servers/deploying-a-configuration.md
> +For changes to remote servers or pollers, you must export their configuration on the central server.
it means that for any changes made to pollers that are not the central itself, their configuration should be deployed from the central server's UI, and not from the Remote server's UI. Do you confirm this @omercier (background: lots of confusion during 21.04 campaign)

2021-07-06 12:51 UTC, omercier commented on en/monitoring/monitoring-servers/deploying-a-configuration.md
> +For changes to remote servers or pollers, you must export their configuration on the central server.
I confirm, so i suggest putting it this way:

> Any configuration change on a host, a service or a poller must be performed and exported from the central server's web user interface or API.

VF:

> Tout changement de configuration sur un hôte, un service ou un collecteur devra se faire et s'exporter via l'interface utilisateur ou l'API du serveur central.

Would it not be better this way?

2021-07-06 13:58 UTC, omercier approved these changes

2021-07-06 14:14 UTC, merged