Fix broken links
centreon/centreon-documentation pull request #816
Opened 2021-06-11 15:12 UTC by cg-tw

## Description
Fix broken links

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-06-11 15:14 UTC, Nohzoh approved these changes

2021-06-11 15:19 UTC, tuntoja commented on fr/upgrade/centreon-ha/upgrade-from-centreon-failover.md
>  * Si vous êtiez en version 20.04, suivez ce [chapitre](../../upgrade/upgrade-from-19-04.html#finalisation-de-la-mise-à-jour).
```suggestion
* Si vous étiez en version 20.04, suivez ce [chapitre](../../upgrade/upgrade-from-19-04.html#finalisation-de-la-mise-à-jour).

```

2021-06-11 15:19 UTC, tuntoja commented on fr/upgrade/centreon-ha/upgrade-from-centreon-failover.md
>  Une fois que les clés SSH des utilisateurs centreon et mysql ont bien été échangées, il est recommander
```suggestion
Une fois que les clés SSH des utilisateurs centreon et mysql ont bien été échangées, il est recommandé

```

2021-06-11 15:58 UTC, thiuyendang commented on fr/upgrade/centreon-ha/upgrade-from-centreon-failover.md
>  * Si vous êtiez en version 19.10, suivez ce [chapitre](../../upgrade/upgrade-from-19-10.html#finalisation-de-la-mise-à-jour).
```suggestion
* Si vous étiez en version 19.10, suivez ce [chapitre](../../upgrade/upgrade-from-19-10.html#finalisation-de-la-mise-à-jour).

```

2021-06-14 07:05 UTC, cg-tw commented on fr/upgrade/centreon-ha/upgrade-from-centreon-failover.md
> +* [Echanges de clés SSH pour le Cluster](../../installation/installation-of-centreon-ha/installation-2-nodes.html#échanges-de-clefs-ssh)
```suggestion
* [Echanges de clefs SSH pour le Cluster](../../installation/installation-of-centreon-ha/installation-2-nodes.html#échanges-de-clefs-ssh)

```

2021-06-14 09:26 UTC, thiuyendang requested changes

2021-06-14 09:26 UTC, thiuyendang commented on fr/upgrade/centreon-ha/upgrade-from-centreon-failover.md
> +Une fois que les clés SSH des utilisateurs centreon et mysql ont bien été échangées, il est recommandé
```suggestion
Une fois que les clefs SSH des utilisateurs centreon et mysql ont bien été échangées, il est recommandé

```

2021-06-14 09:59 UTC, thiuyendang approved these changes

2021-06-14 10:00 UTC, merged