Add(mp)c advisor api monitoring procedure
centreon/centreon-documentation pull request #817
Opened 2021-06-14 13:29 UTC by Sims24

## Description

New monitoring procedure to chech Container metrics through cAdvisor. 

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-06-15 08:17 UTC, cg-tw requested changes

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +Le Pack cAdvisor API propose différentes règles de découvertes de Service.
```suggestion
Le Pack cAdvisor API propose différentes règles de découverte de Service.
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +### Métriques colletées
```suggestion
### Métriques collectées
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +| Rule                                    | Description                                            |
table is in English

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +<!--DOCUSAURUS_CODE_TABS-->
the whole section is in English

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +Un conteneur ou un démon cAdvisor doit être en cours d'execution et disponible. La
```suggestion
Un conteneur ou un démon cAdvisor doit être en cours d'exécution et disponible. La 
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +du port TCP/8080 port. Attention, selon la configuration le port peut être différent.
```suggestion
du port TCP/8080. Attention, selon la configuration le port peut être différent. 
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +<!--Online IMP Licence & IT-100 Editions-->
The name of the tabs is in English

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +2. Dans l'interface de Centreon, installer le Plugin Pack *cAdvisor API* depuis la page "Configuration > Plugin Packs > Manager"
```suggestion
2. Dans l'interface de Centreon, installer le Plugin Pack *cAdvisor API* depuis la page `Configuration > Plugin Packs > Manager`
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +2. Installer le Plugin sur chaque Collecteur allant superviser des containers via cAdvisor:
Points 1 and 2 are the same, apart from some lowercase/uppercase characters. Is that intended?

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +3. Dans l'interface de Centreon, installer le Plugin Pack *cAdvisor API* depuis la page "Configuration > Plugin Packs > Manager"
```suggestion
3. Dans l'interface de Centreon, installer le Plugin Pack *cAdvisor API* depuis la page `Configuration > Plugin Packs > Manager`
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +### Host configuration
```suggestion
### Configuration de l'hôte
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +Ajouter un Hôte depuis le menu `Configuration > Hosts` et selectionner le Modèle `Cloud-cAdvisor-API`.
```suggestion
Ajouter un Hôte depuis le menu `Configuration > Hosts` et sélectionner le Modèle `Cloud-cAdvisor-API`.
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +| Mandatory | Macro                     | Description                                       | Default value                    |
Table is in English

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +Le conteneur ciblé à le nom gray (`--filter-name='^gray$'`) et nous faisons en sorte d'utiliser son nom comme instance pour les
```suggestion
Le conteneur ciblé a le nom gray (`--filter-name='^gray$'`) et nous faisons en sorte d'utiliser son nom comme instance pour les 
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +l'API cAdvisor
```suggestion
l'API cAdvisor.
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +L'utilisation du flag `--debug` permet d'afficher des détails utiles au diagnostique.
```suggestion
L'utilisation du flag `--debug` permet d'afficher des détails utiles au diagnostic.
```

2021-06-15 08:17 UTC, cg-tw commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +est erronné (typo ou conteneur arrêté).
```suggestion
est erronné (faute de frappe, ou conteneur arrêté).
```

2021-06-16 15:18 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
> +<!--DOCUSAURUS_CODE_TABS-->
It's on purpose

2021-06-21 08:30 UTC, cg-tw approved these changes

2021-06-21 12:53 UTC, merged