enh(release): Add Centreon Web 21.04.3 RN
centreon/centreon-documentation pull request #836
Opened 2021-06-24 15:03 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-06-25 13:19 UTC, mdebauchez requested changes

2021-06-25 13:19 UTC, mdebauchez commented on en/releases/centreon-core.md
> +- [ACL] Display message if user doesn't have rights to access to a page
We must remove this ticket, it had a bad fix version and is not fixed in this version

2021-06-25 13:19 UTC, mdebauchez commented on en/releases/centreon-core.md
> +- [Configuration] InfluxDB configuration columns are deleted in Broker from
I think it's 'form' and not 'from'

2021-06-25 13:19 UTC, mdebauchez commented on fr/releases/centreon-core.md
> +- [Configuration] InfluxDB configuration columns are deleted in Broker from
I think it's 'form' and not 'from'

2021-06-28 09:43 UTC, mdebauchez approved these changes

2021-06-28 13:41 UTC, tuntoja requested changes

2021-06-28 13:41 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 28, 2021`

```

2021-06-28 13:41 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`28 juin 2021`

```

2021-06-28 13:50 UTC, merged