enh(release): Add Centreon Web 20.10.9 RN
centreon/centreon-documentation pull request #838
Opened 2021-06-25 09:24 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-06-28 14:32 UTC, mdebauchez requested changes

2021-06-28 14:32 UTC, mdebauchez commented on en/releases/centreon-core.md
> +- [Configuration] InfluxDB configuration columns are deleted in Broker from
I think it's 'form' and not 'from'

2021-06-28 14:32 UTC, mdebauchez commented on fr/releases/centreon-core.md
> +- [Configuration] InfluxDB configuration columns are deleted in Broker from
I think it's 'form' and not 'from'

2021-06-29 07:22 UTC, mdebauchez approved these changes

2021-06-30 07:11 UTC, tuntoja requested changes

2021-06-30 07:11 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`June 30, 2021`

```

2021-06-30 07:11 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`30 juin 2021`

```

2021-06-30 07:25 UTC, tuntoja approved these changes

2021-06-30 07:25 UTC, merged