Add info about the LC_ALL variable
centreon/centreon-documentation pull request #844
Opened 2021-06-29 13:28 UTC by cg-tw

## Description

Add info to prevent problems with the Anomaly Detection module.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-06-30 12:58 UTC, omercier requested changes

2021-06-30 12:58 UTC, omercier commented on en/monitoring/anomaly-detection.md
> +  - The variable [LC_ALL](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) must not be set, or be set to `C`. To check the value of this variable, enter:
```suggestion
  - The SHELL environment variable [LC_ALL](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) must not be set, or be set to `C`. To check the value of this variable, enter:
```

2021-06-30 12:58 UTC, omercier commented on en/monitoring/anomaly-detection.md
> +    echo $ LC_ALL
```suggestion
    echo $LC_ALL
```

2021-06-30 12:58 UTC, omercier commented on fr/monitoring/anomaly-detection.md
> +  - La variable [LC_ALL](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) ne doit pas être renseignée ou bien avoir la valeur `C`. Pour vérifier la valeur de c
```suggestion
  - La variable d'environnement SHELL [LC_ALL](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) ne doit pas être renseignée ou bien avoir la valeur `C`. Pour vérifier la valeur de cette variable, entrez :
```

2021-06-30 12:58 UTC, omercier commented on fr/monitoring/anomaly-detection.md
> +      echo $ LC_ALL
```suggestion
      echo $LC_ALL
```

2021-06-30 13:04 UTC, omercier approved these changes

2021-07-01 08:24 UTC, tuntoja requested changes

2021-07-01 08:24 UTC, tuntoja commented on fr/monitoring/anomaly-detection.md
> +  - La variable d'environnement SHELL [LC_ALL](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) ne doit pas être renseignée ou bien avoir la valeur `C`. Pour v
```suggestion
  - La variable d'environnement SHELL [LC_ALL](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) ne doit pas être définie ou bien avoir la valeur `C`. Pour vérifier la valeur de cette variable, entrez :
```

2021-07-01 08:32 UTC, tuntoja approved these changes

2021-07-01 08:41 UTC, merged