add(epp): centreon-nsclient tutorial
centreon/centreon-documentation pull request #852
Opened 2021-07-07 13:19 UTC by thibaults-centreon

## Description

This tutorial aims to provide support for the centreon-nsclient agent installation and usage

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x (master)

2021-07-09 13:15 UTC, jeanrenemoyap commented on en/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial.md
> +Both the installer and the packaged Centreon Plugins are available on the on the [centreon-nsclient](https://github.com/centreon/centreon-nsclient-build/releases)
The expression 'on the' appear twice

2021-07-09 13:16 UTC, jeanrenemoyap commented on en/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial.md
> +#### Configurer l'accès Rest HTTPS
in English

2021-07-09 13:46 UTC, jeanrenemoyap commented on fr/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial.md
> +les dernières versions des exécutables suivants suivant votre environnement (x86 ou x64):
s/les dernières versions des exécutables suivants suivant votre environnement/les dernières versions des exécutables suivants en fonction de votre environnement/

2021-07-09 13:48 UTC, jeanrenemoyap commented on fr/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial.md
> +* saisissez l'adresse IP des Collecteurs Centreon autorisés à superviser le serveur:
s/saisissez/Saisissez/

2021-07-09 13:52 UTC, jeanrenemoyap requested changes
Please find some comments

Cheers!

2021-07-13 08:52 UTC, Sims24 approved these changes

2021-07-13 09:17 UTC, merged