enh(release): release notes for centreon-autodiscovery 21.04.1
centreon/centreon-documentation pull request #857
Opened 2021-07-09 09:02 UTC by omercier

## Description
Prepare autodisco 21.04.1 rn

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-07-09 09:26 UTC, cg-tw requested changes

2021-07-09 09:26 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Avertir l'utilisateur que les changements non sauvegardés seront perdus en quittant l'étidion d'une tâche
```suggestion
- Avertir l'utilisateur que les changements non sauvegardés seront perdus en quittant l'édition d'une tâche
```

2021-07-09 09:26 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Traduction de l'affichage des conditions et affichage d'une version grammaticalement des opérateurs de comparaison
```suggestion
- Traduction de l'affichage des conditions et affichage d'une version grammaticalement correcte des opérateurs de comparaison
```

2021-07-19 13:04 UTC, mdebauchez approved these changes

2021-07-19 14:07 UTC, cg-tw approved these changes

2021-07-19 15:10 UTC, chgautier requested changes

2021-07-19 15:10 UTC, chgautier commented on en/releases/centreon-commercial-extensions.md
```suggestion

`July 19, 2021`

```

2021-07-19 15:10 UTC, chgautier commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

`19 juillet 2021`

```

2021-07-19 15:36 UTC, merged