Prepare autodisco 20.04.9 rn
centreon/centreon-documentation pull request #860
Opened 2021-07-12 06:49 UTC by omercier

## Description

Release notes

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-07-12 07:41 UTC, cg-tw requested changes

2021-07-12 07:41 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Impossibilité d'enregistrer des règles de découvertes de services avec beaucoup de macros
```suggestion
- Impossibilité d'enregistrer des règles de découverte de services avec beaucoup de macros
```

2021-07-12 07:41 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Impossibilité d'ajouter des services si une macro dans la règle de découverte contient des *single quotes* (')
```suggestion
- Impossibilité d'ajouter des services si une macro dans la règle de découverte contient des guillemets simples (')
```

2021-07-20 15:34 UTC, mdebauchez approved these changes

2021-07-20 15:41 UTC, cg-tw requested changes

2021-07-20 15:41 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Suppression des modificateurs *association/property* ayant comme destination `host.macros` car ils ne fonctionnent p
```suggestion
- Suppression des modificateurs *association/property* ayant comme destination `host.macros` car ils ne fonctionnent
```

2021-07-20 15:41 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +as correctement (utiliser les modificateurs *Macro* à la place)
```suggestion
pas correctement (utiliser les modificateurs *Macro* à la place)
```

2021-07-21 12:56 UTC, chgautier requested changes

2021-07-21 12:56 UTC, chgautier commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

`July 21, 2021`

```

2021-07-21 12:56 UTC, chgautier commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

`21 juillet 2021`

```

2021-07-21 12:56 UTC, chgautier approved these changes

2021-07-21 13:05 UTC, merged