Prepare autodisco 20.10.4 rn
centreon/centreon-documentation pull request #861
Opened 2021-07-12 06:53 UTC by omercier

## Description

Release notes

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-07-12 07:41 UTC, cg-tw requested changes

2021-07-12 07:41 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Impossibilité d'ajouter des services si une macro dans la règle de découverte contient des *single quotes* (')
```suggestion
- Impossibilité d'ajouter des services si une macro dans la règle de découverte contient des guillemets simples (')
```

2021-07-12 07:41 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Impossibilité d'enregistrer des règles de découvertes de services avec beaucoup de macros
```suggestion
- Impossibilité d'enregistrer des règles de découverte de services avec beaucoup de macros
```

2021-07-12 07:41 UTC, cg-tw commented on en/releases/centreon-commercial-extensions.md
> +- Prevent usage of discovery.credentials attributes (except Macro) in host discovery mappers
```suggestion
- Prevent usage of `discovery.credentials` attributes in host discovery mappers (except Macro)
```

2021-07-13 07:46 UTC, mdebauchez approved these changes

2021-07-13 10:00 UTC, cg-tw requested changes

2021-07-13 10:00 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +- Suppression des modificateurs *association/property* ayant comme destination `host.macros` car ils ne fonctionnent p
```suggestion
- Suppression des modificateurs *association/property* ayant comme destination `host.macros` car ils ne fonctionnent
```

2021-07-13 10:00 UTC, cg-tw commented on fr/releases/centreon-commercial-extensions.md
> +as correctement (utiliser les modificateurs *Macro* à la place)
```suggestion
pas correctement (utiliser les modificateurs *Macro* à la place)
```

2021-07-13 10:04 UTC, cg-tw approved these changes

2021-07-13 10:05 UTC, thiuyendang approved these changes

2021-07-13 16:06 UTC, tuntoja requested changes

2021-07-13 16:06 UTC, tuntoja commented on en/releases/centreon-commercial-extensions.md
> +
```suggestion

`July 13, 2021`

```

2021-07-13 16:06 UTC, tuntoja commented on fr/releases/centreon-commercial-extensions.md
> +
```suggestion

`13 juillet 2021`

```

2021-07-13 16:07 UTC, tuntoja approved these changes

2021-07-13 16:07 UTC, merged