Prepare broker 20.10.6 / engine 20.10.6 / clib 20.10.3 / connectors 20.10.2 release notes
centreon/centreon-documentation pull request #862
Opened 2021-07-12 14:59 UTC by omercier

## Description

Release notes **for all poller components**

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-07-13 07:46 UTC, cg-tw requested changes

2021-07-13 07:46 UTC, cg-tw commented on fr/releases/centreon-core.md
> +- Compilation in C++14 with conan-center: bintray has stopped. We had to switch to the conan-center. And then our conan dependencies had to upgrade and then we had to switch to C++14. So here is the
```suggestion
- Compilation in C++14 with conan-center: bintray has stopped. We had to switch to conan-center. And then our conan dependencies had to be upgraded and then we had to switch to C++14. So here is the corresponding compilation.
```

2021-07-13 07:46 UTC, cg-tw commented on fr/releases/centreon-core.md
> +- Start/Stop process\_manager mechanism is rewritten and much more simpler. The consequences are that there are less dead locks in the processes management.
```suggestion
- Start/Stop process\_manager mechanism is rewritten and much simpler. The consequences are that there are less deadlocks in the processes management.
```

2021-07-13 18:46 UTC, chgautier requested changes

2021-07-15 08:35 UTC, omercier commented on en/releases/centreon-core.md
> +
It is a duplicate of: `Sometimes Engine cannot reconnect to the central broker when cbd is restarted`

2021-07-15 08:37 UTC, omercier commented on fr/releases/centreon-core.md
> +
Same as in English version: it duplicates `Sometimes Engine cannot reconnect to the central broker when cbd is restarted
`

2021-07-15 13:43 UTC, chgautier requested changes

2021-07-15 13:43 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

`July 15, 2021`

```

2021-07-15 13:43 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

`July 15, 2021`

```

2021-07-15 13:43 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

`July 15, 2021`

```

2021-07-15 13:43 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

`July 15, 2021`

```

2021-07-15 13:43 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

`July 15, 2021`

```

2021-07-15 13:43 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

`15 juillet 2021`

```

2021-07-15 13:43 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

`15 juillet 2021`

```

2021-07-15 13:43 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

`15 juillet 2021`

```

2021-07-15 13:43 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

`15 juillet 2021`

```

2021-07-15 13:43 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

`15 juillet 2021`

```

2021-07-15 13:47 UTC, chgautier approved these changes

2021-07-15 13:49 UTC, chgautier requested changes

2021-07-15 13:49 UTC, chgautier commented on en/releases/centreon-core.md
> +`July 15, 2021`
```suggestion
```

2021-07-15 13:49 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion
```

2021-07-15 13:58 UTC, chgautier requested changes

2021-07-15 13:58 UTC, chgautier commented on en/releases/centreon-core.md
> +## 20.10.3
```suggestion
### 20.10.3
```

2021-07-15 13:58 UTC, chgautier commented on en/releases/centreon-core.md
> +### Bug fixes
```suggestion
#### Bug fixes
```

2021-07-15 13:58 UTC, chgautier commented on en/releases/centreon-core.md
> +## 20.10.2
```suggestion
### 20.10.2
```

2021-07-15 13:58 UTC, chgautier commented on en/releases/centreon-core.md
> +### Enhancement
```suggestion
#### Enhancements
```

2021-07-15 13:58 UTC, chgautier commented on en/releases/centreon-core.md
> +## 20.10.1
```suggestion
### 20.10.1
```

2021-07-15 13:58 UTC, chgautier commented on en/releases/centreon-core.md
> +### Bugfixes
```suggestion
#### Bugfixes
```

2021-07-15 13:58 UTC, chgautier commented on en/releases/centreon-core.md
> +## 20.10.0
```suggestion
### 20.10.0
```

2021-07-15 13:58 UTC, chgautier commented on en/releases/centreon-core.md
> +### Bugfixes
```suggestion
#### Bugfixes
```

2021-07-15 13:58 UTC, chgautier commented on fr/releases/centreon-core.md
> +## 20.10.3
```suggestion
### 20.10.3
```

2021-07-15 13:58 UTC, chgautier commented on fr/releases/centreon-core.md
> +### Bug fixes
```suggestion
#### Bug fixes
```

2021-07-15 13:58 UTC, chgautier commented on fr/releases/centreon-core.md
> +## 20.10.2
```suggestion
### 20.10.2
```

2021-07-15 13:58 UTC, chgautier commented on fr/releases/centreon-core.md
> +### Enhancement
```suggestion
#### Enhancements
```

2021-07-15 13:58 UTC, chgautier commented on fr/releases/centreon-core.md
> +## 20.10.1
```suggestion
### 20.10.1
```

2021-07-15 13:58 UTC, chgautier commented on fr/releases/centreon-core.md
> +### Bugfixes
```suggestion
#### Bugfixes
```

2021-07-15 13:58 UTC, chgautier commented on fr/releases/centreon-core.md
> +## 20.10.0
```suggestion
### 20.10.0
```

2021-07-15 13:58 UTC, chgautier commented on fr/releases/centreon-core.md
> +### Bugfixes
```suggestion
#### Bugfixes
```

2021-07-15 14:01 UTC, chgautier approved these changes

2021-07-15 14:08 UTC, merged