reorg(integration)new-layout
centreon/centreon-documentation pull request #869
Opened 2021-07-15 11:55 UTC by Sims24

## Description

New layout for third-party integrations. 

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x (master)

2021-09-10 08:12 UTC, tanguyvda requested changes

2021-09-10 08:12 UTC, tanguyvda commented on fr/integrations/introduction-integrations.md
> +l'ajout de fonctionnalité permettant l'ouverture manuelle de ticket sur la base des
```suggestion
l'ajout de fonctionnalités permettant l'ouverture manuelle de ticket sur la base des 
```

2021-09-10 08:12 UTC, tanguyvda commented on fr/integrations/introduction-integrations.md
> +et de traitement des alertes sur vos équipements et applicatifs critiques.
```suggestion
- [Centreon Plugin Packs](../integrations/plugin-packs/introduction.html), permet la 
récupération d'informations de supervision de systèmes tiers afin d'utiliser 
Centreon comme une tour de contrôle devenant le point unique de gestion 
et de traitement des alertes de vos équipements et applicatifs critiques.
```

2021-09-10 08:12 UTC, tanguyvda commented on fr/integrations/introduction-integrations.md
> +et de traitement des alertes sur vos équipements et applicatifs critiques.
3 times "permet" doesn't feel good

2021-09-10 08:12 UTC, tanguyvda commented on fr/integrations/introduction-integrations.md
> +des outils spécialisées dans la gestion des événements en terme de qualification,
```suggestion
des outils spécialisés dans la gestion des événements en terme de qualification, 
```

2021-09-10 08:12 UTC, tanguyvda commented on fr/integrations/introduction-integrations.md
> +afin de permettre une gestion de l'incident et des actions corrective au plus proche
```suggestion
afin de permettre une gestion de l'incident et des actions correctives au plus proche 
```

2021-09-10 08:12 UTC, tanguyvda commented on fr/integrations/introduction-integrations.md
> +afin d'alerter de manière optimale les bonnes personnes au travers de mutliples modes
```suggestion
afin d'alerter de manière optimale les bonnes personnes au travers de multiples modes 
```

2021-09-10 08:12 UTC, tanguyvda commented on fr/sidebars.json
>                  ],
```suggestion
                    "integrations/event-management/sc-servicenow-mid-server",
                    "integrations/event-management/sc-kafka-events"
                ],
```

2021-09-10 08:12 UTC, tanguyvda commented on fr/sidebars.json
> +                    "integrations/event-management/sc-servicenow",
should be converted to sc-service-now-events as soon as the right file is in place (see previous review comment about replacing doc in french doc)

2021-09-13 16:23 UTC, ponchoh commented on en/integrations/introduction-integrations.md
> +presenting, or extending the usage on top of your monitoring data.
Options for "on top of":

1. in addition to
2. including

2021-09-14 08:29 UTC, Sims24 commented on en/integrations/introduction-integrations.md
> +presenting, or extending the usage on top of your monitoring data.
I rephrased it.

2021-09-14 08:29 UTC, Sims24 commented on en/integrations/introduction-integrations.md
> +purpose of each of these sections:
I rephrased it.

2021-09-14 11:07 UTC, tanguyvda approved these changes

2021-09-14 13:58 UTC, merged