enh(mp): Squid SNMP
centreon/centreon-documentation pull request #872
Opened 2021-07-16 15:35 UTC by itoussies

## Description

Documentation enhancements using the new metrics naming convention and new monitoring procedure.

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x (master)

2021-07-18 10:20 UTC, itoussies commented
NOT READY

2021-07-19 13:50 UTC, thibaults-centreon requested changes

2021-07-19 13:50 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +| icp.traffic.out.bitspersecond | traffic out: %s %s/s |
Missing unit column

2021-07-19 13:50 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +This command would trigger a WARNING alarm if the *cpu* utilizationis reported
```suggestion
This command would trigger a WARNING alarm if the *cpu* utilization is reported 
```

2021-07-19 13:50 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +`--help` parameter to thecommand:
```suggestion
`--help` parameter to the command:
```

2021-07-19 13:50 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +`--list-mode` parameter to thecommand:
```suggestion
`--list-mode` parameter to the command:
```

2021-07-19 13:50 UTC, thibaults-centreon commented on en/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +the mode/plugin to work properly.
```suggestion
the mode/Plugin to work properly.
```

2021-07-19 13:50 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +| icp.traffic.out.bitspersecond | traffic out: %s %s/s |
missing unit column

2021-07-19 13:50 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +Tous les modes disponibles peuvent être affichés en ajoute le paramètre
```suggestion
Tous les modes disponibles peuvent être affichés en ajoutant le paramètre 
```

2021-07-19 13:50 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +ou que la communauté SNMP configurée n'est pascorrecte.
```suggestion
Si vous obtenez ce message, cela signifie le collecteur Centreon ne parvient pas
à contacter le serveur sur le port 161 (firewall ou autre équipement en coupure)
ou que la communauté SNMP configurée n'est pas correcte.
```

2021-07-19 13:50 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/applications-squid-snmp.md
> +faire fonctionner le mode/plugin.
```suggestion
faire fonctionner le mode/Plugin.
```

2021-07-30 10:16 UTC, thibaults-centreon approved these changes

2021-07-30 10:19 UTC, merged