enh(mp): ClamAV SSH
centreon/centreon-documentation pull request #873
Opened 2021-07-16 15:36 UTC by itoussies

## Description

Documentation enhancements using the new metrics naming convention and new monitoring procedure.

Any relevant information should be added to help reviewers.

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x (master)

2021-07-18 10:20 UTC, itoussies commented
NOT READY

2021-07-19 13:44 UTC, thibaults-centreon requested changes

2021-07-19 13:44 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
> +macros hôtes.
```suggestion
Deux méthodes de connexion SSH sont possibles:
* soit en échangeant la clé SSH publique de l'utilisateur `centreon-engine` du collecteur Centreon
* soit en définissant votre utilisateur et votre mot de passe directement dans les Macros d'Hôtes.
```

2021-07-19 13:44 UTC, thibaults-centreon commented on fr/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
> +du serveur cible avec `ssh` or `plink` sur le Poller Centreon.
```suggestion
Lors de l'utilisation des backends SSH `ssh` ou `plink` dans les contrôles, il est nécessaire de lancer la commande
manuellement une première fois afin de valider le *fingerprint* du serveur distant.
```

2021-07-30 10:16 UTC, thibaults-centreon approved these changes

2021-07-30 10:20 UTC, merged