MON-10791-licenses Add topic about licenses
centreon/centreon-documentation pull request #877
Opened 2021-07-20 13:45 UTC by cg-tw

## Description

Add topic about licenses.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-07-21 15:52 UTC, mdebauchez commented on en/administration/licenses.md
> +- [MBI](https://docs.centreon.com/current/en/reporting/introduction.html)
I think you should put either all the links to the module introduction pages (best idea I think) or all the links to the installation pages
But it's weird to have only one link to introduction and others to installation

2021-07-21 15:52 UTC, mdebauchez commented on en/administration/licenses.md
> +    - If your token contains one license, a tick mark is displayed next to the **Add** button.
Are you sure ? I never saw it. I just have a success message

2021-07-21 15:52 UTC, mdebauchez commented on en/administration/licenses.md
> +ll /etc/centreon/licenses.d
ll /etc/centreon/license.d/

2021-07-26 10:57 UTC, lpinsivy requested changes

2021-07-26 10:57 UTC, lpinsivy commented on en/administration/licenses.md
> +- [MBI](https://docs.centreon.com/current/en/reporting/installation.html)
- [Enterprise Plugin Packs](https://docs.centreon.com/current/en/monitoring/pluginpacks.html#installation)
- [Auto Discovery](https://docs.centreon.com/current/en/monitoring/discovery/installation.html)
- [Anomaly Detection](https://docs.centreon.com/current/en/monitoring/anomaly-detection.html)
- [Service Mapping (BAM)](https://docs.centreon.com/current/en/service-mapping/install.html)
- [Graphical views (MAP)](https://docs.centreon.com/current/en/graph-views/install.html)
- [Reporting (MBI)](https://docs.centreon.com/current/en/reporting/installation.html)

2021-07-26 10:57 UTC, lpinsivy commented on en/administration/licenses.md
> +### Offline licenses
Should be better tu use "tab", isn't it?

2021-07-26 10:57 UTC, lpinsivy commented on en/administration/licenses.md
> +chmod 644 /etc/centreon/license.d/*
chmod 640 /etc/centreon/license.d/*

2021-07-26 10:57 UTC, lpinsivy commented on en/administration/licenses.md
> +```
```shell
ls -lah /etc/centreon/license.d/
```

2021-07-26 10:57 UTC, lpinsivy commented on en/administration/licenses.md
> +    SELECT COUNT(*) FROM host WHERE host_register='1';
Should be easier to go on "Configuration > Hosts > Hosts" and check the limit in the pagination select box

2021-07-26 10:57 UTC, lpinsivy commented on fr/administration/licenses.md
> +## Comment obtenir une licence?
Apply previous comments from EN part

2021-07-27 11:34 UTC, lpinsivy approved these changes

2021-07-27 13:42 UTC, mdebauchez approved these changes

2021-07-27 13:51 UTC, merged