doc(php): add procedure to upgrade to php 7.3 on 20.04.x
centreon/centreon-documentation pull request #891
Opened 2021-07-23 07:56 UTC by kduret

## Description

add procedure to upgrade php on 20.04.x

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-07-26 12:03 UTC, jeremyjaouen approved these changes

2021-07-26 13:02 UTC, cg-tw requested changes

2021-07-26 13:02 UTC, cg-tw commented on fr/administration/secure-platform.md
> +
ajouter qu'il doit faire `rpm -qa | grep centreon` pour connaître la version de ses composants

2021-07-26 13:02 UTC, cg-tw commented on en/administration/secure-platform.md
> +
Add that they must do `rpm -qa | grep centreon` to know their versions

2021-07-28 08:56 UTC, cg-tw approved these changes

2021-08-06 13:01 UTC, tuntoja requested changes

2021-08-06 13:01 UTC, tuntoja commented on en/administration/secure-platform.md
> +    * centreon-web >= 20.04.17
```suggestion
    * centreon-web >= 20.04.18
```

2021-08-06 13:01 UTC, tuntoja commented on fr/administration/secure-platform.md
> +    * centreon-web >= 20.04.17
```suggestion
    * centreon-web >= 20.04.18
```

2021-08-06 14:39 UTC, tuntoja approved these changes

2021-08-25 13:08 UTC, adr-mo approved these changes

2021-09-28 15:58 UTC, thiuyendang requested changes

2021-09-28 15:58 UTC, thiuyendang commented on en/administration/secure-platform.md
> +    * centreon-web >= 20.04.18
```suggestion
    * centreon-web >= 20.04.19
```

2021-09-28 15:58 UTC, thiuyendang commented on fr/administration/secure-platform.md
> +    * centreon-web >= 20.04.18
```suggestion
    * centreon-web >= 20.04.19
```

2022-01-05 09:37 UTC, kduret commented
mbi prequisite version will not be released on 20.04

2022-01-05 09:37 UTC, closed without merging