enh(release): Add Centreon Web 20.04.17 RN
centreon/centreon-documentation pull request #898
Opened 2021-07-27 09:03 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-07-28 08:37 UTC, mdebauchez approved these changes

2021-07-30 14:11 UTC, chgautier requested changes

2021-07-30 14:11 UTC, chgautier commented on fr/releases/centreon-core.md
> +- [LDAP] Fixed LDAP auto-sync always skip
```suggestion
- [LDAP] Fixed LDAP auto-sync is always skipped
```

2021-07-30 14:11 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

`30 juillet 2021`

```

2021-07-30 14:11 UTC, chgautier commented on en/releases/centreon-core.md
> +- [LDAP] Fixed LDAP auto-sync always skip
```suggestion
- [LDAP] Fixed LDAP auto-sync is always skipped
```

2021-07-30 14:11 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

`July 30, 2021`

```

2021-07-30 14:25 UTC, chgautier approved these changes

2021-07-30 14:26 UTC, chgautier requested changes

2021-07-30 14:26 UTC, chgautier commented on fr/releases/centreon-core.md
> +#### Bugfixes
```suggestion
#### Correctifs
```

2021-07-30 14:28 UTC, chgautier approved these changes

2021-07-30 14:36 UTC, merged