Autodisco AWS use case in Getting Started
centreon/centreon-documentation pull request #901
Opened 2021-07-28 08:44 UTC by cg-tw

## Description

Autodisco AWS use case in Getting Started

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-07-29 07:38 UTC, omercier requested changes

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +1. Make sure your [license](../administration/licenses.html) is installed. (The Auto Discovery module requires a valid license. It is included in the free [IT-100](IT100.html) license.)
```suggestion
1. The Auto Discovery module requires a valid license. Make sure your [commercial](../administration/licenses.html) or [IT-100](IT100.html) license is installed.
```

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +
I am not a fan of putting several sentences inside parentheses :-)

2021-07-29 07:38 UTC, omercier commented on fr/getting-started/autodisco-aws.md
> +1. Assurez-vous que votre [licence](../administration/licenses.html) est installée. (Le module d'autodécouverte demande une licence valide. Le module est inclus dans la licence gratuite [IT-100](IT10
```suggestion
1. Le module d'autodécouverte demande une licence valide. Assurez-vous que votre licence [commerciale](../administration/licenses.html) ou [IT-100](IT100.html) est installée.
```

2021-07-29 07:38 UTC, omercier commented on fr/getting-started/autodisco-aws.md
> +6. Cliquez sur le `+` dans le coin supérieur droit du Plugin Pack. Le Plugin Pack a maintenant une bordure verte et une coche dans le coin supérieur droit.
```suggestion
6. Cliquez sur le `+` dans le coin supérieur droit du Plugin Pack. Le Plugin Pack a maintenant une bordure verte et une coche dans le coin supérieur droit : il est installé !
```

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +6. Click on the `+` sign in the top right corner of the Plugin Pack. The Plugin Pack now has a green border and a tick mark in the top right corner.
```suggestion
6. Click on the `+` sign in the top right corner of the Plugin Pack. The Plugin Pack now has a green border and a tick mark in the top right corner: it is now installed!
```

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +    ![image](../assets/getting-started/aws_provider.png)
```suggestion
    ![image](../assets/getting-started/aws_provider.PNG)
```

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +    ![image](../assets/getting-started/aws_provider.png)
Or, what would be best: rename the file aws-provider.png and adapt the reference here

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +
The image below is not displayed in the jenkins preview because of the CAPS "PNG" in the filename

2021-07-29 07:38 UTC, omercier commented on fr/getting-started/autodisco-aws.md
> +    ![image](../assets/getting-started/aws_provider.png)
```suggestion
    ![image](../assets/getting-started/aws_provider.PNG)
```

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +    ![image](../assets/getting-started/aws-listofjobs.png)
```suggestion
    ![image](../assets/getting-started/aws-listofjobs.PNG)
```

2021-07-29 07:38 UTC, omercier commented on fr/getting-started/autodisco-aws.md
> +    ![image](../assets/getting-started/aws-listofjobs.png)
```suggestion
    ![image](../assets/getting-started/aws-listofjobs.PNG)
```

2021-07-29 07:38 UTC, omercier commented on fr/getting-started/autodisco-aws.md
> +11. Survolez la coche verte puis cliquez sur **Display the job result** (l'icône flèche). Une liste d'hôtes apparaît.
```suggestion
11. Survolez la ligne correspondant à la tâche qui vient de se terminer puis cliquez sur **Display the job result** (l'icône flèche). Une liste d'hôtes apparaît.
```

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +11. Hover over the green tick mark and then click **Display the job result** (the arrow icon). A list of hosts appears.
```suggestion
11. Hover over the row of the job that has just ended and then click **Display the job result** (the arrow icon). A list of hosts appears.
```

2021-07-29 07:38 UTC, omercier commented on en/getting-started/autodisco-aws.md
> +    ![image](../assets/getting-started/aws-success.png)
Why not a screenshot with the mouse over the job's row in order to make the "Display job result" arrow appear in the document?

2021-07-29 08:58 UTC, omercier approved these changes

2021-08-03 16:05 UTC, chgautier requested changes

2021-08-03 16:05 UTC, chgautier commented on fr/getting-started/autodisco-aws.md
> +Vous devez disposer des informations d'identification pour le groupe d'instances AWS que vous souhaitez superviser (nom, AWS Acces Key et AWS Secret Key), et de la région dans laquelle se trouvent vo
```suggestion
Vous devez disposer des informations d'identification pour le groupe d'instances AWS que vous souhaitez superviser (nom, AWS Access Key et AWS Secret Key), et de la région dans laquelle se trouvent vos instances.
```

2021-08-03 16:05 UTC, chgautier commented on fr/getting-started/autodisco-aws.md
> +5. Cliquez sur le `+` à droite de la liste **Choisir des identifants**. Renseignez les champs nom, AWS Acces Key et AWS Secret Key,
```suggestion
5. Cliquez sur le `+` à droite de la liste **Choisir des identifants**. Renseignez les champs nom, AWS Access Key et AWS Secret Key, 
```

2021-08-04 12:27 UTC, chgautier approved these changes

2021-08-04 13:11 UTC, merged