add(epp): google workspace api proc - deprecate old google gsuite proc
centreon/centreon-documentation pull request #912
Opened 2021-08-02 13:38 UTC by garnier-quentin

## Description
-

## Target serie

- [X] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x (master)

2021-08-02 18:27 UTC, Sims24 requested changes

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +## Plugin-Pack assets
Plugin Pack

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +| status                          | status of the service                  |
uppercase ;)

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +2. On the Centreon Web interface, install the *Google Workspace* Centreon Plugin Pack on the "Configuration > Plugin Packs > Manager" page
s/Plugin Pack/Pack/

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +2. Install the Centreon Plugin Pack RPM on the Centreon Central server:
s/Plugin Pack/Pack/

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +3. On the Centreon Web interface, install the *Google Workspace* Centreon Plugin Pack on the "Configuration > Plugin Packs > Manager" page
s/Plugin Pack/Pack/

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +* Log into Centreon and add a new Host through "Configuration > Hosts".
Use bold for menus `**Configuration > Hosts**`

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +2. On the Centreon Web interface, install the *Google Workspace* Centreon Plugin Pack on the "Configuration > Plugin Packs > Manager" page
Use bold for menus `**Configuration > Hosts**`

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +3. On the Centreon Web interface, install the *Google Workspace* Centreon Plugin Pack on the "Configuration > Plugin Packs > Manager" page
Use bold for menus `**Configuration > Hosts**`

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +> Use the **Service Discovery** feature if you wish to get one Service per google workspace service.
Is it still true?

2021-08-02 18:27 UTC, Sims24 commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +A proxy connection may also be necessary to connect to the API.
Link to dedicated topic. 

Missing ## Troubleshooting header

2021-08-02 18:27 UTC, Sims24 commented on fr/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +
Apply EN recommendation unless troubleshooting one.

2021-08-03 14:06 UTC, garnier-quentin commented on en/integrations/plugin-packs/procedures/applications-google-workspace-api.md
> +> Use the **Service Discovery** feature if you wish to get one Service per google workspace service.
yes still true

2021-08-04 14:54 UTC, Sims24 approved these changes

2021-08-04 15:06 UTC, merged