Rework topic on notifications
centreon/centreon-documentation pull request #917
Opened 2021-08-06 07:04 UTC by cg-tw

## Description

Rework topic on notifications

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-08-16 08:12 UTC, tuntoja approved these changes

2021-08-24 15:14 UTC, thiuyendang requested changes

2021-08-24 15:14 UTC, thiuyendang commented on fr/alerts-notifications/notif-configuration.md
> +En effet, une notification ne peut être envoyé que suite à un contrôle. Par exemple, si vous décidez que les contrôles ont lieu toutes les heures mais que les notifications doivent être envoyées tout
```suggestion
En effet, une notification ne peut être envoyée que suite à un contrôle. Par exemple, si vous décidez que les contrôles ont lieu toutes les heures mais que les notifications doivent être envoyées toutes les 10 minutes, les notifications seront en réalité envoyées toutes les heures, car les contrôles ont lieu toutes les heures et non toutes les 10 minutes. 
```

2021-08-31 07:10 UTC, thiuyendang approved these changes

2021-09-06 13:52 UTC, omercier requested changes

2021-09-06 13:52 UTC, omercier commented on en/alerts-notifications/notif-configuration.md
> +### Contacts are not receiving notifications
```suggestion
### Contacts are not receiving notifications e-mails
```

2021-09-06 13:52 UTC, omercier commented on en/alerts-notifications/notif-configuration.md
> +### Contacts are not receiving notifications
This troubleshooting hint applies only if the notification channel is `e-mail`.

2021-09-07 08:38 UTC, cg-tw commented on en/alerts-notifications/notif-configuration.md
> +    If the option is set to **Default**, Centreon will use the value defined on the closest parent template. If no value is defined on any parent template, **Default** means **No**.
It depends on whether the contact has been configured to receive notifications (at host level)

2021-09-07 14:13 UTC, omercier requested changes
One last thing ;-)

2021-09-07 15:57 UTC, omercier approved these changes

2021-09-07 16:01 UTC, merged