Refresh topic on Plugin Packs
centreon/centreon-documentation pull request #946
Opened 2021-08-20 11:25 UTC by cg-tw

## Description

Refresh topic on Plugin Packs

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-08-20 17:29 UTC, tuntoja approved these changes

2021-08-21 16:32 UTC, chgautier requested changes

2021-08-21 16:32 UTC, chgautier commented on fr/monitoring/pluginpacks.md
> +3. Installez le plugin.
```suggestion
4. Installez le plugin.
```

2021-08-21 16:32 UTC, chgautier commented on en/monitoring/pluginpacks.md
> +(with an online or an offline license). Install the plugin on each poller that will execute the plugins.
```suggestion
(with an online or an offline license). Install the plugin on each poller that will execute the plugin checks.
```

2021-08-21 16:32 UTC, chgautier commented on en/monitoring/pluginpacks.md
>  > If you update the plugins on the Centreon central server, be sure also to update them on each poller.
```suggestion
> If you update the plugins on the Centreon central server, be sure to also update them on each poller.
```

2021-08-22 11:32 UTC, tuntoja approved these changes

2021-08-23 07:49 UTC, chgautier approved these changes

2021-08-23 07:59 UTC, merged