enh(release): Add Centreon Gorgone 21.0.4.2 RN
centreon/centreon-documentation pull request #961
Opened 2021-09-02 16:01 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-09-02 16:05 UTC, Nohzoh approved these changes

2021-09-03 12:48 UTC, thiuyendang approved these changes

2021-09-07 07:49 UTC, tuntoja requested changes

2021-09-07 07:49 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`September 9, 2021`

```

2021-09-07 07:49 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`9 Septembre 2021`

```

2021-09-07 07:49 UTC, tuntoja approved these changes

2021-09-07 07:50 UTC, merged