enh(release): Add Centreon Gorgone 20.10.5 RN
centreon/centreon-documentation pull request #962
Opened 2021-09-02 16:04 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-09-03 12:57 UTC, thiuyendang approved these changes

2021-09-07 08:32 UTC, tuntoja requested changes

2021-09-07 08:32 UTC, tuntoja commented on en/releases/centreon-core.md
> +
```suggestion

`September 7, 2021`

```

2021-09-07 08:32 UTC, tuntoja commented on fr/releases/centreon-core.md
> +
```suggestion

`7 septembre 2021`

```

2021-09-07 08:34 UTC, tuntoja approved these changes

2021-09-07 08:38 UTC, merged