enh(release): Add Centreon Web 21.04.5 RN
centreon/centreon-documentation pull request #981
Opened 2021-09-13 08:49 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x (master)

2021-09-13 15:58 UTC, thiuyendang requested changes

2021-09-13 15:58 UTC, thiuyendang commented on en/releases/centreon-core.md
> +- [OpenId] Secret token are displayed as password type
```suggestion
- [OpenId] Secret tokens obfuscation
```

2021-09-13 15:58 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +- [Platform Topology] Fixed using a FQDN for Parent address result as an error for topology
```suggestion
- [Platform Topology] Fixed an error that occurred when a FQDN was used as parent address
```

2021-09-13 15:58 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +- [OpenId] Secret token are displayed as password type
```suggestion
- [OpenId] Secret tokens obfuscation
```

2021-09-14 12:58 UTC, thiuyendang approved these changes

2021-09-14 16:17 UTC, chgautier requested changes

2021-09-14 16:17 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

`14 septembre 2021`

```

2021-09-14 16:17 UTC, chgautier commented on fr/releases/centreon-core.md
> +#### Bugfixes
```suggestion
#### Correctifs
```

2021-09-14 16:17 UTC, chgautier commented on fr/releases/centreon-core.md
> +#### Security fixes
```suggestion
#### Correctifs de sécurité
```

2021-09-14 16:17 UTC, chgautier commented on fr/releases/centreon-core.md
> +#### Enhancements
```suggestion
#### Améliorations
```

2021-09-14 16:17 UTC, chgautier commented on en/releases/centreon-core.md
> +- [Platform Topology] Fixed an error that occurred when a FQDN was used as parent address
```suggestion
- [Platform Topology] Fixed an error that occurred when an FQDN was used as parent address
```

2021-09-14 16:17 UTC, chgautier commented on fr/releases/centreon-core.md
> +- [Platform Topology] Fixed an error that occurred when a FQDN was used as parent address
```suggestion
- [Platform Topology] Fixed an error that occurred when an FQDN was used as parent address
```

2021-09-14 16:20 UTC, chgautier approved these changes

2021-09-14 16:20 UTC, merged