enh(release): Add Centreon Web 20.04.18 RN
centreon/centreon-documentation pull request #983
Opened 2021-09-13 08:55 UTC by lpinsivy

## Description

Please include a short resume of the changes and what is the purpose of the PR.

Any relevant information should be added to help reviewers.

## Target serie

- [x] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

2021-09-13 15:35 UTC, mdebauchez approved these changes

2021-09-13 15:59 UTC, thiuyendang requested changes

2021-09-13 15:59 UTC, thiuyendang commented on en/releases/centreon-core.md
> +- [OpenId] Secret token are displayed as password type
```suggestion
- [OpenId]  Secret tokens obfuscation
```

2021-09-13 15:59 UTC, thiuyendang commented on fr/releases/centreon-core.md
> +- [OpenId] Secret token are displayed as password type
```suggestion
- [OpenId]  Secret tokens obfuscation
```

2021-09-14 08:10 UTC, thiuyendang approved these changes

2021-09-14 13:02 UTC, chgautier approved these changes

2021-09-14 13:02 UTC, chgautier commented on en/releases/centreon-core.md
> +
```suggestion

`September 14, 2021`

```

2021-09-14 13:02 UTC, chgautier commented on fr/releases/centreon-core.md
> +
```suggestion

`14 septembre 2021`

```

2021-09-14 13:07 UTC, merged