Rework chapter on alerts and notifications
centreon/centreon-documentation pull request #991
Opened 2021-09-15 13:58 UTC by cg-tw

## Description

Improve chapter on alerts and notifications a little

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-10-04 18:30 UTC, thiuyendang approved these changes

2021-10-05 12:41 UTC, lpinsivy requested changes

2021-10-05 12:41 UTC, lpinsivy commented on fr/sidebars.json
> +                    "alerts-notifications/notif-flapping",
This is both times, first here but no present into table of contant and secondly in "Gérer les notifications"

2021-10-05 12:41 UTC, lpinsivy commented on en/sidebars.json
> +                    "alerts-notifications/notif-flapping",
This is both times, first here but no present into table of contant and secondly in "Managing alerts"

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/acknowledge.md
> +> the problem by a user of the supervision (and not the correction of
by a user of the monitoring?

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/acknowledge.md
> +1.  Go into the `Monitoring > Status Details > Hosts` (or `Services`)
1.  Go into the **Monitoring > Status Details > Hosts** (or **Services**)
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/acknowledge.md
> +<!--From real time monitoring-->
This is old page, we must explain from "Resources Status" icons

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/acknowledge.md
> +1.  Go into the `Monitoring > Status Details > Hosts` (or `Services`)
```suggestion
1.  Go into the **Monitoring > Status Details > Hosts** (or **Services**)
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/acknowledge.md
> +To delete the acknowledgment of an incident on an object:
We must explain from "Resources Status" page

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/downtimes.md
> +1.  Go into the `Monitoring > Status Details > Hosts` (or `Services`)
```suggestion
1.  Go into the **Monitoring > Status Details > Hosts** (or **Services**)
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/downtimes.md
> +<!--From real time monitoring-->
What about "Resources Status" page?

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/downtimes.md
> +1.  Go into the `Monitoring > Downtimes > Downtimes` menu
```suggestion
1.  Go into the **Monitoring > Downtimes > Downtimes** menu
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/downtimes.md
> +`Monitoring > Downtimes > Recurrent Downtimes` menu and click on
```suggestion
**Monitoring > Downtimes > Recurrent Downtimes** menu and click on
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/other.md
> +1.  Go into the `Monitoring > Downtimes > Comments` menu
```suggestion
1.  Go into the **Monitoring > Downtimes > Comments** menu
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/other.md
> +1.  Go into the `Monitoring > Status Details > Hosts` (or `Services`)
```suggestion
1.  Go into the **Monitoring > Status Details > Hosts** (or **Services**)
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/other.md
> +1.  Go into the `Monitoring > Status Details > Hosts` (or `Services`)
```suggestion
1.  Go into the **Monitoring > Status Details > Hosts** (or **Services**)
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/other.md
> +1.  Go into the menu: `Monitoring > Status Details > Hosts` (or
```suggestion
1.  Go into the menu: **Monitoring > Status Details > Hosts** (or
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/other.md
> +    `Services`)
```suggestion
    **Services**)
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/resources-status.md
> +title: Resources Status Page
```suggestion
title: Resources Status page
```

2021-10-05 12:41 UTC, lpinsivy commented on en/alerts-notifications/submit.md
> +### Practice
This can be done from "Resources Status" page or in details page of an object

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/acknowledge.md
> +1.  Rendez-vous dans le menu `Monitoring > Status Details > Hosts` (or
```suggestion
1.  Rendez-vous dans le menu **Monitoring > Status Details > Hosts** (or
```

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/acknowledge.md
> +    `Services`) menu
```suggestion
    **Services**) menu
```

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/acknowledge.md
> +<!--From real time monitoring-->
what about from "Resources Status page"?

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/acknowledge.md
> +1.  Rendez-vous dans le menu `Monitoring > Status Details > Hosts` (or
```suggestion
1.  Rendez-vous dans le menu **Monitoring > Status Details > Hosts** (or
```

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/acknowledge.md
> +    `Services`) menu
```suggestion
    **Services**) menu
```

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/downtimes.md
> +<!--DOCUSAURUS_CODE_TABS-->
What about "Resource Status" page?

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/downtimes.md
> +1.  Rendez-vous dans le menu `Monitoring > Status Details > Hosts` (ou
```suggestion
1.  Rendez-vous dans le menu **Monitoring > Status Details > Hosts** (ou
```

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/downtimes.md
> +    `Services`)
```suggestion
    **Services**)
```

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/downtimes.md
> +1.  Rendez-vous dans le menu `Monitoring > Downtimes > Downtimes`
```suggestion
1.  Rendez-vous dans le menu **Monitoring > Downtimes > Downtimes**
```

2021-10-05 12:41 UTC, lpinsivy commented on fr/alerts-notifications/submit.md
> +### En pratique
This can be done also from "Resource Status" page

2021-10-05 13:27 UTC, cg-tw commented on en/alerts-notifications/acknowledge.md
> +> the problem by a user of the supervision (and not the correction of
```suggestion
> the problem by a user of the monitoring (and not the correction of
```

2021-10-05 15:45 UTC, lpinsivy approved these changes

2021-10-05 15:48 UTC, lpinsivy approved these changes

2021-10-05 15:54 UTC, merged