Add missing translation
centreon/centreon-documentation pull request #992
Opened 2021-09-15 15:36 UTC by cg-tw

## Description

Add missing translation

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-09-15 15:41 UTC, zaouchelo approved these changes

2021-09-17 14:01 UTC, chgautier requested changes

2021-09-17 14:01 UTC, chgautier commented on fr/graph-views/secure-your-map-platform.md
> +To create self-signed certificate, you can create one using the following commands:
```suggestion
To create a self-signed certificate, you can use the following commands:
```

2021-09-17 14:01 UTC, chgautier commented on fr/graph-views/secure-your-map-platform.md
> +And then, copy the private key and the certificate into **/etc/centreon/broker_cert/** directory:
```suggestion
And then, copy the private key and the certificate into the **/etc/centreon/broker_cert/** directory:
```

2021-09-17 14:57 UTC, chgautier approved these changes

2021-09-17 14:58 UTC, merged